### ISSUE TITLE
ZSTD_DCtx_refDDict unimplemented

### ISSUE THREAD

**Issue by jeromectm** [facebook/zstd#1002]
Hello,
I'm using ZSTD_compress_generic after calling ZSTD_CCtx_refCDict.
However I can't decompress using ZSTD_decompress_generic, as ZSTD_DCtx_refDDict is still unimplemented. Is it planned to implement it? How can I decompress the data using the generic API?

**Comment by Cyan4973** [comment]
You are right @jeromectm, the `ZSTD_decompress_generic()` interface is not completed yet, and especially misses ingredients for dictionary decompression.

You can currently decompress such data with : 
- [`ZSTD_decompress_usingDDict()`](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L241) : single pass decompression
- [`ZSTD_initDStream_usingDDict()`](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L741) : initialization for streaming decompression

**Comment by Cyan4973** [comment]
Missing advanced dictionary functions have been implemented in latest `dev` branch update

**Comment by jeromectm** [comment]
Thanks :)
