### ISSUE TITLE
Rabin chunking for more aggressive compression?

### ISSUE THREAD

**Issue by wurp** [facebook/zstd#1003]
Feature suggestion: See if adding Rabin chunking will give better compression ratios.

There is a Rabin tool that supports file compression at https://github.com/wurp/rabin-tool/wiki

Rabin chunking is a method of breaking up data in a repeatable way. One property Rabin chunks have is that if a long enough piece of data is repeated, most of the repeated data will be broken into chunks in the same way. This means if you use content based addressing to store the chunks, repeated data only gets stored once.

**Comment by gyscos** [comment]
This sounds like it belongs in a higher-level tool than zstd, more like [borg](https://github.com/borgbackup/borg) or [casync](https://github.com/systemd/casync), which do exactly that (and for casync, they even use zstd to compress each chunk).

**Comment by wurp** [comment]
Nice, I didn't know about either of those!

**Comment by Cyan4973** [comment]
I agree with @gyscos on this,
this feature is indeed very useful to update large data sets,
it is probably positioned best in a product dedicated for this usage.
It's always possible to combine `zstd` with a specific filter, but the appropriate filter to select is data or scenario dependent.

On a lighter note, note that the `--long` mode use some equivalent techniques to find long range matches at long distance while keeping a reasonably memory budget.
