### ISSUE TITLE
How to know when to provide more input data

### ISSUE THREAD

**Issue by RobertFromBerlin** [facebook/zstd#1012]
Hi,

reading the documentation of ZSTD_decompressStream() it is not clear to me when I have to present new input data.

When reading I have a fixed size input buffer to fill with at least minReadCount bytes:

    output.dst = someBufferToFill; // After decompressing this must contain at least minReadCount bytes
    output.size = someBufferSize;  // someBufferSize > minReadCount
    output.pos = 0;

    while (output.pos < minReadCount) 
    {
        if (cannotDecode && zinBuffer->pos == zinBuffer->size)
        {
            // When to do this? 
            // This can block so I cannot do it when there is still some data in the internal buffer
            ReadNewInputBufferFromSocket(zinBuffer);
        }

        if (ZSTD_isError(toDecode = ZSTD_decompressStream(zContext, &output, zinBuffer)))
        {
            return ERROR;
        }

        cannotDecode = output.pos < output.size;
    }

But this looks weird so I cannot be right ;-)

Robert

**Comment by Cyan4973** [comment]
A zstd-compressed object is transformed into one or multiple "frames",
though in the general case, it is a single frame.

`ZSTD_decompressStream()` will return `0` [when a frame is completed and fully flushed](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L339).
Until then, keep providing more input, and ensure there is some room left in `output` buffer to flush the decompressed object.

If you provide more input than necessary to complete a frame, `ZSTD_decompressStream()` will simply stop reading at the exact end of the frame (read `zinBuffer->pos` value).

**Comment by RobertFromBerlin** [comment]
I only wanted to say that we recently evaluated several compression libraries. The performance of Zstandard in terms of every metric was outstanding. Additionally we love the code and the SDK including the documentation. But I guess I don't tell news here ;-)

Great work!
