### ISSUE TITLE
Examples fail to compile: Undefined reference errors

### ISSUE THREAD

**Issue by dnbaker** [facebook/zstd#1016]
Hi,

I'm planning to link some of my code against zlibWrapper so that I don't have to recompile my project in order to use your work.

I'm simply attempting to compile the examples after successfully compiling the main project and executables:

`cd zlibWrapper && make example`:

```
/cm/shared/gcc/7.1.0/bin/gcc  examples/example.o zstd_zlibwrapper.o gzclose.o gzlib.o gzread.o gzwrite.o ../lib/libzstd.a -lz -o example
zstd_zlibwrapper.o: In function `z_deflatePending':
zstd_zlibwrapper.c:(.text+0x159a): undefined reference to `deflatePending'
zstd_zlibwrapper.o: In function `z_inflateReset2':
zstd_zlibwrapper.c:(.text+0x1be4): undefined reference to `inflateReset2'
zstd_zlibwrapper.o: In function `z_inflateMark':
zstd_zlibwrapper.c:(.text+0x1e16): undefined reference to `inflateMark'
zstd_zlibwrapper.o: In function `z_inflateGetDictionary':
zstd_zlibwrapper.c:(.text+0x1fb4): undefined reference to `inflateGetDictionary'
collect2: error: ld returned 1 exit status
make: *** [example] Error 1

```

gcc version: 7.1.0
installed zlib version: 1.2.8
zstd commit: 7117ea8bec496bfc46828b272a3854644a281da5

After checking missing functions' header guards, I find that the functions are being called.

(z_inflateGetDictionary is being compiled, as shown by a `#pragma message("Zlib version new enough")` being compiled, for example.

I understand that some of these functions aren't supported, but I'd expect them to link but fail at runtime if called.

Might you be able to point me in a right direction?

Thank you!

**Comment by Cyan4973** [comment]
Hi @dnbaker ,

I'm sorry, for some reason, I'm unable to reproduce your result.
I tested `make example` on both a Linux and OS-X systems, they both work fine, without a single warning.

Hence it's a bit more difficult to understand what could go wrong on your system.
My first hazardous investigation would be on the zlib version used (maybe there are multiple versions installed). Are you certain the version being linked to is 1.2.8 ?

**Comment by dnbaker** [comment]
Thanks for your help!

Sorry, I was mistaken. I had thought that I'd solved an error with the module system on our cluster, but you're right, and it was a linking issue.
