### ISSUE TITLE
Give more context on bad inputs than messages like "Corrupted block detected"

### ISSUE THREAD

**Issue by mvdan** [facebook/zstd#1027]
This can be restricted to when one or many levels of `-v` has been enabled.

For example, I manually crafted a simple frame with an RLE block, but I obviously messed up somehow:

```
$ hexdump block_rle.zst
0000000 b528 fd2f 3324 004b 4100 689f 81e0
000000e
$ zstd -d <block_rle.zst
/*stdin*\ : Decoding error (36) : Corrupted block detected
$ zstd -d -v -v <block_rle.zst
*** zstd command line interface 64-bits v1.3.3, by Yann Collet ***
Using stdout for output
Sparse File Support is automatically disabled on stdout ; try --sparse
Using stdin for input
/*stdin*\ : Decoding error (36) : Corrupted block detected
```

But the educational_decoder accepts it, funnily enough:

```
$ harness block_rle.zst /dev/stdout
AAAAAAAAA
```

I understand that the educational decoder is lacking some features, like xxhash checksums. And this isn't really a bug report for the educational decoder (but it could also be). I just wish that `-v -v` told me exactly what was wrong with the zstd block - be it a reserved bit that was set, missing bytes, et cetera.

**Comment by mvdan** [comment]
Also - bonus points if "corruption" errors included an offset, so that I could quickly spot the byte containing the issue.

**Comment by Cyan4973** [comment]
This would be a nice feature indeed, but unfortunately, I don't see it coming soon.

The current error system is limited to a list of enums, which can be [consulted here](https://github.com/facebook/zstd/blob/dev/lib/common/zstd_errors.h). As you can see, there is more to it than just `corruption detected`, but it's still much less granular than what you request.

The error reporting system is everywhere. A lot of things can break, starting with memory allocation, invalid API usage, etc.. So it's not limited to invalid input.
While you see the errors from a "command line interface" perspective, the error system is primarily developed from an API perspective : it must be simple and clear enough to be integrated by many programs and languages.

What you request seems to require a full analysis of the bad frame, to generate a detailed report. While this looks certainly possible in theory, it also feels like a dedicated tool.

**Comment by mvdan** [comment]
Thanks for the reply. I had seen the enum values, but had not considered how this is all required to fit in a portable and language-agnostic API.

With that in mind, I'd repurpose this issue as "please expand ZSTD_ErrorCode with more values" and "please consider adding offsets to some/most errors". Perhaps either or both of those are more attainable than higher-level, fully-featured error structures made simpler to understand for humans.

In my particular case, an error code that is more narrow than "corrupted block" would have helped, especially if accompanied by a byte offset.

**Comment by Cyan4973** [comment]
Currently this request doesn't match our error reporting model. It probably never will. There are fundamental limitations which make it impossible / undesirable to support "arguments" on top of error codes.

Creating a dedicated tool to detail where a decoding error happened and what the error is, sounds more likely possible.
Though it's a fairly involved effort, for a limited audience.
It might nonetheless be achieved, as a later extension of the "educational decoder" project.

**Comment by Brain2000** [comment]
I found a "corrupted block" error in ZSTD_decompressStream( ) when compressing on one side, sending it across a lan, and decompressing it on the other. Unfortunately, it can take a terabyte or two of data before this shows up, and generally happens only when the network is congested. This may suggest that varying the source size when calling ZSTD_decompressStream( ) may be missing a size check.

I think DEBUGLOG might help me where things are going wrong? If that's true, is there a function to enable DEBUGLOG, or do I need to recompile it with DEBUGLEVEL > 0?

**Comment by Cyan4973** [comment]
Yes, in order to enable runtime checks and debug messages,
`zstd` or `libzstd` must be compiled with build macro `DEBUGLEVEL`, giving it a positive value.
`1` will enable `assert()` only,
then larger values will enable more and more debug messages, up to the point of being very and even extremely verbose.

Considering the issue mentioned seems to involve transferring a large amount of data over a congested network, it could be useful to also ensure that the network layer itself is performing as expected, not dropping nor modifying order of received packets.

**Comment by Brain2000** [comment]
@Cyan4973 Good thinking, that was the first thing I checked, and the only thing I could find between tests was a variance in size of the input buffers (this particular test uses TCP, so packet drops or re-orders are handled at the layer 4 protocol).
