### ISSUE TITLE
Does anynone know how to skip this compile error?

### ISSUE THREAD

**Issue by jackswan** [facebook/zstd#1030]
make
cc -O3   -I. -I./common -DXXH_NAMESPACE=ZSTD_ -I./legacy -DZSTD_LEGACY_SUPPORT=4  -c -o compress/huf_compress.o compress/huf_compress.c
In file included from compress/huf_compress.c:454:
compress/huf_compress_impl.h:35: error: attribute(target("bmi2")) is unknown
compress/huf_compress_impl.h:81: error: attribute(target("bmi2")) is unknown
make: *** [compress/huf_compress.o] Error 1

**Comment by Cyan4973** [comment]
Which compiler are you using ?
(`cc -v`)

**Comment by jackswan** [comment]
gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) has the problem.
It is ok with gcc version 4.8.3
