### ISSUE TITLE
Github generated tarballs change randomly

### ISSUE THREAD

**Issue by bket** [facebook/zstd#1040]
As the title states, github generated tarballs can change at any point. This creates issues for packaging on systems like [OpenBSD](https://marc.info/?l=openbsd-ports&m=151973450514279&w=2) ports. Would it be possible to get official tarballs created / attached to releases?

**Comment by Cyan4973** [comment]
Isn't that the point of tagging [official releases](https://github.com/facebook/zstd/releases) ?

**Comment by bket** [comment]
It seems that this project currently provides auto generated tarballs (tagged source code releases), which are not guaranteed to be stable, they can change as GitHub update software and caches expire. Due to local caches at the GitHub clusters, these files can be different depending on which cluster you're connecting to.

Alternative to the above is to use GitHub's releases infrastructure and upload "normal"
generated distfiles which are not then subject to change.

**Comment by Cyan4973** [comment]
OK, so the content of a link like https://github.com/facebook/zstd/archive/v1.3.3.tar.gz is not guaranteed to remain stable overtime, and may change depending on location and time ?
That's an issue I was not aware of.
Plus, I guess  it's pretty hard to observe too.

This is an unfortunate, and not very publicized, github limitation.
We'll have to think how we want to handle it.
Maybe uploading a tarball we generate ourselves, as you suggest, could be a solution.

**Comment by Varunram** [comment]
Not directly related, but the same goes with the length of commit hashes too, the length that GitHub keeps changing from time to time.

**Comment by Conan-Kudo** [comment]
@Cyan4973 Those URLs are generated by `git archive` runs internally, and they are not considered stable because `git archive` can change over the course of git releases.

**Comment by Cyan4973** [comment]
Starting v1.3.4, a tarball archive of zstd source code is uploaded as an attached file of the release,
alongside its sha256 signature.
