### ISSUE TITLE
[PATCH] CMakelist's fixes and addons.

### ISSUE THREAD

**Issue by Ne01eX** [facebook/zstd#1043]
This patch provides variables set for correct build zstd package on most unix platforms.

[zstd-1.3.3.cmake_fix-rtklinux-1.patch.gz](https://github.com/facebook/zstd/files/1808459/zstd-1.3.3.cmake_fix-rtklinux-1.patch.gz)

Best regards, Aleksandr "Ne01eX" Sayfulin

**Comment by Cyan4973** [comment]
Thanks for this proposed patch @Ne01eX .

Any change this can become a PR ?

**Comment by Ne01eX** [comment]
Yes, this may be used for PR ZSTD. :-)

**Comment by Varunram** [comment]
@Ne01eX most of the changes were related to newline formatting, so I left them as is, I'll be putting in a PR shortly with the changes that aren't related to formatting and you can review it if desired. Thanks
