### ISSUE TITLE
ambiguous license re gpl2 and gpl2+

### ISSUE THREAD

**Issue by pixelb** [facebook/zstd#1046]
Some ancillary files specify "any later version"

```
$ find -type f | xargs grep -Fl 'later version'
./tests/gzip/z-suffix.sh
./tests/gzip/keep.sh
./tests/gzip/zgrep-context.sh
./tests/gzip/test-driver.sh
./tests/gzip/memcpy-abuse.sh
./tests/gzip/hufts.sh
./tests/gzip/zgrep-f.sh
./tests/gzip/list.sh
./tests/gzip/trailing-nul.sh
./tests/gzip/zgrep-signal.sh
./tests/gzip/znew-k.sh
./tests/gzip/null-suffix-clobber.sh
./tests/gzip/zdiff.sh
./tests/gzip/gzip-env.sh
./tests/gzip/stdin.sh
./tests/gzip/unpack-invalid.sh
./tests/gzip/init.sh
./tests/gzip/helin-segv.sh
./tests/gzip/help-version.sh
./tests/gzip/mixed.sh
./contrib/linux-kernel/0006-squashfs-tools-Add-zstd-support.patch
./contrib/linux-kernel/0004-squashfs-Add-zstd-support.patch
./contrib/linux-kernel/fs/squashfs/zstd_wrapper.c

```

**Comment by Cyan4973** [comment]
`/tests/gzip/` files come from `gzip` project, verbatim.
So they come with their license.
Is that a problem ?
I'm not sure what to do about it.

**Comment by pixelb** [comment]
Ah right. Stuff copied from other projects should be fine.
This was prompted by the license being changed from GPLv2 to GPLv2+ in the Fedora package.
I was wondering what might have prompted that, and guessed there was some erroneous matching on these files. I'll sort out the Fedora license, and I don't see a need to change these files from externals projects. cheers
