### ISSUE TITLE
'total.windowSize' is used uninitialized in this function

### ISSUE THREAD

**Issue by tsoome** [facebook/zstd#1070]
cc1: warnings being treated as errors
zstd/programs/fileio.c: In function 'FIO_addFInfo':
zstd/programs/fileio.c:1927: error: 'total.windowSize' is used uninitialized in this function [-Wuninitialized]
*** Error code 1

Suggest declaring total = { 0 }; to get unreferenced fields set.

**Comment by Cyan4973** [comment]
Thanks for report @tsoome .

How (with which tool) have you generated this warning ?

Also, which zstd version are you testing ?
I believe this warning has been fixed in `dev` branch.

**Comment by tsoome** [comment]
gcc 7 in that particular case and 1.3.3.

**Comment by Cyan4973** [comment]
> gcc 7 in that particular case and 1.3.3.

Problem is, I've been compiling zstd v1.3.3 using gcc 7
on both OS-X and Linux platforms,
none of them produce this warning.

Therefore, I can't verify on my side if `dev` branch fix this warning.

**Comment by tsoome** [comment]
Oh, sorry, I did confuse things, it is reported by gcc 4.4.4, and indeed not reported by gcc 6 and gcc 7.
However, while looking on that function, I am puzzled because we return local struct which is gone as soon as we return from FIO_addFInfo().... Since the local variable is gone, it is understandable the gcc 6 and 7 are not complaining...

**Comment by Cyan4973** [comment]
tested with `gcc 4.4.7` on `centOS6`,
and it still doesn't produce the mentioned warning.

Anyway, I believe the issue was fixed in 606374269cf3485972c90b993fbb84dc20da032f,
so the only thing I can recommend is to test the `dev` branch on your target system.

**Comment by tsoome** [comment]
Yes, it does fix the issue.
