### ISSUE TITLE
static suffix list displayed regardless of actual support

### ISSUE THREAD

**Issue by pdknsk** [facebook/zstd#1083]
```Bash
$ unzstd FILE.bogus
zstd: FILE.bogus: unknown suffix (.gz/.xz/.zst/.lzma/.lz4 expected) -- ignored
$ unzstd FILE.gz 
zstd: FILE.gz: gzip file cannot be uncompressed (zstd compiled without HAVE_ZLIB) -- ignored
```

**Comment by haneefmubarak** [comment]
@Cyan4973 I think I'd like to take this on - is there a separate CLA for this project or is the standard Facebook CLA all (have signed that already)?

**Comment by Cyan4973** [comment]
There's only one CLA.
Since you already signed it, you are free to go !

**Comment by Cyan4973** [comment]
fixed in https://github.com/facebook/zstd/pull/1159
