### ISSUE TITLE
How about sharing thread pools across contexts?

### ISSUE THREAD

**Issue by stati64** [facebook/zstd#1097]
Would this let multiple streams or blocks coexist with less dissonance?

**Comment by Cyan4973** [comment]
I don't think it would bring any tangible benefit, neither speed nor memory wise,

but, on the other hand, it would markedly increase code complexity,
as it would introduce some "invisible shared object" between contexts.

**Comment by terrelln** [comment]
Zstd isn't the right place to maintain a "global" thread pool. However, we could potentially use an external thread pool. Now that zstdmt allocates a single memory chunk for the input buffer, I think it is no longer dependent on the size of the thread pool for correctness (or close to independent).

Is this an issue you are running into in practice? If so can you provide some details?

**Comment by marxin** [comment]
I see a similar need for `rpm`. Right now `rpm` creates packages in a parallel way (using openmp) where each of the `.rpm` files is then compressed. I added support for parallel compression, but it may lead to thread explosion as one can process N `.rpm` files each being compressed with N threads in `zstd`.
Maybe it would be handy to have a semaphore API where the compressing thread in `zstd` would need to acquire it?
