### ISSUE TITLE
Detecting truncated streams

### ISSUE THREAD

**Issue by cemeyer** [facebook/zstd#1109]
Hi,

zlib has a nice feature where the decompressor (`inflate`) returns `Z_STREAM_END` at the end of the stream.  This works when zlib is used with or without the gzip framing (an "undocumented" feature accessed by passing a negative window size).  The method is not zlib-specific and is a part of [the DEFLATE standard: a special bit `BFINAL` is set on the final frame](https://www.ietf.org/rfc/rfc1951.txt).  (In zlib [it is referred to as `inflate_state::last`](https://github.com/madler/zlib/blob/master/inflate.c#L858).)

This is useful for determining if a DEFLATE stream has been truncated.  Without the bit, it is impossible to determine whether a stream ending at a frame boundary is truncated or not.  It would be nice if Zstd provided similar functionality.  I may be mistaken, but as far as I can tell Zstd does not expose truncated vs not to the user via `ZSTD_decompressStream()` (and may lack the metadata, although I have not investigated).

**Comment by terrelln** [comment]
`ZSTD_decompressStream()` [returns 0](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L339) exactly when the frame is complete.

**Comment by cemeyer** [comment]
@terrelln Right.  But a stream may have multiple frames, right?  It returns 0 every time a frame is completely decoded — not just for the final frame.  Maybe I misunderstand?

**Comment by cemeyer** [comment]
Ah, perfect!  I was confused by the terminology gap.   With the key "zlib stream = zstd frame; zlib frame = zstd block", your initial response makes sense.  Sorry about the noise!

It looks like `ZSTD_compressEnd()` is invoked via `ZSTD_endStream` -> `ZSTD_compressStream_generic`.

Thank you.
