### ISSUE TITLE
Non-regular file removal test fails on GNU/Hurd

### ISSUE THREAD

**Issue by mestia** [facebook/zstd#1116]
While building zstd on GNU/Hurd the following test fail:
> skip>
> 
>test : file removal
>
> Read : 0 / 0 MB ==> 32% 
>                                                                                
> tmp                  : 32.42%   ( 65537 =>  21246 bytes, tmp.zst) 
> 
> tmp.zst              : 0 MB...     
>                                                                                
> tmp.zst             : 65537 bytes 
> test : should quietly not remove non-regular file
> Makefile:306: recipe for target 'zstd-playTests' failed
> make[3]: *** [zstd-playTests] Error 1

The complete build log lives [here](https://buildd.debian.org/status/fetch.php?pkg=libzstd&arch=hurd-i386&ver=1.3.4%2Bdfsg-2&stamp=1525276222&raw=0).
Any idea what might be wrong there? Thanks!

**Comment by terrelln** [comment]
@mestia does `/dev/zero` exist on GNU/Hurd?

We need to test writing to some non-regular that isn't `/dev/null`, since we special case `/dev/null`.

If `/dev/zero` doesn't exist, we need to add another case [here](https://github.com/facebook/zstd/blob/dev/tests/playTests.sh#L64) to special case GNU/Hurd, and it must be a non-regular file (where [this line](https://github.com/facebook/zstd/blob/dev/programs/util.h#L293) gets triggered).

**Comment by terrelln** [comment]
Nice catch! It should be `$INTOVOID`. Since the `grep` succeeds the pipeline exists okay, but I guess GNU/Hurd still fails when `zstd` fails but `grep` succeeds.

**Comment by mestia** [comment]
Sorry for coming back, but I realized that the actual issue is still there.
```
$ZSTD tmp -f -o /dev/zero; echo $?
tmp                  :316.67%   (     6 =>     19 bytes, /dev/zero)
zstd: /dev/zero: (os/kern) successful
zstd: Refusing to remove non-regular file /dev/zero
1
```
The test in the line [176](https://github.com/facebook/zstd/blob/dev/tests/playTests.sh#L176) fails.

Simply echoing to /dev/zero on Gnu/Hurd produces the same error:
```
echo test > /dev/zero; echo $? 
echo: write error: (os/kern) successful
1
```
I guess this is some kernel specific feature on this architecture.
On amd64 host it works just fine.

Also I don't understand how this snippet suppose to work at all:
```
$ZSTD tmp -f -o "$DEVDEVICE" 2>tmplog > "$INTOVOID"
grep -v "Refusing to remove non-regular file" tmplog
rm -f tmplog
```
if $ZSTD command fails with a non-zero exit code then playTests.sh will fail, if it works, then grep below makes no much sense to me.

A non-regular files supporting writing on Hurd without complaining are `/dev/random` or `/dev/urandom`

**Comment by terrelln** [comment]
Thanks @mestia, that should work. Writing to `/dev/random` seeds the entropy pool, so it is perfectly fine.
