### ISSUE TITLE
Retrieving content size of message while using a pre-computed dictionary

### ISSUE THREAD

**Issue by braibant** [facebook/zstd#1156]
Hi,

I am looking at an application of zstd using the bulk processing dictionary API, but have issues finding how to evaluate the required size to decompress messages using this API. 
 
Here are three leads I followed, unsuccessfully:

- From experiments, it does not look like one can use  `ZSTD_getFrameContentSize` to retrieve an upper bound on the message size (and I would imagine that one would need to pass the dictionary to that function -- or a similar one -- to get meaningful results).

- One could imagine using `ZSTD_decompress_usingDict` to decompress in a buffer, and if this fails, allocate a bigger buffer and retry. To do this properly, I would need to test the error code returned by   `ZSTD_decompress_usingDict`, but these error codes are not documented in the stable part of zstd.h.

- It does not seem possible to use the streaming API when using a pre-computed dictionary (but from an API point of view, this would be tremendously useful).

A working work around is to have an upper bound on the size of the messages that were compressed using the dictionary, but it's not very practical. I would appreciate any pointers on how to deal with this issue. 

Thanks in advance

**Comment by Cyan4973** [comment]
The recommended function for bulk processing dictionary API is [`ZSTD_compress_usingCDict()`](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L216).
The resulting compressed frame should work fine with `ZSTD_getFrameContentSize()`, which shall provide original size. If it doesn't, it's a bug, worth a report.
The corresponding decoding function is `ZSTD_decompress_usingDDict()`.

Since these function names do not seem to appear in your description, I'm wondering what you are trying to do, and how you are trying to achieve it.

**Comment by braibant** [comment]
Thanks for your reply. To give you more context, I am working on bindings for zstd in OCaml. In the example I am building to test the bindings, I am indeed using `ZSTD_compress_usingCDict` and `ZSTD_compress_usingDDict` (apologies for the mistake in the initial comment). Testing `ZSTD_getFrameContentSize`, I can't unfortunately reproduce the issue where I was getting `ZSTD_CONTENTSIZE_UNKNOWN` right now. I will keep that in mind and open a dedicated issue if needed.

Re-reading the documentation of `ZSTD_getFrameContentSize()` now, it might be worth highlighting in the notes that it works for frames encoded with the dictionary APIs?

Thanks again for your help solving this (non) issue.

**Comment by Cyan4973** [comment]
code comment in `zstd.h` updated
