### ISSUE TITLE
Can I pick between the BSD license and the GPLv2 license?

### ISSUE THREAD

**Issue by Mike4Online** [facebook/zstd#1181]
According to[ Wikipedia's article on multi-licensing](https://en.wikipedia.org/wiki/Multi-licensing), software can be published under a dual-license whereby BOTH licenses must be adhered to.  Your GitHub readme.md file does not clearly indicate whether both licenses always apply, or whether I can pick (e.g. BSD over GPLv2).  Please clarify.

Thanks

**Comment by Cyan4973** [comment]
This is the simpler case : 
"When software is multi-licensed, recipients can typically choose the terms under which they want to use or distribute the software"

It's also specified at the top of each file : 
https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L8
> You may select, at your option, one of the above-listed licenses.
