### ISSUE TITLE
C++ binding available for Zstandard?

### ISSUE THREAD

**Issue by Mike4Online** [facebook/zstd#1182]
The [list of language bindings](http://facebook.github.io/zstd/#other-languages) indicates the reference implementation is C, but a C++ wrapper is not listed.  Is a C++ wrapper available?

**Comment by Cyan4973** [comment]
The source code is directly compatible with C++ compilers.
This is tested regularly with `make cxxtest` : 
https://github.com/facebook/zstd/blob/dev/Makefile#L185
