### ISSUE TITLE
Does Zstandard take advantage of SIMD instructions when present?

### ISSUE THREAD

**Issue by Mike4Online** [facebook/zstd#1183]
Fro the documentation, I cannot tell whether Zstandard automatically leverages MMX, SSE, AVX and similar instruction set extensions when they are present.

**Comment by Cyan4973** [comment]
This depends on your compiler.
The code does not contain any intrinsic, 
but it can be auto-vectorized by compilers.
Some functions have been written in a friendly way for auto-vectorizer, but they do not represent a large fraction of cpu usage.
The core functionality is designed to take advantage of Out-of-Order execution, achieving typically 3-4 uops/clock, but that's still not wide enough to make optimized use of vectorized units.
