### ISSUE TITLE
Assert when ZSTD_HEAPMODE=0

### ISSUE THREAD

**Issue by andrewe-playrix** [facebook/zstd#1186]
```
size_t ZSTD_decompress(void* dst, size_t dstCapacity, const void* src, size_t srcSize)
{
#if defined(ZSTD_HEAPMODE) && (ZSTD_HEAPMODE>=1)
    size_t regenSize;
    ZSTD_DCtx* const dctx = ZSTD_createDCtx();
    if (dctx==NULL) return ERROR(memory_allocation);
    regenSize = ZSTD_decompressDCtx(dctx, dst, dstCapacity, src, srcSize);
    ZSTD_freeDCtx(dctx);
    return regenSize;
#else   /* stack mode */
    ZSTD_DCtx dctx;
    return ZSTD_decompressDCtx(&dctx, dst, dstCapacity, src, srcSize);
#endif
}
```
I think that context is not properly initialized for a stack mode.
Release build occasionly works, but debug asserts in ZSTD_startingInputLength
`    assert( (format == ZSTD_f_zstd1) || (format == ZSTD_f_zstd1_magicless) );
`

**Comment by Cyan4973** [comment]
You are right @andrewe-playrix .
This structure is not properly initialized.

`ZSTD_HEAPMODE =0` is something we don't test usually, so this error could creep in.
I guess not initializing `dctx` used to be fine when this option was created.
But today it no longer is, as the scope an features have expanded.

Fix under way.

**Comment by Cyan4973** [comment]
Fix merged into `dev` branch.
It will be part of next release.
