### ISSUE TITLE
API Equivalent of zstd --train?

### ISSUE THREAD

**Issue by atris** [facebook/zstd#1195]
Hi,

I am looking forr an API equivalent of zstd --train that can generate a dictionary given an input set of files. Is there a functionality like that today?

**Comment by Cyan4973** [comment]
do you mean [`zdict.h`](https://github.com/facebook/zstd/blob/dev/lib/dictBuilder/zdict.h) ?

**Comment by atris** [comment]
That seems like what I need, I will try it and post again if I am stuck
