### ISSUE TITLE
`ZSTD_STATIC_ASSERT()` crashes AIX's XL 9.0.0 compiler

### ISSUE THREAD

**Issue by mitchblank** [facebook/zstd#1209]
I have a need to compile zstd using an old version of IBM's C compiler (it's a long story...)  Frustratingly when compiling zstd_decompress.c a compiler stage was apparently crashing, causing `xlc_r` to exit with status code 251.  No diagnostic message, no core dump, just exits.

After much experimentation I found that the cause was the two occurrences of the line:
```
            ZSTD_STATIC_ASSERT(LONG_OFFSETS_MAX_EXTRA_BITS_32 == 5);
```

What's odd about this is:
* All of the other usages of the `ZSTD_STATIC_ASSERT()` macro compiled without problems
* The value of `LONG_OFFSETS_MAX_EXTRA_BITS_32` actually *is* 5, verified with a `printf()`.

So for some reason that expression is poking some bug in this compiler.  FWIW, I was able to compile a static library (and run `zstreamtest` successfully) by changing the implementation of the `ZSTD_STATIC_ASSERT()` macro on this compiler:
```
#ifdef __xlc__
#  define ZSTD_STATIC_ASSERT(c) { extern char static_assertion[(c) ? 1 : -1]; }
#else
#  define ZSTD_STATIC_ASSERT(c) { enum { ZSTD_static_assert = 1/(int)(!!(c)) }; }
#endif
```
AIX would need more work to build a shared library I expect, but I didn't need that.

I don't know whether this is worth upstreaming, since I don't even know if it affects a modern version of the same compiler.  I just wanted to leave a report in case someone else trips over the same problem.

**Comment by Cyan4973** [comment]
Thanks for report @mitchblank .

I initially thought that, if target compiler is _really_ old, it could have been an issue with macro name _length_, since `LONG_OFFSETS_MAX_EXTRA_BITS_32` is pretty long. 
But since compiler works fine with your updated version of `ZSTD_STATIC_ASSERT()`, I guess it's more likely a bug in the compiler.

I'm not opposed to a change of `ZSTD_STATIC_ASSERT()` if it can help, as long as it's not detrimental to other targets. Your suggested version looks clean, easy to follow. I would expect any compiler to compile it fine.

So I guess we can adopt it.

**Comment by Cyan4973** [comment]
mmmh, wait it introduces `-Werror=unused-variable` warning ...

**Comment by mitchblank** [comment]
Yeah, it might not be the best overall option for a static-assert macro that is used inside of a function body.  I've used that pattern many times for checks placed at global-scope.

**Comment by Cyan4973** [comment]
maybe coupled with some `sizeof()` ?

**Comment by Cyan4973** [comment]
`(void)sizeof(char[(c) ? 1 : -1])` seems to work fine,
though it's not possible to use that at global scope.
( But we were not anyway, due to the use of `{ ... }`. )

Would it also work for your AIX target ?

**Comment by mitchblank** [comment]
Yeah, that works fine.  It also correctly stops the compile if I put in a failing assertion.

I only wonder if there are any compilers that would still warn about unused value even with the `(void)` cast... hopefully not?

**Comment by Cyan4973** [comment]
Thanks for feedback @mitchblank .
The `(void)` should take care of that. 
We already use `(void)variable` in many places throughout the code, it works well, and has proven portable so far.

**Comment by Cyan4973** [comment]
new version merged in `dev`
