### ISSUE TITLE
Make Zstd Tests Parallelizable

### ISSUE THREAD

**Issue by felixhandte** [facebook/zstd#1221]
Some targets in the tests Makefile fail when `make` is invoked with parallelism enabled (`-j[N]`). This is true of at least the targets that depend on `zstd-playTests`.

**Comment by Cyan4973** [comment]
Indeed,
latest release of Zstandard paid attention to ensure that `make` and `make all` are compatible with `-j[N]`. But this effort was not extended to `make test`.

One issue with running tests in parallel
is that the text output is completely messed up,
with multiple tests trying to write their result to `stdout` or `stderr` at the same time.

As a consequence, I'm not even convinced that this is a good solution.

For discussion

**Comment by Cyan4973** [comment]
Let's be more specific.
`make -j test` works for example.
But targeting more specifically `make -j -C tests test-zstd` doesn't.

**Comment by felixhandte** [comment]
True. Often times, though, as I'm developing, I just want assurance, as quickly as possible, that all the tests pass. And then in the unlikely event that something failed I'm happy to go back and re-run without parallelism.

**Comment by Cyan4973** [comment]
fixed in 328ec7e .
I accidentally uploaded the fix directly into `dev`, instead of the usual feature branch staging.
