### ISSUE TITLE
-o has no effect when training with --train (v. 1.3.5)

### ISSUE THREAD

**Issue by svenha** [facebook/zstd#1227]
zstd -o gt.zstd --train gt.sample10k/*
writes to file dictionary and not to gt.zstd

**Comment by svenha** [comment]
OK. I found out that -o must come after --train. Is this documented?

**Comment by terrelln** [comment]
This is a bug in the CLI. It shouldn't set `outFileName` to `g_defaultDictName` if it is already set.
