### ISSUE TITLE
which training function is better?

### ISSUE THREAD

**Issue by chencheng354** [facebook/zstd#1228]
for big samples, i use ZDICT_trainFromBuffer_unsafe_legacy(libdivsufsort) or ZDICT_optimizeTrainFromBuffer_cover ,which one compression ratio is better ?

**Comment by terrelln** [comment]
`ZDICT_optimizeTrainFromBuffer_cover()` generally produces better dictionaries, and is what the CLI and `ZDICT_trainFromBuffer()` use.

You can try both and pick the better dictionary, but I would expect the cover algorithm to win most of the time.
