### ISSUE TITLE
Can't get pzstd to work as expected

### ISSUE THREAD

**Issue by fefe17** [facebook/zstd#1229]
I'm using a recent NetBSD checkout as test data here, put into a tar file:

-rw-r--r--    1 leitner  users    2730096640 Jul 10 00:07 NetBSD.tar

Now, I want to compress this with zstd at level 19. I do this:

$ pzstd -19 NetBSD.tar
$ zstd -19 NetBSD.tar

I would expect pzstd to be at most 8 times faster and produce a file that is slightly (below 10%) larger.
But what I get is: zstd takes 18 minutes, pzstd takes 6 seconds.
This is run on an otherwise idle Linux with both the tar file and the output on a tmpfs (RAM based). No swap.

And the file sizes vary widely, too:
zstd: 336004969
pzstd: 478911339

Am I using pzstd wrong here? Is the -19 ignored, maybe?

**Comment by terrelln** [comment]
Something is going wrong, I'll look into it.

I recommend switching to `zstd -T0`, which is the newer multithreading API. You'll get a higher compression ratio than `pzstd` and use less memory. We will be deprecating `pzstd` in the near future.

**Comment by fefe17** [comment]
Oh man, I had actually seen that zstd now has threading, too, and forgot all about it.
Thanks for the pointer. zstd -T0 behaves much closer to what I expected.

**Comment by terrelln** [comment]
Thanks for the report! I've found the bug.

The parameters set by `ZSTD_initCStream_advanced()` aren't sticky, and upon calling `ZSTD_resetCStream()` the parameters get reset to level 3. It will be fixed in the next release.
