### ISSUE TITLE
GENie/premake build

### ISSUE THREAD

**Issue by codecat** [facebook/zstd#1231]
I wrote a [GENie](https://github.com/bkaradzic/GENie)/premake build script for zstd to incorporate within our builds. Would it be worth adding to the `contrib` folder? Additionally, I can make a pull request.

https://gist.github.com/codecat/5ff66a9ab4fce068b6229bcd12f6d985

**Comment by terrelln** [comment]
I'm not sure how popular that build system is, but if you think others might find it useful please submit a pull request to a new directory under `contrib`.

**Comment by codecat** [comment]
GENie (a fork of Premake) is quite popular in game development, while premake itself is quite popular across the board. I will test this script tomorrow in actual premake as well and then do a pull request. Thanks!
