### ISSUE TITLE
Two zstd.h header files

### ISSUE THREAD

**Issue by zhou-heng** [facebook/zstd#1232]
This question arose when I tried to include zstd into LibTIFF. Since LibTIFF's CMakeLists.txt wanna check the existence of zstd.h to determine the include directory of zstd, I searched the source package of zstd and got two: one is in contrib\linux-kernel\include\linux and another is in lib\. I chose the former because it looks like an export directory. But my choice was wrong. So I would like to ask two questions here:

1) What is the difference between these two zstd.h header files?
2) To avoid confusion, is it possible to clean up the zstd package to keep only one zstd.h?

Thanks.

**Comment by terrelln** [comment]
The `contrib/` directory is for projects that aren't part of zstd proper. The `contrib/linux-kernel/` is the version of zstd that is included in the linux kernel. `lib/` contains the zstd library, so `lib/zstd.h` is the correct header to use.

We need to keep the `contrib/linux-kernel/` in the repository, but we do have a README in that directory that explains what the code is.
