### ISSUE TITLE
Multi-threaded compression/decompression

### ISSUE THREAD

**Issue by dzenanz** [facebook/zstd#1248]
When is it planned to make multi-threaded API stable? When is it expected to have a simple multi-threaded API available, e.g.:
```C
size_t ZSTD_compress( void* dst, size_t dstCapacity,
                const void* src, size_t srcSize,
                      int compressionLevel,
                      int numberOfThreads);
```

**Comment by terrelln** [comment]
Multithreading is available using the (unstable) [advanced API](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L916). We plan on stabilizing this API in the next release, or the release after that. Until then, there will be some changes, but hopefully nothing too major.

**Comment by dzenanz** [comment]
When is the next release planned - is there a schedule? How about simple multi-threaded API?

**Comment by terrelln** [comment]
Roughly, we try for every few months. I am confident it will be stabilized this year, and hope it will be ready in a few months. The new advanced API should support that use case, see issue #1249.

**Comment by dzenanz** [comment]
I wanted to replace/supplement [zlib](https://github.com/InsightSoftwareConsortium/ITK/tree/master/Modules/ThirdParty/ZLIB) by zstd in an image processing library [ITK](https://github.com/InsightSoftwareConsortium/ITK). The point is to shorten the long wait for writing larger images bottle-necked by single-threaded compression. As ITK is a mature, 20 year old library it makes no sense to rely on zstd's experimental feature. So we will wait until that API stabilizes.

**Comment by Cyan4973** [comment]
[Advanced API has reached staging area](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L419), which means it's ready to become stable "as is", and just needs to spend one last release cycle in "experimental" section to gather feedback and ensure it's effectively ready to become "stable".

The advanced API [supports multithreading](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L595).
