### ISSUE TITLE
zstdgrep doesn't like dictonaries

### ISSUE THREAD

**Issue by tobwen** [facebook/zstd#1268]
Seems like _zstdgrep_ isn't able to work with dictionaries. It needs to be applied to `${zcat} -fq -`, but that's not implemented in the current build: 

https://github.com/facebook/zstd/blob/dev/programs/zstdgrep#L111
https://github.com/facebook/zstd/blob/dev/programs/zstdgrep#L119

**Comment by Cyan4973** [comment]
That's a good point @tobwen.

Something not yet decided : how should look like the command line to provide the dictionary as argument of zstdgrep ?

**Comment by tobwen** [comment]
A big problem might be duplicate parameters, which are shared by _grep_ and _zstdcat_.

Perhaps recommend a workaround? `zstdcat -D my.dict -qc -- <file> | grep`

**Comment by Cyan4973** [comment]
That sounds fair. We could add such recommendation into the documentation.
