### ISSUE TITLE
Julia binding has moved

### ISSUE THREAD

**Issue by bicycle1885** [facebook/zstd#1286]
The current Julia binding of Zstandard has moved from https://github.com/ararslan/ZStd.jl to https://github.com/bicycle1885/CodecZstd.jl, but the website link (http://facebook.github.io/zstd/) still points to Zstd.jl. Could anyone update the link?

**Comment by Cyan4973** [comment]
Sure @bicycle1885 !
Link is updated !

**Comment by bicycle1885** [comment]
Thank you!
