### ISSUE TITLE
Why can't I use more than one ZSTD_CStream in one thread?

### ISSUE THREAD

**Issue by zhangfuwen** [facebook/zstd#1291]
Why can't I use more than one ZSTD_CStream in one thread?
What is the reason for this?

I'm trying to use multiple compressor instances to compress in one thread and multiple decompressor instances each in it's own thread. And I got an error calling ZSTD_compressStream. I guess it's because multiple compressor instances is not allowed in one thread. 

following is a quoted from the user manul:

## Streaming compression - HowTo
  A ZSTD_CStream object is required to track streaming operation.
  Use ZSTD_createCStream() and ZSTD_freeCStream() to create/release resources.
  ZSTD_CStream objects can be reused multiple times on consecutive compression operations.
  It is recommended to re-use ZSTD_CStream in situations where many streaming operations will be achieved consecutively,
  since it will play nicer with system's memory, by re-using already allocated memory.
  **Use one separate ZSTD_CStream per thread for parallel execution.**

**Comment by Cyan4973** [comment]
> Why can't I use more than one ZSTD_CStream in one thread?

Who said so ?

> I got an error calling ZSTD_compressStream.

which error is it ?
