### ISSUE TITLE
Build fails on machines with grep that uses coloring

### ISSUE THREAD

**Issue by danielshir** [facebook/zstd#1294]
The makefile uses `egrep` without specifying that colors shouldn't be outputted and assumes that the output is simply ASCII. This isn't correct and the correct solution to this should be to use `--color=never`.

Try for example setting up color on grep and then running the makefile - 

```
export GREP_OPTIONS='--color=always'
export GREP_COLOR='139;62;47'
make
```

**Comment by Cyan4973** [comment]
Thanks for the clear reproduction case @danielshir .
I'll look into it.

**Comment by Cyan4973** [comment]
fix merged into `dev`
