### ISSUE TITLE
v1.1.0: ZSTD_compressStream writes to an out-of-bound position

### ISSUE THREAD

**Issue by wgtmac** [facebook/zstd#1300]
Hi all,

Our production environment (linux) utilizes zstd streaming APIs to compress data in the proprietary file format. It was working very well until we found that it failed randomly in a very special case. Although we found it in v1.1.0, I still bring it up here for the lack of any relevant issue or release note found. Sorry that I cannot provide confidential data to reproduce it. However, the same data may only reproduce it once out of tens or even hundreds of attempts. Let me briefly describe the code below. Our input stream is always of 1MB data. The output stream returns available buffer via next() interface and allocates a new 64KB block if previous 64KB block is full.

```
void compress(ZSTD_CStream * zcs,          // reuse zcs for all streams
              InputStream * inputStream,
              OutputStream * outputStream)
{
    int level = 1;
    size_t ret = ZSTD_initCStream(zcs, level);
    if (ZSTD_isError(ret)) throw std::logic_error("init error");

    // inputStream always has full 1MB data (i.e. inputStream->size() is 1048576)
    ZSTD_inBuffer input = { inputStream->data(), inputStream->size(), 0 };
    std::cout << "INPUT(" << inputStream->size() << ")";

    // keep track of the state in outputStream
    int pos = 0, size = 0;
    char * data = nullptr;
    size_t totalCompressedSize = 0;

    do {
        if (pos > size) {
            std::cout << "out of bound: pos:" << pos << ", size:" << size << std::endl;
            throw std::logic_error("out of bound");
        } else if (pos == size) {
            // get next available slot and available size
            outputStream->next(data, size);

            std::cout << " NEXT("<< size << ")";
        }

        ZSTD_outBuffer output = { data + pos, size - pos, 0 };

        if (input.pos < input.size) {
            ret = ZSTD_compressStream(cstream, &output , &input);
            if (ZSTD_isError(ret) throw std::logic_error("compress error");
            totalCompressedSize += output.pos;
            pos += output.pos;

            std::cout << " COMPRESS("<< output.pos << ")";
        } else {
            ret = ZSTD_endStream(cstream, &output);
            if (ZSTD_isError(ret) throw std::logic_error("end error");
            totalCompressedSize += output.pos;
            pos += output.pos;

            std::cout << " END(" << output.pos << ")";

            if (ret == 0) break;
        }
    } while (input.pos <= input.size);

    std::cout << "OUTPUT(" << totalCompressedSize << ")" << std::endl;
}
```

Using our data, its expected output should be as below:
> INPUT(1048576) NEXT(65536) COMPRESS(8165) END(3) OUTPUT(8168)
> INPUT(1048576) NEXT(57368) COMPRESS(7443) END(3) OUTPUT(7446)
> INPUT(1048576) NEXT(49922) COMPRESS(14831) END(3) OUTPUT(14834)
> INPUT(1048576) NEXT(35088) COMPRESS(9010) END(3) OUTPUT(9013)
> INPUT(1048576) NEXT(26075) COMPRESS(6221) END(3) OUTPUT(6224)
> INPUT(1048576) NEXT(19851) **COMPRESS(19851)** NEXT(65536) END(15) OUTPUT(19863)

However, when the bug is triggered, its output is as below:

> INPUT(1048576) NEXT(65536) COMPRESS(8165) END(3) OUTPUT(8168)
> INPUT(1048576) NEXT(57368) COMPRESS(7443) END(3) OUTPUT(7446)
> INPUT(1048576) NEXT(49922) COMPRESS(14831) END(3) OUTPUT(14834)
> INPUT(1048576) NEXT(35088) COMPRESS(9010) END(3) OUTPUT(9013)
> INPUT(1048576) NEXT(26075) COMPRESS(6221) END(3) OUTPUT(6224)
> INPUT(1048576) NEXT(19851) **COMPRESS(19863) out of bound: pos:19863, size:19851**

Comparing the last line of two outputs, we can see that when bug happens it outputs 19863 bytes which exceeds the limit 19851. The difference is 12 bytes. In the correct case, it holds the 12 bytes and outputs them with a block header of 3 bytes in ZSTD_endStream() -- that's why you see END(15) in the last line. I have also dig into ZSTD_compressStream_generic() function in zstd_compress.c of v1.1.0: https://github.com/facebook/zstd/blob/v1.1.0/lib/compress/zstd_compress.c#L2944. After printing flushed variable in line 2944, I found there are many small flushes of size 12. Is that a coincidence? As this bug is difficult to reproduce at random, it may be caused by race condition or uninitialized variables. 

Anyone has an idea? Thanks!

**Comment by Cyan4973** [comment]
By default, the library is not multi-threaded, so there should be no race condition involved.

Is it possible for you to test a more recent release, such as `v1.3.5` ?
The API is stable, it behaves exactly the same.

It would help determining if this issue is already fixed or not.

**Comment by wgtmac** [comment]
Thanks @Cyan4973 for replying!

I have tested it using v1.3.5 and it cannot be reproduced. However, it cannot prove the bug is gone. IIUC, the bug only happens under following conditions:

- all input bytes have been consumed in ZSTD_compressStream().
- output buffer only has N bytes available while the actual data needs to flush (N+12) bytes.
- plus an unknown random factor.

The bug itself takes many attempts to reproduce once on my end. We plan to upgrade to v1.3.5 and see if it will happen in the future workload.

**Comment by wgtmac** [comment]
I will try that. Thanks!

**Comment by Cyan4973** [comment]
Any update on this issue ?
