### ISSUE TITLE
Add ZSTD_minCLevel, like ZSTD_maxCLevel

### ISSUE THREAD

**Issue by cemeyer** [facebook/zstd#1312]
Minor enhancement request.

Especially now that ZSTD API has negative ("fast") compression levels, I think it makes sense to give callers a lower bound too.

Mentioned in #89 as a "when this changes in the future."

**Comment by Cyan4973** [comment]
We would need to define a minimum compression level first !
But indeed, I believe that's a reasonable request.

**Comment by cemeyer** [comment]
`INT_MIN` ?  :joy: :joy:

Thanks :-).

**Comment by Cyan4973** [comment]
function `ZSTD_minCLevel()` is now defined in `dev` branch.
