### ISSUE TITLE
Cannot build for Windows ARM

### ISSUE THREAD

**Issue by vnen** [facebook/zstd#1313]
The code makes use of `__cpuid` and `__cpuidex` when MSVC is detected, but these are [not available for the ARM architecture](https://docs.microsoft.com/en-us/cpp/intrinsics/cpuid-cpuidex?view=vs-2017#requirements)
https://github.com/facebook/zstd/blob/3b53bfe4f3f0a9bcc4f9be014b83896a370ba5ff/lib/common/cpu.h#L39-L54

**Comment by terrelln** [comment]
Thanks for the report @vnen! We don't have tests that run in MSFT ARM, would you be able to confirm that this patch works for you?

**Comment by vnen** [comment]
Thanks for the quick fix. I'll test it soon.

**Comment by vnen** [comment]
Yes, it's working for me. Thanks again.
