### ISSUE TITLE
gcc "conflicting declaration 'typedef struct ZWRAP_CCtx internal_state" when using zlibWrapper

### ISSUE THREAD

**Issue by AgainstWind** [facebook/zstd#1323]
### error info:

_zstd_zlibwrapper.c:102:20: error: conflicting declaration 'typedef struct ZWRAP_CCtx internal_state'
 typedef ZWRAP_CCtx internal_state;
                    ^
In file included from zstd_zlibwrapper.c:24:0:
../../../../../../binarylibs/redhat6.4_aarch64/zlib1.2.11/comm/include/zlib.h:83:8: note: previous declaration as 'struct internal_state'
 struct internal_state;
        ^
zstd_zlibwrapper.c: In function 'int z_inflateInit_(z_streamp, const char*, int)':
zstd_zlibwrapper.c:523:35: error: invalid conversion from 'void*' to 'char*' [-fpermissive]
         zwd->version = ZSTD_malloc(strlen(version)+1, zwd->customMem);_

**Comment by AgainstWind** [comment]
> Thanks for reporting the issue @AgainstWind .
> It seems I'm unable to generate these compilation warnings currently.
> Could you provide more details on how to reproduce it ?
> Such as compiler version, compiler flags, zstd version, etc.

---------------------------------------------
this problem appears when i import the zlibwrapper.c to my own project, my own project originally use zlib to compress data.  
Following the steps which written in file:  _zstd-master/zlibWrapper/README.md_
my env info:
linux kernel version: 4.1.32-vhulk3.7.1.aarch64
gcc version 5.4.0 (GCC)
os is developed by my company based on centos

gcc command:
-bash-4.2# vim ../../../../../../binarylibs/redhat6.4_aarch64/zlib1.2.11/comm/include/zlib.h                                                                       -bash-4.2# g++ -D_GLIBCXX_USE_CXX11_ABI=0 -fsigned-char -DSTREAMPLAN -DPGXC -O2 -g3 -Wall -Wpointer-arith -Wno-write-strings -fnon-call-exceptions -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-attributes -fno-omit-frame-pointer -fno-expensive-optimizations -Wno-unused-but-set-variable -Wno-unused-local-typedefs -Wno-int-to-pointer-cast -pthread  -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -I../../../../../src/include -I../../../../../../buildtools/redhat6.4_aarch64/unixodbc/comm/unixODBC-2.3.0/include -I../../../../../../Platform/redhat6.4_aarch64/libobs/comm/include -I../../../../../../binarylibs/redhat6.4_aarch64/libcgroup/comm/include -I../../../../../../Platform/redhat6.4_aarch64/AdaptiveLM/comm/include -I../../../../../../binarylibs/redhat6.4_aarch64/libhdfs/comm/include -I../../../../../../binarylibs/redhat6.4_aarch64/liborc/comm/include -I../../../../../../binarylibs/redhat6.4_aarch64/protobuf/comm/include -I../../../../../../binarylibs/redhat6.4_aarch64/boost/comm/include -I../../../../../../binarylibs/redhat6.4_aarch64/llvm/comm/include -I../../../../../../binarylibs/redhat6.4_aarch64/kerberos/comm/include -D_GNU_SOURCE  -I../../../../../../binarylibs/redhat6.4_aarch64/zlib1.2.11/comm/include -I../../../../../../binarylibs/redhat6.4_aarch64/zstd/zstd-master/lib -I../../../../../../binarylibs/redhat6.4_aarch64/zstd/zstd-master/lib/common/ -I../../../../../../binarylibs/redhat6.4_aarch64/zstd/zstd-master/zlibWrapper/ -L../../../../../../binarylibs/redhat6.4_aarch64/zstd/zstd-master/lib -lzstd  -c -o zstd_zlibwrapper.o zstd_zlibwrapper.c

**Comment by AgainstWind** [comment]
> Thanks for reporting the issue @AgainstWind .
> It seems I'm unable to generate these compilation warnings currently.
> Could you provide more details on how to reproduce it ?
> Such as compiler version, compiler flags, zstd version, etc.

thanks for

**Comment by Cyan4973** [comment]
So I guess the issue was about using `g++` rather than `gcc` ?
