### ISSUE TITLE
zstd licensing under LGPL

### ISSUE THREAD

**Issue by scherepanov** [facebook/zstd#1341]
Hi,
Thanks for very nice zstd library, I am using it extensively and it works pretty well.
Now I want my vendor to use zstd library. For them to ship product with linked zstd library, it should be licensed as LGPL.
I know zstd is licensed GPLv2, or BSD. Vendor can use zstd library issued as GPLv2, but customer have to install it manually and it adds additional dependency. This vendor have "a lot" of customers and  additional external dependency is not going to be implemented. External dependency not directly controlled at compilation time can cause huge problems, up to product delivering wrong results etc.

Is there any chance to have zstd released as LGPL? May be as an exception for one specific vendor? Have it been any precedents with this kind of licensing?

**Comment by Cyan4973** [comment]
Hi @scherepanov ,
normally, BSD license should be good enough for such requirements.
I'm unaware of any need to use LGPL.

**Comment by scherepanov** [comment]
Thank you for comment!
