### ISSUE TITLE
Questions around streaming decompression when ZSTD_e_flush is used

### ISSUE THREAD

**Issue by indygreg** [facebook/zstd#1360]
I have a use case where I want to use streaming compression to send N logical units between peers. I want to create a **single** compressor and emit bytes in "framed chunks" that correspond to each logical input. The overarching goal is to keep bytes "over the wire" small by reusing compression context from a previous input.

When using ``ZSTD_compress_generic()``, I call ``ZSTD_e_flush()`` at the end of each logical input chunk. When I feed the corresponding output chunks into ``ZSTD_decompress_generic()`` (my application tracks which compressed chunks correspond to which logical units in a layer above zstd), it appears things "just work" most of the time: I feed chunks into the decompressor and the output data maps to the logical units that were fed into the compressor.

However, some times (maybe 1% of the time with my data set), the output from the decompressor doesn't map to the input chunks I was feeding to the compressor!

While I'm not convinced there isn't a bug in my code, I'm not sure I'm using the zstd API properly either. I have a few questions about the streaming APIs. Some of these could point to potential documentation improvements:

1. Is using ``ZSTD_e_flush`` and feeding incremental output into a compressor the proper way to go about what I'm doing? Or should ``ZSTD_e_end`` be used?

2. What are the implications of ``ZSTD_e_flush`` versus ``ZSTD_e_end``? (I think I know the answer to this, but I don't see it spelled out explicitly in the documentation.)

3. If using ``ZSTD_e_flush`` in concert with an incremental decompressor to obtain exact input chunks is supported, what guarantees are there that ``ZSTD_decompress_generic()`` will emit all data provided so far? i.e. how do I ensure the decompressor isn't holding data in its internal buffers? Since ``ZSTD_decompress_generic()`` only returns 0 if a **frame** is fully decoded and ``ZSTD_e_flush`` doesn't end a frame, how do you know you got all available output data from a given input? Is it enough to look at ``input.pos == input.size`` or do you have to attempt a ``ZSTD_decompress_generic()`` again in the special case that ``output.pos == output.size && input.pos == input.size``?

4. Depending on the answer to the previous question, should/could a special return value for ``ZSTD_decompress_generic()`` be added to differentiate between "all data flushed" versus "output buffer full and buffered data remains?"

I think my fundamental confusion is not understanding when streaming decompression has data left in its internal buffers and how that plays with ``ZSTD_e_flush`` and the input/output offsets of ``ZSTD_inBuffer``/``ZSTD_outBuffer``.

**Comment by Cyan4973** [comment]
1. using `ZSTD_e_flush` will force the compressor to emit a block immediately. In general, this requirement is for communication scenarios, when some data must be sent "now". 
      - Because it increases the nb of blocks produced, this technique can be associated with some lower compression ratio. Therefore, whenever there is no need to send data immediately, it's better (for compression ratio) to let the data accumulate in the internal buffers, and let the compressor decide when it's best to output a new block.
      - `ZSTD_e_end` will _end_ a frame. This is even worse for compression. But it guarantees that following data will not make any reference to previous data (in previous frame). 
           - I don't see any such requirement in the scenario described, so I guess it's not necessary to use this order. `ZSTD_e_flush` will be better for the compression ratio.

2. I guess I answered this question in point 1, but if it's not clear from the documentation, indeed, documentation must be updated.

3. This one is more complex. Yes, `ZSTD_decompress_generic()` will make any effort it can to produce and flush all data it received. But its behavior is constrained by the size of buffers it receives from user. In the special case `output.pos == output.size`, it's not possible to tell if all decompressed data was flushed. In fact, except if you have special guarantees from producer side regarding the size of blocks, it is quite likely that there is still some data within internal buffers if the output buffer is entirely filled. In which case, calling `ZSTD_decompress_generic()` again is a good way to ensure it has enough room to flush everything.
    - If you don't provide any more input, the maximum amount of data that `ZSTD_decompress_generic()` can flush is necessarily <= `ZSTD_BLOCKSIZE_MAX`

4. While it seems a good idea to add this feedback signal, I unfortunately don't see how to do it while respecting current interface. The return value of `ZSTD_decompress_generic()` must be _either_ a `0` to mean "frame is completed", _either_ an error, conforming to `ZSTD_isError()`, _either_ an hint regarding best input size expected, to reducing buffering load. All values are covered by this definition, there is no room left.
    - Note that when `@return == 3`, which is the block header size, it's a pretty good signal that `ZSTD_decompress_generic()` consumed a block and is now asking for another block header(*). Nice to know that everything sent was decoded, but it doesn't give any indication regarding data possibly remaining within internal buffer.
    - The recommended test [is `output.pos < output.size`](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L364) : in this case, it's guaranteed that `ZSTD_decompress_generic()` has flushed everything it could. Conversely, if `output.pos== output.size`, there is no guarantee.
        - One could imagine a "special return value" to mean "buffers are empty", but this feels hacky : now the return value is sometimes an hint, sometimes an indication that buffers are empty. If an application wants to follow the hints, as designed, in order to grab the reduced buffering benefits, it can no longer do so.
        - It's also possible to add a function prototype specifically to ask this information (how much data stored within internal buffers).
        - On average, I believe the test `output.pos < output.size` is the correct one for this use case. This information is directly accessible by user program.

[*]: There is an exception possible, when the decoder knows that it is receiving the last block of a frame and that there is no frame checksum, and it just happens that 3 bytes are missing to complete this last block.

**Comment by indygreg** [comment]
Thank you very much for the detailed reply!

I'm pretty sure I now have all the information I was seeking. And it sounds like you may have a few leads on ways to improve the docs as well.

FWIW I updated python-zstandard to call `ZSTD_decompress_generic()` again and this seems to have fixed my failing code. So it appears that `ZSTD_e_flush` is now having the intended desired effect. 

Thanks again!
