### ISSUE TITLE
Question regarding the compiler version requirement for BIT_getMiddleBits

### ISSUE THREAD

**Issue by atdt** [facebook/zstd#1364]
I am wondering why 5397a66 made the BMI specialization of BIT_getMiddleBits conditional on  __GNUC__*1000+__GNUC_MINOR__ >= 4008.

The check appears here:

https://github.com/facebook/zstd/blob/5397a66b19400255623494acd2caa7847b775700/lib/common/bitstream.h#L301

This prevents the BMI code from getting compiled by clang. On trunk clang __GNUC__*1000+__GNUC_MINOR__ is 4002: https://godbolt.org/z/Den3Z7

**Comment by Cyan4973** [comment]
I'm pretty sure that the test is correct for `gcc`,
but indeed, it might not be for clang.
We could add a `__clang__` specific test to cover this situation.

**Comment by Cyan4973** [comment]
Note that, in my tests, force-enabling bmi instruction `bextr` is actually performance detrimental, for both `gcc` (-6%) and `clang` (-9%). 
Not sure if it matches your experimentation, but if it does, it's probably best do disable this code path.

**Comment by atdt** [comment]
We simply noticed the non-BMI path getting executed on a BMI-enabled build and were a bit mystified as to why. Regarding performance, I'm not surprised that `bextr` is slower in this case. I agree that if is indeed slower, it is probably best to remove it.

Many thanks for the quick reply!

**Comment by Cyan4973** [comment]
Thanks for feedback @atdt !

The `bextr` code path has been removed in latest update of `dev` branch.
