### ISSUE TITLE
www.zstd.net TLS certificate is not valid for that domain name

### ISSUE THREAD

**Issue by zackw** [facebook/zstd#1373]
`http[s]://www.zstd.net` currently redirects to `https://facebook.github.io/zstd/`.  I would like to use `https://www.zstd.net` in documentation, for future-proofing, but I can't because that site serves a TLS certificate that is only valid for `mailconfig.ovh.net` and `www.mailconfig.ovh.net`, so browsers will throw up an error page and refuse to follow the redirect.

Please consult https://www.ssllabs.com/ssltest/analyze.html?d=www.zstd.net for further detail on the TLS configuration problems; it looks like this is not the only issue.  (You may have to click through a "ignore cert mismatch and proceed with tests" link to see full details.)

**Comment by Cyan4973** [comment]
Thanks for reporting it @zackw 

Could you try again ?
`https` traffic should work better now.

**Comment by zackw** [comment]
Yes, much better now, thanks for the quick fix.

**Comment by mschilli87** [comment]
I come here almost two years later with the same issue: https://www.zstd.net just gives me `ERR_CONNECTION_REFUSED`. Also, the project description on GitHub *still* uses plain HTTP (in **2020**!) to link to the page. Given that even Joe's mom's cat picture website is using HTTPS nowadays, it is sad to see a huge company like Facebook that makes their (share-holders') money on the web lagging behind on what is to be considered standard on said network. :disappointed:
