### ISSUE TITLE
Is zstd going to be added to .ZIP file format standard?

### ISSUE THREAD

**Issue by TheSil** [facebook/zstd#1378]
Sorry if it is not the best place to discuss this, but I don't know where else to ask. Do you know if there is a plan to add zstd to the .ZIP standard as one of the supported algorithms (https://en.wikipedia.org/wiki/Zip_(file_format))? Are there some plugins for .zip? I've seen couple of plugins for 7z, but not for .zip. The .ZIP file format seems to be updated now and then (most recent seems to be in 2014).

**Comment by Cyan4973** [comment]
This question should indeed be directed at the maintainers of the zip format (aka pkware).

Your suggestion is technically possible, but there is no guarantee that zip maintainers will be willing to update their format.

Contact point is not trivial, though in the format documentation, one can find this email address : 

> To submit requests for information on licensing or enhancements please email zipformat@pkware.com

No idea if it's still active.

**Comment by TheSil** [comment]
Thanks, I am gonna ask them then :)

**Comment by ipaucek4680** [comment]
@TheSil 
If you are still interested in Zstd within the ZIP format, here is an update:

The [latest APPNOTE](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) (format specification) has added Zstandard compression method ID in [specs version 6.3.7](https://pkware.cachefly.net/webdocs/APPNOTE/APPNOTE-6.3.7.TXT). **The method ID for Zstd is 20**.

As listed in the [Zstd homepage](https://facebook.github.io/zstd/), two proprietary applications, namely WinZip and PowerArchiver, are using Zstd. These two applications allows you to use Zstd in ZIP(X), but the Z**std method ID used by WinZip** (and probably PowerArchiver as well) **seems to be 93**.

If you want to use 7-Zip to use Zstd in ZIP, Tino Reichardt is [planning to add this feature](https://github.com/mcmilk/7-Zip-zstd/issues/132#issuecomment-638434730) in 7-Zip ZS, but he is waiting for the response from PKWARE and WinZip (in hope that we can get an answer of the correct method ID to use for Zstd - should we use 20 or 93?).

**Comment by geofft** [comment]
For anyone finding this thread from web search: [APPNOTE-6.3.8.TXT](https://pkwaredownloads.blob.core.windows.net/pkware-general/Documentation/APPNOTE-6.3.8.TXT) standardizes on method ID 93 for zstd and deprecates method ID 20, with the changelog note "Resolved Zstandard compression method ID conflict." So there is a standard ID that can be reliably used.
