### ISSUE TITLE
Release tarballs compressed with zstd

### ISSUE THREAD

**Issue by cemeyer** [facebook/zstd#1381]
It is kind of unfortunate that https://github.com/facebook/zstd/releases has a bunch of .tar.gz's and no .tar.zst.  We likely want to continue to publish .gz for new users, but some of us already have an older version of Zstd and are upgrading.  There is some nice aesthetics to eating our own dogfood and publishing an extra tarball compressed with zstd.

This is not a big deal for anyone and is a slightly greater burden for releases, so it would be absolutely fine to reject this request.  Thanks :-).

**Comment by cemeyer** [comment]
Sounds reasonable to me!  It is not urgent, of course :-).

**Comment by Cyan4973** [comment]
`.zst` variant of the source tarball has been added to latest `v1.3.7` release.
