### ISSUE TITLE
Search text in a compressed TXT file without unpacking

### ISSUE THREAD

**Issue by MrOCR** [facebook/zstd#1389]
Thank you for your hard work,

Is it possible to compress a huge .txt file, and later-on search for a certain string of text without unpacking the entire .txt file.

**Comment by MrOCR** [comment]
@Cyan4973 Can you add a `feature request` tag.
People dealing with databases would be interested in such feature.
 
It would be very handy when having a huge .txt file, such that we can compress, and later on search without unpacking the entire file.
Thank you

**Comment by Cyan4973** [comment]
Streaming is a feature that's [already possible](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L287).

For a data format which allows random access anywhere in the file, by cutting it into multiple independent blocks, we have a `contrib` project at : 
https://github.com/facebook/zstd/tree/dev/contrib/seekable_format

**Comment by MrOCR** [comment]
Thanks

**Comment by Cyan4973** [comment]
Well, for the "streaming" solution suggested above, there is nothing special to do.

Just compress using regular `zstd`, and the resulting file is automatically stream-compatible.

This can then be used to search into compressed file, by using `zstdgrep`, which works the same as `grep`, but is compatible with compressed `.zst` files.
