### ISSUE TITLE
Move ZSTD_initCStream_srcSize to stable API

### ISSUE THREAD

**Issue by edenhill** [facebook/zstd#1391]
With almost two years in public releases it would be convenient if ZSTD_initCStream_srcSize() was moved to the non-advanced/non-static part of the public API to make it generally available without having to link zstd statically.
Being able to encode the decompressed size does make a big difference for a decompressor's double-up-and-realloc loop.

**Comment by Cyan4973** [comment]
I agree. Getting the decompressed size written in the header is important.

Our selected path to bring this capability is to get the [advanced API](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L966) into stable. It covers this use case, and plenty other ones too.

It's supposed to be part of `v1.4.0`.

**Comment by Cyan4973** [comment]
The advanced API has been updated in `dev` branch,
it now features a way to setup `srcSize` : 
after `ZSTD_initCStream()` to set the compression level,
use [`ZSTD_CCtx_setPledgedSrcSize()`](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L661) to indicate the amount of data that will be present in the frame.

Note that this amount will be controlled, and the compression context will issue an error if this amount is not respected at end of frame.

This new advanced API obsoletes `ZSTD_initCStream_srcSize()`, which will be gradually sidelined, and later removed from the experimental API section.

**Comment by edenhill** [comment]
@Cyan4973 It would be good if the docstring mentioned that using setPledgedSrcSize() will include the uncompressed size in the zstd header/framing, allowing a decompressing application to know the full size before-hand.

What about moving setPledgedSrcSize() to the non-advanced/non-experimental section of the API so it can be used from dynamically linked libraries?

**Comment by Cyan4973** [comment]
I can certainly add this comment.
Yes, `setPledgedSrcSize()` will also fill the frame header with this information, unless if explicitly disallowed with `ZSTD_c_contentSizeFlag`.

`setPledgedSrcSize()` is currently in "staging area",
which means it's planned to become "stable" at next release.

Candidate stable functions need to spend at least one release cycle in "staging area", so that we get enough reliability signal that it is a good choice for "stable".
