### ISSUE TITLE
manual: wrong default window size for ZSTD_DCtx_setMaxWindowSize

### ISSUE THREAD

**Issue by pdknsk** [facebook/zstd#1407]
> By default, a decompression context accepts all window sizes <= (1 << ZSTD_WINDOWLOG_MAX)

That should be `ZSTD_WINDOWLOG_DEFAULTMAX` instead.

**Comment by Cyan4973** [comment]
Good point @pdknsk,
besides, this constant does not exist, 
we would need to create and document one.

**Comment by Cyan4973** [comment]
The API has been updated in `dev` branch.
API has been changed, for better consistency between the compression and decompression side,
documentation has been [updated](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L820),
and [`zstd.h` exposes a constant](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L950) which specifies the default limit.
