### ISSUE TITLE
Compare to more compression types?

### ISSUE THREAD

**Issue by lahwran** [facebook/zstd#1414]
so I googled for `zstd vs lzma benchmarks`, and this popped up: https://github.com/powturbo/TurboBench / https://sites.google.com/site/powturbo/compression-benchmark - according to that, it looks like lzturbo is dramatically faster than zstd at the same compression rates. what are your thoughts about the comparison? I imagine it could be pretty expensive to get lzturbo security/stability reviewed.

**Comment by Cyan4973** [comment]
Indeed, `lzturbo` is not open sourced, so we cannot really review nor benchmark it.

**Comment by lahwran** [comment]
doh. also, I see brotli is included now, so this is really just about lzturbo. closing.
