### ISSUE TITLE
cmake target libzstd_static does not export public include directory

### ISSUE THREAD

**Issue by mateuszzz88** [facebook/zstd#1421]
This is a regression that happened in 1.3.5. 
With zstd 1.3.4 I could use library as subproject in cmake, without global install
1. put the whole source in my project, 
2. in CMake add subdirectory: add_subdirectory(zstd-1.3.4/build/cmake)
3. In CMake in my target add target_link_library(my_target PRIVATE libzstd_static)
4. Use library with \#include<zstd.h>

With 1.3.5 and 1.3.7 this fails with "zstd.h file not found".

**Comment by mateuszzz88** [comment]
ok, possibly this is not regression - I may have modified 1.3.4 locally. 
Anyway, 
`target_include_directories(libzstd_static INTERFACE ${LIBRARY_DIR})` is needed in `build/cmake/lib/CMakeLists.txt` and similar for shared version.

**Comment by Cyan4973** [comment]
We accept PR on this topic

**Comment by hjmjohnson** [comment]
FYI:  #1474, #1475 are precursors towards being able to support this use-case robustly.

**Comment by Cyan4973** [comment]
With both #1474 and #1475 merged, I guess this topic is covered now.
