### ISSUE TITLE
zstdgrep returns 0 on non-match

### ISSUE THREAD

**Issue by waterhouse** [facebook/zstd#1428]
The return code of grep is often used—particularly with "grep -q", but not always—in a script to detect the presence or absence of a match.  And zgrep preserves this behavior.  But zstdgrep does not:
```
$ echo a | gzip | zgrep a; echo $?
a
0
$ echo a | gzip | zgrep b; echo $?
1
$ echo a | zstd | zstdgrep a; echo $?
a
0
$ echo a | zstd | zstdgrep b; echo $?
0
```
Even with "zstdgrep -q", a non-match still returns 0.
I'd recommend bringing zstdgrep in line.

**Comment by Cyan4973** [comment]
Fixed by @lzutao

**Comment by Cyan4973** [comment]
Issue fixed by @lzutao
