### ISSUE TITLE
Add Debug Log Statements for Decompression Error Conditions?

### ISSUE THREAD

**Issue by felixhandte** [facebook/zstd#1435]
When diagnosing corrupt compressed blobs, I frequently get a generic "Corrupted block detected" error message, which can be caused by all sorts of different things.

What do you think about adding a `DEBUGLOG` statement everywhere we return an error, so that diagnosing these blobs becomes as simple as rebuilding zstd with `-DDEBUGLEVEL=999`. In many cases the comment that is already on the condition being checked would be the perfect message.

I'm happy to work up a patch that does this.

What do you think about introducing a macro? E.g.,

```
#define RETURN_ERROR(code, ...) do { DEBUGLOG(2, __VA_ARGS__); return code; } while (0)
#define CHECK_M(code, ...) do { if (ERR_isError(code)) { RETURN_ERROR(code, __VA_ARGS__); } } while(0)
```

And then converting existing `return ERROR(corruption_detected);` sites to use the new format with some error message?

**Comment by Cyan4973** [comment]
Agreed.
Level 2 is for temporary debug, for conditions that do not remain in the code.
Level 3+ are adapted for debug messages that remain present in source code.
It's also possible to use a constant with a default value that can be overridden on command line.

**Comment by Cyan4973** [comment]
Is there a PR associated to this issue ?
