### ISSUE TITLE
Build fails when unsigned != U32

### ISSUE THREAD

**Issue by clbr** [facebook/zstd#1441]
On some platforms, uint32_t is defined as unsigned long. Even when it's the same size as unsigned int, the build fails with errors like
In file included from common/fse.h:303,
                 from common/entropy_common.c:41:
common/bitstream.h:401:19: error: conflicting types for 'BIT_readBitsFast'
 MEM_STATIC size_t BIT_readBitsFast(BIT_DStream_t* bitD, U32 nbBits)
                   ^~~~~~~~~~~~~~~~
common/bitstream.h:148:19: note: previous declaration of 'BIT_readBitsFast' was here
 MEM_STATIC size_t BIT_readBitsFast(BIT_DStream_t* bitD, unsigned nbBits);
                   ^~~~~~~~~~~~~~~~

(this is on a 32-bit linux mips platform, gcc 8.2)

**Comment by Cyan4973** [comment]
Thanks @clbr ,
that's a good point.

What would help us is to find a way to generate this issue, so that it can be observed, fixed, and then continuously tested.

Do I read that cross-compiling for mips target might do it ?

**Comment by clbr** [comment]
I think you can repro on 32-bit x86 by changing the typedef to "typedef unsigned long U32". (untested)

**Comment by Cyan4973** [comment]
change integrated into `v1.3.8`
