### ISSUE TITLE
Zstd - compile error: wrong number of arguments specified for 'deprecated' attribute

### ISSUE THREAD

**Issue by jasonma163** [facebook/zstd#1488]
https://github.com/facebook/zstd/blob/282000d88b76a3159773d4a30bb3b9513570e25b/lib/deprecated/zbuff.h#L50

When compiling the code with cloud VMs, the error reported as below occasionally(reproduced uncontrolledly) for some times:
lib/deprecated/zbuff.h:71: 
**error: wrong number of arguments specified for 'deprecated' attribute**

After checking the version supporting the feature 'deprecated', it seems: 
when GCC >= 4.5, "deprecated(message)" supported. 

What do you think about refering to below. Thanks!
https://github.com/open-source-parsers/jsoncpp/blob/master/include/json/config.h
(line 142 ~ 148)

**_#elif (defined(__GNUC__) && (__GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 5))) || defined(__clang__)_**
#define ZBUFF_DEPRECATED(message) ZSTDLIB_API __attribute__((deprecated(message)))
_**#elif defined(__GNUC__) && (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 1))**_
#define ZBUFF_DEPRECATED(message) ZSTDLIB_API __attribute__((deprecated))

**Comment by Cyan4973** [comment]
@jasonma163 , which compiler was used in your test ?

**Comment by jasonma163** [comment]
Thanks for your reply!
Now we have found the reproduction condition.
(1)compiling zstd alone(make command), it's OK.
(2)compiling zstd multi-CPU types via cloud VMs.
As to condition (2), we are narrowing the range for further location.

Another thing is, we tried compiling zstd alone in 4.8 version, only "deprecated" warning report.

@Cyan4973 
I also find your reply in the other issue via https://github.com/lz4/lz4/issues/272

**Cyan4973 commented on 19 Nov 2016
Latest update in dev branch should fix the reported issue**

Could you please show the modification link? Thanks!

**Comment by Cyan4973** [comment]
Here is the associated lz4 fix : 
https://github.com/lz4/lz4/commit/19df3029e234e4c48c31377c9ef5f7c940da5106
