### ISSUE TITLE
Suggestion: compress dictionary files

### ISSUE THREAD

**Issue by ealgase** [facebook/zstd#1497]
I've been using zstd's dictionary compression to compress many similar json files I have.  However, the dictionary that's used to compress them isn't compressed, and uses much more storage space than necessary.  Uncompressed it uses 100kb, and compressed (with default compression levels) it uses only 30kb.

**Comment by Cyan4973** [comment]
It totally makes sense to store the dictionary in compressed format.
It's just that, the API which consumes it, like `ZSTD_compress_usingDict()`, needs this dictionary in uncompressed format. So it has to be decompressed first.
This is just a separate operation, that must be completed first.
