### ISSUE TITLE
 Snap package support(Feature Request)

### ISSUE THREAD

**Issue by mikeroyal** [facebook/zstd#1498]
I was thinking the install and setup could be improved for Ubuntu and other Linux distros by having a [snap package](https://snapcraft.io/) version. If it's not a priority would you mind if I made the snap as a contribution?

[Crafting your first snap](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0)

[Build and test snap](https://snapcraft.io/build)

[Getting Started snap template](https://github.com/snapcrafters/fork-and-rename-me)

**Comment by Cyan4973** [comment]
FYI, there is a `snap.yaml` script provided in : 
https://github.com/facebook/zstd/tree/dev/contrib/snap

However, this is just the start of the process, and there are multiple other steps necessary to publish something on snapcraft.

**Comment by bimbashrestha** [comment]
It's been a while since this thread saw any activity. @mikeroyal, are you still interested in adding zstd to snapcraft?

**Comment by bimbashrestha** [comment]
I'm closing this for now since it looks like there is no longer much interest. Happy to re-open of someone can articulate the need for this feature.
