### ISSUE TITLE
Is there a document to clarify the idea of different compress strategies?

### ISSUE THREAD

**Issue by jingzhao-falcon** [facebook/zstd#1502]
I am planning to implement a hardware version  of ZSTD based on FPGA. I want to figure out the idea of different compression strategies. It's hard to conclude this from the code. So I am wondering is there a doucument contained this information?

**Comment by Cyan4973** [comment]
Hi @jingzhao-falcon,

unfortunately no, there is no document.
This is a domain full of heuristics and ad hoc decisions.

Say you have 2 strategies with different speed / ratio trade-off, 
and each strategy accepts a (potentially different) set of parameters.
The idea is to "test them all", 
and when search space becomes too large, guide the search by pruning unpromising directions.
Then compare both strategies, detect the overlapping area, 
select which one seems better for a given speed / ratio objective,
and there you have it, 2 strategies, multiple speed/ratio choices possible, 
automatic strategy selection based on target speed/ratio.

For 3+ strategies, it's exactly the same method, just a superset, with more candidates.

For example, `tests/paramgrill` implements this methodology, and is used to periodically refresh the compression level table.

For FPGA, I suspect that each strategy will cost a certain transistor budget, so there's an incentive to limit the number of strategies implemented. 
Nonetheless, the exact same methodology to arbitrate between strategies depending on a speed/ratio trade off seems applicable..

**Comment by jingzhao-falcon** [comment]
Hi @Cyan4973 ,
Thanks for sharing your ideas!
