### ISSUE TITLE
CMake does not install zstdgrep and zstdless shell scripts

### ISSUE THREAD

**Issue by Mno-hime** [facebook/zstd#1503]
I ported zstd for the OpenIndiana project userland. I opt to build it via the CMake infrastructure in `build/cmake/`, however `zstdgrep` and `zstdless` shell scripts were not installed to `usr/bin/` (their respective man pages were installed correctly), so, I had to install them manually" in our build infrastructure.

**Comment by terrelln** [comment]
The CMake build is community maintained. We'd gladly accept a PR to improve the situation!

**Comment by LeeYoung624** [comment]
This PR should help
[Cmake bug fix: CMake does not install zstdgrep and zstdless](https://github.com/facebook/zstd/pull/1625)

**Comment by Cyan4973** [comment]
@LeeYoung624 patch merged
