### ISSUE TITLE
zstd --train FILEs: passing files via file?

### ISSUE THREAD

**Issue by braibant** [facebook/zstd#1507]
Looking at zstd (the command line tool) in version 1.3.8, it looks like dictionary training is restricted to passing the training files as command line arguments. Would it be possible to obtain the names of the files to be used in training from a file, a la `grep ---file=FILE`, receiving files from FILE, one per line? 

(This would allow for having arbitrary number of files available for training, irrespective of the size of those files.)

**Comment by Cyan4973** [comment]
Thanks for the suggestion @braibant .

`zstd` command line doesn't have this capability yet.
Closest thing available is the `-r` recursive mode, which can dynamically discover a list of files belonging to a directory (and its sub-directories). And of course shell expansion, but this one can explode when the list of files is really large.

Of course, it's not equivalent : `-r` takes everything within a directory, while `--file=FILE` is explicit, hence more selective.

We will have to add this feature in a future version.

**Comment by bra-fsn** [comment]
Would be a very useful feature indeed. BTW, is training `zstd` feasible with a LOT of files/data?
Does the training process's memory needs scale with the amount of the input?

**Comment by Cyan4973** [comment]
> is training zstd feasible with a LOT of files/data?

Yes. I generally use the recursive mode (`-r`) for such cases, as it's free of command line expansion limitations. But that requires __all__ files within a given directory (and its sub-directories) to be samples, there is no way to "filter" them, only keep some and discards others.

> Does the training process's memory needs scale with the amount of the input?

Yes it does, almost linearly.

**Comment by Cyan4973** [comment]
See #1844

**Comment by Cyan4973** [comment]
This functionality is available in `v1.4.4`
