### ISSUE TITLE
DCtx/CCtx vs DStream/CStream

### ISSUE THREAD

**Issue by luben** [facebook/zstd#1510]
Hi,

I am migrating the dictionary support of zstd-jni to the new advanced API (based on 1.3.8). Through the `zstd.h` I see both variants inter-mixed. Examples: there is  `ZSTD_createDCtx` and `ZSTD_createDStream` but there is no `ZSTD_DStream_loadDictionary`. If I pass `DStream*` to  `ZSTD_DCtx_loadDictionary`, everything looks fine. Also, all the documentation is attached to the 'CStream'/'DStream' so they look as the preferred choice, but the new advanced API works in terms of `DCtx/CCtx`.

What is the path forward? Should I migrate everything to `DCtx`/`CCtx` from `DStream`/`CStream` variants? Any clarification on the subject will be helpful.

**Comment by Cyan4973** [comment]
`CCtx` and `CStream` are now exactly the same object.
This change has been the main purpose for `v1.3.0`, and is explained here : https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L343

Same thing regarding `DCtx` and `DStream`.

Moving forward, we plan to concentrate on names `CCtx` and `DCtx`.

Previous names `CStream` and `DStream` remain available to seamlessly support older applications using API <= `v1.2.0`. 
We plan to always support these names, as synonymous of `CCtx` and `DCtx`.

If that helps, we could rename all context names to `CCtx` and `DCtx` exclusively, and only keep the `typedef` for `CStream` and `DStream`. It did not felt important, so we kept existing declaration "as is". But we are certainly opened to suggestions and comments.

**Comment by luben** [comment]
Great, thanks for the explanation. I will migrate to the new names.
