### ISSUE TITLE
soname inconsistency b/w cmake and non-cmake build

### ISSUE THREAD

**Issue by nehaljwani** [facebook/zstd#1512]
```
$ find ./ | grep libzstd.so

# CMake build produces:
./build/lib/libzstd.so
./build/lib/libzstd.so.1.3.8

# Non-CMake build produces (running make in the top-level directory):
./lib/libzstd.so
./lib/libzstd.so.1.3.8
./lib/libzstd.so.1
```
The symlink `./lib/libzstd.so.1` -> `libzstd.so.1.3.x` is missing from the CMake builds. Is that a bug or has that been omitted deliberately?

**Comment by terrelln** [comment]
The CMake build system is community maintained. We'd gladly accept any PR to fix this!
