### ISSUE TITLE
-Wformat-security superfluous when -Wformat=2 is used

### ISSUE THREAD

**Issue by thatsafunnyname** [facebook/zstd#1514]
Hello and thanks for zstd,

  From all I have read when ```-Wformat=2``` is passed to gcc or clang, ```-Wformat-security``` is enabled:

https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wformat_003d2
 ```
-Wformat=2
Enable -Wformat plus additional format checks. Currently equivalent to -Wformat 
-Wformat-nonliteral -Wformat-security -Wformat-y2k.
```

https://clang.llvm.org/docs/DiagnosticsReference.html#wformat-2
```
-Wformat=2
Some of the diagnostics controlled by this flag are enabled by default.

Controls -Wformat-nonliteral, -Wformat-security, -Wformat-y2k.
```

So I think it is not needed in these 7 Makefiles and 1 meson.build file:

  https://github.com/facebook/zstd/search?q=%22-Wformat%3D2%22+%22-Wformat-security%22&unscoped_q=%22-Wformat%3D2%22+%22-Wformat-security%22

If you agree then I can make a PR against the dev branch to remove ```-Wformat-security``` where ```-Wformat=2``` is used.

**Comment by terrelln** [comment]
I'd gladly accept a PR that reduces the number of flags, thanks!
