### ISSUE TITLE
ZSTD_compressCCtx should not clobber the requestedParams and alternatively allow setting flags such as checksumFlag

### ISSUE THREAD

**Issue by dineshjoshi** [facebook/zstd#1534]
I'm using Zstd via the JNI bindings. I'd like to enable checksumming. However, `ZSTD_compressCCtx` function doesn't accept any flags. Moreover the call to `ZSTD_compressCCtx` then goes into `ZSTD_compress_usingDict` which then [clobbers](https://github.com/facebook/zstd/blob/dev/lib/compress/zstd_compress.c#L3432) the `ZSTD_CCtx->requestedParams` with the defaults that `ZSTD_getParams` give out which happens to have checksumming disabled. For our use-case, having checksumming enabled is really important and `ZSTD_compressCCtx ` is the easiest method invocation we need. Why does `ZSTD_compressCCtx` clobber the `requestedParams` especially something as important as `checksumFlag`?

Either make it possible to specify explicit flags or do not clobber the `ZSTD_CCtx->requestedParams`.

Edit: After I opened the ticket, I noticed `ZSTD_compress_advanced` which does not clobber the context params. We can potentially leverage that but ideally we should not clobber parameters in `ZSTD_compressCCtx`.

**Comment by Cyan4973** [comment]
This use case is covered by ZSTD_compress2(). See advanced API documentation for details.

**Comment by terrelln** [comment]
For example, this would do what you want:

```c
size_t checkIfError(size_t ret);

size_t zstdCompress(void* dst, size_t dstCapacity, void const* src, size_t srcSize) {
  ZSTD_CCtx* cctx = ZSTD_createCCtx();
  checkIfError(ZSTD_CCtx_setParameter(cctx, ZSTD_c_compressionLevel, 1));
  checkIfError(ZSTD_CCtx_setParameter(cctx, ZSTD_c_checksumFlag, 1));
  size_t const size = checkIfError(ZSTD_compress2(cctx, dst, dstCapacity, src, srcSize));
  ZSTD_freeCCtx(cctx);
  return size;
}
```

**Comment by terrelln** [comment]
We'll be moving the advanced API to the stable API in zstd-1.4.0, which is slated to be the next release. After that, it will be featured more prominently in the header.

**Comment by dineshjoshi** [comment]
Thank you @Cyan4973 and @terrelln. What is the equivalent for `ZSTD_compress_usingDict`? It seems to reset the parameters too.

**Comment by terrelln** [comment]
`ZSTD_compress2()` handles all single-pass use cases, since you set the parameters before compression. If you need streaming use `ZSTD_compressStream()` or `ZSTD_compressStream2()`.

```c
size_t checkIfError(size_t ret);

size_t zstdCompress(void* dst, size_t dstCapacity, void const* src, size_t srcSize, void const* dict, size_t dictSize) {
  ZSTD_CCtx* cctx = ZSTD_createCCtx();
  checkIfError(ZSTD_CCtx_setParameter(cctx, ZSTD_c_compressionLevel, 1));
  checkIfError(ZSTD_CCtx_setParameter(cctx, ZSTD_c_checksumFlag, 1));
  checkIfError(ZSTD_CCtx_loadDictionary(cctx, dict, dictSize));
  size_t const size = checkIfError(ZSTD_compress2(cctx, dst, dstCapacity, src, srcSize));
  ZSTD_freeCCtx(cctx);
  return size;
}
```

Note that `ZSTD_CCtx_loadDictionary()` is expensive, so you should either load it once and reuse the context, or create a `ZSTD_CDict` and use `ZSTD_CCtx_refCDict()`.

**Comment by dineshjoshi** [comment]
Ok, thank you!
