### ISSUE TITLE
Provide ZSTD_boundDecompressedSize()

### ISSUE THREAD

**Issue by terrelln** [facebook/zstd#1536]
When the decompressed size isn't written into the frame, and you want to use the one pass function, you are forced to guess the decompressed size. We could estimate the decompressed size using the number of blocks. It will be no larger than 128 KB larger than the decompressed size if flush isn't used. If flush is used, or some other block level API, then we could estimate way too large.

Example usage (without error checking):

```c++
std::string decompress(void* src, size_t size, size_t maxAlloc) {
    size_t const bound = std::min(maxAlloc, ZSTD_boundDecompressedSize(src, size));
    std::string out;
    out.resize(bound);
    out.resize(ZSTD_decompress(&out[0], out.size(), src, size));
    return out;
}
```

Edit: Implemented by @shakeelrao in PR #1543. This issue is left open to add support for legacy mode before the release.

**Comment by shakeelrao** [comment]
Hi @terrelln,

I'm fairly new to the project (have been using the CLI for benchmarking), but would be interested in implementing this feature. Do you have any additional starting points?

**Comment by terrelln** [comment]
1. Read the block header section of the [format spec](https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md#blocks). Each block has at most `Block_Maximum_Decompressed_Size` bytes.
2. We will loop over each frame in the input and either use the content size if available, or count the number of blocks and multiple by `Block_Maximum_Decompressed_Size`.
3. We can reuse the code in [ZSTD_findFrameCompressedSize](https://github.com/facebook/zstd/blob/dev/lib/decompress/zstd_decompress.c#L442). We can write a helper function which finds both the compressed size, and bounds the decompress size. Then `ZSTD_findFrameCompressedSize()` can return only the compressed size.
4. We should support multiple frames like [ZSTD_findDecompressedSize()](https://github.com/facebook/zstd/blob/dev/lib/decompress/zstd_decompress.c#L364).

**Comment by shakeelrao** [comment]
Thanks @terrelln. Is the following pseudocode the right approach?

```
bound = 0
for each frame in src:
  if Frame_Content_Size of frame exists:
    bound += Frame_Content_Size of frame
  else
    for each block in frame:
       bound += Block_Maximum_Decompressed_Size
```

Also, where is `Block_Maximum_Decompressed_Size` defined in the code?

**Comment by shakeelrao** [comment]
Now that I read more code, isn't this an adaption of `ZSTD_findDecompressedSize`, but instead of returning an error if `ZSTD_getFrameContentSize` return `ZSTD_CONTENTSIZE_UNKNOWN`, we calculate the block-based upper-bound?

**Comment by terrelln** [comment]
* `Block_Maximum_Decompressed_Size` is defined in the [spec](https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md#blocks) (you can search for the phrase).
* That pseudocode looks right. Note that we'll want to handle legacy frames. We can start by returning an error, and then add in support later.
* Yeah, it is exactly that. We can probably roll the block-based upper-bound into a helper also used by `ZSTD_findFrameCompressedSize()` so we avoid some code duplication.

**Comment by shakeelrao** [comment]
Should we leave this open until legacy mode is implemented or does it make sense to create a new issue for task?

**Comment by terrelln** [comment]
Lets leave it open, I'll edit the message.

**Comment by shakeelrao** [comment]
Alright, cool. Do you have any preference on who implements it?

**Comment by shakeelrao** [comment]
@terrelln Is there documentation on the legacy format? I'd be interested in implementing legacy support.

**Comment by terrelln** [comment]
There isn't explicit documentations, but they are all predecessors to zstd, so they are very similar.

Check out [ZSTD_findFrameCompressedSizeLegacy](https://github.com/facebook/zstd/blob/dev/lib/legacy/zstd_legacy.h#L181), and each implementation like [ZSTDv01_findFrameCompressedSize](https://github.com/facebook/zstd/blob/dev/lib/legacy/zstd_v01.c#L2002).

Lets start by using the macro [BLOCKSIZE](https://github.com/facebook/zstd/blob/dev/lib/legacy/zstd_v01.c#L1319), instead of inspecting the frame header, since it is a bit simpler, and I'm not 100% confident that `blockSize <= windowSize` for every legacy version. @Cyan4973 may be able to help here. The function `ZSTD_getFrameParams()` is available for versions >= 0.4. However, we only need legacy support so we can say that the bound always works, it isn't super valuable to be as tight as possible for legacy formats, so I don't think the complexity is worth the gains.

**Comment by shakeelrao** [comment]
Hmm, ok. Is the approach to simply calculate `# of blocks * BLOCKSIZE` then?

**Comment by shakeelrao** [comment]
Thanks, @terrelln! Does this mean that the upper-bound is computed by `# of blocks * BLOCKSIZE`?

Also, do you have any implementation specific suggestions? Should we modify each the `v0X` methods to return the compressed size and a compressed bound (as with `ZSTD_findFrameSizeInfo`? Not entirely sure how to approach this...

**Comment by shakeelrao** [comment]
Is this issue considered done now? Thanks again for all the help!

**Comment by terrelln** [comment]
Thanks @shakeelrao for implementing the decompress bound function!
