### ISSUE TITLE
compatible question

### ISSUE THREAD

**Issue by UncP** [facebook/zstd#1546]
Is 1.0.0 compatible with 1.3.4?
say i compress some data with v1.0.0, can i decompress these data correctly with v1.3.4?

**Comment by Cyan4973** [comment]
yes

**Comment by terrelln** [comment]
Additionally, if you compress with v1.3.4, you can decompress with v1.0.0. This holds for any versions >= 0.8.1.

**Comment by UncP** [comment]
good
