### ISSUE TITLE
Refuse to compress a dictionary with itself

### ISSUE THREAD

**Issue by Hello71** [facebook/zstd#1552]
I did `zstd -D dictionary --rm dictionary`.

**Comment by terrelln** [comment]
Sure, we can do that.

Notes for implementor:
* We have file comparison logic [here](https://github.com/facebook/zstd/blob/dev/programs/fileio.c#L519). We should extract that logic into a helper function `UTIL_isSameFile(char const* file1, char const* file2)`.
* Save the dictionary file name in the [cRess_t](https://github.com/facebook/zstd/blob/dev/programs/fileio.c#L632).
* Whenever we are compressing an input file, check if it is the same file name as the dictionary in  [FIO_compressFilename_srcFile](https://github.com/facebook/zstd/blob/dev/programs/fileio.c#L1311).
