### ISSUE TITLE
Failed to create compressed file contains 10w+ files

### ISSUE THREAD

**Issue by kmahyyg** [facebook/zstd#1560]
I have a folder contains 10w+ photos as a deep learning datasets, both use dictionary method or direct compress from command line will notice:

`zsh: argument list too long: zstd`

I wanna do:
- Create a zstd compress file contains 10w+ photos and a folder
- Make it use Compress Level 20

How to deal with this problem?

**Comment by kmahyyg** [comment]
```
╰─ ls -l| grep "^-"| wc -l                                                                                           ✔  6543  22:24:28 
100220
```

**Comment by terrelln** [comment]
If you just use `zstd` without `tar`, you will lose the file boundaries. You could do two things:

```
tar c ./train_data_2 | zstd -T0 -20 -o train_data_2.tar.zst
```

OR if you are using `zstd-1.3.8` or newer we allow you to set the compression level through an environment variable.

```
ZSTD_CLEVEL=20 tar --zstd cf  train_data_2.tar.zst ./train_data_2
```

**Comment by kmahyyg** [comment]
Thanks for your help.

**Comment by h4rd33p** [comment]
@terrelln 
MAC OS Catalina 10.15.7 | ZSTD v1.4.9
$ zstd ./files_bin/* --output-dir-mirror folder.tar.zst
-bash: /usr/local/bin/zstd: Argument list too long

exact command with exact version works on Linux (Amazon Linux 2)

**Comment by esemeniuc** [comment]
You can use the `-r` flag to recurse in a subdirectory
