### ISSUE TITLE
Is static library not enough static?

### ISSUE THREAD

**Issue by Geograph-us** [facebook/zstd#1564]
I tried your precompiled static library libzstd_static.lib with MSVC compiler like:
`cl  sqlite3.c  /0x -DSQLITE_API=__declspec(dllexport) -link -dll -out:sqlite3_zstd.dll libzstd_static.lib`

and got errors:
> libzstd_static.lib(zstd_v06.o) : error LNK2001: unresolved external symbol ___chkstk_ms
> libzstd_static.lib(zstd_v07.o) : error LNK2001: unresolved external symbol ___chkstk_ms
> libzstd_static.lib(huf_decompress.o) : error LNK2001: unresolved external symbol ___chkstk_ms
> libzstd_static.lib(fse_decompress.o) : error LNK2001: unresolved external symbol ___chkstk_ms
> libzstd_static.lib(huf_compress.o) : error LNK2001: unresolved external symbol ___chkstk_ms
> libzstd_static.lib(fse_compress.o) : error LNK2001: unresolved external symbol ___chkstk_ms
> libzstd_static.lib(hist.o) : error LNK2001: unresolved external symbol ___chkstk_ms
> libzstd_static.lib(zstd_v05.o) : error LNK2001: unresolved external symbol ___chkstk_ms
> libzstd_static.lib(fse_compress.o) : error LNK2019: unresolved external symbol ___udivdi3 referenced in function _FSE_normalizeCount

Next time I tried compile static library from source. I used "build.VS2015.cmd" and got new Win32-Release libzstd_static.lib (in 4 times bigger than original). With this library compilation was successful until I deleted the sources.
Now "static" library without zstd-source files show errors:

> libzstd_static.lib(zstd_compress.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
> zstd_compress.c : fatal error C1083: Cannot open compiler generated file: 'VS2010\bin\obj\libzstd_Win32_Release\zstd_compress.cod': No such file or directory
> LINK : fatal error LNK1257: code generation failed

**Comment by terrelln** [comment]
I think that the static library can only be compiled with MinGW. See Issue #1527.

**Comment by FBLeee** [comment]
Recompile，This method can be used to solve the problem of visual studio calling errors under Windows
```
https://www.jl1mall.com/forum/PostDetail?postId=202307051148000593125    
```
