### ISSUE TITLE
Update https://facebook.github.io/zstd/ to include Apache Cassandra

### ISSUE THREAD

**Issue by dineshjoshi** [facebook/zstd#1565]
Apache Cassandra now officially supports Zstd Compression. Could you please update the website to include Apache Cassandra? Ref: https://issues.apache.org/jira/browse/CASSANDRA-14482

**Comment by terrelln** [comment]
Sure! I will put up a PR soon. Is this image good for the logo https://commons.wikimedia.org/wiki/File:Apache-cassandra-icon.png? If not please let me know.

**Comment by dineshjoshi** [comment]
Here are the official logos for Apache projects: http://www.apache.org/logos/ There are various sizes and resolutions available. Please use v2 logo (eg. http://www.apache.org/logos/res/cassandra/cassandra-2_highres.png) and ensure that you refer to it as "Apache Cassandra". Thank you!

**Comment by Cyan4973** [comment]
Hi @dineshjoshi , I was looking for the `zstd` support official statement, or the PR where it's documented that it happened. I found this PR :
https://github.com/apache/cassandra/pull/292
Is this the correct one ?

**Comment by dineshjoshi** [comment]
Hi @Cyan4973 apologies for missing the reference when I created this issue. That is not the correct PR but here is the ticket on Apache Cassandra Jira board - https://issues.apache.org/jira/browse/CASSANDRA-14482

**Comment by Cyan4973** [comment]
Reference added

**Comment by dineshjoshi** [comment]
@Cyan4973 could you please identify it as "Apache Cassandra" and not just Cassandra. The official logo is here: http://www.apache.org/logos/res/cassandra/cassandra-2_highres.png

**Comment by Cyan4973** [comment]
It's a subtle issue of "space fairness",
looking at the list of references, I'm trying to keep all candidates to "about the same space".

Replacing the single word "Cassandra" by "Apache Cassandra" would give this specific project a larger spot. Plus, I would have to consider the same for similar projects, such as "Apache Hadoop", "Apache HBase", and then by extension why not "MongoDB WiredTiger", "Facebook Presto", and so on.

So I prefer to keep it as a small imprint list. Clicking on the link will lead to http://cassandra.apache.org/, so I suppose the association is still present.
