### ISSUE TITLE
Add PGO support for meson and LLVM/clang

### ISSUE THREAD

**Issue by tpgxyz** [facebook/zstd#1570]
Hi,

Meson build does not offer PGO build with GCC and specific flags/tools when LLVM/clang is uses as default compiler.

In Openmandriva we used this to enable PGO with meson and LLVM/clang
https://github.com/OpenMandrivaAssociation/zstd/blob/2203beba6095fb6b9221f476be77fd37b6c76086/zstd.spec#L67

**Comment by terrelln** [comment]
The Meson build system is maintained by the community. We'd gladly accept any pull requests to fix this!

**Comment by lzutao** [comment]
I believe PGO is supported by Meson. Use `meson configure -Db_pgo=on`
after setup your Meson build folder.

Helpful links:
- https://mesonbuild.com/Builtin-options.html#base-options
- https://mesonbuild.com/Configuring-a-build-directory.html

**Comment by tpgxyz** [comment]
@lzutao Well looks like Meson does not support LLVM/clang specific flags and tools when -Db_pgo is used

https://github.com/mesonbuild/meson/issues/5251

**Comment by lzutao** [comment]
Well, in this case I think we could either wait for official meson support
or use workaround ourselves.

**Comment by Cyan4973** [comment]
Closing.
Progresses on this topic seem dependent on a external project (meson).
