### ISSUE TITLE
LONG_TELL Build issues WINDOWS

### ISSUE THREAD

**Issue by ZRobison** [facebook/zstd#1591]
Hi,

I ran into an error when building with cmake using MinGW-W64 7.2.0 on windows.

It complains about  `LONG_TELL'  being defined in fileio.c.

There does not seem to be a  `LONG_TELL` defined in the `#elif defined(_WIN32) && !defined(__DJGPP__)` macro branch. 

I fixed this by just adding `#define LONG_TELL ftello64` and it seemed to work

**Comment by terrelln** [comment]
@Cyan4973 you wrote `LONG_SEEK` for this branch 2 years ago in https://github.com/facebook/zstd/pull/542. Do you have the context to fix `LONG_TELL` on this branch?

It seems that we don't have a test for it on Appveyor.

**Comment by Cyan4973** [comment]
I don't remember to be fair.
But the fact that `LONG_TELL` is not defined for configuration `defined(_WIN32) && !defined(__DJGPP__)` can only be a bug.

I'm surprised it did not show up before.

**Comment by Cyan4973** [comment]
The code for `defined(_WIN32) && !defined(__DJGPP__)` was added by @ds77 two years ago.

Then 3 months ago, @kostmo added `LONG_TELL` to "fix --list on truncated files ".
The `LONG_TELL` macro was not added to `defined(_WIN32) && !defined(__DJGPP__)` configuration. Nonetheless, it managed to pass all tests, and no one noticed.

So it seems this configuration is not tested on `Appveyor`. Not sure if we can improve that.
