### ISSUE TITLE
add --format=pigz & --format=pxz multi-threaded support

### ISSUE THREAD

**Issue by centminmod** [facebook/zstd#1592]
I just finished some [zstd 1.4.0 benchmarks](https://community.centminmod.com/threads/round-3-compression-comparison-benchmarks-zstd-vs-brotli-vs-pigz-vs-bzip2-vs-xz-etc.17259/) including testing  --format=gzip and --format=xz options and they seem to be single threaded. Would love to see zstd support multithreaded gzip via pigz and multithreaded xz via pxz as well for --format=pigz & --format=pxz :)

**Comment by terrelln** [comment]
I didn't look that closely, but it looks like those tools don't provide libraries, only command line tools.

Zstd uses the zlib and lzma libraries to provide support for `--format=gzip` and `--format=xz`. We'd have to shell out to the the respective CLIs to support `pigz` and `pxz`. I'd rather not do that.

If there widely used library for parallel xz or parallel zlib, I'd be happy to accept a PR that adds support.

**Comment by centminmod** [comment]
cheers @terrelln wouldn't I don't know inner workings of pigz or pxz or if there are such libraries or not.

**Comment by Cyan4973** [comment]
Closing. Such a feature would require advanced dependencies, that we prefer not to depend upon.
