### ISSUE TITLE
Website: used by: change the link to ClickHouse.

### ISSUE THREAD

**Issue by alexey-milovidov** [facebook/zstd#1596]
From https://github.com/yandex/ClickHouse/tree/master/contrib/libzstd
to https://github.com/yandex/ClickHouse/tree/master/contrib/
(or any other link you find appropriate)

because the library is included as a submodule now and the old link has rendered obsolete.

**Comment by Cyan4973** [comment]
Thanks for notification @alexey-milovidov !
Link has been updated
