### ISSUE TITLE
Extra bits on the sequence stream are ignored

### ISSUE THREAD

**Issue by klauspost** [facebook/zstd#1597]
It seems that any leftover bits on the sequence stream are ignored.

While it is debatable what it should do, it should either:

1) Cause an error or
2) Be specified in the spec

Here are a couple of samples with extra bits in the sequences:

[extrabits.zip](https://github.com/facebook/zstd/files/3109313/extrabits.zip)

**Comment by Cyan4973** [comment]
That's a good point @klauspost ,
the decoder must consume exactly all bits, and not more.
If some bits remain, it should be considered an error.
Something to clarify, and enforce.

**Comment by terrelln** [comment]
The patch now errors when it detects the bitstream isn't complete. This flags the error on all the inputs in `extrabits` except `0ef619d15539778c4ba2ec7fc51d526226a5b816`. That input "overflows" the bitstream and returns `BIT_DStream_overflow`. The overflowed data is ignored.
