### ISSUE TITLE
[stack usage] Reduce stack usage of HUF_sort()

### ISSUE THREAD

**Issue by terrelln** [facebook/zstd#1636]
Maninder Singh found that `HUF_sort()` is using 256 bytes of stack space, and reduced it to 128 bytes in https://lkml.org/lkml/2019/5/10/89.

`HUF_buildCTable_wksp()` takes a `workspace` parameter that we can move the `rank` table into. We'll just need to increase the size to account for it.

**Comment by felixhandte** [comment]
Closed via #1984.
