### ISSUE TITLE
Visual Studio issues

### ISSUE THREAD

**Issue by Absotively** [facebook/zstd#1639]
The Visual Studio 2010 projects for libzstd and libstd-dll have the setting to produce assembler listings turned on. At least in Visual Studio 2017, this usually causes linking to a copy of libzstd that was built on another machine to fail, because the existence of assembler listings somehow causes the linker to look for things by an absolute path that's stored when libzstd is built. It doesn't seem likely that most users are looking for assembler listings, and the other Visual Studio 2010 projects don't produce them, so I'd like to suggest they be turned off.

Also, the Visual Studio project for libzstd defines "ZSTD_DLL_EXPORT=1", which causes executables that use the static library to export the zstd api functions. This define should probably be removed from this project.

I can submit a pull request with these settings changes if that's helpful.

**Comment by Cyan4973** [comment]
sure !
