### ISSUE TITLE
1rd function call argument 'srcBuffer' is a pointer to uninitialized value

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [facebook/zstd#1648]
1rd function call argument 'srcBuffer' is a pointer to uninitialized value
https://github.com/facebook/zstd/blob/81276c4ee4a8572356d90382f5a1eaca7d24776c/programs/dibio.c#L317

in line 287, 'srcBuffer' is defined here but not initialized
https://github.com/facebook/zstd/blob/81276c4ee4a8572356d90382f5a1eaca7d24776c/programs/dibio.c#L287

**Comment by Cyan4973** [comment]
Why should it be initialized ?
It's going to be written to. At this invocation, it's a destination buffer.

**Comment by QiAnXinCodeSafe** [comment]
the function DiB_loadFiles() is declared here 
https://github.com/facebook/zstd/blob/8ac2831f3d2d52eb86837588e7579e883a0593fd/programs/dibio.c#L104

1rd argument is not initialized and assigned to 'buff' 
https://github.com/facebook/zstd/blob/8ac2831f3d2d52eb86837588e7579e883a0593fd/programs/dibio.c#L109

**Comment by felixhandte** [comment]
Right. We agree that `buffer` is uninitialized when it is passed to `DiB_loadFiles()`. Why is that a problem?

**Comment by QiAnXinCodeSafe** [comment]
'buffer' is uninitialized  and assigend to 'buff', Although the 'buff' is not used in function DiB_loadFiles()，but also not good code quality. 

at the same time， 'buff' is a never used variable, recommended deletion.

**Comment by felixhandte** [comment]
`buff` is used [here](https://github.com/facebook/zstd/blob/81276c4ee4a8572356d90382f5a1eaca7d24776c/programs/dibio.c#L127).

If you have a specific example of how zstd reads from uninitialized memory, especially one that can be demonstrated with msan, please re-open and provide a detailed description and/or instructions to reproduce the issue.
