### ISSUE TITLE
code coverage for zstd

### ISSUE THREAD

**Issue by heaven-hq** [facebook/zstd#1651]
Hi guys. I check out the zstd project and found that there's no code coverage tools.
Maybe we can add some code coverage tools to zstd, like Gcov or Lcov?

**Comment by Cyan4973** [comment]
That's an interesting possibility, 
though it takes time to understand how they work, and properly set them.

**Comment by terrelln** [comment]
We have coverage reports in OSS-Fuzz, but those aren't public.

I'd be happy to accept a PR that reports code coverage, as long as it is integrated with all of our tests (fuzzer regression testing, zstreamtest.c, fuzz.c, playTests.sh, etc.), and we can control which files/directories the coverage is reported over. E.g. I don't want to report coverage of `contrib/`, `docs/`, or `examples/`.

**Comment by heaven-hq** [comment]
@Cyan4973 @terrelln Thank you very much for reply. 
Next, I will try to submit a PR to finish this work.

**Comment by heaven-hq** [comment]
@terrelln   
Can it be achieved like the following?  
1. lib/Makefile add  compile option `-fprofile-arcs -ftest-coverage`：   
`GCOV = 0
ifeq ($(GCOV), 1)
GCOV_FLAGS = -fprofile-arcs -ftest-coverage
CFLAGS += $(GCOV_FLAGS)
endif`   

2. lib/Makefile clean target add commands to delete all of the files with .gcno and .gcna suffixes :
`	@$(RM) core *.o *.a *.gcno *.gcda *.$(SHARED_EXT) *.$(SHARED_EXT).* libzstd.pc
	@$(RM) common/*.gcno compress/*.gcno decompress/*.gcno dictBuilder/*.gcno legacy/*.gcno deprecated/*.gcno
	@$(RM) common/*.gcda compress/*.gcda decompress/*.gcda dictBuilder/*.gcda legacy/*.gcda deprecated/*.gcda`  

3. programs/Makefile add  compile option `-fprofile-arcs -ftest-coverage`：   
`GCOV = 0
ifeq ($(GCOV), 1)
GCOV_FLAGS = -fprofile-arcs -ftest-coverage
CFLAGS += $(GCOV_FLAGS)
LDFLAGS += $(GCOV_FLAGS)
endif`  

4. programs/Makefile clean target add commands to delete all of the files with .gcno and .gcna suffixes and other output files:  
`	@$(RM) core *.o tmp* result* ***.gcno** *.gcda dictionary *.zst \
        zstd$(EXT) zstd32$(EXT) zstd-compress$(EXT) zstd-decompress$(EXT) \
        zstd-small$(EXT) zstd-frugal$(EXT) zstd-nolegacy$(EXT) zstd4$(EXT) \
        *.gcda default.profraw have_zlib$(EXT) -rf ./outputfile *.info`  

5. tests directory add gcov.sh script，tests/Makefile add execute gcov.sh script：
`GCOVE = 0
test-zstd test-zstd32 test-zstd-nolegacy: datagen
	file $(ZSTD)
	ZSTD="$(QEMU_SYS) $(ZSTD)" ./playTests.sh $(ZSTDRTTEST)
ifeq ($(GCOVE), 1)
	ZSTD="$(QEMU_SYS) $(ZSTD)" ./gcov.sh
endif `

6. gcov.sh mainly executes the following command:
`cd ../programs
lcov -b ./ -d ./ -c -o outputfile.info
genhtml -o outputfile --prefix='pwd' outputfile.info
cd outputfile
firefox index.html&`

    First, add how to install the lcov tool and how to view the code coverage via add the variable GCOV=1  of the compile incoming parameters in the README，like `make GCOV=1;make check GCOV=1`
    When execute the make check GCOV=1 command, we will see the code coverage report as follows：
![codeCoverage](https://user-images.githubusercontent.com/51770115/60514992-3ae91400-9d0d-11e9-8be8-6be16e577228.PNG)

**Comment by Cyan4973** [comment]
Closing, duplicate #1728
