### ISSUE TITLE
Unnecessary records in `build/.gitignore`

### ISSUE THREAD

**Issue by dr15x86** [facebook/zstd#1673]
Hello.

At the end of the file `build/.gitignore` recently added two new entries:

```
build
lib
```

Which are too general and conflict, for example, with an existing `build/cmake/lib` directory. In addition, the `build/.gitignore` file already contains the entry` cmake/build/`.

I put the zstd source codes in the Node.js package. Npm parses the .gitignore files and skips the `build/cmake/lib` directory.

I propose to delete these records. Or, if these directories are created somewhere, limit the effect of these entries to only one level, using a slash:

```
/build/
/lib/
```

**Comment by Cyan4973** [comment]
Agreed
