### ISSUE TITLE
Dynamic linking libzstd?

### ISSUE THREAD

**Issue by zvezdochiot** [facebook/zstd#1680]
Dynamic linking libzstd?:
```
ldd zstd | grep zstd
(none)
```
PS:
```
./zstd -V
*** zstd command line interface 32-bits v1.4.0, by Yann Collet ***
```

**Comment by Cyan4973** [comment]
`zstd`, as the binary CLI program, doesn't link against the shared library `libzstd`.
It includes directly the static library `libzstd.a`.

One of the main reasons is that `zstd` enables multi-threading by default, while `libzstd` does not.

**Comment by zvezdochiot** [comment]
@Cyan4973 say> zstd enables multi-threading by default, while libzstd does not.

Ok. It's a pity.
