### ISSUE TITLE
Maybe there is a redundant command when execute the make test command.

### ISSUE THREAD

**Issue by heaven-hq** [facebook/zstd#1682]
I found an interesting thing,when execute the make test command,will generate twice of the following targets:zstdcli.o、util.o、timefn.o、fileio.o、benchfn.o、benchzstd.o、datagen.o、dibio.o、zstd.Which cased by `MOREFLAGS="$(MOREFLAGS)" $(MAKE) -j -C $(PRGDIR) allVariants` and `$(MAKE) -C $(TESTDIR) $@` two commands.

So when I add `-fprofile-arcs -ftest-coverage`  compile option to count code coverage，execute the make test and collect coverage data will report errors like 
```“stamp mismatch with graph file”
Processing xxx.gcda
xxx.gcda:stamp mismatch with graph file
geninfo: WARNING: gcov did not create any files for xxx.gcda!
```

Analysis is caused by build twice some files,make the .gcno and .gcda timestamps  inconsistent . when remove the command  `MOREFLAGS="$(MOREFLAGS)" $(MAKE) -j -C $(PRGDIR) allVariants`  will not affect the results of the make test, but also correctly count the code coverage data.

So I want to pull a request to remove the `MOREFLAGS="$(MOREFLAGS)" $(MAKE) -j -C $(PRGDIR) allVariants` command.

**Comment by Cyan4973** [comment]
It's not a good idea to remove test cases just to be more compliant with limitations of a coverage tool.

Alternative solutions include :
- Change the target of the coverage tool. 
  + In your case, changing from `make test` to `make -C tests test` would achieve the same goal as the proposed patch.
- More involved : find a way to execute the same tests, while being compliant with coverage tool limitation. This might be possible, but is definitely more involved, requiring to understand the details of the build system to properly modify them. A solution may exist, but is not guaranteed.

**Comment by heaven-hq** [comment]
Thank you very much for your advice.I think **Change the target of the coverage tool.** is effective！

Before that, I compared the log comparison before and after deleting **`MOREFLAGS="$(MOREFLAGS)" $(MAKE) -j -C $(PRGDIR) allVariants`** command.The test cases executed are actually the same.So I think this command is unnecessary.Maybe I understand it wrong?

**Comment by Cyan4973** [comment]
`make allVariants` is a compilation test, not a runtime test, 
so it doesn't participate to coverage testing.

But it is useful : it ensures that the binary can be compiled without warning using different build settings, a list of which can be found [here](https://github.com/facebook/zstd/tree/dev/programs#compilation-variables). We are checking "unusual" combination, such as compiling with only the compression, or only the decompression, with or without multi-threading, with minimal binary size, etc.

**Comment by heaven-hq** [comment]
I see. Thank you for your patience.
