### ISSUE TITLE
gcc8 doesn't suppress pointer-overflow properly

### ISSUE THREAD

**Issue by ephiepark** [facebook/zstd#1686]
Expected:
- signed-integer-overflow (pointer-overflow) from ubsan is supposed to be suppressed. 

Actual Behavior:
- ubsan test crashes with signed-integer-overflow (pointer-overflow)

Steps to reproduce:
- Go to commit b01c1c679f553cadb6630618b532873e284073a5
- `make gcc8install`
- `CC=gcc-8 make clean uasan-zstreamtest`
- `./tests/zstreamtest --newapi -t1 -T2mn -s6846`

Note:
I tried to fix this issue by appending `pointer-overflow` flag to `-fsanitize-recover=signed-integer-overflow` flag in main Makefile for ubsan. This fixes the issue for gcc8 but this causes another issue for gcc6 since it doesn't understand `pointer-overflow`.

**Comment by Cyan4973** [comment]
We only need 1 UBSAN test, and it's run with up to date version of `gcc`.
