### ISSUE TITLE
Parallel decompression.

### ISSUE THREAD

**Issue by tipiratio** [facebook/zstd#1702]
Afaik, parallel decompression is possible with special file format structure (lbzip2 and plzip implement this). Will this ever be considered to be implemented for zstd?

**Comment by Cyan4973** [comment]
The MT decoder design we have in mind is fairly different from the simpler splitting found in typical MT implementations. The advantage is that it would be compatible with any way data was compressed, and therefore would not rely on the encoder to pre-split data in a certain way. However, it's also more complex to implement.

So far, we have simply missed a good use case to justify investing in this direction. In most usages, `libzstd` is used single-threaded on a lot of small data (it's effectively multi-threaded, but on a lot of independent payloads).
Multithreaded decompression of a single frame only makes sense for some large data. While it may seem surprising, it's actually a minor application for `libzstd`. Moreover, whenever there is some large data, the bottleneck tends to be elsewhere (I/O). In which case, even single-threaded `zstd` ends up being faster than bottleneck, thus reducing usefulness of a multi-threaded variant.

That being said, if you absolutely want multi-threaded decompression, a solution exists : it's `pzstd`. It's been available in `contrib` directory for quite some time. This implementation compresses and decompresses using splitting, and therefore can decompress while multi-threading fairly easily.

**Comment by tipiratio** [comment]
Thanks a lot, pzstd is what I've been searching for. I'm wondering could pzstd also be compiled in MinGW, or does it require porting?

**Comment by Cyan4973** [comment]
cc @terrelln

**Comment by tipiratio** [comment]
I don't have too much clue about C++, but while waiting for the answer I've tried to just make the thing using MSYS2 with MinGW64. I received warning first:
`cc  -MMD -MP -MF util.Td   -I../../lib -I../../lib/common -I../../programs -I. -DNDEBUG -O3 -Wall -Wextra      -c ../../programs/util.c  -o ../../programs/util.o
../../programs/util.c: In function 'UTIL_countPhysicalCores':
../../programs/util.c:377:16: warning: cast between incompatible function types from 'FARPROC' {aka 'long long int (*)()'} to 'BOOL (*)(struct _SYSTEM_LOGICAL_PROCESSOR_INFORMATION *, DWORD *)' {aka 'int (*)(struct _SYSTEM_LOGICAL_PROCESSOR_INFORMATION *, long unsigned int *)'} [-Wcast-function-type]
  377 |         glpi = (LPFN_GLPI)GetProcAddress(GetModuleHandle(TEXT("kernel32")),
      |`
then the process continued until:
`g++ -MMD -MP -MF Pzstd.Td   -I../../lib -I../../lib/common -I../../programs -I. -DNDEBUG -O3 -Wall -Wextra -pedantic  -std=c++11 -c Pzstd.cpp  -o Pzstd.o
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:71,
                 from ../../programs/platform.h:126,
                 from Pzstd.cpp:9:
Logging.h:16:15: error: expected unqualified-id before numeric constant
   16 | constexpr int ERROR = 1;
      |               ^~~~~
make: *** [Makefile:254: Pzstd.o] Error 1`

**Comment by terrelln** [comment]
It looks like there would be some minor amount of porting required to get it working, but it should mostly work.

* The first error could be worked around by fixing up the ifdef's in `util.c` to work with MinGW https://github.com/facebook/zstd/blob/dev/programs/util.c#L357.
* The second can probably be fixed by renaming the variable, there is probably a macro of the same name.

If you get it working, I'm happy to accept a PR with fixes.
