### ISSUE TITLE
compile failure with cygwin in windows10 platform

### ISSUE THREAD

**Issue by bolunfeng** [facebook/zstd#1710]
hi:
   I want to compile the project in windows10 platform with cynwin,but I get the error:
  fengbolun@DESKTOP-AIFJCFI /cygdrive/e/software/gt_compress/3thparty/zstd/build/cmake
$ cmake .
-- ZSTD VERSION: 1.3.8
-- CMAKE_INSTALL_PREFIX: /cygdrive/e/software/gt_compress/3thparty/zstd/build/lib/%OS%/%COMPILER%/%BUILDTYPE%/zstd
-- CMAKE_INSTALL_LIBDIR: lib
-- ZSTD_LEGACY_SUPPORT not defined!
-- ZSTD_MULTITHREAD_SUPPORT is enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /cygdrive/e/software/gt_compress/3thparty/zstd/build/cmake

fengbolun@DESKTOP-AIFJCFI /cygdrive/e/software/gt_compress/3thparty/zstd/build/cmake
$ make
[ 36%] Built target libzstd_static
[ 73%] Built target libzstd_shared
[ 74%] Creating pkg-config file
[ 74%] Built target libzstd.pc
[ 75%] Linking C executable zstd-frugal.exe
CMakeFiles/zstd-frugal.dir/cygdrive/e/software/gt_compress/3thparty/zstd/programs/zstdcli.c.o:zstdcli.c:(.text+0x2669)：对‘_fileno’未定义的引用
CMakeFiles/zstd-frugal.dir/cygdrive/e/software/gt_compress/3thparty/zstd/programs/zstdcli.c.o:zstdcli.c:(.text+0x2669):  截断重寻址至相符: R_X86_64_PC32 针对未定义的符号 _fileno
CMakeFiles/zstd-frugal.dir/cygdrive/e/software/gt_compress/3thparty/zstd/programs/zstdcli.c.o:zstdcli.c:(.text+0x2670)：对‘_isatty’未定义的引用
CMakeFiles/zstd-frugal.dir/cygdrive/e/software/gt_compress/3thparty/zstd/programs/zstdcli.c.o:zstdcli.c:(.text+0x2670):  截断重寻址至相符: R_X86_64_PC32 针对未定义的符号 _isatty
CMakeFiles/zstd-frugal.dir/cygdrive/e/software/gt_compress/3thparty/zstd/programs/zstdcli.c.o:zstdcli.c:(.text+0x26c0)：对‘_fileno’未定义的引用
CMakeFiles/zstd-frugal.dir/cygdrive/e/software/gt_compress/3thparty/zstd/programs/zstdcli.c.o:zstdcli.c:(.text+0x26c0):  截断重寻址至相符: R_X86_64_PC32 针对未定义的符号 _fileno
CMakeFiles/zstd-frugal.dir/cygdrive/e/software/gt_compress/3thparty/zstd/programs/zstdcli.c.o:zstdcli.c:(.text+0x26c7)：对‘_isatty’未定义的引用
CMakeFiles/zstd-frugal.dir/cygdrive/e/software/gt_compress/3thparty/zstd/programs/zstdcli.c.o:zstdcli.c:(.text+0x26c7):  截断重寻址至相符: R_X86_64_PC32 针对未定义的符号 _isatty
CMakeFiles/zstd-frugal.dir/cygdrive/e/software/gt_compress/3thparty/zstd/programs/fileio.c.o:fileio.c:(.text+0x8f52)：对‘_fileno’未定义的引用
CMakeFiles/zstd-frugal.dir/cygdrive/e/software/gt_compress/3thparty/zstd/programs/fileio.c.o:fileio.c:(.text+0x8f52):  截断重寻址至相符: R_X86_64_PC32 针对未定义的符号 _fileno
CMakeFiles/zstd-frugal.dir/cygdrive/e/software/gt_compress/3thparty/zstd/programs/fileio.c.o:fileio.c:(.text+0x8f59)：对‘_isatty’未定义的引用
CMakeFiles/zstd-frugal.dir/cygdrive/e/software/gt_compress/3thparty/zstd/programs/fileio.c.o:fileio.c:(.text+0x8f59):  截断重寻址至相符: R_X86_64_PC32 针对未定义的符号 _isatty
collect2: 错误：ld 返回 1
make[2]: *** [programs/CMakeFiles/zstd-frugal.dir/build.make:115：programs/zstd-frugal.exe] 错误 1
make[1]: *** [CMakeFiles/Makefile2:307：programs/CMakeFiles/zstd-frugal.dir/all] 错误 2
make: *** [Makefile:130：all] 错误 2

I need your help!thanks.....

**Comment by LeeYoung624** [comment]
It seems like that you are using `make` on `Windows`, and this is wired : the CMake scripts of zstd is designed to use Visual Studio(via `MSBuild.exe`) to build `zstd` on `Windows`. Even more, the cmake scripts will not generate `Makefile` on `Windows`, instead the `Visueal Studio` files including `zstd.sln` should be generated after `cmake .`
I tested on Windows 10 with `zstd 1.3.8` and successfully build zstd with commands:
`MSBuild.exe .\zstd.sln`.

**Comment by felixhandte** [comment]
@bolunfeng, are you still having this issue? I've experienced this before when I had an unclean working directory from a previous build and then tried to continue the build with a different compiler. Try restarting the build from a clean slate?

**Comment by Cyan4973** [comment]
Closed, due to no feedback
