### ISSUE TITLE
mingw and cmake on windows ,I need your help!

### ISSUE THREAD

**Issue by bolunfeng** [facebook/zstd#1717]
When I compile with mingw and cmake on the windows platform, how should I set the cmake command parameters and set the compile condition? ---defined(_WIN32)

#elif defined(_WIN32) && !defined(__DJGPP__)

**Comment by bolunfeng** [comment]
D:\software\gt_compress\3thparty\zstd\programs\fileio.c:2287:73: warning: implicit declaration of function 'LONG_TELL'; did you mean 'LONG_SEEK'? [-Wimplicit-function-declaration]
                 unsigned long long file_position = (unsigned long long) LONG_TELL(srcFile);
                                                                         ^~~~~~~~~
                                                                         LONG_SEEK
[ 93%] Building C object programs/CMakeFiles/zstd.dir/D_/software/gt_compress/3thparty/zstd/programs/benchfn.c.obj
cd /d D:\software\gt_compress\3thparty\zstd\build\cmake\programs && D:\software\gt_compress\3thparty\win_lib\gcc_7.1.0\bin\gcc.exe -DXXH_NAMESPACE=ZSTD_ -DZSTD_LEGACY_SUPPORT=0 -DZSTD_MULTITHREAD @CMakeFiles/zstd.dir/includes_C.rsp -std=c99 -Wall -Wextra -Wundef -Wshadow -Wcast-align -Wcast-qual -Wstrict-prototypes -g   -o CMakeFiles\zstd.dir\D_\software\gt_compress\3thparty\zstd\programs\benchfn.c.obj   -c D:\software\gt_compress\3thparty\zstd\programs\benchfn.c
[ 95%] Building C object programs/CMakeFiles/zstd.dir/D_/software/gt_compress/3thparty/zstd/programs/benchzstd.c.obj
cd /d D:\software\gt_compress\3thparty\zstd\build\cmake\programs && D:\software\gt_compress\3thparty\win_lib\gcc_7.1.0\bin\gcc.exe -DXXH_NAMESPACE=ZSTD_ -DZSTD_LEGACY_SUPPORT=0 -DZSTD_MULTITHREAD @CMakeFiles/zstd.dir/includes_C.rsp -std=c99 -Wall -Wextra -Wundef -Wshadow -Wcast-align -Wcast-qual -Wstrict-prototypes -g   -o CMakeFiles\zstd.dir\D_\software\gt_compress\3thparty\zstd\programs\benchzstd.c.obj   -c D:\software\gt_compress\3thparty\zstd\programs\benchzstd.c
[ 96%] Building C object programs/CMakeFiles/zstd.dir/D_/software/gt_compress/3thparty/zstd/programs/datagen.c.obj
cd /d D:\software\gt_compress\3thparty\zstd\build\cmake\programs && D:\software\gt_compress\3thparty\win_lib\gcc_7.1.0\bin\gcc.exe -DXXH_NAMESPACE=ZSTD_ -DZSTD_LEGACY_SUPPORT=0 -DZSTD_MULTITHREAD @CMakeFiles/zstd.dir/includes_C.rsp -std=c99 -Wall -Wextra -Wundef -Wshadow -Wcast-align -Wcast-qual -Wstrict-prototypes -g   -o CMakeFiles\zstd.dir\D_\software\gt_compress\3thparty\zstd\programs\datagen.c.obj   -c D:\software\gt_compress\3thparty\zstd\programs\datagen.c
[ 98%] Building C object programs/CMakeFiles/zstd.dir/D_/software/gt_compress/3thparty/zstd/programs/dibio.c.obj
cd /d D:\software\gt_compress\3thparty\zstd\build\cmake\programs && D:\software\gt_compress\3thparty\win_lib\gcc_7.1.0\bin\gcc.exe -DXXH_NAMESPACE=ZSTD_ -DZSTD_LEGACY_SUPPORT=0 -DZSTD_MULTITHREAD @CMakeFiles/zstd.dir/includes_C.rsp -std=c99 -Wall -Wextra -Wundef -Wshadow -Wcast-align -Wcast-qual -Wstrict-prototypes -g   -o CMakeFiles\zstd.dir\D_\software\gt_compress\3thparty\zstd\programs\dibio.c.obj   -c D:\software\gt_compress\3thparty\zstd\programs\dibio.c
[100%] Linking C executable zstd.exe
cd /d D:\software\gt_compress\3thparty\zstd\build\cmake\programs && D:\software\gt_compress\3thparty\win_lib\CMake\bin\cmake.exe -E cmake_link_script CMakeFiles\zstd.dir\link.txt --verbose=1
D:\software\gt_compress\3thparty\win_lib\CMake\bin\cmake.exe -E remove -f CMakeFiles\zstd.dir/objects.a
D:\software\gt_compress\3thparty\win_lib\gcc_7.1.0\bin\ar.exe cr CMakeFiles\zstd.dir/objects.a @CMakeFiles\zstd.dir\objects1.rsp
D:\software\gt_compress\3thparty\win_lib\gcc_7.1.0\bin\gcc.exe  -std=c99 -Wall -Wextra -Wundef -Wshadow -Wcast-align -Wcast-qual -Wstrict-prototypes -g   -Wl,--whole-archive CMakeFiles\zstd.dir/objects.a -Wl,--no-whole-archive  -o zstd.exe -Wl,--out-implib,libzstd.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\zstd.dir\linklibs.rsp
CMakeFiles\zstd.dir/objects.a(fileio.c.obj): In function `FIO_analyzeFrames':
D:/software/gt_compress/3thparty/zstd/programs/fileio.c:2287: undefined reference to `LONG_TELL'
CMakeFiles\zstd.dir/objects.a(fileio.c.obj): In function `FIO_analyzeFrames':
D:/software/gt_compress/3thparty/zstd/programs/fileio.c:2287: undefined reference to `LONG_TELL'
collect2.exe: error: ld returned 1 exit status
programs\CMakeFiles\zstd.dir\build.make:259: recipe for target 'programs/zstd.exe' failed
make[2]: *** [programs/zstd.exe] Error 1
make[2]: Leaving directory 'D:/software/gt_compress/3thparty/zstd/build/cmake'
CMakeFiles\Makefile2:243: recipe for target 'programs/CMakeFiles/zstd.dir/all' failed
make[1]: *** [programs/CMakeFiles/zstd.dir/all] Error 2
make[1]: Leaving directory 'D:/software/gt_compress/3thparty/zstd/build/cmake'

**Comment by myzhang1029** [comment]
Hi, there! I think you are using an older version of zstd. Because the 2287th line of programs/fileio.c is no longer like that. Maybe you can try a newer version(i.e. after 1.4.1, there is a fix inside) of zstd?

**Comment by felixhandte** [comment]
Closing based on lack of response. Please re-open with more details if you still have this issue.
