### ISSUE TITLE
travis-ci build error: FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by jiangjufa** [facebook/zstd#1718]
travis-ci  build error: FileNotFoundError: [Errno 2] No such file or directory: 'test_dat.zst' -> 'test_dat_01_64_v0.5.0_dictio.zst,Who has encountered?

The link is as follows:
https://travis-ci.org/jiangjufa/zstd/builds/571708295

**Comment by felixhandte** [comment]
Closing as this isn't actionable. Please re-open with more context if you think this is an actual issue.
