### ISSUE TITLE
Codecov, an automation integration test platform, guarantees code quality

### ISSUE THREAD

**Issue by jiangjufa** [facebook/zstd#1728]
After the Travis CI is built, it is automatically integrated into the Codecov platform, and then shows the complexity and coverage of the circle; and its results can be configured to README.md, which we can visually view.
The following is the result of the results of its running：
![image](https://user-images.githubusercontent.com/28834227/63246854-36b18f80-c296-11e9-879e-8c05415b52d2.png)
![image](https://user-images.githubusercontent.com/28834227/63246888-4630d880-c296-11e9-9fec-c62fbaf8fc7a.png)

**Comment by jiangjufa** [comment]
@Cyan4973 What do you think of this, can I provide a PR?

**Comment by Cyan4973** [comment]
Hi @jiangjufa,

thanks for the suggestion,
it looks like a nice idea,
though I'm also interrogative about implied implications.

What does the Codecov indicator tells us ?

From what I understand, it's supposed to track activity in TravisCI, and reports which lines of codes were effectively triggered during tests.

This looks fine. As an internal or relative indicator, it may help to see when a new test was able to trigger some new lines, thus helping to justify that it's worth it. That's useful.

But as an absolute indicator, I'm worried it might send the wrong message. 55% coverage implies 45% not covered. So, does that makes 100% an objective ?

But not everything is tested in Travis. Only tests with "acceptable" time length are present there. Or Windows-related tests are on Appveyor for example.
The most complicated and longest tests are dealt with in different systems, which are not necessarily public. That's where we actively try to trigger these lines designed to handle "exceptional" cases.
So we'll never even target 100% on Travis CI.

Hence a follow up question is, how do we "educate" the public about this indicator ? Is it even useful for this indicator to be public to begin with ?

**Comment by jiangjufa** [comment]
Hi @Cyan4973 ,
Thank you for your reply，
I express my opinion：
55% means that 55% of the number of lines is a useful example coverage; if there is a PR integration, if there is no use case, this indicator is reduced; then this time should let the PR provider supplement the test case, otherwise it will not let Into the PR, in this case, he will consider the use of the scene, supplement the corresponding test cases, and then help to find some bugs that are considered in advance.

**Comment by jiangjufa** [comment]
Hi @Cyan4973 ,
I think we can try it, what do you think?

**Comment by Cyan4973** [comment]
We will pass for the time being.

Adding a new tool may seem like a good idea, at best it "brings something", at worst it does nothing, right ?
But such a view disregards its costs, in time, complexity, maintenance, confusion, dependency, etc. 

As we are currently underwater, so we can't just add something without a clear value of its benefit.
