### ISSUE TITLE
Stabilized advanced APIs should not require ZSTD_STATIC_LINKING_ONLY

### ISSUE THREAD

**Issue by vnair81** [facebook/zstd#1734]
v.1.4.0 was meant to stabilize advanced APIs.
Perhaps we should bring them out from ZSTD_STATIC_LINKING_ONLY now and only keep experimental stuff in that macro?

**Comment by Cyan4973** [comment]
In `v1.4.0`, a big chunk of the advanced API has been transferred into stable.

But not _everything_.

There are parts of the `ZSTD_STATIC_LINKING_ONLY` section which either require more time to become labelled "stable", or will never be part of "stable", or will disappear in the future.

Maybe we could label these intentions more accurately, so that users will not be surprised.

In the meantime, if you have a more precise question about a specific API entry, we can answer that here.

**Comment by vnair81** [comment]
Apologies for not being precise enough in my original query.
I was interested in functions which take `ZSTD_customMem` like `ZSTD_createCCtx_advanced` and `ZSTD_createDCtx_advanced`.

**Comment by Cyan4973** [comment]
Clear @vnair81 ,

these functions were intentionally left into the `ZSTD_STATIC_LINKING_ONLY` section.
For the time being, it is expected that these functions will remain indefinitely in this section, reasons being : 
- It's a seriously advanced use case, so we want to keep them in a section reserved for expert users only
- None of our use cases would require this capability coupled with a dynamic library linking. It seems that this capability is generally used in a context requiring static linking anyway.

Of course, this second point can be discussed. It was more a guide to justify this decision for `v1.4.0`.

Other relevant information : 
- There's no risk that these functions will disappear one day, they are actually useful, and their purpose cannot be replaced by existing "stable" API.
- There's a small risk that some of these functions may change in some minor way in some unspecified future. Though nothing like this is planned at this stage.

As usual, user feedback is valued when making informed decisions about API's future. "Stable" status is a very strong commitment, with direct implications for the maintenance and evolution of the library, so the bar is pretty high to get there. But it's obviously not "impossible". Just, "experimental" status is a lot more flexible, hence an easier place for advanced features.

**Comment by vnair81** [comment]
Thanks for the explanation Yann.
