### ISSUE TITLE
Document dictionary creation

### ISSUE THREAD

**Issue by KOLANICH** [facebook/zstd#1735]
For example it is unclear why

```python
default_dict_size = 110 << 10
zstd.train_dictionary(default_dict_size, [bytes(range(256))]*6)
```

fails with `ZstdError: cannot train dict: Src size is incorrect`. 

More precisely I have no idea

0. what these chunks are and what is the sense of splitting binary into chunks. How should I split for example a tarball? By files boundaries? By fixed size? Or by what?
1. why even one large enough chunk is insufficient
2. why I have to have at least 7 chunks
3. why exactly 7 and not 100

The error message is itself arcane, we need more error codes and more messages explaining what exactly is wrong and how to fix that.

**Comment by Cyan4973** [comment]
What is the language used in the 2-lines example ? Is that python ?

**Comment by KOLANICH** [comment]
It is. ztandard library with some patches to use the latest zstd.

**Comment by waldemar161** [comment]
как правильно работать с zstd-v1.4.3-win64,есть файлы zst но не могу их раскодировать,программу скачал,но не знаю как пользоватся

**Comment by KOLANICH** [comment]
@waldemar161
0. your question is offtop in this issue.
1. write in English.
2. the format of the files may be legacy. Legacy format support is usually disabled, need to be enabled using a macrodef.

**Comment by Cyan4973** [comment]
Should this question be rather directed at the Python implementation offering this interface ?

**Comment by KOLANICH** [comment]
I guess no. It just passes through the stuff done by a library.

>ZstdError: cannot train dict: Src size is incorrect.

is a result of error code returned by zstd lib. But it is unclear why it errors and what I should do about the errors.

**Comment by Cyan4973** [comment]
The `libzstd` API is quite different from the python prototype of your example code.
As a consequence, the equivalence between the two is not trivial, let alone the return value.
It must exists, it's just, someone has to read and understand the python wrapper code to clarify the relation between the two.

But even without that, there are a few striking points in your question.

>  what is the sense of splitting binary into chunks. How should I split for example a tarball?

That's not a correct thing to do.
If you are planning on compressing a tarball, then don't use dictionary training.
The outcome is most likely going to be negative.

Dictionary is only useful in the context of a _large quantity_ of small messages.
In which case, there is no chunking : each message is a sample.

Dictionary will save a few KB per message. That's a small gain ... except when messages are a few KB large.

But for a single big tarball, this is insignificant, and likely a lesser benefit than the cost of the dictionary itself.

> why I have to have at least 7 chunks

I don't remember if it's 7 or more. But the previous definition should give a hint : 
dictionaries are only useful to compress a lot of small messages.
If only a few samples are provided at training stage, it's a strong hint that this is not a valid use case for dictionary training.

**Comment by KOLANICH** [comment]
I use zstd to compress records in an SQLite database. Currently I compress per-record with a shared dict and it saves the half of the size of the db compared to compression without a shared dict. The devil is what to do when I don't have enough records now but expect them to appear in future. Taking in account that dict training can fail complicates the code.

**Comment by Cyan4973** [comment]
> I use zstd to compress records in an SQLite database. Currently I compress per-record with a shared dict and it saves the half of the size of the db

Yes, that's a good use case.

> what to do when I don't have enough records now but expect them to appear in future

If there are not enough records to train a dictionary, then it's probably not the right time to train a dictionary. It's also a sign that there is not so much data to save.

If you "expect them to appear in future", you might be able to infer their shape / characteristics, and from there, produce a set of synthetic samples that "look like" these future records. Such samples are perfectly valid for training. Just, the efficiency of the dictionary will be tied to how "realistic" are the synthetic samples.

If by "complicate" you mean you want to always invoke `ZSTD_compress_usingCDict()` unconditionally, even for data categories that don't have a dictionary yet, note this API comment : 
https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L816

> A ZSTD_CDict can be created from an empty dictBuffer

It's possible to create a `cdict` from a 0-sized buffer. In which case, the only thing it transports is the compression level. This makes it possible to always invoke `ZSTD_compress_usingCDict()`  with a `ZSTD_CDict*` argument.

**Comment by KOLANICH** [comment]
Thanks for the info.

**Comment by abionics** [comment]
Maybe it will be useful for somebody, use `notifications` flag in `zstandard` library in Python to see detail info:
```python
zstd.train_dictionary(default_dict_size, [bytes(range(256))]*6, notifications=4)
```
PS in my case the error was due to _"Total samples size is too large (5035 MB), maximum size is 4095 MB"_

**Comment by simon-liebehenschel** [comment]
This issue is the TOP result in the web search for `cannot compress: Src size is incorrect`. Sadly, this issue is as useless as the error message. 

Extending the message with more details would be very helpful. 

In my case the `cctx.compress` fails for some reason. 

---

Sorry for the noise. I've found a reason: `cctx.compress` was called with Python threading:
```py
with concurrent.futures.ThreadPoolExecutor() as executor:
    # `cctx.compress` is called here...
```
I wonder if `zstandard` can detect threads usage and show a meaningful warning instead of `Src size is incorrect`.
