### ISSUE TITLE
Training a dictionary is single-threaded

### ISSUE THREAD

**Issue by KOLANICH** [facebook/zstd#1738]
At least in both python bindings and `zstd` CLI app. Python bindings have some API to set count of threads, I set it to -1 to use all the available cores, but CPU load monitor reveals that it is single-threaded.

**Comment by Cyan4973** [comment]
nope : 

```
time zstd --train samples
system 99% cpu 15.927 total

time zstd -T2 --train samples
system 169% cpu 11.139 total

time zstd -T3 --train samples
system 242% cpu 8.599 total
```

**Comment by KOLANICH** [comment]
Oops. So for CLI  app I have to provide `-T` to use all the cores. When I set `-T0` it really works. BTW why not to make that behavior default? For python bindings .... it's strange. Needs investigation.

**Comment by Cyan4973** [comment]
The library `libzstd` can be compiled without multi-threading, in which case it always behave single-threaded.

**Comment by KOLANICH** [comment]
It can. But it is not in my case. When I have patched the python bindings to use fastCover I have managed to observe 100% CPU load for some time, but after that the load is dropped to 50% (I have a 2-core CPU).
