### ISSUE TITLE
Should common subset of ZDICT_cover_params_t and ZDICT_fastCover_params_t be moved into a separate struct and put it into the front of the struct, implementing inheritance this way?

### ISSUE THREAD

**Issue by KOLANICH** [facebook/zstd#1740]
Should common subset of ZDICT_cover_params_t and ZDICT_fastCover_params_t be moved into a separate struct and put it into the front of the struct, implementing inheritance this way?

**Comment by Cyan4973** [comment]
Why would inheritance matter ?

**Comment by Cyan4973** [comment]
cc @terrelln , who has more context about these structures

**Comment by terrelln** [comment]
We didn't go this direction when implementing `ZSTD_fastCover_params_t` because we didn't want to break users of `ZSTD_cover_params_t`. If there is a breaking change to the cover API, we may consider this.

**Comment by KOLANICH** [comment]
>Why would inheritance matter ?

For uniformity of use. Currently for allowing using both cover and fast cover I would have to patch too much in python binding, so the easiest way was to just replace cover with fastcover (taking in account that just cover is too slow to be anyhow usable).
