### ISSUE TITLE
For commerical usage, do we need any patent grants?

### ISSUE THREAD

**Issue by coldfog** [facebook/zstd#1747]
Hi, ZSTD is such an amazing compression algorithm and it will help us a lot in our product to reduce the package size and improve user experience. But we have noticed that, in 2018, there was a patent dispute between Facebook and REALTIME DATA LLC. 
https://litigationtools.maxval-ip.com/UnifiedPatentViewDocument/home/index?caseid=202073
https://news.bloomberglaw.com/ip-law/facebook-hit-with-patent-suit-over-data-compression-tech

Do you have further information about the status of this lawsuit? If we apply this algorithm in our product for commercial usage, do we need an extra patent grant from facebook or LLC and is there a potential legal risk about this patent grants？Thank you for your patience.

**Comment by Cyan4973** [comment]
There is no such need, from neither party.
The case was dismissed last year.
