### ISSUE TITLE
pip install zstd error

### ISSUE THREAD

**Issue by pyotam** [facebook/zstd#1768]
I am having trouble installing ZSTD on MacOS (Mojave version 10.14.6).
I have the OSX command line tools installed, I'm trying to install it in a conda environment.
I have tried both Python 3.7.4 and Python 3.6.3 environments.

gcc info:
`gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin` 

Error output:
`command: /Users/<my user_name>/anaconda3/envs/pysyft/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/1j/35_k3jw502vc385xbz9qj9qw0000gn/T/pip-install-g121mu55/zstd/setup.py'"'"'; __file__='"'"'/private/var/folders/1j/35_k3jw502vc385xbz9qj9qw0000gn/T/pip-install-g121mu55/zstd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/1j/35_k3jw502vc385xbz9qj9qw0000gn/T/pip-record-qn4ra0a5/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/1j/35_k3jw502vc385xbz9qj9qw0000gn/T/pip-install-g121mu55/zstd/
    Complete output (87 lines):
    running install
    running build
    running build_ext
    building 'zstd' extension
    creating build
    creating build/temp.macosx-10.7-x86_64-3.6
    creating build/temp.macosx-10.7-x86_64-3.6/zstd
    creating build/temp.macosx-10.7-x86_64-3.6/zstd/lib
    creating build/temp.macosx-10.7-x86_64-3.6/zstd/lib/compress
    creating build/temp.macosx-10.7-x86_64-3.6/zstd/lib/common
    creating build/temp.macosx-10.7-x86_64-3.6/zstd/lib/decompress
    creating build/temp.macosx-10.7-x86_64-3.6/src
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/<my user_name>/anaconda3/envs/pysyft/include -arch x86_64 -I/Users/<my user_name>/anaconda3/envs/pysyft/include -arch x86_64 -I/Users/<my user_name>/anaconda3/envs/pysyft/include/python3.6m -c zstd/lib/compress/zstd_compress.c -o build/temp.macosx-10.7-x86_64-3.6/zstd/lib/compress/zstd_compress.o -O2 -DVERSION="1.4.3.2" -DZSTD_MULTITHREAD=1 -Izstd/lib -Izstd/lib/common -Izstd/lib/compress -Izstd/lib/decompress
    In file included from zstd/lib/compress/zstd_compress.c:23:
    zstd/lib/compress/zstd_compress_internal.h:118:5: error: unknown type name 'ZSTD_literalCompressionMode_e'
        ZSTD_literalCompressionMode_e literalCompressionMode;
        ^
    zstd/lib/compress/zstd_compress_internal.h:207:5: error: unknown type name 'ZSTD_dictAttachPref_e'
        ZSTD_dictAttachPref_e attachDictPref;
        ^
    zstd/lib/compress/zstd_compress_internal.h:208:5: error: unknown type name 'ZSTD_literalCompressionMode_e'
        ZSTD_literalCompressionMode_e literalCompressionMode;
        ^
    zstd/lib/compress/zstd_compress_internal.h:321:5: error: use of undeclared identifier 'ZSTD_bounds'
        ZSTD_bounds const bounds = ZSTD_cParam_getBounds(cParam);
        ^
    zstd/lib/compress/zstd_compress_internal.h:322:22: error: use of undeclared identifier 'bounds'
        if (ZSTD_isError(bounds.error)) return 0;
                         ^
    zstd/lib/compress/zstd_compress_internal.h:323:17: error: use of undeclared identifier 'bounds'
        if (value < bounds.lowerBound) return 0;
                    ^
    zstd/lib/compress/zstd_compress_internal.h:324:17: error: use of undeclared identifier 'bounds'
        if (value > bounds.upperBound) return 0;
                    ^
    zstd/lib/compress/zstd_compress.c:67:50: error: use of undeclared identifier 'ZSTD_reset_parameters'
        {   size_t const err = ZSTD_CCtx_reset(cctx, ZSTD_reset_parameters);
                                                     ^
    zstd/lib/compress/zstd_compress.c:252:1: error: unknown type name 'ZSTD_bounds'
    ZSTD_bounds ZSTD_cParam_getBounds(ZSTD_cParameter param)
    ^
    zstd/lib/compress/zstd_compress.c:254:5: error: use of undeclared identifier 'ZSTD_bounds'; did you mean 'ZSTD_count'?
        ZSTD_bounds bounds = { 0, 0, 0 };
        ^~~~~~~~~~~
        ZSTD_count
    zstd/lib/compress/zstd_compress_internal.h:457:19: note: 'ZSTD_count' declared here
    MEM_STATIC size_t ZSTD_count(const BYTE* pIn, const BYTE* pMatch, const BYTE* const pInLimit)
                      ^
    zstd/lib/compress/zstd_compress.c:254:16: error: expected ';' after expression
        ZSTD_bounds bounds = { 0, 0, 0 };
                   ^
                   ;
    zstd/lib/compress/zstd_compress.c:254:17: error: use of undeclared identifier 'bounds'
        ZSTD_bounds bounds = { 0, 0, 0 };
                    ^
    zstd/lib/compress/zstd_compress.c:254:26: error: expected expression
        ZSTD_bounds bounds = { 0, 0, 0 };
                             ^
    zstd/lib/compress/zstd_compress.c:258:10: error: use of undeclared identifier 'ZSTD_c_compressionLevel'; did you mean 'ZSTD_p_compressionLevel'?
        case ZSTD_c_compressionLevel:
             ^~~~~~~~~~~~~~~~~~~~~~~
             ZSTD_p_compressionLevel
    /Users/<my user_name>/anaconda3/envs/pysyft/include/zstd.h:1005:5: note: 'ZSTD_p_compressionLevel' declared here
        ZSTD_p_compressionLevel=100, /* Update all compression parameters according to pre-defined cLevel table
        ^
    zstd/lib/compress/zstd_compress.c:259:9: error: use of undeclared identifier 'bounds'
            bounds.lowerBound = ZSTD_minCLevel();
            ^
    zstd/lib/compress/zstd_compress.c:260:9: error: use of undeclared identifier 'bounds'
            bounds.upperBound = ZSTD_maxCLevel();
            ^
    zstd/lib/compress/zstd_compress.c:261:16: error: use of undeclared identifier 'bounds'
            return bounds;
                   ^
    zstd/lib/compress/zstd_compress.c:263:10: error: use of undeclared identifier 'ZSTD_c_windowLog'; did you mean 'ZSTD_p_windowLog'?
        case ZSTD_c_windowLog:
             ^~~~~~~~~~~~~~~~
             ZSTD_p_windowLog
    /Users/<my user_name>/anaconda3/envs/pysyft/include/zstd.h:1011:5: note: 'ZSTD_p_windowLog' declared here
        ZSTD_p_windowLog,        /* Maximum allowed back-reference distance, expressed as power of 2.
        ^
    zstd/lib/compress/zstd_compress.c:264:9: error: use of undeclared identifier 'bounds'
            bounds.lowerBound = ZSTD_WINDOWLOG_MIN;
            ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/<my_user_name>/anaconda3/envs/pysyft/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/1j/35_k3jw502vc385xbz9qj9qw0000gn/T/pip-install-g121mu55/zstd/setup.py'"'"'; __file__='"'"'/private/var/folders/1j/35_k3jw502vc385xbz9qj9qw0000gn/T/pip-install-g121mu55/zstd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/1j/35_k3jw502vc385xbz9qj9qw0000gn/T/pip-record-qn4ra0a5/install-record.txt --single-version-externally-managed --compile Check the logs for full command output`

Let me know if you require any additional information.

**Comment by Cyan4973** [comment]
`pip install zstd` worked flawlessly on my own Mac laptop.

But more importantly, this repository is not in best position to support python-specific questions.
It might be better to look for support directly on the target python-zstd repository, which might be https://pypi.org/project/zstd/, or maybe https://pypi.org/project/zstandard/.

**Comment by pyotam** [comment]
Got it. Thanks. 
There is actually thread describing the exact same problem in one of the issues:
https://github.com/sergey-dryabzhinsky/python-zstd/issues/33

I will follow up there.
