### ISSUE TITLE
zstd educational decoder has incorrect baseline value for literal length symbol 35

### ISSUE THREAD

**Issue by bhushangparikh** [facebook/zstd#1774]
In zstd educational decoder the baseline value for last literal length is 65538

static const u32 SEQ_LITERAL_LENGTH_BASELINES[36] = {
    0,  1,  2,   3,   4,   5,    6,    7,    8,    9,     10,    11,
    12, 13, 14,  15,  16,  18,   20,   22,   24,   28,    32,    40,
    48, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768, 65538};

This does not matches to spec value of 65536

+----------------------+----------+----------------+
     | Literals_Length_Code | Baseline | Number_of_Bits |
     +----------------------+----------+----------------+
     |         0-15         |  length  |       0        |
     +----------------------+----------+----------------+
     |          16          |    16    |       1        |
     +----------------------+----------+----------------+
     |          17          |    18    |       1        |
     +----------------------+----------+----------------+
     |          18          |    20    |       1        |
     +----------------------+----------+----------------+
     |          19          |    22    |       1        |
     +----------------------+----------+----------------+
     |          20          |    24    |       2        |
     +----------------------+----------+----------------+
     |          21          |    28    |       2        |
     +----------------------+----------+----------------+
     |          22          |    32    |       3        |
     +----------------------+----------+----------------+
     |          23          |    40    |       3        |
     +----------------------+----------+----------------+
     |          24          |    48    |       4        |
     +----------------------+----------+----------------+
     |          25          |    64    |       6        |
     +----------------------+----------+----------------+
     |          26          |    128   |       7        |
     +----------------------+----------+----------------+
     |          27          |    256   |       8        |
     +----------------------+----------+----------------+
     |          28          |    512   |       9        |
     +----------------------+----------+----------------+
     |          29          |   1024   |       10       |
     +----------------------+----------+----------------+
     |          30          |   2048   |       11       |
     +----------------------+----------+----------------+
     |          31          |   4096   |       12       |
     +----------------------+----------+----------------+
     |          32          |   8192   |       13       |
     +----------------------+----------+----------------+
     |          33          |  16384   |       14       |
     +----------------------+----------+----------------+
     |          34          |  32768   |       15       |
     +----------------------+----------+----------------+
     |          35          |  65536   |       16       |
     +----------------------+----------+----------------+

-Bhushan

**Comment by Cyan4973** [comment]
Yes, that can't be the correct value.
To be fixed

**Comment by bhushangparikh** [comment]
Thank you,
-Bhushan
