### ISSUE TITLE
[Question] This is non-transparent?

### ISSUE THREAD

**Issue by Chaython** [facebook/zstd#1778]
By transparency; I mean like LZX in NTFS; the folder is accessible as a folder not as a file. An application can be launched without decompressing the entire folder...? I use LZX and Xpress for compressing most of my storage... I am looking for alternatives to these.
This is non-transparent? I only heard of this from a post about Linux kernel compression.
This only compresses as .zst ?
Is there any plans to make this transparent?

**Comment by chungy** [comment]
zstd is supported as the compression algorithm in at least btrfs (as well as zfs, though [not officially yet](https://github.com/zfsonlinux/zfs/pull/9024)). It is up to the work of file systems to implement zstd, not the zstd project itself.
