### ISSUE TITLE
Backwards streaming decompression?

### ISSUE THREAD

**Issue by ronnyli** [facebook/zstd#1810]
Hi, this is a bit of an odd question but I have a large `.zst` file of Reddit comments that I would like to decompress in reverse order. I tried using `tac` but no success:
```
# This command
tac myfile.zst | zstd -cdq

# Results in the following error
zstd: /*stdin*\: unsupported format 
```
I wouldn't be surprised if this isn't possible but I figure it's worth asking anyway.

Thanks in advance!

**Comment by Cyan4973** [comment]
Indeed, this will not work.

**Comment by ronnyli** [comment]
thanks for the fast reply!
