### ISSUE TITLE
No stable zdict.h API for rolling your own dictionaries

### ISSUE THREAD

**Issue by nigeltao** [facebook/zstd#1816]
`lib/dictBuilder/zdict.h` has the `ZDICT_trainFromBuffer` function to *train* a dictionary. There's other API (e.g. `ZDICT_params_t`, `ZDICT_finalizeDictionary`) that lets you *create* a dictionary from your own training algorithm. But that other API is not stable: it's behind an `#ifdef ZDICT_STATIC_LINKING_ONLY` guard, and my (Go) program does not static-link zstd.

See #1776 for motivation.

I know that "just bless the existing unstable API as stable" can be easier said than done. I just want a zstd-the-project issue to point people to if I'm asked why my program doesn't support zstd-the-format dictionaries yet.

**Comment by terrelln** [comment]
Are there any objections to stabilizing `ZDICT_finalizeDictionary()` in the next release?

**Comment by Cyan4973** [comment]
No objection regarding the goal itself, which I believe is a great and useful one.

We will probably have a discussion on the exact prototype to upgrade to "stable", 
it's not yet clear if upgrading the existing `ZDICT_finalizeDictionary()` verbatim is the best course of action.
