### ISSUE TITLE
ZSTD educational decoder fails when lit section compressed size > regenerated size

### ISSUE THREAD

**Issue by bhushangparikh** [facebook/zstd#1821]
In ZSTD educational decoder there is following check
    if (regenerated_size > MAX_LITERALS_SIZE ||
        compressed_size >= regenerated_size) {
        CORRUPTION();
    }
However ZSTD spec does not have any such requirement.
Is it added in educational decoder as a guideline to have efficient ZSTD compressor?

Thank you,
-Bhushan

**Comment by Cyan4973** [comment]
Hi @bhushangparikh ,

I believe you are right : this restriction is not part of the specification.

It happens that the reference encoder has been enforcing it, hence we had no counter-example. But being "efficient" only concerns the encoder. So this restriction should actually be removed from the decoder side.

**Comment by bhushangparikh** [comment]
Thank you for confirming.
-Bhushan

**Comment by Cyan4973** [comment]
@bimbashrestha, can you look into it please ?

**Comment by Cyan4973** [comment]
Fixed by @bimbashrestha .
