### ISSUE TITLE
ZSTD_dm_etc should be ZSTD_dct_etc

### ISSUE THREAD

**Issue by nigeltao** [facebook/zstd#1822]
Some files (e.g. in `lib/zlib.h`) have comments like "`the prefix is interpreted as raw content (ZSTD_dm_rawContent)`", which refers to names like:

- `ZSTD_dm_auto`
- `ZSTD_dm_rawContent`
- `ZSTD_dm_fullDict`

These should presumably be updated to:

- `ZSTD_dct_auto`
- `ZSTD_dct_rawContent`
- `ZSTD_dct_fullDict`

```
$ grep --files-with-matches --recursive ZSTD_dm_ .
./tests/fuzzer.c
./doc/zstd_manual.html
./lib/zstd.h
./lib/compress/zstd_compress.c
```

I'd make the PR myself, except that I'm not sure whether `doc/zstd_manual.html` should be manually updated or generated by some tool. In any case, it should be easy for y'all to fix.

**Comment by Cyan4973** [comment]
`doc/zstd_manual.html` is indeed automatically generated from `zstd.h`.

**Comment by Cyan4973** [comment]
fixed in `dev` branch
