### ISSUE TITLE
ZSTDMT_releaseAllJobResources memset's ZSTDMT_jobDescription, corrupting ZSTD_pthread_mutex_t and ZSTD_pthread_cond_t held in them

### ISSUE THREAD

**Issue by vnair81** [facebook/zstd#1830]
In `ZSTDMT_releaseAllJobResources` the following line is troublesome:
`memset(mtctx->jobs, 0, (mtctx->jobIDMask+1)*sizeof(ZSTDMT_jobDescription));`

Not only does this leak resources `ZSTD_pthread_mutex_t`/`ZSTD_pthread_cond_t` (`CRITICAL_SECTION`/`CONDITION_VARIABLE` on Windows), but also causes memory corruption in the scenario when the `ZSTDMT_CCtx` is reused after abandoning a compression job (by calling `ZSTD_CCtx_reset`).

In `ZSTDMT_freeCCtx` also, the correct call to dispose these resources `ZSTDMT_freeJobsTable` is after `ZSTDMT_releaseAllJobResources` which is causing leaks even in case the context is destroyed after each use.

**Comment by Cyan4973** [comment]
Thanks for pointing that out @vnair81 ,
we'll investigate.
