### ISSUE TITLE
1) Repeat Offsets across block boundaries 2) ZSTD decompress self-correction

### ISSUE THREAD

**Issue by SmitaKumar** [facebook/zstd#1833]
I have two questions

1) Can you confirm that the following is correct. 
In the ZSTD S/W implementation we cannot have back to back sequences with the same Match Offset and Literal Length of 0 within a Block. However, If the first sequence in a block has a Literal_length of 0 and a Match Offset = Repeated_Offset1, it cannot be encoded with a Repeated_Offset code as it falls into the exception category below.

> "There is an exception though, when current sequence's literals_length = 0. In this case, repeated offsets are shifted by one, so an offset_value of 1 means Repeated_Offset2, an offset_value of 2 means Repeated_Offset3, and an offset_value of 3 means Repeated_Offset1 - 1_byte."

2) I noticed this in the zstd_decompress code. Why is it self-correcting an error instead of flagging it as a corruption
 

>    size_t temp = (offset==3) ? seqState->prevOffset[0] - 1 : seqState->prevOffset[offset];
>                 ****temp += !temp;   /* 0 is not valid; input is corrupted; force offset to 1 */_****
>                 if (offset != 1) seqState->prevOffset[2] = seqState->prevOffset[1];
>                 seqState->prevOffset[1] = seqState->prevOffset[0];
>                 **_seqState->prevOffset[0] = offset = temp;_**

**Comment by Cyan4973** [comment]
1) Correct

2) At this point in the code, there is no way to bubble up an error. 
The idea is that, assuming an error (transmission, or bitflip, etc.), the flow of sequences (which are compressed with FSE) will quickly derail after this point, triggering an error, or if not (say, it's the last sequence), the checksum will catch the issue,
and assuming a malicious modification, this doesn't achieve much,
in particular, it cannot enforce a memory area in the buffer to remain uninitialized.

**Comment by SmitaKumar** [comment]
Thank you
