### ISSUE TITLE
IANA Structured Syntax Suffix Registry?

### ISSUE THREAD

**Issue by jonjohnsonjr** [facebook/zstd#1846]
Hello!

I see that you've gone through the process of registering the zstd media type: https://github.com/facebook/zstd/issues/767

Over in the OCI world, they recently merged a PR that uses `+zstd` as a media type suffix: https://github.com/opencontainers/image-spec/pull/788

But I noticed that it isn't actually in [the suffix registry](https://www.iana.org/assignments/media-type-structured-suffix/media-type-structured-suffix.xhtml). Have you considered [registering](https://tools.ietf.org/html/rfc6838#section-6) a `+zstd` suffix with the IANA registry?

**Comment by Cyan4973** [comment]
cc @mskucherawy

**Comment by Cyan4973** [comment]
We have a second round of minor clarifications going to IETF soon.
We can probably add the suffix registry item to the list.

**Comment by Cyan4973** [comment]
Just FYI : request is ongoing, the `zstd` RFC is being updated to integrate this new media type suffix.
Now mostly waiting for editorial delays (which can take a while).

**Comment by felixhandte** [comment]
Hi @jonjohnsonjr,

The IESG has approved our [update of the Zstd RFC](https://datatracker.ietf.org/doc/draft-kucherawy-rfc8478bis/) for publication. So `+zstd` will be registered when that gets through the RFC Editor's queue and is actually published, which should happen soon.

As such, I'm going to close this issue.

**Comment by Cyan4973** [comment]
The `+zstd` suffix is now officially IANA registered :
https://www.iana.org/assignments/media-type-structured-suffix/media-type-structured-suffix.xhtml
