### ISSUE TITLE
Is overlap log available in single threaded mode?

### ISSUE THREAD

**Issue by andrew-aladev** [facebook/zstd#1861]
Hello. Please review the [following code](https://github.com/facebook/zstd/blob/dev/lib/compress/zstd_compress.c#L323-L344).

Yesterday I've tried to use `overlapLog` with other params combinations. I've received `ZSTD_error_parameter_unsupported` when using `nbWorkers: 0` and `overlapLog: 9` with multithreaded support disabled.

Please consider wrapping overlapLog bounds using `ifdef ZSTD_MULTITHREAD`. Thank you.

**Comment by felixhandte** [comment]
Thanks for your report! I'll put up a PR to fix this.
