### ISSUE TITLE
[request for help] Undo zstd -r folder -o output.zst

### ISSUE THREAD

**Issue by twnaing** [facebook/zstd#1862]
This is not the issue of the zstd itself. This mess is created by me.

I didn't read enough the manual and run the following command
```
$ zstd -r folder -o output.zst
```

The following command gave me back a single file called output 

```
$ unzstd output.zst 
```

The output file has all the contents of the files under the folder concatenated.

Is there some tools or programs to un-concatenate the single file into multiple original files?

This is the only backup file I have and I need the backup.

**Comment by Cyan4973** [comment]
arf, no, unfortunately, all compressed frames are just stored back to back in the same file `output.zst`.

While there would be a way, at least in theory, to separate each frame, and therefore find the boundaries of each file, another problem is that none of these frames contain the file name, nor the position in directory tree. So you would end up with a bunch of nameless files.
Depending on your use case, that might be a start, or that might be useless.

The proper way to archive is to combine zstd with `tar`, which is in charge of preserving file metadata.

**Comment by twnaing** [comment]
@Cyan4973 Thank you for the information. 

Is there any tools or programs that can help me to separate each frame?

**Comment by Cyan4973** [comment]
None that I can think of off the top of my head.
By default, the CLI will just decompress all frames back-to-back into the same decompressed file, which is not the outcome you are looking for.

Most likely, you'll have to program it yourself, using the `lz4frame.h` decompression API.

**Comment by twnaing** [comment]
@Cyan4973 thank you again. I think I am out of my depth to program using `lz4frame.h`

**Comment by felixhandte** [comment]
I think @Cyan4973 probably meant zstd frame, not lz4 frame.

This is not necessarily all that difficult, although as mentioned you will not be able to recover filenames.  Each compressed file will be one zstd frame. So you can use `ZSTD_findFrameCompressedSize()`, for example, to partition the compressed file into separate individually compressed files, which you can then decompress. (Alternatively, a hacky version would just split the compressed file at every instance of "\x2b\xb5\x2f\xfd", which is the magic value that signals the start of a new frame.)

**Comment by terrelln** [comment]
@twnaing using the API you can call `ZSTD_findFrameCompressedSize()` to find the size of the first frame, decompress only that, and repeat the process at the second frame.

**Comment by Cyan4973** [comment]
> I think @Cyan4973 probably meant zstd frame, not lz4 frame.

Right :)

**Comment by twnaing** [comment]
Thank you all for the input. I will try to read on how to write a C program. It will take a while for me, I think.

**Comment by twnaing** [comment]
Meanwhile, what I should have run is described in https://github.com/facebook/zstd/issues/1526#issuecomment-464374334

**Comment by a1994sc** [comment]
@twnaing did you ever figure out how to get your files? I have the same problem

**Comment by terrelln** [comment]
@A1994SC 

```c
#undef NDEBUG
#define ZSTD_STATIC_LINKING_ONLY

#include <assert.h>
#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <zstd.h>

static uint64_t get_file_size(char const* filename) {
  FILE* f = fopen(filename, "rb");
  assert(f != NULL);
  int ret = fseek(f, 0L, SEEK_END);
  assert(ret == 0);
  long int const size = ftell(f);
  assert(size >= 0);
  fclose(f);
  return (uint64_t)size;
}

static void read_file(char const* filename, void* buffer, size_t size) {
  FILE* f = fopen(filename, "rb");
  assert(f != NULL);
  size_t const read = fread(buffer, 1, size, f);
  assert(read == size);
  char tmp;
  assert(fread(&tmp, 1, 1, f) == 0);
  fclose(f);
}

static size_t decompress_one_frame(char const* inputPtr, char const* inputEnd, char const* outputPrefix, int idx) {
  size_t const inputSize = (size_t)(inputEnd - inputPtr);
  size_t const compressedSize = ZSTD_findFrameCompressedSize(inputPtr, inputSize);
  assert(!ZSTD_isError(compressedSize));

  size_t const decompressBound = ZSTD_decompressBound(inputPtr, compressedSize);
  assert(decompressBound != ZSTD_CONTENTSIZE_ERROR);
  void* const decompressed = malloc(decompressBound);
  assert(decompressed != NULL);

  size_t const decompressedSize = ZSTD_decompress(decompressed, decompressBound, inputPtr, compressedSize);
  assert(!ZSTD_isError(decompressedSize));


  size_t const outputFileSize = strlen(outputPrefix) + 11;
  char* const outputFile = malloc(outputFileSize);
  assert(outputFile != NULL);
  {
    size_t const written = snprintf(outputFile, outputFileSize, "%s%d", outputPrefix, idx);
    assert(written < outputFileSize);
  }
  {
    FILE* f = fopen(outputFile, "wb");
    size_t const written = fwrite(decompressed, 1, decompressedSize, f);
    assert(written == decompressedSize);
    fclose(f);
  }

  free(outputFile);
  free(decompressed);
  return compressedSize;
}

int main(int argc, char** argv) {
  if (argc != 3) {
    fprintf(stderr, "USAGE: %s FILE.zst OUT-PREFIX\n", argv[0]);
    fprintf(stderr, "Decompresses a zstd file containing more than one frame to ${OUT-PREFIX}0, ${OUT-PREFIX}1, ...\n");
    return 1;
  }
  char const* const inputFile = argv[1];
  char const* const outputPrefix = argv[2];

  size_t const inputSize = get_file_size(inputFile);
  char* const input = malloc(inputSize);
  assert(input != NULL);
  read_file(inputFile, input, inputSize);

  char const* inputPtr = input;
  char const* const inputEnd = input + inputSize;
  int idx = 0;
  while (inputPtr < inputEnd) {
    size_t const compressedSize = decompress_one_frame(inputPtr, inputEnd, outputPrefix, idx);
    inputPtr += compressedSize;
    ++idx;
  }
  assert(inputPtr == inputEnd);
  free(input);
  return 0;
}
```

This program will work for you. If you write it into a file called `unzstd.c`, and have libzstd installed, you can compile it with `cc unzstd.c -lzstd -o unzstd`. Then, if the file you want to decompress is `input.zst` you can run:

```
mkdir output
./unzstd input.zst output/
ls output/
```

It will create one output file per input file that you compressed, in the order that they were compressed, named `output/0`, `output/1`, etc. So you'll lose the filenames, and the directory structure, but you will get all your files back.
