### ISSUE TITLE
Change default compression level

### ISSUE THREAD

**Issue by icebluey** [facebook/zstd#1871]
How can I change default compression level to 5 or other value when compiling zstd?

**Comment by senhuang42** [comment]
You can change your environment variable `ZSTD_CLEVEL` to something else with something like `export ZSTD_CLEVEL=5`, see: https://github.com/facebook/zstd/blob/dev/programs/README.md#restricted-usage-of-environment-variables

**Comment by terrelln** [comment]
You can define your own `ZSTD_CLEVEL_DEFAULT` during compilation. Just add `-D ZSTD_CLEVEL_DEFAULT=5` to your `CPPFLAGS`.

**Comment by icebluey** [comment]
@terrelln
CPPFLAGS="-D ZSTD_CLEVEL_DEFAULT=5" don't work.

CPPFLAGS="-DZSTD_CLEVEL=5 -DZSTDCLI_CLEVEL_DEFAULT=5" , this works!
