### ISSUE TITLE
strange lz4 occurence in Makefile

### ISSUE THREAD

**Issue by vtorri** [facebook/zstd#1879]
https://github.com/facebook/zstd/blob/dev/Makefile#L122

is it really lz4 ??

**Comment by felixhandte** [comment]
Yep: https://github.com/facebook/zstd/commit/5705d9f25a48c6af18d7e2b8430d99b64540c90d

This could be improved to `rm -rf lz4` I guess.

**Comment by vtorri** [comment]
ok, closing
