### ISSUE TITLE
Error 37 while decompressing

### ISSUE THREAD

**Issue by pgudadhe** [facebook/zstd#1881]
[ZSTD Corrupt File 2 RLE Blocks.zip](https://github.com/facebook/zstd/files/3832691/ZSTD.Corrupt.File.2.RLE.Blocks.zip)

Please find the following attached in ZIP file:
1) zstd compressed file.       [output_fail_rel.zst]
2) pdf file showing bit-by-bit analysis of the ZST file     [ZSTD Corrupt File 2 RLE Blocks.pdf]

I am seeing following error while decompressing. 
output_fail_rel.zst : Decoding error (37) : should consume entire input

But upon closely inspecting the file bit-by-bit I don’t seem to understand why there may be any problem with the file. As you can see in the pdf file, every byte of the ZST file is accounted for.
Also the educational decoder is able to decompress the file fine.
I would really appreciate if someone could look into this.

**Comment by terrelln** [comment]
Updating the zstd-1.4.4 will fix the issue.

How did you generate this file? The zstd compressor should never have generated a file like this.

We have a bug in the CLI that refused to decompress when the first block is a RLE block. Therefore, when we started generating RLE blocks in https://github.com/facebook/zstd/pull/1744, we won't generate an RLE block as the first block. This is a bug only in the CLI, not the library.

**Comment by pgudadhe** [comment]
Thank you so much @terrelln. Really appreciate the help. 
I am currently working on a randomized and parameter based data generator for ZSTD files.  It generated this file. 
Thanks again for your quick reply.

**Comment by terrelln** [comment]
> I am currently working on a randomized and parameter based data generator for ZSTD files. It generated this file.

Awesome! Let us know if there is anything we can do to help!
