### ISSUE TITLE
Error 36 while decompressing

### ISSUE THREAD

**Issue by pgudadhe** [facebook/zstd#1882]
(https://github.com/facebook/zstd/files/3832943/ZSTD.No.seq.corrupt.and.noncorrupt.files.zip)

Please find the following attached in ZIP file:
1) zstd compressed file.     [output_1blk_fail.zst]
2) zstd compressed file      [output_3blk_pass.zst]
3) pdf file showing bit-by-bit analysis of both ZST files [ZSTD No seq corrupt and noncorrupt files.pdf]

I am seeing following error while decompressing.
output_1blk_fail.zst : Decoding error (36) : Corrupted block detected

But upon closely inspecting the file bit-by-bit I don’t seem to understand why there may be any problem with the file with only 1 block because in the 2nd file with 3 blocks, the same blocks appears at the end. Surprisingly 2nd file gets compressed without any issues
[ZSTD No seq corrupt and noncorrupt files.zip]. 
You can see detailed bit-by-bit analysis of both files in the pdf file.
Also the educational decoder is able to decompress both files fine.
I would really appreciate if someone could look into this.

I am not sure if this issue is related to Issue #1881, but their characteristics seem different.

**Comment by terrelln** [comment]
This is a buggy zstd file.

1. It is using single-segment mode.
2. The frame content size is 21 bytes, which implies the window size is 21 bytes.
3. The compressed block size is 24 bytes.

This is invalid because the compressed block size must be <= the window size.

**Comment by terrelln** [comment]
Looks like we are missing a constraint in the spec. Initially we said "compressed blocks must not be larger than uncompressed blocks". But we removed it. Now we are missing the constraint that the "compressed block size must be no larger than the `Block_Maximum_Decompressed_Size`". It is a bug in the spec.

CC @Cyan4973

**Comment by Cyan4973** [comment]
Right, this is not explained clearly enough in the spec. To be updated.

**Comment by pgudadhe** [comment]
Again, thanks @terrelln & @Cyan4973 for your quick responses. 

To summarize:

I have a compressed block with a literal section containing 21 RAW bytes and sequence section containing no sequences.
When I have a frame containing only this compressed block:
My FCS = Window size = 21 Bytes.
Compressed block size = 21 raw bytes + 1 LIT section header + 1 SEQ section header byte + 1 # of sequences = 21 + 3 = 24 Bytes.
According to the rule, Compressed Block size <= Windows Size. So, this scenario is invalid.

In my 2nd file, I have a RAW block and a RLE block before the above mentioned compressed block.
Because of previous RAW & RLE blocks, the windows size is a lot bigger than 24 in this scenario. 
So, this scenario is valid. 

Could you please elaborate why this (Compressed Block size <= Windows Size) restriction is in place. I was just curious what must have been the reason behind it.

**Comment by terrelln** [comment]
> Could you please elaborate why this (Compressed Block size <= Windows Size) restriction is in place. I was just curious what must have been the reason behind it.

We define `Block_Maximum_Decompressed_Size` which is the minimum of 128 KB and the window size. By enforcing `Compressed_Block_Size <= Block_Maximum_Decompressed_Size` the decoder knows it can allocate a buffer of `Block_Maximum_Decompressed_Size` and it will fit any compressed block. This way the decoder can allocate its buffers at the beginning of the decompression operation, and know it will be large enough for every block, so it will never have to reallocate it.

`Block_Maximum_Decompressed_Size` is the min of 128 KB and window size, so that the decoder can save memory when the window size is small.

**Comment by Cyan4973** [comment]
In #1884, the text of the specification has been updated to better explain the meaning and purpose of `Block_maximum_size`.
This hopefully clarifies this issue.
You are welcomed to review the new text if you wish.

**Comment by Cyan4973** [comment]
Format specification updated
