### ISSUE TITLE
The return value of 'fread()' should be checked

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [facebook/zstd#1895]
https://github.com/facebook/zstd/blob/6a7f65117e8f270ff30f43855ef0efe63fb4b31f/programs/fileio.c#L1777

**Comment by terrelln** [comment]
We do check the output of `fread()` (it is in a while loop). But you're right, we should have a `ferror(finput)` after the loop.

**Comment by Cyan4973** [comment]
fixed by @selavy
