### ISSUE TITLE
Website: used by: MySQL

### ISSUE THREAD

**Issue by methane** [facebook/zstd#1912]
MySQL uses ZSTD to compress connections as of 8.0.18.
This is the release note:
https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-18.html#mysqld-8-0-18-connection-control

**Comment by Cyan4973** [comment]
Thanks for notification @methane .
The example was added into the ["reference"](https://facebook.github.io/zstd/#references) section.
