### ISSUE TITLE
Is there a way to search a compressed archive?

### ISSUE THREAD

**Issue by g666gle** [facebook/zstd#1915]
I am currently using tar to make an archive of many small files so there is more history for the compression. For example, I have "file.tar.zst" I'm curious if there is any possible way to search through the files without having to decompress the archive?

**Comment by Cyan4973** [comment]
Not that I'm aware of.
It can't be faster than searching though a non-compressed `.tar` file, 
and as far as I know, ` -t` and `--list` require a complete scan of the file.

**Comment by nabijaczleweli** [comment]
Well, to traverse the entire archive, you need to traverse the entire archive, but you can avoid writing it to disk like this `zstd -d owo.tar.zst -c 2>/dev/null | tar -t`, for example

**Comment by Cyan4973** [comment]
I believe @nabijaczleweli answers this question quite cleanly.
