### ISSUE TITLE
Resetting a CStream: Compressing without updating internal structures?

### ISSUE THREAD

**Issue by robertfeldt** [facebook/zstd#1919]
Is there a way to compress new data without affecting internal structures, i.e. so that I can reset the state back to the same state as before the latest call to compress?

The use case is:
- We have a very long string/stream which has been compressed already, C(s_long)
- We now have a set of N shorter strings S_shorts = [s1, ..., sN] and we want to calculate the length of compressing each one of them together with s_long, but without having to re-compress s_long. So we want to know length(C(s_long * s1)), length(C(s_long * s2)) and so on (where str1*str2 is the concatenation of string str1 with str2).
- Note that we only need the lengths of all the C(s_long * si), not their actual, compressed bytes.

Is there some way to reset the state of C(s_long) between each call to compress the shorter strings? Or would I have to copy the full CCtx between each call?

**Comment by felixhandte** [comment]
Zstd does not expose an API to duplicate/copy a `ZSTD_CCtx`. (I actually thought it did, but if you look at the [documentation](https://github.com/facebook/zstd/blob/dev/lib/compress/zstd_compress.c#L1740) for `ZSTD_copyCCtx()`, it only works for contexts that are not in the middle of a compression.)

So instead, I'd recommend using the dictionary API. If you `ZSTD_createCDict(s_long)`, you can then perform each compression using that dictionary (via `ZSTD_compress_usingCDict()` etc.). Zstd has ways to make the use of that dictionary quite efficient (it may not even have to copy the internal datastructures).

Note that the result will not perfectly match the incremental data you would get from compressing one of these candidate strings in the same stream as your prefix. Compressing with a dictionary will generate a new zstd frame, with a frame header etc. The other disadvantage is that the `ZSTD_createCDict()` step is a linear operation over the (large) prefix string, that is redundant with the work of compression you may have already done if you were already actually compressing the prefix.

Does that make sense?

**Comment by robertfeldt** [comment]
Thanks @felixhandte, for your quick reply.

Yes, it does make sense. I was thinking that going with a dict would be the alternative. However, I will also need to add to s_long incrementally and I don't see a way to update a dict? It is always done in "batch" mode from the whole set of strings/stream?

So, if I understand correctly even if the size of a CCtx is available it might not be enough to copy the memory? Ok, yes, I see it in the documentation now. Hmm, that is a bummer.

**Comment by felixhandte** [comment]
@robertfeldt, that's correct, dictionaries cannot at present be accumulated. (For simplicity and performance, we have stricter requirements around the internal compression datastructures when they're used as a dictionary than when they're used as the working context). It would be possible to change this... and maybe not even so very difficult.

To your other point, yeah. The `ZSTD_CCtx` is not [`TriviallyCopyable`](https://en.cppreference.com/w/cpp/named_req/TriviallyCopyable); it manages memory and contains internal pointers and so on. In theory, it is possible to create a function that would copy a `CCtx` that's part way through a streaming compression. I'm not sure we've ever seen a good use for that. But if you wanted to dig in and write that, I'd be happy to review / guide a pull request.

**Comment by felixhandte** [comment]
Closing based on inactivity. Feel free to re-open if you want to continue the conversation.

**Comment by Hello1024** [comment]
How hard would it be to allow ZSTD_copyCCtx to work when a frame is in progress? (but at the end of a block - ie. after a flush).    I think that would cover most usecases mentioned here.
