### ISSUE TITLE
Make zstd cmake use idomatically correct cmake install

### ISSUE THREAD

**Issue by ned14** [facebook/zstd#1922]
zstd currently uses idiomatically incorrect cmake install which breaks direct usage within other cmake which expects install to work as cmake says it ought to. I have a patchset fixing zstd's cmake at:

https://github.com/ned14/zstd/commit/ff6021046353cd91cbb1963ac943256029f0927c#commitcomment-36287624

... however I am unsure how compatible my changes are with cmake 2.8.

Are you open to accepting a PR fixing these issues, or would potential cmake 2.8 compatibility be a blocker?

**Comment by ned14** [comment]
For reference, the link above is to https://github.com/cpp-pm/hunter, a 100% cmake-based package manager. It only accepts packages with correct cmake install.

**Comment by bimbashrestha** [comment]
Thanks for submitting @ned14! I believe it would be good to retain cmake 2.8 compatibility. I'm not too familiar with the topic. While a fix for the issues you mentioned would certainly be very nice, we should first scope out what specifically the compatibility concerns on 2.8 would be with the patch you have in mind.

**Comment by Cyan4973** [comment]
> Are you open to accepting a PR fixing these issues, or would potential cmake 2.8 compatibility be a blocker?

The primary reason for the existence of such a limit is to remain compatible with CI environments. Since this limit was established, CI environments have evolved, and now generally support newer versions.

However, we can't just go directly to latest version, because the script is meant to be broadly usable for anyone trying to compile or install `zstd`. And there are various systems out there, too high version requirement would limit the nb of systems able to use the `cmake` script. 

So there must be a limit. But which one ?
As a generic rule, we have to be conservative.

Hence here is what I would suggest : 

- If there is a need for newer capabilities, which can't be used with current limit, ___define___ a new limit. 

   + The new limit should be defined as tight as possible, aka, the minimum version absolutely required to be compatible with the new `cmake` script. Do not over-provision by setting a large encompassing limit, this will reduce the nb of compatible systems.

    + The new limit must remain compatible with CI tests. If I've not missed something, it has been increased to <= 3.9.2. And if I'm wrong, a test is likely to fail somewhere.

**Comment by ned14** [comment]
@bimbashrestha My initial concern about cmake 2.8 compatibility was the use of `install(TARGETS ... EXPORT ...)` which I had thought a cmake 3-ism. But according to https://cmake.org/cmake/help/v2.8.12/cmake.html, it might just be supported, though how bug free I cannot tell.

@Cyan4973 Some perhaps useful data points:

- cmake 3.1 is widely considered to be the minimum viable for "modern cmake" of the kind as taught by Stephen Kelly et al.
- cmake 3.5 is what we at Boost chose as the minimum for Boost cmakeification. This was done after much research and argument, but essentially < 3.5 has a number of annoying bugs and quirks. You can work around all of them using cmake policies and custom cmake logic, but 3.5 won simply by being old enough it's widely supported, and 3.5 "just works" for modern cmake.

My suggestion would be therefore cmake 3.1 or 3.5 if 2.8 proves problematic. However I do feel concern that your CI isn't testing 2.8. If you're not testing it, you can't claim it works.

**Comment by Cyan4973** [comment]
Pinning `cmake` to a specific version is something we haven't done.
The version(s) were just inherited from environment.
For a long time, there was at least one CI using `v2.8.12`, but I can't find that anymore, so I guess they have all moved on.

It's interesting to force `cmake` to the minimum supported version, implying that it might trigger some implementation bugs which are not present in later version. We would need to learn how to do that.

**Comment by ned14** [comment]
> It's interesting to force cmake to the minimum supported version, implying that it might trigger some implementation bugs which are not present in later version. We would need to learn how to do that.

You are currently doing something unusual, which is setting a required minimum of 2.8.9, but then setting the policy defaults to whatever your current cmake is, up to some cmake version verified as working. That's plain weird if you don't mind me saying. If you tell cmake 3.15 that your cmake is 2.8.9, it'll emulate 2.8.9 for you (bar bug fixes). That's almost always what you want: choose your cmake poison, and adhere to that.

Me personally, I would have thought that what you're currently doing is buggy, because if you're not CI testing every cmake version from 2.8 to latest, you cannot be sure if that particular policy version set isn't broken on your cmake.

Regarding your cmake overall, it's not bad. It's targets based which is the most important thing. I'd personally mostly keep it as is.

**Comment by Cyan4973** [comment]
> if you're not CI testing every cmake version from 2.8 to latest, you cannot be sure if that particular policy version set isn't broken on your cmake.

I'm opened to CI tests improvements in this field.
We are no `cmake` experts , and `cmake` was initially purely "community driven". We had to step in a few times, to ensure consistency and evolution, but that's about it. Any advanced topic is likely off our radar.

**Comment by ned14** [comment]
> We are no cmake experts , and cmake was initially purely "community driven". We had to step in a few times, to ensure consistency and evolution, but that's about it. Any advanced topic is likely off our radar.

There are only a few cmake experts in the world.

As you may be aware, WG21 is pushing for build standardisation. To my current best knowledge, cmake will be one of the three build systems to fully support Modules. You should be able to graft support for that into your current cmake easily enough from my inspection of it, when the time comes.

Anyway PR is submitted. Thanks for your help on this.
