### ISSUE TITLE
Document/Request update to the "ZStandard is used by" section of references page

### ISSUE THREAD

**Issue by verticacrossman** [facebook/zstd#1927]
Request Vertica be added in the Databases section of https://facebook.github.io/zstd/#references. Vertica supports 3 modes of ZStandard as of our fall 2018 version 9.2. Here's the documentation link.
https://www.vertica.com/docs/9.3.x/HTML/Content/Authoring/SQLReferenceManual/Statements/encoding-type.htm?zoom_highlight=zstandard#Zstandar

Thanks

**Comment by bimbashrestha** [comment]
Sounds good @verticacrossman. It will be added:)

**Comment by Cyan4973** [comment]
Vertica reference added.
Thanks for notification @verticacrossman !
