### ISSUE TITLE
cpp check errors

### ISSUE THREAD

**Issue by Ornias1993** [facebook/zstd#1931]
Hi,
While checking the ZSTD library for use in ZFS, I got 2 cppcheck errors.

This might be worthwhile to have documented in an issue and/or fixed:

```
[contrib/zstd/compress/zstd_double_fast.c:99]: (error) Pointer addition with NULL pointer.
[contrib/zstd/compress/zstd_lazy.c:663]: (error) Pointer addition with NULL pointer.
```

**Comment by felixhandte** [comment]
Hi @Ornias1993, what version of Zstd are you working with? I believe @terrelln fixed this with #1903. Do you have the same issue with the current `dev` branch?

**Comment by Ornias1993** [comment]
Sorry, totally forgot to add the version:
1.4.4 on Debian 10

If 1903 is next version, you can close this :)

(any hint when next version is planned btw?)

**Comment by Ornias1993** [comment]
Checked, 1903 is not in 1.4.4... Closing this! :)
