### ISSUE TITLE
How to decompress an entire folder in their respective files?

### ISSUE THREAD

**Issue by chrisssj2** [facebook/zstd#1937]
I know I can decompress single files adding the -d command in an shortcut then dropping my files on the shortcut. Im not so techsavy. So it was already an achievement to find this out. But how do I do an entire folder? I have thousands of little files. which would dragging them solo be incredibly tedious.

**Comment by bimbashrestha** [comment]
Hi @chrisssj2, Thanks for posting the issue! 

You can compress files in their own folder using: 

`zstd -r folder`

Similarly, you can decompress files in their own folder using: 

`zstd -dr folder`

Hope I understood your question.

**Comment by Cyan4973** [comment]
Note that `zstd -r` will create one compressed file per source file.

If the goal is to generate a single compressed file containing a complete directory, preserving the full hierarchy and file metadata, this is usually done differently, using the `tar` command.

Here are similar questions, with answers : 
https://github.com/facebook/zstd/issues/1526
https://stackoverflow.com/questions/45355277/how-can-i-decompress-an-archive-file-having-tar-zst

and for context : 
https://www.phoronix.com/scan.php?page=news_item&px=GNU-Tar-1.31-Released
https://www.gnu.org/software/tar/manual/html_section/tar_68.html

**Comment by chrisssj2** [comment]
Thanks for your replies. I managed to get it working yesterday with the command  zstd -d -r directory
How is this different is this different then zstd -dr folder ?

**Comment by Cyan4973** [comment]
> How is this different

It's not.
`-d -r` is exactly identical to `-dr`.
Short commands (single letter) can be aggregated. --long-commands cannot.

See : https://github.com/facebook/zstd/tree/dev/programs#aggregation-of-parameters
