### ISSUE TITLE
Fuzz corpora source

### ISSUE THREAD

**Issue by sciencemanx** [facebook/zstd#1943]
I see that there are two options for generating corpora for the fuzz harnesses: downloading and local. Is there any difference between the two? (i.e. is the downloaded version the result of fuzzing + minset or is it generated in the same way as local?)

@terrelln

**Comment by terrelln** [comment]
The downloaded corpus is generated by oss-fuzz, and is the result of coverage it found. I may not have updated it in some time (probably since we changed the semantics of the fuzz input), so I will leave this issue open until I update it from the current oss-fuzz coverage.

**Comment by terrelln** [comment]
I just updated the GitHub corpus to the latest corpus generated by oss-fuzz.

**Comment by terrelln** [comment]
The locally generated seed corpora are the seeds for oss-fuzz. Then we upload them to our fuzz corpora release. oss-fuzz picks it up and uses it as a seed for the corpus it generates. Then we periodically update the seed corpus on our fuzz corpora release to reflect the latest coverage of oss-fuzz.

**Comment by terrelln** [comment]
Please reopen or file a new issue if you have further questions!
