### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [facebook/zstd#1953]
Memory is allocated
https://github.com/facebook/zstd/blob/6cf04c03443134f04c949707f46877a15d87bf79/doc/educational_decoder/harness.c#L36
but at the end of function，never free it

**Comment by lazka** [comment]
>  but at the end of function，never free it

The memory is freed by the caller.

**Comment by Cyan4973** [comment]
Yes, the code works.
I think it can be argued that the coding style is not so clear, and can be improved, so I will rewrite this function, just for clarify purpose.

**Comment by Cyan4973** [comment]
`harness` refactored to reduce risks of confusion (both human and static analyzers).
