### ISSUE TITLE
In-use training

### ISSUE THREAD

**Issue by grahamreeds** [facebook/zstd#1955]
I am looking into improving the compression of a messaging system.

Due to data concerns is there a way to train a dictionary while in use?

I have looked through the manual and had a quick dig through the zdict.h and it appears not.  Has anyone attempted or done something like this?  

What would be needed to implement this?  Is it unfeasible due to how the compression works?

**Comment by grahamreeds** [comment]
Found a partial answer to training in #1913

**Comment by Cyan4973** [comment]
> is there a way to train a dictionary while in use ?

This use case is different from #1913 and #1577, and

>  Is it unfeasible due to how the compression works?

yes, it's completely infeasible.
A dictionary is a clear state agreed upon by the sender and the receiver, so it must remain immutable.

The closest thing to what you are looking for is called the "Streaming mode".
In this case, both the sender and receiver preserve a state "in sync". But they can evolve together.
The state remains valid as long as the _frame_ is not closed.
But it's nonetheless possible to send data anytime using a _flush_ order.

The downside is that a state costs more memory, and there must be one state per connection direction. It works fine in pipeline mode, or more generally when the nb of connections is low enough for memory.
