### ISSUE TITLE
zlib is gzip or deflate?

### ISSUE THREAD

**Issue by 1137845831** [facebook/zstd#1966]
there is Compression Speed vs Ratio picture in README. So zlib is gzip or deflate? Because zlib include gzip and deflate

**Comment by Cyan4973** [comment]
`zlib`.
`gzip` tend to be slower.

**Comment by 1137845831** [comment]
zlib is  compress algorithm lib. zlib lib include gzip algorithm and deflate algorithm.So I means that is it gzip or deflate ?

**Comment by Cyan4973** [comment]
Actually, [`deflate`](https://www.ietf.org/rfc/rfc1951.txt) is the core compression format, present in both [`zlib`](https://www.ietf.org/rfc/rfc1950.txt) and [`gzip`](https://www.ietf.org/rfc/rfc1952.txt). Both are overlays on top of `deflate`. They vary in amount of metadata and checksum policy.

The benchmarked library is integrated into [lzbench](https://github.com/inikep/lzbench).
[This is the code](https://github.com/inikep/lzbench/blob/master/_lzbench/compressors.cpp#L1504) calling `zlib`. It invokes `compress2()`.

`zlib`, as a library, can also support `gzip` format. But by default, it produces `zlib` format, which is a bit faster and slightly more compact than `gzip`.

A different function like [`gzwrite()`](https://www.zlib.net/manual.html#Gzip) would instead produce `gzip` format.

**Comment by 1137845831** [comment]
ok,I know. Thank you
