### ISSUE TITLE
Question about the define of “LIKELY” and “UNLIKELY”

### ISSUE THREAD

**Issue by caoyzh** [facebook/zstd#1967]
the define of “LIKELY” and “UNLIKELY” :
[1] https://github.com/facebook/zstd/blob/dev/contrib/pzstd/utils/Likely.h#L23-L24
[2] https://github.com/facebook/zstd/blob/dev/lib/common/compiler.h#L155-L156

Referring to https://www.geeksforgeeks.org/branch-prediction-macros-in-gcc/, the following is more universal, and can void some warnings when the code is not standardized ( eg. judging pointer without relational operators). Is there any other consideration for not using this method?
#define LIKELY(x)   __builtin_expect(!!(x), 1)
#define UNLIKELY(x) __builtin_expect(!!(x), 0)

**Comment by Cyan4973** [comment]
`(x)` is itself a test, which means it's translated as `0` or non-zero.
`!!(x)` achieves the same, just forces the outcome of `(x)` to be a clear `0` or `1`.

Naively, `!!` represents 2 additional `NOT` operations, and therefore could introduce a performance penalty. I presume that a compiler with decent optimization can prove that these 2 operations do not change the outcome of the test, and therefore eliminate them for better runtime.
Well, that is, until it can't.

I suspect such change would have no impact on `zstd`, considering we use it rarely, and there is no place where the `(x)` test is strange, so the `!!` should be transformed into a no-op.

I don't see a clear case where `!!(x)` is helpful. In your example, you mention a test like `if (ptr)` (as opposed to `if (ptr!=NULL)`). I'm struggling to understand why `!!(x)` would help.

**Comment by terrelln** [comment]
The definition using `!!(x)` can work as well. It is more important for C++ where `!!` can be important to covert the object to a bool, therefore potentially calling the user-defined `operator bool`.
