### ISSUE TITLE
Improve documentation for open source contributors

### ISSUE THREAD

**Issue by terrelln** [facebook/zstd#1990]
Our documentation for how to develop and test a PR for open source contributors is lacking.
* Workflow for submitting a PR.
* Style guide / how big should your PR be / what should the summary be / what should you benchmark.
* How to run local tests and fuzzers. What does the continuous integration do?
* How to set up continuous integration in your repository.

**Comment by bimbashrestha** [comment]
We still need some documentation on benchmarking and style

**Comment by terrelln** [comment]
Related to #2102

**Comment by bimbashrestha** [comment]
Moving related issue tasks to this one and closing that one: 

TODO:
- How to measure optimizations
- Static analysis
- Style

**Comment by bimbashrestha** [comment]
I think the only thing remaining on this issue is the style documentation. And I recall we decided @Cyan4973 should be the one to do that. So I'm reassigning it.

**Comment by Cyan4973** [comment]
Coding style paragraph (finally) added
