### ISSUE TITLE
why we commit those patch files

### ISSUE THREAD

**Issue by HuKeping** [facebook/zstd#2000]
Is there any plan  to upstream those patches in directory `zstd/contrib/linux-kernel/`  to kernel?

**Comment by felixhandte** [comment]
@HuKeping, I believe they have all been merged. @terrelln would know for sure.

**Comment by terrelln** [comment]
@HuKeping all of those patches have been merged since 2017. What is not yet merged is:

* zstd support for initramfs
* zstd compressed x86 kernel

There has been renewed interest in these patches, so I am going to resubmit them soon.
