### ISSUE TITLE
--stream-size doesn't allow values greater than 4GB

### ISSUE THREAD

**Issue by lgarrison** [facebook/zstd#2006]
When I specify a stream size in the CLI that overflows a 32-bit unsigned int, I get an error like so:
```console
$ ./zstd --stream-size=4096MB
error: numeric value too large 
```

Internally, the CLI is using `size_t` as the type to store the stream size, so I think this is just a limitation of the option parser, which only supports U32 at the moment.

I've fixed this in my fork by adding another int parser that accepts `size_t` and applied it to the four CLI options whose internal variables are of type `size_t`.  The new int parser is just a copy-paste of the old one with the types changed to `size_t`, so this definitely isn't the most elegant way to solve the problem, just the quickest!  I've confirmed it fixes my original `--stream-size` problem.

Here's the diff: https://github.com/facebook/zstd/compare/dev...lgarrison:cli-allow-sizet

If you agree that this is the right place to fix the problem, I'm happy to open a PR and iterate on the solution.

**Comment by felixhandte** [comment]
Hi @lgarrison,

Thanks for the report! I took a quick look at your branch. Seems like a reasonable approach! Why don't you open a PR and we can dig in.

**Comment by felixhandte** [comment]
Oh cool, you do astrophysics stuff! I interned at the Harvard-Smithsonian Center for Astrophysics.

**Comment by Cyan4973** [comment]
I agree, this is a nice approach.
As you have already discovered, the function that reads numerical arguments is limited to `U32` range.
In the past, we did not need more, but with a command like `--stream-size=#`, it becomes possible to provide values larger than 4G. 
So yes, a PR is welcomed.
