### ISSUE TITLE
22 compression level file is 100 times bigger than on default

### ISSUE THREAD

**Issue by 532910** [facebook/zstd#2011]
xsession-errors size is about 16G it contains a lot of repeated lines
xsession-errors.zst is 1.4M
xsession-errors-ultra.zst 442M

**Comment by felixhandte** [comment]
That's surprising! Can you share any more details about the data you're compressing and how you're invoking Zstd to compress it?

**Comment by Cyan4973** [comment]
We recently identified an efficiency issue with very large files (> 3 GB) and `--ultra` mode.
It is fixed in current `dev` branch.
It can also be circumvented in any previous version by using the `--single-thread` command.

Could you try testing agin your file with : 
- the newer version in `dev` branch
- adding `--single-thread` to your command line ?

**Comment by 532910** [comment]
just `zstd` in the first case and `zstd --ultra -22` in the second

**Comment by 532910** [comment]
I'm using 1.4.4+dfsg-3 from debian.
With `--single-thread` the size is 1.3M
Should I try `dev` branch?

**Comment by Cyan4973** [comment]
Yes please,
it should give you an equivalent result, but without the need to specify `--single-thread`.

**Comment by 532910** [comment]
dev version output is also 1.3M but it's not absolutely identical:
```
1323322 xsession-errors2.zst # 1.4.4 + --single-thread
1323410 xsession-errors3.zst # dev without --single-thread
```

**Comment by 532910** [comment]
`dev` ans `1.4.4` with `--single-thread` produce absolutely the same output

**Comment by Cyan4973** [comment]
OK, so it seems that we have our answer.
Huge files (>3 GB) currently suffer from an efficiency issue when combined with `--ultra`.
This will be fixed in next release.
In the meantime, one can use `--single-thread` to circumvent the issue.

**Comment by 532910** [comment]
Is the different in output between _with_ and _without single-thread_ an new issue?

**Comment by Cyan4973** [comment]
No, it's always been the case.
We are just trying to keep the difference as small as possible,
but internally, there are some big differences in the data flow between multi-threaded and single-threaded, so there's no point trying to produce _exactly_ the same output.

**Comment by 532910** [comment]
Yann, thank you for explanation.
Should I close this issue or you need it untill release?

**Comment by Cyan4973** [comment]
I believe it can be closed.
The fix is already in, now it's just a matter to reach `release` status.
