### ISSUE TITLE
Confusing/misleading note in docs for ZSTD_c_compressionLevel

### ISSUE THREAD

**Issue by drakedevel** [facebook/zstd#2012]
This is the comment for `ZSTD_c_compressionLevel` this issue refers to (for quick reference):

https://github.com/facebook/zstd/blob/61eeca4bd66ecfa504441aadda5081f5c39e7aac/lib/zstd.h#L271-L277

I'm having trouble understanding what's meant by this note at the end:

>Note 2 : setting a level resets all other compression parameters to default

Given that note, I'd expect that if I call `ZSTD_CCtx_setParameter(cctx, ZSTD_c_compressionLevel, level)` it would have the effect of reverting any previous changes to the other compression parameters (like `ZSTD_c_windowLog`). 

That doesn't seem to actually be the case. If I set `windowLog`, and then change `compressionLevel`, `ZSTD_CCtx_getParameter` shows no change to `windowLog`. The logic in `ZSTD_getCParamsFromCCtxParams` appears to override the `compressionLevel`-based defaults with the requested compression parameters, so it doesn't look like changing `compressionLevel` can affect any compression parameters that were set explicitly. That's consistent with this comment on the advanced parameters:

https://github.com/facebook/zstd/blob/61eeca4bd66ecfa504441aadda5081f5c39e7aac/lib/zstd.h#L278-L280

If I'm not missing something and the `ZSTD_c_compressionLevel` note is just wrong/outdated, let me know and I'd be happy to submit a doc PR to update it.

**Comment by Cyan4973** [comment]
Good catch !
I believe this is outdated.

It used to be that setting the compression level would automatically update all dependent parameters.
This was changed in a later release: now setting the compression level only sets the compression level, which means it will later impact the compression parameters which are still set to "auto" mode, but not the ones which have been manually set.
This respect better a core concept of the advanced API : all parameters are sticky and can be set in an order (exceptions to that rule shall be expressly documented).

So yeah, this note should be updated.
