### ISSUE TITLE
pkg-config prefix check erroneously thinks libdir is not in prefix on macOS

### ISSUE THREAD

**Issue by andlabs** [facebook/zstd#2015]
I'm trying to build a fully static libarchive with a static zstd for an automated make build of a private program that will use this libarchive. I'm trying to do a dry run of this setup manually, but I've now run into a hurdle with zstd after e668c9b52896e1cf92c99da3b01e3bdbbae77100:

```
$ mkdir /tmp/libarchive; pushd /tmp/libarchive
$ git clone --quiet https://github.com/libarchive/libarchive.git libarchive
$ pushd libarchive; mkdir _prefix; popd
$ git clone --quiet https://github.com/facebook/zstd.git zstd
$ pushd zstd
$ make PREFIX=/tmp/libarchive/libarchive/_prefix
Makefile:235: *** configured libdir (/tmp/libarchive/libarchive/_prefix/lib) is outside of prefix (/tmp/libarchive/libarchive/_prefix), can't generate pkg-config file.  Stop.
make: *** [lib-release] Error 2
$ popd; popd
```

I'm at a loss as to what happened here. I thought lz4 could give a hint, but that codebase doesn't have this change. I also tried copying the relevant test into my shell, but I can't get it to produce anything other than a blank output, and I'm not even sure I am correctly making it valid for the shell (that is, stripping the make-isms).

I'm running macOS 10.12.6 with Version 9.2 (9C40b). Thanks!

**Comment by felixhandte** [comment]
Hey @andlabs, this is my fault. Seems like the regex I'm using is bad on OS X somehow. I'm going to back out that change and take another approach. Sorry for the trouble!

**Comment by andlabs** [comment]
No worries! I'm admittedly unclear as to what the regex is supposed to be / what it's trying to do.
