### ISSUE TITLE
zstdgrep wrapper not reporting errors such as access denied

### ISSUE THREAD

**Issue by trantor** [facebook/zstd#2020]
Hello.

I've noticed a basic, and important, problem with zstdgrep.
Comparing the wrapper with similar ones, such as zgrep or xzgrep, it seems to lack some logic in how to deal with errors.
Which is made obvious in the problem I've come across. When zstdcat is called by the wrapper and it exits with an error, e.g. permission denied accessing its file arguments, nothing is reported back to the user either in stdout or stderr.
Therefore as far as the user is concerned, everything went well and there was just no line matching the pattern in the input files. Which is not at all the case.

Needless to say, this is a fundamental problem with the wrapper script.

**Comment by Cyan4973** [comment]
Doesn't the utility return an error code > 0 ?

**Comment by trantor** [comment]
Hello @Cyan4973 . Yes, I guess it does, but that's pretty much useless when using it interactively.

Just to give you an example below:
```
$ sudo su
# echo PATTERN > /tmp/sample
# xz /tmp/sample
# chmod 600 /tmp/sample.xz
# ls -l /tmp/sample.xz
-rw------- 1 root root 8 feb 29 14:49 /tmp/sample.xz
# exit
$ xzgrep PATTERN /tmp/sample.xz 
xz: /tmp/sample.xz: Permission denied
$ zstdgrep PATTERN /tmp/sample.xz
$
```
I've used an `xz` file just to compare the two wrappers.
Now how is a user supposed to notice that the lack of output is not due to the absence of the string `PATTERN` in the sample file but to the fact the `zstdcat` cannot access the file?

[zgrep](http://git.savannah.gnu.org/gitweb/?p=gzip.git;a=blob;f=zgrep.in;h=16b86c29a714e69c3eb90026454dac232444fb6c;hb=HEAD#l199), which is, I guess, what wrappers such as `xzgrep` derive their code from, shows a clearly more complex (and meaningful) way to handle these situations than the few lines in `zstdgrep`. And since the wrapper was, I guess, meant to mimic the likes of `zgrep` in the first place, perhaps it should implement a similar way to handle basic error situations such as the one described above.

**Comment by trantor** [comment]
Thanks for the patch :)
