### ISSUE TITLE
Make ZSTDMT_JOBSIZE_MIN runtime configurable

### ISSUE THREAD

**Issue by romankarlstetter** [facebook/zstd#2043]
On low-end (but multicore) systems, having `ZSTDMT_JOBSIZE_MIN` set to [1MB](https://github.com/facebook/zstd/blob/66607d0eac54a99946ca14fee6af29fc525275c0/lib/compress/zstdmt_compress.h#L51) might be too large. Even for smaller buffers than 1MB, having multithreading enabled would be beneficial. Of course, I could compile with a lower value for `ZSTDMT_JOBSIZE_MIN`, but that is not very accessible for every user.

So, I thought it might be a good idea to have `ZSTDMT_JOBSIZE_MIN` configurable as a runtime parameter (like number of threads already is configurable), so that I can enable it already at smaller sizes.

As an alternative, it might be good to at least mention in the API documentation for the ZstdCompressor (I'm using the python API via `import zstandard`) that there is the limit of 1MB for parallel compression.

Here is an image illustrating the performance jump on an Intel Atom E3940 @ 1.6GHz (measurement is done via python in a jupyter notebook, compressor is initialized like that: `ZstdCompressor(zstd_level, threads=-1)`).
![2020-03-19 10_50_35-ZSTD compression throughput test](https://user-images.githubusercontent.com/1151415/77054141-ab38e200-69cf-11ea-8280-cc17205efb8e.png)

**Comment by terrelln** [comment]
Related to #2071

**Comment by Cyan4973** [comment]
`jobSize` is already configurable as runtime parameter.

The lower limit `ZSTDMT_JOBSIZE_MIN` has been reduced to 512 KB in #2611.
 It can also be set to any other value at compilation time if need be.
