### ISSUE TITLE
can't compress binary data 

### ISSUE THREAD

**Issue by JsBlueCat** [facebook/zstd#2044]
[test.zip](https://github.com/facebook/zstd/files/4364752/test.zip)
i try test file 
but i find the zstd can't compress test file 
```bash
zstd test
```

**Comment by terrelln** [comment]
That means the file isn't compressible. Zstd cannot find any matches.

It is possible that the file is already compressed, encrypted, or just random data.

E.g. this file isn't compressible because it is random noise:

```
> head -c 1000000 /dev/urandom > test
> zstd test
test                 :100.00%   (1000000 => 1000037 bytes, test.zst)
```

**Comment by JsBlueCat** [comment]
> That means the file isn't compressible. Zstd cannot find any matches.
> 
> It is possible that the file is already compressed, encrypted, or just random data.
> 
> E.g. this file isn't compressible because it is random noise:
> 
> ```
> > head -c 1000000 /dev/urandom > test
> > zstd test
> test                 :100.00%   (1000000 => 1000037 bytes, test.zst)
> ```

but if i read the data and translate it to ascii code , i use gzip the file can be compressed..

**Comment by terrelln** [comment]
When you translate it to hex you are expanding the original file by a factor of 2. When you compress that file with gzip OR zstd you will recover approximately the original file size, because we will find that redundancy with Huffman encoding.

**Comment by JsBlueCat** [comment]
> When you translate it to hex you are expanding the original file by a factor of 2. When you compress that file with gzip OR zstd you will recover approximately the original file size, because we will find that redundancy with Huffman encoding.

its so wired, this file is made by  random chose ascii data and translate to binary file. but can zstd can compress this file ?

**Comment by terrelln** [comment]
Neither zstd nor gzip can compress random data. You'll see that gzip compresses the file you sent to approximately the same size as zstd.

If you have 8 MB of random data you will never be able to compress it to less than 8 MB.

If you have 8 MB of data and translate it into 16 MB of hex, then you'll be able to compress it back to 8 MB, but never below 8 MB.

It is impossible, because there is no redundancy by definition.

**Comment by JsBlueCat** [comment]
> Neither zstd nor gzip can compress random data. You'll see that gzip compresses the file you sent to approximately the same size as zstd.
> 
> If you have 8 MB of random data you will never be able to compress it to less than 8 MB.
> 
> If you have 8 MB of data and translate it into 16 MB of hex, then you'll be able to compress it back to 8 MB, but never below 8 MB.
> 
> It is impossible, because there is no redundancy by definition.

\x8b|z\x17\x1d\x90#\x9a\xd9e\x16/-\xe3hm7\x8f\xd1\x8e\x8e\xbd\xbe\x85\x1a~C\xb0\x89$\xc3\x8c,\xec\x89\xcb\xcf\xf4\xe2$\xc6\xdf\xc8\x062p\x89\xe1|\xaaB<\xc9\x14\xc7e\x01L\xc1\xf4$\r\xcfL\x06\xd1\xdc\xa8\xd0o\xfc\x9e\x9fa\xd4\xa1\xa1>\x82\x84\x94\x85YL\x94\x91\xfa\xa5\x91\x0c\x97E\xb5W#B^H7{]Q\xac\x9fM\xda\xd0\xb0\x12\x90\xc1\x7fq\x91\x9f.,E\xf5\x9cjF\xc3\x08\xea;J?\xff>M>\x1c\x864I\xf0\x9a\xf8A\x8fj/l3\x1a6\xe6i\xbc_\xe5\xd2n\x07\xd9WZ.\x86\xa7\xa4k\x1c\x97E\xb6\xfd\xa9\x0c\xcfst\x80\xd3_{\xc2\xd9\xa4\x03n\xfcrv\xad\xcf\xa6\x85U\x10\n
the data is like this.   all code was encoded with ascii and end with \n

**Comment by terrelln** [comment]
* What is the original file size?
* What is the gzip compressed file size (of the binary data)?
* What is the file size when translated to ascii?
* What is the gzip compressed file size of the ascii data?

**Comment by JsBlueCat** [comment]
> * What is the original file size?
> * What is the gzip compressed file size (of the binary data)?
> * What is the file size when translated to ascii?
> * What is the gzip compressed file size of the ascii data?

in another words，can zstd compress the above btyes？ if not， could you give some suggestions？ i‘m sure that this file can be compressed
