### ISSUE TITLE
Q: Concurrent stream compression feedback

### ISSUE THREAD

**Issue by klauspost** [facebook/zstd#2046]
I am gearing up to add concurrent stream compression to the Go zstandard library.

In terms of implementation, my thoughts mainly go to split up the input into chucks (term used to not confuse it with other stuff) bigger than blocks and compress these chunks separately, but provide a history for the first blocks of each chunk to initialize each chunk with the previous content. Everything is still emitted as a single frame.

That way a number of chunks could be 'in flight' on different codes and the output should just be appended in correct order.

Implementation notes: https://gist.github.com/klauspost/87644c642e92b0acda3c7968c4786b79

With your experience would that be a reasonable approach? The only real downside is the higher memory usage which seems pretty unavoidable.

Apologies if this is not the proper forum to ask. I looked around for something more suitable.

**Comment by Cyan4973** [comment]
If I do understand your question correctly, you want to create a fully decodable `zstd` frame, just use multithreading in order to compress faster.

In this case, yes, the method you describe looks correct. It's similar to what has been implemented in [zstdmt](https://github.com/facebook/zstd/blob/dev/lib/compress/zstdmt_compress.c).

**Comment by klauspost** [comment]
> You will have to disable them for the first 3 sequences of each chunk.

I already do, since I compress finished sequences/literal values separately and want to be able to just switch to an uncompressed block in case it doesn't compress.

That allows me to start matching the next block without having to wait for output block compression.

Thanks. Just wanted to confirm I didn't do anything silly :)

**Comment by Cyan4973** [comment]
This is variable.

Default chunk size is `4 x windowSize`, so it varies with compression level.
The amount of history varies too : it's `windowSize / 8` for "fast" levels, then it gradually increases towards full `windowSize` on reaching highest compression levels.

**Comment by klauspost** [comment]
Makes sense. Thanks for the information!
