### ISSUE TITLE
will gpu accelerate the compress process？

### ISSUE THREAD

**Issue by JsBlueCat** [facebook/zstd#2049]
will gpu accelerate the compress process？

**Comment by terrelln** [comment]
We don't believe so. LZ77 match finding isn't well suited to GPUs. There have been some interesting papers for Huffman & FSE compression on GPUs. But, the cost to transfer the data to and from the GPU vastly outweighs the benefits.

**Comment by JsBlueCat** [comment]
> But, the cost to transfer the data to and from the GPU vastly outweighs the benefits

Oh, what's about FPGA?

**Comment by bimbashrestha** [comment]
A little related: https://github.com/facebook/zstd/issues/1502

**Comment by bimbashrestha** [comment]
Hi @JsBlueCat, 

I'm not too familiar with FPGAs but a quick google search shows that a number of people have had success adapting LZ algorithms (including [LZ4](https://github.com/Xilinx/Applications/tree/master/data_compression/xil_lz4)) to them. No such attempt has been made for zstd to my knowledge. From my naive perspective, I can imagine this being an interesting area of investigation. 

Are you thinking about pursuing a FPGA adapted implementation of zstd? If you have ideas/plans for doing something like this, i'm happy to support in anyway I can:)

**Comment by JsBlueCat** [comment]
> Hi @JsBlueCat,
> 
> I'm not too familiar with FPGAs but a quick google search shows that a number of people have had success adapting LZ algorithms (including [LZ4](https://github.com/Xilinx/Applications/tree/master/data_compression/xil_lz4)) to them. No such attempt has been made for zstd to my knowledge. From my naive perspective, I can imagine this being an interesting area of investigation.
> 
> Are you thinking about pursuing a FPGA adapted implementation of zstd? If you have ideas/plans for doing something like this, i'm happy to support in anyway I can:)

sorry for that , i'm trying use FPGA to accelerate the compress process but failed.

**Comment by bimbashrestha** [comment]
Ah okay, well I'll close this for now. And we can re-open if either of these topics become interesting again.
