### ISSUE TITLE
License concern

### ISSUE THREAD

**Issue by zhangfuwen** [facebook/zstd#2052]
Hi, 

We are using zstd, and are now encountering a license problem and we hope you can help us with some clarification or modification.
zstd is basically a dual license project but we've found three files have a different license announcement with other files. 
one of the different files is `zstd/lib/compress/zstd_ldm.c`.

Other files' license announcement says dual license and 

    You may select, at your option, one of the above-listed licenses.

zstd_ldm.c doesn't have the last statement. Our company's legal team says in this situation we have to select the stricter license which is GPLv2 (which we don't want to use). 

Is the absence of the last statement a negligence or is it intended ?

If it is a negligence, can we modify it and add the statement?

license annoucement in zstd_ldm.c:
```
/*
 * Copyright (c) 2016-present, Yann Collet, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under both the BSD-style license (found in the
 * LICENSE file in the root directory of this source tree) and the GPLv2 (found
 * in the COPYING file in the root directory of this source tree).
 */
```

license announcement in other files:
```
/*
 * Copyright (c) 2016-present, Yann Collet, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under both the BSD-style license (found in the
 * LICENSE file in the root directory of this source tree) and the GPLv2 (found
 * in the COPYING file in the root directory of this source tree).
 * You may select, at your option, one of the above-listed licenses.
 */
```

all files without the last statement:

https://github.com/facebook/zstd/blob/dev/lib/compress/zstd_ldm.c
https://github.com/facebook/zstd/blob/dev/lib/common/threading.h
https://github.com/facebook/zstd/blob/dev/lib/compress/zstd_ldm.h

**Comment by terrelln** [comment]
This is a mistake, all files in lib/ are dual licensed. I will put up a PR to fix it tomorrow.

**Comment by terrelln** [comment]
This should be fixed now, let us know if you have any further concerns.
