### ISSUE TITLE
Is there any way to use zstd in archive on Linux?

### ISSUE THREAD

**Issue by szcnick** [facebook/zstd#2057]
Does Linux have good archive that supports zstd？Just like p7zip.

**Comment by Cyan4973** [comment]
You may want to try [7-zip Zstandard](https://github.com/mcmilk/7-Zip-zstd/)

**Comment by felixhandte** [comment]
Or [`tar`](https://www.gnu.org/software/tar/manual/html_node/gzip.html).

**Comment by Cyan4973** [comment]
Good point !
`tar` support is way more universal in the `linux` and `posix` world.

**Comment by szcnick** [comment]
There are many data sources for  our business processing, like xz zlib lzma ....
So as I know, p7zip Integrated Zstd  maybe the best way. Thanks.

**Comment by bimbashrestha** [comment]
Looks like a few suitable options have been proposed already. I'm going to go ahead and close this issue.
