### ISSUE TITLE
!  Warning : nb of samples too low for proper processing !  showed even when number of files is 1285 :(

### ISSUE THREAD

**Issue by The-Steel-Talon** [facebook/zstd#2058]
**Describe the bug**
I was trying to use the --train feature.
Here is the command and output :
$ zstd --train "/some directory/*" -o abc
!  Warning : nb of samples too low for proper processing ! 
!  Please provide _one file per sample_. 
!  Alternatively, split files into fixed-size blocks representative of samples, with -B# 
Error 14 : nb of samples too low
`

That directory has 1285 items as reported by thunar.

**Expected behavior**
Should work just fine.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 5.4.22-1-lts
 - Compiler: I don't know. Got it from pacman.
 - Flags: I don't know. Got it from pacman.

**Additional context**
Maybe I am not using this feature correctly.
Just tell me how to use it.

**Comment by Cyan4973** [comment]
This command wants to rely on automatic name expansion by the shell.
While the exact details of what works or not depend on shell's specifics, chances are, enclosing the path inside `".."` blocks automatic expansion.

Try instead : 
`zstd --train -r "/some directory" -o abc`

Expansion will be realized inside `zstd` (which is also more efficient).

**Comment by The-Steel-Talon** [comment]
Cyan4973: Works. :)
Thank you.
