### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by dsoprea** [facebook/zstd#2070]
The underlying website is down, so CloudFlare, which is apparently fielding the initial requests, is unable to connect. If using SSL, it complains of not being able to negotiate SSL (for obvious reasons).

![Selection_20200404-131259](https://user-images.githubusercontent.com/715626/78457204-763ab980-7676-11ea-804c-eb5f9c583088.png)

**Comment by Cyan4973** [comment]
The website was never down, it's the `https` redirection that was broken for some unknown reason.
The link seems to be back online, at least from my station (network caches and propagation delays make diagnosis difficult).
Could you confirm on your side ?

**Comment by dsoprea** [comment]
Nope. Note the new status code.

![image](https://user-images.githubusercontent.com/715626/78845683-46254a80-79d7-11ea-9519-ffb39839be1f.png)

**Comment by dsoprea** [comment]
From our perspective, a down website on the backend *could* result in an SSL negotiation error. So, I wasn't presuming anything.

**Comment by Cyan4973** [comment]
This is strange.
Since the website is fine, the problem seems on the URL redirection, basically on Cloudflare side. However, a lot of websites use Cloudflare redirection services, so if there is indeed a pb at Cloudflare, I would expect this issue to be impacting many more websites ...

**Comment by dsoprea** [comment]
Now it looks like it's all of the way down:

![image](https://user-images.githubusercontent.com/715626/78850659-baff8100-79e5-11ea-8d7c-157a6c01d3a8.png)

**Comment by Cyan4973** [comment]
And now handshake fails on my side.
We apparently see different results, as a consequence of living in different areas.
This seems consistent with a topology based on unicast, where the same IP address is effectively routed to different nodes depending on origin, and sometimes complementary distribution rules.

Yet, the "real" website itself works fine : 
https://facebook.github.io/zstd/

**Comment by dsoprea** [comment]
If you're saying that the CDN is actually wrapped around the
facebook.github.io site, then sure.



Dustin

**Comment by mvanleeu** [comment]
Just in case, it is still down :-(

**Comment by Cyan4973** [comment]
Yeah, multiple attempts at fixing this thing, still no positive outcome.
I'm tempted to move out from Cloudflare, though will try a less drastic action first.

**Comment by dsoprea** [comment]
@Cyan4973 If for any other reason than just being distracted at length by such a stupid problem.

**Comment by easyaspi314** [comment]
> Yet, the "real" website itself works fine :
> https://facebook.github.io/zstd/

![Screenshot_20200412-121702](https://user-images.githubusercontent.com/6258309/79073960-94786900-7cb7-11ea-922d-b5d7c1d2bba0.png)
Yup, totally fine.

**Comment by dsoprea** [comment]
That didn't used to happen. It has also been tough getting consistent results due to the CDN behavior. Maybe also because of edge caching. Remember that zstd.net is the frontend URL. If the *backend* URL is now redirecting to the *frontend*, it might be additional failures introduced by others while debugging the problem in the last several days.

**Comment by dsoprea** [comment]
Resolved. Thanks for getting things moving, @Cyan4973.

**Comment by chenrui333** [comment]
Looks like the site is down again.

![image](https://user-images.githubusercontent.com/1580956/85953956-0882ee80-b942-11ea-8bbc-07933d79cb95.png)

**Comment by chenrui333** [comment]
```
$ curl -I https://www.zstd.net/
curl: (7) Failed to connect to www.zstd.net port 443: Connection refused
```

**Comment by Cyan4973** [comment]
The `https://` redirection was no longer working, so I just removed it.
Redirection still works with` http://` though.

**Comment by chenrui333** [comment]
👍

**Comment by pxeger** [comment]
Currently redirects to GitHub pages, but only on plain HTTP (port 80); HTTPS (443) gives a connection error, so the link in the README still doesn't work and should be updated
