### ISSUE TITLE
cross-compilation for Windows fails

### ISSUE THREAD

**Issue by vtorri** [facebook/zstd#2072]
**Describe the bug**

when cross-compiling on Linux for Windows, the Makefile rule which copies programs/zstd.exe fails, because EXT is not set correctly : 

cp: cannot stat 'programs/zstd': No such file or directory

the problem is the way EXT is defined : 

ifneq (,$(filter Windows%,$(OS)))
EXT =.exe
else
EXT =
endif

EXT is defined according to the OS value in the terminal, which is incorrect when cross compiling

**To Reproduce**

on linux, install the mingw-w64 + gcc toolchain 64 bits packages, then

make CC=x86_64-w64-mingw32-gcc WINDRES=x86_64-w64-mingw32-windres AR=x86_64-w64-mingw32-ar

**Expected behavior**

zstd.exe should be copied, not zstd

**Desktop (please complete the following information):**

Linux with Fedora

**Additional context**

cross compilation on Linux for Windows

**Comment by vtorri** [comment]
btw, in lib/Makefile there will be the same problem as OS is also used to detect OS

maybe you should do something like that
SYSTEM ?= $(OS)

and use $(SYSTEM) instead of $(OS)

and if someone whant to cross -compile, it passes the correct SYSTEM value

**Comment by bimbashrestha** [comment]
Thanks for posting the issue.

I was able to reproduce this on my Fedora VM:

```
$ make CC=x86_64-w64-mingw32-gcc WINDRES=x86_64-w64-mingw32-windres AR=x86_64-w64-mingw32-ar
...
cp: cannot stat 'programs/zstd': No such file or directory
```

I could not however reproduce this on my ubuntu vm when cross-compiling using the mingw-w64 + gcc toolchain. There, the .exe extension seems to not get placed in the executable and so the cp succeeds. 

Still, I think your proposed solution is a good one here and I confirm it fixes the build issue on fedora while having no impact on ubuntu. It can't hurt to let the user force windows as the target system in case they need it. And  ?= $(OS) will mean we won't break any existing functionality by default so I'll go ahead and put up a PR
