### ISSUE TITLE
--patch-from with --memory hits unexpected ceiling

### ISSUE THREAD

**Issue by RubenKelevra** [facebook/zstd#2076]
**Describe the bug**
While setting `--memory` to something like 200 on a normal file compression works fine, setting `--memory` to "144M" will return an error:

`zstd: error 11 : Parameter is out of bound`

**To Reproduce**
zstd --ultra -22 --memory="144M" --patch-from=file_a file_b patch

**Desktop (please complete the following information):**
 - OS: ArchLinux (Manjaro)
 - Flags O2 native
 - Other relevant hardware specs i3-2330M
 - Build system [Aur package](https://aur.archlinux.org/packages/zstd-git/)

**Comment by bimbashrestha** [comment]
Hello again @RubenKelevra, if I'm not mistaken, I think the usage of the cli is incorrect in your example. You're missing the -o before patch

Try:
```
zstd --ultra -22 --memory="144M" --patch-from=file_a file_b -o patch
```

**Comment by RubenKelevra** [comment]
Wow, looks I was a bit too excited to test this feature. Thanks for catching this!

Maybe a bit more specific error message would be helpful, for people like me :)
