### ISSUE TITLE
`patch-from` with `--ultra -22` recommends invalid option

### ISSUE THREAD

**Issue by RubenKelevra** [facebook/zstd#2081]
**Describe the bug**
running zstd to generate a patch with `--ultra -22` will output some recommendations, one is:

```
- Set a larger chainLog (eg. --zstd=chainLog=31)
```

While setting this option results in the following error:
```
zstd: error 11 : Parameter is out of bound 
```

**Comment by bimbashrestha** [comment]
Ah thanks @RubenKelevra. The recommendation is wrong and the error is correct. The max chainLog is lower than that. I'll put up a pr shortly
