### ISSUE TITLE
Benchmarks missing fast mode.

### ISSUE THREAD

**Issue by indolering** [facebook/zstd#2098]
The benchmarks in the README.md and docs appear to be missing fast mode.  This is important marketing as it positions ZSTD a competitor to LZO and LZ4.

**Comment by terrelln** [comment]
Thanks for the report @indolering! We're making a release soon. I will update the benchmarks with the new version, and add fast mode, once we're ready to cut the release.

**Comment by terrelln** [comment]
See the updated benchmarks in https://github.com/terrelln/zstd/blob/benches/README.md

**Comment by indolering** [comment]
> See the updated benchmarks in https://github.com/terrelln/zstd/blob/benches/README.md

I'm still only counting 20 points on that diagram, not 27....

**Comment by terrelln** [comment]
So far I’ve only updated the table. The graphs have not yet been updated
