### ISSUE TITLE
Makefiles have many unlabeled PHONY targets

### ISSUE THREAD

**Issue by Artoria2e5** [facebook/zstd#2126]
### Describe the bug
A lot of the targets in `programs/Makefile` are actually "phony" in that they don't emit a file of their name. These files are mostly variants of the main `zstd` build, but as a matter of correctness this is wrong.

The `lib/Makefile` has a similar problem where the `install-*` targets are not labeled as PHONY.

I don't have time to check the other makefiles, but chances are `zstd` doesn't have them all correct either.

### To Reproduce
1. `cd programs; make zstd-pro; test -e zstd-pgo && echo it exists || echo what`

### Expected behavior
Well, the target file should exist.

* * *

### How should we fix it?
The solution is obvious for `install` and friends. Just add them to the `.PHONY` list.

The solution is less obvious for the zstd variations, since they *do* make an output file. My suggestion is to do like `zstdmt` does and perform a `ln -sf zstd$(EXT) $@$(EXT)`, but making them actually PHONY is probably okay too. (A hard link *could* be better, since that allows for building variants alongside each other - kind of.)

**Comment by Cyan4973** [comment]
PR welcome

**Comment by McZenith** [comment]
Is this issue still available? I'm interested...

**Comment by Cyan4973** [comment]
Sure @McZenith !

**Comment by McZenith** [comment]
Thanks... Updates soon...

**Comment by McZenith** [comment]
Hi! It is not as easy could you please provide me with more explanation?

**Comment by senhuang42** [comment]
Addressed in #2629, thanks for the report!
