### ISSUE TITLE
Update benchmarks on zstd.net website

### ISSUE THREAD

**Issue by k00bler** [facebook/zstd#2145]
**Is your feature request related to a problem? Please describe.**

On the [website zstd.net](https://facebook.github.io/zstd/), one expects to see benchmarks of the latest version of zstd (or at least of one of the past year), but the latest benchmarked version is 1.3.4. lxbench has also been updated to 1.4.4 and i am wondering why there is no newer benchmark on the website.

**Describe the solution you'd like**
I want a newer benchmark (like 1.4.4, or 1.4.5 when it finally arrives) visible on the project website.

**Comment by Cyan4973** [comment]
Benchmark table updated with results from `v1.4.5`.
