### ISSUE TITLE
cmake: wrongly installs various internal headers

### ISSUE THREAD

**Issue by lazka** [facebook/zstd#2161]
1.4.5 has relative includes pointing to non-existing files in installed header files (with cmake).

e.g.

include/cover.h:

```
#include "../common/mem.h" /* read */
#include "../common/pool.h"
#include "../common/threading.h"
#include "../common/zstd_internal.h" /* includes zstd.h */
```
and

include/zbuf.h:

```
#include "../zstd.h"
```

Could it be that these files shouldn't be installed? Can I drop them downstream?

**Comment by Cyan4973** [comment]
These files are not "necessary",
`zbuff.h` is an old deprecated streaming API, `cover.h` is an internal API of `zdict`,

but if, for some reason, you need any of them,
they should be installed at the same _relative_ position from `zstd.h`.

**Comment by lazka** [comment]
ok, thanks, I will delete them during packaging then. I don't know if this issue should stay open or not, so feel free to close.

For some extra context, here is the list of files cmake installs into \<prefix\>/include -> https://github.com/facebook/zstd/blob/299229316a87c83a46d6c97aa59867c7c7746663/build/cmake/lib/CMakeLists.txt#L153

**Comment by Cyan4973** [comment]
Since these incorrectly placed files are installed by the `cmake` script from this repository,
I believe we should keep this issue opened,
it will be useful to track the `cmake` fix.

**Comment by Cyan4973** [comment]
Looking at the `cmake` script, I'm surprised because it _seems_ that it installs additional headers in their _correct_ directories, for example : `"${LIBRARY_DIR}/deprecated/zbuff.h"` . How come you seem to report its presence in `include/zbuf.h` instead ?

**Comment by lazka** [comment]
This is what I get on Debian for a `make install DESTDIR=foo`

```
Install the project...
-- Install configuration: "Release"
-- Installing: foo/usr/local/lib/cmake/zstd/zstdTargets.cmake
-- Installing: foo/usr/local/lib/cmake/zstd/zstdTargets-release.cmake
-- Installing: foo/usr/local/lib/cmake/zstd/zstdConfig.cmake
-- Installing: foo/usr/local/lib/cmake/zstd/zstdConfigVersion.cmake
-- Installing: foo/usr/local/lib/pkgconfig/libzstd.pc
-- Installing: foo/usr/local/include/zstd.h
-- Installing: foo/usr/local/include/zbuff.h
-- Installing: foo/usr/local/include/zdict.h
-- Installing: foo/usr/local/include/cover.h
-- Installing: foo/usr/local/include/zstd_errors.h
-- Installing: foo/usr/local/lib/libzstd.so.1.4.5
-- Installing: foo/usr/local/lib/libzstd.so.1
-- Installing: foo/usr/local/lib/libzstd.so
-- Installing: foo/usr/local/lib/libzstd.a
-- Installing: foo/usr/local/bin/zstd
-- Installing: foo/usr/local/bin/zstdcat
-- Installing: foo/usr/local/bin/unzstd
-- Installing: foo/usr/local/bin/zstdgrep
-- Installing: foo/usr/local/bin/zstdless
-- Installing: foo/usr/local/share/man/man1/zstd.1
-- Installing: foo/usr/local/share/man/man1/zstdcat.1
-- Installing: foo/usr/local/share/man/man1/unzstd.1
-- Installing: foo/usr/local/share/man/man1/zstdgrep.1
-- Installing: foo/usr/local/share/man/man1/zstdless.1
-- Installing: foo/usr/local/bin/zstdmt
```

**Comment by Cyan4973** [comment]
We will have to revisit this topic.

`cover.h` should not be installed, it is internal, and tries to include internal stuff, not accessible on the public side.
The other ones _may_ fulfill a role (they are advanced optional headers), but the way they are currently installed is not desirable.

Suggestion: we could create an `include/zstd` directory, and put the optional headers there. This way, the `../` relationship with `zstd.h` is preserved, while the directory name becomes more acceptable than `include/common` and `include/deprecated`.

**Comment by Cyan4973** [comment]
Looking a bit more in details : 
- `zstd_errors.h` : this header doesn't include `zstd.h`, so it could be stored directly into `\include`
- `zdict.h` : doesn't include `zstd.h`, could be stored directly into `\include`
- `zbuff.h` : requires `zstd.h`, to access declarations of `ZSTD_CCtx`, `ZSTD_DCtx` and `ZSTD_customMem`. Without modifications, required to be present in a subdirectory below `zstd.h`.

Other associated topic : we may have to consider `#include` consistency when using the library, and when integrating directly with the `zstd` source code. Ideally, the `#include` statement should remain the same in both cases, maybe at the cost of setting a different `/include` path.

**Comment by Cyan4973** [comment]
All install scripts have been updated, and do not longer install `zbuff.h` nor `cover.h`.

`zstd_errors.h` and `zdict.h` are still installed alongside `zstd.h` into `include/`.

**Comment by lazka** [comment]
Thanks!
