### ISSUE TITLE
pzstd breaks on Windows build because ERROR is already defined on Windows

### ISSUE THREAD

**Issue by brechtsanders** [facebook/zstd#2165]
When building v1.4.5 for Windows with MinGW-w64 (from http://winlibs.com in my case) compilation fails because `ERROR` is already defined in Windows when it is redefined in `contrib/pzstd/Logging.h`.
I was able to build by adding `#define ERROR ZSTD_ERROR` at the top of `contrib/pzstd/Logging.h` for now, but the clean solution would be to replace `ERROR` with something else.

**Comment by brechtsanders** [comment]
Come to think of it, maybe `ERROR` is not the only one. I can imagine `DEBUG` may also conflict on some platforms. Maybe all of these should be changed, for example by adding a `LOG_` prefix:
```
constexpr int ERROR = 1;
constexpr int INFO = 2;
constexpr int DEBUG = 3;
constexpr int VERBOSE = 4;
```

**Comment by terrelln** [comment]
That’s a reasonable solution. I will accept a PR that does that, or will put up a PR myself in a bit.
