### ISSUE TITLE
Bugs found by static tests

### ISSUE THREAD

**Issue by tester7632** [facebook/zstd#2170]
Sonarqube revealed some potential bugs that shloud get a closer look.

Most of the results are false positives or "not best practice" but there are usually some valid issues in the "blocker" category: https://sonarcloud.io/project/issues?id=tester7632_zstd&resolved=false&severities=BLOCKER&types=BUG

The full report can be found here:
https://sonarcloud.io/dashboard?id=tester7632_zstd

**Comment by terrelln** [comment]
Hi @tester7632,

I have taken a look at the first few warnings, and they are all false positives. We use clang's scan-build as our static analysis, and find the incremental gain of using more than one static analysis method is outweighed by the costs. See https://github.com/facebook/zstd/blob/dev/CONTRIBUTING.md#pitfalls-of-static-analysis for context.

If you look through that list and feel that one or more of them are very likely to be real issues, please link them here and I will take a further look.
