### ISSUE TITLE
Dictionary ID 0 not described in spec

### ISSUE THREAD

**Issue by klauspost** [facebook/zstd#2172]
**Describe the bug**

The [spec](https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md#dictionary_id) doesn't mention ID 0 as having special meaning, so from the description I would expect I should treat it as any other ID.

Edit: ok, it is mentioned in the [Dictionary format](https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md#dictionary-format) as a special value. It should probably also be mentioned as such in the frame header part.

**Desktop:**

 - OS: Windows 10, 64 bit
 - Version `zstd command line interface 64-bits v1.4.5, by Yann Collet`
 - Compiler: Executable downloaded.

**Comment by Cyan4973** [comment]
That's a good point.
In the reference decoder, a `dictID` value of `0` means the same a no `dictID` at all,
which itself  means "this frame _might_ be dictionary compressed, but I won't tell you if it is, nor the relevant `dictID`, receiver must know such information by themselves".

**Comment by Cyan4973** [comment]
Spec updated
