### ISSUE TITLE
avoid absolute prefix path in .pc file

### ISSUE THREAD

**Issue by dirk-thomas** [facebook/zstd#2182]
The generated `.pc` file contains the absolute path of the install prefix in the `prefix` fields which makes that artifact not relocatable.

Instead of embedding the absolute install prefix the `.pc` can use the variable `${pcfiledir}` which points to the path of the `.pc` file at runtime. Depending on how many subdirectories the `.pc` is being installed under the install prefix the hard coded install prefix can be emulated by e.g. `${pcfiledir}/../..` (the number of `..` depends on the used `libdir`.

**Comment by dirk-thomas** [comment]
An example how the absolute path can be avoided: ros2/urdfdom#20.

**Comment by felixhandte** [comment]
Man, the pkg-config file has been a continuing source of contention. Pretty much any change we make to it seems to break someone's use case.

I'm not sure that this is an expected property of pkg-config files. Can you point me to some documentation for what situation requires this functionality?

**Comment by terrelln** [comment]
> The generated .pc file contains the absolute path of the install prefix in the prefix fields which makes that artifact not relocatable.

My (limited) understanding is that install artifacts aren't meant to be portable with regards to `$PREFIX`. Instead you should run `make install` again with the new `$PREFIX`.

**Comment by dirk-thomas** [comment]
> I'm not sure that this is an expected property of pkg-config files.

https://manpages.debian.org/stretch/pkg-config/pkg-config.1.en.html#PKG-CONFIG_DERIVED_VARIABLES

> I'm not sure that this is an expected property of pkg-config files. Can you point me to some documentation for what situation requires this functionality?

After building the package and installing it to `/foo` you *relocate* the artifacts (e.g. to `/bar` because the artifacts are copied to a different machine and placed in a different location). If the artifacts contains the original prefix path (`/foo`) hardcoded in them they won't work in the different location. When using `pcfiledir` they will continue to work.

**Comment by dirk-thomas** [comment]
> My (limited) understanding is that install artifacts aren't meant to be portable with regards to `$PREFIX`.

Can you clarify why you think that is the case? (Beside the obvious case of the `.pc` file described in this ticket.)

**Comment by felixhandte** [comment]
None of the 185 pkg-config files installed on my system appear to be relocatable in this way.

**Comment by felixhandte** [comment]
@dirk-thomas, I'm going to close this issue, unless you have any objections.
