### ISSUE TITLE
Support for splitting the compressed output file into many files of an given size

### ISSUE THREAD

**Issue by mniehren** [facebook/zstd#2184]
Hi together,

my usecase is the following: Backup of qcow2 Files
- i compress qemu2 Images with zstd together with the --rsyncable option
- then i transfer the files to an external rsync-server, all right run's like a charm
- on the external rsync-Server i wan't to have backup's from the last 5 days, so
  to save space i "copy" the backup-files over hardlinks, so that new space is only
  allocated for new data
- that makes no sense with 1 big zstd compressed qcow2 Image file, so i split
  the zstd compressed image file in many files of size 100M. For that case i
  use the split command together with zstd -c (split -a 4 -d -b 100M )

But the zstd -c ... | split ... command need's double of the time as the zstd -O command
without splitting the file. So it would be very nice to have an zstd option for splitting the
output files directly to an given size.

For example, the output filename, which is set by -O, should be splitted into files like
  <filename>.0001
  <filename>.0002
  ...

The analog would be useful for decrompressing too ...

**Comment by Cyan4973** [comment]
If I do understand correctly, 
you would like `zstd` to support an additional command to split output file automatically, defining a name scheme in the process, essentially duplicating `split`, because the `split` command is not fast enough ?

**Comment by felixhandte** [comment]
I don't think we're going to implement this. The Unix Philosophy says: "do one thing well". `zstd` compresses data. `split` splits data. So I'm going to close this issue.

I am surprised though that you see such a performance difference though in introducing what should be a very lightweight indirection. Are you running this on a single-core system or something?

**Comment by chadbrewbaker** [comment]
Bump. I have the same use case. Whole system memory dump I need to compress then transfer over the network.

Where zstd might need a feature is strong hashcodes of common memory ranges so they can be zero copy. I don't think the current dictionary format allows for this? Perhaps crate a hdict - a hashed byterange dictionary? Those regions are greedily documented then zeroed out/squashed before compression.

@marcbrooker I know you run into this at scale with container images. Probably the most knowledgable. 

---Notes for myself --
Faster Algorithms for Longest Common Substring - https://arxiv.org/abs/2105.03106 - suffix array to greedily pick out common strings to reduce to hashed byteranges.   8192 bytes is a good block size? Likely data set dependent.
