### ISSUE TITLE
--patch-from fails to work on pipes

### ISSUE THREAD

**Issue by cpba** [facebook/zstd#2195]
**Describe the bug**

Trying to compress from a pipe using `--patch-from` fails.

**To Reproduce**

```cat foo | zstd --patch-from=bar  -o patch.zstd```

Outputs:

```zstd: fileio.c:774: FIO_adjustMemLimitForPatchFromMode: Assertion `maxSize != UTIL_FILESIZE_UNKNOWN' failed.```

Similarly adding `--long` and or `--memory` produces the same result:

```cat foo | zstd --long --patch-from=bar  -o patch.zstd```

```zstd: fileio.c:774: FIO_adjustMemLimitForPatchFromMode: Assertion `maxSize != UTIL_FILESIZE_UNKNOWN' failed.```

**Expected behavior**

Using `--patch-from` in this manner should produce a working patch.

If patching from stdin is not possible, it'd be preferable to print an error message explaining the situation.

**Desktop (please complete the following information):**
 - OS: fedora
 - Version: 32
 - Compiler: gcc
 - Build system: meson

**Comment by Cyan4973** [comment]
cc @bimbashrestha 
A better error message is indeed preferable.

Would there be a way to make `stdin` work in combination with `--stream-size=#` ? (note: it doesn't right now)
