### ISSUE TITLE
patch-from seems to have problems with windows

### ISSUE THREAD

**Issue by tru** [facebook/zstd#2198]
Hello,

I have worked with `zstd --patch-from` for a bit now and it seems like it creates binaries that are a bit wrong when patching files on windows while it works without problems on Linux.

My zstd is 1.4.5 built with mingw for windows.

Here is how it looks like on linux:

```
ff72435e9dacc441a19042165117113de22e30737d6eb68466a31ae256980da0  x86_64-windows.tar
cb45fad05cfe8b23627384e6af16eace8d508f1a2a0c181fea842457634f57b0  x86_64-windows-patch-from-80.zst

zstd -d --long=30 --patch-from=../80/x86_64-windows.tar x86_64-windows-patch-from-80.zst -o hello.tar
330b67ec154ad611f7c1183341a591a61719902f0f32fa5e8a6a9c2e1451d1eb  hello.tar
```

Same files on windows:

```
SHA256 hash of x86_64-windows.tar:
ff72435e9dacc441a19042165117113de22e30737d6eb68466a31ae256980da0

SHA256 hash of x86_64-windows-patch-from-80.zst:
cb45fad05cfe8b23627384e6af16eace8d508f1a2a0c181fea842457634f57b0

zstd -d --long=30 --patch-from=x86_64-windows.tar ..\82\x86_64-windows-patch-from-80.zst -o hello.tar

SHA256 hash of hello.tar:
480868cade3a8f4cb3ae02c7188efe667258288d671409d06eedba3121050272
```

Is this something known? Doesn't patch-file work correctly on windows or is it a problem with my mingw build?

**Comment by tru** [comment]
Actually it seems like any decompression has this problem:

Windows
```
SHA256 hash of x86_64-windows.tar.zst:
8925b1d31831897b17f548bc111bd868b056d6b988595c4d1b743a9ae4a7fd35
zstd -d --long=30 x86_64-windows.tar.zst
SHA256 hash of x86_64-windows.tar:
480868cade3a8f4cb3ae02c7188efe667258288d671409d06eedba3121050272
```


Linux:
```
8925b1d31831897b17f548bc111bd868b056d6b988595c4d1b743a9ae4a7fd35  x86_64-windows.tar.zst
zstd -d --long=30 x86_64-windows.tar.zst
330b67ec154ad611f7c1183341a591a61719902f0f32fa5e8a6a9c2e1451d1eb  x86_64-windows.tar
```

Seems like it has to be a problem with my build or maybe that I compress files on linux and they end up not being compatible with windows?

**Comment by sergeevabc** [comment]
@tru, any news?

**Comment by terrelln** [comment]
We will sanity check --patch-from mode on windows before our release. @tru @sergeevabc are you still experiencing this issue on `dev`?

**Comment by sergeevabc** [comment]
@terrelln, I find it difficult to remember what exactly bothered me about this issue more than a year ago. Alas, the machine with the script and test files of that time are far away now. However, a quick test of ZSTD 1.5.2 has revealed no errors so far.

```console
$ xxhsum app_v1.exe app_v2.exe
dfc5167ffce422d5  app_v1.exe
645c289c5b32de15  app_v2.exe 

$ zstd -19 --zstd=chainLog=30 --patch-from=app_v1.exe app_v2.exe -o magic.bin

$ zstd -d --patch-from=app_v1.exe magic.bin -o app_v1_patched.exe

$ xxhsum app_v2.exe app_v1_patched.exe
645c289c5b32de15  app_v2.exe
645c289c5b32de15  app_v1_patched.exe
```

**Comment by tru** [comment]
I think this can be closed (sorry it just popped up on my notifications now for the first time in a long time). We where building ZSTD with a MinGW toolchain and something in that process made zstd decompress faulty, we switched to using upstream binaries for Windows instead and have been using them ever since without any problems.
