### ISSUE TITLE
Make no longer builds on SLES11 OS

### ISSUE THREAD

**Issue by dkcasset** [facebook/zstd#2215]
I believe I was able to build zstd 1.3.4 on SLES11 but 1.4.5 now fails for 2 reasons:

Issue 1: Use of undocumented -E option in sed (alias for -r)
Issue 2: Missing utime.h in programs/util.c

To reproduce:

1. make
sed: invalid option -- 'E'

2a. In lib/Makefile, replace all occurrences of -E option with -r
2b. make
util.c: In function 'UTIL_setFileStat':
util.c:161: error: storage size of 'timebuf' isn't known

3a. Add to programs/util.c
#include <utime.h>
3b. make
(Build successful)

Desktop
 - OS: SLES11 (x86-64_linux_3.0.101_ImageSLES11SP4-4)
 - Version: 1.4.5
 - Compiler: cc
 - Flags: Whatever is supplied in the Makefiles
 - Hardware specs: Intel(R) Xeon(R) CPU E5-2667
 - Build system: make

**Comment by terrelln** [comment]
Thanks for the report @dkcasset!

If you would like to put up a PR for these changes we'd happily accept it. Otherwise, we'll be sure to make these fixes before our next release.

**Comment by dkcasset** [comment]
I have since realized that the utime.h issue can be solved on the command line:
make CC='cc -DPLATFORM_POSIX_VERSION=1'
This is a reasonable workaround

**Comment by felixhandte** [comment]
I believe this is fixed, so I'm going to close this.
