### ISSUE TITLE
Train data compression ratio

### ISSUE THREAD

**Issue by vladviolenty** [facebook/zstd#2223]
My Train Data:
[train.tar.gz](https://github.com/facebook/zstd/files/4850166/train.tar.gz)
i try compress file
[2020-06-30 06:00:02.txt](https://github.com/facebook/zstd/files/4850173/2020-06-30.06.00.02.txt)
without dictionary:

> zstd -b 2020-06-30\ 06:00:02.txt
 3#6-30 06:00:02.txt :     40712 ->      3920 (10.39), 591.9 MB/s ,1373.4 MB/s

with dictionary

> zstd -b -D dictionary 2020-06-30\ 06:00:02.txt 
 3#6-30 06:00:02.txt :     40712 ->      3560 (11.44), 398.3 MB/s ,1368.1 MB/s

if i try compress all my train data i get compression ratio over 30

> zstd -b train.tar
 3#train.tar         :   3829760 ->    128064 (29.91),1281.7 MB/s ,2768.2 MB/s`

`zstd v1.4.5`
`linux 4.19`

**Comment by Cyan4973** [comment]
Compressing a `tar` archive is a best case scenario.
I don't think it's reasonable to expect dictionaries to reach an equivalent level of efficiency.

Now, I presume you were expecting dictionary to do "better".
I note a few things which are uncommon in this sample set : 
- each record can be compressed to a large compression ratio (> 10)
- each individual record is "large" (~40KB)

Both these properties are unusual in a dictionary compression scenario.
Dictionary is best used for "small" data (< 1 KB), which do not compress well when compressed individually (ratio < 2).
The "large" size of individual record dilutes dictionary's efficiency, and the effect is even more pronounced when a high level of internal correlation is also present, as they tend to take precedence over the dictionary.

Going farther than that requires a deeper analysis of source data.
The way I see it, there are a lot of metadata in common across files, including the sequence and order, to the point that only a few fields get updated.
This case seems perfect for the "repeat mode" which will be automatically triggered when compressing these files as a batch, resulting in high compression ratio.
Unfortunately, it's less efficient for a the dictionary, which will tend to break very long series of metadata into smaller batches.
At least, that's the case what will happen with current dictionary builder.
Improving that is probably possible, but it's less easy to both improve this case, and remain "universal", i.e. preserving efficiency for other kind of data to compress.
