### ISSUE TITLE
Link to BLOSC in Website to be updated

### ISSUE THREAD

**Issue by mvanleeu** [facebook/zstd#2225]
On the [zstd website](http://facebook.github.io/zstd/), in teh section "Zstd is used by...", the link to the Blosc blog post indicting it is using zstd is outdated. 
Instead of 
http://www.blosc.org/blog/zstd-has-just-landed-in-blosc.html 
it should be 
https://www.blosc.org/posts/zstd-has-just-landed-in-blosc/

**Comment by Cyan4973** [comment]
Link fixed. Thanks for notification @mvanleeu !
