### ISSUE TITLE
What do the "max" values refer to in the dictionary compression section?

### ISSUE THREAD

**Issue by JoeArizona** [facebook/zstd#223]
Hi Yann – In your graph for the dictionary compression, what do the parenthetical "max" values refer to?

Also, what do the tilde figures refer to? (e.g. `~ 1.5 KB` for Mercurial events) Is this the size reduction, or the new file size perhaps?

Thanks.

**Comment by Cyan4973** [comment]
`max` is the maximum size of any sample,
while `~` is the average sample size (uncompressed).

**Comment by JoeArizona** [comment]
Thanks. I haven't seen great results without generating a dictionary. Brotli is compressing jQuery quite a bit more than Zstd so far. It gets close if I use the jQuery file as the training data for Zstd to generate a dictionary to compress that very same file.

With such a dictionary, I can get jquery-2.2.4.min.js down to 27,674 bytes at level 22. Brotli at max gets it down to 26,961. libdeflate yields 28,818 bytes, just barely edging past zopfli in this case. (The original is 85,578 bytes. This is the official jquery-supplied minified file.)

Do you foresee any benefit in enriching the training data (perhaps counter-intuitively) with files _other than_ the targeted file? I wonder if a few different jQuery releases would yield a more effective dictionary for any given release. Would having multiple copies of the same file have an impact? (I'm thinking of the possibility that it would lead to different weights or something, but I have no idea how the dictionary, or really the scheme itself, works.)

**Comment by Cyan4973** [comment]
Dictionary compression is primarily introduced to compress live small packets and messages (Kilobyte range). With larger sources, the _relative_ effectiveness of dictionary decreases.
For a source size ~80K, you are likely to get a ~5% benefit. Still measurable and good, but no longer transformative.

This is obviously a rule of thumb, specific conditions can trigger different results either way.

The general idea is : dictionary will be used to compress many packets, and these packets share a generic "structure" (without being identical to each other).
The dictionary builder will try to "catch" this structure, and create a dictionary out of it.
The way it does it is by analyzing similarities between packets. The parts that are most repeated will be prioritized.

The "sample set" needs to be large enough to reliably catch and sort the better similarities.
The recommended sample size is about ~10K records.
Obviously, it will work too if you provide ~1K records.
But if the number of records is really small, it will have difficulties determining the better sequences and their order.

> Do you foresee any benefit in enriching the training data (perhaps counter-intuitively) with files other than the targeted file?

Using one dictionary to compress one file is not the best use case.
In general, you will want a dictionary to compress multiple files of same type.
For a single target file, it would be enough to provide the file itself as a dictionary, but that would be a bit cheating.


> Would having multiple copies of the same file have an impact? (I'm thinking of the possibility that it would lead to different weights or something, but I have no idea how the dictionary, or really the scheme itself, works.)

Yes, it would work.
If you repeat the same file 5 times in the sample batch, it will get a much higher priority.

Keep in mind that dictionary compression is a pretty new topic, and there is still a lot left to discover.
You may very well find your own answers by experimenting.

**Comment by Cyan4973** [comment]
The [dictionary compression section on main page](https://github.com/facebook/zstd#the-case-for-small-data-compression) has been updated and does no longer feature a "max" value.
I expect the new version to be easier to understand.
