### ISSUE TITLE
make -C lib does not work for a release

### ISSUE THREAD

**Issue by marxin** [facebook/zstd#2234]
When using a tarball I see:

```shell
$ make -C lib lib-mt
make: Entering directory '/tmp/zstd-1.4.5/lib'
make: Nothing to be done for 'lib-mt'.
make: Leaving directory '/tmp/zstd-1.4.5/lib'
```

while the current git master does:

```shell
make -C lib lib-mt
make: Entering directory '/home/marxin/Programming/zstd/lib'
cc -Wall -Wextra -Wcast-qual -Wcast-align -Wshadow -Wstrict-aliasing=1 -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wundef -Wpointer-arith -Wvla -Wformat=2 -Winit-self -Wfloat-equal -Wwrite-strings -Wredundant-decls -Wmissing-prototypes -Wc++-compat  -O3 -DXXH_NAMESPACE=ZSTD_ -DZSTD_LEGACY_SUPPORT=5 -DZSTD_MULTITHREAD  -c -o common/debug.o common/debug.c
cc -Wall -Wextra -Wcast-qual -Wcast-align -Wshadow -Wstrict-aliasing=1 -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wundef -Wpointer-arith -Wvla -Wformat=2 -Winit-self -Wfloat-equal -Wwrite-strings -Wredundant-decls -Wmissing-prototypes -Wc++-compat  -O3 -DXXH_NAMESPACE=ZSTD_ -DZSTD_LEGACY_SUPPORT=5 -DZSTD_MULTITHREAD  -c -o common/entropy_common.o common/entropy_common.c
cc -Wall -Wextra -Wcast-qual -Wcast-align -Wshadow -Wstrict-aliasing=1 -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wundef -Wpointer-arith -Wvla -Wformat=2 -Winit-self -Wfloat-equal -Wwrite-strings -Wredundant-decls -Wmissing-prototypes -Wc++-compat  -O3 -DXXH_NAMESPACE=ZSTD_ -DZSTD_LEGACY_SUPPORT=5 -DZSTD_MULTITHREAD  -c -o common/error_private.o common/error_private.c
...
```

**Comment by Cyan4973** [comment]
Let's be a little bit more accurate.
When you say "the current git master", you actually mean the main branch, which is named `dev`.
And when you say "a tarball", you most likely mean the tarball of last release, which is actually sync'ed with branch `master`.

Anyway, `make -C lib lib-mt` was simply [fixed after the release](https://github.com/facebook/zstd/pull/2176).
That's however the only solution we can currently offer.
Due to the nature of an official release, which is now checksumed with a `sha256` signature, we can't change any bit after publication.

**Comment by marxin** [comment]
> Let's be a little bit more accurate.
> When you say "the current git master", you actually mean the main branch, which is named `dev`.
> And when you say "a tarball", you most likely mean the tarball of last release, which is actually sync'ed with branch `master`.

Yes, both matches!

> 
> Anyway, `make -C lib lib-mt` was simply [fixed after the release](https://github.com/facebook/zstd/pull/2176).

Great.

> That's however the only solution we can currently offer.
> Due to the nature of an official release, which is checksummed with a `sha256` signature, we can't change any bit after publication.

That's for sure, I can easily cherry pick the patch and add it to `openSUSE` package.
Thank you.
