### ISSUE TITLE
Make number of threads configurable via Environment Variable

### ISSUE THREAD

**Issue by gebi** [facebook/zstd#2241]
**Is your feature request related to a problem? Please describe.**
It would be nice as a user to enable multithreading per default eg. via a environment variable (eg. ZST_THREADS=0) for all everyday tasks.
Just like one can set the default compression level via ZST_CLEVEL.
The problem this solves is that eg. all invocation of tar on the cmdline (eg. via `tar caf foo.tar.zst <DIR>` auto deduction of compressor from file ending) would not only choose the compression level per default but would also not be really slow when sitting in front of a laptop with 8 cores or a workstation with 32, because only one thread is used.

**Describe the solution you'd like**
Please support ZST_THREADS to set threads per environemnt variable.

**Describe alternatives you've considered**
As we don't have great internet here it's cumbersome to always specify to use multithreading (because most people here set the compression level quite high), cpu is cheap, bandwidth not.

**Comment by senhuang42** [comment]
Resolved in #2299 - you can use `ZSTD_NUMTHREADS=#` as your environment variable for specifying number of threads.

**Comment by oshanz** [comment]
@senhuang42 according to the PR #2299 it looks like variable is `ZSTD_NBTHREADS`
