### ISSUE TITLE
The Makefiles should test the presence of a directory

### ISSUE THREAD

**Issue by JohnBurrell** [facebook/zstd#2254]
Your Makefiles try and change the permissions on my directories. These are /usr/bin, /usr/include, /usr/share/man/man1. You have no right to trample all over my directories. If I want it 777 that's my lookout, or 700 might be more to my taste.

Please test the presence of a directory before you try and create it. If it doesn't exist then fair enough. But if it does exist then leave it alone and install what you have to. If the permissions don't allow it, then that's the owners tough luck. Give a warning and leave it at that. You shouldn't assume that your package is being installed by root.

**Comment by Cyan4973** [comment]
fixed in `dev` branch
