### ISSUE TITLE
Directory tree

### ISSUE THREAD

**Issue by giovariot** [facebook/zstd#2260]
**Is your feature request related to a problem? Please describe.**
I totally love using zstd to archive old disks backups. However when I'm looking for a specific disk image I always wonder which compressed file exactly contains which image.

**Describe the solution you'd like**
I am aware zstd is a compressor, not an archiver and that in order to compress a folder you first have to create a tar archive and then compress that with zstd (or with a combined command), but it would be awesome to have the ability to insert into the archive header some sort of folder content tree.

**Describe alternatives you've considered**
I know I could ask this to tar developers but as long as the zstd file format doesn't support anything like this I don't think anyone could add that function to the file headers.

**Additional context**
I hope my idea is feasible, I'm not really a programmer so...

Thanks in advance for the great program, anyways.

**Comment by terrelln** [comment]
If you're on Linux check out SquashFS. It is a compressed read only filesystem. You can create it like a tar, and then mount it like a filesystem.

```
# E.g. compress using zstd with a 4MB block size at level 19
mksquashfs data/ bkup.sqfs -b 4M -comp zstd -Xcompression-level 19
mkdir bkup
sudo mount bkup.sqfs bkup
```
