### ISSUE TITLE
Disallow --rm with multiple inputs and a single output unless --force is present

### ISSUE THREAD

**Issue by terrelln** [facebook/zstd#2269]
This stops the zstd cli from destroying information unless `-f` is present. A helpful error message should be printed.

**Comment by SkyC0der** [comment]
I'd like to take this up. Could you explain on how to go about it?

**Comment by HarshilShrivastava** [comment]
I'd like to try this up. Could you explain on how to go about it?

**Comment by Cyan4973** [comment]
Thanks for your interest !

Note that this topic is already receiving a patch by @senhuang42  at #2279

**Comment by senhuang42** [comment]
#2279 was merged, addressing this issue
