### ISSUE TITLE
zlibWrapper README instructions missing a couple of bits

### ISSUE THREAD

**Issue by twotwotwo** [facebook/zstd#2273]
**Describe the bug**

I tried to follow instructions from zlibWrapper/README.md, and ran into two problems:

1) Instructions say your project just needs to statically or dynamically link against `-lzstd`. However, just using `-lzstd` gives me an error about undefined references to ZSTD_malloc and ZSTD_free; zstd_zlibwrapper wants them but they don't seem to be exported from libzstd.so.1.4.5, either the copy I built or the one in the EPEL packages for CentOS. As a workaround, I was able to link against the libzstd.a created during my local build of zstd. 

2) Instructions suggest compiling `zstd_zlibwrapper.c` as part of your project, so they could mention that requires adding `<zstd installation root>/lib/common/` to your include path for it to find its includes.

It's possibly I made some silly mistake here; messing with builds of projects in C isn't something I do a lot. But if the suggested workarounds seem potentially useful to include in the README I'm happy to submit them in a PR.

**Comment by Cyan4973** [comment]
These are fair points.

The fact that `zlibWrapper` uses `ZSTD_malloc()` and `ZSTD_free()` makes it incompatible with the dynamic library.
These are internal symbols, which are not supposed to be exposed, so they require the static library to be found.

We will have to consider if we either remove compatibility with the dynamic library, or change the way `zlibWrapper` works to be compatible with `-lzstd`.

Regarding the include path issue, it's also a fair point. We will have to look at it in details, and update the documentation to reflect how the wrapper can be integrated into a project and which exact dependencies are required.

**Comment by terrelln** [comment]
This has been fixed in the dev branch, zlibWrapper only uses public symbols. This fix will be present in the next zstd release.
