### ISSUE TITLE
zstd.net: Merge/swap bindings and ports

### ISSUE THREAD

**Issue by klauspost** [facebook/zstd#2296]
**Is your feature request related to a problem? Please describe.**

I've gotten a few people that were surprised that a native port of zstandard exists to Go.

At least a few had not seen this since "Bindings for other languages" and "Ports into other languages" are separate on the  [homepage](http://facebook.github.io/zstd/#other-languages) and had only seen the bindings.

At least in Go a native approach is to be preferred since it excludes the need for a C compiler installed.

**Describe the solution you'd like**

Merge  "Bindings for other languages" and "Ports into other languages" and have the ports marked (bold, another bg colour, etc).

Alternatively swapping the tables will also make it more visible since the list of ports is fairly small having it first would make it easy to see and it would be clear there are bindings below.

**Describe alternatives you've considered**

Obviously biased person here, so feel free to take action as you see appropriate.

**Comment by Cyan4973** [comment]
zstd.net has been updated,
the "other languages" tables have been merged into a single one,
with _Ports_ being explicitly labelled.

**Comment by mvanleeu** [comment]
I'm not sure this presentation is very readable, as different dimensions are indicated in the same manner (binding vs port; buffers-only or also streaming support; dict support or not, plus other tags/comments like "decoder" "signed", "emscripten" etc) after the name. 
Wouldn't it make more sense to make it more explicit by adding more columns, and have something like the following structure?

Language | _flavour_ | _features_ | Author | URL

With _flavour_ being "binding" or  "port" (i.e. explicitly), _features_ a list of tags like "streaming", "dict", "decoder-only" etc... 
Assumption for the features is that the ports/binding making the list of the homepage implement a decoder for buffers at least. Some of them do not have an encoder (and are explicitly marked as decoder only), some of them do more like dict support, streaming etc.
