### ISSUE TITLE
compressionLevel is not respected in this case

### ISSUE THREAD

**Issue by animalize** [facebook/zstd#2300]
This [test code](https://github.com/animalize/misc/blob/master/size_use_dict.c) read all files in a folder to memory, and train a dictionary with these files:
(usage: modify `PATH` to zstd/lib/compress folder, should ends with `\` or `/` depend on the system)

Then compare these two cases:

1, One shot compress, all files concatenated in a single flat buffer.
```c
    // load dictionary to context
    cdict = ZSTD_createCDict(dict_buffer, DICT_SIZE, compression_level);
    ZSTD_CCtx_refCDict(cctx, cdict);
    
    // one shot compress
    ZSTD_compressStream2(cctx, &out, &in, ZSTD_e_end);
```

2, Stream compress, file by file.
```c
    // load dictionary to context
    cdict = ZSTD_createCDict(dict_buffer, DICT_SIZE, compression_level);
    ZSTD_CCtx_refCDict(cctx, cdict);
    
    // stream compress, file by file
    in.src = &input_buffer;
    for (int i = 0; i < content_count; i++) {
        in.size = content_sizes[i];
        in.pos = 0;
        
        ZSTD_compressStream2(cctx, &out, &in, ZSTD_e_continue);
        
        in.src += content_sizes[i];
    }
    // end the frame
    in.size = 0;
    in.pos = 0;
    ZSTD_compressStream2(cctx, &out, &in, ZSTD_e_end);
```

It seems one shot compress doesn't respect `compressionLevel`, its output size is always `121086` bytes.

The output of test code:
```
Read 25 files, total read size: 687379

compressionLevel 0:
One shot compress, output size: 121086
Stream compress, output size: 120456

compressionLevel 1:
One shot compress, output size: 121086
Stream compress, output size: 150086

compressionLevel 2:
One shot compress, output size: 121086
Stream compress, output size: 136046

compressionLevel 3:
One shot compress, output size: 121086
Stream compress, output size: 120456

compressionLevel 4:
One shot compress, output size: 121086
Stream compress, output size: 119666

compressionLevel 5:
One shot compress, output size: 121086
Stream compress, output size: 109670

compressionLevel 6:
One shot compress, output size: 121086
Stream compress, output size: 102324

compressionLevel 7:
One shot compress, output size: 121086
Stream compress, output size: 100145

compressionLevel 8:
One shot compress, output size: 121086
Stream compress, output size: 97499

compressionLevel 9:
One shot compress, output size: 121086
Stream compress, output size: 95822

compressionLevel 10:
One shot compress, output size: 121086
Stream compress, output size: 94824

compressionLevel 11:
One shot compress, output size: 121086
Stream compress, output size: 94244

compressionLevel 12:
One shot compress, output size: 121086
Stream compress, output size: 92322

compressionLevel 13:
One shot compress, output size: 121086
Stream compress, output size: 96481

compressionLevel 14:
One shot compress, output size: 121086
Stream compress, output size: 88812

compressionLevel 15:
One shot compress, output size: 121086
Stream compress, output size: 86981

compressionLevel 16:
One shot compress, output size: 121086
Stream compress, output size: 86292

compressionLevel 17:
One shot compress, output size: 121086
Stream compress, output size: 86224

compressionLevel 18:
One shot compress, output size: 121086
Stream compress, output size: 86218

compressionLevel 19:
One shot compress, output size: 121086
Stream compress, output size: 86271

compressionLevel 20:
One shot compress, output size: 121086
Stream compress, output size: 86218

compressionLevel 21:
One shot compress, output size: 121086
Stream compress, output size: 86218

compressionLevel 22:
One shot compress, output size: 121086
Stream compress, output size: 86219
```

**Comment by Cyan4973** [comment]
When the amount of input to dictionary-compress is "large",
it's preferable to re-build the dictionary and adjust the compression parameters to the target size
rather than use the built-in dictionary in `cdict` which is more targeted at small data.

I don't remember what is the threshold, but looking at the sizes displayed in this example, input may indeed cross the threshold, and therefore trigger the dictionary re-build stage.

This capability is relatively recent, and it's possible that an undetected issue slipped through its development.
For example, maybe this new method forgets to transfer the compression level from the dictionary, and uses the one in `cctx` instead.
I presume that setting the compression level explicitly into the `cctx` would fix this issue.

cc @senhuang42

**Comment by senhuang42** [comment]
Yep, I'm not sure how big your dictionary is, but if your input is larger than 128KB AND your input is more than 6x the size of the dictionary, we will automatically re-load the dictionary and adjust the compression parameters based on data you're compressing rather than based on the parameters in the CDict.

You can forcibly disable this with: `ZSTD_CCtx_setParameter(cctx, ZSTD_c_forceAttachDict, [ZSTD_dictForceAttach | ZSTD_dictForceCopy])` to respect the CDict's params.

One thing to note is that compression levels are just numbers that map to a set of parameters. In the case of a dictionary, it's hard to tell what parameters to use without any knowledge of the input, so it's usually beneficial to readjust these parameters after getting more info about the data's size, deferring to the `cctx`.

I'm not sure if it's better to let the compression level of the `cdict` or `cctx` to supersede. I think while developing this feature we leaned towards the latter to emphasize the fact that we are using the `cdict` purely for its dictionary content rather than any parameters it might set. @Cyan4973 any thoughts?

**Comment by Cyan4973** [comment]
This is essentially an API consistency issue. Let's discuss this later today.

**Comment by senhuang42** [comment]
As discussed, `cdict` will supersede, PR to come.

**Comment by animalize** [comment]
Thanks for your answers.

Off topic but related, I suppose this line can be removed, but I am not sure:
https://github.com/facebook/zstd/blob/v1.4.5/lib/compress/zstd_compress.c#L3098

```c
    if ( (cdict)
      && (cdict->dictContentSize > 0)
      && ( pledgedSrcSize < ZSTD_USE_CDICT_PARAMS_SRCSIZE_CUTOFF
        || pledgedSrcSize < cdict->dictContentSize * ZSTD_USE_CDICT_PARAMS_DICTSIZE_MULTIPLIER
        || pledgedSrcSize == ZSTD_CONTENTSIZE_UNKNOWN
        || cdict->compressionLevel == 0)    // <-- this line
      && (params->attachDictPref != ZSTD_dictForceLoad) ) {
        return ZSTD_resetCCtx_usingCDict(cctx, cdict, params, pledgedSrcSize, zbuff);
    }
```

**Comment by senhuang42** [comment]
Ah, the reason that's there is that `cdict->compressionLevel` is an overloaded parameter, and `compressionLevel==0` implies usage of the advanced API. So in the case that we're using the advanced API for `cdict` creation, we actually want to fully respect the user's choice in whether or not to reload the dictionary.

I suppose some more documentation here (rather than just in the init function) wouldn't hurt.

**Comment by animalize** [comment]
> 
> 
> Ah, the reason that's there is that `cdict->compressionLevel` is an overloaded parameter, and `cdict->compressionLevel==0` implies usage of the advanced API. So in the case that we're using the advanced API for `cdict` creation, we actually want to fully respect the user's choice in whether or not to reload the dictionary.
> 
> I suppose some more documentation here (rather than just in the init function) wouldn't hurt.

Okay, after reading your explanation and reading the code, I have no doubts about it.

**Comment by animalize** [comment]
Sorry, found another problem.
Should add below code to `ZSTD_createCDict_byReference()`, so it can be consistent with [`ZSTD_createCDict()`](https://github.com/facebook/zstd/blob/v1.4.5/lib/compress/zstd_compress.c#L3447-L3456):

```diff
 lib/compress/zstd_compress.c | 9 ++++++---
 1 file changed, 6 insertions(+), 3 deletions(-)

diff --git a/lib/compress/zstd_compress.c b/lib/compress/zstd_compress.c
index 4866c2f0..84fc25ce 100644
--- a/lib/compress/zstd_compress.c
+++ b/lib/compress/zstd_compress.c
@@ -3463,9 +3463,12 @@ ZSTD_CDict* ZSTD_createCDict(const void* dict, size_t dictSize, int compressionL
 ZSTD_CDict* ZSTD_createCDict_byReference(const void* dict, size_t dictSize, int compressionLevel)
 {
     ZSTD_compressionParameters cParams = ZSTD_getCParams_internal(compressionLevel, ZSTD_CONTENTSIZE_UNKNOWN, dictSize);
-    return ZSTD_createCDict_advanced(dict, dictSize,
-                                     ZSTD_dlm_byRef, ZSTD_dct_auto,
-                                     cParams, ZSTD_defaultCMem);
+    ZSTD_CDict* cdict = ZSTD_createCDict_advanced(dict, dictSize,
+                                                  ZSTD_dlm_byRef, ZSTD_dct_auto,
+                                                  cParams, ZSTD_defaultCMem);
+    if (cdict)
+        cdict->compressionLevel = compressionLevel == 0 ? ZSTD_CLEVEL_DEFAULT : compressionLevel;
+    return cdict;
 }
 
 size_t ZSTD_freeCDict(ZSTD_CDict* cdict)
```

**Comment by senhuang42** [comment]
Great catch, thanks! I'll open a PR for that as well (or feel free to do so yourself if you'd like!) ☺️

**Comment by animalize** [comment]
Please do it together.
Approving a PR from me is no less than doing it directly.

**Comment by animalize** [comment]
It seems PR https://github.com/facebook/zstd/pull/2303 fixed this problem.
Test code output:
```
Read 25 files, total read size: 687379

compressionLevel 0:
One shot compress, output size: 121086
Stream compress, output size: 120456

compressionLevel 1:
One shot compress, output size: 138726
Stream compress, output size: 150067

compressionLevel 2:
One shot compress, output size: 131304
Stream compress, output size: 136046

compressionLevel 3:
One shot compress, output size: 121086
Stream compress, output size: 120456

compressionLevel 4:
One shot compress, output size: 120648
Stream compress, output size: 119666

compressionLevel 5:
One shot compress, output size: 109769
Stream compress, output size: 109670

compressionLevel 6:
One shot compress, output size: 104699
Stream compress, output size: 102324

compressionLevel 7:
One shot compress, output size: 99812
Stream compress, output size: 100145

compressionLevel 8:
One shot compress, output size: 98213
Stream compress, output size: 97499

compressionLevel 9:
One shot compress, output size: 96002
Stream compress, output size: 95822

compressionLevel 10:
One shot compress, output size: 95948
Stream compress, output size: 94824

compressionLevel 11:
One shot compress, output size: 95948
Stream compress, output size: 94244

compressionLevel 12:
One shot compress, output size: 94586
Stream compress, output size: 92322

compressionLevel 13:
One shot compress, output size: 92198
Stream compress, output size: 96481

compressionLevel 14:
One shot compress, output size: 92198
Stream compress, output size: 88812

compressionLevel 15:
One shot compress, output size: 91807
Stream compress, output size: 86981

compressionLevel 16:
One shot compress, output size: 87556
Stream compress, output size: 86292

compressionLevel 17:
One shot compress, output size: 86891
Stream compress, output size: 86224

compressionLevel 18:
One shot compress, output size: 85952
Stream compress, output size: 86218

compressionLevel 19:
One shot compress, output size: 85592
Stream compress, output size: 86271

compressionLevel 20:
One shot compress, output size: 85592
Stream compress, output size: 86218

compressionLevel 21:
One shot compress, output size: 85572
Stream compress, output size: 86218

compressionLevel 22:
One shot compress, output size: 85595
Stream compress, output size: 86219
```
