### ISSUE TITLE
Decoding error (36) : Corrupted block detected

### ISSUE THREAD

**Issue by OrNixx** [facebook/zstd#2302]
# zstd -d vzdump-qemu-101-2020_09_06-00_00_02.vma.zst
_06-00_00_02.vma.zst : 317172 MB...     _06-00_00_02.vma.zst : Decoding error (36) : Corrupted block detected

Hello. Tell me please, is it possible to skip corrupted blocks and restore at least part of data?

**Comment by Cyan4973** [comment]
It's generally possible to restore data up to the corrupted block, though not beyond that point.
The `zstd` CLI should already do that by default.

**Comment by felixhandte** [comment]
To expand on that: each block depends on the content of previous ones. So if one can't be decompressed, it's not possible to reconstruct subsequent ones either.
