### ISSUE TITLE
Question about Windows CLI version

### ISSUE THREAD

**Issue by animalize** [facebook/zstd#2304]
I downloaded a Windows CLI program (`zstd-v1.4.5-win64.zip`) from here:
https://github.com/facebook/zstd/releases/tag/v1.4.5

Right click file `zstd.exe`,  Properties -> Details, the "FileVersion" is "1.4.4.0", "ProductVersion" is "1.4.4".

But the version reported in CLI is "v1.4.5" :
```
E:\>zstd.exe --version
*** zstd command line interface 64-bits v1.4.5, by Yann Collet ***
```

It seems "FileVersion" and "ProuctVersion" are defined by zstd macro:
https://github.com/facebook/zstd/blob/v1.4.5/build/VS2010/zstd/zstd.rc

Did it misuse zstd v1.4.4 library when compiling v1.4.5 CLI program?

**Comment by Cyan4973** [comment]
Maybe the automated script which generates the `zstd` windows binary doesn't update the Windows Resource file, 
either there is no automation for this, or it is not triggered before package build.

Something to investigate, though as none of us use Windows, it's actually complex to do.

**Comment by ghost** [comment]
zstd.exe (v1.4.7) no longer has "FileVersion" and "ProductVersion", close this issue.
