### ISSUE TITLE
Question about ZSTD_c_hashLog and ZSTD_c_chainLog

### ISSUE THREAD

**Issue by animalize** [facebook/zstd#2305]
It's weekend, no need to reply immediately.

In [zstd.h](https://github.com/facebook/zstd/blob/dev/lib/zstd.h), `ZSTD_cParameter` enum has these descriptions:
```c
    ZSTD_c_hashLog=102,      /* Size of the initial probe table, as a power of 2.
                              * Resulting memory usage is (1 << (hashLog+2)). */
    ...
    ZSTD_c_chainLog=103,     /* Size of the multi-probe search table, as a power of 2.
                              * Resulting memory usage is (1 << (chainLog+2)). */
```
But there seems no `+2` in the source code, the usages are `1 << value`
Is the comment wrong?

**Comment by aqrit** [comment]
The comment seems correct. 
There are two steps: `hSize = 1 << hashLog` then `hSize * sizeof(U32)`
(shifting left by two is equivalent to multiplying by 4).

**Comment by animalize** [comment]
Thanks, I see.

I wrote a pyzstd module for Python, I had this problem when I wrote the [document](https://pyzstd.readthedocs.io/en/latest/).
