### ISSUE TITLE
Can I run zstd_compress/zstd_decompress inside a GPU thread?

### ISSUE THREAD

**Issue by shauryapatel1995** [facebook/zstd#2307]
I am trying to run the compression and decompression algorithms directly inside GPU threads. I was wondering if it is possible to run these functions directly inside GPU kernels with the cuda architecture?

**Comment by felixhandte** [comment]
Hi @shauryapatel1995,

There is not (to my knowledge) any toolchain for compiling generic C code for execution on a GPU. To run code on a GPU you have to write code in a domain-specific language (CUDA or OpenCL). No such port exists at the moment for Zstd.

I know nvidia has released a compression tool that can run on the GPU here: https://github.com/castano/nvidia-texture-tools. Maybe that will work for your use-case?

**Comment by shauryapatel1995** [comment]
Hey @felixhandte, thanks for the reply, unfortunately, the Nvidia tool can't work for my use case but maybe I can work something out!

**Comment by mnicely** [comment]
@shauryapatel1995 Do you mind explaining your use case here? 
https://github.com/NVIDIA/nvcomp

**Comment by shauryapatel1995** [comment]
Hi @mnicely I have already attempted to use nvcomp and have had discussions with them. Unfortunately it didn't work for my use case. It was for a project that I have already given up on at this point!

**Comment by ahfuzhang** [comment]
@shauryapatel1995 hi, sir, I am looking for macos gpu version of zstd.
If you have such a code, could you share it to me? thanks.
My email is : ahfuzhang@gmail.com

**Comment by shauryapatel1995** [comment]
Hi @ahfuzhang, I am not aware of such a port, but there are other compression solutions you can use. [nvcomp](https://github.com/NVIDIA/nvcomp), [cuSZ](https://github.com/szcompressor/cuSZ) and [zfp](https://computing.llnl.gov/projects/zfp). I have personally used zfp and it works well. We worked on optimizations to use zfp effectively in streams with ML training. You can check out our paper [here](https://ieeexplore.ieee.org/document/9651175).
