### ISSUE TITLE
`EXEC_PREFIX` and `PREFIX` are interpreted as regexes resulting in build failures in some cases

### ISSUE THREAD

**Issue by jmesmon** [facebook/zstd#2312]
**Describe the bug**

In [lib/Makefile](https://github.com/facebook/zstd/blob/d96e98cfde66e9e20dcadcfd9ed3b82ba648adfe/lib/Makefile#L273-L290), `PCLIBDIR` and `PCINCDIR` assignments treat `EXEC_PREFIX` and `PREFIX` as regular expressions, which can result in `PCLIBDIR` (and/or `PCINDIR`) testing as empty, and then triggering the later errors.

I observed this within a oe build that had a `prefix` with a `+` in it (which is common for oe sdk packages)

**To Reproduce**
1. `make PREFIX=$HOME/xxx/x+foo`
2. it shows:

```
make[1]: Entering directory '/home/cody/d/zstd/lib'
Makefile:280: *** configured libdir (/home/cody/xxx/x+foo/lib) is outside of prefix (/home/cody/xxx/x+foo), can't generate pkg-config file.  Stop.
make[1]: Leaving directory '/home/cody/d/zstd/lib'
make: *** [Makefile:63: lib-release] Error 2
```

**Expected behavior**

Build succeeds. (ie: what happens if `+` is replaced with a normal character)

**Additional info**

In oe, I've worked around this with the `zstd_%.bbappend` fragment to set the `PCLIBDIR`/`PCINCDIR` directly:
```
export PCLIBDIR="${@oe.path.relative("${exec_prefix}", "${libdir}")}"
export PCINCDIR="${@oe.path.relative("${prefix}", "${includedir}")}"
```

**Comment by jmesmon** [comment]
Also notable: the error messages here appear to print the wrong `prefix` vs `exec_prefix` value. This initially threw me off, but in my case they're set to the same value anyhow.

**Comment by felixhandte** [comment]
Should be fixed in `dev`.
