### ISSUE TITLE
zstd fails to compile with uclibc-ng

### ISSUE THREAD

**Issue by stefson** [facebook/zstd#2316]
uclibc-ng is a libc for embedded systems, it's lean and much faster than glibc. However, it can't compile zstd with it's uclibc-ng and gcc based toolchain: 

```
util.c: In function 'UTIL_setFileStat':
util.c:161:24: error: storage size of 'timebuf' isn't known
  161 |         struct utimbuf timebuf;
      |                        ^~~~~~~
util.c:164:16: warning: implicit declaration of function 'utime'; did you mean 'ctime'? [-Wimplicit-function-declaration]
  164 |         res += utime(filename, &timebuf);
      |                ^~~~~
      |                ctime
util.c:161:24: warning: unused variable 'timebuf' [-Wunused-variable]
  161 |         struct utimbuf timebuf;
      |                        ^~~~~~~
make[1]: *** [<builtin>: util.o] Error 1

```
if you're on linux, it's always possible to grab a stage3 from: http://distfiles.gentoo.org/experimental/arm/uclibc/ , unpack locally and chroot into it. Just compile the package with package manager: ```emerge -av zstd```

I really don't know if that happens due to a bug in zstd code, or if it's due to a bug in uclibc-ng code. Also I'm not using this libc for anything important, so this bug report is meant to tell you about the build failure, and maybe if it's your bug to fix it into one of the next releases of zstd lib. thanks

**Comment by Cyan4973** [comment]
`struct utimbuf` is presumed to be part of `utime.h` : 
https://man7.org/linux/man-pages/man2/utime.2.html

As far as I can tell, it seems defined in `uclibc`, for a long time now : 
https://git.uclibc.org/uClibc/commit/?h=64bc6412188b141c010ac3b8e813b837dd991e

`uclibc-ng` self-describes as a spin-off of `uclibc` from ~2015.
I have no knowledge of this `libc`, though I would have expected it to be a superset of `uclibc`.
Maybe it's not.

**Comment by stefson** [comment]
this is fixed with the same fix for uclibc: https://github.com/facebook/zstd/pull/2243

do you mind telling me if that's going to be included into v1.4.6, and how close we are to the release?

**Comment by Cyan4973** [comment]
#2243 is part of `v1.4.6`.

`v1.4.6` is mostly ready by now, but must paired with another integration effort in the Linux Kernel, led by @terrelln and currently in review stage. When it's merged into the kernel, it will be possible to refer the kernel to `v1.4.6`, and formally finalize and publish the associated release.

`dev` is already passed that point, gearing towards `v1.4.7`.

**Comment by stefson** [comment]
do you think it's possible that you direct me toward that review stage, maybe it's a thread on the lkml? it's so that I can better anticipate if I need to backport the fix for my distro. thanks :)

**Comment by Cyan4973** [comment]
It's on `lkml`.
Mirror : https://www.spinics.net/lists/linux-crypto/msg50393.html

**Comment by stefson** [comment]
I see, but this seems to be the zstd builtin copy the kernel uses to decompress an initramfs, and has nothing to do with allowing ```>=zstd-1.4.6``` to be run in the userspace, right?

**Comment by terrelln** [comment]
@stefson the goal is to ensure the kernel zstd is synced with an upstream zstd release. It could take some time to get this patch merged into the kernel. If it goes too long, say 3-4 weeks, then we will cut a zstd release anyway. So I'd say expect zstd-1.4.6 within a month.

**Comment by stefson** [comment]
ok, thank you so much for giving me the information, I'll talk with the people responsible for packaging at my distro and solve the problem with them.
