### ISSUE TITLE
Can I pick a licensen between BSD and GPL for every file in v1.4.4?

### ISSUE THREAD

**Issue by PeterAlfredLee** [facebook/zstd#2318]
Hi all.

I noticed the license declaimer in code files was modified with commit `ac58c8d7` on 27, Mar, 2020. For some older versions like `v1.4.4`, the license declaimers were not a same one :

1. `lib\compress\hist.c` has a BSD-2 Clause license;
2. `lib\compress\zstd_ldm.c` has a dual license of BSD-3 Clause and GPL, but without the declaimer that I can select one of the them;

For the zstd version `v1.4.4`, may I compile and use these code files with only BSD license?

**Comment by Cyan4973** [comment]
yes

**Comment by PeterAlfredLee** [comment]
@Cyan4973 Thank you for your great contributions of zstd! It's awesome.
