### ISSUE TITLE
ZSTD_seekable_decompress() can hang

### ISSUE THREAD

**Issue by mdittmer** [facebook/zstd#2335]
**Describe the bug**
`ZSTD_seekable_decompress()` can hang.

**To Reproduce**
Checkout #2334 

```
$ cd contrib/seekable_format/examples
$ make
$ ./hang
```

**Expected behavior**
Program halts, returning some ZSTD error as status code.

**Additional context**
This bug was found via [this fuzzer](https://fuchsia.googlesource.com/fuchsia/+/6c0911153a4b36d5a6ab86f74cc9d1a313d8e8ca/src/storage/blobfs/test/zstd-seekable-fuzzer.cc). The specific decompressor input is an input generated by the fuzzer to reproduce the issue.

**Comment by senhuang42** [comment]
Resolved in #2408
