### ISSUE TITLE
Question: Streaming limitations

### ISSUE THREAD

**Issue by RelayrMA** [facebook/zstd#2340]
In the current project we're sending many small messages over the network but we're being billed by 4KB block. There's also a hard limit of 64KB message size, anything larger than that won't pass.

So we're trying to aggregate these small messages into buffers which take a little under 4 KB after compression.
This task seems surprisingly hard to do right...

* To meet 4 KB limit we're flushing and using a rough compression ratio estimation for the message that we mean to add (the messages are highly repeatable, about 10:1 is right). If we pass 4KB - not a big deal, just try to fill 8 KB. And so on until 64 KB.
* To meet 64 KB limit we're flushing, checking the size so far plus ZSTD_compressBound(nextMessageSize).

The problems with that:
* The ZSTD_compressBound() docs explicitly forbid our use. What can we do to get a hard bound for our case?
* I read that frequent flushes cost a lot of compression. Is that still the case? I don't think we can avoid flushing frequently...
* To get the final bound *really* tight it would be useful to be able to:
  * make a backup copy of the stream, input and output buffers
  * put a message in the stream opportunistically
  * if the size is too large - use the backup

I recognise that these backups would be SLOW. It's fine, we don't have to do it until the buffer is near-full which should significantly reduce the overhead. Then we could evaluate whether the performance tradeoff is worth it for us. Still, it doesn't seem possible with the current API...

**Comment by terrelln** [comment]
> The ZSTD_compressBound() docs explicitly forbid our use. What can we do to get a hard bound for our case?

Add 3 bytes per flush.

> I read that frequent flushes cost a lot of compression. Is that still the case? I don't think we can avoid flushing frequently...

Flushing every 4K shouldn't have a huge impact on compression ratio, but it will probably be a few percent.

If you don't mind added latency, you could just pass your data to zstd without any flushing. Then, just send exactly 4KB of compressed data at a time. The decompressor will need to wait until it receives a full block (128KB of uncompressed data) before it will start producing output, but it will buffer up the compressed data correctly.

Additionally, you can try the [`ZSTD_c_targetCBlockSize`](https://github.com/facebook/zstd/blob/4b4d8b4dc959e7bda5a5d412df245a1723544889/lib/zstd.h#L1544-L1545) parameter and setting it to 4KB. The implementation isn't perfect, so it can't guarantee <= 4KB blocks, but it will do its best. So 99% of the time you will have blocks ~= 4KB.

**Comment by RelayrMA** [comment]
> > The ZSTD_compressBound() docs explicitly forbid our use. What can we do to get a hard bound for our case?
> 
> Add 3 bytes per flush.

Thanks!

> 
> > I read that frequent flushes cost a lot of compression. Is that still the case? I don't think we can avoid flushing frequently...
> 
> Flushing every 4K shouldn't have a huge impact on compression ratio, but it will probably be a few percent.
> 
> If you don't mind added latency, you could just pass your data to zstd without any flushing. Then, just send exactly 4KB of compressed data at a time. The decompressor will need to wait until it receives a full block (128KB of uncompressed data) before it will start producing output, but it will buffer up the compressed data correctly.
> 
> Additionally, you can try the [`ZSTD_c_targetCBlockSize`](https://github.com/facebook/zstd/blob/4b4d8b4dc959e7bda5a5d412df245a1723544889/lib/zstd.h#L1544-L1545) parameter and setting it to 4KB. The implementation isn't perfect, so it can't guarantee <= 4KB blocks, but it will do its best. So 99% of the time you will have blocks ~= 4KB.

Full streaming does not seem to be a good option for us. We can't guarantee that messages arrive in order. We'd rather avoid assumptions about the work of load balancer (i.e. that the same worker processes the entire stream) at the protocol level. We don't want to deal with stuff like worker restarts in the middle of the stream. So each message that we send is self-contained and we want it to stay like that.

Actually we're not flushing every 4KB because we don't know where they end. Initially we flushed before every message, so every ~100B. Considering high compression ratio, the cost of flushes seems like a very expensive option...but our benchmark doesn't show that. We changed the implementation so that as long as ZSTD_compressBound() is < 4KB, there are no flushes. It didn't reduce the number of flushes all that much, merely by 7% but the output size didn't change by even a single byte. I wonder if we're doing something wrong...

**Comment by terrelln** [comment]
@RelayrMA I must have misunderstood the use case.

If I understand correctly, you will stream trying to flush (with `ZSTD_e_flush`) to get compressed data close to a 4KB boundary. Once you achieve that, or get too close to 64KB you will end the frame (with `ZSTD_e_end`) and send it over the network.

Is that correct?

**Comment by RelayrMA** [comment]
Yes

**Comment by Cyan4973** [comment]
Any remaining action / question ?
