### ISSUE TITLE
Pass ZSTD_dictMode_e into CParams Adjustment

### ISSUE THREAD

**Issue by felixhandte** [facebook/zstd#2342]
**Is your feature request related to a problem? Please describe.**
#2337 causes the dict size to be taken into account when sizing down the working context tables. However, it is increasingly the case with dictionaries that they remain independent from the working context (attached, either normally or with a DDSS), and the working context does not need to be sized to support searches into the dictionary. So I think it likely that #2337 will be a pessimization for those scenarios.

**Describe the solution you'd like**
We should take the dictMode into account when sizing the working context tables. In particular, when attaching a dictionary, we should ignore the dict size when adjusting the working context table sizes.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Cyan4973** [comment]
Is this issue complete ?

**Comment by terrelln** [comment]
Yeah
