### ISSUE TITLE
Repeat offsets are documented incorrectly

### ISSUE THREAD

**Issue by yotann** [facebook/zstd#2346]
The [documentation for repeat offsets](https://github.com/facebook/zstd/blob/8adeb9f1e62aa43dd2dda1ca7b11791d2365f276/doc/zstd_compression_format.md#repeat-offsets) is incorrect in the case where a repeat offset *could* have been used but a non-repeat offset was used instead. This case occurs in [silesia.tar.zst](https://github.com/facebook/zstd/releases/tag/regression-data).

For example:
```
Repeated_Offset1 = 1
Repeated_Offset2 = 4
Repeated_Offset3 = 8
offset_value = 4
NewOffset = offset_value - 3 = 1
```

The documentation indicates that, because NewOffset matches Repeated_Offset1, the Repeated_Offset values will be left unchanged just as if offset_value had been 1. That's incorrect. Instead, because a non-repeat offset was used, the Repeated_Offset values are updated just as if NewOffset didn't match any of them. The correct result is this:
```
Repeated_Offset1 = 1
Repeated_Offset2 = 1
Repeated_Offset3 = 4
```

As another issue, if the NewOffset is 0, the reference implementation treats it as if it were 1. The [full behavior used to update Repeated_Offset](https://github.com/facebook/zstd/blob/f7d49437885fe2ecafeb0d2663a5c891ba57231a/lib/decompress/zstd_decompress_block.c#L957) works as follows.

```python
if offset_value <= 3:
    if literal_length == 0:
        offset_value = offset_value + 1
    if offset_value == 1:
        NewOffset = Repeated_Offset1
    elif offset_value == 2:
        NewOffset = Repeated_Offset2
        Repeated_Offset2 = Repeated_Offset1
        Repeated_Offset1 = NewOffset
    elif offset_value == 3:
        NewOffset = Repeated_Offset3
        Repeated_Offset3 = Repeated_Offset2
        Repeated_Offset2 = Repeated_Offset1
        Repeated_Offset1 = NewOffset
    else: # offset_value == 4
        NewOffset = Repeated_Offset1 - 1
        if NewOffset == 0: # corrupted input
            NewOffset = 1
        Repeated_Offset3 = Repeated_Offset2
        Repeated_Offset2 = Repeated_Offset1
        Repeated_Offset1 = NewOffset
else: # offset_value > 3
    NewOffset = offset_value - 3
    Repeated_Offset3 = Repeated_Offset2
    Repeated_Offset2 = Repeated_Offset1
    Repeated_Offset1 = NewOffset
```

**Comment by yotann** [comment]
RFC erratum: https://www.rfc-editor.org/errata/eid6303

**Comment by terrelln** [comment]
Thanks for the report @yotann!

CC @Cyan4973

**Comment by Cyan4973** [comment]
Thanks for the feedback @yotann ,
we will introduce a new formulation for this part of the spec
in order to reduce risks of confusion underlined in this issue.

**Comment by senhuang42** [comment]
I believe that this might be a slightly clearer way to reason about it
```
if litLength != 0:
    if new_offset == repeat_offset_1:
        repcode = 1
        do not update repcodes
    else if new_offset == repeat_offset_2:
        repcode = 2
        swap ranks of repeat_offset_2 and repeat_offset_1
    else if new_offset == repeat_offset_3:
        repcode = 3
        update repcodes as usual
    else:
        update repcodes as usual
else:
    if new_offset == repeat_offset_2:
        repcode = 1
        swap ranks of repeat_offset_2 and repeat_offset_1
    else if new_offset == repeat_offset_3:
        repcode = 2
        update repcodes as usual
    else if new_offset == repeat_offset_1 - 1:
        repcode = 3
        update repcodes as usual
    else:
        update repcodes as usual
```
