### ISSUE TITLE
Could you add my pyzstd module to Zstandard homepage?

### ISSUE THREAD

**Issue by animalize** [facebook/zstd#2347]
The information:
```
Language: Python
Author  : Ma Lin
URL     : https://pypi.org/project/pyzstd
```

After a month of development, the API seems to be stable.

Moreover, thanks for your answers in these days, they helped me a lot.

**Comment by felixhandte** [comment]
Is there a distinguishing characteristic you want to highlight between your binding and the two we currently list? E.g., the two we have are labeled "simple" and "full".

**Comment by animalize** [comment]
> Is there a distinguishing characteristic you want to highlight between your binding and the two we currently list? E.g., the two we have are labeled "simple" and "full".

Its API style is similar to the bz2/lzma module in the Python standard library, but it's hard to write these in one word.

Please just leave the distinguishing characteristic blank, and put this module as the third of Python modules.

**Comment by Cyan4973** [comment]
module  added

**Comment by animalize** [comment]
Thanks

**Comment by animalize** [comment]
"(std api)" sounds a bit strange, it seems to be saying that the API of other modules is not standard.

IMO the user will choose what they need, so please remove "(std api)".

When there is enough time, maybe you can use [mvanleeu's suggestion](https://github.com/facebook/zstd/issues/2296#issuecomment-693295946):
 
> 
> I'm not sure this presentation is very readable, as different dimensions are indicated in the same manner (binding vs port; buffers-only or also streaming support; dict support or not, plus other tags/comments like "decoder" "signed", "emscripten" etc) after the name.
> Wouldn't it make more sense to make it more explicit by adding more columns, and have something like the following structure?
> 
> Language | _flavour_ | _features_ | Author | URL
> 
> With _flavour_ being "binding" or "port" (i.e. explicitly), _features_ a list of tags like "streaming", "dict", "decoder-only" etc...
> Assumption for the features is that the ports/binding making the list of the homepage implement a decoder for buffers at least. Some of them do not have an encoder (and are explicitly marked as decoder only), some of them do more like dict support, streaming etc.
