### ISSUE TITLE
Could you please add this new Dart binding to the website?

### ISSUE THREAD

**Issue by marianopeck** [facebook/zstd#2389]
Hi guys,

We have created a new Zstd binding for Dart language. Our binding covers most of the Zstd features and options. We would like if you can add a new entry in the table of "Multiple programming languages" in https://facebook.github.io/zstd/

The info should be:

Language: Dart
Author: Instantiations
URL: https://pub.dev/documentation/es_compression/latest/zstd/zstd-library.html

Thanks in advance and thanks a lot for such a great product!

**Comment by Cyan4973** [comment]
Thanks for the great work @marianopeck !
Your `Dart` binding has been added to [`zstd` homepage](https://facebook.github.io/zstd/#other-languages).

**Comment by marianopeck** [comment]
Thanks a lot @Cyan4973 !!!
Btw, the great work is from @sethloco  I am just the messager ;)

**Comment by sethloco** [comment]
Hi @Cyan4973 
Thanks so much for your responsiveness and for the great work that you have done.
It certainly has added a lot of value to our software over the years!
