### ISSUE TITLE
v1.1.4 compress is faster than v1.4.5?

### ISSUE THREAD

**Issue by rooong** [facebook/zstd#2391]
**v1.1.4 compress is faster than v1.4.5??**

I had a simple test between v1.1.4 and v1.4.5 compress the same file，the progam from github release version,
they are zstd-v1.1.4-win64-fix and zstd-v1.4.5-win64, my os is windows7 x64 , i5-4590
compress file is a binary file, about 3M size.

cmd:zstd.exe -18 testfile.rec
the test result is: **v1.1.4 cost about 1.0s, v1.4.5 cost about 1.20s**

i test many times...

it is really? or is there something what i donot know? the actual result should not be v1.4.5 faster than v.1.1.4？
[testfile.zip](https://github.com/facebook/zstd/files/5522593/testfile.zip)

**Comment by Cyan4973** [comment]
A lot has changed between these 2 versions,
and no, there is no guarantee that newer versions are strictly faster than older ones.
We can rebalance parameters between versions, generally resulting in some improvement in at least one metric, but also with other side-effects which can be more or less beneficial depending on exact scenario.
And by the way, when it comes to higher compression levels, the scale has been rebalanced towards (slightly) stronger (hence slower) compression.

That being said, citing the compression speed alone is not an accurate comparison.
You could have also mentioned compression ratio.
And on this front, `zstd_v1.4.5 -18` is expected to compress stronger than `zstd_v1.1.4 -18`.
Actually, one could decide to trade some of this compression ratio advantage for more speed, and use level 17 instead. 
Let's see. Quick test on my laptop:

| filename | version | level | C.Ratio | C.Speed | D.Speed |
| --- | --- | --- | --- | --- | --- |
| calgary.tar | v1.4.5 | 18 | 3.629 | 3.20 | 613 |
| calgary.tar | v1.4.5 | 17 | 3.582 | 4.00 | 658 |
| calgary.tar | v1.1.4 | 18 | 3.554 | 3.50 | 511 |
| |
| enwik7 | v1.4.5 | 18 | 3.559 | 1.83 | 532 |
| enwik7 | v1.4.5 | 17 | 3.520 | 2.21 | 544 |
| enwik7 | v1.1.4 | 18 | 3.511 | 2.10 | 446 |
| |
| testfile.rec | v1.4.5 | 18 | 6.162 | 2.71 | 706 |
| testfile.rec | v1.4.5 | 17 | 6.101 | 3.76 | 725 |
| testfile.rec | v1.1.4 | 18 | 6.031 | 3.20 | 601 |

There you have it : `v1.4.5` at level 17 compresses stronger and faster than `v1.1.4` at level 18. It decompresses faster too.
Of course, exact outcome vary depending on files, but you've got the gist of it.

Hence if `v1.1.4` at level 18 represented your "limit budget" in term of compression speed, you might find `v1.4.5` at level 17 an interesting replacement.

**Comment by rooong** [comment]
oo, you are right. I try it change level to 17 as you do, the result is like yours.
thanks you very much
