### ISSUE TITLE
can vc++6.0 use this as a static library????

### ISSUE THREAD

**Issue by ohyeah521** [facebook/zstd#2392]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
can vc++6.0 use this as a static library????

i'm using vc++6.0 ,but the release file can not use.

**Comment by animalize** [comment]
> i'm using vc++6.0 ,but the release file can not use.

Please describe the problem in detail.

Have you ever tried to compile zstd source code with your project? Put the `lib` folder into your project, and include `zstd.h` in C++ file.

**Comment by felixhandte** [comment]
Closing based on inactivity.
