### ISSUE TITLE
Random access file archive format for zstd

### ISSUE THREAD

**Issue by abitrolly** [facebook/zstd#2396]
**Describe the bug**
1. It is impossible to delete from from `.tar.zstd` archive
2. It is impossible to extract a single file from `.tar.zstd` without decompressing prior files

**To Reproduce**

1. Create some `.tar.zstd` 
2. Try to remove a file from inside

**Comment by Cyan4973** [comment]
This is more a limitation of the `tar` format.
As the extension implies, `zstd` is merely compressing a file in `tar` format, and has no control on what's inside.

**Comment by abitrolly** [comment]
@Cyan4973 right, there is no solution to this problem outside.

**Comment by animalize** [comment]
Is it possible to create a new specification like `tar`, that supports random access, compressed or uncompressed data.

IMO people need an universal file-system in a file.
If a folder has thousands of small read-only files, copying or deleting it use a lot of time. If all in one file, it's convenient and faster.

**Comment by animalize** [comment]
`tar` was born in 1988, it doesn't have many features.
https://peazip.github.io/tar-file-format.html

**Comment by abitrolly** [comment]
@animalize there are a lot of existing formats https://en.wikipedia.org/wiki/List_of_archive_formats#Archiving_and_compression. Some of them like .7z support different compressions and options. The amount of features makes it very hard to create independent implementations. And keep them secure. That's why a simple format for hierarchical structures s is needed that is fast to seek and modify.

**Comment by abitrolly** [comment]
@Cyan4973 any.. explanation? ...

**Comment by Cyan4973** [comment]
I initially understood this issue as a question about `.tar.zst` format.

Were you instead implying that the `zstd` project should develop and implement a Random access file archive format as part of its scope ?

**Comment by abitrolly** [comment]
@Cyan4973 yep. Because benefits of compression such as parallelism and fast seek are lost when `zstd` is used with `.tar.zstd`, which makes a lot of things slow, for example in Linux packaging ecosystem.

**Comment by Cyan4973** [comment]
This exact capability is defined as part of the `zip` format specification : https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT .

It's already supported by `winzip`, for example.

**Comment by abitrolly** [comment]
@Cyan4973 looks like proprietary format to me, despite of its popularity. The spec mentioned is 46 pages long and doesn't allow reproduction without an exclusive permission.

> Any reproduction or distribution of this document in whole or in part without prior written permission from PKWARE is strictly prohibited.

I would think about hierarchical data with addressing and metadata, that is fast to seek and extract. Heard something about HDF5 format that data science community uses, and Blender 3D, which makes the format very close to how data is presented in memory. With the new non-volatile memory coming, maybe it is worth rethinking the format. Maybe it will end up being something like Btrfs in a file or Squashfs. Would be nice to see some benchmarks for that, like installing or updating Linux on some cloud instances.

**Comment by Cyan4973** [comment]
Such a scope is worth an entire dedicated project.

**Comment by abitrolly** [comment]
Maybe you get a better chance to have fun with that @facebook.
