### ISSUE TITLE
Test crashed in docker

### ISSUE THREAD

**Issue by xkszltl** [facebook/zstd#2400]
**Describe the bug**

I consistently hit a crash in test when run as part of a docker build.
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/5203025/100373113-37aea080-3045-11eb-8609-b75422175d28.png">
This part does not failed the test immediately, but there's another crash after it, and the test is killed:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/5203025/100374433-3da58100-3047-11eb-9f5f-36e650857965.png">

The first one seems to be a file name, with many `;32GF` there.
Sounds like memory corruption.

I hit this on a CentOS 7 machine running docker build.
Also tried the same build script:
1. Directly on this CentOS 7 host.
2. Manually called in `docker run`.
3. On another Ubuntu 18.04 machine running docker build.
but all works fine.

**Desktop (please complete the following information):**
 - OS: [e.g. Mac] CentOS 7
 - Version [e.g. 22] 1.4.5
 - Compiler [e.g gcc] gcc-9 (devtoolset-9)
 - Flags [e.g O2] build script: https://github.com/xkszltl/Roaster/blob/aa4187322d37e995496c54e976b115507d2542cd/pkgs/zstd.sh#L33-L46
 - Other relevant hardware specs [e.g. Dual-core] Single Xeon 6140
 - Build system [e.g. Makefile] Makefile

**Comment by xkszltl** [comment]
Even more strange is, during the latest crash, sssd (CentOS's auth service) on host is killed by watchdog...
Yes, host, not in docker, and docker is not run in privileged mode.

**Comment by Cyan4973** [comment]
This looks like a local host issue

**Comment by xkszltl** [comment]
> This looks like a local host issue

Could you explain more about what that means?

**Comment by xkszltl** [comment]
I had an repro with `docker run`.
Issue only shows up when no `-it` is provided (which is also the case of `docker build`), so TTY-related I guess.

**Comment by xkszltl** [comment]
We can provide a repro docker for this issue.
It has issue on both CentOS and Ubuntu host, but only continues execution on Ubuntu host even after error.

```
sudo docker run --rm --runtime runc roasterproject/debug:github.com_facebook_zstd_issues_2400 /etc/roaster/scripts/setup.sh zstd
```

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/5203025/100446182-4fd7fb80-30e9-11eb-8b91-63b41f0407e2.png">

This docker is built from `centos:7` base image, with some pkgs installed via yum/dnf.
Nothing fancy.
Image is 24.5 GB decompressed.
```
$ sudo docker images roasterproject/debug
REPOSITORY             TAG                                    IMAGE ID            CREATED             SIZE
roasterproject/debug   github.com_facebook_zstd_issues_2400   1269d13d157f        29 hours ago        24.5GB
```

Command `setup.sh zstd` runs `pkgs/zstd.sh` with a few helper env var.
You can also find it in https://github.com/xkszltl/Roaster/blob/aa4187322d37e995496c54e976b115507d2542cd/pkgs/zstd.sh#L33-L46

**Comment by Cyan4973** [comment]
Maybe it's a tty issue, but then it seems related to `lz4` command line, rather than `zstd`.
These issues have been fixed, but since the docker image provides an old version of `lz4`, they may still be active there.

An interesting test would be to update `lz4` to latest `v1.9.3` before running the test script again.

**Comment by xkszltl** [comment]
1.8.3 is the latest version shipped by CentOS 7.
I also found that on our build log of an ubuntu 18.04 based docker, which has an even older version r128 (the package we installed says `liblz4-dev_0.0~r131-2ubuntu3_amd64.deb` but it is recognized as r128):
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/5203025/100482087-46728180-3131-11eb-9777-9d1410b8892d.png">

Given the distro-stock version is old, can we avoid the use of buggy feature in test?
How well does lz4 work with/without tty should not affect zstd's correctness, so should be better to find an alternative way for compatibility.

**Comment by Cyan4973** [comment]
Updating `lz4` was just suggested as a test, not for a fix.

**Comment by xkszltl** [comment]
Doesn't help.

These 2 repro add the lz4 build script.
The only difference is `./setup.sh zstd` vs. `./setup.sh lz4 zstd`, and you can see the version in screenshot indicating LZ4 1.9.3 is correctly picked up.

Repro with LZ4 1.8.3 (CentOS stock):
```
sudo docker run -w /etc/roaster/scripts --rm --runtime runc roasterproject/debug:github.com_facebook_zstd_issues_2400 bash -c 'git remote set-url origin https://github.com/xkszltl/roaster.git && git fetch && git merge --ff-only 1a82e06 && sed -i "s/# *make check/make check/" pkgs/zstd.sh && ./setup.sh zstd'
```
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/5203025/100535614-731fb980-3255-11eb-9554-6fd7b093b8b7.png">

Repro with LZ4 1.9.3 (built from source):
```
sudo docker run -w /etc/roaster/scripts --rm --runtime runc roasterproject/debug:github.com_facebook_zstd_issues_2400 bash -c 'git remote set-url origin https://github.com/xkszltl/roaster.git && git fetch && git merge --ff-only 1a82e06 && sed -i "s/# *make check/make check/" pkgs/zstd.sh && ./setup.sh lz4 zstd'
```
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/5203025/100535538-e117b100-3254-11eb-8e8d-c9ba45f472fc.png">

Note the docker image is publicly available, you can run these repro on your side as well.

**Comment by Cyan4973** [comment]
Thanks for the report @xkszltl ,
this issue should now be fixed in `dev` branch.
