### ISSUE TITLE
Do files/directories compressed with zstd have an internal dictionary?

### ISSUE THREAD

**Issue by ghost** [facebook/zstd#2431]
Wasn't sure where to ask this question; if this is the wrong place do close the issue.

For example: `zstd mybigfile.bin` produces `mybigfile.bin.zst`.

Can I freely move this file around and decompress it on systems that have `zstd` installed? I'm concerned about the "dictionary" file; and if I need to account for that file as well?

**Comment by Cyan4973** [comment]
> Can I freely move this file around and decompress it on systems that have zstd installed?

yes

> I'm concerned about the "dictionary" file; and if I need to account for that file as well?

There is no dictionary file by default.

**Comment by ghost** [comment]
Thanks!
