### ISSUE TITLE
Entropy-only compression modes

### ISSUE THREAD

**Issue by tpwrules** [facebook/zstd#2467]
**Is your feature request related to a problem? Please describe.**
I'm interested in using Zstd for lossless compression of scientific video data. Zstd, in combination with prefiltering, offers compression ratios within a few percent of the popular lossless FFV1 codec but several times faster. Using the underlying FSE library is several times faster again with nearly the same compression ratio.

The problem here is that the video data is relatively low entropy, but does not have patterns. It seems from my tests that overall the effort that zstd puts into finding matches is wasted and it's the FSE backend that does the real work.

**Describe the solution you'd like**
I think it would be very useful for this, and similar applications, if Zstd could have the option to run the input data through FSE only instead of spending time trying to find matches. In the current bitstream format literal data is Huffman compressed. This means that the match finding is necessary for Zstd to achieve a similar compression ratio to raw FSE. Bypassing the match finding would require a revision to the format to have a FSE-compressed literal section to maintain good compression.

**Describe alternatives you've considered**
Obviously it would be easy for me to write my own file format which uses raw FSE. However, Zstd is currently an extremely popular and widely available implementation of the FSE algorithm. Using it would enable readers in particular to take advantage of easy availability and high performance of the Zstd library for fast decoding in many different contexts. For example, raw video could be decompressed using the Zstd command line tool for backward compatibility with any video program or analysis package which can use raw input.

I haven't carefully read the bitstream format, but it's possible there's a way to effectively FSE compress literal data without changing anything. If so, then a custom program (or an option in the Zstd library) could be used to write a primarily FSE-compressed stream that can be decompressed by any compliant Zstd implementation.

**Additional context**
I'm not expecting any great urgency in addressing this, but I'm hoping I can put it in the back of somebody's head to be implemented at some point, perhaps if or when the bitstream is next revised.

**Comment by terrelln** [comment]
The zstd format is fixed, and only supports Huffman compressed literals, so zstd cannot FSE compress literals. You can use the FSE library directly if you need FSE compressed literals.

It would be possible to add a Huffman only match finder, if that fits your use case.

**Comment by tpwrules** [comment]
From my tests, Huffman coding doesn't give the compression ratios I want, so I will use FSE directly, and I don't think it's necessary for you guys to make any changes.

Thank you for the quick response.
