### ISSUE TITLE
Is there a byte that the compression doesn't use?

### ISSUE THREAD

**Issue by applesthepi** [facebook/zstd#2468]
I want to compress several strings separately, then join them into 1 string. I need to separate these compressed segments by something. Is there a byte (0-255) that the compression doesn't use?

Apologies if this has been answered or is somewhere I'm not looking.

Edit:

It looks like the bytes are either "10" or somewhere around "50" so im going to just use "1" for now.

**Comment by terrelln** [comment]
> I want to compress several strings separately, then join them into 1 string. I need to separate these compressed segments by something. Is there a byte (0-255) that the compression doesn't use?

No. Compression aims to be as compact as possible and uses every byte.

What problem are you attempting to solve?

**Comment by PallHaraldsson** [comment]
>I need to separate these compressed segments by something.

I'm not sure you do. Just as you can concatenate uncompressed files, I believe it's supported for (only some) compressed file formats, such as gzip, and apparently zstd (I just checked) to concatenate the files with e.g. Unix cat.

If your strings are short then this will not be efficient. See e.g. what's then better (while I'm not sure it cupports such concatenation):

https://ed-von-schleck.github.io/shoco/

See also:
https://stackoverflow.com/questions/14744692/concatenate-multiple-zlib-compressed-data-streams-into-a-single-stream-efficient
>Since you don't mind venturing into C, you can start by looking at the code for gzjoin. [..]

and another answer:
>In addition to gzjoin which requires decompression of the first deflate stream, you can take a look at gzlog.h and gzlog.c, which efficiently appends short strings to a gzip file without having to decompress the deflate stream each time [..]

**Comment by PallHaraldsson** [comment]
@applesthepi
>It looks like the bytes are either "10" or somewhere around "50" so im going to just use "1" for now.

Don't do that (it's also not needed, see my comment above). It WILL break. You just got lucky, not every byte is used all the time, but it's very likely you get each possible byte, and all for longer files.

You/someone should also close this issue, as your question(s) have been answered.

**Comment by terrelln** [comment]
Several options:
1. Concatenate the zstd compressed streams. The zstd library can find the size of the compressed frame by either using streaming decompression, or `ZSTD_findFrameCompressedSize()`. That way you can separate the uncompressed data.
2. As @PallHaraldsson mentions, just concatenate the uncompressed data. If you need to be able to separate it again, store the size of each uncompressed data in a header.

**Comment by applesthepi** [comment]
Thanks for all of your responses, I've solved my problem.
