### ISSUE TITLE
Multithreaded decompression

### ISSUE THREAD

**Issue by NMinhNguyen** [facebook/zstd#2470]
Hey, so I tried searching this repo to find out whether `zstd` supports multithreaded decompression, but was unable to find anything conclusive. I tried using terms like `-T0` / `multithread` / `multithreaded` alongside `decompress` / `decompression`. The reason why I'm unclear on this is because the description for `-T` uses the term `compress` but not sure if it also applies to decompression:

https://github.com/facebook/zstd/blob/7e6c53c7fe25e84d0a72224165403f4a786d43fa/programs/zstd.1.md#L115-L119

Perhaps if this is only limited to compression, the docs could be updated to indicate so?

**Comment by Cyan4973** [comment]
There is _currently_ no multithreading for decompression, only for compression.
This is due to a combination of being more difficult to do, and less critical, since decompression is already plenty fast with just a single thread (typically faster than ssd). 

This doesn't mean that it is impossible to do, but it will require care and available time to be achieved properly.

**Comment by NMinhNguyen** [comment]
Got it, thanks for the prompt reply! I'm happy for this issue to be closed then.

**Comment by Integral-Tech** [comment]
> There is _currently_ no multithreading for decompression, only for compression. This is due to a combination of being more difficult to do, and less critical, since decompression is already plenty fast with just a single thread (typically faster than ssd).
> 
> This doesn't mean that it is impossible to do, but it will require care and available time to be achieved properly.

@Cyan4973 Any plan to implement multi-threaded decompression in 2025?
Single-threaded decompression isn't typically faster than SSD in 2025 now, as PCIe 4.0 SSDs are increasingly prevalent (7000 MiB/s+ Read, 6000 MiB/s+ Write)
Several PCIe 5.0 consumer SSDs have released, which are even faster. Take Crucial T700 which was released in 2023 as an example, it has 12,400 MiB/s sequential read speed and 11,800 MiB/s sequential write speed.

**Comment by ScottRosenberg2** [comment]
> [@Cyan4973](https://github.com/Cyan4973) Any plan to implement multi-threaded decompression in 2025? Single-threaded decompression isn't typically faster than SSD in 2025 now, as PCIe 4.0 SSDs are increasingly prevalent (7000 MiB/s+ Read, 6000 MiB/s+ Write) Several PCIe 5.0 consumer SSDs have released, which are even faster. Take Crucial T700 which was released in 2023 as an example, it has 12,400 MiB/s sequential read speed and 11,800 MiB/s sequential write speed.

Given this, I'd like to also request this be reconsidered.
Preferably with the same env variable of ZSTD_NBTHREADS=0 so we can just default to using it, on an environmental basis.

**Comment by LeakorgX** [comment]
What about decompressing 500gb+ of data, it will not be fast please add multithreaded decomp
