### ISSUE TITLE
For a new PR, what kinds of test need I do?

### ISSUE THREAD

**Issue by zhangp8x** [facebook/zstd#2476]
HI, 

I see a lots of scripts in test folder. If I submit a new MR, what kinds of test should I do first? So that, the patch can not influence the zstd performance, functional features. And fit the zstd patch quality.

BRs.

**Comment by Cyan4973** [comment]
As a minimum, `make check`.
As a more thorough test, `make test`.

All these tests (and more) will be played automatically in CI when submitting a PR.

**Comment by zhangp8x** [comment]
@Cyan4973 

Thank you for your answer.

**Comment by yongchengmiao** [comment]
When submitting a PR , isn't the following script required to pass?
- function
> tests/playTests.sh
- performance
> python automated_benchmarking.py


What tests does CI mainly include?

**Comment by Cyan4973** [comment]
The CI test system is pretty complex, and I don't believe it's the right place to describe it.

If submitters run `make test` on their local system, it should go a long way to check the essentials.
It includes `playTests.sh`.

> What tests does CI mainly include?

Have a look at a recent PR, like for example [this one](https://github.com/facebook/zstd/pull/2475).
Click on `show all checks`, and a (fairly large) list of tests should appear.
You can then click on any single test if you want some more details.
`automated_benchmarking` is [there](https://github.com/facebook/zstd/pull/2475/checks?check_run_id=1723676862#step:3:4).

**Comment by yongchengmiao** [comment]
@Cyan4973

Thank you for your quick replay.

**Comment by cheng-long-neu** [comment]
How to determine the OK / ng of the log generated by make check whether contains the command or script for OK / ng of test results.
