### ISSUE TITLE
Add GitHub Actions to "Zstandard is used by" list

### ISSUE THREAD

**Issue by smorimoto** [facebook/zstd#2477]
It has been switched to use zstd for quite some time, but it's not listed yet. It's probably a good idea to put it on a list. Are there any assets that could be used for this? @dhadka

**Comment by Cyan4973** [comment]
We typically need a logo (github logo will do) and a public link towards the decision to use `zstd`

**Comment by felixhandte** [comment]
Looks like @smorimoto is talking about [this PR](https://github.com/actions/cache/pull/270)?

**Comment by smorimoto** [comment]
Yes, it is. It's still actually one of the things in progress (for native Windows support), but zstd is clearly saving a lot of computing resources on every build across the world at the moment, so I wanted to list it.

**Comment by Cyan4973** [comment]
Github Actions reference added

**Comment by smorimoto** [comment]
As fast as zstd! Thank you.
