### ISSUE TITLE
Dictionary compression savings and speed

### ISSUE THREAD

**Issue by nand28** [facebook/zstd#2478]
We have been trying to use zstd compression algorithm to compress 32KB data and this would mean decompressing the entire 32KB data to use any 4KB data in the range. So as an alternative, we are experimenting to use dictionary trained for this 32KB data which will be used to compress 4KB data independently. 

The savings obtained by this way is less than the savings seen without zstd  dictionary. We are trying these at default compression level of zstd. Following are the queries we have:
1. 32KB is less data for training a dictionary but given a data to train a dictionary and use it to compress the same data is giving comparitively less savings. Why is that?
2. How can we achieve similar saving with dictionary in this approach? 
3. The compression speed is very less compared to without dictionary usage, are there any optimized apis to train dictionary (we used ZDICT_optimizeTrainFromBuffer_fastCover, ZSTD_createCDict) and compress (we usedZSTD_compress_usingCDict) ?

**Comment by Cyan4973** [comment]
These are fairly advanced questions, and it's difficult to provide definitive answers to them, as so much depends on details.

That being said, here are some broad expectations : 

**32 KB vs 4 KB + dictionary :**
I don't expect 4 KB + dictionary to do better than 32 KB. At best, it will give comparable results, but even that is a stretch. 4 KB blocks are expected to result in lower compression ratios, even with a dictionary. Dictionary is a way to mitigate the loss from reducing block size. 

**Generating a dictionary every 32 KB block :** 
That's possible, but it's very intensive. You already use the right function to get the job done in a fast way (`fastCover`), but computing a new dictionary every 32 KB, that's definitely going to be felt cpu side.

Another point is that, while it works, such a method does not take advantage of some general data property expectations which, if they are not present, make dictionary a less adequate method.

To begin with, if there is a new dictionary every 32 KB, it needs to be stored, and therefore cost some space. This cost will counter-balance the savings produced by dictionary compression. The ratio `input_size / dictionary_size` is not high enough to make it negligible.

Rather, the way we prefer to use dictionary compression, is when there is a family of messages or records which are "similar". In a database, it's typically a column, which is supposed to store data of the same "kind".
In which case, a single dictionary is good enough for the _entire_ column. We only generate it once, per column, not per block.
(we also use more than one block to determine the "optimal" dictionary).
Such an approach saves time, and also storage cost for the dictionary, which improves savings, both storage and memory.

Now, this only works if data is "broadly similar" in a large category. If one cannot make such assumption, and data could be literally anything, thus justifying a more granular approach, then dictionary is not a great fit to begin with, and will not help much.

Anyway, as mentioned, this is a complex topic, and we can only provide general advises on an issue board.
Nonetheless, I hope it helps.

**Comment by nand28** [comment]
Thanks for the clarification.
