### ISSUE TITLE
Add a ZSTD_UNREACHABLE() macro for impossible code path

### ISSUE THREAD

**Issue by ghost** [facebook/zstd#2481]
Some code use `assert(0)` to indicate an impossible code path:

```c
    ...
    case ZSTD_btultra2:
        break;
    default:
        assert(0);  /* not possible : not a valid strategy id */
    }
```
Python has a [`Py_UNREACHABLE()`](https://docs.python.org/3/c-api/intro.html?#c.Py_UNREACHABLE) macro for this purpose, it also helps the compiler to optimize the code in release mode, please see the link.

Py_UNREACHABLE definition:
https://github.com/python/cpython/blob/v3.10.0a5/Include/pymacro.h#L103

It supports gcc/clang/msvc/icc, and raises an error in debug mode.

**Comment by terrelln** [comment]
We actually don't want to annotate these cases as unreachable. For example, this case could be reachable if the user passed in a bad `strategy` parameter. It is a user error, but it is not provably unreachable.

When a case like this happens, we are free to either ignore the problem, or return an error. But, the code must not crash in this case. None of these cases should be in performance sensitive code (hot loops), so better codegen in these cases shouldn't improve performance (but feel free to prove me wrong with a benchmark).

We could improve the clarity by creating helpers which just call `assert(0);` or `RETURN_ERROR()` underneath, depending on the scenario, but we don't want to crash in prod builds.

**Comment by ghost** [comment]
> but we don't want to crash in prod builds.

This worry is reasonable.

The doc said:
> If a code path is very unlikely code but can be reached under exceptional case, this macro must not be used.

Maybe it only save a compare instruction in release mode, very tiny performance improvement.

**Comment by terrelln** [comment]
> Maybe it only save a compare instruction in release mode, very tiny performance improvement.

All of the places where we have `switch` statements aren't inside the hot decoding loop. They only happen at most once per block (128 KB of input), so saving a few instructions won't meaningfully impact performance.

But again, if you have a real use case where annotating something as unreachable does meaningfully change performance, please let me know!

**Comment by ghost** [comment]
> if you have a real use case where annotating something as unreachable does meaningfully change performance, please let me know!

I have a problem unrelated to unreachable code these days.

This is a decompress speed test:
https://github.com/animalize/decompress
(usage: change `const char* PATH = "e:\\txt.zst";` to a compressed file path in decompress.cpp)

MSVC 2019 has a `/Ob3` option that provides more aggressive inlining:
https://docs.microsoft.com/en-us/cpp/build/reference/ob-inline-function-expansion
Just add `/Ob3`, it speeds up from 1.227 sec to 1.143 sec, ~6% faster.

It seems ~99% of the time is spent in `ZSTD_decompressSequences_body()` function.
https://github.com/facebook/zstd/blob/v1.4.8/lib/decompress/zstd_decompress_block.c#L1103

I compared two builds' assembly code, and try to inline functions by hand.
But can't reach the speed of `/Ob3` build, the speed is not much improved, it's very strange.

**Comment by ghost** [comment]
This patch add time stamp to `DEBUGLOG` macro.
```diff
 lib/common/debug.h     | 23 +++++++++++++++++++++++
 lib/common/zstd_deps.h |  2 +-
 2 files changed, 24 insertions(+), 1 deletion(-)

diff --git a/lib/common/debug.h b/lib/common/debug.h
index 8b57343..84719ff 100644
--- a/lib/common/debug.h
+++ b/lib/common/debug.h
@@ -66,6 +66,28 @@ extern "C" {
  * by modifying g_debug_level.
  */
 
+#include <stdint.h>
+#if defined(_MSC_VER)
+    #undef ERROR
+    #include "Windows.h"
+    static inline uint64_t GetTimeStamp()
+    {
+        long long t;
+        QueryPerformanceCounter((LARGE_INTEGER*)&t);
+        return t;
+    }
+    #define ERROR(name) ZSTD_ERROR(name)
+    static const char print64pattern[] = "<%I64u>";
+#else
+    #include <sys/time.h>
+    static inline uint64_t GetTimeStamp() {
+        struct timeval tv;
+        gettimeofday(&tv, 0);
+        return tv.tv_sec*(uint64_t)1000000+tv.tv_usec;
+    }
+    static const char print64pattern[] = "<%lld>";
+#endif
+
 #if (DEBUGLEVEL>=1)
 #  define ZSTD_DEPS_NEED_ASSERT
 #  include "zstd_deps.h"
@@ -91,6 +113,7 @@ extern int g_debuglevel; /* the variable is only declared,
             }   }
 #  define DEBUGLOG(l, ...) {                                     \
                 if (l<=g_debuglevel) {                           \
+                    printf(print64pattern, GetTimeStamp());      \
                     ZSTD_DEBUG_PRINT(__FILE__ ": " __VA_ARGS__); \
                     ZSTD_DEBUG_PRINT(" \n");                     \
             }   }
diff --git a/lib/common/zstd_deps.h b/lib/common/zstd_deps.h
index 0fb8b78..5583249 100644
--- a/lib/common/zstd_deps.h
+++ b/lib/common/zstd_deps.h
@@ -92,7 +92,7 @@
 #define ZSTD_DEPS_IO
 
 #include <stdio.h>
-#define ZSTD_DEBUG_PRINT(...) fprintf(stderr, __VA_ARGS__)
+#define ZSTD_DEBUG_PRINT(...) fprintf(stdout, __VA_ARGS__)
 
 #endif /* ZSTD_DEPS_IO */
 #endif /* ZSTD_DEPS_NEED_IO */
```
This script counts the time between each DEBUGLOG and the previous DEBUGLOG, and accumulates them to show hot functions.
```python
import sys,re

with open(sys.argv[1]) as f:
    text = f.read()
    
pattern = r'(?m)^<(\d+)>([^\d\n]+)'

d = {}
last_time = 0
for m in re.finditer(pattern, text):
    if last_time == 0:
        time = 0
        last_time = int(m.group(1))
    else:
        temp = last_time
        last_time = int(m.group(1))
        time = last_time - temp
    name = m.group(2)

    if name not in d:
        d[name] = time
    else:
        d[name] += time

d=sorted(d.items(), key=lambda x:x[1])
for k, v in d:
    print(v, k)
```

**Comment by ghost** [comment]
Close this issue.
