### ISSUE TITLE
gh-pages: update tarantool's branch name

### ISSUE THREAD

**Issue by Totktonada** [facebook/zstd#2484]
The [page](https://github.com/facebook/zstd/blob/a1af7dd0885e6c275869c3f13d511c693a0388a0/index.html#L276) points to the `1.8` branch, which does not exist anymore (the URL gives `404 Not found`). Now we use `master` branch for development.

**Comment by Cyan4973** [comment]
Thanks for pointing that out. Should be fixed now.
