### ISSUE TITLE
self-tests: stat on NetBSD has no '-c'

### ISSUE THREAD

**Issue by 0-wiz-0** [facebook/zstd#2493]
**Describe the bug**
When running the self tests for zstd-1.4.8 on NetBSD, I see an error running `stat`:
````
stat: unknown option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
````
**To Reproduce**
Build and install zstd on NetBSD, run the self tests.

**Expected behavior**
Successful self test without this error.

**Desktop (please complete the following information):**
 - OS: NetBSD
 - Version 9.99.80
 - Compiler gcc
 - Build system: Makefile

**Comment by felixhandte** [comment]
Hi @0-wiz-0,

I've put up a proposed fix for this issue. I believe it should fix the problem, but I myself don't have a NetBSD system to test on. Perhaps you could try this and let us know that this works?

**Comment by 0-wiz-0** [comment]
The referenced commit improves the situation on NetBSD, thanks!
