### ISSUE TITLE
OK / ng log

### ISSUE THREAD

**Issue by cheng-long-neu** [facebook/zstd#2511]
How to determine the OK / ng of the log generated by make check whether contains the command or script for OK / ng of test results.

**Comment by cheng-long-neu** [comment]
How to determine the OK / ng of the log generated by make check? whether contains the command or script for OK / ng of test results?

**Comment by felixhandte** [comment]
If I understand your question correctly, you are asking how to tell whether `make check` succeeds or fails. The best way to tell is to inspect the return code. When it has succeeded, it will return 0. When it has failed, it will return a non-zero code. You can access the return code like so:

```
make check
echo $?
```

**Comment by cheng-long-neu** [comment]
Thank you @felixhandte
