### ISSUE TITLE
1.4.9 Win64 release is corrupted

### ISSUE THREAD

**Issue by JoeUX** [facebook/zstd#2526]
**Describe the bug**

The 1.4.9 Win64 binaries are corrupted. As usual, they come in a ZIP file. Unzipping that file yields a single binary blob of indeterminate nature, rather than the intended contents, folders, zstd.exe, etc.

The blob is called `zstd-v1.4.9-win64`, which is the name of the ZIP file but without the .zip extension. Windows believes that this blob is a file, not a folder, and is interpreting `.9-win64` as its file extension. (Note that the blob is only 3 KiB larger than the ZIP file, a difference of 0.2% – the unzipped releases are usually more than twice the size of the ZIP.)

The ZIP release is here: https://github.com/facebook/zstd/releases/download/v1.4.9/zstd-v1.4.9-win64.zip

To see a non-corrupted release, open the Win32 version here: https://github.com/facebook/zstd/releases/download/v1.4.9/zstd-v1.4.9-win32.zip

I tried unzipping with both Windows 10's built-in ZIP support and with the 7-Zip client. Same results in both cases.

**Screenshots and charts**

Here's what I see. Bottom row is the entity. Note the date says March 3, but it was unzipped today – that's just when it was built:

![Zstd release bug](https://user-images.githubusercontent.com/8071692/110219527-966d8c80-7e74-11eb-940d-e2643a97884b.JPG)

**Desktop:**

 - OS: Windows 10 Pro 64-bit
 - Version: 20H2, build 19042.844 (latest)
 - Other relevant hardware specs: Intel Skylake Quad-Core

**Comment by ghost** [comment]
`zstd-v1.4.9-win64` is a ZIP file, if add `.zip` extension name, it can be opened with Windows 10's explorer and 7-Zip client.

**Comment by felixhandte** [comment]
Hi @JoeUX,

Thanks for pointing this out! The last steps of building the windows artifacts are still a manual process, so I must have fat-fingered something. My bad.

I've replaced the zip file with a corrected one.
