### ISSUE TITLE
Question: Final Bit clarification

### ISSUE THREAD

**Issue by PSeitz** [facebook/zstd#2527]
Regarding the final bit in huffman coded stream, it's not clear in the example to me how it is detected.
Does the final bit cause the padding to be `00001`?
Does the decoding table, to find the actual number of bits to skip, include final bit detection by covering maxBits+1? 
Otherwise `00001` could be read as `0001` = Symbol 4

https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md#huffman-coded-streams

**Comment by Cyan4973** [comment]
The header tells the decoder where is the final byte of the Huffman stream.
This final byte includes the final bit, so it cannot be `0`.

The final bit is the highest bit set of the final byte.
This bit is consumed, before starting decoding proper.

**Comment by PSeitz** [comment]
Thanks for the clarification, if I understood correctly, the bits in the example `0001_0000 00001_1_01` do not include the final bit. The padding is the last bits written in the useful stream and used to tell the decoder the bit offset to start reading in reverse order.
