### ISSUE TITLE
[Windows] Why release folder structure was changed in zstd 1.4.9?

### ISSUE THREAD

**Issue by al-cheb** [facebook/zstd#2532]
Before 1.4.9 release folder structure for Windows doesn't contain parent folder:
![image](https://user-images.githubusercontent.com/47745270/110796510-15096600-8289-11eb-8c91-a43524261161.png)

Since 1.4.9 release contains parent folder:
![image](https://user-images.githubusercontent.com/47745270/110796591-2e121700-8289-11eb-8e1d-f94539c0fb34.png)

Could you please update release pipeline to remove nested folder?

**Comment by g0blin-NN** [comment]
but it was generally creepy
https://github.com/facebook/zstd/issues/2526

**Comment by al-cheb** [comment]
cc @felixhandte

**Comment by g0blin-NN** [comment]
так как Вы из России скажу на нашем. было хуже. сейчас папка в архиве, а был zip-архив без расширения. просто наспех поправили. не такая уж это огромная беда и не баг вовсе. специально для Вас [zstd-v1.4.9-win64.zip](https://github.com/facebook/zstd/files/6128462/zstd-v1.4.9-win64.zip) все по феншую.

**Comment by al-cheb** [comment]
> так как Вы из России скажу на нашем. было хуже. сейчас папка в архиве, а был zip-архив без расширения. просто наспех поправили. не такая уж это огромная беда и не баг вовсе. специально для Вас [zstd-v1.4.9-win64.zip](https://github.com/facebook/zstd/files/6128462/zstd-v1.4.9-win64.zip) все по феншую.

Thank you for providing the repackaged version. I think it should be fixed by the repo maintainers to not broke a CI with different folder structure.

**Comment by felixhandte** [comment]
Hey all,

Apologies for this. I come from unix where it's a pretty strong convention to make all archives wrap all their contents in a single folder with the same name as the archive. This makes the archive unpack very cleanly and predictably, without spewing files all over the place.

For compatibility, I've changed the zips on the release back to the old pattern. However, I think we will probably make this change, to this new pattern, for the next breaking release (v1.5.0). (And we'll make sure to announce the change then.)

Does that make sense? Would that be a problem?

Thanks.

**Comment by al-cheb** [comment]
@felixhandte,
Thank you for mentioned about the next  breaking changes. We will update our pipeline CI to support to the new patter structure. It definitely can break some 3-rd party package management providers, for e.g. chocolatey - https://chocolatey.org/packages/zstandard

**Comment by maki-chan** [comment]
Yes, and changing it after the release did break the already released chocolatey package which wasn't great either 😉 

It should be possible to adapt to a new folder structure in the ZIP files without huge problems. I don't think there are even changes needed for chocolatey at least, only the usual checksum and URL update.
