### ISSUE TITLE
partial decompression of fully compressed image

### ISSUE THREAD

**Issue by sbapuram** [facebook/zstd#2543]
Hi,

our requirement is compress the full image, split the compressed image into lets say 100m and then decompress the splitted chunks before writing into destination file.

can you please confirm whether it works?

tried the below steps, but there is an error while decoding the splitted compressed images

1. ./zstd -3 dummy.ext4
2. dd if=dummy.ext4.zst | split -b 100m - dummy.ext4.zst
 dummy.ext4
 dummy.ext4.zst
 dummy.ext4.zstaa
 dummy.ext4.zstab
3../zstd -d dummy.ext4.zstaa -o dummy.ext4.aa
dummy.ext4.zstaa     : 273 MB...     dummy.ext4.zstaa : Read error (39) : premature end
4../zstd -d dummy.ext4.zstab -o dummy.ext4.ab
zstd: dummy.ext4.zstab: unsupported format

Thanks,
Saritha

**Comment by felixhandte** [comment]
Hi @sbapuram,

No, I'm afraid this is not a supported use case. If you want to split an object into independently decompressible chunks, they must be compressed independently. So you should split first and then compress each split chunk.

**Comment by Cyan4973** [comment]
Alternatively, if all you want is to regenerate the full image from multiple chunks, you could _stream_ the chunks _**in order**_ to the decompressor : 
```
cat $(ls dummy.ext4.zst* | sort) | zstd -d -o dummy.ext4
```

Note that it doesn't allow decompressing chunks in parallel nor in random order. @felixhandte 's suggestion, split first then compress, would better fit such requirement.

**Comment by sbapuram** [comment]
Thank you both for the quick reply.

our main intention is to compress the full image with zstd utility and decompress the partial image using API's, is that possible.
definitely, we cannot combine the full image for decompression.

**Comment by sbapuram** [comment]
Can you please share sample programs for streamed data decompression

**Comment by Cyan4973** [comment]
https://github.com/facebook/zstd/blob/dev/examples/streaming_decompression.c
