### ISSUE TITLE
ZSTD_decodeSequence: Coverity recommends to initialize structure to 0

### ISSUE THREAD

**Issue by paulmenzel** [facebook/zstd#2545]
In [commit 2777cf4466 (zstd: Initialize seq_t structure fully)](https://git.savannah.gnu.org/cgit/grub.git/commit/?id=2777cf4466719921dbe4b30af358a75e7d76f217) GRUB, using Zstandard 1.3.8 from 2018, changed the current Zstandard code below

https://github.com/facebook/zstd/blob/eace4abc2559eabb9300b9ca7e6769f620f0446e/lib/decompress/zstd_decompress_block.c#L941-L954

because Coverity recommended it.

    -    seq_t seq;
    +    seq_t seq = {0};

**Comment by Cyan4973** [comment]
Thanks for the feedback.

It's a case where the static analyzer isn't able to determine that the return value is correctly filled on return. As a consequence, it would like some initialization to happen up-front "just in case". But it is not beneficial in this case. 

`seq` is correctly initialized on `return`, as the function flow ensures all 3 compulsory members are necessarily filled.

**Comment by paulmenzel** [comment]
Thank you for the analysis.

[Darren replied](https://lists.gnu.org/archive/html/grub-devel/2021-03/msg00248.html):

> I can't honestly remember the details that Coverity had, but there was a
> flow found by Coverity that did end up returning the value in seq
> without touching all of the fields in the structure.
>
> Looking through the code manually just now, I can see that seq.match is
> never set during that code in ZSTD_decodeSequence(), so that is the most
> likely cause of the error from Coverity.
>
> All that it can do is report that it was not set before returning, it
> cannot necessarily predict what will happen after that function returns
> it, especially over time.

**Comment by Cyan4973** [comment]
Yes, that was my suspicion too.
The field `match` is optional, and only filled when needed afterwards (condition tracked by an `enum` parameter).
So that's a 2-functions relation which is too hard to track for a static analyzer.

**Comment by felixhandte** [comment]
I believe this is resolved.
