### ISSUE TITLE
zstd does not accept a block device as input

### ISSUE THREAD

**Issue by kogorman** [facebook/zstd#2552]
I wanted a complete copy of a hard drive before I tried to fix a problem on it, which may or may not have had to do with any recognizable file.   Zstd refused because it wasn't a "regurlar file".  Of course it wasn't.  So I had to pipe input through dd first.  Not a big issue, but an annoyance.

Running with -8 -T0 on a core i7 it squashed down to 13% taking jsut over an hour working on a 2TB SSD so yippee for that!!

**Comment by felixhandte** [comment]
This will be fixed in the 1.5.0 release. Thanks for the report!
