### ISSUE TITLE
Can add recovery record algorithm？

### ISSUE THREAD

**Issue by h45251880** [facebook/zstd#2563]
I think adding the recovery record will help the integrity of the file.
Ex. rr3% of winrar.
Can refer to Snapshot

**Comment by Cyan4973** [comment]
Not the correct layer.

`zstd` is a raw compression algorithm, like `gzip` or `lz4`,
not an archiver like `winrar`, nor a backup solution.

It's designed to be _integrated_ within other applications, _including_ archivers and backup servers,
where it can be combined with other functionalities, such as recovery records or error correction layers.
