### ISSUE TITLE
--patch-from last in the race

### ISSUE THREAD

**Issue by sergeevabc** [facebook/zstd#2576]
Windows 7, zstd 1.4.9, hdiffz 3.1.1, jdiff 0.8.5, xdelta 3.1.0

Source: [binaries.7z][1] <sup>SHA256: 2c1c8b1c4093e071de64b2dd9aebf7a1003712e39c0e5473c04a17ae781f81f5</sup>

``` console
$ zstd -19 --patch-from binary.old binary.new -o patch.zdiff
$ hdiffz -c-zlib-9  binary.old binary.new patch.hdiff
$ jdiff -jb binary.old binary.new patch.jdiff
$ xdelta -e -9 -s binary.old binary.new patch.xdelta
```
Computation speed is about the same, but patch size… 

``` console
$ stat -c "%s %n" patch.* | sort -n | column -t
72    patch.jdiff    
100   patch.hdiff    
247   patch.xdelta   
1952  patch.zdiff     
```

[1]: https://download.ru/files/y8IoES6N

**Comment by Cyan4973** [comment]
There's a fundamental format limitation in `zstd`
which makes it impossible to reach a ratio below ~100 bytes by MB.

It appears this is approximately what happens here,
with an input in the ~20 MB, I would expect the minimum patch size to be ~2 KB.

In scenarios where the input is large, but the amount of changes is very small,
`zstd` format can't avoid the 0.01% tax of the underlying format limitation,
so it starts at a disadvantage (compared to more dedicated tools and format).

Obviously, it the amount of changes is closer to the 1% mark, or larger,
this "tax" becomes proportionally insignificant
making `zstd` more competitive.
