### ISSUE TITLE
`--no-content-size` bails out with `Incomplete read`

### ISSUE THREAD

**Issue by Hi-Angel** [facebook/zstd#2578]
**Describe the bug**

As a solution to https://github.com/facebook/zstd/issues/1926 a new option `--no-content-size` was added. The usecase is compressing log files while they're being appended *(so the file size might increase during the compression)*.

Unfortunately, even if option is provided, `zstd` still prints an error "Incomplete read", and then quits with exit code `27`. So the option doesn't seem to work.

**To Reproduce *(in terms of terminal commands)***

```
 λ truncate -s 2G testfile
 λ ping localhost >> testfile &
[1] 125399
 λ zstd -18 --no-content-size testfile
Read : 1955 / 2048 MB ==>  0%zstd: error 27 : Read error : Incomplete read : 2147483946 / 2147483883 B
 λ echo $?
27
```

**Expected behavior**

Exit code is `0`

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Version: 1.4.9

**Comment by Hi-Angel** [comment]
FTR: the [PR that added the option](https://github.com/facebook/zstd/pull/2032) has a different usage example. So I tried that out too, to no avail:

```
 λ zstd --compress --no-content-size --stdout testfile > testfile.zst
zstd: error 27 : Read error : Incomplete read : 2147561899 / 2147561835 B 
```

**Comment by Cyan4973** [comment]
As a temporary workaround,
would that work to pipe the file _into_ `zstd` ?
```
cat testfile | zstd > testfile.zst
```

**Comment by Hi-Angel** [comment]
> As a temporary workaround,
> would that work to pipe the file _into_ `zstd` ?
> 
> ```
> cat testfile | zstd > testfile.zst
> ```

Thank you, yes, I've seen a similar workaround in the original bugreport, and ended up using it for now.

**Comment by terrelln** [comment]
I don't think that it is possible to support compressing a file that is actively being written, or is something we want to support. It would work if `testfile` was a FIFO pipe (I believe we support FIFO pipes, but I may be mistaken).

**Comment by Hi-Angel** [comment]
> I don't think that it is possible to support compressing a file that is actively being written, or is something we want to support. It would work if `testfile` was a FIFO pipe (I believe we support FIFO pipes, but I may be mistaken).

But then, what is the point of `--no-content-size` option?

**Comment by terrelln** [comment]
> But then, what is the point of --no-content-size option?

It doesn't write the content size into the compressed frame. It could be useful if you don't want to pay the 1-8 byte cost of writing the content size in the frame. It is also just a way to escape from the default behavior. But the default of writing the content size into the frame is the default for a good reason, it is almost always a good thing to do.

Your example is a race condition. If `ping` is slow, zstd might finish executing before `ping` writes any data into `testfile`. Or it might only see half the data that `ping` produces before finishing.

**Comment by Cyan4973** [comment]
After a bit more thinking,
I believe that piping the growing input into `zstd` is more than a work-around,
it's the right thing to do.
Everything lines up pretty well between the properties and expectations of a pipe input, and your scenario (appending more data into input while compressing it).

In contrast, using the `FILE` interface embeds some expectation, such as querying its size, with follow-up consequences (size is not expected to change after initial  query). 
Consequently, it would be unwise and risky to carve out a "special" path on the `FILE` interface, weighting code complexity and associated maintenance costs, for a use case which is already fully supported by the pipe interface.

**Comment by Hi-Angel** [comment]
Alright, you're the maintainers. Though, if I could give a suggestion: I think it would be useful to not advice using this syntax `zstd > testfile.zst` in preference of this one `zstd -o testfile.zst`. The difference is that when `-o` is used, zstd will show a progress-bar as it compresses, so a user will know the command haven't stuck or something, and how much it compressed already.
