### ISSUE TITLE
UB in ZSTD_decompressSequences_body when error-valued onSeqSize is added to op

### ISSUE THREAD

**Issue by acmorrow** [facebook/zstd#2590]
**Describe the bug**
MongoDB bundles zstd and we recently attempted to upgrade from `v1.4.4` to the latest stable, `v1.4.9`. After doing so, one of our unit tests started failing in our CI UBSAN runs. After some digging, it appears that this line in `zstd_decompress_block.cpp` may be misplaced (see https://github.com/facebook/zstd/blob/333dd60bffc5811cfdfe436e60d36712d9a869a9/lib/decompress/zstd_decompress_block.c#L1191):

```
            op += oneSeqSize;
```

because it occurs before the check for whether the value held in `oneSeqSize` is actually an error. In the event that it is, the error code value is added to `op`, which points into the user-provided destination buffer. UBSAN complains as follows:

```
cpp_unit_test:transport_test] src/third_party/zstandard/zstd/lib/decompress/zstd_decompress_block.c:1191:16: runtime error: addition of unsigned offset to 0x7ffcc359dfb0 overflowed to 0x7ffcc359df6a
[cpp_unit_test:transport_test]     #0 0x7f9a27d00316 in ZSTD_decompressSequences_body /data/mci/7d4d745948a0b867bc54675364c8286b/src/src/third_party/zstandard/zstd/lib/decompress/zstd_decompress_block.c
[cpp_unit_test:transport_test]     #1 0x7f9a27d00316 in ZSTD_decompressSequences_bmi2 /data/mci/7d4d745948a0b867bc54675364c8286b/src/src/third_party/zstandard/zstd/lib/decompress/zstd_decompress_block.c:1352
[cpp_unit_test:transport_test]     #2 0x7f9a27cf06d0 in ZSTD_decompressSequences /data/mci/7d4d745948a0b867bc54675364c8286b/src/src/third_party/zstandard/zstd/lib/decompress/zstd_decompress_block.c:1387:16
[cpp_unit_test:transport_test]     #3 0x7f9a27cf06d0 in ZSTD_decompressBlock_internal /data/mci/7d4d745948a0b867bc54675364c8286b/src/src/third_party/zstandard/zstd/lib/decompress/zstd_decompress_block.c:1514
[cpp_unit_test:transport_test]     #4 0x7f9a27ce1650 in ZSTD_decompressFrame /data/mci/7d4d745948a0b867bc54675364c8286b/src/src/third_party/zstandard/zstd/lib/decompress/zstd_decompress.c:862:27
[cpp_unit_test:transport_test]     #5 0x7f9a27ce1650 in ZSTD_decompressMultiFrame /data/mci/7d4d745948a0b867bc54675364c8286b/src/src/third_party/zstandard/zstd/lib/decompress/zstd_decompress.c:972
[cpp_unit_test:transport_test]     #6 0x7f9a27ce1fbf in ZSTD_decompress_usingDDict /data/mci/7d4d745948a0b867bc54675364c8286b/src/src/third_party/zstandard/zstd/lib/decompress/zstd_decompress.c:1484:12
[cpp_unit_test:transport_test]     #7 0x7f9a27ce1fbf in ZSTD_decompressDCtx /data/mci/7d4d745948a0b867bc54675364c8286b/src/src/third_party/zstandard/zstd/lib/decompress/zstd_decompress.c:1027
[cpp_unit_test:transport_test]     #8 0x7f9a27ce1fbf in ZSTD_decompress /data/mci/7d4d745948a0b867bc54675364c8286b/src/src/third_party/zstandard/zstd/lib/decompress/zstd_decompress.c:1037
```

At first I expected to find this to be signed integer overflow, but I'm not sure that it is. I think the issue that UBSAN is complaining about may be that this addition synthesizes a pointer outside the bounds of an array. In any event, moving the offending line until after it has been determined whether `oneSeqSize` contains an error code eliminates the UB report:

```
diff --git a/src/third_party/zstandard/zstd/lib/decompress/zstd_decompress_block.c b/src/third_party/zstandard/zstd/lib/decompress/zstd_decompress_block.c
index b71bc20d65b..59d19bdb5f1 100644
--- a/src/third_party/zstandard/zstd/lib/decompress/zstd_decompress_block.c
+++ b/src/third_party/zstandard/zstd/lib/decompress/zstd_decompress_block.c
@@ -1188,7 +1188,6 @@ ZSTD_decompressSequences_body( ZSTD_DCtx* dctx,
 #endif
             DEBUGLOG(6, "regenerated sequence size : %u", (U32)oneSeqSize);
             BIT_reloadDStream(&(seqState.DStream));
-            op += oneSeqSize;
             /* gcc and clang both don't like early returns in this loop.
              * Instead break and check for an error at the end of the loop.
              */
@@ -1196,6 +1195,8 @@ ZSTD_decompressSequences_body( ZSTD_DCtx* dctx,
                 error = oneSeqSize;
                 break;
             }
+            op += oneSeqSize;
+
             if (UNLIKELY(!--nbSeq)) break;
         }
```

If you agree with this analysis, I'm happy to put together a PR with that change.

**To Reproduce**
1. Checkout https://github.com/acmorrow/mongo/tree/SERVER-49230, cd into repo
2. make a python3 based virtualenv and activate it
3. Install the compile requirements in the virtualenv with `python -m pip install -r etc/pip/compile-requirements.txt`
4. Compile the unit test (may take a few minutes), with: `python ./buildscripts/scons.py CC=/path/to/clang-7-or-newer CXX=/path/to/clang++7-or-newer LLVM_SYMBOLIZER=/path/to/llvm-symbolizer --dbg=on --opt=on --allocator=system --sanitize=undefined,address --ssl --ocsp-stapling=off -j$(grep -c ^processor /proc/cpuinfo) --link-model=dynamic build/install/bin/transport_test`
5. Run the instrumented build with : `UBSAN_OPTIONS="print_stacktrace=1:external_symbolizer_path=/path/to/llvm-symbolizer" LSAN_OPTIONS="suppressions=etc/lsan.suppressions:report_objects=1" ASAN_OPTIONS="detect_leaks=1:check_initialization_order=true:strict_init_order=true:abort_on_error=1:disable_coredump=0:handle_abort=1:external_symbolizer_path=/opt/mongodbtoolchain/v3/bin/llvm-symbolizer" ./build/install/bin/transport_test`

The program should fail with a UBSAN report like the one above.

**Expected behavior**
The expected behavior is for the unit test to pass without UBSAN errors, but the observed behavior is the UBSAN report above.

**Desktop (please complete the following information):**
 - OS: Observed on Ubuntu 18.04 (MongoDB CI) and Ubuntu 20.04 (my desktop, while reproducing)
 - Version: v1.4.9
 - Flags: See above
 - Build system: MongoDB writes its own `SConscript` to compile `zstd`. You can find it in `src/third_party/zstandard/SConscript` after cloning the above repo.

**Comment by terrelln** [comment]
I will look into changing it to silence UBSAN. The only problem is that small differences in this loop can cause huge swings in performance.

However, note that in this case we are okay with the UB. When `oneSeqSize` is an error, and overflows the pointer, we don't use `op`. So the result of the addition doesn't matter.

**Comment by acmorrow** [comment]
> I will look into changing it to silence UBSAN. The only problem is that small differences in this loop can cause huge swings in performance.

Yes, understood. The code had that feeling when I was looking at the surrounding context.


> 
> However, note that in this case we are okay with the UB. When `oneSeqSize` is an error, and overflows the pointer, we don't use `op`. So the result of the addition doesn't matter.

Unfortunately, I'm not sure that argument works. The compiler is, for better or for worse, allowed to assume that UB does not happen, and is furthermore allowed to optimize based on that assumption. The fact that the results of the UB are unused doesn't matter, to the best of my understanding.

https://devblogs.microsoft.com/oldnewthing/20140627-00/?p=633

Obviously, if you decide not to address this, we will just add the necessary runtime suppressions or compile time exemption lists to hide the problem. But my recommendation is to simply swap the order of the statements, unless the performance consequences are truly severe. Even if current compilers don't do something awful here, future ones might, especially in a world more heavily imbued with constexpr, LTO, etc.

**Comment by BillyDonahue** [comment]
The UB is inside the `+=` operation that produced the overflowed pointer (per [expr.add](http://eel.is/c++draft/expr.add#4.3) ), not inside a dereference of the result (it's "undefined behavior" not "undefined result"). Any execution branch that can be proven to lead to such a condition can be omitted or assumed not to happen by an aggressive optimizer and there could be really subtle trouble.

**Comment by terrelln** [comment]
I understand that compilers can assume that UB doesn't happen, and I would definitely prefer to fix it if possible. This seems like it can be fixed, but it just has to be attempted. I will look into it before our next release.

Zstd does however rely on two pieces of UB:

1. Out of bounds pointers. E.g. pointers that don't point to valid memory. We only use them for pointer arithmetic, and don't dereference them, but this is still UB.
2. Pointer underflow wraps around.

Ideally, we wouldn't have any UB. But, these are pretty deeply baked into the library, and would be very hard to change. But, we're aware they are there, and would expect our runtime tests and fuzzers to check that the compiler isn't doing anything nasty.

**Comment by terrelln** [comment]
Unfortunately the proposed patch shows a 2.5% performance regression in gcc. However, that may just be noise that we can ignore. But, that means a more careful performance analysis is needed, and it isn't just an easy perf neutral fix.

**Comment by acmorrow** [comment]
@terrelln - 

Regarding the deliberate UB, I'd suggest then that perhaps `zstd` ought to ship an example UBSAN runtime suppression or a compile time denylist file that explicitly tags the known and deliberate instances of UB. Or if not that, at least explicitly comment those known and deliberate instances in the code with a standard pattern, so that when your users encounter such UB in the library, they can know that they are in the right to do their own work to suppress those instances in their instrumented builds. Without that, we are left guessing, even if FB knows that this UB is "safe" (and that still gives me real pause, because, safe with which compilers?).

On the performance side, that's unfortunate. I was hoping that it wouldn't matter. But, given that it does cause a slight regression, I can't disagree that further investigation is necessary.

For the moment, we are putting our efforts to upgrade to the latest stable zstd on pause, partially due to this issue but not exclusively. So it definitely isn't urgent, and, even it it became urgent, we could just write our own suppressions.

Hopefully future versions of C++ leave fewer and fewer of these UB corners.

**Comment by terrelln** [comment]
The exact UBSAN flags we use are `-fno-sanitize-recover=all -fsanitize-recover=pointer-overflow -fsanitize=undefined`.

> Or if not that, at least explicitly comment those known and deliberate instances in the code with a standard pattern, so that when your users encounter such UB in the library, they can know that they are in the right to do their own work to suppress those instances in their instrumented builds.

We can do that.

**Comment by acmorrow** [comment]
@terrelln - Thank you for the fix!
