### ISSUE TITLE
dev branch is ahead of master branch 

### ISSUE THREAD

**Issue by sbapuram** [facebook/zstd#2599]
Master branch is far behind than dev branch(approximately 254 commits), is there any plan on merging the latest commits into master

**Comment by Cyan4973** [comment]
`master` branch is no longer used (and will be removed in some future).
To access the content of latest release, pull the `release` branch (or alternatively the associated tag, such as `v1.4.9` currently).
The `release` branch will be updated at next release (planned to be `v1.5.0`).

**Comment by sbapuram** [comment]
Thanks, this helps
