### ISSUE TITLE
Building with MinGW fails when linking zstd CLI to zstd DLL

### ISSUE THREAD

**Issue by jdx-gh** [facebook/zstd#2631]
When I configure version 1.4.9 with `-DZSTD_PROGRAMS_LINK_SHARED=ON` added to CMake command line parameters, building fails:
```
[100%] Linking C executable zstd.exe
CMakeFiles/zstd.dir/objects.a(benchzstd.c.obj):benchzstd.c:(.text+0x16e0): undefined reference to `ZSTD_XXH64'
CMakeFiles/zstd.dir/objects.a(benchzstd.c.obj):benchzstd.c:(.text+0x2065): undefined reference to `ZSTD_XXH64'
collect2.exe: error: ld returned 1 exit status
programs/CMakeFiles/zstd.dir/build.make:224: recipe for target 'programs/zstd.exe' failed
make[2]: *** [programs/zstd.exe] Error 1
CMakeFiles/Makefile2:249: recipe for target 'programs/CMakeFiles/zstd.dir/all' failed
make[1]: *** [programs/CMakeFiles/zstd.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

Quick look at the sources proves that the error is justified because XXH related symbols are not exported – `XXH_PUBLIC_API` is defined as empty in `xxhash.h` and there is no code which could define it as `__declspec(dllexport)` (as it is for example with `ZSTDLIB_API` at the top of `zstd.h`).

**Comment by Cyan4973** [comment]
The `zstd` CLI should preferably not be linked to the dynamic library.
One issue is that it relies on unstable experimental symbols, which are tied to a specific version of the library.
If there is a mismatch between the CLI and the library versions, it could end badly.

On top of that, indeed, it depends on `xxhash`, which is not even part of unstable (it's internal to the library).

I recommend linking the CLI with the static library only.

**Comment by jdx-gh** [comment]
> On top of that, indeed, it depends on `xxhash`, which is not even part of unstable (it's internal to the library).

Yeah, `xxhash` seems to be (to me, a user, not a developer) internal to the library so its symbols should not be visible to CLI even if linking statically.

> I recommend linking the CLI with the static library only.

That's what I have been doing since I started to use zstd. However I have noticed a new feature mentioned in the changelog…
