### ISSUE TITLE
ARMv6 unaligned hack ends up in bus-error if running under a 64bit kernel

### ISSUE THREAD

**Issue by bugfinder** [facebook/zstd#2632]
the comment in the source code already points out that the unaligned access violates the C standard.
just for reference if you run this code with a 32bit userspace on a 64bit armv8/aarch64 kernel the unaligned access is no longer caught and handled by the kernel but leads directly to a bus error.
not sure if this could/should make it into the documentation somewhere

**Comment by bmwiedemann** [comment]
https://github.com/facebook/zstd/blob/v1.4.9/lib/common/mem.h#L139 to be precise with the special ARMV6 default of 2 below.

**Comment by bmwiedemann** [comment]
related http://fastcompression.blogspot.com/2015/08/accessing-unaligned-memory.html says
> Of course, a better solution would be for all compilers, and gcc specifically, to properly translate `memcpy()` into efficient assembly for all targets. But that's wishful thinking, clearly outside of our responsibility. Even if it does improve some day, we nonetheless need an efficient solution now, for current crop of compilers.
