### ISSUE TITLE
tar -Izstd and piping tar to zstd produces files incompatible with libzstd

### ISSUE THREAD

**Issue by DarjanKrijan** [facebook/zstd#2646]
**Bug description**
zstd compressed tar files with either ```tar -Izstd -cf data.tar.zst data``` or ```tar -cf - data | zstd > data.tar.zst``` make ```ZSTD_getFrameContentSize``` return ```ZSTD_CONTENTSIZE_UNKNOWN```.
Function returns expected value with split ```tar``` and ```zstd``` commands.
The ```zstd``` binary is able to decompress all the combinations above.

**Reproduce**
Rename and run attached k_libzstd.sh(.txt) that tests zstd and the k_libzstd.c(.txt) kernel with the above combinations.
Output attached as well.
[k_libzstd.sh.txt](https://github.com/facebook/zstd/files/6474540/k_libzstd.sh.txt)
[k_libzstd.c.txt](https://github.com/facebook/zstd/files/6474646/k_libzstd.c.txt)
[k_libzstd_log.txt](https://github.com/facebook/zstd/files/6474541/k_libzstd_log.txt)

**Expectation**
```ZSTD_getFrameContentSize``` should return decompressed size on these files.

**System/versions:**
Arch Linux, linux kernel 5.12.2
tar (GNU tar) 1.34
zstd v1.4.9

Edit: simplified k_libzstd.c a little.

**Comment by terrelln** [comment]
Zstd doesn't know the size of the stream, since it is being piped, so it can't write the frame content size in. If you want the frame content size to be present, you can do:

```
tar -cf data.tar data && zstd --rm data.tar
```

`libzstd` does not require the frame content size to be present, so this data is not incompatible with libzstd. The CLI is implemented using libzstd.

However, you are correct that `ZSTD_getFrameContentSize()` will return `ZSTD_CONTENTSIZE_UNKNOWN`. You could get around this in a few ways:
1. Use streaming decompression `ZSTD_decompressStream()`. This is the most efficient.
2. Pre-allocate a buffer you know will be large enough and use `ZSTD_decompressDCtx()`, or keep retrying with a growing buffer until it is large enough. This is less efficient, but will still work.

**Comment by DarjanKrijan** [comment]
Is this not a bug (or missing feature) of the zstd compressor then?
Eventually the pipe closes and zstd could write the content size/decompressed size into the zst file when finishing up?

Streaming decompression is fine if you want to just decompress files to disk, but I'd like to read a compressed zst file untouched to save disk space + network bandwidth and decompress to memory to analyze the data right away.
Compressed files could be 1GB+ large, and decompressed god knows what. It would be convenient to know the decompressed size in this case.

Anyway I'll for now make sure zstd/libzstd isn't stream compressing the files to make it compatible for my purpose.

Feel free to close this if it's a wontfix.

**Comment by terrelln** [comment]
> Is this not a bug (or missing feature) of the zstd compressor then?
> Eventually the pipe closes and zstd could write the content size/decompressed size into the zst file when finishing up?

Zstd writes its files in sequential order, so it has to finalize the frame header, including the frame content size, before the end of the file. It could theoretically work if zstd is writing to an output file, but if zstd is writing to stdout, there is nothing it could do.

So this is not a bug or a missing feature, it is zstd working as intended.

> Streaming decompression is fine if you want to just decompress files to disk, but I'd like to read a compressed zst file untouched to save disk space + network bandwidth and decompress to memory to analyze the data right away.

You can stream into memory using `libzstd` and `ZSTD_decompressStream()`.

**Comment by DarjanKrijan** [comment]
Right, I forgot the writing to stdout which is a one-way.

But even if I do ```tar -cf - file | zstd -o file.tar.zst```, ```zstd``` doesn't add the content size when it could seek back to the header and add it to finalize the file.
Or something that could hypothetically be added to a footer/end of the zst file in either way, just like ```Content_Checksum```...

I can't grasp how being in the dark about the decompressed size can be anywhere efficient/performant as it needs to constantly check if the (set by good guess) output buffer can hold the data, and if it can't it needs to ```fwrite``` to file/```fmemopen```(posix) or ```realloc``` syscall to resize the buffer and then call ```ZSTD_decompressStream``` again...

I know for large files it is the only option to stream if it can't fit to memory, but for my sort of use case it is lacking a bit if the files were to be "stream compressed" and there's no intel on the decompressed size.

**Comment by DarjanKrijan** [comment]
I ended up implementing it in two ways, depending if the size is known or not.
In the unknown case I malloc/realloc in 100MiB steps and shrink(realloc) it to the actual decompressed size after completion.
Lots of lines of code imo for something that could be simplified if size was written to the end of stream...

Closing this here.
