### ISSUE TITLE
broken 1.5.0 release artifact tarballs

### ISSUE THREAD

**Issue by anthraxx** [facebook/zstd#2652]
The dedicated release artifacts are wrongly created, it seems the `git archive` command has a wrong `--prefix` command without a tailing slash. This leads to prefixes being applied to filenames instead of prefixing it with a directory:

https://github.com/facebook/zstd/releases/download/v1.5.0/zstd-1.5.0.tar.gz
https://github.com/facebook/zstd/releases/download/v1.5.0/zstd-1.5.0.tar.zst

bsdtar tf zstd-1.5.0.tar.gz
```
zstd-1.5.0.buckconfig
zstd-1.5.0.buckversion
zstd-1.5.0.circleci/
zstd-1.5.0.circleci/config.yml
zstd-1.5.0.circleci/images/
zstd-1.5.0.circleci/images/primary/
zstd-1.5.0.circleci/images/primary/Dockerfile
zstd-1.5.0.cirrus.yml
zstd-1.5.0.gitattributes
zstd-1.5.0.github/
....
```

**Comment by senhuang42** [comment]
Yep, this has been fixed as of now. The release is still in "pre-release" state, so once we set it to "release" everything should be good to go.

**Comment by anthraxx** [comment]
I guess the github workflow action kicks in? As I've checked that file and it seems to be right plus I didn't see that action being run yet :cat:

**Comment by felixhandte** [comment]
The action failed to run, for reasons we don't understand. So we prepped the artifacts manually for this release.

**Comment by anthraxx** [comment]
one last question, where do I find public RSA key 4EF4AC63455FC9F4545D9B7DEF8FE99528B52FFD

**Comment by felixhandte** [comment]
[Here](http://zstd.net/signing-key.asc) or [here](http://keys.gnupg.net/pks/lookup?op=get&search=0xEF8FE99528B52FFD).

**Comment by anthraxx** [comment]
@felixhandte ah thats, looks like SKS infra hasn't propagated it fully yet. I've used a magical script and published the public key on a lot of servers to speed up the sync :cat: 

- [x] Artifact directory prefix fixed
- [x] GPG signing key available
- [x] Signature verified for new artifact

thx for the quick replies, looking forward to the final non pre release

**Comment by anthraxx** [comment]
hey folks, I'm slightly confused now. Is 1.5.0 no pre-release anymore?
https://github.com/facebook/zstd/releases/tag/v1.5.0

According to the github page the `pre-release` marker is gone

**Comment by senhuang42** [comment]
Yep, we've moved it to `release`.
