### ISSUE TITLE
Now RFC 8478 obsoleted by RFC 8878

### ISSUE THREAD

**Issue by data-man** [facebook/zstd#2656]
Since February 2021 according to [datatracker.ietf.org](https://datatracker.ietf.org/doc/html/rfc8878).

**Comment by Cyan4973** [comment]
That's correct.

Differences are fairly minor though, mostly rewording sentences and examples for better clarity,
and a fix for a pretty deep implementation detail.

These small details only matter for implementers, but there are a few now. Hence the update.
