### ISSUE TITLE
can't build zstd 1.5.0 with cmake after deletion of  "lib/common/zstd_trace.c"

### ISSUE THREAD

**Issue by openmax** [facebook/zstd#2658]
This commit : 
https://github.com/facebook/zstd/commit/6cee3c2c4f031125f487d2aa09c878e52a18fd4e
prevent build with cmake , missing symbol from deleted  ->" lib/common/zstd_trace.c "
ld: 0711-317 ERROR: Undefined symbol: ZSTD_trace_compress_begin
ld: 0711-317 ERROR: Undefined symbol: .ZSTD_trace_compress_begin
ld: 0711-317 ERROR: Undefined symbol: ZSTD_trace_compress_end
ld: 0711-317 ERROR: Undefined symbol: .ZSTD_trace_compress_end
ld: 0711-317 ERROR: Undefined symbol: ZSTD_trace_decompress_end
ld: 0711-317 ERROR: Undefined symbol: .ZSTD_trace_decompress_end
ld: 0711-317 ERROR: Undefined symbol: ZSTD_trace_decompress_begin
ld: 0711-317 ERROR: Undefined symbol: .ZSTD_trace_decompress_begin

**To Reproduce**
Build with cmake

**Expected behavior**
correct include o missing symbol.

**Comment by gvollant** [comment]
To compile with GCC-8 on IBM AIX (powerpc processor), I added this compiler option:
```
-DZSTD_HAVE_WEAK_SYMBOLS=0
```

**Comment by openmax** [comment]
i'm on OS400 7.3 Pase Environment ( is like aix 7.2 )   with gcc6.3 e cmake 3.16 , i got : 

CMake Warning:
  Manually-specified variables were not used by the project:

    ZSTD_HAVE_WEAK_SYMBOLS

so no luck ...

**Comment by openmax** [comment]
i suggest to modify lib/common/zstd_trace.h adding AIX exclude : 

`/* weak symbol support */
#if !defined(ZSTD_HAVE_WEAK_SYMBOLS) && defined(__GNUC__) && \
    !defined(__APPLE__) && !defined(_WIN32) && !defined(__MINGW32__) && \
    !defined(__CYGWIN__) && !defined(_AIX)
#  define ZSTD_HAVE_WEAK_SYMBOLS 1
#else
#  define ZSTD_HAVE_WEAK_SYMBOLS 0
`#endif``

**Comment by gvollant** [comment]
I suggest don't define automatically ZSTD_HAVE_WEAK_SYMBOLS  on any platform

**Comment by terrelln** [comment]
@gvollant and @openmax please let me know if PR #2674 fixes your issues.
