### ISSUE TITLE
Different compression between ZSTD_compressCCtx and ZSTD_compress2

### ISSUE THREAD

**Issue by oleg-st** [facebook/zstd#2671]
**Describe the bug**
The compressed data is different when using ZSTD_compressCCtx  and ZSTD_compress2 + ZSTD_CCtx_setParameter

**To Reproduce**

Tested on `dickens` file from the Silesia compression corpus, compression levels >= 16.

1) 
```c
ZSTD_CCtx* cctx = ZSTD_createCCtx();
size_t compressedLength = ZSTD_compressCCtx(cctx, dstPtr, destLength, srcPtr, srcLength, 16);
printf("size %d\n", (int)compressedLength);
```

Ouputs:
```
size 2925106
```

2) 
```c
ZSTD_CCtx* cctx = ZSTD_createCCtx();
ZSTD_CCtx_setParameter(cctx, ZSTD_c_compressionLevel, 16);
size_t compressedLength = ZSTD_compress2(cctx, dstPtr, destLength, srcPtr, srcLength);
printf("size %d\n", (int)compressedLength);
```

Ouputs:
```
size 2924808
```

**Expected behavior**
I think in both cases the result should be the same.
Is this a bug or is it working as intended?

**Desktop (please complete the following information):**
 - OS: Win64
 - Version 1.5.0
 - Compiler MSVC
 - Flags Release build
 - Build system Visual Studio

**Comment by terrelln** [comment]
This is working as intended.

We enable some extra options in `ZSTD_compress2()` when we detect that they won't hurt compression speed, and will bring a benefit to compression ratio. Generally for the optimal parser, levels 16+. For larger inputs we will enable long range mode, and we will always enable block splitting for the optimal parser.

For now, we haven't added them to `ZSTD_compressCCtx()`, but we may in the future.

Given the same {API, parameters, library version} zstd guarantees determinism. But, if you change any of those, zstd reserves the right to produce different compressed output (but still compatible with all zstd decoders).

**Comment by oleg-st** [comment]
Thank you for the clarification.
