### ISSUE TITLE
Generic error returned but only in 32 bits and only in the 1.5.0 release

### ISSUE THREAD

**Issue by Ben136KBC** [facebook/zstd#2690]
Compiling using Visual C++ 2019 version 16.9.6. using these flags:

CCOPTION = $(CCOPTION) -DZSTD_DLL_EXPORT=1
CCOPTION = $(CCOPTION) -DZSTD_MULTITHREAD=1
CCOPTION = $(CCOPTION) -DZSTD_LEGACY_SUPPORT=5
CCOPTION = $(CCOPTION) -DWIN32
CCOPTION = $(CCOPTION) -DNDEBUG
CCOPTION = $(CCOPTION) -D_CONSOLE
CCOPTION = $(CCOPTION) -D_CRT_SECURE_NO_WARNINGS

Calling ZSTD_compressCCtx (zstd_cctx, dest, destSize, source, size, compressLevel)

destSize = 16843776
size = 5956110
compressLevel = 1

and it returns ZSTD_error_GENERIC. If fails on the first compress call, which is the first call into the DLL other than creating two contexts. zstd_cctx is the unchanged return value from ZSTD_createCCtx. Only a single thread is used.

The 64 bit version, where the data being compressed is slightly different, always succeeds and never has an issue. Only the 32 bit version has this issue often.

The previous version of Zstd 1.4.5 did not exhibit this issue.

I tried the latest development branch as of 31 March 2021, and the problem is still there.

**Comment by Ben136KBC** [comment]
Looks like it dies in FSE_buildCTable_wksp on the first call, on the check:

    if ((size_t)workSpace & 3) return ERROR(GENERIC); /* Must be 4 byte aligned */

Here workspace is: 0x12e1e35e

When calling ZSTD_compressCCtx , the arguments were:
dest=0x2E006040
destSize = 16843776
source=0x2cff2040
size = 5956110
compressLevel = 1

**Comment by Cyan4973** [comment]
Indeed, the library expects this buffer to be aligned, and apparently it's not.
This will likely require some time to investigate why this happens.

**Comment by Ben136KBC** [comment]
Our code was compiling using /Zp1 when in 32 bits for legacy reasons. If I make sure Zstd is compiled with /Zp4 then it works again.

Does ZSTD_compressCCtx require the pointer arguments being passed in to be aligned in any way?

**Comment by Ben136KBC** [comment]
May I suggest these improvements:

In error_private.h modify ERR_isError so be:

```
ERR_STATIC unsigned ERR_isError(size_t code)
   {
   size_t test = ERROR(maxCode);
   return (code > test); 
   }
```
So that one can easily put a breakpoint on the return line?

Also, if it expects the pointers coming in from the outside to be aligned, a check at the beginning with an explicit error code would really be helpful, I spent the last couple of hours debugging this. lol.

**Comment by ghost** [comment]
> Our code was compiling using /Zp1 when in 32 bits for legacy reasons. If I make sure Zstd is compiled with /Zp4 then it works again.

How about manually add unused variables to the struct, so that it's always aligned to 4 bytes.

**Comment by felixhandte** [comment]
Struct-packing is not standards-compliant. It's hard enough to make sure zstd is correct in all the hairy corner cases of standards-compliant platforms. We're not going to try to support this.
