### ISSUE TITLE
Travis Test 'Passed' without running test

### ISSUE THREAD

**Issue by gouthamkrishnakv** [facebook/zstd#2701]
**Describe the bug**
Travis CI running test `test-zstream-2` on **Xenial (Meson+clang)** is executing "help message" **without** running any test.

**To Reproduce**
1. Run CI build on Travis
2. Navigate to **Xenial (Meson+clang)** job
3. Get to the log where `test-zstream-2` is running.
4. Check the error.

**Expected behaviour**
- The Tester should run the test `test-zstream-2`, and output it's error.
- The Tester should start execution execute with `Starting zstream tester (XX-bits, X.X.0)`.

**Present Behavior**
Outputs the following for the test
```help
Usage :
      /home/travis/build/facebook/zstd/builddir/tests/zstreamtest [args]
Arguments :
 -i#    : Number of tests (default:10000)
 -T#    : Max duration to run for. Overrides number of tests. (e.g. -T1m or -T60s for one minute)
 -s#    : Select seed (default:prompt user)
 -t#    : Select starting test number (default:0)
 -P#    : Select compressibility in % (default:50%)
 -v     : verbose
 -p     : pause at the end
 -h     : display help and exit
```
**Screenshots and charts**
Link to the unexpected behaviour of the jobs in question:
- https://www.travis-ci.com/github/facebook/zstd/jobs/512314786#L1785
- https://www.travis-ci.com/github/facebook/zstd/jobs/509247139#L1777
(I'm guessing jobs before this also had this issue, but probably have went unnoticed).

Git Blame to the test in `meson.build` file in question: 
https://github.com/facebook/zstd/blame/dd33ec9db084a0343db8e49eb0223decd8a611dd/build/meson/tests/meson.build#L189

Commit to CI configuration file Enabling Meson Tests: https://github.com/facebook/zstd/commit/1d70bc3ba92df00336b9977aba167250082880e2

The test `test-zstream-2` is possibly not at all running in Meson.

**Desktop (please complete the following information):**
 - OS: Ubuntu Xenial
 - Version: Source Tree, `dev` branch.
 - Compiler: Clang
 - Flags: Flags derived from Meson
 - Build system: Meson

**Comment by Cyan4973** [comment]
The linked test, using `--mt` command, is simply no longer valid.
It should be removed from the list of tests.
