### ISSUE TITLE
Efficient read of input sparse files

### ISSUE THREAD

**Issue by anon00000000** [facebook/zstd#2718]
Hello

**Is your feature request related to a problem? Please describe.**
My problem is the following: I may do whole block device backups using `dd if=/dev/sda of=img conv=sparse` to get a sparse file, but if I want to compress it further without zstd having to read TB of data, I have to use GNU tar with the sparse option to make the hole detection effective for further compression.

**Describe the solution you'd like**
A way for zstd to skip reading those holes.

Simple example with a 30 GB SD card image:
```
$ du -h --apparent-size disk.img
30G disk.img
$ du -h disk.img
348M    disk.img
$ time zstd -v disk.img
*** zstd command line interface 64-bits v1.3.3, by Yann Collet ***
disk.img             :  0.35%   (31914983424 => 111902939 bytes, disk.img.zst)
zstd -v disk.img  6,77s user 6,31s system 98% cpu 13,229 total
$ tar -cSf disk.img.tar disk.img
$ du -h --apparent-size disk.img.tar
348M    disk.img.tar
$ time zstd -v disk.img.tar
*** zstd command line interface 64-bits v1.3.3, by Yann Collet ***
disk.img.tar         : 29.96%   (364021760 => 109059497 bytes, disk.img.tar.zst)
zstd -v disk.img.tar  1,52s user 0,08s system 99% cpu 1,603 total
```
Note that the final compression ratio also suffers (even more at higher compression levels).

**Comment by felixhandte** [comment]
Hi @anon00000000,

Something like `tar` is probably the appropriate place to address this need. While the `zstd` command line understands the idea of files and so on, the compressed format that it writes out does not. A Zstandard compressed blob (a "frame") simply encodes a stream of bytes. So there isn't really a good place in a Zstandard frame to transport the metadata around where the holes are etc., certainly not in a way that is compatible with the standard and the existing decoder. So even if the CLI were able to recognize and skip the holes at compression-time, they would not be preserved and would not be regenerated at decompression-time, which would presumably corrupt your data.

Does that make sense?

**Comment by anon00000000** [comment]
I don't want to "transport" the metadata, zstd can already create sparse files. What is needed is to use `lseek` with `SEEK_DATA` and `SEEK_HOLE` (when available on the  OS/FS combo) instead of just reading the TBs of zeros; this probably implies some voluminous changes to zstd, to handle compression of "N zeros" instead of "a buffer of size N filled with zeros".

For example, GNU tar's way: https://git.savannah.gnu.org/cgit/tar.git/tree/src/sparse.c#n287

**Comment by Cyan4973** [comment]
`zstd` already supports writing sparse files,
but your question is about _reading_ sparse files,
and actively skipping  holes, rather than getting them transparently translated into blocks of zeroes.

While this seems in theory possible,
in practice, it's a substantial complexity, with associated increase in maintenance cost and risks.
It would have to result in some substantial gains in order to be worth the investment.

My understanding is that, in your example, when effective useful size is 100x smaller than full size (including holes), you were able to measure a 4x speed improvement.
It's certainly noticeable.
Remaining questions are : 
- how common is such a use case
- what's the benefit compared to using `tar` as an intermediate to achieve the same effect ?

**Comment by anon00000000** [comment]
If this is deemed too complex to do (I wouldn't have thought so, but I don't know zstd's internals), tar does do the job, but the bad support for sparse files from almost all compressors has always seemed strange to me.

Even a very simplistic mechanism that would fill zstd's "read buffers" with 0 via memset instead of literally reading from the disk would probably give a substantial improvement.

> how common is such a use case

Who knows? I do think that disk images aren't a fringe use case, and that zstd having a very good speed/compression ratio along with an rzip like long mode makes it very suitable.

> what's the benefit compared to using `tar` as an intermediate to achieve the same effect ?

The benefit for not using tar is evident when one knows the horrible portability situation:
https://mgorny.pl/articles/portability-of-tar-features.html#sparse-files
And this should be handled by tools that can reasonably expect to get sparse input; especially when it's a single file with no special attributes to preserve, i.e. where tar shouldn't be needed otherwise.

**Comment by Cyan4973** [comment]
> If this is deemed too complex to do (I wouldn't have thought so, but I don't know zstd's internals)

You are of course welcome to submit a patch to provide the feature, especially if you believe it's simple to do.

**Comment by ghost** [comment]
You can use a special format to deal with sparse data, and then use zstd to compress it.
