### ISSUE TITLE
Seekable parallel compression and decompression

### ISSUE THREAD

**Issue by darleybarreto** [facebook/zstd#2734]
Hi folks, I am doing something similar to the [parallel compression](https://github.com/facebook/zstd/blob/dev/contrib/seekable_format/examples/parallel_compression.c) example, but when decompressing, there's a corruption error ([this](https://github.com/facebook/zstd/blob/dev/contrib/seekable_format/zstdseek_decompress.c#L503) line). In that example, there's a [call](https://github.com/facebook/zstd/blob/dev/contrib/seekable_format/examples/parallel_compression.c#L110) directly to the `XXH64`, which gives a different checksum from when we use `XXH64_update` in `ZSTD_seekable_compressStream` [here](https://github.com/facebook/zstd/blob/dev/contrib/seekable_format/zstdseek_compress.c#L243). In this case, should I use another function instead of `ZSTD_seekable_decompress` to decompress?

Thanks in advance!

**Comment by Cyan4973** [comment]
`XXH64()` and `XXH64_update()` should give the same result,
assuming they receive same input (and same `seed`).

I would start by suspecting that this is the crux of the pb here.
It's unclear to me if tested implementation correctly resets, updates and digests `XXH64` checksum and state.
Unfortunately, "something similar" is not accurate enough, hence I can't be sure what target code is doing.
So many things can go wrong, outcome can be impacted by very subtle differences.

**Comment by darleybarreto** [comment]
> Unfortunately, "something similar" is not accurate enough, hence I can't be sure what target code is doing.

Yeah, that's a bit subtle indeed. Do you know Rust? I am trying to debug a piece of code that uses `zstd-seekable` under the hood.

**Comment by darleybarreto** [comment]
So, similarly to [`compressFrame`](https://github.com/facebook/zstd/blob/dev/contrib/seekable_format/examples/parallel_compression.c#L106), I have (in a very simplified way)
```rust
fn compress_frame<D: Dst>(
    src_ptr: *const u8,
    src_len: size_t,
    level: usize,
) -> Result<CompressedFrame<D>, Error> {
    unsafe {
        let mut dst = D::new();
        let checksum = XXH64(src_ptr, src_len); //XXH64 is the same function
        let ret = ZSTD_compress(
            dst.as_mut_ptr() as *mut c_void,
            dst.len() as size_t,
            src_ptr as *const c_void,
            src_len,
            level as c_int,
        );
        if ZSTD_isError(ret) != 0 {
            return Err(Error::ZSTD(ret));
        }
       Ok(CompressedFrame {
            src_size: src_len,
            dst_size: ret,
            checksum,
            dst,
        })
    }
}
```
The `ZSTD_compress` is the same found in `compressFrame`. To do the decompression, I have
```rust
pub fn parallel_compress<W: std::io::Write, D: Dst + 'static>(
    src: &[u8],
    mut output: W,
    level: usize,
    jobs: usize,
) -> Result<(), Error> {
    ...
    let frames = ... // an ordered vector of the parallel frames
	let mut log = FrameLog::new();
	for frame in frames.iter() {
	    output.write_all(frame.as_slice())?;
	    log.log_frame(frame);
	}
	log.write_all(&mut output)?;
	...
}
```
Here, `write_all` calls `ZSTD_seekable_writeSeekTable`, and `log_frame` calls `ZSTD_seekable_logFrame`. After that we have the compressed bytes in the output, so we need to decompress
```rust
let mut decomp = Vec::new(); // the output to fill with decompressed bytes
let mut s = { Seekable::init_buf(&output).unwrap() }; // the seekable that calls `ZSTD_seekable_initBuff`
for frame in 0..s.get_num_frames() {
    let size = s.get_frame_decompressed_size(frame);
    let n = decomp.len();
    decomp.extend(std::iter::repeat(0).take(size));
    s.decompress_frame(&mut decomp[n..], frame); // <- Error here
}
```
Then, `decompress_frame` calls `ZSTD_seekable_decompressFrame` and the checksum is different from `(XXH64_digest(&zs->xxhState) & 0xFFFFFFFFU)`. For completeness, the whole code is [here](https://nest.pijul.com/pijul/zstd-seekable:main/IH334Q5ACWE4S.LWXAG).

Thanks!

**Comment by darleybarreto** [comment]
Indeed there's no problem with the `C` examples. There's something more subtle happening in the rust side... Well, I'm closing this thread since it works as it should. Thank you for your time!
