### ISSUE TITLE
zstd v1.5.0 with row-match-finder on produces different output for same input on s390x compared to x86_64

### ISSUE THREAD

**Issue by jonathan-albrecht-ibm** [facebook/zstd#2736]
**Describe the bug**
Prior to v1.5.0, running zstd with level 6 compression but otherwise default args on the same input file would produce the same output file on s390x and x86_64. In 1.5.0, the `--row-match-finder` feature is on by default and the output file is not always the same for the same input on s390x and x86_64.

if run with `--no-row-match-finder` then both x86_64 and s390x produce identical output.

I'm not sure that zstd output is supposed to be identical on both architectures but comments in some past issues make me think it is. eg: https://github.com/facebook/zstd/issues/2079 

Please note I don't think there is any issue with the generated output on either architecture. I can still decompress a file generated on a different architecture and get the same input file back.

Also I ran `git bisect` to find the first commit where this started happening: 4694423c4f73e7d6101e44c949cfaaa0205f1500 which is how I found the `--row-match-finder` feature.

**To Reproduce**
On linux x86_64:
1. Checkout and make zstd v1.5.0
2. ` wget https://raw.githubusercontent.com/luben/zstd-jni/6030208a0d7d3d919cc7cee80900bbc31fe34b93/src/test/resources/xml`
3. `./programs/zstd -6 -f -o xml-6.zstd ./xml`
4. Check files:
```$ du -b xml*
5345280 xml
577949  xml-6.zstd
$ md5sum xml*
9b09c0c80104adb8aae910b7d7db003e  xml
bb7dd17759ecb22330af1845afcacb21  xml-6.zstd
```
5. Repeat 1-3 on s390x and check files
```
$ du -b xml*
5345280 xml
622983  xml-6.zstd
$ md5sum xml*
9b09c0c80104adb8aae910b7d7db003e  xml
acaa292dfc79ec610ec048946c5440d0  xml-6.zstd
```

**Expected behavior**
I think the output files should be identical but let me know if that's not the case.

**Desktop (please complete the following information):**
 - OS: RHEL 8.4 x86_64 and s390x
 - Version 8.4
 - Compiler gcc (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)
 - Flags Just ran bare make command
 - Other relevant hardware specs 8 core 
 - Build system Makefile

**Comment by senhuang42** [comment]
Out of curiosity, does this still happen on the current `dev` branch? Some changes have been made since 1.5.0 that affect the compression level you mentioned, specifically with regards to better big endian support, in particular, commit `dd4f6aa`.

**Comment by jonathan-albrecht-ibm** [comment]
Thanks @senhuang42. Good news, the latest `dev` branch does produce identical output on s390x and x86_64! I tried with a couple files and the output is identical now. I'll try a few more files and compression options and report back if anything looks wrong.

I'm not sure how the release process and planning works in zstd; could this fix go in a future v1.5.1? Happy to help with any testing if needed.

**Comment by senhuang42** [comment]
Great to hear! Yeah, our testing on s390x/big-endian systems unfortunately isn't particularly robust since we focus mostly on x86. Our next v1.5.1 release will definitely have this change included.

**Comment by jonathan-albrecht-ibm** [comment]
Just a quick note that I ran some more tests comparing output on x86_64 and s390x using latest dev branch on several files and compression levels and found no differences between platforms.
