### ISSUE TITLE
Small typo in documentation. ZSTD_decompress -> ZSTD_decompressDCtx

### ISSUE THREAD

**Issue by kagiannis** [facebook/zstd#2740]
**Describe the bug**
In this [line](https://github.com/facebook/zstd/blob/6ee70bae4632ce4f77f4aada0c519ef095633ecf/lib/zstd.h#L935) I think it should be  `ZSTD_decompressDCtx` instead of `ZSTD_decompress`.

**Comment by abxhr** [comment]
I would love to fix this! 🙋‍♂️
