### ISSUE TITLE
Release non windows binary

### ISSUE THREAD

**Issue by DmitryLukyanov** [facebook/zstd#2748]
Hey, I see that you have only windows binary in your releases. Do you have a guide how to get binaries for other `OS`s like linux and macOS (including building with different options like x32/x64 mode)?

**Comment by Cyan4973** [comment]
Do you mean something like [build instructions](https://github.com/facebook/zstd#build-instructions) ?

**Comment by DmitryLukyanov** [comment]
yeah :) I was able to generate libzstd library via `make` with default arguments, now I'm trying to configure the resulted file for example to be in x32 mode with no luck for now
