### ISSUE TITLE
What do I need to do to launch zstdgrep?

### ISSUE THREAD

**Issue by janafrank** [facebook/zstd#2754]
Hey! I'm still a newbie, pardon my probably naive questions, but if you could explain me step-by-step how to use it I would be very grateful. I've read that one can search through .zst files using zstdgrep. But I can't find any tutorials on how to do that actually. I've downloaded the Win64 release and use zstd command via CLI, for example in cmd:
`C:\zstd-v1.5.0-win64> zstd --help` works just fine.

But now how do I use zstdgrep? `zstdgrep` command doesn't work. I've cloned the repository to try and launch zstdgrep from `zstd/programs` folder, but cmd does not recognize it as a command. Powershell just tries to open it as a file.

So yeah, I'm stumbling in a dark here, so any help greatly appreaciated c:

**Comment by Cyan4973** [comment]
`zstdgrep` is a [shell script](https://en.wikipedia.org/wiki/Shell_script),
meaning it's meant to be run in a posix shell environment. Linux and macos come to mind.

On Windows, it might work in an emulated posix console, like `msys`, `mingw` or `cygwin`.
But certainly not in non-`sh` compliant consoles, such as `cmd` or `powershell`.

**Comment by variar** [comment]
Installing WSL on Windows can help launching those shell scripts.
