### ISSUE TITLE
Dictionary/No-Dictionary/Object Storage/Append Compression?

### ISSUE THREAD

**Issue by Lexxos** [facebook/zstd#2759]
I have a dataset of 300 terabytes in hundreds of thousands of plain FILES on linux that can delimited by :

for instance the files are as such;

proposal.name{

column1 = name : column2 = location};

so that is how our entire archive is saved.

but we are needing to make these public for public research since our team was publicly funded. It was going to be impossible to serve these under normal standards, but since your software allows for quick and accurate search queries; we decided to go with this route. 

What is the best option to do? We will be adding files every month, so do we create a dictionary, and then apply the dictionary to that file that's going to be at least 100GB, or do we just make a new impression?

The title length of entries is 80 character. 

Will I get better compression and searchability by going this route? I've tried a few options but errors keep getting thrown. Eventually I just appended them all together with a header on each layer and compressed it.

**Comment by Cyan4973** [comment]
Dictionary compression is meant for compressing "small" data, think about a few KB per object, at most.
Of course, a whole lot of small data can still represent a huge total amount of data.
But now it depends, on your application, on your access pattern.

From a compression ratio perspective, you will get the best result by appending all these files together and compressing them together. Dictionary compression is not expected to do better than that, it's expected to mitigate the impact of separating these files and compressing them independently.

Compressing a bunch of files together is best for compression ratio, but it has other drawbacks. For example, if one needs just one file or one field inside the big pack, it still needs to decompress the whole pack. That's a form of energy waste. Sometimes it's acceptable, sometimes it's not. It really depends on the application.
Same thing on the compression side, compressing many files together means having these files all available at compression time. Depending on the generation process, these files probably have to be buffered somewhere, and then compressed when date is due or enough amount has been accumulated. Sometimes it's acceptable, sometimes it's not, depending on application's requirement.

As you can see, there is no "one size fits all".
Considering your objective, distributing a large amount of data to the public, eventually refreshed once per month, it looks to me that just aggregating these monthly packs of files and compressing them as a single stream (typically `tar | zstd`) would maximize the compression ratio, hence save of bandwidth and storage, which seems to be your primary concern.

**Comment by Lexxos** [comment]
I'm sorry, I must have really misunderstood something. I thought your compression software was different because it was able to be searched using the scheme of the dictionary and was able to be extracted in blocks from the main compressor. So, basically, this compresses many, many little files, which makes them easier to search. I have strings of information such as serial numbers. Can those serial numbers be located when searched? If that's not the case, we may have to try out a one byte file system. Although at max that only saves us half since we're already on linux. Had we been on Windows it would have been a 4x improvement.

If they need to be small filers, I can certainly truncate everything into sections and subsections. It says that the dictionary should be trained on 10% of the fully expectant files. So, would we create many files that equal 30TB and train on that? And if so, how big should the files be? What actions would you recommend we run?

**Comment by Cyan4973** [comment]
The [`seekable_format`](https://github.com/facebook/zstd/tree/dev/contrib/seekable_format) might be able to provide some of the basic functionalities needed, such as compressing and retrieving individual files, using a jump table with an index. But it's merely a starting point. There is a lot of boiler plate to add in order for your implementation to do exactly what you desire.

In any case, it looks to me that your topic is much larger than "just" compression.
Search is an entirely different field for example.

**Comment by Lexxos** [comment]
https://github.com/Genivia/ugrep

looks like the solution was right around the corner! But it appears to work with ZSTD, so I'm going to see how well this compresses some archives. Any suggestions on how to pack them?
