### ISSUE TITLE
The zstd benchmark on the website/readme is not up to date

### ISSUE THREAD

**Issue by Augustin-Zidek** [facebook/zstd#2764]
**Is your feature request related to a problem? Please describe.**
On the website http://facebook.github.io/zstd/ and in the GitHub readme, it would be great to see benchmarks of the latest version of zstd (1.5.0 currently), but the benchmarked version is 1.4.5 which was released more than 1 year ago. Numerous performance improvements have been added in the last year and it would be great for the benchmark to reflect this.

**Describe the solution you'd like**
It would be great to have a benchmark of the most recent version (1.5.0 currently) on the project website and in the GitHub readme. It would be also gread to benchmark against the most recent versions of other compression libraries, and using the most up-to-date version of `lzbench`:
zlib 1.2.11
brotli 1.0.9
quicklz 1.5.0
lzo1x 2.10
lz4 1.9.3
lzf 3.6
snappy 1.1.9

Thanks!

**Comment by Cyan4973** [comment]
We'll likely make an update for `v1.5.1`

**Comment by Augustin-Zidek** [comment]
Brilliant, thank you! Looking forward to the updated numbers and thanks for making zstd faster with every version.

**Comment by Cyan4973** [comment]
Benchmark updated

**Comment by Augustin-Zidek** [comment]
Amazing, thank you (and congrats on the upcoming release)!

Note that http://facebook.github.io/zstd/ still has the old benchmark numbers, but I assume the main readme lives in GitHub anyway these days.

**Comment by gvollant** [comment]
if possible, including https://github.com/zlib-ng/zlib-ng in benchmark can be useful. https://github.com/zlib-ng/zlib-ng is a deflate "1993" compatible solution faster than classic zlib

**Comment by gvollant** [comment]
And pehaps for large dictionnary compression, xz - lzma - 7zip

**Comment by andrews05** [comment]
@Cyan4973 I think you forgot to put the correct version on the zstd fast benchmarks?

Also, any chance you could update the charts? [This one](https://github.com/facebook/zstd/blob/dev/doc/images/DCspeed5.png) is from v0.6.0.

**Comment by Cyan4973** [comment]
> @Cyan4973 I think you forgot to put the correct version on the zstd fast benchmarks?

Indeed! Thanks for the notification, it's fixed now.

> Also, any chance you could update the charts? [This one](https://github.com/facebook/zstd/blob/dev/doc/images/DCspeed5.png) is from v0.6.0.

Will need some more time

**Comment by data-man** [comment]
@gvollant 

> if possible, including zlib-ng/zlib-ng in benchmark can be useful.

Feel free improve my branch: https://github.com/data-man/lzbench/tree/zlib_ng

Some my results (`ucd.all.flat.xml` from Unicode 14.0):
lzbench 1.8 (64-bit Linux)  Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Assembled by P.Skibinski

| Compressor name         | Compression| Decompress.| Compr. size | Ratio | Filename |
| ---------------         | -----------| -----------| ----------- | ----- | -------- |
| memcpy                  |  7005 MB/s |  6961 MB/s |   203590448 |100.00 | ucd.all.flat.xml|
| brotli 1.0.9 -2         |   449 MB/s |  2716 MB/s |     7026109 |  3.45 | ucd.all.flat.xml|
| brotli 1.0.9 -5         |   141 MB/s |  2879 MB/s |     5842190 |  2.87 | ucd.all.flat.xml|
| zstd 1.5.0 -2           |  1550 MB/s |  4190 MB/s |     7319337 |  3.60 | ucd.all.flat.xml|
| zstd 1.5.0 -5           |   319 MB/s |  4163 MB/s |     6821822 |  3.35 | ucd.all.flat.xml|
| zlib 1.2.11 -2          |   272 MB/s |   977 MB/s |    10982359 |  5.39 | ucd.all.flat.xml|
| zlib 1.2.11 -5          |   146 MB/s |  1050 MB/s |     8769979 |  4.31 | ucd.all.flat.xml|
| zlib-ng 2.1.0.devel -2  |   497 MB/s |  1215 MB/s |    11066537 |  5.44 | ucd.all.flat.xml|
| zlib-ng 2.1.0.devel -5  |   306 MB/s |  1320 MB/s |     8741770 |  4.29 | ucd.all.flat.xml|

It's combined table: `lzbench` compiled with `make DONT_BUILD_ZLIB_NG=1` and `make DONT_BUILD_ZLIB=1`.
