### ISSUE TITLE
Minor TYPO in ztest build/test process

### ISSUE THREAD

**Issue by stephan57160** [facebook/zstd#2768]
**Describe the bug**
Detected, when rebuilding from scratch with RPMBUILD on a CentOS Box :
  `Also consdier playing around with searchLog and hashLog`

Appears a few times during the build/testing process.

Typo present in the sources:
``` 
[stephan@pc-stephan:zstd]$ find . -type f | xargs grep consdier
./programs/fileio.c:        DISPLAYLEVEL(1, "Also consdier playing around with searchLog and hashLog\n");
[stephan@pc-stephan:zstd]$ 
```

**To Reproduce**
- git clone ...
- cd zstd
- make all pzstd tests tests_zstd 2>1& |  grep consdier

**Expected behavior**
Should be "consider", not "consdier".

**Screenshots and charts**
```
[Optimal parser notes] Consider the following to improve patch size at the cost of speed:
- Use --single-thread mode in the zstd cli
- Set a larger targetLength (eg. --zstd=targetLength=4096)
- Set a larger chainLog (eg. --zstd=chainLog=29)
Also consdier playing around with searchLog and hashLog
     ^^^^^^^^
```
...
```
===> alternate syntax: patch-from origin
[Optimal parser notes] Consider the following to improve patch size at the cost of speed:
- Use --single-thread mode in the zstd cli
- Set a larger targetLength (eg. --zstd=targetLength=4096)
- Set a larger chainLog (eg. --zstd=chainLog=29)
Also consdier playing around with searchLog and hashLog
     ^^^^^^^^
```
...
```
zstd: error 42 : Using --patch-from with stdin requires --stream-size 
[Optimal parser notes] Consider the following to improve patch size at the cost of speed:
- Use --single-thread mode in the zstd cli
- Set a larger targetLength (eg. --zstd=targetLength=4096)
- Set a larger chainLog (eg. --zstd=chainLog=29)
Also consdier playing around with searchLog and hashLog
     ^^^^^^^^
```
...

**Desktop (please complete the following information):**
 - OS: NA
 - Version : NA
 - Compiler : NA
 - Flags : NA
 - Other relevant hardware specs : NA
 - Build system : Makefile

**Additional context**

**Comment by stephan57160** [comment]
It seems there since 2020 and #1959.

Even a google search shows the same :
https://www.google.com/search?q=%22Also+consdier+playing+around%22&filter=0&biw=1920&bih=1067

https://fedora.starfivetech.com/kojifiles/work/tasks/257/257/build.log
https://fedora.starfivetech.com/kojifiles/packages/zstd/1.4.9/1.fc33/data/logs/riscv64/build.log
...

**Comment by senhuang42** [comment]
Thanks for pointing this out, should be fixed now
