### ISSUE TITLE
Ninja + cmake on Windows build error

### ISSUE THREAD

**Issue by cartesius82** [facebook/zstd#2770]
Cannot build ZSTD using `ninja` + `cmake` (versions below) on Windows. Perhaps it's the cmake's fault but is there any workaround? `msbuild` generator works fine.

```
cmake ..\build\cmake\ -G Ninja

...
-- Performing Test C_FLAG_WCAST_ALIGN
-- Performing Test C_FLAG_WCAST_ALIGN - Success
-- Performing Test CXX_FLAG_WCAST_ALIGN
-- Performing Test CXX_FLAG_WCAST_ALIGN - Success
-- Performing Test C_FLAG_WCAST_QUAL
-- Performing Test C_FLAG_WCAST_QUAL - Success
-- Performing Test CXX_FLAG_WCAST_QUAL
-- Performing Test CXX_FLAG_WCAST_QUAL - Success
-- Performing Test C_FLAG_WSTRICT_PROTOTYPES
-- Performing Test C_FLAG_WSTRICT_PROTOTYPES - Success
-- Performing Test C_FLAG_DDEBUGLEVEL_1
-- Performing Test C_FLAG_DDEBUGLEVEL_1 - Success
-- Performing Test CXX_FLAG_DDEBUGLEVEL_1
-- Performing Test CXX_FLAG_DDEBUGLEVEL_1 - Success
-- CMAKE_INSTALL_PREFIX: C:/Program Files (x86)/zstd
-- CMAKE_INSTALL_LIBDIR: lib
-- ZSTD_LEGACY_SUPPORT not defined!
-- ZSTD_MULTITHREAD_SUPPORT is enabled
-- Configuring done
-- Generating done
CMake Error:
  Running

   'C:/Users/james/scoop/shims/ninja.exe' '-C' 'C:/Users/james/src/xxx/third_party/zstd/b' '-t' 'recompact'

  failed with:

   ninja: error: build.ninja:767: multiple rules generate lib/zstd.lib [-w dupbuild=err]

```

Trying `-w dupbuild=warn` leads to errors as well.

**Versions**

- cmake version 3.21.2
- ninja 1.10.2
- commit a488ba114ec17ea1054b9057c26a046fc122b3b6 (HEAD, tag: v1.5.0, origin/release)

**Comment by cartesius82** [comment]
@Cyan4973 Thank you for proper tagging. Any help would be appreciated.

**Comment by jannkoeker** [comment]
You are propably using Clang (**not** Clang-cl)
See https://github.com/facebook/zstd/issues/2248#issuecomment-927108348

**Comment by terrelln** [comment]
Is there any action for us to take on this issue?

**Comment by jannkoeker** [comment]
The best way would be to extend this code block
https://github.com/facebook/zstd/blob/c2c6a4ab40fcc327e79d5364f9c2ab1e41e6a7f8/build/cmake/lib/CMakeLists.txt#L108-L113
to add an additional check for Clang on Windows.
I will create a pull request as soon as I have time.
