### ISSUE TITLE
A question about msvc with sdl

### ISSUE THREAD

**Issue by andrewevstyukhin** [facebook/zstd#2772]
Hi, folks!

We use MSVC from the latest Visual Studio 2019 (16.11.2) with [/sdl](https://docs.microsoft.com/en-us/cpp/build/reference/sdl-enable-additional-security-checks?view=msvc-160) option enabled and we have some warnings on the latest 1.5.0 release for Win64.

Zstd compiles fine with /sdl- but not with /sdl. So question is how to properly fix this place:

> /* DMS/DDS variables that may be referenced laster
> ...
> U32* dmsRow = 0;
> BYTE* dmsTagRow = 0;

Looks like a false positive under multiple `if (dictMode == ZSTD_dictMatchState)`

**Comment by ghost** [comment]
I tested,  this commit has fixed the problem:

commit 7012c6e7a4dbedad5b6a949a49ce941adc5e8df8
Author: Bartosz Taudul
Date:   Sat May 15 00:40:49 2021 +0200

Initialize "potentially uninitialized" pointers.

lib/compress/zstd_lazy.c | 4 ++--
1 file changed, 2 insertions(+), 2 deletions(-)
