### ISSUE TITLE
[CI] Work around compiler bug and re-enable aarch64build

### ISSUE THREAD

**Issue by terrelln** [facebook/zstd#2785]
https://github.com/facebook/zstd/pull/2783 triggered an internal compiler error in the aarch64 compiler. E.g. this [run](https://app.circleci.com/pipelines/github/facebook/zstd/3169/workflows/214e6e68-b827-468c-b364-0b2d0a619f91/jobs/11255). I haven't been able to fix it, so I've just disabled the test for now. We have aarch64 coverage of the main binary in GitHub Actions [here](https://github.com/facebook/zstd/blob/dev/.github/workflows/dev-short-tests.yml#L243). What we're missing is the build of the other binaries covered by `make allzstd`.

Alternatively, `make allzstd` could be covered by the QEMU tests in GitHub Actions. But, I had some issues with linking in the naive attempt, so I haven't done it yet.

**Comment by Cyan4973** [comment]
Reducing test duplication is a good objective anyway.
