### ISSUE TITLE
unexpected increase of runtime 

### ISSUE THREAD

**Issue by sbelharbi** [facebook/zstd#2786]
hi,
thanks for this work.
**Describe the bug**
so, the issue is the following:

i have n=240 folder to compress.
i compress them iteratively using `tar` with combination with `zstandard`.
all folders have relatively the same number of files (rgb images) and same size (~200kb).
so, i expect that the compression will take relatively the same time.
in my case, it is not.
there is a sudden large constant increase after processing few folders.
the code is running over a server with almost no load. 
the sever is almost idle even when compressing. all the cores are at ~0 % of their capacity.
there is almost no increase in memory during compression.
because processes are run iteratively, i dont expect any accumulation of ram usage or any other interaction.

any idea why this behavior? and how to fix it?

i run a bash script `compress.sh` with the following content:

text files contain list of files to compress.

```sh
#!/usr/bin/env bash  
echo "0/240" 
time ( cd folder && tar -cf  train_chunk_0.tar.zst --use-compress-program=zstd -T train_chunk_0.txt  ) 

echo "1/240" 
time ( cd folder && tar -cf  train_chunk_1.tar.zst --use-compress-program=zstd -T train_chunk_1.txt  ) 

...

echo "239/240" 
time ( cd folder && tar -cf  train_chunk_239.tar.zst --use-compress-program=zstd -T train_chunk_239.txt  ) 

```

```sh
...
7/240

real    0m10.556s
user    0m3.188s
sys     0m1.904s
8/240

real    0m11.158s
user    0m3.576s
sys     0m2.044s
9/240

real    0m10.658s
user    0m3.200s
sys     0m1.956s
10/240

real    0m11.382s
user    0m3.588s
sys     0m2.072s
11/240

real    0m12.846s
user    0m3.564s
sys     0m2.196s
12/240

real    0m10.625s
user    0m3.252s
sys     0m1.980s
13/240

real    0m10.599s
user    0m3.392s
sys     0m2.160s
14/240

real    0m11.170s
user    0m3.484s
sys     0m2.320s
15/240

real    0m10.598s
user    0m3.236s
sys     0m2.020s
16/240

real    0m10.816s
user    0m3.280s
sys     0m2.284s
17/240

real    0m10.366s
user    0m3.000s
sys     0m2.084s
18/240

real    0m10.796s
user    0m2.996s
sys     0m2.056s
19/240

real    0m11.067s
user    0m3.448s
sys     0m2.268s
20/240

real    0m12.532s
user    0m3.396s
sys     0m2.324s
21/240

real    0m10.590s
user    0m3.400s
sys     0m2.244s
22/240

real    1m3.184s
user    0m3.640s
sys     0m2.336s
23/240

real    2m11.785s
user    0m4.052s
sys     0m3.216s

real    2m11.785s
user    0m4.052s
sys     0m3.216s
24/240

real    2m10.322s
user    0m4.124s
sys     0m3.868s
25/240

real    2m8.806s
user    0m4.156s
sys     0m3.052s
26/240

real    2m11.435s
user    0m4.140s
sys     0m3.248s
27/240

real    2m12.506s
user    0m4.100s
sys     0m3.208s
28/240

real    2m13.846s
user    0m4.156s
sys     0m3.468s
29/240

real    2m11.701s
user    0m4.108s
sys     0m3.032s
30/240

real    2m12.598s
user    0m4.056s
sys     0m3.152s
31/240

real    2m10.040s
user    0m4.192s
sys     0m3.156s
32/240

real    2m11.127s
user    0m4.224s
sys     0m3.280s
33/240


...
```

**To Reproduce**
1. install 
```sh
git clone https://github.com/facebook/zstd.git
git checkout 9d2a45a705e22ad4817b41442949cd0f78597154
make
make prefix=~/.local install
```
2. run script. not sure how you can do this...

**Expected behavior**
the compression of every folder is expected to have relatively the same runtime.

**Screenshots and charts**
If applicable, add screenshots and charts to help explain your problem.

**Desktop (please complete the following information):**

$ make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

OS: Ubuntu 16.04.4 LTS (x86_64)
GCC version: (Ubuntu 5.4.1-2ubuntu1~16.04) 5.4.1 20160904
Clang version: Could not collect
CMake version: version 3.5.1
Libc version: glibc-2.7

zstandard: 1.5.0

$ tar --version
tar (GNU tar) 1.28
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.

cpu:
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                28
On-line CPU(s) list:   0-27
Thread(s) per core:    1
Core(s) per socket:    14
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
Stepping:              1
CPU MHz:               1200.281
CPU max MHz:           3300.0000
CPU min MHz:           1200.0000
BogoMIPS:              4801.66
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              35840K
NUMA node0 CPU(s):     0-13
NUMA node1 CPU(s):     14-27
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts

let me know if you need more info.
thanks

**Comment by Cyan4973** [comment]
`real` time increases dramatically, while `user` stays relatively the same.

This leans towards a scenario where the cpu is effectively waiting for something else to complete. It's not using more energy to compress.

Given the nature of your application, I would suspect an I/O condition, either on network, or directly on storage side.

**Comment by sbelharbi** [comment]
i think you are right.
it could be the disk.
it is known to have issue.
i think cpu is waiting for the writing to finish and it is taking all the extra observed time.
the network could be a possible issue.

i run this script several times. and i observed the same behavior.
that's why i supected zstandard is probably accumulating something and it slows it down.

assuming it is the disk/network, why the writing is fast at the first couple folders ~10s, but it hits 2mins later...

could writing several files 600mb in a row on disk-with-issues  slow the disk down?
thanks

**Comment by sbelharbi** [comment]
closing as this is more likely to be caused by our disk or network.
thanks
