### ISSUE TITLE
gcc `bmi2` option doesn't contain `bmi`

### ISSUE THREAD

**Issue by ghost** [facebook/zstd#2814]
Compile this code using `gcc-9.3`:
```c
#include <stdint.h>
#include <stdio.h>
#include <x86intrin.h>

__attribute__((__target__("bmi2")))  // <- wrongly use bmi2
unsigned long long blsr(unsigned long long l)
{
    // Reset lowest set bit, BMI(1) has an instruction `blsr` for it.
    return l & (l - 1);
}

int main(int argc, char** argv)
{
    printf("%lld\n", blsr(atoll(argv[1])));
    return 0;
}
```
Asm code:
```asm
blsr:
.LFB5547:
	.cfi_startproc
	endbr64
	lea	rax, -1[rdi]
	and	rax, rdi
	ret
	.cfi_endproc
```
If change `__attribute__((__target__("bmi2")))` to `__attribute__((__target__("bmi")))`, gcc uses a BMI(1) instruction `blsr	`:
```asm
blsr:
.LFB5547:
	.cfi_startproc
	endbr64
	blsr	rax, rdi
	ret
	.cfi_endproc
```

So `TARGET_ATTRIBUTE("bmi2")` in zstd source code should be `TARGET_ATTRIBUTE("bmi,bmi2,lzcnt")`, then can make full use of (potential) instructions.

Ref:
1. [Wikipedia - X86 Bit manipulation instruction set](https://en.wikipedia.org/wiki/X86_Bit_manipulation_instruction_set)
2. [gcc defines haswell instructions](https://github.com/gcc-mirror/gcc/blob/master/gcc/config/i386/i386.h#L2298-L2299)

**Comment by ghost** [comment]
Another way to check it:
```
gcc -mbmi  -dM -E - < /dev/null | egrep "FMA|SSE|AVX|BMI|MMX|CNT" | sort
#define __BMI__ 1
...
```
```
gcc -mbmi2  -dM -E - < /dev/null | egrep "FMA|SSE|AVX|BMI|MMX|CNT" | sort
#define __BMI2__ 1
...
```
```
gcc -mlzcnt  -dM -E - < /dev/null | egrep "FMA|SSE|AVX|BMI|MMX|CNT" | sort
#define __LZCNT__ 1
...
```
Unlike `-mavx2`, it enables mmx/sse/sse2/sse3/ssse3/sse4.1/sse4.2/avx instructions.

**Comment by ghost** [comment]
If chang like this:
```diff
-TARGET_ATTRIBUTE("bmi2")
+TARGET_ATTRIBUTE("avx2,bmi,bmi2,lzcnt")
```
In `gcc` build, the decompression speed improves:
```
 1#silesia.tar   375.9 MB/s, 1294.3 MB/s  ->  374.5 MB/s, 1301.3 MB/s
 2#silesia.tar   285.9 MB/s, 1141.0 MB/s  ->  285.1 MB/s, 1154.7 MB/s
 3#silesia.tar   201.7 MB/s, 1090.3 MB/s  ->  202.7 MB/s, 1105.4 MB/s
 4#silesia.tar   186.8 MB/s, 1051.7 MB/s  ->  188.0 MB/s, 1073.7 MB/s
 5#silesia.tar   110.6 MB/s, 1075.0 MB/s  ->  109.5 MB/s, 1093.9 MB/s
 6#silesia.tar    74.9 MB/s, 1073.2 MB/s  ->   74.7 MB/s, 1096.9 MB/s
 7#silesia.tar    63.3 MB/s, 1132.9 MB/s  ->   62.6 MB/s, 1167.2 MB/s
 8#silesia.tar    51.6 MB/s, 1152.2 MB/s  ->   51.9 MB/s, 1171.0 MB/s
 9#silesia.tar    45.1 MB/s, 1165.3 MB/s  ->   45.4 MB/s, 1185.2 MB/s
10#silesia.tar    38.9 MB/s, 1126.8 MB/s  ->   38.7 MB/s, 1151.4 MB/s
11#silesia.tar    30.0 MB/s, 1138.7 MB/s  ->   30.0 MB/s, 1162.9 MB/s
12#silesia.tar    20.7 MB/s, 1146.9 MB/s  ->   20.6 MB/s, 1166.3 MB/s
```
CPUs that support `bmi2` instructions should also support these instructions.

**Comment by Cyan4973** [comment]
Thanks @animalize, that's a good find !

**Comment by terrelln** [comment]
This could be doable. I wouldn't enable it by implicitly enabling AVX2 / BMI1, but by changing our bmi2 check to include all 3 using `ZSTD_cpuid_bmi1(cpuid) && ZSTD_cpuid_bmi2(cpuid) && ZSTD_cpuid_avx2(cpuid)`.

On my machine, I don't see a significant difference when enabling BMI1 & lzcnt & avx2. I actually see worse performance, likely because of alignment. So I'd want to be sure the gains were actually because the compiler was able to use a new instruction, and not because of random noise.

**Comment by ghost** [comment]
> On my machine, I don't see a significant difference when enabling BMI1 & lzcnt & avx2. I actually see worse performance, likely because of alignment.

There seems to be a bit improvement on my machines overall. 
The current `dev` branch, `CLI` means benchmark with the CLI program, `LIB` means the statically linked zstd library, I tested each one 9 times.

**On i5-4570, gcc-9.3, Ubuntu20.04 (WSL2)**

![1](https://user-images.githubusercontent.com/11244865/137579864-26a4c0c5-e5cc-417c-b377-813f60f22ffb.png)
![2](https://user-images.githubusercontent.com/11244865/137579866-2d705d03-d85d-4546-8132-1135f88503e0.png)
![3](https://user-images.githubusercontent.com/11244865/137579874-b166ffd9-42f2-4e3e-92fb-929038a93ce4.png)
![4](https://user-images.githubusercontent.com/11244865/137579885-ca621731-8e8f-4b3b-9ff3-5f72647d1941.png)

**On r5-3600X, gcc-9.3, Ubuntu20.04 (WSL2)**

![a](https://user-images.githubusercontent.com/11244865/137579917-f6e17bc0-714f-4a8b-adf1-bc163131700c.png)
![b](https://user-images.githubusercontent.com/11244865/137579923-ee8103d5-4a28-42f4-9845-3def51604111.png)
![c](https://user-images.githubusercontent.com/11244865/137579934-564a4760-63da-438c-9924-bc9cf95c54b3.png)
![d](https://user-images.githubusercontent.com/11244865/137579943-60e85cb6-d31e-48af-be51-eee7e94f0fbc.png)

**Comment by ghost** [comment]
Above tests were tested with gcc-9.3, changed like this:
```diff
-TARGET_ATTRIBUTE("bmi2")
+TARGET_ATTRIBUTE("avx2,bmi,bmi2,lzcnt")
```

This benchmark use global options, statically link to zstd library, test 12 times for each one:

- gcc 11.1: `-mavx2 -mbmi -mbmi2 -mlzcnt`
- msvc 2022-preview: `/arch:AVX2`

![avx2](https://user-images.githubusercontent.com/11244865/138213459-3aaf0c61-62d3-4097-8b13-21f9dfbd7363.png)

With `gcc-11.1`, the avx2 build is slower in de-compressions, but faster in some level compressions.
With `msvc-2022-preview`, the avx2 build is always faster.

> On my machine, I don't see a significant difference when enabling BMI1 & lzcnt & avx2. I actually see worse performance, likely because of alignment.

It seems this is not a net win in `gcc` builds.
