### ISSUE TITLE
Zstd should try to draw the progress bar only on TTY

### ISSUE THREAD

**Issue by jimis** [facebook/zstd#2816]
I run zstd v1.4.4 as a cron job, and I get a progress bar output even when the stdout and stderr are not tty:
```
zstd --rm -19 $FILENAME  2>&1 | logger
```

Zstd tries to draw the progress bar, as a result I see this in the journal:
```
[386B blob data]
```

It would be best to imply `-q` when the stdout/stderr are not a tty. Or at least print `\n` instead of `\r` as a separator between the lines.

**Comment by terrelln** [comment]
I think implying `-q` when `stderr` is not a TTY would make sense.
