### ISSUE TITLE
What is the correct way to pass the "--fast=X" flag for compression in BTRFS mount options?

### ISSUE THREAD

**Issue by bkdwt** [facebook/zstd#2821]
By default we use compression=zstd:X (x is the level), but now I see this new flag "--fast=X" and I don't know how to use this on FSTAB.

```
compression=zstd --fast=X?
compression=zstd_fast:X?
```

Thanks in advance! :)

**Comment by terrelln** [comment]
The lowest compression level available for BtrFS is 1. We added BtrFS support before negative compression levels were added, so it doesn't support them.

There isn't currently a way to say `compression=zstd:-1` or `compression=zstd_fast:1`. We have considered changing the compression level mapping, and mapping `zstd:1` to `-1`.

I'm currently working on updating the zstd version in the kernel. Once that works has landed, it will be possible to use negative compression levels, and we could consider how to support them in BtrFS.

**Comment by bkdwt** [comment]
> The lowest compression level available for BtrFS is 1. We added BtrFS support before negative compression levels were added, so it doesn't support them.
> 
> There isn't currently a way to say or . We have considered changing the compression level mapping, and mapping to .`compression=zstd:-1``compression=zstd_fast:1``zstd:1``-1`
> 
> I'm currently working on updating the zstd version in the kernel. Once that works has landed, it will be possible to use negative compression levels, and we could consider how to support them in BtrFS.

Thanks for the explanation and for your hard work! I'll wait for this. 😉
