### ISSUE TITLE
Compression ratio for --fast=2 and higher became significantly worse. Expected?

### ISSUE THREAD

**Issue by danlark1** [facebook/zstd#2827]
https://github.com/facebook/zstd/pull/2749 introduced a noticeable regression in compression ratio of --fast=2 and higher fast compression values for silesia.tar

```console
$ git checkout 80bc12b33a
build
$ ./zstd --fast=3 ~/data/silesia.tar
57.05%   (   267 MiB =>    152 MiB)
$ git checkout ab8aa49b
build
$ ./zstd --fast=3 ~/data/silesia.tar
61.30%   (   267 MiB =>    164 MiB)
```

164/152 ~ 1.08

Yes, it came with around ~10% CPU performance increase but just to note that I don't see any benchmarks of lower than -1 values in the pull request. And -1 is just fine

At Google we see up to 20% regressions on some data with --fast=3, so I wonder if that's expected

**Comment by danlark1** [comment]
Oh, I actually see the diff in tests/regression/results.csv

```
before:
silesia.tar,                        level -5,                           compress simple,                    6738593
silesia.tar,                        level -3,                           compress simple,                    6446372
silesia.tar,                        level -1,                           compress simple,                    6186042
after:
silesia.tar,                        level -5,                           compress simple,                    7359401
silesia.tar,                        level -3,                           compress simple,                    6901672
silesia.tar,                        level -1,                           compress simple,                    6182241
```

**Comment by terrelln** [comment]
Thanks for the feedback, its especially helpful before a release, so we have time to change things if we want!

So far we haven't really stabilized the ratio/speed tradeoff negative compression levels. They're getting monotonically faster, but thats what we provide so far. So we'll have to discuss and decide if we want to provide further stability.

Does switching from `--fast=3` to `--fast=2` approximate the old `--fast=3` setting?

**Comment by danlark1** [comment]
`--fast=2` is on par with the old `--fast=3` performance but compression ratio is still a little worse for our data: 8% of relative size (new/old) vs 20% when both compressed with `--fast=3`

We are considering more to move with `--fast=1` as it provides better tradeoff

**Comment by terrelln** [comment]
It seems like we aren't quite ready to stabilize the speed curve of the negative compression levels. For now we will leave them un-stabilized. This topic is on our mind, but we find ourselves lacking time. We want to take our time here, so we don't close off future opportunities in the negative compression level space.

**Comment by felixhandte** [comment]
Hey @danlark1, this was a known issue with #2749 but we felt that it was a reasonable tradeoff since that PR benefits levels 1 and 2, which are much more heavily used.

I recently spent some time seeing if we can avoid harming the negative levels as much. The result of that work is #2921, which I expect to merge shortly. We come much closer to preserving the pre-existing behavior of the negative levels, although things do shift around some. So you may still want to tune exactly which level you use, but the choices should be better. Let me know if you have any feedback!

**Comment by danlark1** [comment]
FYI, we migrated to level -1 in these workloads and feel happier than ever, luckily, it was successful in terms of savings

Still I find it useful to tell about you these findings
