### ISSUE TITLE
Size optimization for clevels.h

### ISSUE THREAD

**Issue by aleksazr** [facebook/zstd#2833]
@Cyan4973 recently added clevels.h in #2830 and noted there could be cpu-specific tables in the future.

What I don't like is the size of the `ZSTD_defaultCParameters` table.
It has 4*23 levels with 28 bytes each which is 2576 bytes.

I'm proposing a shorter table, with 4 bytes per entry, totaling 368 bytes.
The shorter table would be used only once, at program init, to convert the shorter table into run-time table.

http://users.beotel.net/~gwh/zstd/clevels.h

A line from current clevels.h `{ 19, 12, 13,  1,  6,  1, ZSTD_fast    }`
would be replaced with `{ dcpW_19, dcpC_12, dcpH_13,  dcpS_1,  dcpL_6,  dcpT_1, ZSTD_fast    }`

`dcp` stands for `defaultCParameters`, `W` for `windowLog`, `C` for `chainLog` and so on.

`dcpW_19` is defined in `DCPW_enum` and is a zero-based index into `DCPW` table which has all numbers used by `dcpW_xxx` entries.

`dcpw` is defined as 4 - the number of bits required to accommodate all the numbers in `DCPW` table.

`ZSTD_defaultCParameters_Init()` (~200 bytes of x86/x64 code) is used to convert  the table, and I have tested it to produce the same table as the original. Perhaps it should be called from `ZSTD_CCtxParams_init_internal()`.

**Comment by Cyan4973** [comment]
> `ZSTD_defaultCParameters_Init()` (...) is used to convert the table, and I have tested it to produce the same table as the original.

Note that this suggested optimization transfers memory usage from one type of memory to another.

In the original case, the table is static, and remains in read-only memory.
In the new suggested construction, the static read-only memory usage is reduced, but the full table now lays in RAM.

Worth mentioning that most memory-limited environments, typically embedded systems, tend to value RAM even more than read-only memory.

**Comment by aleksazr** [comment]
Well, my first idea was this 8 bytes struct

```
typedef struct {
    unsigned windowLog:8;     // BYTE
    unsigned chainLog:8;      // BYTE
    unsigned hashLog:8;       // BYTE
    unsigned searchLog:8;     // BYTE
    unsigned minMatch:8;      // BYTE
    ZSTD_strategy strategy:8; // BYTE
    unsigned targetLength:16; // WORD (aligned order)
} ZSTD_compressionParameters_short;
```

but I didn't know if 8/16 bits would be enough, and if it would have a performance penalty.

**Comment by Cyan4973** [comment]
It would theoretically have a performance penalty, but it also probably wouldn't matter much : it's only run once per job. That's unlikely to move the needle.

**Comment by aleksazr** [comment]
Not sure if you understood it. It is not run at all (there is no conversion), that is a static const table, just organized as bytes, instead of dwords. So it would be accessed at run time with zero extensioning. Again, not sure if it would be a performace penalty.

**Comment by Cyan4973** [comment]
> it would be accessed at run time with zero extensioning. Again, not sure if it would be a performace penalty.

I understood it this way, and yes, it would have a theoretical performance penalty, though likely an insignificant one.

**Comment by Cyan4973** [comment]
Is this topic still active ?

**Comment by aleksazr** [comment]
afaic, no. Its only 2k diff.
