### ISSUE TITLE
Cross-origin image request in docs causes TLS client cert prompt

### ISSUE THREAD

**Issue by hmarr** [facebook/zstd#2842]
**Describe the bug**

When navigating to https://facebook.github.io/zstd/, I get prompted to select a TLS client certificate for the mcmilk.de domain (which has TLS mutual auth enabled). This seems to be caused by the [image](https://github.com/facebook/zstd/blob/4fdaf56f0590844dfbb6f5601d4654bb49112653/index.html#L248) that's being loaded from that domain. Copying the image to a CDN or directly to the repository hosting the documentation would fix this issue. You can use the GitHub CDN by dragging and dropping the image into a markdown editor on GitHub then copying the URL.

**To Reproduce**
Go to https://facebook.github.io/zstd and see the modal dialog appear. The dialog only seems to appear once, but using an incognito window makes it reappear. I'm using Chrome 94 on macOS Big Sur.

**Expected behavior**
No dialog appears.

**Screenshots and charts**
<img width="810" alt="Screenshot 2021-11-02 at 15 40 21" src="https://user-images.githubusercontent.com/110275/139941186-9fea4b77-91ad-4305-a0fb-825a546f57c0.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 11.6
 - Compiler n/a
 - Flags n/a
 - Other relevant hardware specs n/a
 - Build system n/a

**Additional context**

**Comment by Cyan4973** [comment]
Thanks for the very clear description of the issue @hmarr .

This should be fixed in latest update of [`zstd` homepage](https://facebook.github.io/zstd/).
