### ISSUE TITLE
[Decoding error (36) : Corrupted block detected] zstd file corruption

### ISSUE THREAD

**Issue by hk-lrzy** [facebook/zstd#2852]
**Describe the bug**
We used the zstd compression format, but in the process of using it, we found that the ZSTD compressed file was occasionally damaged. We currently believe that it has been damaged during the process of writing to the disk.

So，we set `debuglevel` to 5, and find all corruption file have same problems, zstd max block size is 131072, but corruption file block size all are 390821.
<img width="1235" alt="截屏2021-11-11 16 14 41" src="https://user-images.githubusercontent.com/14176134/141263412-b71aca42-8d76-405f-a350-7e7637bd1f2e.png">
<img width="1221" alt="截屏2021-11-11 16 15 02" src="https://user-images.githubusercontent.com/14176134/141263426-b2e068f8-08ae-4daf-944f-1844784cb6a2.png">

I want to know how to avoid this problems, thx!!!

**To Reproduce**
1. Downloads data '...'
2. Run '...' with flags '...'
3. Scroll up on the log to '....'

**Expected behavior**

**Screenshots and charts**
If applicable, add screenshots and charts to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Mac]
 - Compiler [e.g gcc]
 - Flags [e.g O2]
 - Other relevant hardware specs [e.g. Dual-core]
 - Build system [e.g. Makefile]

**Additional context**

**Comment by Cyan4973** [comment]
Information is limited.
From the symptoms, it could be a different source of corruption, such as hardware storage.
In which case, `zstd` then just detects the damage, but there's nothing else it can do about it.

**Comment by hk-lrzy** [comment]
I find more detail about this issue.

In a corrupted file, i find `0xFD2FB528` appeared 2 times, first at the beginning, the other in middle of file.
![image](https://user-images.githubusercontent.com/14176134/142829946-2ec8c71f-54dd-431d-97a4-4318f3adc5ce.png)
![image](https://user-images.githubusercontent.com/14176134/142829968-0ab50b30-8b07-4a41-96d7-af3440e3affe.png)

So, does anyone know under what circumstances will cause such a problem?

ZTSD Jni Version: 1.4.4-3

**Comment by Cyan4973** [comment]
Concatenating `zstd` frames is a possibility.
This is "legal" from `zstd` CLI perspective,
but maybe other tools in the ecosystem have more difficulties managing this case ?

**Comment by hk-lrzy** [comment]
> Concatenating `zstd` frames is a possibility. This is "legal" from `zstd` CLI perspective, but maybe other tools in the ecosystem have more difficulties managing this case ?

So, in this case, the block before the second magic number should be marked as last, right? Actually it is not mark as a last block

I split corrupted file into 2 parts according by the second `0xFD2FB528`. before second `0xFD2FB528` part is not completely to decompression，after second `0xFD2FB528` part could be decompression.

i think two frames all could be decompression,right?

**Comment by Cyan4973** [comment]
So this is likely a corrupted stream.
There are too many reasons this could happen.
Hardware could be one way, but I would more likely target the software around the library,
it's very easy to triggers issues around incorrect pointers, unfinished flushing, buffer reuse, unwarranted overwriting, incomplete initialization, etc.
I'm afraid there are too many possibilities to debug effectively from just the elements provided in this issue.

**Comment by hk-lrzy** [comment]
> So this is likely a corrupted stream. There are too many reasons this could happen. Hardware could be one way, but I would more likely target the software around the library, it's very easy to triggers issues around incorrect pointers, unfinished flushing, buffer reuse, unwarranted overwriting, incomplete initialization, etc. I'm afraid there are too many possibilities to debug effectively from just the elements provided in this issue.

I agree with your opinion. I am currently using the following methods to obtain more information, set debuglevel=4, and then observe the writing status of zstd-jni(java). At the same time, I would like to know if there are other ways to avoid such problems, such as detecting the above problems during writing?

**Comment by Cyan4973** [comment]
Collecting traces with `DEBUGLEVEL` presumes that the issue comes from within the library.
If, instead, the issue lies in some code _around_ the library, you'll need different sources of traces.

**Comment by Cyan4973** [comment]
Closing, due to lack of activity
