### ISSUE TITLE
Find Threads module within Android NDK

### ISSUE THREAD

**Issue by AnastaZIuk** [facebook/zstd#2859]
https://github.com/facebook/zstd/blob/v1.5.0/build/cmake/CMakeLists.txt#L123 this one is probably not necessary and forces to workarounds under android ndk build because the Android libc standard library (called "bionic") already includes the relevant functions in `threads.h` and `pthread.h` headers. That support is not yet completely POSIX compliant and differs by API level, but will be sufficient for most cases.

**Comment by terrelln** [comment]
Would disabling multithreading on Android solve the problem for you @AnastaZIuk?

**Comment by felixhandte** [comment]
I believe this issue should be fixed in `dev`.
