### ISSUE TITLE
Why is there no detailed output when multiple files are compressed

### ISSUE THREAD

**Issue by 15596858998** [facebook/zstd#2860]
This is the detailed output of a single file compression：
![image](https://user-images.githubusercontent.com/33825201/141712700-db8a969a-b738-419c-92b3-4097a924390c.png)
![image](https://user-images.githubusercontent.com/33825201/141712744-3e636749-daea-4bf6-b7ae-4460273c753f.png)
This is multiple file compression：
![image](https://user-images.githubusercontent.com/33825201/141712838-ec281115-0db5-4cc1-8bdd-8fb987caae85.png)
Why can't multiple files have detailed information output similar to a single file.
This is what I am looking forward to：
![image](https://user-images.githubusercontent.com/33825201/141713174-ef4c3935-a6b9-4392-8032-6cd4ffca32af.png)

**Comment by Cyan4973** [comment]
1) Which version of `zstd` are you using ?
2) Have you tried option `-v` ?
