### ISSUE TITLE
[build] Reduce code size of zstd_opt.c & decrease build time

### ISSUE THREAD

**Issue by terrelln** [facebook/zstd#2862]
The optimal parser takes up a lot of code size, which also hurts build time. Improve it so we can retain speed while saving code size.

**Comment by crrodriguez** [comment]
It must also be noted that always_inline almost never makes sense in a place other than small, header-only wrappers. It will rarely make you code any better and will certainly make it bigger.

**Comment by terrelln** [comment]
> It must also be noted that always_inline almost never makes sense in a place other than small, header-only wrappers. It will rarely make you code any better and will certainly make it bigger.

@crrodriguez we use always_inline to emulate templates in C. We only use it cases where we expect the function to take one or more compile time constants as parameters, and we want the compiler to hardwire branches & do dead code elimination.
