### ISSUE TITLE
‘-S’ will output the benchmark test results of each file separately, but the result is not

### ISSUE THREAD

**Issue by 15596858998** [facebook/zstd#2870]
‘-S’ will output the benchmark test results of each file separately, but the result is not
![image](https://user-images.githubusercontent.com/33825201/142375047-24b901cb-7511-43ed-a740-ebeae36a837e.png)

**Comment by Cyan4973** [comment]
`-S` is designed to work with the benchmark mode (`-b`) exclusively. 
It has no meaning beyond this context.

Detailed statistics per file is provide by `-v`.
