### ISSUE TITLE
The help file cannot fully include all parameters

### ISSUE THREAD

**Issue by 15596858998** [facebook/zstd#2875]
This is the description provided by the "-h" help manual, but it is not enough.
![截图22](https://user-images.githubusercontent.com/33825201/142996846-4a6eff94-3e03-4ac4-a548-01b90d26fac3.PNG)
We need more help manuals, it is best to include all the code implementation
![image](https://user-images.githubusercontent.com/33825201/142997264-e7aeab7d-3f77-4604-9aa2-6f7a99bd8062.png)

**Comment by Cyan4973** [comment]
`zstd -h` is just a quick summary of the main options.

For a more exhaustive manual, prefer using `man zstd`.
