### ISSUE TITLE
Function parameter symbol type does not match

### ISSUE THREAD

**Issue by 15596858998** [facebook/zstd#2903]
The "size_t" here is unsigned, but the parameter of the "read_bits_LE()" function is signed. Is the usage here not rigorous enough?
![image](https://user-images.githubusercontent.com/33825201/144555236-2ebb0af6-fab8-4606-82e5-86429c907832.png)

**Comment by Cyan4973** [comment]
Yes, a stricter implementation would be explicit in the type casting.

I believe it's code from the educational decoder, which is rather meant to illustrate the spec, not to go into production or ported verbatim to multiple architectures. So the coding standard is mode relaxed here.

**Comment by 15596858998** [comment]
ok
