### ISSUE TITLE
No message is displayed when -T is used to decompress the package.

### ISSUE THREAD

**Issue by 15596858998** [facebook/zstd#2918]
I use the multi-thread function of -T to decompress the file, you can see that the decompression is successful, but we do not support multi-thread decompression, this will cause a misunderstanding to users.
![image](https://user-images.githubusercontent.com/33825201/145392081-502927ea-5321-44da-b16d-516b60ae8fab.png)
I think there's a need to do some processing here.

**Comment by yoniko** [comment]
Thank you for reporting.
Issue was fixed in https://github.com/facebook/zstd/pull/3208.
