### ISSUE TITLE
Windows 1.5.1 pre-release assets still 1.5.0

### ISSUE THREAD

**Issue by orz--** [facebook/zstd#2943]
Windows 1.5.1 pre-release assets still 1.5.0
zstd-v1.5.0-win32.zip
zstd-v1.5.0-win64.zip

**Comment by orz--** [comment]
I'm sorry.
Execute file's version is 1.5.1.
zstd.exe --version
*** zstd command line interface 64-bits v1.5.1, by Yann Collet ***

Just only assets name are 1.5.0.

**Comment by Cyan4973** [comment]
Thanks for the notification @orz-- !
Asset name has been fixed.

**Comment by ghost** [comment]
In [v1.5.1 release page](https://github.com/facebook/zstd/releases/tag/v1.5.1), `Huffman Improvements` section has two "gcc-11	Literal compression - 4KB block", it seems a typo of "clang-13".

**Comment by Cyan4973** [comment]
Yes it is, thanks for the notification @animalize
