### ISSUE TITLE
Dual License is Ambiguous

### ISSUE THREAD

**Issue by hinton-mgi** [facebook/zstd#2945]
README.md does not indicate whether both BSD and GPLv2 must be followed, or if one or the other may be chosen. I understand that it is intended to be the latter, according to issue https://github.com/facebook/zstd/issues/1181 and according to comments at the top of most source files. However there are source files that do not make this indication, e.g. [lib/decompress/huf_decompress_amd64.S](https://github.com/facebook/zstd/blob/dev/lib/decompress/huf_decompress_amd64.S).

Intent is not enough for some. Please edit README.md to make this unambiguous.

**Comment by terrelln** [comment]
We'll fix this in our next release. `lib/decompress/huf_decompress_amd64.S` is intended to have exactly the same license header as our other files in `lib/`.

We have automation to check our licensing, but it doesn't cover `.S` extensions. So we'll have to fix that up.
