### ISSUE TITLE
libs built with executable stack on non amd64 architectures

### ISSUE THREAD

**Issue by pixelb** [facebook/zstd#2963]
Due to the effectively empty huf_decompress_amd64.S on non amd64 architectures,
the empty assembly file is still significant, and causes libs to be built with an executable stack.
This triggers various security issues, most obvious being failure to boot on non x86_64 fedora systems,
due to systemd not loading as it sees the dependent libzstd.so.1 as a security issue (which it is).

There were a few solutions discussed at https://bugzilla.redhat.com/2035802

A possible fix may be just to move the "non executable stack" directive outside the ifdef in the huf_decompress_amd64.S file

**Comment by jpalus** [comment]
You beat me to it by 5 minutes :)

Can confirm that today 2 of my arm 32-bit boards (armv6hl and armv7hnl) did not boot after upgrade of zstd to 1.5.1.

For reference:
```
a5f2c45528032ed20c33e0f8cd2c163a800a0017 is the first bad commit
commit a5f2c45528032ed20c33e0f8cd2c163a800a0017
Author: Nick Terrell <terrelln@fb.com>
Date:   Fri Sep 17 11:43:04 2021 -0700

    Huffman ASM
```
