### ISSUE TITLE
compiling on macOS12 targeting macOS10.15

### ISSUE THREAD

**Issue by sl1200mk2** [facebook/zstd#2979]
Hi,
not sure if it's really a bug though... but when I compile latest code on macOS12 targeting macOS10.15, the linker is not happy about huf_decompress_amd64.S.o

here's my cmake line:
cmake -G "Unix Makefiles" .. -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/opt/local -DCMAKE_INSTALL_PREFIX:PATH=/opt/local -DCMAKE_C_FLAGS="-O2" -DCMAKE_MACOSX_RPATH=On -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15

and here's the result:
-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ZSTD VERSION: 1.5.1
-- Performing Test CXX_FLAG_STD_CPLUSPLUS11
-- Performing Test CXX_FLAG_STD_CPLUSPLUS11 - Success
-- Performing Test C_FLAG_STD_C99
-- Performing Test C_FLAG_STD_C99 - Success
-- Performing Test C_FLAG_WALL
-- Performing Test C_FLAG_WALL - Success
-- Performing Test CXX_FLAG_WALL
-- Performing Test CXX_FLAG_WALL - Success
-- Performing Test C_FLAG_WEXTRA
-- Performing Test C_FLAG_WEXTRA - Success
-- Performing Test CXX_FLAG_WEXTRA
-- Performing Test CXX_FLAG_WEXTRA - Success
-- Performing Test C_FLAG_WUNDEF
-- Performing Test C_FLAG_WUNDEF - Success
-- Performing Test CXX_FLAG_WUNDEF
-- Performing Test CXX_FLAG_WUNDEF - Success
-- Performing Test C_FLAG_WSHADOW
-- Performing Test C_FLAG_WSHADOW - Success
-- Performing Test CXX_FLAG_WSHADOW
-- Performing Test CXX_FLAG_WSHADOW - Success
-- Performing Test C_FLAG_WCAST_ALIGN
-- Performing Test C_FLAG_WCAST_ALIGN - Success
-- Performing Test CXX_FLAG_WCAST_ALIGN
-- Performing Test CXX_FLAG_WCAST_ALIGN - Success
-- Performing Test C_FLAG_WCAST_QUAL
-- Performing Test C_FLAG_WCAST_QUAL - Success
-- Performing Test CXX_FLAG_WCAST_QUAL
-- Performing Test CXX_FLAG_WCAST_QUAL - Success
-- Performing Test C_FLAG_WSTRICT_PROTOTYPES
-- Performing Test C_FLAG_WSTRICT_PROTOTYPES - Success
-- CMAKE_INSTALL_PREFIX: /opt/local
-- CMAKE_INSTALL_LIBDIR: lib
-- ZSTD_LEGACY_SUPPORT not defined!
-- ZSTD_MULTITHREAD_SUPPORT is enabled
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- The ASM compiler identification is Clang
-- Found assembler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/nico/Downloads/zstd-dev/build/cmake/build
nico@love build % make -j 6
Scanning dependencies of target zstdless.1
Scanning dependencies of target zstd.1
Scanning dependencies of target zstdgrep.1
Scanning dependencies of target libzstd_static
Scanning dependencies of target libzstd_shared
[  3%] Copying manpage zstd.1
[  3%] Copying manpage zstdless.1
[  3%] Copying manpage zstdgrep.1
[  3%] Built target zstdless.1
[  3%] Built target zstdgrep.1
[  3%] Built target zstd.1
Scanning dependencies of target zstdcat.1
Scanning dependencies of target unzstd.1
[  5%] Creating unzstd.1 symlink
[  5%] Creating zstdcat.1 symlink
[  5%] Built target zstdcat.1
[  5%] Built target unzstd.1
[  9%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/common/entropy_common.c.o
[  9%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/common/entropy_common.c.o
[  9%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/common/debug.c.o
[ 10%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/common/debug.c.o
[ 11%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/common/error_private.c.o
[ 12%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/common/error_private.c.o
[ 15%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/common/fse_decompress.c.o
[ 15%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/common/fse_decompress.c.o
[ 16%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/common/pool.c.o
[ 17%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/common/pool.c.o
[ 20%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/common/xxhash.c.o
[ 20%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/common/threading.c.o
[ 21%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/common/zstd_common.c.o
[ 22%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/common/threading.c.o
[ 23%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/common/xxhash.c.o
[ 24%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/compress/fse_compress.c.o
[ 25%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/common/zstd_common.c.o
[ 27%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/compress/fse_compress.c.o
[ 29%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/compress/hist.c.o
[ 29%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/compress/hist.c.o
[ 30%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/compress/huf_compress.c.o
[ 31%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/compress/huf_compress.c.o
[ 32%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/compress/zstd_compress.c.o
[ 34%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/compress/zstd_compress.c.o
[ 35%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/compress/zstd_compress_literals.c.o
[ 36%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/compress/zstd_compress_literals.c.o
[ 37%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/compress/zstd_compress_sequences.c.o
[ 38%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/compress/zstd_compress_sequences.c.o
[ 40%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/compress/zstd_compress_superblock.c.o
[ 41%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/compress/zstd_double_fast.c.o
[ 42%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/compress/zstd_compress_superblock.c.o
[ 43%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/compress/zstd_fast.c.o
[ 44%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/compress/zstd_double_fast.c.o
[ 45%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/compress/zstd_lazy.c.o
[ 47%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/compress/zstd_ldm.c.o
[ 48%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/compress/zstd_fast.c.o
[ 49%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/compress/zstd_lazy.c.o
[ 50%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/compress/zstd_ldm.c.o
[ 51%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/compress/zstd_opt.c.o
[ 52%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/compress/zstd_opt.c.o
[ 54%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/compress/zstdmt_compress.c.o
[ 55%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/compress/zstdmt_compress.c.o
[ 56%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/decompress/huf_decompress.c.o
[ 57%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/decompress/huf_decompress.c.o
[ 58%] Building ASM object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/decompress/huf_decompress_amd64.S.o
[ 60%] Building ASM object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/decompress/huf_decompress_amd64.S.o
[ 61%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/decompress/zstd_ddict.c.o
[ 62%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/decompress/zstd_ddict.c.o
[ 63%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/decompress/zstd_decompress.c.o
[ 64%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/decompress/zstd_decompress.c.o
[ 65%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/decompress/zstd_decompress_block.c.o
[ 67%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/dictBuilder/cover.c.o
[ 68%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/decompress/zstd_decompress_block.c.o
[ 69%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/dictBuilder/divsufsort.c.o
[ 70%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/dictBuilder/fastcover.c.o
[ 71%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/dictBuilder/cover.c.o
[ 72%] Building C object lib/CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/dictBuilder/zdict.c.o
[ 74%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/dictBuilder/divsufsort.c.o
[ 75%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/dictBuilder/fastcover.c.o
[ 76%] Building C object lib/CMakeFiles/libzstd_static.dir/Users/nico/Downloads/zstd-dev/lib/dictBuilder/zdict.c.o
[ 77%] Linking C static library libzstd.a
[ 77%] Built target libzstd_static
Scanning dependencies of target zstd-frugal
Scanning dependencies of target zstd
[ 78%] Building C object programs/CMakeFiles/zstd-frugal.dir/Users/nico/Downloads/zstd-dev/programs/fileio.c.o
[ 81%] Building C object programs/CMakeFiles/zstd-frugal.dir/Users/nico/Downloads/zstd-dev/programs/util.c.o
[ 81%] Building C object programs/CMakeFiles/zstd-frugal.dir/Users/nico/Downloads/zstd-dev/programs/zstdcli.c.o
[ 82%] Building C object programs/CMakeFiles/zstd-frugal.dir/Users/nico/Downloads/zstd-dev/programs/timefn.c.o
[ 83%] Building C object programs/CMakeFiles/zstd.dir/Users/nico/Downloads/zstd-dev/programs/zstdcli.c.o
[ 84%] Building C object programs/CMakeFiles/zstd.dir/Users/nico/Downloads/zstd-dev/programs/util.c.o
[ 85%] Building C object programs/CMakeFiles/zstd.dir/Users/nico/Downloads/zstd-dev/programs/timefn.c.o
[ 87%] Building C object programs/CMakeFiles/zstd.dir/Users/nico/Downloads/zstd-dev/programs/fileio.c.o
[ 88%] Building C object programs/CMakeFiles/zstd.dir/Users/nico/Downloads/zstd-dev/programs/benchfn.c.o
[ 89%] Linking C shared library libzstd.dylib
ld: warning: object file (CMakeFiles/libzstd_shared.dir/Users/nico/Downloads/zstd-dev/lib/decompress/huf_decompress_amd64.S.o) was built for newer macOS version (12.0) than being linked (10.15)
[ 90%] Building C object programs/CMakeFiles/zstd.dir/Users/nico/Downloads/zstd-dev/programs/benchzstd.c.o
[ 90%] Built target libzstd_shared
[ 91%] Building C object programs/CMakeFiles/zstd.dir/Users/nico/Downloads/zstd-dev/programs/datagen.c.o
[ 92%] Building C object programs/CMakeFiles/zstd.dir/Users/nico/Downloads/zstd-dev/programs/dibio.c.o
[ 94%] Building C object programs/CMakeFiles/zstd.dir/Users/nico/Downloads/zstd-dev/programs/zstdcli_trace.c.o
[ 95%] Linking C executable zstd-frugal
ld: warning: object file (../lib/libzstd.a(huf_decompress_amd64.S.o)) was built for newer macOS version (12.0) than being linked (10.15)
[ 95%] Built target zstd-frugal
[ 96%] Linking C executable zstd
ld: warning: object file (../lib/libzstd.a(huf_decompress_amd64.S.o)) was built for newer macOS version (12.0) than being linked (10.15)
[ 96%] Built target zstd
Scanning dependencies of target zstdcat
Scanning dependencies of target zstdmt
Scanning dependencies of target unzstd
[ 98%] Creating zstdmt symlink
[ 98%] Creating zstdcat symlink
[100%] Creating unzstd symlink
[100%] Built target zstdcat
[100%] Built target unzstd
[100%] Built target zstdmt

best regards,
nicolas

**Comment by sl1200mk2** [comment]
Hi,
same message from the linker with the latest code.

++

**Comment by terrelln** [comment]
Can you try removing the cmake build directory and rebuilding?

**Comment by sl1200mk2** [comment]
Hi,
I'm starting each time from a fresh clone, and so recreate the build directory.

++

**Comment by terrelln** [comment]
To clarify, the build is still working, just emitting this warning message, correct?

We'll still want to fix it either way.

**Comment by sl1200mk2** [comment]
yes, that's it

**Comment by sl1200mk2** [comment]
Hi,
same error with zstd 1.5.2

++

**Comment by terrelln** [comment]
Are you still running into this issue? We haven't been able to reproduce it locally.

**Comment by sl1200mk2** [comment]
Hi,
no it's ok now.
thanks you for your great work.

++
