### ISSUE TITLE
Request to Add Xilinx Zstd Hardware solution reference in zstd docs

### ISSUE THREAD

**Issue by heeran-xilinx** [facebook/zstd#2988]
**Describe the bug**
Can you please add Xilinx zstd solution under hardware section of zstd documentation page  here : http://facebook.github.io/zstd/

Xilinx has implemented ZSTD Compression and Decompression on Xilinx FPGA devices and targetted Xilinx Alveo Platform. It is part of Xilinx Vitis Data Compression Library. 
Top page: https://github.com/Xilinx/Vitis_Libraries/blob/master/data_compression/README.rst (fixed)
Zstd compression path (dynamic, can change in future): https://github.com/Xilinx/Vitis_Libraries/tree/master/data_compression/L2/tests/zstd_quadcore_compress
Zstd Decompression path (dynamic, can change in future): https://github.com/Xilinx/Vitis_Libraries/tree/master/data_compression/L2/tests/zstdd_32KB

**To Reproduce**
Go to following page and see Xilinx ZSTD solutions:
Top page: https://github.com/Xilinx/Vitis_Libraries/blob/master/data_compression/README.rst (fixed)
https://github.com/Xilinx/Vitis_Libraries/tree/master/data_compression/L2/tests/zstd_quadcore_compress
https://github.com/Xilinx/Vitis_Libraries/tree/master/data_compression/L2/tests/zstdd_32KB
these are hardware solution and our recommendation is to include this reference in zstd documentation page under hardware. 

**Expected behavior**
User should  see the Xilinx Hardware ZSTD solution reference in ZSTD documentation page.

**Comment by Cyan4973** [comment]
Thanks for the notification @heeran-xilinx,

Xilinx FPGA reference has been added to the homepage.

**Comment by heeran-xilinx** [comment]
Thanks @Cyan4973
