### ISSUE TITLE
Explanation Ratio 

### ISSUE THREAD

**Issue by JcJinChen** [facebook/zstd#2996]
**Describe the bug**
I am confused about the ratio mentioned in the table, is it the ratio before and after compression?Can someone help with this?Thanks!

**Comment by JcJinChen** [comment]
what i learned, the compress ratio usually means the ratio of compressed to uncompressed.

**Comment by ghost** [comment]
It's `uncompressed_size / compressed_size`.

**Comment by JcJinChen** [comment]
Thank you so much
