### ISSUE TITLE
Windows release 1.5.1 doesn't contains pre-release files

### ISSUE THREAD

**Issue by seladb** [facebook/zstd#3001]
**Describe the bug**
In Windows release 1.5.1, both `zstd-v1.5.1-win32.zip` and `zstd-v1.5.1-win64.zip` contains only the `.exe` file and not the lib/dll and header files. How can I get the pre-release files for this release?
Previous releases did contain these files.

**To Reproduce**
1. Downloads  `zstd-v1.5.1-win32.zip` and `zstd-v1.5.1-win64.zip`
2. It contains only the `.exe` file

**Expected behavior**
Previous release included pre-release files also

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.5.1

**Comment by felixhandte** [comment]
Zstd 1.5.2 is out, with corrected artifacts.
