### ISSUE TITLE
pzstd --long: Invalid argument: --long

### ISSUE THREAD

**Issue by ole-tange** [facebook/zstd#3002]
**Describe the bug**
pzstd does not support --long

**To Reproduce**
~~~
$ seq 10 | ./pzstd --long 
Invalid argument: --long
~~~

**Expected behavior**
Run pzstd with --long

**Screenshots and charts**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: 1.5.2
 - Compiler: gcc
 - Flags: default
 - Other relevant hardware specs: 64 core
 - Build system: Makefile

**Additional context**
N/A

**Comment by Cyan4973** [comment]
This isn't planned. 
We would rather prefer bringing `pzstd` capabilities within `zstd`,
Also, `--long` is in direct opposition with `pzstd` principles of cutting input into independent blocks.
