### ISSUE TITLE
Windows builds of 1.5.1 are missing lots of files and folders

### ISSUE THREAD

**Issue by JoeUX** [facebook/zstd#3012]
The Windows builds for 1.5.1 are mostly empty, missing all files and folders except for a single executable. There's no `Readme.md`, and the usual `dll`, `example`, `include`, and `static` folders are missing.

All prior Windows releases have those contents, and the non-Windows release of 1.5.1 has that and more (I think it's entire repo). The files I'm talking about are:

- https://github.com/facebook/zstd/releases/download/v1.5.1/zstd-v1.5.1-win64.zip (missing most content, 544 KB)
- https://github.com/facebook/zstd/releases/download/v1.5.1/zstd-1.5.1.tar.zst (normal, 1.41 MB)

**Comment by felixhandte** [comment]
@JoeUX, I have *just* released v1.5.2, which (among other things) should have the right windows artifacts attached.

Unfortunately, these artifacts are still manually tweaked and attached to the release, which introduces opportunities for error. This is something we want to improve in the future. Thanks for the report!

**Comment by niheaven** [comment]
@felixhandte Will the package content of zstd windows release be changed in the future? As an end user, the single-exe package is more friendly, and it makes maintain package manager, e.g. Scoop, easier to track the update. Or would you release a single-exe package plus a dev package w/ DLLs and headers? Thanks!
