### ISSUE TITLE
How to use --fast=1 with API ?

### ISSUE THREAD

**Issue by hehechen** [facebook/zstd#3028]
https://github.com/facebook/zstd/blob/cc7d23bcec14525d7752f597d09c1377b982d050/programs/zstdcli.c#L1042
It seems that the compression level in `--fast=X` is `-X`? So if I want to compress some data in C program with `--fast=1`, I just use the `ZSTD_compress` simple API and set the last function parameter `compressionLevel` with `-1`?

**Comment by Cyan4973** [comment]
> It seems that the compression level in `--fast=X` is `-X`? So if I want to compress some data in C program with `--fast=1`, I just use the `ZSTD_compress` simple API and set the last function parameter `compressionLevel` with `-1`?

Yes
