### ISSUE TITLE
Decompress legacy stream with `ZSTD_decompressStream`

### ISSUE THREAD

**Issue by gyscos** [facebook/zstd#303]
Currently, the new `ZSTD_decompressStream` API only accept 0.8 frame format.
Indeed, in the `case zdss_loadHeader` of the `switch`, it calls `ZSTD_getFrameParams` which expects the new frame format.

All this with `ZSTD_LEGACY_SUPPORT=1`.

I realize the API itself it new, but I believe it should still be compatible with legacy frames?

**Comment by Cyan4973** [comment]
Yes, that's correct.

In v0.8.1, `ZSTD_decompressStream()` has the same scope as `ZBUFF_decompressContinue()`,
which means it doesn't handle legacy formats. It's also listed in the "experimental" section, which doesn't provide any guarantee regarding _automatic_ decoding of legacy formats.

(note : manually routing legacy formats into appropriate `ZBUFFv0x_*` API works and is possible. That's the way the command line utility works. See [`programs/legacy/fileio_legacy.c`](https://github.com/Cyan4973/zstd/blob/master/programs/legacy/fileio_legacy.c). )

In the next release, the intention is to upgrade `ZSTD_compressStream()` from "experimental" to "stable". At which stage, it will have to handle legacy formats automatically.

**Comment by gyscos** [comment]
It's now in the master branch, thanks!
