### ISSUE TITLE
Negative compression levels

### ISSUE THREAD

**Issue by hwogit** [facebook/zstd#3032]
What does it mean when ZSTD_minCLevel() returns -131072? I would expect there is a gapless range between the minimum and maximum compression levels. Currently, I support the range of 0 to 22 because I don't know how to interpret the negative levels. The user can select a number from a dropdown list. Could he (theoretically) also select any value between 0 and -131072?

**Comment by Cyan4973** [comment]
> Could he (theoretically) also select any value between 0 and -131072?

Yes

**Comment by Cyan4973** [comment]
In practice, especially if you use a dropdown list,
one should not bother with largely negative values.
One could either completely ignore negative values,
or cap accessible values to >= -5.
This would be our recommendation, as the speed/compression trade-off worsens after this threshold.

**Comment by hwogit** [comment]
Thank you
