### ISSUE TITLE
zstd-v1.5.2-win64.zip does not contains libzstd.lib

### ISSUE THREAD

**Issue by theloy84** [facebook/zstd#3049]
zstd-v1.5.2-win64.zip does not contains libzstd.lib

**Comment by felixhandte** [comment]
I see `zstd-v1.5.2-win64/static/libzstd_static.lib`. Is that not what you're looking for?

**Comment by egrochow** [comment]
libzstd_static.lib is for static linking not dynamic linking AFAIK.|

However, there is a libzstd.dll.a 
This is in effect libzstd.lib.  I renamed the .a to .lib and it worked. 
You can verify this using dumpbin too.
