### ISSUE TITLE
ZSTD_compress returns it's input

### ISSUE THREAD

**Issue by jogardi** [facebook/zstd#3065]
**Describe the bug**
The ZSTD_compress function just copies the src to the dst. This is an issue specific to my machine. I can't reproduce it on another mac laptop. 

**To Reproduce**
Put this code in ex.cc:
```
#include <zstd.h>
#include <fstream>

int main()
{
	std::ifstream input("ex.cc", std::fstream::in | std::fstream::ate);
	const size_t inputSize = input.tellg();
	input.seekg(0);
	char* inputBuffer = new char[inputSize];
	input.read(inputBuffer, inputSize);
	const size_t approxCompressSize = ZSTD_compressBound(inputSize);
	char* compressBuffer = new char[approxCompressSize];
	const size_t compressSize = ZSTD_compress(compressBuffer, approxCompressSize, inputBuffer, inputSize, 22);

    std::ofstream out("out.zst", std::fstream::out);
    out.write(compressBuffer, compressSize);

	return 0;
}
```
Compile and run with 
```
clang++ -lzstd ex.cc -o out
./out
```
The output in out.zst should be compressed but it is just a copy of the input. 

**Expected behavior**
The expected behavior is for out.zst to contain the compressed data. I get 56% compression with the zstd executable command line tool.

**Desktop (please complete the following information):**
 - OS: Mac
 - Version 11.4
 - Compiler clang++
 - Build system: cloned the repository and did make install. The installation worked without issue.

**Comment by Cyan4973** [comment]
> The ZSTD_compress function just copies the src to the dst

This is not supposed to be possible.

Even assuming that input is incompressible, `ZSTD_compress()`'s contract requires it to generate frames respecting the `zstandard` specification. Therefore, while content might be stored in uncompressed format, the frame will still feature `zstandard` headers and markers, and possibly checksum, so it's not an "exact copy" of original.

> This is an issue specific to my machine. I can't reproduce it on another mac laptop.

So this is weird, and considering the previous comment, it hints at a possibility that, for some reason, `ZSTD_compress()` symbol _on your system_ is an entry point towards  _something else_ , not the "regular" `libzstd` symbol.
Worth checking.

**Comment by jogardi** [comment]
i deleted the zstd library i had installed. Then as expected recompiling gave me an error about missing the zstd library. Then I did brew reinstall zstd. Then I recompiled and still got the same issue. I also get the same issue with the streaming api and with g++ rather than clang. But it does work in a docker container on my machine. 

Yes this is weird.

**Comment by Cyan4973** [comment]
Could it be an issue with `brew` package ?
This is weird, I would expect such an issue to have large repercussions, given how popular this package manager is.

Another potential test could be
to uninstall the `brew` package of `zstd`,
and instead, `make install` directly from source.
Just to see if it makes a difference.

Another possibility could be an error in the script, which would write the input instead of the output.
But I don't see this error in the provided script in the first post.

**Comment by jogardi** [comment]
i already tried that. If maximum compression was my concern I would have to use it in a docker container. But in this case I'm just using zlib and that works. So I am closing this issue.
