### ISSUE TITLE
Library bloat (with ZSTD_LIB_MINIFY=1) since v1.5.1

### ISSUE THREAD

**Issue by hchunhui** [facebook/zstd#3066]
**Describe the bug**
Build zstd with `ZSTD_LIB_MINIFY=1`, the size of `libzstd.a` is increased since v1.5.1.

**To Reproduce**
```sh
git clone https://github.com/facebook/zstd
cd zstd

# build recent version (or v1.5.1/v1.5.2)
make -C lib ZSTD_LIB_MINIFY=1 libzstd.a
du -h lib/libzstd.a   # shows 604K

# build v1.5.0
make clean
git checkout v1.5.0
make -C lib ZSTD_LIB_MINIFY=1 libzstd.a
du -h lib/libzstd.a   # shows 328K
```

**Expected behavior**
The size of `libzstd.a` should be ~330K. The first bad commit is 8bf699aa59372d7c2bb4216bcf8037cab7dae51e.

**Desktop (please complete the following information):**
 - OS: Debian amd64
 - Version: 11.2
 - Compiler: gcc-10
 - Flags: ZSTD_LIB_MINIFY=1
 - Build system: Makefile

**Comment by terrelln** [comment]
Thanks for reporting the issue @hchunhui! Should be fixed after PR #3366 gets merged, and will be included in our next release.
