### ISSUE TITLE
ZSTD_NbCommonBytes implementation is incorrect for Big-Endian MSVC

### ISSUE THREAD

**Issue by embg** [facebook/zstd#3067]
[These](https://github.com/facebook/zstd/blob/970460f67d8641f38d4954683e95887d97d3e388/lib/compress/zstd_compress_internal.h#L761) [lines](https://github.com/facebook/zstd/blob/970460f67d8641f38d4954683e95887d97d3e388/lib/compress/zstd_compress_internal.h#L782) should be changed to `(r ^ 63) >> 3` and  `(r ^ 31) >> 3`, respectively. I found the bug while adding tests for bitwise intrinsics in https://github.com/facebook/zstd/pull/3045. That PR fixes the bug (as well as removing the Big-Endian MSVC specific code, which is probably not used by anyone).

**Comment by Cyan4973** [comment]
> [These](https://github.com/facebook/zstd/blob/970460f67d8641f38d4954683e95887d97d3e388/lib/compress/zstd_compress_internal.h#L761) [lines](https://github.com/facebook/zstd/blob/970460f67d8641f38d4954683e95887d97d3e388/lib/compress/zstd_compress_internal.h#L782) should be changed to `(r ^ 63) >> 3`

- `(r ^ 63)` or `(r & 63)` ?
- Is that even possible for `r` to return a larger value (than 63) ?
- If not, but we don't want to trust `_BitScanReverse ()` for some reason, could this condition be just `assert()` ?

**Comment by embg** [comment]
@Cyan4973  The XOR translates an index from LSB (which we get from `_BitScanReverse()`) into an index from MSB. See [here](https://github.com/facebook/zstd/blob/970460f67d8641f38d4954683e95887d97d3e388/lib/common/zstd_internal.h#L369-L373) for an example in `ZSTD_highbit32()` (which is where I learned this trick from).

**Comment by Cyan4973** [comment]
> The XOR translates an index from LSB (which we get from `_BitScanReverse()`) into an index from MSB

Good point!
What about `(63 - r)` then ?

**Comment by embg** [comment]
@Cyan4973 I just favored `(r ^ 63)` to stay closer to the original code (the ZSTD_highbit32 implementation) and reduce the chance of introducing a performance regression in the refactor. If you think we can go to `(63 - r)` without hurting performance I'm happy to go that direction (this only affects Win32 so it's difficult for me to measure the performance impact directly).

**Comment by Cyan4973** [comment]
It's probably equivalent.
I don't think it matters much to be that "close to the edge" for this code.
I'm rather advocating for code readability, so that less reviewer(s) wonder "what is this code doing ?".

**Comment by embg** [comment]
Sounds good, will update my PR.

**Comment by embg** [comment]
> @Cyan4973 I just favored `(r ^ 63)` to stay closer to the original code (the ZSTD_highbit32 implementation) and reduce the chance of introducing a performance regression in the refactor. If you think we can go to `(63 - r)` without hurting performance I'm happy to go that direction (this only affects Win32 so it's difficult for me to measure the performance impact directly).

Correction: this actually affects performance across the board, not just Win32, because of ZSTD_hightbit32. I will benchmark on gcc to make sure switching away from XOR doesn't regress performance.
