### ISSUE TITLE
spec: Does Block_Maximum_Size apply for RAW/RLE blocks?

### ISSUE THREAD

**Issue by klauspost** [facebook/zstd#3072]
**Describe the bug**

While fuzz testing my Go port, I came across this input that I can decompress, but cli cannot.

The input has an RLE block of 1572321 bytes. The cli fails with `Destination buffer is too small` and extended error is `check regenSize > dstCapacity failed, returning ERROR(dstSize_tooSmall)`.

Reading [spec](https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md#blocks) I want to confirm my (new) reading is correct;

Does the `Block_Size is limited by Block_Maximum_Size (see below)` mean that no matter the block type, the limit of Window Size/128KB applies? I kind of read/assumed that other types could use up to the 21 bits available.

**Comment by Cyan4973** [comment]
Indeed,
the `Block_Maximum_Size` is applicable to all block types, including RLE and RAW.

**Comment by klauspost** [comment]
Thanks. Just wanted to confirm before adding the restriction locally.
