### ISSUE TITLE
--rsyncable make compression much slower

### ISSUE THREAD

**Issue by hansmid** [facebook/zstd#3097]
```
# time /usr/local/bin/zstd -1 -T0 -o test2.zst vmbackup.img
vmbackup.img : 64.20%   (   164 GiB =>    105 GiB, test2.zst)

real    6m54.581s
user    19m55.084s
sys     8m57.265s

# time /usr/local/bin/zstd -1 -T0 --rsyncable -o test3.zst vmbackup.img
vmbackup.img : 64.21%   (   164 GiB =>    105 GiB, test3.zst)

real    9m40.283s
user    23m50.710s
sys     6m36.879s

# /usr/local/bin/zstd --version
*** zstd command line interface 64-bits v1.5.2, by Yann Collet ***
```
Zstd with --rsyncable is approximately 40% slower than without, is that expected behaviour? I can't find any comments on this in changelog or man page.

**Comment by Cyan4973** [comment]
`--rsyncable` adds a serial stage to the pipeline, so yes, it does add some processing requirement.

Moreover `-1 -T0` is a pretty fast baseline, so the relative importance of this stage is maximized under this setting.

For example, on my test system, the `--rsyncable` stage adds ~0.4sec / GB to total processing time.
This is relatively fast and almost negligible when using compression parameter `-7 -T1` for example, but such a cost represents a much larger portion compared to `-1 -T0`.
