### ISSUE TITLE
zstd vs lz4 

### ISSUE THREAD

**Issue by qingqingfeiwu** [facebook/zstd#3098]
Hi, I tested ZSTD , LZ4 and LZO-RLE on our phone. When we use the default level(3) for comparison tests. The ZSTD decompressed speed much more slowly than LZ4and LZO-RLE.   Is there a level setting of ZSTD that has better compression ratio and decompression speed than LZ4?  Thank you!

**Comment by Cyan4973** [comment]
`LZ4` always decompresses faster. There's a lot less work to do for LZ4 decompression.

**Comment by qingqingfeiwu** [comment]
Thank you for your explanation!   Sorry , I have another question.  Is there a level setting of ZSTD that has better compression ratio and decompression speed than LZO-RLE ?  Thanks

**Comment by Cyan4973** [comment]
I don't know much about `LZO-RLE`. Some sources describe it as a "faster `lzo` variant". Might be, but `lzo` was not particularly fast when it comes to decompression speed, so I would expect both `lz4` and `zstd` to remain (much) faster at decompression speed.

Therefore, my guess is that `zstd` level 1 is a good enough match for `lzo-rle`. It certainly compresses more, and likely decompresses faster, though mileage could vary depending on exact workload and platform.

**Comment by qingqingfeiwu** [comment]
Thank you very much!
