### ISSUE TITLE
zstd -l should print out the dictionary ID

### ISSUE THREAD

**Issue by bouk** [facebook/zstd#3099]
```
$ zstd --version
*** zstd command line interface 64-bits v1.5.2, by Yann Collet ***
```

Currently the output of zstd looks something like this:

```
Frames  Skips  Compressed  Uncompressed  Ratio  Check  Filename
     1      0     162   B       267   B  1.648  XXH64  ./test.zst
```

It would be useful if the dictionary ID (if present) was also printed

**Comment by mraddatz** [comment]
@bouk that is the output of exactly which command? With which flags? I have been compressing and decompressing without seeing this type of output.

**Comment by bouk** [comment]
`zstd -l <file>`

**Comment by felixhandte** [comment]
#3184 fixes this (with `--verbose`).
