### ISSUE TITLE
Possible typo in Operation modifiers section of man page of v1.5.2

### ISSUE THREAD

**Issue by southwindcg** [facebook/zstd#3101]
The --long[=#]: bullet point contains a phrase that I believe contains an error.

> --long[=#]:  enables  long  distance matching with # windowLog, **if not # is not present** it defaults to 27.

I believe this should read "if no # is present" or "if # is not present"...

**Comment by Cyan4973** [comment]
Yes, indeed, good point, and good fix suggestion.
