### ISSUE TITLE
Missing change-log entry for 1.4.10 release

### ISSUE THREAD

**Issue by paulmenzel** [facebook/zstd#3107]
Version 1.4.10 was tagged, but I am unable to find an entry in the file [`CHANGELOG`](https://github.com/facebook/zstd/blob/v1.4.10/CHANGELOG).

**Comment by Cyan4973** [comment]
`v1.4.10` is a special tag, created for synchronization with the Linux Kernel community, and corresponds to the state of the software at latest Linux Kernel update.

But it's not a "release". `zstd` `v1.4.10` was never released. Hence no trace in the `CHANGELOG`.

**Comment by paulmenzel** [comment]
Thanks, maybe that could be added to `CHANGELOG`? Anyway, thanks for clearing this up. (Debian [packaged that version now][1].)

[1]: https://metadata.ftp-master.debian.org/changelogs//main/libz/libzstd/libzstd_1.4.10+dfsg-1_changelog
