### ISSUE TITLE
Train large number of files for dictionary

### ISSUE THREAD

**Issue by greensea** [facebook/zstd#3115]
**Is your feature request related to a problem? Please describe.**
I am traning dictionary from large number of files ( ~2M files), using the command:
`zstd --train train_dataset/*`
And got an error:
```
zsh: argument list too long: zstd
```

**Describe the solution you'd like**
If I can specify the train dataset with a directory like this
`zstd --train train_dataset/`
Then the argument list limit is not a problem anymore.

**Comment by felixhandte** [comment]
You can use `-r` to find files recursively. So `zstd --train -r train_dataset/` should work.

You also shouldn't need that many samples for training. It's going to be very slow.
