### ISSUE TITLE
Cirrus CI infra failure (FreeBSD test)

### ISSUE THREAD

**Issue by embg** [facebook/zstd#3124]
There seems to be an infra failure with one of the Cirrus CI tests. [Example job](https://cirrus-ci.com/task/5680139374690304). I will take a look next week.

```
pkg install -y gmake coreutils
Updating FreeBSD repository catalogue...
pkg: http://pkg.FreeBSD.org/FreeBSD:11:amd64/latest/meta.txz: Not Found
repository FreeBSD has no meta file, using default settings
pkg: http://pkg.FreeBSD.org/FreeBSD:11:amd64/latest/packagesite.txz: Not Found
Unable to update repository FreeBSD
Error updating repositories!
Exit status: 3
```

**Comment by koobs** [comment]
@embg FreeBSD 11.x is now EoL (and has been a while) [1], it wouldn't surprise me if the packages have been taken down.

You'll want to update cirrus to use 13.x releases and packages.

```
+image_family: freebsd-13-0
image_family: freebsd-12-2
-# The stable 11.3 image causes "Agent is not responding" so use a snapshot
- image_family: freebsd-11-3-snap
```

Note: 13.1-RELEASE is imminent, so you'll want to update to `freebsd-13-1` when its out

[1] https://www.freebsd.org/security/unsupported/
