### ISSUE TITLE
Generating dictionary hangs on loading files

### ISSUE THREAD

**Issue by PMunch** [facebook/zstd#3130]
**Describe the bug**
When trying to train a dictionary with the CLI tool it simply hangs forever

**To Reproduce**
1. Split normal dmesg log into one line per file
2. Run `zstd` with flags `--train  -r data/ -o zstddict`
3. See "Loading data/<semi-random file>" which never goes away

**Expected behavior**
Expected `zstd` command to complete after having read all the files and created a dictionary

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 5.17.1
 - Compiler: Unknown, probably GCC
 - Flags: Unknown, installed through package manager

**Comment by PMunch** [comment]
It appears that the issue is caused by having a completely empty file in the set of files (as generated by e.g. `touch`) the file it hangs on loading isn't the empty file, but possibly the last file it managed to load or the file it tries to open after the empty one.

**Comment by michael-grunder** [comment]
I encountered similar behavior and found it to be fixed in newer versions.  I think the relevant commit is da737c7ab89f61f1ea7c392299137f6ffe6f9733.
