### ISSUE TITLE
Streaming decompression of data in a vector

### ISSUE THREAD

**Issue by bertox94** [facebook/zstd#3132]
I need to do the following procedure.
1. Compress an input text into an array.
2. Split the compressed output into multiple pieces with approx. the same length and store them in a vector.
3. Decompress using streaming decompression.

Is it possible to do that?
Consider that in my case, the size of each block is fixed and independent of the compression scheme.

Thanks,
Alberto

**Comment by terrelln** [comment]
Yes, see the [streaming compression API](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L611), and and the [streaming compression](https://github.com/facebook/zstd/blob/dev/examples/streaming_compression.c) and [streaming decompression](https://github.com/facebook/zstd/blob/dev/examples/streaming_decompression.c) examples.

**Comment by terrelln** [comment]
Yes, see the [streaming compression API](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L611), and and the [streaming compression](https://github.com/facebook/zstd/blob/dev/examples/streaming_compression.c) and [streaming decompression](https://github.com/facebook/zstd/blob/dev/examples/streaming_decompression.c) examples.
