### ISSUE TITLE
Contrib build fails on riscv64 hardware

### ISSUE THREAD

**Issue by Madouura** [facebook/zstd#3134]
**Describe the bug**
We get a linker error in pzstd specifically, when building on riscv64 hardware. (StarFive VisionFive)

**To Reproduce**
See https://github.com/NixOS/nixpkgs/blob/634141959076a8ab69ca2cca0f266852256d79ee/pkgs/tools/compression/zstd/default.nix for specific build information.

**Expected behavior**
pzstd should correctly link.

**Desktop (please complete the following information):**
 - OS: [NixOS (Linux)]
 - Version [22.05 (master)]
 - Compiler [gcc (11.3.0)]
 - Flags [O2 (Should be default for nix build system IIRC)]
 - Other relevant hardware specs [Dual-core, RISC-V 64-bit]
 - Build system [Cmake]

**Additional context**
Error log: https://gist.github.com/Madouura/a3fd7780a069d6def34a0e57469fe095

**Comment by embg** [comment]
Could you modify [this logic](https://github.com/NixOS/nixpkgs/blob/634141959076a8ab69ca2cca0f266852256d79ee/pkgs/tools/compression/zstd/default.nix#L45) to add `-DCMAKE_BUILD_TYPE=Debug` and share that build output?

**Comment by Madouura** [comment]
https://gist.github.com/Madouura/01bac15373b6569af269176095ffb120

**Comment by embg** [comment]
I did some research and it seems like lots of people are having link errors with C++11 atomics on RISC-V. Adding `--as-needed -latomic` to CFLAGS and CXXFLAGS should solve the problem. Can you try this and let me know if it works?

Sources:
https://github.com/riscv-collab/riscv-gcc/issues/12 and linked PRs
https://gitlab.kitware.com/cmake/cmake/-/issues/20895
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81358

**Comment by Madouura** [comment]
Unfortunately, it did not work. https://github.com/Madouura/nixpkgs/commit/01699f4cfe6bb74c8bbb2201ed9f540dd1c78798
Same error as before.

**Comment by embg** [comment]
Shoot. Can you check that you're compiling with C++11?

**Comment by Madouura** [comment]
```console
-- Performing Test CXX_FLAG_STD_CPLUSPLUS11
-- Performing Test CXX_FLAG_STD_CPLUSPLUS11 - Success
```
Is there something else specific I should be looking for? Nothing regarding which version of C++ we're compiling with is specified in the nix package.

**Comment by embg** [comment]
Not sure, sorry! Assigning this to @terrelln

**Comment by Madouura** [comment]
See https://github.com/NixOS/nixpkgs/pull/180028 for a fix.

**Comment by kallisti5** [comment]
@Madouura was the fix here for NixOS ever pushed upstream to zstd?

**Comment by Madouura** [comment]
> @Madouura was the fix here for NixOS ever pushed upstream to zstd?

It was just adding ``-latomic`` to ``LDFLAGS``, so I doubt it.
