### ISSUE TITLE
Documentation issue in repeat offset table

### ISSUE THREAD

**Issue by dkcasset** [facebook/zstd#3142]
**Describe the bug**
(Documentation). In doc/zstd_compression_format.md, the table that shows the values of the Repeated_Offsets:
- The last row shows Repeated_Offset3 having a value of 3333 (changed from previous row value of 1111)
- It seems the correct value would be 1111

**To Reproduce**
1. NA

**Expected behavior**
NA

**Screenshots and charts**
If applicable, add screenshots and charts to help explain your problem.
NA

**Desktop (please complete the following information):**
NA

**Additional context**
NA

**Comment by Cyan4973** [comment]
You are right @dkcasset, the example contains a mistake. To be fixed.
