### ISSUE TITLE
How can I use the function ZSTDLIB_STATIC_API unsigned long long ZSTD_findDecompressedSize(const void* src, size_t srcSize)?

### ISSUE THREAD

**Issue by NOTRp** [facebook/zstd#3149]
How can I use the function ZSTDLIB_STATIC_API unsigned long long ZSTD_findDecompressedSize(const void* src, size_t srcSize)?
I use  the static library with "cmake -DZSTD_MULTITHREAD_SUPPORT=ON -DZSTD_BUILD_TESTS=ON -DZSTD_ZSTD_BUILD_STATIC=ON -DZSTD_LEGACY_SUPPORT=ON ..  && make". But, when I build my project , it show me that "error: ‘ZSTD_findDecompressedSize’ was not declared in this scope"

thanks!

**Comment by Cyan4973** [comment]
It looks like a more fundamental build + linking stage issue, 
so the `zstd` code base, and the symbol you are trying to link to in particular, are unlikely participants to this problem.

Unfortunately, such issues are also quite specific to your build setup.

**Comment by ghost** [comment]
add `-DZSTD_STATIC_LINKING_ONLY` should solve it.

**Comment by Cyan4973** [comment]
Good point @animalize !
This symbol is indeed part of the non-stable API,
and therefore requires `ZSTD_STATIC_LINKING_ONLY` to be set.
Maybe that's all there is ...
