### ISSUE TITLE
Destination buffer is too small

### ISSUE THREAD

**Issue by kkishoreyadav** [facebook/zstd#3176]
Error occurs during decompress  com.github.luben.zstd.ZstdException: Destination buffer is too small |	at com.github.luben.zstd.ZstdDecompressCtx.decompressByteArray(ZstdDecompressCtx.java:157) |	at com.github.luben.zstd.ZstdDecompressCtx.decompress(ZstdDecompressCtx.java:214) |	at com.github.luben.zstd.ZstdDecompressCtx.decompress(ZstdDecompressCtx.java:219) |
at com.snapchat.ab.exposure.util.compression.ZstdCompressorImpl.decompress(ZstdCompressorImpl.java:144) |	at com.snapchat.ab.exposure.util.compression.ZstdCompressorImpl.decompressBitMap(ZstdCompressorImpl.java:163) |	at 

Is the error saying the byte data has more bytes than the original size 

byte[] data = context.decompress(compressedData.getCompressedBytes(),
          compressedData.getOriginalSize());

1) We are using gradle depedendency as com.github.luben:zstd-jni:1.4.5-6

Appendix
public class ZstdCompressorImpl implements Compressor {
  private final int currentDictionaryVersion = 0;
  private final Map<Integer, byte[]> versionToZstdDictionaryMap;
  // Determined by local profiling results. Provides 22% more compression with negligible increase in latency
  // Default is 3 and max is 19. 19 provides slightly better compression but latency 30x
  private final Map<Integer, Integer> zstdVersionToCompressionLevelMap =
      ImmutableMap.of(0, 10);
  private ThreadLocal<Map<Integer, ZstdCompressCtx>> versionToCompressCtxMapThreadLocal;
  private ThreadLocal<Map<Integer, ZstdDecompressCtx>> versionToDecompressCtxMapThreadLocal;
  private final double checksumSamplingRate;

  private final MetricsClient metrics;

  private static final Logger LOGGER = LoggerFactory
          .getLogger(ZstdCompressorImpl.class.getName());

  @Inject
  public ZstdCompressorImpl(MetricsClient metrics) throws IOException {
    //TODO Move this to fetch the value from SnapConfig
    this(1.0, metrics);
  }

  public ZstdCompressorImpl(double checksumSamplingRate, MetricsClient metrics) throws IOException {
    this.metrics = metrics;

    final String dictionaryUrlAsStr = IOUtils.toString(ZstdCompressorImpl.class.
            getResourceAsStream("/zstdRoaringBitmapDictionary_0"));

    versionToZstdDictionaryMap = ImmutableMap.of(0, dictionaryUrlAsStr.getBytes(StandardCharsets.UTF_8));
    versionToCompressCtxMapThreadLocal = ThreadLocal.withInitial(() -> {
      ZstdCompressCtx context =
          new ZstdCompressCtx().loadDict(versionToZstdDictionaryMap.get(0))
              .setLevel(zstdVersionToCompressionLevelMap.get(0));
      context.setFinalize(true);
      return ImmutableMap.of(0, context);
    });
    versionToDecompressCtxMapThreadLocal = ThreadLocal.withInitial(() -> {
      ZstdDecompressCtx context = new ZstdDecompressCtx()
          .loadDict(versionToZstdDictionaryMap.get(0));
      context.setFinalize(true);
      return ImmutableMap.of(0, context);
    });
    this.checksumSamplingRate = checksumSamplingRate;
  }

  @VisibleForTesting
  String calculateCheckSum(byte[] data) throws NoSuchAlgorithmException {
    if (ThreadLocalRandom.current().nextDouble() >= checksumSamplingRate) {
      return null;
    }
    MessageDigest md = MessageDigest.getInstance("MD5");
    md.update(data);
    return DatatypeConverter.printHexBinary(md.digest()).toUpperCase();
  }

  private CompressedData compress(byte[] data) {
    Stopwatch stopwatch = Stopwatch.createStarted();
    try {
      ZstdCompressCtx context =
          versionToCompressCtxMapThreadLocal.get().get(currentDictionaryVersion);
      byte[] compressedBytes = context.compress(data);
      CompressedData compressedData = new CompressedData.Builder()
          .compressedBytes(compressedBytes)
          .originalSize(data.length)
              .dictionaryVersion(currentDictionaryVersion)
          .checksum(calculateCheckSum(data))
          .build();
      metrics.time("ZstdCompressorImpl.compress.latencyUs",
              stopwatch, TimeUnit.MICROSECONDS);
      return compressedData;
    } catch (Exception ex) {
      metrics.count("ZstdCompressorImpl.compress.ExceptionType." +
              ex.getCause().getClass().getSimpleName(), 1);
      metrics.time("ZstdCompressorImpl.compress.exception.latencyUs",
              stopwatch, TimeUnit.MICROSECONDS);
      LOGGER.error("Error occurs during compress ", ex);
      throw new RuntimeException(ex);
    }
  }

  @Override
  public CompressedData compressBitmap(RoaringBitmap roaringBitmap) {
    Stopwatch stopwatch = Stopwatch.createStarted();
    long startTime = System.currentTimeMillis();
    try {
      ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
      DataOutputStream dataOutputStream = new DataOutputStream(byteArrayOutputStream);
      roaringBitmap.serialize(dataOutputStream);
      dataOutputStream.flush();
      byteArrayOutputStream.flush();
      metrics.time("ZstdCompressorImpl.compressBitmap.latencyUs",
              stopwatch, TimeUnit.MICROSECONDS);
      return compress(byteArrayOutputStream.toByteArray());
    } catch (Exception ex) {
      String metricxPrefix = "ZstdCompressorImpl.compressBitmap";
      MetricsUtil.emitExceptionCountAndLatency(metrics, ex, metricxPrefix, startTime);
      metrics.count(metricxPrefix + ".error" , 1);
      throw new RuntimeException(ex);
    }
  }

  private byte[] decompress(CompressedData compressedData) {
    Stopwatch stopwatch = Stopwatch.createStarted();
    long startTime = System.currentTimeMillis();
    try {
      int dictionaryVersion =
          compressedData.getDictionaryVersion();
      ZstdDecompressCtx context =
          versionToDecompressCtxMapThreadLocal.get().get(dictionaryVersion);
      Preconditions.checkArgument(context != null);
      byte[] data = context.decompress(compressedData.getCompressedBytes(),
          compressedData.getOriginalSize());
      String checksum = calculateCheckSum(data);
      Preconditions.checkArgument(Objects.equals(checksum, compressedData.getChecksum()));
      metrics.time("ZstdCompressorImpl.decompress.exception.latencyUs",
              stopwatch, TimeUnit.MICROSECONDS);
      return data;
    } catch (Exception ex) {
      String metricxPrefix = "ZstdCompressorImpl.decompress";
      MetricsUtil.emitExceptionCountAndLatency(metrics, ex, metricxPrefix, startTime);
      metrics.count(metricxPrefix + ".error" , 1);
      LOGGER.error("Error occurs during decompress ", ex);
      throw new RuntimeException(ex);
    }
  }

  @Override
  public RoaringBitmap decompressBitMap(CompressedData compressedData) throws IOException {
    Stopwatch stopwatch = Stopwatch.createStarted();
    byte[] bytes = decompress(compressedData);
    ByteBuffer byteBuffer = ByteBuffer.wrap(bytes);
    RoaringBitmap roaringBitmap = new RoaringBitmap();
    roaringBitmap.deserialize(byteBuffer);
    metrics.time("ZstdCompressorImpl.decompressBitMap.latencyUs",
            stopwatch, TimeUnit.MICROSECONDS);
    r

**Comment by felixhandte** [comment]
Hi @kkishoreyadav,

It's difficult to analyze what's going wrong here.

This failure is almost certainly the result of user error: you are likely incorrectly transporting the output of compression to the decompressor somehow. I'm not really in a position to debug what specifically is going wrong, since, (1) that's not really a minimal reproducer of your issue, (2) it's in Java, (3) you are using a third-party wrapper layer to interact with Zstd.

The one suspicious thing I see here is that you're calling `context.decompress(compressedData.getCompressedBytes(), compressedData.getOriginalSize());`. I don't know how the Java wrapper works but in the underlying C implementation we expect you to pass in `const void* src, size_t srcSize`, i.e., the *compressed* size, not the *original, uncompressed* size.

**Comment by ghost** [comment]
IMO, this is an usage problem of Java wrapper, you may ask in https://github.com/luben/zstd-jni/issues.
