### ISSUE TITLE
[Question] What's the difference between ZSTD_decompressDCtx and ZSTD_decompressStream

### ISSUE THREAD

**Issue by xiaoyong-z** [facebook/zstd#3178]
What's the difference between ZSTD_decompressDCtx and ZSTD_decompressStream? 
Under what circumstances should I use ZSTD_decompressDCtx? 
And under what circumstances should I use ZSTD_decompressStream?

**Comment by xiaoyong-z** [comment]
which one's performance is better?

**Comment by xiaoyong-z** [comment]
In my scenario, in some cases I will decompress the entire block directly, in other cases i will decompress the streaming data piece by piece.

**Comment by Cyan4973** [comment]
It's recommended to employ `ZSTD_decompressDCtx()` whenever possible.
This variant is leaner, simpler and slightly faster than the streaming variant.

However, `ZSTD_decompressDCtx()` can only work on full-buffer scenarios,
i.e. the entire compressed frame must be present in memory within a single continuous buffer,
and the resulting decompressed content will be generated into a single pre-allocated continuous buffer.
These restrictions are generally fine for small content,
but become more difficult as content becomes larger.

In which case, use `ZSTD_decompressStream()`. It's a strict superset.
Whatever `ZSTD_decompressDCtx()` does, `ZSTD_decompressStream()` can do too.
And it can also receive input in multiple separated segments, and generate output progressively into multiple consecutive buffers.
However, it employs more resources to do so, is slightly slower, and its API is a bit more difficult to use.
So this is intended for more "advanced" use cases.
