### ISSUE TITLE
Zstd support of multithreading and multicpu support

### ISSUE THREAD

**Issue by wanfuse123** [facebook/zstd#3183]
Hi! I understand this is possible now, is it possible to set it system wide MULTITHREADING AND MULTICORE support using compile options?

If so is there compile directions for doing this?

Lastly will this work on Linux?

I would like to work this with zswap and zram together getting LZ4 or LZ4HC compression to get around system ram limitations.

Also, I might look for a ram drive and add it to that since this should be six times faster than SSD's but thats for a little later on.

Thanks in advance!

**Comment by yoniko** [comment]
Hi @wanfuse123 ,
Please see https://github.com/facebook/zstd/tree/dev/lib#multithreading-support regarding compilation options required for multithreading support in the library.
It should work on linux as long as the `pthread` lib is available.

**Comment by wanfuse123** [comment]
will this work with zcache, zram and zswap. I am told it might not multithread even though I have installed it as a kernel module because the kernel will not support multithreading. Anything special I have to do to get it to multithread? or is this not possible?
See my code so far here:  https://github.com/wanfuse123/zram-zswap-with-parallelized-compression-using-facebook-zlib
