### ISSUE TITLE
"sweetspot" of --rsyncable option?

### ISSUE THREAD

**Issue by JsBergbau** [facebook/zstd#3191]
I've compressed database backups with zstd and `--rsyncable` option. I've then used restic to store these files. Restic detects identical blocks and deduplicates them, similar as rsync would not transfer these blocks via network. 

The resulting table

| ZSTD Level | compresed size | in restic |  
|------------|------------|-----------|
|      1      |   84.9 GB         |    31.34 GB       |   
|       2     |       76.3 GB    |     32.72  GB    |   
|       3     |       71.1 GB     |    35.45 GB       |   
|      4      |        70.9 GB    |     35.73 GB      |   
|     5       |      65.5 GB      |        33.36 GB   |   
|      6     |    62.4 GB        |   31.70 GB        |   
|        7     |     61.5 GB       |      31.11 GB     |   
|       8     |      58.1 GB      |     29.48 GB      |   
|      9      |    54.0 GB        |    31.56 GB       |   
|       10     |    53.6 GB        |      31.35 GB     |   
|     11       |   53.3 GB         |       31.81 GB    |   
|       12     |    53.3 GB        |       31.99 GB    |   
|    13        |     53.0 GB       |       31.68 GB    |   
|      14      |     52.8 GB       |         31.52 GB  |   
|       15     |   52.2 GB         |      30.56 GB     |   
|       16     |       49.7 GB     |      29.22 GB     |   
|       17     |        45.5 GB    |    33.12 GB       |   
|       18     |  45.1 GB          |      32.60 GB     |   
|       19     |       41.8 GB     |    31.26 GB       |   

As you can see there are some levels which deduplicate better than others. Level 16 seems to make the best job for deduplication.

Is this result which level deduplicates better than others highly dependent on the input data or is there some "sweetspot" like Level 16 in this case for most of the data? Maybe someone with more knowlege to the algorithm can tell more.

More info on the test here https://github.com/restic/restic/issues/3821

**Comment by terrelln** [comment]
There isn't a sweet spot w.r.t the level. Higher levels will compress better, and I think levels 8 and 16 is just getting the best by chance.

The parameter you can tune is `-B` for the job size. This will affect how large of a block that we will de-dup. E.g. you could try `-B512KB`, or `-B4MB`.

**Comment by JsBergbau** [comment]
Thanks for the hint. 
I've tried `-B512KB`. This lead to a siginificant longer time it took to compress the files. 

Complete results

ZSTD Level | -B parameter  | compressed size |   in restic
----|----|----|----|
16 | 512KB | 57.9 GB | 24.18 GB
16 | 4MB | 65.5 GB | 24.61 GB
16 |default (as above)| 49.7GB | 29.22 GB

Using deduplication of restic and internal (zstd) compression of these blocks/chunks leads to 23.83 GB with default compression level and only 20.37 GB with maximum compression level.

**Comment by terrelln** [comment]
I'm closing out this issue, but please re-open if you have any further questions!
