### ISSUE TITLE
Can change license from  BSD and GPLv2 to MIT or something else，just like react？

### ISSUE THREAD

**Issue by winxblast** [facebook/zstd#3192]
I holp to use this powerful algorithm in my work，but because of this license，our company forbid us to use。

**Comment by felixhandte** [comment]
What part of the BSD license is a problem for you that wouldn't be with an MIT license? The MIT license is *very* similar.

**Comment by winxblast** [comment]
thanks，I am asking the lawyer of company，I have to follow his advice
