### ISSUE TITLE
Is there a way to not have all the training samples in memory for building the dictionary?

### ISSUE THREAD

**Issue by m-nagarajan** [facebook/zstd#3198]
Hi team,

I am trying to use 2GB of training samples to build the dictionary but the system only has 256MB of RAM. Trying to see if there is a way to build this dictionary in this 256MB system? Currently only way I can think of is to load all the 2GB of data into memory and build the dictionary. Is there a way we can do streaming build where not all the sample is in memory at any time?

Thanks,
Manoj

**Comment by felixhandte** [comment]
We don't currently support that. It's unlikely you need so much training data, though. You'll find rapidly diminishing returns as you increase the number of samples provided to the trainer past 10MB of data or so. Could you select a subset (randomly?) of your data that would be representative of the overall corpus?

**Comment by m-nagarajan** [comment]
Thanks @felixhandte for the reply. The diminishing returns after 10MB or so applies even if the original data is in multiple TBs? 
As per my understanding, the more the sample, the more the possibility of finding more frequent Bytes to be made an efficient dictionary.

**Comment by felixhandte** [comment]
Well it all depends on the nature of your data.

I'd recommend trying to train dictionaries on, for example, 1MB, 10MB, and 100MB of your data, and then benchmarking how much each of those improves compression for the dataset. If your data is fairly homogeneous, I would expect those dictionaries to perform equivalently well.

**Comment by m-nagarajan** [comment]
thanks @felixhandte, Let me experiment on it.

Closing the ticket.
