### ISSUE TITLE
plans for packaging on different platforms (package manager integration)

### ISSUE THREAD

**Issue by benaryorg** [facebook/zstd#320]
Are there any plans on getting zstd into the main package manager repositories of various (or all if possible) platforms?
Is there a list for this already?

A list of platforms includes (but is not limited to):
- GNU/Linux
  - debian derived
    - [x] *buntu (aptitude)
      - [package](http://packages.ubuntu.com/search?keywords=zstd) (xenial : 0.5.1-1 (outdated) ; yakkety : 0.8.0-1 (compatible) ; zesty : 1.1.2-1 (current) )
    - [x] Debian (aptitude)
      - [package](https://packages.debian.org/sid/utils/zstd) (testing&unstable)
  - Red Hat
    - [x] Fedora&Red Hat Enterprise Linux
      - [package](https://admin.fedoraproject.org/pkgdb/package/rpms/zstd/)
  - SUSE
    - [x] OpenSUSE (zypper)
      - [package](https://build.opensuse.org/package/show/Archiving/zstd)
  - other
    - [x] Gentoo (portage)
      - [package](https://packages.gentoo.org/packages/app-arch/zstd) (~amd64&~x86)
    - [x] Alpine
      - [package](https://pkgs.alpinelinux.org/packages?name=zstd)
    - [x] Arch Linux
      - [package](https://www.archlinux.org/packages/community/x86_64/zstd/)
- Unix&BSD
  - [x] FreeBSD&DragonFlyBSD
    - [package](https://github.com/bsd-hacker/freebsd-ports/tree/master/archivers/zstd)
  - [x] OpenBSD
    - [package](http://openports.se/archivers/zstd)
  - [x] NetBSD
    - [package](http://pkgsrc.se/archivers/zstd)
  - [x] OSX (brew)
    - [package](http://brewformulas.org/zstd)
- Windows
  - [x] Windows (some MSI thing and plain exes)
  - [x] MSYS2
  - [ ] Cygwin

**Comment by nabijaczleweli** [comment]
What about MSYS2 for WIndooze?

**Comment by benaryorg** [comment]
Ah, right, sorry, I had them in mind at the time I started writung but somehow forgot about them.

**Comment by benaryorg** [comment]
Also note that (at least for some people) to really provide both, MSI and simple plain exe/dll builds for Windows.

**Comment by tomByrer** [comment]
I like the idea, but the builder/output repo does not need to be part of *this* repo.  Eg another repo could provide the source for the builder.

**Comment by tomByrer** [comment]
/@benaryorg could you add JavaScript via [Enscripten](https://github.com/kripken/emscripten) please?

**Comment by benaryorg** [comment]
This would belong to a "port" of the algorithm, I was thinking about the compilation and packaging of the binaries that the code in this repository produces **already** when running `make`.

These binaries just need to be wrapped in a deb, rpm, or whatever and uploaded somewhere. This definitely belongs to this repository as the "builder" would be something like *travis*, *buildbot* or one of the dozen others that are available, some of them also self-hosted, I don't really know how facebook hanyles this.

For the *BSD ports or Gentoo parts (actually every source distro) there would probably only be the need to find a (trusted) maintainer.

**Comment by Cyan4973** [comment]
For debian, there is this package : 
https://packages.debian.org/sid/utils/zstd

though I don't know if it means `apt-get` works out of the box,
need access to relevant VM to test.

These objectives are pretty good,
I just have little idea how to automate them.
If there is an entry point to look at, I'm willing to investigate.

**Comment by benaryorg** [comment]
Well, this repository already uses [travis](https://travis-ci.org/facebook/zstd) and has a very detailed [configuration](https://github.com/facebook/zstd/blob/master/.travis.yml) for that so that could be used to package the files needed.

I haven't ever tried to get something into the official repositories ever and don't have experience with the process so you might want to ask someone who was involved in that. Probably asking in the mailinglists for those OSes and distros could even bring up a maintainer or two.

**Comment by juanfra684** [comment]
I'm an OpenBSD developer. I'm working on an official package.

**Comment by benaryorg** [comment]
> I'm an OpenBSD developer. I'm working on an official package.

Pkg, ports, or both?

Also, if you finish that package, will that affect the other BSDs?

**Comment by juanfra684** [comment]
@benaryorg On OpenBSD, the ports are just a tool to build packages.

My work will not affect to other BSDs. Anyway, if zstd works fine on OpenBSD, probably will work also on other BSDs.

**Comment by intdel** [comment]
I tried to email the Debian maintainer for zstd, but he uses a spam@ email address, so I didn't even bother. Not sure what the point is of being a maintainer if one cannot contact you.

**Comment by pixelb** [comment]
Fedora package review at https://bugzilla.redhat.com/1373218

**Comment by benaryorg** [comment]
I'll add it as WIP.

**Comment by gyscos** [comment]
Archlinux has had a [zstd package](https://aur.archlinux.org/packages/zstd) for a while, if you want to include it.

**Comment by benaryorg** [comment]
I added and checked Arch. Did someone check whether the Debian package works?

**Comment by Cyan4973** [comment]
A Gentoo package by Patrick Lauer is announced here : 
https://packages.gentoo.org/packages/app-arch/zstd

**Comment by benaryorg** [comment]
I can confirm the Gentoo package compiles and runs.

**Comment by benaryorg** [comment]
Can anyone confirm the debian package works and is at least 1.0.0?

**Comment by intdel** [comment]
https://packages.debian.org/search?searchon=names&keywords=zstd

Doesn't look like that there is even one at the moment. If I can find time soon, I'll try to build a debian package.

**Comment by benaryorg** [comment]
Okay so whatever [this Debian package](https://packages.debian.org/sid/utils/zstd) is, it's possible to install it but.… well:

```text
$ zstd --version
*** zstd command line interface 64-bits v0.8.0, by Yann Collet ***
```

**Comment by Cyan4973** [comment]
Good news is : v0.8.0 is fully compatible with v1.

Anyway, @kdmurray91 seems to be working on next Debian release : 
https://qa.debian.org/cgi-bin/vcswatch?package=libzstd

**Comment by kdmurray91** [comment]
@benaryorg: As @Cyan4973 says,  a Debian package for 1.0.0 is in progress. The package has to make it through the Debian peer review process again, as there are new binary packages and copyright changes. 

Please remember that most Debian folks (including myself) are volunteers, and things might not happen instantly :smile:.

**Comment by intdel** [comment]
@kdmurray91 I wanted to contact you via email first to get an update etc. (didn't know you are on Github!), but on the Debian package website you provided a spam@whatever email address. Are you actually able to receive email on that address?

**Comment by kdmurray91** [comment]
@intdel Yep, I do, thought it gets heavily filtered for spam.

**Comment by kdmurray91** [comment]
Just letting you all know that the 1.0.0 package was accepted into Debian Sid. All going well, it will be in testing in a week or so. That means that it will make it into the next stable release of Debian (and Ubuntu and friends).

**Comment by Cyan4973** [comment]
There seems to be a FreeBSD version, by @jrmarino : 
https://github.com/bsd-hacker/freebsd-ports/tree/master/archivers/zstd

**Comment by benaryorg** [comment]
> *** zstd command line interface 64-bits v1.0.0, by Yann Collet ***

zstd in FreeBSD seems to be up to date and working.

**Comment by jrmarino** [comment]
On FreeBSD "ports" and "packages" are not separate.  All ports that are buildable also have packages generated from those ports (assuming it is legal to distribute them as binary packages).

So there's no port in having two checkboxs.  You can do what you did for OpenBSD and put "ports and packages"

by the way, the bullets are messed up.  It shows openbsd under freebsd right now.

**Comment by benaryorg** [comment]
@jrmarino Thanks for the heads up.

**Comment by juanfra684** [comment]
@benaryorg zstd is now an official OpenBSD package. The command to install the package is `pkg_add zstd` and the unofficial web to browse the packages list is: http://openports.se/archivers/zstd.

**Comment by jrmarino** [comment]
netbsd has had zstd for 2-3 weeks already: http://pkgsrc.se/archivers/zstd

**Comment by jrmarino** [comment]
oh, and "FreeBSD" also includes "DragonFly" (meaning they share the same ports system so both of them have zstd)

**Comment by benaryorg** [comment]
Okay, I just added a few links and checked some boxes.

Does anybody have an idea why Ubuntu is so far behind?

Also, is there *anybody* who know about Windows' status?

**Comment by jrmarino** [comment]
Another "by the way", NetBSD has it through pkgsrc, which means actually many platforms have it, most notably Illumos, but also some Linux distributions use pkgsrc and technically it's an alternative system for FreeBSD, DragonFly and OpenBSD.

here's a list that I hope is up to date: https://www.netbsd.org/docs/pkgsrc/introduction.html#supported-platforms

**Comment by benaryorg** [comment]
I see Cygwin there, that might be worth trying to get to work.

Not saying that the others aren't worth too, but Cygwin is already in the "mainstream OSes" list.

**Comment by jforberg** [comment]
I made an Arch Linux package about a year ago when Zstandard was first published and have been maintaining it since. However, it's in the AUR/unsupported section which requires compiling from source. I don't know the process to get it into the supported/binary section as I have no official standing within the Arch project.

**Comment by pixelb** [comment]
I was asked to add pzstd to the fedora package and was wondering how supported this variant is at present and how long term it might be. I.E. might its functionality be incorporated into the main util at some stage, thus best not making the util widely available?

**Comment by benaryorg** [comment]
Status Report on Thursday 2016-10-06 (UTC, somewhen very early):

All of the currently checked platforms these have 1.1:
- Fedora
- Gentoo
- Arch Linux
- FreeBSD&DragonFlyBSD
- OpenBSD
- NetBSD

Except Debian which is still at 1.0.

Ubuntu is just weird with having a package but being way outdated (0.5 on xenial, 0.8 on yakkety), although Ubuntu usually has newer packages.…

Alpine and SUSE still don't have anything or at least we don't know anything.

Red Hat Enterprise Linux takes packages from Fedora if I got that right?

Nobody on GitHub seems to care for Windows (or maybe just nobody who found this issue).


A lot of people here did nice work, if noone else, at least I am going to appreciate that. Thank you!

**Comment by jforberg** [comment]
The Arch Linux package was moved to the official repositories yesterday.

https://www.archlinux.org/packages/community/x86_64/zstd/

**Comment by Cyan4973** [comment]
Not sure if it's related : 
http://beta.repology.org/package/zstd.html

**Comment by pixelb** [comment]
In the Red Hat section you could say RHEL and CentOS are now available through EPEL.
I.E. you can use the same package link as used for Fedora for a RHEL/CentOS entry

**Comment by inikep** [comment]
Please check `Windows` as official Windows binaries compiled with MinGW/MSYS2 are available for zstd v0.8 and newer:
https://github.com/facebook/zstd/releases

**Comment by Cyan4973** [comment]
Alpine Linux proposes zstd v1.1.1 :  
https://pkgs.alpinelinux.org/packages?name=zstd

**Comment by Cyan4973** [comment]
Looks like OpenSUSE also has a package now :
https://build.opensuse.org/package/show/Archiving/zstd

**Comment by benaryorg** [comment]
I think this issue can be closed by now.
If a distro (looking at you Debian Stable) gets stuck on an old version an issue should be opened on their issue tracker I think.
After all, the initial "creating a package and finding a maintainer"-task is done.

Anyone disagree?

**Comment by Cyan4973** [comment]
Sounds fair 👍

**Comment by rolando** [comment]
I'm not sure where to post this and just to let you know, [conda-forge](https://conda-forge.github.io/) has published packages for `zstd`, for linux and osx , in the near future there will be packages for windows too.

Packages and installation instructions can be found here: https://anaconda.org/conda-forge/zstd

**Comment by Cyan4973** [comment]
Great news @rolando !
For information, as I see on https://anaconda.org/conda-forge/zstd : "License: Unspecified"
the license is BSD

**Comment by rolando** [comment]
@Cyan4973 probably the license is a temporary anaconda.org issue. The recipe has the correct license value https://github.com/conda-forge/zstd-feedstock#about-zstd
