### ISSUE TITLE
Request for ZSTD to be available in NGINX

### ISSUE THREAD

**Issue by CoderJoeW** [facebook/zstd#3207]
This is related to an old and closed issue here
https://github.com/facebook/zstd/issues/409

We need ZSTD to be available in NGINX by default. I don't know what needs to happen to get it there but GZIP should no longer be the de facto standard for web compression/decompression its gotta be ZSTD and the only way mass adoption is gonna happen is if its available by default in nginx

**Comment by tansy** [comment]
As you referred to that issue/409 you probably realise that it's been done. I mean the module. You also need to implement the support in browsers and have the compression be actually better and/or faster and/or less memory hungry.

At level 3, which is default, it's going to be faster, that's for sure but is it better compressor (I mean ratio)? With standard DuckDuckGo search (<16kB uncompressed) is not, with inner html (60-90kB), which, I suppose, is generated on client's side, is not. with Gogle search, which is huge in that comparison (400-500kB) is better by <1kB. Similar result on random news websites - gzip and zstd ratio are marginally different.
Both of them are far worse than brotli that both these search engines "extensively" use.

And the last one is memory. From my test zstd uses between 5.125-6.01MiB, depending on size of input, I guess. 3-3.5 MiB of this goes to client, I presume from decompression test - 3.62+window-size [MiB] to be more precise. How many times more it is in comparison to gzip? With thousands of concurrent clients you will start to add up, especially if the process won't fit in processor cache.

**Comment by felixhandte** [comment]
@CoderJoeW, I agree! This would be great.

I think this is not the right forum to discuss default-inclusion in nginx. It looks like they ask for this to be discussed on their [mailing list](http://nginx.org/en/docs/contributing_changes.html).

As @tansy notes, we're in a bit of a chicken-or-the-egg situation. Browsers are reluctant to add support until there's a wide base of server support, and vice-a-versa. But advocating in appropriate fora helps drive awareness and hopefully momentum!

**Comment by tansy** [comment]
> As @tansy notes, we're in a bit of a chicken-or-the-egg situation

I think I had been misunderstood.
From issue/409 referred by @[CoderJoeW](https://github.com/CoderJoeW)  it appears that problem is already solved. Module with zstd support is done.

Reluctance, you mention comes from qualities of zstd, that is indeed faster, but that's about it. It's not better than gzip at compression level 3 and is just as memory hungry as brotli. So advantages seem to fade. At least technical ones.
