### ISSUE TITLE
windows download for version 1.0

### ISSUE THREAD

**Issue by anjanb** [facebook/zstd#321]
Need a windows binary for version 1.0 and ongoing. 
thank you.

**Comment by nabijaczleweli** [comment]
Build it yourself, you need just a non-ancient C compiler

**Comment by anjanb** [comment]
Hi there,

  thank you.

  I can do for myself since I'm a developer.

I thought that there are countless people who don't have compiler but have
a computer and a need to compress/decompress. Are you going to ask them to
compile it by themselves ? It helps all those people to download a
legitimate copy of zstd -- instead of virus makers targetting the
popularity of zstd and releasing viruses ridden version of zstd soon.

thoughts ?

thank you,

BR,
~A

**Comment by KrzysFR** [comment]
If you don't want to have to open Visual Studio, but have the required SDKs installed on your dev box (msdbuild & MSVC compiler) you can use the build scripts under `/projects/build` to produce both x86 and x64 binaries (exe and dll) for various versions of the MS VC Runtime

See https://github.com/facebook/zstd/blob/master/projects/build/README.md for details.

**Comment by Cyan4973** [comment]
There are now pre-compiled zstd binaries in the [release](https://github.com/facebook/zstd/releases) section for v1.0,
prepared by @inikep .

**Comment by albertdb** [comment]
Thanks. [Node.js interface](https://www.npmjs.com/package/node-zstandard) has been updated to use them.
