### ISSUE TITLE
--target-compressed-block-size produces corrupted file

### ISSUE THREAD

**Issue by tansy** [facebook/zstd#3212]
**Describe the bug**

For some reason I wanted to "split" input into blocks and couldn't find an option for it. I expected it to be `-B`, like in lz4, lizard or lzip, but it wasn't an option. I found this option: `--target-compressed-block-size`, which I expected to be some, close alternative, compressed some files and during testing they all turned out to be corrupt.
Below you have a script that works every single time.
I don't exactly understand this option as there is nothing in man and little in help but it should produce some kind of correct output.
Also it seems to not accept values above 262144.

```
ARC="zstd-dev.tar"

OPTS="--target-compressed-block-size=1024 --maxdict=1024"
$ ./zstd $OPTS -c $ARC &gt; $ARC.zst
$ ./zstd -t zstd-dev.tar.zst
zstd-dev.tar.zst     : 7.08 MiB...     zstd-dev.tar.zst : Decoding error (36) : Corrupted block detected

OPTS="--target-compressed-block-size=1024"
$ ./zstd $OPTS -c $ARC &gt; $ARC.zst
$ ./zstd -t zstd-dev.tar.zst
zstd-dev.tar.zst : Decoding error (36) : Data corruption detected

OPTS="--target-compressed-block-size=1024KB"
$ ./zstd $OPTS -c $ARC &gt; $ARC.zst
zstd: error 11 : Parameter is out of bound

OPTS="--target-compressed-block-size=1048576"
$ ./zstd $OPTS -c $ARC &gt; $ARC.zst
zstd: error 11 : Parameter is out of bound
```
**To Reproduce**
Explained above.

**Expected behavior**
To produce correct output.
To accept input values within claimed bounds including accepting suffixes (KB, etc.) and if out of limits provide those limits in man/help/error message.

**Desktop (please complete the following information):**
 - OS: linux
 - Compiler: gcc
 - Flags: default
 - Build system: default (Makefile)

**Comment by terrelln** [comment]
Thanks for the report, I was able to reproduce it. We'll work on fixing the bug, and figuring out why our fuzzers aren't catching the issue for the next release.

I'm not sure if `--target-compressed-block-size` is the option you want. It aims to produce compressed blocks of approximately some size, to improve the latency of streaming compression in some scenarios. But these block aren't independent of each other. And seeing as it is broken, I definitely wouldn't use it currently.

> For some reason I wanted to "split" input into blocks and couldn't find an option for it.

For what purpose do you want to split the input into blocks? And what do you mean by blocks, do you want to decompress each block independently? Zstd will already break the file up into blocks of 128KB, but each block depends on the previous blocks.

**Comment by terrelln** [comment]
Commit https://github.com/facebook/zstd/commit/e103d7b4a64c6321bb3ac4df07899ea09c3edbb2 introduces the bug, so it's been broken since v1.4.5.

**Comment by tansy** [comment]
Actually I wanted to split input into blocks of some fixed size. But, as there is no such option I thought it would be an alternative.

I also wanted to set sliding window size to limit memory usage during decompression. As far as I understood it's `--zstd=wlog`, but not sure about that.

**Comment by adamdmoss** [comment]
Hah, cool, I just got bitten by this today.  FWIW my simple little input file which tickled the bug is:
[badzstd.txt](https://github.com/facebook/zstd/files/9222974/badzstd.txt) - just about any (valid) --target-compressed-block-size seems to generate a bad output when trying to compress this.

**Comment by terrelln** [comment]
@adamdmoss what is your usecase for `--target-compressed-block-size`? It is a pretty unusual feature.

BTW: Anyone who hit this bug, please post here if you need your files recovered. This bug is recoverable. I can post a patch to the zstd decoder which will allow you to recover your files.

**Comment by adamdmoss** [comment]
My use-case is a dumb toy.  I can live without.  Was just surprised to get corruption.
