### ISSUE TITLE
Decompressing to terminal results in confusing 'Incorrect parameters'

### ISSUE THREAD

**Issue by moparisthebest** [facebook/zstd#322]
I was experimenting with zstd and pipes, and it behaves confusingly:

```
$ echo bob | zstd | zstd -d
Incorrect parameters
Usage :
      zstd [args] [FILE(s)] [-o file]

FILE    : a filename
          with no FILE, or when FILE is - , read standard input
Arguments :
 -#     : # compression level (1-19, default:3) 
 -d     : decompression 
 -D file: use `file` as Dictionary 
 -o file: result stored into `file` (only if 1 input file) 
 -f     : overwrite output without prompting 
--rm    : remove source file(s) after successful de/compression 
 -k     : preserve source file(s) (default) 
 -h/-H  : display help/long help and exit
```
I expected it to behave like gzip:
```
$ echo bob | gzip | gzip -d
bob
```
And finally figured out it will write to a pipe, as long as it isn't a terminal?
```
$ echo bob | zstd | zstd -d | cat
bob
```

I tested xz/lzop/bzip2 also:
```
$ echo bob | lzop | lzop -d
lzop: <stdout>: uncompressed data not written to a terminal
$ echo bob | lzop | lzop -d | cat
bob
$ echo bob | xz | xz -d
bob
$ echo bob | bzip2 | bzip2 -d
bob
```

So gzip/xz/bzip2 all decompress to terminal no problem, while lzop has an explicit error message, and zstd fails without any indication as to the problem.

If you tell me whether you want this to behave like lzop or gzip/xz/bzip2, I can submit a pull request with the fix. Thanks!

**Comment by gyscos** [comment]
zstd currently needs `-c` to write to stdin. You can do:
* `echo foo | zstd | zstd -d -c`
* `echo foo | zstd | zstdcat`

I don't know why `echo foo | zstd | zstd -d -o -` doesn't work, or why it isn't the default.

**Comment by moparisthebest** [comment]
Indeed -c forces it to write to the terminal too, regardless, the error message still should be fixed shouldn't it?  To be in-line with lzop's ?

**Comment by Cyan4973** [comment]
These are very good points.

When input is `stdin`, `zstd -d` should output to `stdout`.

When input is a file though, writing to `stdout` must be an explicit operation, requiring `-c`.

We should add this use case to the test suite.

**Comment by Cyan4973** [comment]
Latest update in `dev` branch should correctly support
`echo foo | zstd | zstd -d`
scenario

**Comment by Cyan4973** [comment]
Improved CLI behaviour and error messages in v1.1.0

**Comment by txtsd** [comment]
This isn't working correctly for me.
```
└─▶ zstd -V                                                                                                                    
*** zstd command line interface 64-bits v1.3.1, by Yann Collet ***
```
```
└─▶ echo derp | zstd | zstd -f                                                                                                 
(µ/ýP(µ/ýP)derp
)
 'x

   I%                                                                                                                           
```
```
└─▶ echo derp | zstd | zstd -f | cat                                                                                           
(µ/ýP(µ/ýP)derp
)
 'x

   I%                                                                                                                           
```
