### ISSUE TITLE
How to train a dict by api?

### ISSUE THREAD

**Issue by hzh0425** [facebook/zstd#3233]
Hi, I try to use zstd dictionary mode for compression.
I want to use dictionary mode in my code.
But by looking at zstd.h, I found that there is no relevant api to train a dict, what should I do?
The example only shows how to use dict to compress and decompress, but it doesn't explain how to train a dict without cliTool

**Comment by Cyan4973** [comment]
The API for dictionary training is in [`zdict.h`](https://github.com/facebook/zstd/blob/dev/lib/zdict.h).

**Comment by hzh0425** [comment]
Thanks~
