### ISSUE TITLE
decompression of zst file is not done successfully in following cases

### ISSUE THREAD

**Issue by shulib** [facebook/zstd#3234]
**Describe the bug**
example of hex data of zst files:
1.
28 b5 2f fd e0 4a 02 00 00 00 00 00 00 7d 12 00 74 24 54 70 c3 73 54 3d 70 07 07 7b a0 7e c3 c3 7b 82 7b 73 70 3d 82 b2 95 6e 54 6e 7e 54 95 67 78 73 3d a0 78 7b 67 17 a9 17 07 7e 17 a0 3e 3d c3 c3 b2 54 7e 7b 3d 78 44 bb 17 3e 7e a0 07 a9 44 78 44 3e 67 b2 c3 a9 44 78 d3 3e b2 c3 44 a9 b2 95 7b 70 7e 3d 54 82 7b 7b 95 b2 44 3e 17 a9 07 7b a0 54 b2 a9 17 82 54 07 73 78 07 a9 70 54 95 82 c3 67 82 73 78 3e 3e 3d 73 70 44 d3 d3 7b a0 67 a0 b2 54 a0 c3 a9 17 07 d3 4c 95 78 6e d3 78 d3 44 70 6e 6e 73 7b 6e 3e a9 a9 95 7e d3 a9 17 70 3e 7e d3 6e 07 70 bb b2 c3 b2 a0 d3 3d 70 89 73 6e d3 73 b2 07 78 78 6e d3 54 17 54 95 c3 7b 07 3d 70 07 70 a0 bb 70 6e 70 7e 67 17 78 a0 73 70 a9 6e 7b 73 c3 d3 82 17 07 54 17 44 b2 95 73 a9 70 c3 73 3e d3 70 82 a0 a0 70 95 e1 54 67 07 89 6e 78 d3 95 95 67 7e 95 44 a0 44 b2 17 a0 67 d3 54 44 82 17 a9 a0 e1 07 a0 54 95 7b 82 44 44 82 70 95 78 3e 7b d3 17 95 82 44 a0 67 73 07 54 67 73 7e 82 67 44 a9 70 95 b2 7e 7e 78 a0 a9 95 3d 6e 44 7e f8 7e 67 c3 b2 7e 73 7b 78 95 73 3d 82 c3 3d 7e 6e 3e c3 82 6e 82 95 d3 a9 44 95 44 07 6e 70 82 3d 78 b2 3e 3e 07 a0 6e 17 a9 b2 d3 7e 82 78 4c 7b a9 3d 54 17 a9 3d d3 44 a0 07 82 67 a0 82 73 07 e1 70 3d d3 b2 78 7e 17 82 7b 6e f8 b2 73 44 17 54 95 44 54 75 7e 95 a0 a0 54 b2 b2 a9 07 67 17 d3 67 44 3e a9 73 3e a9 7b 54 82 3e 78 73 3d c3 73 70 c3 b2 b2 67 c3 73 7b 75 7b 95 70 07 78 3d c3 44 6e f8 a0 17 82 67 78 7b 67 3d 82 3d 3e c5 7e 3d 67 78 7e a0 a9 a9 82 67 c3 70 3d 3e 75 a0 a9 95 54 95 3e 73 3d c3 44 7b 6e 07 c3 17 3d c5 67 78 a0 17 b2 7b 6e 95 78 3e 67 a9 d3 c3 3e c5 78 07 d3 c3 17 b2 78 54 07 d3 07 70 3e 67 78 67 44 7b 44 07 3d 6e 3d d3 d3 7b 73 54 c3 67 6e 67 d3 95 b2 44 b2 3e 3e 82 17 70 7e 73 6e 7e 6e 89 c3 82 3e 7b 17 67 7b 54 73 6e 17 07 a9 70 3d 7e 7e d3 54 b2 3e 3e 54 c3 82 7e 6e 17 73 7e 3d 07 17 6e 4c 80 01 00 00 4a 17

packet of literals and 1 sequence: ll=12 ml = 3 m0 = 5 
this file is compressed by zst protocol - but tool corrupt it - why? because ml and mo is small? 
2. raw data in literal section without sequences.  uncompressed size is 7. 
if it correct zsd file - why it corrupted?

**Comment by terrelln** [comment]
This file is corrupt. It violates the requirement that the compressed block size must be no more than `min(window_size, 128 KB)`. And the window size advertised 586 bytes. But the compressed block is 591 bytes. So this file is corrupt.

How did you generate this file? If it was created by the upstream zstd library, then that is a bug.

BTW: If you need to recover this file for whatever reason, the latest zstd CLI will decode this file, even though it is corrupt. Though because the checksum is disabled, I cannot tell you if the decoded file is correct, just that the tool will succeed in decoding it.

**Comment by shulib** [comment]
thanks for answer - I took the zstd file from other source ( it is not a tool bug)
