### ISSUE TITLE
This packet not decompressed by tool

### ISSUE THREAD

**Issue by shulib** [facebook/zstd#3243]
Hi, 
I take the additional file and tried to decompress it
as you see, the packet consists two blocks - one is zero block and the other is compressed block, 
contains literals raw and all tables (they are predefined table, but it written as a regular table).
why the tool not decompress it?

this is the data of packet
28 b5 2f fd c0 7f fd 03 00 00 00 00 00 00 98 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 75 21 00 74 3e 27 41 aa b2 0a 82 4a 98 08 a2 cb df 84 18 0c 8e 0f 98 7c af ba 43 8e d6 b2 df d9 2b 0a 20 d1 7c 6a df 2b 8b 30 41 22 3d 3f a5 4a 4a ac 6c 0c 68 62 33 9e c3 c3 ba 30 43 50 25 5f 5b 9b 30 af a0 18 1f d3 3d 4d 9b 68 3d ac b2 62 5b b6 06 d9 ac 6c 65 06 be d6 6e c3 98 65 b2 55 df d6 8e 08 04 7a cb c5 30 d1 3f 6a c7 af 5d 08 d9 6a 2a 3f 2b 43 d6 80 98 01 82 6c 08 6a cb 62 ac 59 04 50 ac 0a 30 65 af 0a b6 d9 2d 80 5d 4d 50 7e af ba 4a 43 62 68 96 90 3f d9 be 5d 57 a0 7e 3f 25 41 cb c5 68 3f d1 6c 2d c3 06 0a 5f a5 a2 55 6a 29 6c 6c 8e c5 d6 b8 41 a5 a8 80 57 6a 68 18 37 7e 0a d1 06 84 a5 77 d6 9b ba 6a ac 2b 30 25 4d c9 6e af be ac 7a 33 71 b6 2b af 14 08 14 c5 b5 b6 a2 53 22 6e b2 80 c3 2a 22 0c 7a 18 27 14 c7 86 a5 33 ac 5d a8 8e 90 df bc b2 3a ba 22 df 0a ac 25 d1 43 43 ba 41 b8 6e 62 5d 9b 62 c5 a5 2b 6c 98 06 80 d1 c9 7a be be 04 d3 4d 98 71 cb 22 1f a5 80 50 7a c7 6e 1b c9 4a 18 ac 7a 47 a0 d6 cb b6 c3 55 08 06 aa b2 04 7c 8b db 5b 16 1f df 45 7c 33 62 a0 90 8e 18 ac 25 82 55 82 a5 71 71 0a a2 d5 b6 7c 41 71 86 14 8e c9 7e 90 27 7e 14 65 47 80 9e 5d 27 47 db ac 0c 6a 3d 2d c5 50 62 57 b7 4d b6 1f 20 1f 18 82 27 80 3a 8e db c5 a2 14 6a 27 0c 22 5b 65 04 5f 4d 18 b2 5d 0c 73 55 6a cb d3 59 43 98 75 6c 7a 41 71 30 c7 1f 30 50 d1 7a 50 3f 7e 62 d1 8e 57 08 16 be a5 90 3f a2 9b cb 57 d6 2d 57 04 8b 47 c3 6e 41 6e 55 08 be 62 7a af 12 4a 59 50 98 3a d4 65 25 d9 af 3d d3 5d 7e 43 df 62 82 71 1f 33 1f a0 8e a0 59 41 df 7e c9 ba be 04 b6 4d b2 db 4d c7 30 1f 8b 4d 14 98 7e 22 6e 59 50 45 47 d6 5f 3a ba 14 7e 90 82 8b 5d 6a 50 41 c5 d9 cb 68 db 33 c5 dd 27 3a 8b 5b 22 af a5 d6 1e 65 65 47 d6 50 50 a0 47 35 5d b2 d1 4d 3a 57 68 be 47 d9 5b 6c 6a 57 c7 4d 80 2b 0c c3 c3 6e 82 55 7c 80 6c 3d 8b 2b 7a a0 68 d3 cb b6 30 53 4a 93 cb 89 7e 8b 04 08 d1 90 5b 8b 0c 41 2b 57 3a 06 a2 55 7c 0c 08 25 df 7e d9 5f b6 0c 01 55 06 be be 82 9b 82 d9 8b 7c 71 90 8e d3 3a c3 65 5f d2 af 6e b6 06 0a 2d 65 7a 9b ba 25 04 5f a0 9b 43 0c 33 55 98 c9 4d 4a c9 d4 5f db be 3a c0 7a 98 d1 ac 2b 3d db 35 ce 98 8e 3d 8b 04 80 08 68 14 5f 5f 27 73 a5 08 1f 30 3d 4a 04 be 6a 04 7e d6 2b 22 d5 68 7c ac 3a db 41 6e 43 25 5b c5 c0 c6 06 a2 71 c7 b6 47 5b 18 4a 2d c9 7c d3 d3 b2 57 93 3f 80 d9 3a 47 43 33 65 5f c9 2d 0c 0c 18 57 90 ba 43 a2 33 cb 80 59 c3 3f 6a a5 2d 14 5f 5b 55 5d 33 25 62 3a 65 96 1e 5d db 0c 68 d2 27 06 3f 41 43 71 82 6e 65 3a 4d b5 25 df 7c 2b 8e 22 08 98 5d 33 a0 6c 30 59 0a c5 a0 50 8b be 5f 27 d1 1b 06 59 3f 8b 47 c9 9b 3d 0a 90 db c7 06 1f 90 df 2d 33 df a2 2b 06 22 41 a0 3d c3 27 a2 59 59 6c 98 1f 5f 47 68 62 db 33 b2 14 d3 c5 59 c7 c9 3d a5 47 d3 0a 1f 90 6e 71 8b 18 30 59 2d 55 8e 5b bc 27 3a af c3 82 b2 db 30 37 2b 3f 3f 2d 65 0a c5 5b 7a 2d c9 90 2d 3d 4a d3 04 ba 62 33 d3 55 2d 14 c7 b2 0a 3d 27 c7 dd 9b a2 68 a0 22 d9 4d 0f b6 ba 18 18 7a 6e b6 c9 b7 6c d3 59 29 82 a0 af ce 18 c7 14 68 71 12 d9 ba 43 c7 ba 57 af a5 4a 89 7c 7c 9b 04 71 5b 57 4a cb 50 c5 c3 71 22 25 c6 57 90 6c 5b 1f 82 d1 db 08 7e 77 14 55 a2 25 27 a2 9b 80 d6 22 25 7c 59 75 9b 47 9b 5d 4a 80 01 a8 51 10 63 8c 31 c6 18 63 0c 21 c4 18 63 66 66 86 46 92 04 00 21 14 c4 18 63 8c 21 84 10 42 08 21 84 10 42 08 21 44 44 44 44 44 44 44 44 24 09 00 00 20 84 10 42 66 46 44 44 44 44 24 49 02 00 06 4c 20

thanks,

**Comment by embg** [comment]
Where did this file come from? How did you generate it?

**Comment by terrelln** [comment]
The offset table seems to be corrupt.

You can enable verbose logging with zstd by compiling with `make zstd DEBUGLEVEL=10`, you can raise or lower the debug level to get more or less verbose logging.

**Comment by embg** [comment]
Yes, in particular `ZSTD_decodeSeqHeaders` failed. You could try looking at the code for that function and see how your file is violating its requirements.

```
../lib/decompress/zstd_decompress_block.c: ZSTD_decodeSeqHeaders
../lib/decompress/zstd_decompress_block.c:644: ERROR!: check ERR_isError(headerSize) failed, returning ERROR(corruption_detected):
../lib/decompress/zstd_decompress_block.c:715: ERROR!: check ERR_isError(ofhSize) failed, returning ERROR(corruption_detected): ZSTD_buildSeqTable failed
../foo3 : Decoding error (36) : Data corruption detected
```
