### ISSUE TITLE
pzstd compressed file begins with skippable frame

### ISSUE THREAD

**Issue by chris8754** [facebook/zstd#3255]
**Describe the bug**
Files compressed with pzstd are beginning with a skippable frame. This makes the compressed file indistinguishable from an lz4 formatted file when reading the first four bytes (magic number). The magic number range of a skippable zstd frame is the same as the magic number range of a skippable lz4 frame. 

**To Reproduce**
1. Download "dickens" from the Silesia Corpus. Any large file will likely show this issue.
2. run "pzstd dickens"
3. run "od -x dickens.zst | head -5"

Output is 
0000000 2a50 184d 0004 0000 1bd0 002e b528 fd2f
0000020 5804 4bf4 8e06 c4cc 0c70 b033 0cd0 1b6d

**Expected behavior**
First frame in the file should be a non-skippable frame. The first four bytes of a .zst file will always start with this magic number: 0xFD2FB528. 

**Desktop (please complete the following information):**
 - SUSE Linux 12
 - pzstd version 1.5.3
- clang compiler version 11.0.1

**Additional context**
https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md#skippable-frames
https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md#skippable-frames
https://sun.aei.polsl.pl//~sdeor/corpus/dickens.bz2

**Comment by terrelln** [comment]
Sorry for the late reply!

@chris8754 this is a limitation of the `pzstd` format. `pzstd` is somewhat deprecated in favor of zstd's native multithreading support. We will still fix any bugs, but it is not under active development. Zstd's native multithreaded compression doesn't have this issue, but does not support parallel decompression.

If you see a file starting with a skippable frame number, I suggest skipping the frame and checking the magic number after the skippable frame. This is what `file` does, for instance.

Please open a new issue if you have any further questions.
