### ISSUE TITLE
[Help Wanted] should `ZSTD_flushStream` behaves differently from `ZSTD_endStream` when used for flushing purposes?

### ISSUE THREAD

**Issue by revintec** [facebook/zstd#3266]
Hi, I'm using 1.5.2, through jni(https://github.com/luben/zstd-jni 1.5.2-3), both are latest version as of writing

I use streaming compression to stream some lines of json string, delimited by line feed. After some critical point is reached I would like to flush zstd buffer so that the receiver can decode them immediately. I added a switch to call either `ZSTD_flushStream` or `ZSTD_endStream` for flushing purposes. Am I correct that they should be equivalent if the receiver is looping on `ZSTD_decompressStream`(ignoring its return value, thus also ignoring frame boundaries)?

More specifically, I found that:
when using `ZSTD_endStream` the receiver never hangs on receive, but using `ZSTD_flushStream` the receiver almost always hang due to insufficient bytes available(`so.read(...)` inside `read0`, code at bottom), that doesn't seems to be correct. This can be reproduced on my production system(I'm trying to minimize it into a minimal reproducer in the mean time), but it can't be reproduced on smaller dataset(yet)

pointers and their offsets should already be updated and advanced properly according to doc, both pointer arith and error checking code are omitted from the diagram
I'll post more code if the the information provided here is not enough(and when I've successfully produced minimal reproducer), but the same code works for smaller dataset, and the only change is the `eof` flag: from using `ZSTD_endStream` to `ZSTD_flushStream`

reference diagram
<img width="795" alt="image" src="https://user-images.githubusercontent.com/8952734/191198116-da237b3c-6635-4f0a-89d1-d5aea67b094f.png">

code snippets:
https://github.com/luben/zstd-jni/blob/905202f10e5355cf7ed7a558e909558bc6ebf184/src/main/native/jni_directbuffercompress_zstd.c
https://github.com/luben/zstd-jni/blob/905202f10e5355cf7ed7a558e909558bc6ebf184/src/main/native/jni_directbufferdecompress_zstd.c
```kotlin
    private fun castZstd(n:Long)=if(isError(n))throw ZstdException(n)else n.toIntExact()
    fun decompress(dst:ByteBuffer,src:ByteBuffer):Int{
        if(stream<0)throw ClosedChannelException()
        val n=castZstd(decompressStream(stream,dst,dst.position(),dst.remaining(),src,src.position(),src.remaining()))
        src.position(src.position()+consumed)
        dst.position(dst.position()+produced)
        return n
    }
    suspend fun compress(m:ByteBuffer){ // input buffer
        if(stream<0)throw ClosedChannelException();while(m.hasRemaining()){
            if(!buffer.hasRemaining())flushBuffer()
            castZstd(compressDirectByteBuffer(stream,buffer,buffer.position(),buffer.remaining(),m,m.position(),m.remaining()))
            buffer.position(buffer.position()+produced)
            m.position(m.position()+consumed)
        }
    }
    suspend fun flush(eof:Boolean){ // the previously mentioned `flag`
        if(stream<0)throw ClosedChannelException();val fn=if(eof)::endStream else::flushStream;do{
            val n=castZstd(fn(stream,buffer,buffer.position(),buffer.remaining()))
            buffer.position(buffer.position()+produced)
            flushBuffer()
        }while(n!=0)
    }
    // socket outer loop, if `buffer` doesn't contain '\n', call `read0` one more time
    override suspend fun read0():Int{ // `produced` is how much data is produced by calling `decompress`
        do v=decompress(buffer,so.read(max(1,v)))while(produced==0)
        return produced
    }
```

**Comment by Cyan4973** [comment]
Not sure what "hang" means in your description.

A `flush()` order will immediately create a block, with currently available input data.
The block is then flushed to output buffer, for immediate reading and decoding by a consumer process.
Note that `flush()` may not be able to flush the entire compressed block if the output buffer is not large enough,
I assume from now on that this is not the case.

On the receiving side, indeed `ZSTD_decompressStream()` will be able to decode compressed data sent from originating process, as soon as the entire block is received.
The "only" difference is that, on `flush()`, a block is completed but the current "frame" (succession of blocks) is not, so the decompression state must keep enough information to be able to decompress future blocks.
Whereas on `end()`, both the block and frame are completed.

Difference is also perceptible on the return value of `ZSTD_decompressStream()` : on `end()`, it will return `0`, to signifies the end of a frame. On `flush()`, it will return non-0, (likely 3, though the exact value does not really matter) to signify that more data is expected. See [doc](https://github.com/facebook/zstd/blob/v1.5.2/lib/zstd.h#L776).

As you are using a JNI intermediate layer between the raw C library and your application, it is also possible that the behavior vary from raw C library. This is something to check with the `zstd-jni` project.

**Comment by revintec** [comment]
thanks for helping, the information you give is aligned with mine, I'll try to dig deeper

---

by "hang" I mean the receiver end won't get enough data to make progress. it behaves like the sender doesn't send a complete json line(or zstd block), thus it was blocking on lower network recv call, which is unexpected and shouldn't happen. the sender on the other hand thinks that it has flushed enough data so it won't send more, thus receiver hangs

It seems a little difficult to debug this case without dumping all uncompressed stream as well as the compressed stream that is sent though the wire

all edge cases you've mentioned are ruled out currently, I'm rewriting the code to build a minimal reproducer
I've checked the return value of `ZSTD_flushStream`, looping until it returns zero
I've observed that `ZSTD_decompressStream()` sometimes returns 3 and I think its handled correctly, I'll check again
I've checked(link provided in the above post) the JNI implementation source code, it seems straight enough, just passing to C call

**Comment by revintec** [comment]
Ahhh...I've found the issue, though I don't know if this is expected or not

according to this `http://facebook.github.io/zstd/zstd_manual.html#Chapter9`
```
@return : 0 when a frame is completely decoded and fully flushed,
        or an error code, which can be tested using ZSTD_isError(),
        or any other value > 0, which means there is still some decoding or flushing to do to complete current frame :
                                the return value is a suggested next input size (just a hint for better latency)
                                that will never request more than the remaining frame size.
```
it reads to me that if the return value -- `retv` -- is >0, I should read at least `retv` bytes from the underlying medium before continue decompression, did I understand it correctly? `<-- THIS IS THE QUESTION`

---

however I've observed that when the sender calls `ZSTD_flushStream`, the data -- `cc` bytes in size -- did get sent to the receiver, but `ZSTD_decompressStream` returns `cc+3` -- instead of `cc` bytes

this causes the underlying medium failing to read all required bytes -- 3 bytes short -- thus hang indefinitely
curiously this exact setup doesn't hang each and every time. sometimes, like compressing a very small amount of data and then call `ZSTD_flushStream` doesn't hang

calling `ZSTD_endStream`, beyond flushing, would also write a end block(according to the docs it should be 3 bytes) thus the `cc+3` read won't hang

---

the actual file content may contain sensitive information thus I may not be able to provide, here are some debug output instead

this image shows a call site that the underlying socket hangs

<img width="1580" alt="image" src="https://user-images.githubusercontent.com/8952734/194041274-13811ae2-11ea-4800-96f0-e37864d5042b.png">

after dumping the data transferred on the wire, saved to a file. calling `ZSTD_decompressStream` and record the returned value -- `v` -- and the available bytes left from the file -- `left` -- shows this

<img width="713" alt="image" src="https://user-images.githubusercontent.com/8952734/194041340-325ccbdc-9218-4f86-a242-d5fe7ddfadc2.png">

this screenshot shows that all data is correctly flushed by the sender(notice the trailing `null`), and `zstdcat` is able to read them

<img width="817" alt="image" src="https://user-images.githubusercontent.com/8952734/194042753-a01cf7ed-8145-4019-8775-ed2d8926a1e2.png">

**Comment by Cyan4973** [comment]
> it reads to me that if the return value -- `retv` -- is >0, I should read at least `retv` bytes from the underlying medium before continue decompression, did I understand it correctly?

Yes.
But "continue" in this context is in relation to the frame, not to the block.
Essentially, if the return value is `> 0`, it means the **frame** is not fully decoded. 

This is what happens after a `ZSTD_flushStream()` : the sender completes a block, but the frame is still ongoing.
Consequently, even after receiving the complete compressed block, `ZSTD_decompressStream()` will still return a value `> 0`. And actually, if it returns `3`, it's a pretty good sign that it has ingested a complete compressed block and is expecting the header of next block.

> this causes the underlying medium failing to read all required bytes

It's not _required_.
It's just a "hint". If you provide less bytes, or more bytes, to the input, streaming will still work.
The main objectives of the return value are : 
1) Signal an error
2) Tell when a frame is completely decoded and completely flushed (`0`)

Telling when a block subdivision was just completed was never part of the designed contract,
though we could say that, when it returns `3`, it's a good sign that a compressed block was just ingested,
and now the decoder state is waiting for one more block.

**Comment by revintec** [comment]
1. so decompression can(at least sometimes) continue(produce at least 1 byte of decompressed data) even for partial block? I thought it can only continue when the whole block is read...
2. after reading your comment, if I want the decompression to always make progress, it seems the return value(let's call it `retv`) from `ZSTD_decompressStream`(if it's not an error) can only be safely compared against 0?
3. how is this `retv` "hint" useful? -- if all positive `retv` values collapse into `1`, did we lose any information?

**Comment by Cyan4973** [comment]
> 1. so decompression can(at least sometimes) continue(produce at least 1 byte of decompressed data) even for partial block?

_continue_ is **not** defined as "produce at least 1 byte of decompressed data".
`zstd` considers that there is forward as long as one of these conditions is met: 
- successfully ingested at least 1 byte of input data
- successfully produced at least 1 byte of output data

If any of these conditions is met, then there is "forward progress", which you could translate into "successful continue".

What `zstd` tries to avoid are "busy loop", where nothing gets done (no ingestion, no production). These situations are classified problematic and can lead to error.
But as long as there is at least 1 byte to read from input, and space for at least 1 byte to write to output, this scenario shall never happen. The `libzstd` library is tested to ensure it respects this condition.


> how is this retv "hint" useful?

Following the input size hint can reduce buffering operations.
To be fair though, this effect is very small, and probably negligible in most scenarios with other sources of bottlenecks.
In which case, the exact value of the hint can be safely ignored.
The only thing that matters then is to check if the return value is `ZSTD_isError()`, or `0` (end of frame), or any other value (ongoing frame).

**Comment by revintec** [comment]
thanks for your time, it has been of great help
