### ISSUE TITLE
Mac OS X Homebrew tap does not work

### ISSUE THREAD

**Issue by bingh0** [facebook/zstd#328]
brew tap facebook/zstd zstd does not work, results in asking for github username and password. This usually happens when the tap doesn't exist.

brew tap facebook/zstd zstd
==> Tapping facebook/zstd
fatal: repository 'zstd' does not exist
Error: Failure while executing: git clone zstd /usr/local/Library/Taps/facebook/homebrew-zstd --depth=1

HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 06fe347de97975dc01e726f87bf07a56a6fb713e
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ec8f64cef2a351cc63a6ead56229a7da0aafdd94

**Comment by Cyan4973** [comment]
Why is `brew tap` necessary ?
doesn't `brew install` work out of the box ?

**Comment by bingh0** [comment]
https://code.facebook.com/posts/1658392934479273/smaller-and-faster-data-compression-with-zstandard
We would like to thank all contributors, both of code and of feedback, who
helped us get to 1.0. This is just the beginning. We know that for
Zstandard to live up to its potential, we need your help. As mentioned
above, you can try Zstandard today by grabbing the source or pre-built
binaries from our GitHub project <https://github.com/facebook/zstd>, or,
for Mac users, installing via homebrew (brew tap facebook/zstd zstd && brew
install zstd). We'd love any feedback and interesting use cases you have,
as well as additional language bindings and help integrating it with your
favorite open source projects.


brew install zstd
==> Downloading
https://homebrew.bintray.com/bottles/zstd-0.8.0.el_capitan.bottle.tar.gz
########################################################################
100.0%
==> Pouring zstd-0.8.0.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/zstd/0.8.0: 17 files, 1.2M

**Comment by Cyan4973** [comment]
Article has been fixed. Only `brew install` is necessary.
