### ISSUE TITLE
Multithreading issue with z_nbWorkers>1, self build zstd with gcc 8 or redhat 9 x64 system build, 

### ISSUE THREAD

**Issue by halifir** [facebook/zstd#3280]
I have a multithreading issue on Linux with self compiled libzstd.a and gcc 7 and gcc 8 
and with the prebuild redhat 9 x64 usr/lib64/libzstd.so

The problem with usr/lib64/libzstd.so means - that the problem is not bound to my local gcc compiler.

When I use the ZSTD stream functions with z_nbWorkers >1 (I used 9)

ZSTD_CCtx_setParameter(z_comp_context, ZSTD_c_nbWorkers, z_nbWorkers);
and using the API with 
ZSTD_createCStream
loop through
    ZSTD_compressStream2 
ZSTD_freeCStream

I got somehow wrong packets when i transfer "lot of data (eg 185MB)"
The problem happens often and somewhere - not always in the part of the data and not the same way on all machines. Some machines do not have any problems, other machines have a lot of destroyed datasets.

I have this  solutions found for my problem:
a) 
Using z_nbWorkers=0 (default=1, no threads)

b)
compiling my own libzstd.a without -DZSTD_MULTITHREAD 
sporadic failures with
gcc  -c -DLINUX  -pipe  -pthread -D_GNU_SOURCE -m64 -DUSE_SSE2 -fPIC -fno-omit-frame-pointer -mtune=generic -Wno-deprecated -D__64BIT__  -D_UNIX -D_BSD=44  -std=gnu11 -ffunction-sections -fdata-sections -g -O2 -minline-stringops-dynamically   -g   -DZSTD_MULTITHREAD  zstdlib.src/common/pool.c -o zstdlib.src/common/pool.o

no failures without multithreading
gcc  -c -DLINUX  -pipe  -pthread -D_GNU_SOURCE -m64 -DUSE_SSE2 -fPIC -fno-omit-frame-pointer -mtune=generic -Wno-deprecated -D__64BIT__  -D_UNIX -D_BSD=44  -std=gnu11 -ffunction-sections -fdata-sections -g -O2 -minline-stringops-dynamically   -g   zstdlib.src/common/pool.c -o zstdlib.src/common/pool.o

c) 
probably a solutin. I am not sure, but I significantly increased the chance to _not_ get corrupted datas when using mutithreading

Using volatile variables in the thread struct of pool.c + zstdmt_compress.c

{ This solution seems to mean, that the compiler is using CPU registers to fetch this variables in functions, that use mutex at the same time.
I guess (because I saw this behavior on HP-ux in pigzee some years ago)
transfer variable from struct to register
call mutex function 
do something the variable in register - but the content of the register is wrong, because the register was loaded before the mutex function.
On HP the mutex function is a simple function and no kind of memory barrier which invaliades registers. So no variables inside mutex region should be used without volatile.
I guess that this happens in gcc (8), too. But I am aware that a lot of people in the internet say, the gcc _always_ takes care of mutex calls. On the other hand side  - the people are not programming and testing the gcc with all available source code, do they? And I see that some people even do not see the difference between volatile and mutex. a mutex area will be called just ba a defined (often 1) thread at one time. But what the thread will see in registers or memory depend on volatile - because if a another thread a not written back his registers in the unlock function to real memory, all other threads will not see the variables at all.
I guess the std::atomic<type> will be in C++ what volatile will do in C here.
}

struct POOL_ctx_s {
    ZSTD_customMem customMem;
    /* Keep track of the threads */
    ZSTD_pthread_t* threads;
    volatile  size_t threadCapacity;
    volatile  size_t threadLimit;

    /* The queue is a circular buffer */
    POOL_job *queue;
    volatile size_t queueHead;
    volatile size_t queueTail;
    volatile size_t queueSize;

    /* The number of threads working on jobs */
    volatile size_t numThreadsBusy;
    /* Indicates if the queue is empty */
    volatile int queueEmpty;

    /* The mutex protects the queue */
    ZSTD_pthread_mutex_t queueMutex;
    /* Condition variable for pushers to wait on when the queue is full */
    ZSTD_pthread_cond_t queuePushCond;
    /* Condition variables for poppers to wait on when the queue is empty */
    ZSTD_pthread_cond_t queuePopCond;
    /* Indicates if the queue is shutting down */
    volatile int shutdown;
};

edit 2 update
adding volatiles in zstdmt_compress.c

typedef struct buffer_s {
    void* start;
    volatile size_t capacity;
} buffer_t;

typedef struct ZSTDMT_bufferPool_s {
    ZSTD_pthread_mutex_t poolMutex;
    volatile size_t bufferSize;
    volatile unsigned totalBuffers;
    volatile unsigned nbBuffers;
    ZSTD_customMem cMem;
    buffer_t bTable[1];   /* variable size */
} ZSTDMT_bufferPool;

typedef struct {
    ZSTD_pthread_mutex_t poolMutex;
    volatile int totalCCtx;
    volatile int availCCtx;
    ZSTD_customMem cMem;
    ZSTD_CCtx* cctx[1];   /* variable size */
} ZSTDMT_CCtxPool;

typedef struct {
    void const* start;
    volatile size_t size;
} range_t;

typedef struct {
    /* All variables in the struct are protected by mutex. */
    ZSTD_pthread_mutex_t mutex;
    ZSTD_pthread_cond_t cond;
    ZSTD_CCtx_params params;
    ldmState_t ldmState;
    XXH64_state_t xxhState;
    volatile unsigned nextJobID;
    /* Protects ldmWindow.
     * Must be acquired after the main mutex when acquiring both.
     */
    ZSTD_pthread_mutex_t ldmWindowMutex;
    ZSTD_pthread_cond_t ldmWindowCond;  /* Signaled when ldmWindow is updated */
    ZSTD_window_t ldmWindow;  /* A thread-safe copy of ldmState.window */
} serialState_t;

solution
d)

I added a call to ZSTD_toFlushNow before ZSTD_compressStream2 as fileio.c is doing.
# ifdef ZSTD_MULTITHREAD
						ZSTD_toFlushNow(z_comp_context);
# endif						

						if (bFileEnd)
							zc_retvalue = ZSTD_compressStream2(z_comp_context, &zc_out_buff, &zc_in_buff, ZSTD_e_end);
						else
							zc_retvalue = ZSTD_compressStream2(z_comp_context, &zc_out_buff, &zc_in_buff, ZSTD_e_continue);

with the additional ZSTD_toFlushNow , which do a mutex on the oldest non-fully-flushed job , the result of the Stream2 function seems to be very stable (tests are still running)

**Comment by Cyan4973** [comment]
It seems like you are experiencing a pretty serious issue.
A blatant corruption when using multi-threading is unexpected : after all, this code path is heavily fuzzed, so we should have experienced an error being triggered during consistency checks.

Obviously, different issues could also lead to the same symptom.
And there might be a nb of conditions required for the bug to happen, maybe that's why it evades testing.

So I believe the first action here would be to find a reliable way to reproduce the problem.

**Comment by halifir** [comment]
I dont have the problem with clang. And it seem to be, that I dont have the problem if I just set the size/pos variables in zstd.h on volatile.
Something is breaking the access to a variable in my gcc. 
I did a debug session for my code and the mutitthreading part on windows (before diving into the compression),  and I dont saw an unexpected problem in the sources.

**Comment by halifir** [comment]
Because of defining the variables for size/pos in zstd.h  as volatile - the variable/register optimization problem of my gcc seems to  be in the calling part aka my code. I will reduce the function size of the caller/fetch variables with memcpy or something like that and I am sure that this will fix the problem, because the problem vanishes if I compile my code with clang or on Windows cl.exe or clang.exe
