### ISSUE TITLE
Custom Huffman dictionary to ZSTD

### ISSUE THREAD

**Issue by danlark1** [facebook/zstd#3283]
Hi, I have a question.

Say, I have a good set of strings and their frequencies to build a standard Huffman tree that I know nicely compresses small strings when standard Huffman is applied with a greedy strategy. What is the best way to construct a dictionary for ZSTD given these strings and frequences?

I tried concatenating them in both orders with the frequency counts repetitions and without and applying `ZDICT_finalizeDictionary` but unfortunately the compression was far lower than standard Huffman (11x vs 7.8x on a github set).

I read through docs and code and dictionary is just a set of bytes, but how exactly is it used to improve the compression? I see referral to ` * Effective Construction of Relative Lempel-Ziv Dictionaries` paper where the segment strings are concatenated, so here is the question, what should be done to feed strings+Huffman freqs to get the best compression?

**Comment by terrelln** [comment]
> Say, I have a good set of strings and their frequencies to build a standard Huffman tree that I know nicely compresses small strings when standard Huffman is applied with a greedy strategy. What is the best way to construct a dictionary for ZSTD given these strings and frequences?

Just pass the samples to `ZDICT_finalizeDictionary()`. Also make sure to set the compression level to the level you'll be using in the `ZDICT_params_t`.

`ZDICT_finalizeDictionary()` will:
* Compress each sample with the given compression levels
* Extract the literals from the samples, build a Huffman tree from the stats of the literals only, and put it in the dictionary
* Build FSE tables for offsets, literal lengths, and match lengths fitted to the compressed blocks, and put it in the dictionary

It will also make sure that every possible symbol has a non-zero probability. This might hurt compression ratio a bit, but it ensures the dictionary will always work.

We don't currently have a way to pass custom statistics into the dictionary builder. But I'd try this method first and see if it works. If not, it is possible to build your own dictionary header given the [format specification](https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md#dictionary-format).

> I read through docs and code and dictionary is just a set of bytes, but how exactly is it used to improve the compression? I see referral to * Effective Construction of Relative Lempel-Ziv Dictionaries paper where the segment strings are concatenated, so here is the question, what should be done to feed strings+Huffman freqs to get the best compression?

Zstd dictionaries can optionally have a header before the content. This is what `ZDICT_finalizeDictionary()` adds.

**Comment by danlark1** [comment]
Thanks! I believe I got the answer

Just for the context: I am trying to build an external dictionary which I believe should compress faster and better

I tried the method you described and unfortunately it worked worse :(. I expected ZSTD to be even better feeding a set of strings that is known to compress a set of files even as a literal compression. Given I have this dictionary, I believed I could concatenate them and literals compression should have worked like a charm. Taking a few stripes of 16-32 bytes randomly from samples and just stick them together as a dictionary works good. However, I found a very good and precise dictionary and while concatenating it, it works better than random stripes, not that good if I just apply huffman algo on them.

I'll try to build FSE and Huffman entropy tables then on my own, thanks!

**Comment by danlark1** [comment]
One more thing, I found that it's useful to have most common elements at the end of the dictionary so that offsets are closer to the file itself, that was a little surprising to discover but I should just continue reading code, I guess :+1:

**Comment by terrelln** [comment]
> I tried the method you described and unfortunately it worked worse :(. I expected ZSTD to be even better feeding a set of strings that is known to compress a set of files even as a literal compression.

`ZDICT_finalizeDictionary()` does not insert any "content" into the dictionary. It only adds the header containing the Huffman & FSE tables to the beginning of a pre-built dictionary. You pass it the pre-built dictionary, and the samples.

`ZDICT_trainFromBuffer()` is the "default" dictionary builder which is reasonably fast and builds a reasonably good dictionary. I'd recommend also trying `ZDICT_trainFromBuffer_cover()` with the default parameters, but maybe set `steps=256`, and increase `nbThreads` so it is faster. This can also be achieved on the command line with `zstd -T0 --train-cover=steps=256`.

We definitely need to spend some time cleaning up the dictionary builder API & docs. It is a bit of a mess, but we haven't really found the time to revamp it.

>  One more thing, I found that it's useful to have most common elements at the end of the dictionary so that offsets are closer to the file itself, that was a little surprising to discover but I should just continue reading code, I guess 👍

Yup, this is because the offsets to reference them are the smallest, and when we build our tables, they are the last hashes put into the table, meaning least likely to be overwritten by a collision! The zstd dictionary builder puts its "best" strings at the end.
