### ISSUE TITLE
Please produce binaries for the latest versions

### ISSUE THREAD

**Issue by mikhailkoliada** [facebook/zstd#3297]
Hello!

I am a member of the team responsible for GitHub Actions hosted runners and Microsoft-provided agents in Azure DevOps.
zstd is a highly-demanded package amongst GitHub customers, apart from that, the [actions/cache](https://github.com/actions/cache) action hardly relies on the zstd installed in the images we provide.

As we only provide the LTS versions of [ubuntu](https://github.com/actions/runner-images/tree/main/images/linux) zstd is surely quite obsolete there, and as a result we have to install zstd using the [linuxbrew](https://github.com/actions/runner-images/blob/main/images/linux/scripts/installers/homebrew.sh#L37) package manager.

Due to recent changes in brew we had to [remove](https://github.com/actions/runner-images/issues/6283) it from our $PATH. Apart from that, we are considering mere reliable ways of shipping zstd to our customers (including possibility of providing a self-built binary), but before building it oursalves, we wanted to reach you and ask if it is possible to produce binaries for the latest versions, it might be probably a benefit for lots of people, not only GitHub.

Thanks!

**Comment by felixhandte** [comment]
In general we rely on distros to produce the binaries for their OSes. But yes it's disappointing that the LTS releases don't update the zstd package. Technically, versions before 1.4.9 are affected by a [CVE](https://repology.org/project/zstd/cves).

Have you considered grabbing the .deb from a newer Ubuntu release and installing it manually? I see that 22.10 packages the current version. Given that zstd (1) is nearly dependency-free and (2) has a stable API/ABI, I believe that should work.

**Comment by mikhailkoliada** [comment]
Hmm, we have not considered using deb from the newer ubuntu version, will check it out and let you know how it goes.

**Comment by mikhailkoliada** [comment]
@felixhandte 1.5.2 from 22.10 works on 22.04, but on 18 & 20 / 04 it depends on the toolchain libs still :(

<img width="642" alt="image" src="https://user-images.githubusercontent.com/88318005/197196219-4098cdbb-9b4e-44df-86c5-fcf109e6c9fe.png">

**Comment by mikhailkoliada** [comment]
@felixhandte any thoughts? :)

**Comment by mikhailkoliada** [comment]
@felixhandte and now? :)

**Comment by felixhandte** [comment]
Sorry for the radio silence.

Is there a reason you need us to build these binaries? Ultimately, what we would build would just be the result of `git clone https://github.com/facebook/zstd && git checkout v1.5.2 && make zstd-release` on that platform.

Edit: I see you call that out as an option in your original comment. Yeah, I think that's probably the easiest way forward here.

**Comment by felixhandte** [comment]
In the absence of a reply, I'm going to close the issue. If you want to discuss further, please feel free to re-open.

**Comment by gaby** [comment]
@felixhandte I ran into the same issue, hundreds of devices using zstd but they are stuck with an older version because of Ubuntu LTS. 

This a valid issue, fixable via github actions.

**Comment by gaby** [comment]
Seems like @mikhailkoliada found a fix. The github actions are using 1.5.4
