### ISSUE TITLE
Missing parens in macro definition

### ISSUE THREAD

**Issue by terrelln** [facebook/zstd#3301]
`RANK_POSITION_LOG_BUCKETS_BEGIN` and `RANK_POSITION_DISTINCT_COUNT_CUTOFF` need parens around their definitions.

Their uses are still correct without parens, but this is a code smell.

https://lore.kernel.org/oe-kbuild/20221027075910._PbWJp-5TkY_Ws8XnTmi6N1OnHCeRmO-lRyZj3XRJBk@z/T/#mbfb497176c369eb99f264c8c66cbef8883d29c57

Reported-by: kernel test robot <lkp@intel.com>
Reported-by: Dan Carpenter <dan.carpenter@oracle.com>

**Comment by fool1280** [comment]
Hi, can I take on this issue? It seems like a simple fix for a first time contributor like me. Thank you!

**Comment by terrelln** [comment]
Absolutely!
