### ISSUE TITLE
Where is ZSTD_CCtx allocated when ZSTD_createCCtx is called?

### ISSUE THREAD

**Issue by Hlinbit** [facebook/zstd#3305]
I have found a curious problem when I write code for compressing data in multi-thread mode.  My code is like following fake code.
```
// Just set address of request->zstd_cctx to be aabb. And in the main memory we create the request and thread.
request->zstd_cctx =  ZSTD_createCCtx(); \\ request is a structure contained zstd_cctx. And every thread will have its own request to be processed.
thread_create(function, request)

function(request):
       initResult = ZSTD_initCStream(request->zstd_cctx, 1); // in this line, the program crashes. And if debug it, the address of  request->zstd_cctx is not aabb. And if ZSTD_createCCtx is called in the function before ZSTD_initCStream, the problem will disappear.
       ....
```

So Where is ZSTD_CCtx allocated when ZSTD_createCCtx is called? Threads created will share heap memory with the main process. But In the above example, the address of zstd_cctx in the sub-thread does not equal the address when it is created.
Because the struct ZSTD_CCtx is implicit, I can not check the content in it. 

Hope for your reply.

**Comment by felixhandte** [comment]
The `ZSTD_CCtx` struct is allocated on the heap via a simple call to `malloc()` ([here](https://github.com/facebook/zstd/blob/v1.5.2/lib/compress/zstd_compress.c#L92-L95) to [here](https://github.com/facebook/zstd/blob/v1.5.2/lib/compress/zstd_compress.c#L114) to [here](https://github.com/facebook/zstd/blob/v1.5.2/lib/common/zstd_common.c#L60) to [here](https://github.com/facebook/zstd/blob/v1.5.2/lib/common/zstd_deps.h#L54)). Without knowing more about your environment and program, I can't speculate why you're seeing this problem. But zstd definitely isn't doing anything tricky here.

By the way, the CStream API is an [old API](https://github.com/facebook/zstd/blob/v1.5.2/lib/zstd.h#L736-L742) that has been superseded by [`ZSTD_compressStream2()`](https://github.com/facebook/zstd/blob/v1.5.2/lib/zstd.h#L691-L716). You might find it easier to use the new API.
