### ISSUE TITLE
Feature request: Automatic/unlimited decompression memory

### ISSUE THREAD

**Issue by Mysak0CZ** [facebook/zstd#3307]
**Is your feature request related to a problem? Please describe.**
When specific compression options are used (for me talking mainly about rather common `--long=31` option), decompression needs to be supplied the same arguments or decompression will fail, because of the massively increased memory requirements, resulting in for user unhelpful messages, such as:
> Zstd decompression failed: Frame requires too much memory for decoding

This makes lot of sense in server/shared environment, however is rather frustrating when used in desktop environment, where user wants to get the task done, even if lot of memory would be used and would affect other parts of system.

**Describe the solution you'd like**
An option for both CLI and coding API that either unlimits the memory or makes Zstd auto-detect required memory/options based on the input archive user is attempting to decompress.

**Describe alternatives you've considered**
Alternative is documenting what are options to set to decompress most common compression configs and setting them at least so those are decompress-able by default. This has drawback of being cat-and-mouse game and only shifts the original problem (until options using more memory become more common) instead of solving it.

**Additional context**
Originally started solving this as GUI application `ark` using the `libarchive` library couldn't show `.tar.zstd` file, because it was compressed using `--long=31`.
Related issue for `libarchive`: [libarchive/libarchive#1795](https://github.com/libarchive/libarchive/issues/1795)

**Comment by embg** [comment]
We limit memory allocation in the decompressor to 2^27 bytes by default so that applications don't need to worry about unexpected inputs causing OOM issues.

If you want to increase the default limit, simply pass `--long=31` or `-M2048MB` to the zstd CLI for all inputs. If you are using the C API, set [ZSTD_d_windowLogMax](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L567) to 31. Actual memory consumption will only increase when necessary for a particular input.

**Comment by Cyan4973** [comment]
I believe one of the points in this issue is that the CLI prompt is not descriptive enough to help the user solve the problem : 

> resulting in for user unhelpful messages, such as:
> `Zstd decompression failed: Frame requires too much memory for decoding`

I made the same test on current `dev` version, and it resulted in the following error:

```
long31.zst : Decoding error (36) : Frame requires too much memory for decoding
long31.zst : Window size larger than maximum : 2147483648 > 134217728
long31.zst : Use --long=31 or --memory=2048MB
```

Maybe older versions were less descriptive?
