### ISSUE TITLE
Fix Scorecard Github Action error

### ISSUE THREAD

**Issue by joycebrum** [facebook/zstd#3308]
**Describe the bug**

I've seen that the Scorecard Github Action is throwing an error (https://github.com/facebook/zstd/actions/runs/3371193183).

This [error](https://github.com/ossf/scorecard-action/issues/998) is solved in the version 2.0.6 (https://github.com/joycebrum/zstd/actions/runs/3371656143), can I open a PR to upgrade the version and solve the issue?

**Comment by felixhandte** [comment]
Hi @joycebrum,

Yeah, sure thing! Thanks for taking a look.
