### ISSUE TITLE
pzstd

### ISSUE THREAD

**Issue by twirrim** [facebook/zstd#331]
Ran into a few bugs using pzstd, but wow is it ever blazingly fast.  Apologies, C isn't a language I'm particularly familiar with or I'd try to fix these myself.

1) To build on Linux (g++ only?) you need to pass the -pthreads flag.  Easy to fix so I could get the code to compile, but I'm not sure the appropriate Makefile voodoo to make it work on multiple platforms.

2) decompression over stdin seems to still require an input file.  compression over stdin works fine.

3) on 32bit environment I could manage to get
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```
if I tried to pass in large content over stdin, or read large block devices.

**Comment by terrelln** [comment]
1.  Will fix today.
2.  If you pass "-" as the input file it will work.  I will fix this to default to stdin.
3.  I don't have a 32 bit machine to test on, perhaps I can build in 32 bit mode.  Do you know how big the file is?  `std::bad_alloc` means that pzstd ran out of memory.  Right now, it doesn't do anything at all to limit the amount of memory it consumes.  I think there is low hanging fruit to reduce the memory footprint a large amount without impacting performance, which I will hopefully get around to today.

Thanks for the reports!

**Comment by terrelln** [comment]
Pull request #333 should fix your memory usage.  For instance when compressing a 4GB file, it used to take ~4GB of memory, now it takes ~100 MB at compression level 8.

If you are still having memory issues, please let me know.

**Comment by octoploid** [comment]
Another issue: If the number of threads is not explicitly specified,
use all available on the machine by default.

Something like:  

```
diff --git a/contrib/pzstd/Options.cpp b/contrib/pzstd/Options.cpp
index 61613099691d..ba2387ae76ce 100644
--- a/contrib/pzstd/Options.cpp
+++ b/contrib/pzstd/Options.cpp
@@ -10,6 +10,7 @@
 
 #include <cstdio>
 #include <cstring>
+#include <thread>
 
 namespace pzstd {
 
@@ -172,10 +173,8 @@ bool Options::parse(int argc, const char** argv) {
     }
   }
   // Check that numThreads is set
-  if (numThreads == 0) {
-    std::fprintf(stderr, "Invalid arguments: # of threads not specified.\n");
-    return false;
-  }
+  if (numThreads == 0)
+    numThreads = std::thread::hardware_concurrency();
   return true;
 }
 }
```

**Comment by terrelln** [comment]
Yeah, that is better.  Its also what pigz does.
