### ISSUE TITLE
Surprising error report for dict id mismatch

### ISSUE THREAD

**Issue by embg** [facebook/zstd#3310]
**Describe the bug**
When I change the dict id between compression and decompression, I get `zstd: error 11 : Allocation error : not enough memory`.

**To Reproduce**
```
$ zstd --train silesia.tar -B16K -o dict_old
$ python3
>>> dictf = open('dict_old','rb').read()
>>> dictf = dictf[0:4] + 'abcd'.encode() + dictf[9:]
>>> open('dict_new','wb').write(dictf)
>>> quit()
$ zstd silesia.tar -D dict_old -o silesia.tar.zst
silesia.tar          : 31.43%   (   202 MiB =>   63.5 MiB, silesia.tar.zst)    
$ zstd -D dict_old -d silesia.tar.zst -o /dev/null
silesia.tar.zst     : 211975168 bytes  
$ zstd -D dict_new -d silesia.tar.zst -o /dev/null
zstd: error 11 : Allocation error : not enough memory 
```

**Expected behavior**
 I would expect to get an error code more closely related to the underlying problem, such as `ZSTD_error_dictionary_wrong` or `ZSTD_error_dictionary_corrupted`.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: 1.5.1 (also confirmed on 1.5.3)

**Comment by Cyan4973** [comment]
Surprising.
I tried the same test, and got : 
```
Decoding error (36) : Dictionary mismatch
```

**Comment by embg** [comment]
> Surprising. I tried the same test, and got :
> 
> ```
> Decoding error (36) : Dictionary mismatch
> ```

Did you test with a large file like silesia.tar?

**Comment by Cyan4973** [comment]
> Did you test with a large file like silesia.tar?

Yes,
same outcome.

**Comment by embg** [comment]
> > Did you test with a large file like silesia.tar?
> 
> Yes, same outcome.

Strange, I'll try to figure out what's causing it then since it doesn't reproduce on your machine...

**Comment by embg** [comment]
Problem is a bug in the python code: it should be `8:` rather than `9:`. Fixing that bug causes zstd to return `Decoding error (36) : Dictionary mismatch` as desired.

For future reference, instead of the Python code I could have trained two dictionaries using the `--dictID=#` flag. Thanks @Cyan4973 for helping me debug.
