### ISSUE TITLE
Can we set the input buffer point same as the output buffer point? ( just for version 1.3.7) 

### ISSUE THREAD

**Issue by Hlinbit** [facebook/zstd#3313]
This question is just about streaming compression in version 1.3.7 .

Well, after reading the code about using examples in zstd, I wonder why we need to allocate two memory areas to contain input buffer and out buffer respectively. However, I have tested that output and input share the same memory area to compress the data. It works well and the compression result is correct. So can I use the same memory area for output and input in our project? Is this safe? 

Hope for your reply!

**Comment by terrelln** [comment]
No, it is not safe. This may work sometimes, but zstd reserves the right to use optimizations that break this model.

In fact, if the first operation you do is with `ZSTD_compressStream2(cctx, &out, &in, ZSTD_e_end)` then it will already not work.
