### ISSUE TITLE
Compression level 1 much better than all levels 2-15

### ISSUE THREAD

**Issue by jonashaag** [facebook/zstd#3314]
**Describe the bug**

For this file: https://conda.anaconda.org/conda-forge/linux-64/repodata.json the compression level 1 is much better than all levels 2-15.

**To Reproduce**

```
for l in $(seq 0 19); do echo $l; zstd -$l -f repodata.json; done
```

Output:

```
0
repodata.json        : 13.15%   (   219 MiB =>   28.8 MiB, repodata.json.zst)
1
repodata.json        : 11.52%   (   219 MiB =>   25.2 MiB, repodata.json.zst)
2
repodata.json        : 11.87%   (   219 MiB =>   26.0 MiB, repodata.json.zst)
3
repodata.json        : 13.15%   (   219 MiB =>   28.8 MiB, repodata.json.zst)
4
repodata.json        : 13.59%   (   219 MiB =>   29.7 MiB, repodata.json.zst)
5
repodata.json        : 12.94%   (   219 MiB =>   28.3 MiB, repodata.json.zst)
6
repodata.json        : 12.49%   (   219 MiB =>   27.3 MiB, repodata.json.zst)
7
repodata.json        : 12.32%   (   219 MiB =>   27.0 MiB, repodata.json.zst)
8
repodata.json        : 12.08%   (   219 MiB =>   26.4 MiB, repodata.json.zst)
9
repodata.json        : 12.38%   (   219 MiB =>   27.1 MiB, repodata.json.zst)
10
repodata.json        : 12.26%   (   219 MiB =>   26.8 MiB, repodata.json.zst)
11
repodata.json        : 12.21%   (   219 MiB =>   26.7 MiB, repodata.json.zst)
12
repodata.json        : 12.21%   (   219 MiB =>   26.7 MiB, repodata.json.zst)
13
repodata.json        : 12.29%   (   219 MiB =>   26.9 MiB, repodata.json.zst)
14
repodata.json        : 12.18%   (   219 MiB =>   26.7 MiB, repodata.json.zst)
15
repodata.json        : 12.13%   (   219 MiB =>   26.5 MiB, repodata.json.zst)
16
repodata.json        : 10.66%   (   219 MiB =>   23.3 MiB, repodata.json.zst)
17
repodata.json        : 10.18%   (   219 MiB =>   22.3 MiB, repodata.json.zst)
18
repodata.json        : 10.25%   (   219 MiB =>   22.4 MiB, repodata.json.zst)
19
repodata.json        :  9.95%   (   219 MiB =>   21.8 MiB, repodata.json.zst)
```

**Expected behavior**

I would expect a mostly negative correlation between compression level and size.

**Screenshots and charts**
If applicable, add screenshots and charts to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS 13.0.1
 - v1.5.2
 - Installed from Homebrew

**Comment by daniellerozenblit** [comment]
This is not necessarily a bug, and can definitely occur. There is _generally_  a negative correlation between compression level and compressed size, however, this is not always the case. Issue [2973](https://github.com/facebook/zstd/issues/2973) observes a similar phenomena.

**Comment by jonashaag** [comment]
Thanks, I’m aware that this correlation does not always hold. I just wanted to report this here to have it documented. Feel free to close.

**Comment by jonashaag** [comment]
Is there something special about level 1 that makes it perform so well in those cases? If so I guess it is systematic and could be „fixed“/worked around in higher levels. 

If nothing special, naïve  idea: implement „multi mode“ compression eg `zstd -1+15` that performs compression with multiple levels and takes the best output. Could easily be done as an external tool as well.

**Comment by daniellerozenblit** [comment]
Thank you for documenting! If there is a systematic issue, this sample could be helpful to analyze for future improvements.

I am not sure there is anything special about level 1 in particular. However, as described in the previous issue, we sometimes observe a reinforcing problem in higher levels that lead to suboptimal solutions. 

We actually do have a tool, [paramgrill](https://github.com/facebook/zstd/tree/v1.3.7/tests#readme), that finds optimal compression parameters given some constraints (i.e. speed).

**Comment by Cyan4973** [comment]
> Is there something special about level 1 that makes it perform so well in those cases? If so I guess it is systematic and could be „fixed“/worked around in higher levels.


Level 1 is looking for larger matches, at the expense of shorter ones.
It's essentially a "bet", originally selected for better speed.

Level 1 also have less capabilities to find matches, which, in this special case, tends to help because finding more (shorter) matches actually mess with the higher level repetition logic.

But that's really specific to this input. In most cases, more and shorter matches win the compression ratio battle.

Larger matches can be replicated for higher compression level, by forcing the match length : `--zstd=mml=7`. This will help compression ratio for this file, though not necessarily beat level 1.

Unfortunately, there is no "one size fits all" lesson that can be generally applied everywhere.

**Comment by jonashaag** [comment]
Thanks! I have no understanding of the science of compression algorithms so pardon my naive question: would trying a few different match sizes before actually starting to compress solve this? (Or maybe more generally trying a few different levels.)

I’m aware that you can use an external tool to find a good compression level but I wonder if one could come up with a heuristic robust and efficient enough to be included in the main program and then `-15` saying that 15 is the _maximum_ level that Zstd may use?
