### ISSUE TITLE
Is there a document describing the compression strategy of zstd?

### ISSUE THREAD

**Issue by huhu0823** [facebook/zstd#3326]
First off, I love zstd and thanks for your work - I've used it multiple times with great success.
My question is ... I want to learn the compression strategy of zstd，but I can't find relevant information on the Internet.

**Comment by Cyan4973** [comment]
If by compression strategies you mean the advanced parameter that can be selected with `--zstd=strategy=X`,
I'm afraid there is no further guidance than "higher numbers lead to higher compression ratios and slower speeds".

Going further than that requires some pretty deep technical expertise, and they are categorized as implementation details, meaning they change overtime (and have already changed multiple times in the past).

At this level of detail, there is no other documentation than the code itself (which can be consulted within `zstd/lib/compress/`).

**Comment by huhu0823** [comment]
Thank you for your reply！Time can solve everything
