### ISSUE TITLE
Compilation description

### ISSUE THREAD

**Issue by tansy** [facebook/zstd#3358]
There are things and features in the compilation that could and should be controlled but they are not described in any way. I talk about turning on/off zlib/lzma/lz4/threads support/features.
I found that only way to do it is manual edition of Makefile and they have to be investigated beforehand as well.

Would you mind to give some simple description in README or better in INSTALL file, what the options are and how to control them? Ideally from command line, without editing.

**Comment by Cyan4973** [comment]
Did you notice [this section](https://github.com/facebook/zstd/tree/dev/programs#compilation-variables) of documentation ?

**Comment by tansy** [comment]
> Did you notice this section of documentation?

No. I checked `Readme` and `doc/*`, not `programs/Readme`. Did not expect to find it there.

BTW. It would be clearer if introduction or closing of this section explained how to use these variables with examples, rather than inlining examples in a text. It's unintelligible. Also using \`\`\` and giving commands in separate line/s would help.
Examples:
```
$ make zstd HAVE_THREAD=0
$ make zstd HAVE_ZLIB=1
$ make zstd ZSTD_LEGACY_SUPPORT=2 ZSTD_NOCOMPRESS=1 BACKTRACE=1
```
\`$' denotes shell/command prompt.

**Comment by tansy** [comment]
Last question - how to make zstd dynamically linked to libzstd? I found this target \`zstd-dll' in programs/Makefile but I got [undefined references](https://paste.ee/p/2nVqz) to \`POOL_xxx' in \`pool.o' which is not part of libzstd.so although it is in 'statically' linked zstd.

**Comment by Cyan4973** [comment]
This is currently not possible unfortunately, and not planned to be.
The `zstd` CLI is designed to work with a specific version of `libzstd`,
and as a consequence must be linked against the static library `libzstd.a`.
