### ISSUE TITLE
Document that ZSTD_checkCParams moves the goalposts on ZSTD_compressionParameters.searchLength bounds

### ISSUE THREAD

**Issue by indygreg** [facebook/zstd#337]
ZSTD_compressionParameters adjusts the minimum and maximum search length constraints when certain strategies are used. I discovered this the hard way when effectively fuzzing that ZSTD_initCStream_advanced accepted all ZSTD_compressionParameters permutations.

I reckon there should be in a comment in zstd.h documenting this behavior.

**Comment by Cyan4973** [comment]
Is this request specifically about `ZSTD_compressionParameters.searchLength` field ?

**Comment by indygreg** [comment]
Yes.

**Comment by Cyan4973** [comment]
Right,
indeed, min and max values of `searchLength` depend on `strategy`.

Maybe they should be defined as functions instead, to generate a value depending on `strategy`.

**Comment by Cyan4973** [comment]
`searchLength` limits commented in `zstd.h` v1.1.0
