### ISSUE TITLE
Improve help/usage (`-h`) formatting

### ISSUE THREAD

**Issue by jonpalmisc** [facebook/zstd#3383]
**Is your feature request related to a problem? Please describe.**
The help output is rather difficult to parse visually and is somewhat unconventional compared to many other programs. I think giving it a makeover would be beneficial.

**Describe the solution you'd like**
I'd like to see the help output rewritten/reformatted so that it is easier to read and parse.

**Describe alternatives you've considered**
I could be more tolerant of the current output.

**Additional context**
I'm actually interested in tackling this problem myself, but wanted to create an issue first to:
- see if this is something others are interested in; and
- find out if the current help formatting is "set in stone" or not open to changes before I get ahead of myself.

Please advise&mdash;if changes to the help output are welcome, I'd happily PR changes that I think are reasonable.

**Comment by Cyan4973** [comment]
Yes, this is a good idea.

**Comment by jonpalmisc** [comment]
I will start working on these changes. Thanks!

**Comment by Cyan4973** [comment]
#3385 merged
