### ISSUE TITLE
Mark v1.5.x deprecated functions as deprecated

### ISSUE THREAD

**Issue by embg** [facebook/zstd#3405]
We have a number of comments like 

> Note : this prototype will be marked as deprecated and generate compilation warnings on reaching v1.5.x

where the prototypes aren't actually marked as deprecated. For example: https://github.com/facebook/zstd/blob/90597d78eadadae7acf3633ab4d81ef7c4e6057f/lib/zstd.h#L2445-L2447

Filing an issue to remind myself to fix this.

**Comment by Cyan4973** [comment]
Yes, this is a good point @embg .
These symbols should probably be marked as `deprecated` now.
