### ISSUE TITLE
Transparent legacy decompression returns incorrect error codes

### ISSUE THREAD

**Issue by benrg** [facebook/zstd#341]
Each zstd_v##.c file has its own ZSTD_error_* enum whose values don't match the values in error_public.h. ZSTD_decompress and ZSTD_decompressStream return these codes without any translation. They also return their own v1.0 errors (such as memory_allocation), so even if you know the version of the stream there's no way to be sure what an error code means.

Since all of the old error codes are all still present in v1.0, and the numbering isn't part of the legacy API (it's not defined in zstd_v##.h), it seems like you could just delete the old enums and use the v1.0 codes.

**Comment by Cyan4973** [comment]
That's a good point @benrg .
We'll try to improve that behavior.

**Comment by Cyan4973** [comment]
"dev" update #344 , by @inikep , should solve the reported issue.

**Comment by Hotkajun** [comment]
I was unaware of the issue. Thanks?

**Comment by Cyan4973** [comment]
Fixed in v1.1.0
