### ISSUE TITLE
Support for mobile plateform Android and iOS

### ISSUE THREAD

**Issue by mackoj** [facebook/zstd#342]
Hi,

It's would be great if zstd could be build for mobile plateform.

Cheers,

**Comment by Cyan4973** [comment]
It's supposed to already possible.
We have reports of running versions under iOS and Android.

**Comment by mackoj** [comment]
Ok, but how did they compile it ? Maybe have a small documentation update on how to do it could help ? Because I tried and I don't find a way to make it work.

**Comment by nabijaczleweli** [comment]
They use a C compiler

**Comment by mackoj** [comment]
Loool

**Comment by nabijaczleweli** [comment]
No "Loool", it's true

**Comment by mackoj** [comment]
I don't say it's false. I say "Loool" because it's obvious.
What I was asking is more like how did they change the Makefile to make it work.

**Comment by mackoj** [comment]
I get it sorry i'm stupid

**Comment by Cyan4973** [comment]
There's nothing stupid in learning new things 😉  
👍

**Comment by chwma0** [comment]
> Great news,
> 
> But how did they compile it ? Maybe have a small documentation update on how to do it could help ? Because I tried and I don't find a way to make it work.

I have same question, how to compile on android?
