### ISSUE TITLE
zstd_compression_format.md has old magic number

### ISSUE THREAD

**Issue by mitchblank** [facebook/zstd#345]
https://github.com/facebook/zstd/blame/dev/zstd_compression_format.md#L147

> __`Magic_Number`__
> 
> 4 Bytes, little-endian format.
> Value : 0xFD2FB527

This is a legacy one now, the current is ...28:
```
$ grep MAGICNUMBER zstd.h legacy/zstd_v07.h
zstd.h:#define ZSTD_MAGICNUMBER            0xFD2FB528   /* v0.8 */
legacy/zstd_v07.h:#define ZSTDv07_MAGICNUMBER            0xFD2FB527   /* v0.7 */
```

Hopefully the rest of the file is current for the 0.8 format (seems to be as far as I can tell)

**Comment by Cyan4973** [comment]
Damn it, you are totally right !
Yo be updated ....

**Comment by mitchblank** [comment]
Thanks!
