### ISSUE TITLE
CLI benchmark mode should respect --format

### ISSUE THREAD

**Issue by dralley** [facebook/zstd#3463]
**Is your feature request related to a problem? Please describe.**

The `zstd` command provides very useful benchmark functionality, but it doesn't seem to take `--format` into account.  If I provide the flag `--format=gzip`, the size of the compressed file and compression ratio is identical to the one provided when running without that flag specified.

```
[dalley@thinkpad repodata]$ zstd -b3 -e10 e181f69e28d21f4e5cf9368bb14feb957a3f8dc1c3a9891cac7c2c5d1426e2a4-other.xml
 3#426e2a4-other.xml : 107952714 ->   6185975 (x17.45),  880.3 MB/s, 4167.4 MB/sml...       
 4#426e2a4-other.xml : 107952714 ->   6222700 (x17.35),  831.9 MB/s, 4145.2 MB/sml...       
 5#426e2a4-other.xml : 107952714 ->   5946069 (x18.16),  319.7 MB/s, 3478.8 MB/sml...       
...  
[dalley@thinkpad repodata]$ zstd -b3 -e9 --format=gzip e181f69e28d21f4e5cf9368bb14feb957a3f8dc1c3a9891cac7c2c5d1426e2a4-other.xml
 3#426e2a4-other.xml : 107952714 ->   6185975 (x17.45),  891.1 MB/s, 4254.5 MB/sml...       
 4#426e2a4-other.xml : 107952714 ->   6222700 (x17.35),  847.3 MB/s, 4090.5 MB/sml...       
 5#426e2a4-other.xml : 107952714 ->   5946069 (x18.16),  419.7 MB/s, 4113.3 MB/sml...       
...
```

This could be misleading if a user expects these options to combine properly, and also it's a bit of a shame that it doesn't work, because it's a very convenient way to do head-to-head comparisons.

**Describe the solution you'd like**

The benchmarking functionality should respect the `--format` flag and allow benchmarking of gzip (zlib), lzma, lz4, etc.  The default compression level as well as compression level bounds would need to be set depending on the compression type.

**Describe alternatives you've considered**

Alternatively, you could fail and print an error message when `--format` is provided if there is no desire to support benchmarking other compression formats, to avoid confusion.

**Comment by Cyan4973** [comment]
There is no plan to support the `--format` statement in the benchmark module.

Displaying an error message to avoid confusion is a good suggestion.
