### ISSUE TITLE
unexpected behavior using ZSTD_compressBlock and "zstd -d".

### ISSUE THREAD

**Issue by OstCollector** [facebook/zstd#3466]
Hi,
I am trying to compress a huge amount of streams.
I tried using boost filtering stream, which creates a cctx for each stream, but it eat too much memory.
So I am trying to use split the stream into chunks, and call ZSTD_compressBlock for each chunk, while reuse and resets a ZSTD_CCtx each chunk.

I use following code to perform compress, while in_buf has `(1 << 17)` bytes.
```
    #define WINDOW_SIZE_LOG (17)
    loop
        ZSTD_compressBegin(cctx, 1);
        ZSTD_CCtx_setParameter(cctx, ZSTD_c_windowLog, WINDOW_SIZE_LOG);
        ZSTD_CCtx_setParameter(cctx, ZSTD_c_checksumFlag, 0);
        size_t out_len = ZSTD_compressBlock(cctx, out_buf, sizeof(out_buf), in_buf, in_len);
```

Now I found the decompressed file differs from the original.
I found `zstd -d` can decompress a single block well, but when it decompresses multiple consecutive blocks, the following blocks (including second) may be corrupted.
Is such behavior expected?
If so, do you have a preferred method to compress huge number (e.g. 100k) of streams without much memory overhead?

Attached file is a simplified example, the first corruption is at ~0x60030.
[zstd-issue.tar.gz](https://github.com/facebook/zstd/files/10538327/zstd-issue.tar.gz)

**Comment by Cyan4973** [comment]
Don't use `compressBlock()`, it's unlikely to do what you want.
Moreover, this entry point is going to be deprecated soon.

If you want to produce an independently decompressible frame at every loop, prefer `ZSTD_compress2()` or `ZSTD_compressStream2()` with the `zstd_e_end` statement.

If you want to produce a block (i.e. a subdivision of a frame) at every loop, employ `ZSTD_compressStream2()` with the `ZSTD_e_flush` statement. But then, each block is not independent (it depends on previously produced blocks to be decompressible). And the `ZSTD_compressBegin()` should be outside of the loop. And the frame must be finished properly at then end, with a `zstd_e_end` statement.

**Comment by OstCollector** [comment]
Thanks, I checked the format specification and noticed that a file can contain multiple frames. So I can use ZSTD_compress2.
