### ISSUE TITLE
zstd.exe does not have FileVersion and ProductVersion defined

### ISSUE THREAD

**Issue by KrzysFR** [facebook/zstd#347]
When building the dev branch (currently at v1.0.1) on Windows, using one of the batch files under `projects\build\`, I see that `zstd.exe` (and other exe as well) do not have any `File Description`, `File Version`, `Product Name`, `Product Version` and `Copyright`defined:

![image](https://cloud.githubusercontent.com/assets/1662235/18283781/3b263a32-7467-11e6-98de-017fd46d1a3e.png)

While they are defined for `zstdlib.dll`:

![image](https://cloud.githubusercontent.com/assets/1662235/18283787/442024c2-7467-11e6-8b8c-2765224ab211.png)

I think that this is because `zstdlib.vcxproj` (under `projects\VS2010`) does reference `zstdlib.rc` (which defines these properties), while the other projects (like `zstd.vcxproj`) do not. I think it would be a simple matter of moving `zstd.vcxproj` to a shared location, and have all projects reference the file?

Minor details: the Copyright is still for 2013-2015, should probably be 2013-2016.

Less minor detail: building the dev branch gives a `Product version` of `1.0.1`, but a `File Version` of `1.0.0.0`. Shouldn't be both fields either equal, or more probably `File Version` should be bumped to `1.0.1`, and `Product Version` unchanged? (if you want drop in replacement for minor bug fixes)

**Comment by inikep** [comment]
It's easy to do with Visual Studio, but our executables are generated with gcc (MinGW) because they are faster. I found however a solution at:
http://stackoverflow.com/questions/708238/how-do-i-add-an-icon-to-a-mingw-gcc-compiled-executable

**Comment by KrzysFR** [comment]
I'm using msbuild to build my binaries. I added the .rc file to the zstdlib.vcxproj a while ago, but never used the zstd.exe directly until today.

Looking at the SO answer, it seems gcc you would also need the .rc file (which is already there in the zstdlib folder), so the change would probably work for both msbuild and gcc builds

**Comment by Cyan4973** [comment]
Fixed by @inikep in v1.1.0

**Comment by KrzysFR** [comment]
Thanks!
