### ISSUE TITLE
MSVC with AVX2 compile option, C4244 warnings.

### ISSUE THREAD

**Issue by ghost** [facebook/zstd#3489]
If build with AVX2 instruction set, MSVC has dozens of C4244 warnings:
`warning C4244: 'return': conversion from 'unsigned __int64' to 'unsigned int', possible loss of data`

```c
MEM_STATIC unsigned ZSTD_countTrailingZeros64(U64 val)
{
    assert(val != 0);
#   if defined(_MSC_VER) && defined(_WIN64)
#       if STATIC_BMI2 == 1
            return _tzcnt_u64(val);
#       else
```
Adding `(unsinged)` before `_tzcnt_u64(val)` should fixes this issue.

**Comment by Cyan4973** [comment]
Maybe we should also update our Windows CI tests,
so that they can catch such issues.

**Comment by ghost** [comment]
> Maybe we should also update our Windows CI tests,

IMO no need, these codes will not be changed for a long time.

Maybe refactor the architecture-related code into one file, such as `clz`/`ctz`/`memcpy_16bytes` code, this is handy for porting to new architecture.
PR #2831 tried to refactor `clz`/`ctz` code, it removes some similar code that spread everywhere.
