### ISSUE TITLE
zstd.exe requires msys-2.0.dll

### ISSUE THREAD

**Issue by g0blin-NN** [facebook/zstd#3493]
ver zstd [1.5.4](https://github.com/facebook/zstd/releases/download/v1.5.4/zstd-v1.5.4-win64.zip)
os windows 10.0.19044.2486
Why? There is no such thing in [1.5.2](https://github.com/facebook/zstd/releases/download/v1.5.2/zstd-v1.5.2-win64.zip).
![clip](https://user-images.githubusercontent.com/66860852/218102285-1a3ae6b2-4218-4321-94f7-26745bb73435.png)

**Comment by Mathomstore** [comment]
I concur, same error here.

Was 1.5.4 compiled with MSYS2 instead of MingW w/ static ?

Reverting to 1.5.2 for now.

**Comment by Cyan4973** [comment]
The automated script that we used to produce windows binaries does not work anymore,
and unfortunately the newer script meant to replace it does produce wrong binaries, with the side effect you observed.

So I went ahead and manually generated a new `win64` package.
It seems to work fine on a local Windows 10 laptop.
Please test to see if it works fine on your side too.

**Comment by g0blin-NN** [comment]
@Cyan4973 Thank you. Everything is all right now.

**Comment by Mathomstore** [comment]
Works perfectly here too.
Many thanks.

**Comment by viceice** [comment]
the new win64 package is missing the subdir so it broke existing automatic installs 😕 

- https://github.com/visualon/docker-buildpack/pull/456
