### ISSUE TITLE
CMake: bump min CMake version to 3.18 or remove usage of `check_linker_flag()`

### ISSUE THREAD

**Issue by SpaceIm** [facebook/zstd#3500]
https://github.com/facebook/zstd/pull/3392 (part of zstd 1.5.4) checks linker flags in CMake build by relying on https://cmake.org/cmake/help/latest/module/CheckLinkerFlag.html, a function available since CMake 3.18. But `cmake_minimum_required()` of main CMakeLists is still 2.8.12.
Is it intentional to use such recent feature? If it is, `cmake_minimum_required()` should be updated accordingly. Otherwise it's possible to achieve the same checks by using `check_source_compiles()` and therefore avoid constraining CMakeLists of zstd to such recent CMake version.

**Comment by Cyan4973** [comment]
We could update the minimum version of `cmake` if there is a good reason for it, but `3.18` is way too recent to become the new minimum (I think we could consider a new minimum as high as `3.5`, but no more than that to ensure a good reach).

When a feature requires a version which is higher than the minimum, it should be guarded by version checks, and offer a fallback strategy.

#3392 was added by @terrelln , so we'll need his input.

**Comment by botanegg** [comment]
To anyone who is stuck with CI pipelines - you can upgrade your cmake from kitware apt - https://apt.kitware.com/  
Look at [kitware-archive.sh](https://apt.kitware.com/kitware-archive.sh)  
This solved the problem for me

**Comment by kou** [comment]
How about just disabling the `-z noexecstack` with old CMake?
I want to use old CMake for apache/arrow.
See also: https://github.com/apache/arrow/issues/34148

**Comment by terrelln** [comment]
> How about just disabling the -z noexecstack with old CMake?

It should be safe to default to not adding the linker flag if the cmake version is too old. This PR was mostly aiming at fixing our tests, and it should be safe to skip this flag when cmake doesn't support `check_linker_flag()`. I'll put up a PR to add that.

**Comment by kou** [comment]
@terrelln Thanks for your comment! #3510 does it. Could you review the pull request?
