### ISSUE TITLE
"window-resize.sh" from "cli-tests" (zstd-1.5.4) fail on 32-bit targets.

### ISSUE THREAD

**Issue by ilyakurdyukov** [facebook/zstd#3502]
**Describe the bug**

It looks like "window-resize.sh" doesn't work on 32-bit architectures due to lack of memory?

```
FAIL: compression/window-resize.sh
FAIL: compression/window-resize.sh.check_exit
Exit code mismatch! Expected 0 but got 1
FAIL: compression/window-resize.sh.check_stdout
stdout does not match!
> diff expected actual
---
< Window Size: 1.000 GiB (1073741824 B)
```

**To Reproduce**
I got this issue when building for "i586" and "armh" targets (both 32-bit) for a linux distro, don't know if I can easily reproduce this.

**Comment by zwenna** [comment]
The problem seems to be that window-resize.sh invokes zstd with the --long=31 option which is not valid on 32-bit architectures, and zstd complains about that.

zstd: error 11 : Parameter is out of bound

I have not tested whether changing the option to "long=30" lets the test succeed, but I expect it will.

**Comment by ilyakurdyukov** [comment]
Well actually it's easy to reproduce:

```
make CFLAGS="-O2 -m32"
make -C tests test-cli-tests CFLAGS="-O2 -m32"
```

For example, on Ubuntu with "gcc-multilib" installed.

**Comment by ilyakurdyukov** [comment]
"window-resize.sh" stderr:
```
zstd: error 11 : Parameter is out of bound 
*** Zstandard CLI (32-bit) v1.5.4, by Yann Collet ***
Error : file.zst is not a file 
rm: cannot remove 'file.zst': No such file or directory
```

**Comment by ilyakurdyukov** [comment]
> I have not tested whether changing the option to "long=30" lets the test succeed, but I expect it will.

You're right, the test passes with "--long=30".
