### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [facebook/zstd#351]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/facebook/zstd/blob/b85cdabd50a86be4f086a7f9a40415f3c82aa81c/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
* [CMake](https://cmake.org/ "CMake build system")
* [Autotools](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Introduction.html "GNU build system")

**Comment by Cyan4973** [comment]
We don't necessarily need strong builder tools, since the library has very limited dependencies, mostly standard C.

There is also a [CMake project](https://github.com/facebook/zstd/tree/dev/projects/cmake) provided for those interested.

**Comment by Cyan4973** [comment]
a cmake project is provided within build/cmake .
