### ISSUE TITLE
Access to RLE or REE decoded data

### ISSUE THREAD

**Issue by alippai** [facebook/zstd#3519]
Is it possible to decode ZSTD into RLE or REE (run length encoded or run end encoded) data without fully expanding the data? I’d imagine it’s faster, cheaper for certain types of data.

**Comment by felixhandte** [comment]
Zstd does not internally use an RLE/REE representation (except in the degenerate case where an entire block is made up of only one symbol). Instead, zstd's internal intermediate representation is a series of "sequences" (see [`struct ZSTD_Sequence`](https://github.com/facebook/zstd/blob/v1.5.4/lib/zstd.h#L1243-L1278) for the public definition).

You could imagine a translation layer from sequences to RLE that would skip an intermediate materialized representation, but I think it would be difficult to make that meaningfully faster than just fully decoding and then RLE-encoding the data.

**Comment by alippai** [comment]
One value per block might be a real world case. For context I’m thinking about Parquet->Arrow transformation, where the data is often sorted and denormalized. Arrow is adding RLE (REE) array in memory representation and implementing operations on top of it.

**Comment by felixhandte** [comment]
I've filed #3520, which would expose the sequences such that they could be translated into RLE/REE by the user.

We are unlikely to want to ship that transformation directly in `libzstd`, because it sounds pretty niche, but it might be a good fit for the `contrib/` directory.

**Comment by alippai** [comment]
Thanks a lot!
