### ISSUE TITLE
Files only, not directories?

### ISSUE THREAD

**Issue by itsnotvalid** [facebook/zstd#353]
I am a bit curious when looking at the examples. There are options to zip up multiple files, but when supplying a directory, it simply skip that. Is it possible to add directory support in future generations, or we need to do it with `tar cf x/ | zstd > x.tar.zst` or `tar -I zstd -cf x.tar.zst x`?

**Comment by Cyan4973** [comment]
`zstd` has the same scope as `compress`/`gzip`/`bzip2`, so it is not an archiver.

You can compress multiple files in a directory : `zstd -r directory`.

But that's not the same as converting a directory content into a single file archive.
For this task, `tar` is needed.

**Comment by christophered** [comment]
@Cyan4973 perhaps give zstd the capability to load a list containing the files names.

**Comment by terrelln** [comment]
zstd can compress multiple files, but it will compress them individually. If you want to compress an archive, first create an uncompressed tar or zip archive, and then compress the archive with zstd.

zstd is just a compressor, and doesn't have a format for creating an archive from multiple files. [libarchive](http://www.libarchive.org/) is a library that will create compressed archives, and it has zstd support.
