### ISSUE TITLE
Can't build using Emscripten in cmake 

### ISSUE THREAD

**Issue by LeenHawk** [facebook/zstd#3550]
**Describe the bug**
The cmake build method can't pass because of "Could NOT find Threads (missing: Threads_FOUND)"

**To Reproduce**
1. git clone https://github.com/facebook/zstd.git
2. mkdir zstd/build/cmake/builddir && cd zstd/build/cmake/builddir
3. emcmake cmake .. -DCMAKE_CXX_FLAGS="-pthread" -DCMAKE_C_FLAGS="-pthread"

**Expected behavior**
Build successfully.

**Screenshots and charts**
output:
```shell
configure: cmake .. -DCMAKE_CXX_FLAGS=-pthread -DCMAKE_C_FLAGS=-pthread -DCMAKE_TOOLCHAIN_FILE=/home/saltyfish/tools/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/home/saltyfish/tools/emsdk/node/14.18.2_64bit/bin/node;--experimental-wasm-bulk-memory;--experimental-wasm-threads
-- The ASM leen identification is unknown
-- Found assembler: /home/saltyfish/tools/emsdk/upstream/emscripten/emcc
-- Warning: Did not find file leen/-ASM
-- ZSTD VERSION: 1.5.4
-- Setting build type to 'Release' as none was specified.
-- Performing Test C_FLAG_WALL
-- Performing Test C_FLAG_WALL - Success
-- Performing Test CXX_FLAG_WALL
-- Performing Test CXX_FLAG_WALL - Success
-- Performing Test C_FLAG_WEXTRA
-- Performing Test C_FLAG_WEXTRA - Success
-- Performing Test CXX_FLAG_WEXTRA
-- Performing Test CXX_FLAG_WEXTRA - Success
-- Performing Test C_FLAG_WUNDEF
-- Performing Test C_FLAG_WUNDEF - Success
-- Performing Test CXX_FLAG_WUNDEF
-- Performing Test CXX_FLAG_WUNDEF - Success
-- Performing Test C_FLAG_WSHADOW
-- Performing Test C_FLAG_WSHADOW - Success
-- Performing Test CXX_FLAG_WSHADOW
-- Performing Test CXX_FLAG_WSHADOW - Success
-- Performing Test C_FLAG_WCAST_ALIGN
-- Performing Test C_FLAG_WCAST_ALIGN - Success
-- Performing Test CXX_FLAG_WCAST_ALIGN
-- Performing Test CXX_FLAG_WCAST_ALIGN - Success
-- Performing Test C_FLAG_WCAST_QUAL
-- Performing Test C_FLAG_WCAST_QUAL - Success
-- Performing Test CXX_FLAG_WCAST_QUAL
-- Performing Test CXX_FLAG_WCAST_QUAL - Success
-- Performing Test C_FLAG_WSTRICT_PROTOTYPES
-- Performing Test C_FLAG_WSTRICT_PROTOTYPES - Success
-- Performing Test LD_FLAG_Z_NOEXECSTACK
-- Performing Test LD_FLAG_Z_NOEXECSTACK - Success
-- Performing Test C_FLAG_QUNUSED_ARGUMENTS
-- Performing Test C_FLAG_QUNUSED_ARGUMENTS - Failed
-- Performing Test CXX_FLAG_QUNUSED_ARGUMENTS
-- Performing Test CXX_FLAG_QUNUSED_ARGUMENTS - Failed
-- Performing Test C_FLAG_WA_NOEXECSTACK
-- Performing Test C_FLAG_WA_NOEXECSTACK - Failed
-- Performing Test CXX_FLAG_WA_NOEXECSTACK
-- Performing Test CXX_FLAG_WA_NOEXECSTACK - Failed
-- CMAKE_INSTALL_PREFIX: /home/saltyfish/tools/emsdk/upstream/emscripten/cache/sysroot
-- CMAKE_INSTALL_LIBDIR: lib
-- ZSTD_LEGACY_SUPPORT defined!
-- ZSTD_MULTITHREAD_SUPPORT is enabled
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if leen accepts -pthread
-- Check if leen accepts -pthread - no
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
CMake Error at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.25/Modules/FindThreads.cmake:228 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:132 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/saltyfish/tools/third_party/zstd/build/cmake/builddir/CMakeFiles/CMakeOutput.log".
See also "/home/saltyfish/tools/third_party/zstd/build/cmake/builddir/CMakeFiles/CMakeError.log".
emcmake: error: 'cmake .. -DCMAKE_CXX_FLAGS=-pthread -DCMAKE_C_FLAGS=-pthread -DCMAKE_TOOLCHAIN_FILE=/home/saltyfish/tools/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/home/saltyfish/tools/emsdk/node/14.18.2_64bit/bin/node;--experimental-wasm-bulk-memory;--experimental-wasm-threads' failed (returned 1)
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Version Debian Sid
 - Compiler emcc 3.1.32
 - Flags "-pthread"
 - Other relevant hardware specs Default
 - Build system CMake

**Additional context**
No Emscripten problem, "emmake make" can work.

**Comment by terrelln** [comment]
Try setting `ZSTD_MULTITHREAD_SUPPORT=OFF`.

You can also try the [single file library](https://github.com/facebook/zstd/tree/dev/build/single_file_libs) which allows you to turn the zstd library (both encoder & decoder, or just the decoder) into a single file. People have had success with this for building with enscripten.

**Comment by LeenHawk** [comment]
> Try setting `ZSTD_MULTITHREAD_SUPPORT=OFF`.
> 
> You can also try the [single file library](https://github.com/facebook/zstd/tree/dev/build/single_file_libs) which allows you to turn the zstd library (both encoder & decoder, or just the decoder) into a single file. People have had success with this for building with enscripten.

But why make build system can work? It's official build system. I think it's cmake build system problem. I have [asked emscripten team](https://github.com/emscripten-core/emscripten/issues/18948#issue-1620841922), it's because emscripten don't support `-z` . Do you (I suppose zstd developers) can fix it in zstd cmake script? Or maybe we can wait emscripten fix pr merge.

**Comment by LeenHawk** [comment]
> Try setting `ZSTD_MULTITHREAD_SUPPORT=OFF`.
> 
> You can also try the [single file library](https://github.com/facebook/zstd/tree/dev/build/single_file_libs) which allows you to turn the zstd library (both encoder & decoder, or just the decoder) into a single file. People have had success with this for building with enscripten.

Hi, can we give a pr like vcpkg [fix](https://github.com/microsoft/vcpkg/pull/30174#issue-1622878454)? As emscripten don't support `-z` flag?
