### ISSUE TITLE
zstd/lib/compress/zstd_compress.c:55:17: fatal error: mem.h: No such file or directory

### ISSUE THREAD

**Issue by 11zgudu** [facebook/zstd#356]
![2016-09-09-181402_883x462_scrot](https://cloud.githubusercontent.com/assets/20792571/18383678/39bed52e-76b9-11e6-8a6b-bb59925ca540.png)
Please help me! Thanks!

**Comment by 11zgudu** [comment]
pip3, easy_install3 same error.

**Comment by Cyan4973** [comment]
This installation script does not come from facebook.
A recommended action is to ask support from the provider of this script.

Apparently, it seems to be missing an `-Izstd/lib` preprocessor directive.
