### ISSUE TITLE
How to allow larger windowLog size at streaming decompression stage?

### ISSUE THREAD

**Issue by sainttttt** [facebook/zstd#3560]
I'm trying to decompress a zst file which I need to include --long=31 on the command line. When I do it using the streaming_decompression.c example I get `CHECK(!ZSTD_isError(err)) failed: Frame requires too much memory for decoding`

I assume it has something to do with this:

```    ZSTD_c_windowLog=101,    /* Maximum allowed back-reference distance, expressed as power of 2.
                              * This will set a memory budget for streaming decompression,
                              * with larger values requiring more memory
                              * and typically compressing more.
                              * Must be clamped between ZSTD_WINDOWLOG_MIN and ZSTD_WINDOWLOG_MAX.
                              * Special: value 0 means "use default windowLog".
                              * Note: Using a windowLog greater than ZSTD_WINDOWLOG_LIMIT_DEFAULT
                              *       requires explicitly allowing such size at streaming decompression stage. */
```

It mentions that I have to explicitly allow a larger windowLog size during streaming decompression, but I can't see how to do that. Thanks

**Comment by ghost** [comment]
Is it possible to add a `ZSTD_d_windowLogMax` value, such as `1` for automatically using the frame request memory?

**Comment by Cyan4973** [comment]
> It mentions that I have to explicitly allow a larger windowLog size during streaming decompression, but I can't see how to do that

The following command should achieve the requested objective:
```
ZSTD_DCtx_setParameter(dctx, ZSTD_d_windowLogMax, 31);
```

See https://github.com/facebook/zstd/blob/v1.5.4/lib/zstd.h#L639 for more information.


> Is it possible to add a `ZSTD_d_windowLogMax` value, such as `1` for automatically using the frame request memory?

Well, setting `ZSTD_d_windowLogMax` to `31` effectively achieves the same outcome.

**Comment by sainttttt** [comment]
This worked, thank you!
