### ISSUE TITLE
please be more clear about rsyncable performance impact in manpage

### ISSUE THREAD

**Issue by devZer0** [facebook/zstd#3567]
manpage tells on --rsyncable:

       •   --rsyncable  :  zstd  will  periodically  synchronize the compression state to make the 
       compressed file more rsync-friendly. There is a negligible impact to compression ratio, and the
           faster compression levels will see a small compression speed hit. This feature does not work 
           with --single-thread. You probably don´t want to use it with long  range  mode,  since  it
           will decrease the effectiveness of the synchronization points, but your milage may vary.
           
           
"the faster compression levels will see a small compression speed hit"  is nothing i can confirm, please have a look at https://bugzilla.proxmox.com/show_bug.cgi?id=4605

proxmox is using --rsyncable as a default for zstd compression , which unfortunately can't be disabled.

the data i collected does not confirm that there is just a "small compression speed hit"

it's quite big difference even with default compression settings, so that should at least be documented, if not fixable.

also see https://github.com/facebook/zstd/issues/3097

i'm using v1.4.8 on debian 11

**Comment by devZer0** [comment]
i have built zstd from latest git ( it tells it's v1.5.4 ) and re-tested and it confirms what i reported at proxmox bugtracker

--rsyncable makes zstd about 3 times slower

``` 
root@dell-r620:/nvmepool/vms/images/105# time cat vm-105-disk-0.raw |/root/zstd/zstd --threads=8 >/dev/null

real	0m46.920s
user	2m24.769s
sys	0m56.565s

root@dell-r620:/nvmepool/vms/images/105# time cat vm-105-disk-0.raw |/root/zstd/zstd --rsyncable --threads=8 >/dev/null

real	2m31.753s
user	4m46.045s
sys	0m57.539s
```

**Comment by devZer0** [comment]
the file vm-105-disk-0.raw is read from ultra fast nvme drive and furthermore after first read, it's completely served from ram (arc cache) , so read rate from disk doesn't have any influence on the measurement here.

here is some even more impressive/better showcase:

```
# time /root/zstd/zstd --threads=20 -c vm-105-disk-0.raw >/dev/null

real	0m23.430s
user	2m30.326s
sys	0m24.634s

# time /root/zstd/zstd --rsyncable --threads=20 -c vm-105-disk-0.raw >/dev/null

real	2m27.337s
user	4m38.390s
sys	0m31.197s
```

system is dell poweredge r620 with dual  Xeon E5-2650L v2 @ 1.70GHz with 192GB RAM und dual INTEL datacenter P3605 NVME

**Comment by Cyan4973** [comment]
"a small compression speed hit" here seems to imply using default setting `--threads=1`.
In which case, the splitting resolution mechanism is fast enough to be only a small fraction of total compression time.

But this doesn't work when employing many threads for compression, and assuming enough I/O bandwidth to keep up, because at some point, the splitting resolution mechanism itself becomes the limiting factor.

This is a pretty high speed though. I would assume somewhere in the vicinity of 1 GB/s.

**Comment by devZer0** [comment]
>This is a pretty high speed though. I would assume somewhere in the vicinity of 1 GB/s.

yes, 1.5GB/s
