### ISSUE TITLE
A separate .dll just for unpacking zst's

### ISSUE THREAD

**Issue by lelik107** [facebook/zstd#3582]
Hello Yann! I'd like to ask you for making a separate .dll for just to unpack .zst files for the future releases.
Like 7zxa.dll or unrar.dll. So it could be easily updatable and implementable in the third party software. Zst archives became widely used these days but not so many software unfortunately support unpacking of them. I mean Windows software. libzstd is just too big and complex that's what some authors told me and they don't want the ZSTD code in the main program.  I'm neither a software developer myself nor an author so I can't tell if it's true or not. My goal is to force :) most of the authors of the software I use to support ZSTD format. It'll will be of a great help if you make this .dll.

**Comment by Cyan4973** [comment]
Well, as far as I can tell, the `win64` package available on the [release page](https://github.com/facebook/zstd/releases/latest) does contain a pre-compiled `libzstd.dll` library file.

**Comment by lelik107** [comment]
Well, as I can tell libzstd.dll contains everything to compess and decopress. But I meant a separate .dll just to decompress zst files. Without a code for compression. The project doesn't have one jet. Something like unzstd.dll.
