### ISSUE TITLE
Release missing win32 zip files. zstd-v1.5.4-win32.zip and zstd-v1.5.5-win32.zip

### ISSUE THREAD

**Issue by Kim-SSi** [facebook/zstd#3597]
**Describe the bug**
The 1.5.4 and 1.5.5 releases are missing the win32 zip files,
zstd-v1.5.4-win32.zip and zstd-v1.5.5-win32.zip

**To Reproduce**
Go to Assets on the Release pages
https://github.com/facebook/zstd/releases/tag/v1.5.5
https://github.com/facebook/zstd/releases/tag/v1.5.4

**Expected behavior**
1.5.2 has a zstd-v1.5.2-win32.zip

**Comment by Cyan4973** [comment]
We lost our ability to generate `win32` artifacts in the migration to Github Actions.
We'll see if we can make it happen again, though it will take some time, so no promise.

Another option could be to generate these artifacts manually, but this requires a properly setup Windows computer.

**Comment by Kim-SSi** [comment]
@Cyan4973 
I have opened a PR #3600 with changes to get the win32 artifacts building using GitHub Actions.

**Comment by Kim-SSi** [comment]
PR merged fixed this
