### ISSUE TITLE
zstd doesn't preserve ownership, access, or modification times

### ISSUE THREAD

**Issue by dabble** [facebook/zstd#360]
I was looking to use zstd in place of gzip and noticed that file ownership was changed
as well as modification times.

**Comment by Cyan4973** [comment]
As far as I know, `gzip` doesn't preserve ownership either; this is simply impossible with Unix right management.

Modification time is another topic.
I believe it's possible to preserve it, albeit probably only for posix / windows systems, since these concepts are out of reach from standard C.

**Comment by dabble** [comment]
With gzip, if the root user is compressing/decompressing the files, the ownership and permissions stay the same.  If a different user is compressing/decompressing the files, the permissions (644, 664, etc) stay the same instead of following the umask, but then gzip cannot change the ownership of the original file (or possibly delete the original file depending on the parent directory's permissions).

**Comment by trixpan** [comment]
:+1: 

reproducing gzip behavior instead of adopting umask eases migration of sticky tape integration

**Comment by Cyan4973** [comment]
In latest `dev` branch, `zstd` cli is now expected to preserve permissions when compressing or decompressing files

**Comment by Cyan4973** [comment]
this feature has been added to `zstd` by @inikep, and is available in latest release
