### ISSUE TITLE
Documentation on how multithreading compression is implemented?

### ISSUE THREAD

**Issue by cgbur** [facebook/zstd#3608]
I am very curious how the deterministic multithreaded compression is implemented. Not being familiar with the code it is difficult to track down or understand the approach at a high level. Is there any documentation or very specific pieces of code that I can look at to understand how this is done?

If there is no documentation, could I have a brief high level overview of the approach?

**Comment by ghost** [comment]
The data will be split into portions and compressed in parallel. The portion size can be specified by `jobSize` parameter, the overlap size can be specified by `overlapLog` parameter, usually don’t need to set these.

The multi-threaded output will be different than the single-threaded output. However, both are deterministic, and the multi-threaded output produces the same compressed data no matter how many threads used.

The multi-threaded output is a single frame, it’s larger a little. Compressing a 520.58 MiB data, single-threaded output is 273.55 MiB, multi-threaded output is 274.33 MiB.
