### ISSUE TITLE
usage for mixed files archive

### ISSUE THREAD

**Issue by tomByrer** [facebook/zstd#361]
Use case: gziped archive that contains both a large XML file & several WAV audio files (likely stereo 16bit, but may be any combo of mono/stereo, 16-24bit, various sample rates up to 192bps, 1 second small clips & multi-minute clips).
What settings are best for zstd here?

**Comment by Cyan4973** [comment]
WAV files require a delta preprocessing step to achieve good compression.
Unfortunately, since applying the delta filter requires understanding of the format,
this tends to be a manual / specific step.
There is currently no automatic / transparent solution (that I'm aware of) which can be blindly applied on all files and will only filter relevant / beneficial parts.

**Comment by Cyan4973** [comment]
Is there anything else we can do, or shall be close this issue ?

**Comment by tomByrer** [comment]
Thanks for asking.  Is 'delta preprocessing' compatible with zlib uncommpression?
I'm open to learn a manual step; not sure where to start.

But I was imagining Zstd could adjust dictionaries according to the filetype in a folder.  Another example;  archiving a web development project.  I'd assume that the JSON, XML/HTML/SVG, code, & documentation all could benefit from separate dictionaries vs being clumped together.

**Comment by Cyan4973** [comment]
'delta preprocessing' is just a preparation step, one in many possible ones, which makes compression more effective on "certain kind of data".
That's the problem by the way, "certain kind of data" is basically decided manually by some programmer.

> I was imagining Zstd could adjust dictionaries according to the filetype in a folder

This is _possible_ in theory,
but it must be organized by the user program, which is aware of filetype.
zstd stands at the same level as zlib or lzma, and has no knowledge of what is being compressed.

Archivers can do it, and this is one step above compression itself.
Famous archivers include 7-zip or FreeArc for example.
They typically group files of same type together, provide solid-mode compression, exe filters, and such. That's where preprocessing can be organized. Archivers know file types, and can make advanced decision based on that.
