### ISSUE TITLE
Use Zstd dictionary to decompress the data compressed without dictionary

### ISSUE THREAD

**Issue by heiwais25** [facebook/zstd#3626]
Hi Team, it might be a silly question, but I have a quick question on Zstd dictionary.

I have a one service that already use zstd compression before store data in database. Recently, i’ve found that the dictionary can help us improve the performance for our case. 

What I’m worried about is how the dictionary enabled compressor decompress the data which is compressed without the dictionary. I think it should support, but not sure about this. Can you help me understand this?

Thanks in advance. I’m sorry if this is already described in somewhere.

**Comment by Cyan4973** [comment]
It you attach a dictionary to a decompressor,
and decompress with this decompressor a compressed frame that doesn't need any dictionary,
then it will decompress it just fine.

**Comment by heiwais25** [comment]
Thanks! That's what I needed.
