### ISSUE TITLE
At negative levels, GCC build is much slower than MSVC build

### ISSUE THREAD

**Issue by ghost** [facebook/zstd#3628]
My program is statically linked to `zstd` v1.5.5 library.
At negative compression levels, GCC build is much slower than MSVC build.
At positive levels, the difference is not significant.

Below results are one-shot compression/decompression of `silesia.tar`.
(CPU: i5-11500, RAM: DDR4-3200 dual channel.)

MSVC 2022 (latest) build:
```
level   c_speed  d_speed  size_ratio
        (MiB/s)  (MiB/s)  (%)
-10000: 2586.14  5466.35  99.69
-5000:  2381.76  4580.10  99.50
-1000:  2276.27  4729.64  97.69
-500:   2178.41  4527.83  95.80
-300:   2024.32  4143.81  93.56
-100:   1516.61  3610.13  85.60
-50:    1294.95  2648.32  79.02
-10:    770.09   1642.64  55.60
-5:     650.73   1482.92  48.64
-3:     602.21   1335.98  44.66
-1:     524.86   1288.76  41.04
```
GCC 11.3 build, on Ubuntu 22.04 (WSL), GLIBC 2.35-0ubuntu3.1
```
level   c_speed d_speed  size_ratio
        (MiB/s) (MiB/s)  (%)
-10000: 707.15  1274.63  99.69
-5000:  663.32  1275.71  99.50
-1000:  647.33  1281.27  97.69
-500:   650.54  1282.35  95.80
-300:   645.78  1249.98  93.56
-100:   629.76  1226.93  85.60
-50:    597.30  1135.71  79.02
-10:    536.87  991.51   55.60
-5:     496.88  934.84   48.64
-3:     487.88  926.60   44.66
-1:     453.99  908.39   41.04
```
I haven't installed a real Linux, don't know if this is a WSL(Windows Subsystem for Linux) issue.
Can Linux user verify the speeds of GCC build for `silesia.tar`?

**Comment by ghost** [comment]
In real Ubuntu 22.04, it's faster.
```
level   c_speed  d_speed  size_ratio
        (MiB/s)  (MiB/s)  (%)
-10000: 1773.85  3857.94  99.69
-5000:  1767.60  3877.93  99.50
-1000:  1696.79  3860.52  97.69
-500:   1630.20  3786.60  95.80
-300:   1579.08  3694.01  93.56
-100:   1313.35  3117.87  85.60
-50:    1121.02  2638.94  79.02
-10:    755.22   1888.43  55.60
-5:     658.96   1740.68  48.64
-3:     615.80   1666.59  44.66
-1:     558.31   1607.93  41.04
```

**Comment by Cyan4973** [comment]
It's interesting, it would the first time that a report mentions Visual Studio having a speed advantage over `clang` or `gcc`
(unless you are using `clang` as back-end of MSVC?)

**Comment by ghost** [comment]
I'm not using `clang` as back-end in MSVC.
