### ISSUE TITLE
Include Windows DLLs with the releases

### ISSUE THREAD

**Issue by ararslan** [facebook/zstd#364]
First of all, excellent work here. Zstandard is awesome.

Now, currently the releases include executables on Windows. However, for embedding/linking purposes, it would be awesome if compiled 32- and 64-bit DLLs could be included as well. It's dead simple to build libzstd on Linux and OS X (there's even a Homebrew formula on OS X) but Windows is proving to be a challenge.

**Comment by Cyan4973** [comment]
Within "project" directory, there are several Windows Visual Studio projects,
a few Visual build scripts,
and a cmake script,
which can be used to create binaries, including dll.

On top of that, we are working on having automated Windows binaries in a future release.

**Comment by benrg** [comment]
If the stuff in `projects/` isn't working for some reason, here's a dead simple way to build a 1.0.0 DLL with MSVC: change to the lib directory and run

`cl -O2 -GL -LD -Fezstdlib.dll -DNDEBUG -DZSTD_DLL_EXPORT=1 -DZSTD_HEAPMODE=0 -I. -Icommon common\*.c compress\*.c decompress\*.c`

If you want dictionary builder support, add

`-IdictBuilder dictBuilder\*.c`

If you want legacy decompression support, add

`-DZSTD_LEGACY_SUPPORT=1 -Ilegacy legacy\*.c`

**Comment by Cyan4973** [comment]
`projects` directory has been renamed `build` in v1.1.0,
in the hope that more people will notice the multiple build scripts available there.
