### ISSUE TITLE
pzstd cannot decompress multiple files when supplied --stdout

### ISSUE THREAD

**Issue by gcflymoto** [facebook/zstd#3650]
**Describe the bug**
pzstd cannot decompress multiple files when supplied --stdout.

**To Reproduce**
Two file .zst files in the same location and run
% pzstd --stdout -d *.pzstd.zst
Cannot specify an output file when handling multiple inputs

**Expected behavior**
Behave as zstd would

**Desktop (please complete the following information):**
 - OS: SUSE
 - Version SUSE12
 - Compiler clang12

**Workaround**
Feed pzstd one file at a time

**Comment by terrelln** [comment]
`pzstd` is in maintenance-only mode. We aren't adding new features, and are just fixing bugs. You could likely use `xargs` to achieve this functionality.
