### ISSUE TITLE
Add static lib for MSVC

### ISSUE THREAD

**Issue by Lioncky** [facebook/zstd#3660]
___chkstk_ms is defined in libgcc, MSVC will build with error, I've checked the history #1527 #1564. 

build log:
1>libzstd_static_x86.lib(hist.o) : error LNK2019: unresolved external symbol  ___chkstk_ms，in  _HIST_countFast 
1>libzstd_static_x86.lib(fse_compress.o) : error LNK2019:  ___udivdi3，in  _FSE_normalizeCount 
1>libzstd_static_x86.lib(fse_compress.o) : error LNK2001:  ___divdi3

Anyway to fix it?

**Comment by Lioncky** [comment]
Build with vs2019 successful, close

**Comment by sefgit** [comment]
Trying to compile LLVM with zstd enabled, using Visual Studio Version 17
I get
`libzstd_static.lib(zstd_v05.o) : error LNK2001: unresolved external symbol ___chkstk_ms
`
I'm using zstd-v1.5.5-win64
