### ISSUE TITLE
Unable to compile ZSTD with BOOST

### ISSUE THREAD

**Issue by pratyush333** [facebook/zstd#3694]
I have been trying to compile boost with ZSTD for a week . I am stuck at a particular error. Please suggest what could be a solution

 zstd.obj : error LNK2019: unresolved external symbol _ZSTD_isError referenced in function "public: static void __cdec
l boost::iostreams::zstd_error::check(unsigned int)" (?check@zstd_error@iostreams@boost@@SAXI@Z) [C:\Project\MKECC\mkec
c_dawood\mkecc\externals\build\boost.vcxproj]
  zstd.obj : error LNK2019: unresolved external symbol _ZSTD_getErrorName referenced in function "public: __thiscall bo
ost::iostreams::zstd_error::zstd_error(unsigned int)" (??0zstd_error@iostreams@boost@@QAE@I@Z) [C:\Project\MKECC\mkecc_
dawood\mkecc\externals\build\boost.vcxproj]
  zstd.obj : error LNK2019: unresolved external symbol _ZSTD_createCStream referenced in function "protected: __thiscal
l boost::iostreams::detail::zstd_base::zstd_base(void)" (??0zstd_base@detail@iostreams@boost@@IAE@XZ) [C:\Project\MKECC
\mkecc_dawood\mkecc\externals\build\boost.vcxproj]
  zstd.obj : error LNK2019: unresolved external symbol _ZSTD_freeCStream referenced in function "protected: __thiscall
boost::iostreams::detail::zstd_base::~zstd_base(void)" (??1zstd_base@detail@iostreams@boost@@IAE@XZ) [C:\Project\MKECC\
mkecc_dawood\mkecc\externals\build\boost.vcxproj]
  zstd.obj : error LNK2019: unresolved external symbol _ZSTD_initCStream referenced in function "private: void __thisca
ll boost::iostreams::detail::zstd_base::do_init(struct boost::iostreams::zstd_params const &,bool,void * (__cdecl*)(voi
d *,unsigned int,unsigned int),void (__cdecl*)(void *,void *),void *)" (?do_init@zstd_base@detail@iostreams@boost@@AAEX
ABUzstd_params@34@_NP6APAXPAXII@ZP6AX22@Z2@Z) [C:\Project\MKECC\mkecc_dawood\mkecc\externals\build\boost.vcxproj]
  zstd.obj : error LNK2019: unresolved external symbol _ZSTD_compressStream referenced in function "protected: int __th
iscall boost::iostreams::detail::zstd_base::deflate(int)" (?deflate@zstd_base@detail@iostreams@boost@@IAEHH@Z) [C:\Proj
ect\MKECC\mkecc_dawood\mkecc\externals\build\boost.vcxproj]
  zstd.obj : error LNK2019: unresolved external symbol _ZSTD_flushStream referenced in function "protected: int __thisc
all boost::iostreams::detail::zstd_base::deflate(int)" (?deflate@zstd_base@detail@iostreams@boost@@IAEHH@Z) [C:\Project
\MKECC\mkecc_dawood\mkecc\externals\build\boost.vcxproj]
  zstd.obj : error LNK2019: unresolved external symbol _ZSTD_endStream referenced in function "protected: int __thiscal
l boost::iostreams::detail::zstd_base::deflate(int)" (?deflate@zstd_base@detail@iostreams@boost@@IAEHH@Z) [C:\Project\M
KECC\mkecc_dawood\mkecc\externals\build\boost.vcxproj]
  zstd.obj : error LNK2019: unresolved external symbol _ZSTD_createDStream referenced in function "protected: __thiscal
l boost::iostreams::detail::zstd_base::zstd_base(void)" (??0zstd_base@detail@iostreams@boost@@IAE@XZ) [C:\Project\MKECC
\mkecc_dawood\mkecc\externals\build\boost.vcxproj]
  zstd.obj : error LNK2019: unresolved external symbol _ZSTD_freeDStream referenced in function "protected: __thiscall
boost::iostreams::detail::zstd_base::~zstd_base(void)" (??1zstd_base@detail@iostreams@boost@@IAE@XZ) [C:\Project\MKECC\
mkecc_dawood\mkecc\externals\build\boost.vcxproj]
  zstd.obj : error LNK2019: unresolved external symbol _ZSTD_initDStream referenced in function "private: void __thisca
ll boost::iostreams::detail::zstd_base::do_init(struct boost::iostreams::zstd_params const &,bool,void * (__cdecl*)(voi
d *,unsigned int,unsigned int),void (__cdecl*)(void *,void *),void *)" (?do_init@zstd_base@detail@iostreams@boost@@AAEX
ABUzstd_params@34@_NP6APAXPAXII@ZP6AX22@Z2@Z) [C:\Project\MKECC\mkecc_dawood\mkecc\externals\build\boost.vcxproj]
  zstd.obj : error LNK2019: unresolved external symbol _ZSTD_decompressStream referenced in function "protected: int __
thiscall boost::iostreams::detail::zstd_base::inflate(int)" (?inflate@zstd_base@detail@iostreams@boost@@IAEHH@Z) [C:\Pr
oject\MKECC\mkecc_dawood\mkecc\externals\build\boost.vcxproj]
  bin.v2\libs\iostreams\build\msvc-14.3\release\address-model-32\threading-multi\boost_iostreams-vc143-mt-x32-1_82.dll
: fatal error LNK1120: 12 unresolved externals [C:\Project\MKECC\mkecc_dawood\mkecc\externals\build\boost.vcxproj]
  C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(248,5):
 error MSB8066: Custom build for 'C:\Project\MKECC\mkecc_dawood\mkecc\externals\build\CMakeFiles\081985892b2a1b0cd81616
3ebe80ac88\boost-mkdir.rule;C:\Project\MKECC\mkecc_dawood\mkecc\externals\build\CMakeFiles\081985892b2a1b0cd816163ebe80
ac88\boost-download.rule;C:\Project\MKECC\mkecc_dawood\mkecc\externals\build\CMakeFiles\081985892b2a1b0cd816163ebe80ac8
8\boost-update.rule;C:\Project\MKECC\mkecc_dawood\mkecc\externals\build\CMakeFiles\081985892b2a1b0cd816163ebe80ac88\boo
st-patch.rule;C:\Project\MKECC\mkecc_dawood\mkecc\externals\build\CMakeFiles\081985892b2a1b0cd816163ebe80ac88\boost-con
figure.rule;C:\Project\MKECC\mkecc_dawood\mkecc\externals\build\CMakeFiles\081985892b2a1b0cd816163ebe80ac88\boost-build
.rule;C:\Project\MKECC\mkecc_dawood\mkecc\externals\build\CMakeFiles\081985892b2a1b0cd816163ebe80ac88\boost-install.rul
e;C:\Project\MKECC\mkecc_dawood\mkecc\externals\build\CMakeFiles\43f646ce2a5890f73948e0acaa6559b7\boost-complete.rule;C
:\Project\MKECC\mkecc_dawood\mkecc\externals\build\CMakeFiles\e7169c7441cfcd0ea69242d553f60a89\boost.rule;C:\Project\MK
ECC\mkecc_dawood\mkecc\externals\CMakeLists.txt' exited with code 1. [C:\Project\MKECC\mkecc_dawood\mkecc\externals\bui
ld\boost.vcxproj]

I have tried all versions of Boost and ZSTD for their compartibility.

**Comment by Cyan4973** [comment]
It looks like a C vs C++ symbol mangling compatibility thing.

**Comment by pratyush333** [comment]
@Cyan4973 any suggestion to resolve it.!!!

**Comment by terrelln** [comment]
> It looks like a C vs C++ symbol mangling compatibility thing.

I'm not sure about that. It looks like the C symbols are being correctly mangled (or rather not mangled).

It looks like you just aren't linking against libzstd, since it doesn't look like any zstd symbols are available.
