### ISSUE TITLE
truncated file name in error message

### ISSUE THREAD

**Issue by ip7z** [facebook/zstd#3702]
zstd truncates file name in error message.
Is it bug?
```
zstd --test 123456789012345678.zst

3456789012345678.zst : Decoding error (36) : Frame requires too much memory for decoding 
3456789012345678.zst : Window size larger than maximum : 2147559775 > 134217728 
3456789012345678.zst : Window log larger than ZSTD_WINDOWLOG_MAX=31; not supported 
```

And the question about large window size.
Is there any zstd decoder that supports window larger than 2 GB?
Will zstd support larger than 2GB window in future?
Do we need to support larger than 2 GB window in new alternative zstd decoder?
Or we should limit the decoder code to 2 GB window?

**Comment by terrelln** [comment]
> Is there any zstd decoder that supports window larger than 2 GB?

The reference decoder doesn't currently support it, but it wouldn't be very hard to add decoder support. Encoder support would be harder.

There are a few other decoder implementations in other languages. I'm not sure what their maximum supported window size is.

Note that you have to opt-in to supporting window sizes > 128 MB in the reference decoder, to protect against obscene memory allocation.

Our spec says:

> For broader compatibility, decoders are recommended to support memory sizes of at least 8 MB. This is only a recommendation, each decoder is free to support higher or lower limits, depending on local limitations.

For Zstd decoder implementations, I'd recommend allowing opting into larger window sizes, but picking a default maximum window size of either 8 MB or 128 MB for compatibility.

> Will zstd support larger than 2GB window in future?

It is possible. This is something we've considered, and might do in the future, but don't have active plans to do.

The biggest place where we see it could be useful is to allow dictionaries >2GB for `--patch-from` mode, to allow Zstd to create deltas of very large files.

> Do we need to support larger than 2 GB window in new alternative zstd decoder?

I'd recommend picking a default maximum window size of 8 MB (for tight memory control) or 128 MB (for maximum compatibility), and allowing users to opt into larger window sizes.

It would be great to support up to 2GB of window size, and if it is easy to increase beyond 2GB, go for it.

But, if we do eventually add encoder support for >2GB windows, we'd be very careful to make users explicitly opt-in to it, knowing that decoder support will be limited to newer versions of the reference decoder.

**Comment by terrelln** [comment]
> Is it bug?

This is intentional behavior, to make sure our error messages don't go beyond 80 columns.

However, we should allow verbose logging with `-v` to write full file filenames.
