### ISSUE TITLE
Hidden files and folders are not mirrored correctly when source is a relative path

### ISSUE THREAD

**Issue by mzoellner** [facebook/zstd#3703]
**Describe the bug**
When the source of a zstd command is given as a relative path, hidden files and folders are not correctly copied to the target folder, but into the parent of the target folder.

**To Reproduce**
I created a small repository that makes it easier to reproduce the issue: https://github.com/mzoellner/zstd-repro

Imagine a folder structure like this:
```
/opt/source/file
/opt/source/.hidden-file
/opt/source/.hidden-folder/file-in-hidden-folder
```

Then run the following command
`mkdir -p /opt/target && cd /opt/source && zstd -r --output-dir-mirror /opt/target ./`

`.hidden-file.zst` and `file-in-hidden-folder.zst` will both end up in `/opt` instead of `/opt/target`

**Expected behavior**
Hidden files and folders from `source` are mirrored in `target`

**Desktop (please complete the following information):**
 - OS: Debian 12 / Ubuntu 22.04
 - Version zstd 1.5.5

**Comment by felixhandte** [comment]
Hi @mzoellner,

Thanks for the report!

I have reproduced the issue. This is the offending check:

https://github.com/facebook/zstd/blob/63779c798237346c2b245c546c40b72a5a5913fe/programs/util.c#L1122-L1123

Now I just need to figure out why this check exists before I remove it...

But I'll get a fix up shortly.

**Comment by mzoellner** [comment]
Thank you for fixing this @felixhandte 
Much appreciated.
