### ISSUE TITLE
How can I add my software to https://facebook.github.io/zstd/#other-languages

### ISSUE THREAD

**Issue by alberttwong** [facebook/zstd#3705]
Hi,

I'd like to add our database as also another user of zstd.   I can't figure how which file to edit on github.  Please help.

![Screenshot 2023-07-22 at 5 28 40 PM](https://github.com/facebook/zstd/assets/749093/47073c78-97f0-4b97-b059-155ef5a55229)

**Comment by Cyan4973** [comment]
Tell us which software it is, and provide a link that shows its usage of `zstd`.
We'll take care of the rest.

**Comment by alberttwong** [comment]
StarRocks.  https://docs.starrocks.io/en-us/latest/sql-reference/sql-statements/data-definition/CREATE%20TABLE#set-data-compression-algorithm
