### ISSUE TITLE
position of out buffer is not updated when using stream decompress API

### ISSUE THREAD

**Issue by kongsuozt** [facebook/zstd#3706]
**Describe the bug**
When using zstd_decompress_stream API, I build a compressed input buffer which have size more than 4K, but I only set input buffer's size with 4K and trying to know how many output I can get if I only decompress 4K of this compressed data. But after code running, I can see the out buf.pos do not update with a no error decompress return value.

**To Reproduce**
Test code:
       rc = zstd_compress_cctx(zctx->cctx, zctx->cout_buffer,          
                              (1 << 17), src, srcSize, &params);
       if (ZSTD_isError(rc)) {                                         
               printf("%s, rc:%x, cctx:%p, srcSize:%5d, dstSize:%5d, high:%d, low:%d, try:%d\n",
                       __func__, (unsigned int)rc,                     
                       zctx->cctx, srcSize, dstSize, high, low, try_count);
               return -EFAULT;                                         
       }                                                               

       /* decompress dst size */                                       
       in_buf.src = zctx->cout_buffer;                                 
       in_buf.pos = 0;                                                 
       in_buf.size = 4096;                                          
                                                                       
       out_buf.dst = zctx->dout_buffer;                                
       out_buf.pos = 0;                                                
       out_buf.size = 1 << 17;                               
                                                                       
       rc = zstd_decompress_stream(dstream, &out_buf, &in_buf);        
       if (ZSTD_isError(rc)) {                                         
               printf("stream decompress failed:%d, in:%p %d %d, out:%p, %d %d\n",
                       rc, in_buf.src, in_buf.pos, in_buf.size,        
                       out_buf.dst, out_buf.pos, out_buf.size);        
               return -EIO;                                            
       }                                                               
       printf("stream decompress ok:%d -> %d, in:%p %d %d, out:%p, %d %d, try:%d\n",
               rc, tmp, in_buf.src, in_buf.pos, in_buf.size,           
               out_buf.dst, out_buf.pos, out_buf.size, try_count);     

log iof print, pos of out buffer is not updated:
erofs_compressor_zstd_setlevel, set level to 3, wksp_size:910072, cctx:0x5620225da0e0
ZSTD_decompressStream, bufferSize:262144, static:620296, size:95944
stream decompress ok:61045 -> 65141, in:0x562022599cb0 4096 4096, out:0x5620225ba0d0**, 0** 131072, try:1

**Expected behavior**
out_buf.pos should updated after API return no-failed value.

**Screenshots and charts**
If applicable, add screenshots and charts to help explain your problem.

**Desktop (please complete the following information):**
ubutu 2020

**Additional context**

**Comment by felixhandte** [comment]
Unless instructed otherwise ([via e.g., `ZSTD_c_maxBlockSize`](https://github.com/facebook/zstd/blob/v1.5.5/lib/zstd.h#L2177-L2187)), Zstd cuts the input into 128KB chunks and compresses each of those chunks as a block. The decompressor must receive a whole block in order to begin decompressing that block.

In this case, `zstd_decompress_stream()` is accurately reporting its status:

1. It has not had an error.
2. It has consumed the input presented to it (into an internal buffer until it can accumulate a full block).
3. Since it does not yet have a full block, it has no output to return yet.

**Comment by felixhandte** [comment]
Please re-open if you have further questions.
