### ISSUE TITLE
Document best practices on how to use zstd in a memory constrained environment

### ISSUE THREAD

**Issue by mykaul** [facebook/zstd#3708]
For example, set ZSTD_c_windowLog to ZSTD_WINDOWLOG_MIN , set ZSTD_c_hashLog to ZSTD_HASHLOG_MIN ... but what else (and separate between dfast and fast modes?).
This is specifically targeting memory constrained environments, not for general use case, I reckon.

**Comment by Cyan4973** [comment]
Is it for the `libzstd` library specifically, or also for the `zstd` CLI program ?

**Comment by terrelln** [comment]
See https://github.com/facebook/zstd/wiki/Using-Zstandard-in-a-memory-constrained-environment

**Comment by mykaul** [comment]
Thanks @terrelln  ! 
CC @michoecho
