### ISSUE TITLE
Compatibility between compress/decompress APIs

### ISSUE THREAD

**Issue by cbi42** [facebook/zstd#3711]
**Context:**
Hi - I am working on enabling the checksum flag for zstd compression in RocksDB. For compression, RocksDB currently uses `ZSTD_compress_usingDict()` when not using dictionary (passes in an empty string) or not having a digested dictionary, and `ZSTD_compress_usingCDict()` otherwise. Similarly, for decompression, RocksDB uses `ZSTD_decompress_usingDict()` and `ZSTD_decompress_usingDDict()` depending on whether a digested dictionary is available. After reading the zstd manual and #1534, it seems that `ZSTD_compress2()` is needed to enable checksum and I am planning the following usage:

Compression:
```
ZSTD_CCtx* context = ZSTD_createCCtx();
ZSTD_CCtx_setParameter(context, ZSTD_c_compressionLevel, level);
ZSTD_CCtx_setParameter(context, ZSTD_c_checksumFlag, 1);
...
if (digested_dict) {
  ZSTD_CCtx_refCDict(context, digested_dict);
} else {
  ZSTD_CCtx_loadDictionary(context, raw_dict_ptr, raw_dict_size);
}

ZSTD_compress2(context, ...)
```

For decompression, I assume no change is needed. I may use `ZSTD_decompressDCtx()` in the future if there is a need to specify decompression parameter (and use `ZSTD_DCtx_loadDictionary()` and `ZSTD_DCtx_refDDict()` to set dictionary).

**Question:**
My concern is about compatibility when a user switches between new and old versions of RocksDB and wanted to know if this change is safe. In particular, when dictionary is empty, I am wondering if `ZSTD_compress2()` is compatible with `ZSTD_decompress_usingDict()`, and if `ZSTD_compress_usingDict()` is compatible with `ZSTD_decompressDCtx()`?

Not sure if this is the right place to post question. If not, I'll move the question to the right channel. Thanks.

**Comment by Cyan4973** [comment]
If I understand the context correctly, the answer is yes.
`ZSTD_compress2()` generates frames as valid as `ZSTD_compress_usingDict()` or `ZSTD_compress_usingCDict()`, just with more fine parameter controls.

Decompression remains compatible with all variants mentioned above,
presuming you already pass the relevant dictionary for each frame whenever needed.
Already deployed decoders will have no problem decoding new frames with checksum enabled.

**Comment by cbi42** [comment]
Thanks @Cyan4973!
