### ISSUE TITLE
Document and the compiler support and specify the C/C++ standard to use

### ISSUE THREAD

**Issue by ShamrockLee** [facebook/zstd#3715]
**Is your feature request related to a problem? Please describe.**

From both the source code and the documentation, there's no way to determine the minimum supported compiler versions and C/C++ specification.

From the source code, there are multiple lines checking if `__GNUC___ > 4` and even `__GNUC__ == 4 && __GNUC_MINOR__ > 5`, but compilation with GCC 4.9 fails complaining builtin-function missing and `-std=c++11` not specified but `constexpr` used.

**Describe the solution you'd like**

Document the supported compilers and the minimum versiton of each of them, and specify the C/C++ standard to uses in the build flag inside `Makefile`s.

**Describe alternatives you've considered**

Regarding the C/C++ standard, they can be documented instead of being specified directly. Nevertheless, it would be nice to have both.

**Additional context**

The build above can be reproduced with Nix and Nixpkgs.

Here's the one-liner to get the attached build log:

`docker run -it --rm nixos/nix:2.17.0 nix-build --no-out-link --expr "let nixpkgs-source = builtins.fetchTarball \"https://github.com/NixOS/nixpkgs/archive/48e82fe1b1c863ee26a33ce9bd39621d2ada0a33.tar.gz\"; lib = import \"\${nixpkgs-source}/lib\"; pkgs = import nixpkgs-source { }; in pkgs.zstd.override { stdenv = pkgs.gcc49Stdenv; }" | tee nix_build_zstd_with_gcc49Stdenv.log`

[nix_build_zstd_with_gcc49Stdenv.log](https://github.com/facebook/zstd/files/12238368/nix_build_zstd_with_gcc49Stdenv.log)

**Comment by Cyan4973** [comment]
The `zstd` source code is designed to support `C90` compilers.

This is valid for `zstd` (and `libzstd`) proper, 
not necessarily for surrounding tests, tools and example programs.

**Comment by Cyan4973** [comment]
By the way, the source code's standard (`C90`) is already described in : 
https://github.com/facebook/zstd/blob/dev/CONTRIBUTING.md#c90
