### ISSUE TITLE
Unclear license status

### ISSUE THREAD

**Issue by safinaskar** [facebook/zstd#3717]
README states: "Zstandard is dual-licensed under [BSD](https://github.com/facebook/zstd/blob/dev/LICENSE) and [GPLv2](https://github.com/facebook/zstd/blob/dev/COPYING)". Unfortunately such sentence is very unclear.

It doesn't tell whether these licenses are connected with "and" or "or".

In case you never heard that such distinction may be important here is link with explanation: https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/ , see section "D.4 Composite license expressions".

Please note, that this distinction is extraordinary important. Such decision should not be taken lightly. "Or" means that user of zstd may choose license. "And" means that user must abide to both. Choosing "or" means that zstd is "effectively BSD", i. e. that it is distributed by permissive license. But choosing "and" makes zstd "effectively GPL", i. e. copyleft.

You may say: "but README literally says "and" ". Well, yes, naive direct reading of README may suggest that "and" is intended. But I don't think this is what you really meant. Again: choosing "and" will turn zstd into copyleft software and thus its use in proprietary products will be disallowed.

So, please choose one of these two options, fix README and widely announce result. Users should be aware of such change in any case. Again: this is very important

**Comment by aqrit** [comment]
`grep --include \*.h --include \*.c -r -L "You may select, at your option, one of the above-listed licenses."`

so the oddballs are:
zlibwrapper (https://www.zlib.net/zlib_license.html)
divsufsort (MIT)
contrib files (who cares?)

**Comment by safinaskar** [comment]
Okay, so it seems that in _core_ files, such as https://github.com/facebook/zstd/blob/d857369028d997c92ff1f1861a4d7f679a125464/lib/compress/zstd_compress_superblock.c , license specified properly. So, I'm exaggerated issue, I'm sorry about this. Still, please, properly specify the license in README

**Comment by terrelln** [comment]
Zstd is dual licensed under BSD or GPLv2, and we [test](https://github.com/facebook/zstd/blob/dev/tests/test-license.py) that all files that are part of the library or CLI (under `lib/` and `programs/`) are properly licensed.

But you're right, we should fix the wording in our README to be more clear, and match the licensing in our headers, which is correct.

**Comment by bilbothebaggins** [comment]
I'm piggybacking this question here since I think those that already commented might have some insight into this:

Can anybody explain why the zstd sources are even dual-licensed BSD and GPL? BSD-3-Clause is already compatible with GPL, so I fail to see the point of this dual licensing. (It's not that it hurts functionally, it's just confusing.)

Ref: https://opensource.stackexchange.com/questions/14830/what-is-the-point-of-dual-licensing-a-library-under-bsd-3-clause-and-gpl

**Comment by terrelln** [comment]
@bilbothebaggins Initially Zstd was licensed under BSD + PATENTS clause, which was not compatible with GPL. Zstd was then dual licensed under GPL in order to be merged into the Linux kernel. Later, the PATENTS clause was removed from the BSD license.
