### ISSUE TITLE
Adding ZSTD_DCtx_loadDictionary_advanced() to the stable API

### ISSUE THREAD

**Issue by nidhijaju** [facebook/zstd#3723]
Based on the discussion in https://github.com/WICG/compression-dictionary-transport/issues/45, we decided to support only raw dictionaries for compression dictionary transport for now.

This means that implementations of compression dictionary transport with zstd have to use [ZSTD_DCtx_loadDictionary_advanced()](https://github.com/facebook/zstd/blob/969e54f26ee5e03677d47b6449be02fe48e6d349/lib/decompress/zstd_decompress.c#L1680) with [ZSTD_dct_rawContent](https://github.com/facebook/zstd/blob/969e54f26ee5e03677d47b6449be02fe48e6d349/lib/zstd.h#L1314), but this is part of the experimental advanced API. Is it possible to make this part of the stable API so that we don't have to use static linking for this use case?

**Comment by felixhandte** [comment]
Hi @nidhijaju,

We plan to promote a bunch of symbols to the stable API in v1.6.0, and these symbols are definitely good candidates for inclusion.

But as I understand it, the Zstd that Chrome depends on is in the Chrome source tree / repository. So a particular Chrome revision is guaranteed to use the Zstd version checked in at that revision. If that guarantee holds, this makes it safe to use the unstable APIs, whether or not zstd is eventually statically or dynamically linked in, and you should feel free to define `ZSTD_STATIC_LINKING_ONLY` and use these symbols.

Does that make sense?

**Comment by nidhijaju** [comment]
Hi @felixhandte, sounds good!

Yes, that is true for Chrome, but just thought it would be good to move to the stable API if that is what is being recommended to use for the Compression Dictionary Transport work.

Anyway, thank you!
