### ISSUE TITLE
CLI: `-q` flag doesn't function when used after `-V`(`--version`)

### ISSUE THREAD

**Issue by yzqzss** [facebook/zstd#3727]
**Describe the bug**

The zstd man page states:

> -V, --version: display version number and exit. Advanced : -vV also displays supported formats. -vvV also displays POSIX support. -q will only display the version number, suitable for machine reading.

But I have noticed that when `-q` is used after `-V`, the `-q` flag seems to lose its effect and the output doesn't only display the version number.

**Screenshots and charts**

`-q` after `-V`

```shell
$ zstd -V -q
*** Zstandard CLI (64-bit) v1.5.5, by Yann Collet ***
$ zstd -vV -q
*** Zstandard CLI (64-bit) v1.5.5, by Yann Collet ***
*** supports: zstd, zstd legacy v0.5+, gzip, lzma, xz 
$ zstd -vvV -q
*** Zstandard CLI (64-bit) v1.5.5, by Yann Collet ***
*** supports: zstd, zstd legacy v0.5+, gzip, lzma, xz 
zlib version 1.2.13
lz4 version Unsupported
lzma version 5.4.2
_POSIX_C_SOURCE defined: 200809L
_POSIX_VERSION defined: 200809L 
PLATFORM_POSIX_VERSION defined: 200809L
```

`-V` after `-q` (it's good)

```shell
$ zstd -q -V
1.5.5
$ zstd -q -vV (or zstd -v -q -V)
*** Zstandard CLI (64-bit) v1.5.5, by Yann Collet ***
$ zstd -q -vvV (or zstd -vv -q -V)
*** Zstandard CLI (64-bit) v1.5.5, by Yann Collet ***
*** supports: zstd, zstd legacy v0.5+, gzip, lzma, xz 
```

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.2
 - Version: 1.5.5
 - Build system: just `make` the v1.5.5 from github release

**Comment by Cyan4973** [comment]
`zstd -h` :
` -V     : display Version number and exit`

`-V` has a specific behavior : it acts immediately, and exit the program. Which means, any flag that comes after it is effectively ignored.

**Comment by yzqzss** [comment]
Could a hint about this be added to the man docs?

**Comment by Cyan4973** [comment]
documentation updated in #3928 to reflect that commands sent after `-V` are not parsed, 
therefore modifiers such as `-v` and `-q` must be passed before.

**Comment by yzqzss** [comment]
Thanks!
