### ISSUE TITLE
Zstd Encode on limited resources

### ISSUE THREAD

**Issue by AlexandrosEmvoliadis** [facebook/zstd#3735]
Hello, i basically have 2 questions:

1) I'm setting an empty dictionary in the encoders dict parameter (as b""), does this indeed initialize an empty dictionary and, thus, saves memory from loading a pre-defined, static dictionary?

2) Does the size of the "to-be-compressed" object plays a role in the size of the zst encoder object size? For example, suppose an object of approx. 5.5kB, how large will be the encoder object given an empty dictionary and a quality level of 22?

Thank you

**Comment by Cyan4973** [comment]
In general, an empty dictionary is expected to behave the same as no dictionary at all.

Now, exact specifics depend on the details, and the above scenario could be achieved in multiple different ways.
For a more accurate answer, employing code (or script) samples helps ensuring that the exact details of your configuration are well specified and understood.
