### ISSUE TITLE
More actual benchmarks at zstandard web site 

### ISSUE THREAD

**Issue by stefano2734** [facebook/zstd#3744]
**Is your feature request related to a problem? Please describe.**

at Zstandard web site benchmarks are with version 1.3.4 and 1.4.5.
There are great differences in some tests to actual. Version 1.5.5

https://facebook.github.io/zstd/

**Describe the solution you'd like**

please new runs of benchmark with actual version of zstd and with actual versions of zlib and others.

**Describe alternatives you've considered**

The alternative is doing nothing and wait for other versions of zstandard.

**Additional context**

**Comment by isker** [comment]
A benchmark suite for zstd vs competitors like you've got in xxhash would be greatly appreciated.

All of the existing benchmark data I can find online comes from point-in-time measurements that go stale quite quickly.  Everyone is using 5+ year old versions of zstd and brotli.  The squash benchmarks are ancient in 2024.

If anyone has any recommendations for good benchmarks with bad SEO 🌞 I'd love to hear them.

**Comment by Cyan4973** [comment]
We'll update the benchmark numbers for the next release.
