### ISSUE TITLE
Enough data for multi threads

### ISSUE THREAD

**Issue by OkobaPatino** [facebook/zstd#3751]
For multi thread compression, what is the way to estimate how much data is enough so each thread have something to compress?
For example, for Level 3, and 4 threads, is 256MB enough for them to have enough work?

I tried to give small files (64MB) and ask ZSTD CLI to compress them, and increasing threads won't change much and even CPU usage of my PC shows that either the threads didn't start or didn't get to work, before the compress is all done.

**Comment by Cyan4973** [comment]
I think level 3 and 4 require ~ 8 MB per thread,
meaning that 64MB should be enough data to run 8 threads simultaneously.

**Comment by OkobaPatino** [comment]
How do you calculate that? As I saw the effect you are talking about, 16MB for 2 threads is faster, but 8MB for 2 threads is slower.

**Comment by Cyan4973** [comment]
Well, 8 MB will use a single thread.

You can influence that quantity by taking direct control of the "job size".
See "Advanced Compression Options" in `man zstd` : 

```
ADVANCED COMPRESSION OPTIONS
       ### -B#: Specify the size of each compression job. This parameter is only available when multi-threading is enabled. Each compression job is run in parallel, so this value indirectly impacts the nb of active threads.
       Default job size varies depending on compression level (generally 4 * windowSize). -B# makes it possible to manually select a custom size. Note that job size must respect a minimum value which is enforced transparently.
       This minimum is either 512 KB, or overlapSize, whichever is largest. Different job sizes will lead to non-identical compressed frames.
```

**Comment by OkobaPatino** [comment]
Thank you.
One question for me is that I see different size result when I use threads. Mostly slight increase in size (8KB for a 32MB).
Can I ask why there is a little increase?
Here are some numbers I made for my test, using Level 3:
Raw data: 33,554,432
Compressed with 1 thread: 825,167
Compressed with 2 threads: 833,163
Compressed with 8 threads: 833,163 (Same as 2)

**Comment by Cyan4973** [comment]
Using the `zstd` CLI, there shouldn't be any difference whatever the nb of threads you use.
If you are seeing a difference when using 1 thread, I presume you are not using 1 worker, as in `-T1` (which is the default), but you are using the `--single-thread` mode, which is different.
In which case, it's known that `--single-thread` will produce a different output than any `-T#` output.
That's due to internal reasons which are too long to explain here, but let's say there are near-infinite ways to compress a file, and subtle differences in the way data is processed result in different compressed payloads.
`--single-thread` _tends_ to produce slightly more compressed payloads, but really very slightly, i.e. negligible, and that's not even guaranteed. Depending on input and compression level, `-T#` might actually win from time to time. In most cases, the difference is not worth talking about.

**Comment by OkobaPatino** [comment]
I am using C API and using ZSTD_c_nbWorkers. I don't set it for 1 thread and set it to 2 or 8 for others.
Is it because I don't set it for 1?

**Comment by Cyan4973** [comment]
Yes,
in the API, when `ZSTD_c_nbWorkers` is not set, it's essentially equivalent to `--single-thread`.

**Comment by OkobaPatino** [comment]
Thank you.

Is there a documentation about how they are different? And why there is a difference? 
Surprising to me, for 1 in 10 cases, I see multi threaded version makes smaller sizes too.

I assume, in multi thread version, it splits the data in job-size frames, and give them to each thread. But if that was the case, it should decrease the compression rate as they see different independent chunks. I saw couple of issue discussing multi thread implementation but they are very old and I guess there are a lot of changes.

**Comment by Cyan4973** [comment]
This should be treated as an implementation detail. There is no contract to publish and continuously guarantee.

Explaining the differences would require a fairly deep dive into data compression systems.
Suffice to say, there are near-infinite compressed payloads that can represent the same data, and any subtle variation in the processing pipeline can result in a completely different set of choices after this point. It's no wonder when 2 pipelines are very different that they end up making different valid choices when producing their compressed payloads.
But that is a moot point anyway if the compression ratio difference is negligible at the end.
It only matters for security-focused systems that require reproducible payloads.

**Comment by OkobaPatino** [comment]
Thank you for such helpful answer.
And thank you for ZSTD.
