### ISSUE TITLE
How to decompress a zstd file to directory

### ISSUE THREAD

**Issue by Yullin** [facebook/zstd#3756]
1. I compressed a directory by using the command `zstd -r ./dir/ -o dir.zstd`
2. When I was going to decompress the file with command `zstd -dr ./dir.zstd`, I got a file named dir, It's not a directory
So, How should I do? I want a directory just like before compressing, Please help me

**Comment by Yullin** [comment]
My bad, didn't notice the message 
```
*** zstd command line interface 64-bits v1.5.2, by Yann Collet ***
zstd: WARNING: all input files will be processed and concatenated into a single output file: dir.zstd
The concatenated output CANNOT regenerate the original directory tree.
```

**Comment by Cyan4973** [comment]
I was going to provide the same answer ...

The command should also have triggered a `yes/no` prompt after the warning message, to be sure that the user understands the operation. Unless the `-f` / `--force` was also employed.

**Comment by Yullin** [comment]
> I was going to provide the same answer ...
> 
> The command should also have triggered a `yes/no` prompt after the warning message, to be sure that the user understands the operation. Unless the `-f` / `--force` was also employed.

This is a very good idea!
