### ISSUE TITLE
In place decompression

### ISSUE THREAD

**Issue by OkobaPatino** [facebook/zstd#3759]
Is it safe to use the same pointer for src and dst of ZSTD_decompress? Assuming that the buffer has enough memory for decompressed content.

**Comment by Cyan4973** [comment]
Documentation for in-place decompression can be found here : 
https://github.com/facebook/zstd/blob/v1.5.5/lib/zstd.h#L1470

**Comment by OkobaPatino** [comment]
That is a bit complicated for me, so to be sure, if I have 
`outputSize = ZSTD_getFrameContentSize(compSize)`
`margin = ZSTD_decompressionMargin(compBuffer, compSize)`
then I should have a `outputBuffer` with size of `outputSize + margin`?
And I have to write the `compBuffer` at the end of `outputBuffer`?
So start of `compBuffer` actually is at `outputBuffer[outputSize]`?

**Comment by Cyan4973** [comment]
start of `compBuffer` is at `outputBuffer[outputSize + margin - compSize]`

**Comment by yosun** [comment]
can this IPDC handle 100MB+ files?

**Comment by Cyan4973** [comment]
Yes
