### ISSUE TITLE
Possible performance regressions on some CPUs after #3449 (C fast loops)

### ISSUE THREAD

**Issue by iksaif** [facebook/zstd#3762]
**Describe the bug**
It seems that https://github.com/facebook/zstd/pull/3449 introduced a performance regression on modern CPUs, this is particularly problematic on aarch64/arm64 since those don't have an ASM function and will always use the fast loop functions.

**To Reproduce**
```
wget https://github.com/facebook/zstd/releases/download/v1.1.3/github_users_sample_set.tar.zst
zstd -d github_users_sample_set.tar.zst
tar xf github_users_sample_set.tar
wget https://mattmahoney.net/dc/silesia.zip
unzip silesia.zip
tar -cf silesia.tar dickens mozilla mr nci ooffice osdb reymont samba sao webster x-ray xml

CFLAGS="-O2 -march=native" make -j8; ./zstd -b1 -r github ; ./zstd -b1e1 --compress-literals --zstd=tlen=131072 silesia.tar
```

On Darwin: (Apple clang version 14.0.3 (clang-1403.0.22.14.1))
On Linux: (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0)

**Expected behavior**
Performance should not degrade between v1.5.2 and v1.5.4

**Screenshots and charts**

* b1: `zstd -b1 -r github`
* b2: `zstd -b1e1 --compress-literals --zstd=tlen=131072 silesia.tar`

* 🟢 - best performances for this machine
* 🔴 - worst performances for this machine

Machine | Version | github | silesia |
-- | -- | -- | --
m1 | v1.5.2 | 🟢 529.5 MB/s | 🔴 722.5 MB/s
m1 | v1.5.4 | 🔴 412.3 MB/s | 🟢 723.4 MB/s
m1 | v1.5.4 + disableFast | 🟢 529.4 MB/s | 🟢 722.4 MB/s
m1 | dev | 🔴 410.6 MB/s | 🟢 722.7 MB/s
c7g Graviton 3 | 51b123d5f732955b2079dffe00b5f197dcc8c206 | 🟢 483.1 MB/s | 🟢 1128.2 MB/s
c7g | v1.5.2 | 🟢 436.1 MB/s | 🟢 1122.5 MB/s
c7g | v1.5.4 | 🔴 349.6 MB/s | 🔴 703.7 MB/s
c7g | v1.5.4 + disableFast | 🟢 436.7 MB/s | 🟢 1125.5 MB/s
c7g | dev | 🔴 349.3 MB/s | 🔴 720.4 MB/s
c6i Intel(R) Xeon(R) Platinum 8375C | 51b123d5f732955b2079dffe00b5f197dcc8c206 (pre Huffman ASM) | 🟢 492.4 MB/s | 🟠 1232.3 MB/s
c6i | v1.5.2 | 🔴 393.4 MB/s | 🟢 1589.8 MB/s
c6i | v1.5.4 | 🔴 398.7 MB/s | 🟢 1579.3 MB/s
c6i | v1.5.4 + disableAsm | 🔴 404.0 MB/s | 🔴 907.0 MB/s
c6i | v1.5.4 + disableAsm + disableFast | 🟢 494.3 MB/s | 🟠 1235.2 MB/s
c6i | dev | 🔴 397.4 MB/s | 🟢 1585.9 MB/s
c6a AMD EPYC 7R13 | 51b123d5f732955b2079dffe00b5f197dcc8c206 (pre Huffman ASM) | 🟢 519.3 MB/s | 🟠 1209.2 MB/s
c6a | v1.5.2 | 🔴 397.9 MB/s | 🟢 1467.3 MB/s
c6a | v1.5.4 | 🔴 397.6 MB/s | 🟢 1466.8 MB/s
c6a | v1.5.4 + disableAsm | 🔴 396.8 MB/s | 🔴 687.4 MB/s
c6a | v1.5.4 + disableAsm + disableFast | 🟢 476.0 MB/s | 🟠  1301.4 MB/s
c6a | v1.5.5 | 🔴 396.1 MB/s | 🟢 1469.0 MB/s
c6a | dev | 🔴 391.8 MB/s | 🟢 1466.3 MB/s

**Summary:**
* `v1.5.4 + disableAsm` always gives the worst performances for both tests - and this versions uses the Generic C fast loops
* `v1.5.4 + disableAsm + disableFast`: is slightly slower that the ASM function for the second benchmark but faster for the first one
* For aarch64 the first benchmark was always faster with `v1.5.2`
* For amd64 the first benchmark was faster before the ASM function
* https://github.com/facebook/zstd/pull/3449 results can be replicated only on Apple silicon with the second benchmark

**Desktop (please complete the following information):**
See above

**Comment by iksaif** [comment]
CC: @terrelln since you authored the original PR you are probably interested about this

I haven't looked at *why* things might be slower, but given the results it might be interesting to offer the option to not build the generic C versions of the fast decoding loops since it's unclear that they offer a significant performance boost on modern CPUs and compilers

Also maybe I did something wrong in those tests, I'm happy to re-run them if necessary

**Comment by iksaif** [comment]
This also relates to:
* https://github.com/facebook/zstd/issues/3278 - which shows that assembly versions are not as performant as we think (for benchmark 1)
* https://github.com/facebook/zstd/pull/3155 which looks at custom ASM functions for aarch64 (but it looks like trusting the compiler could be faster)

**Comment by terrelln** [comment]
Thanks for the report @iksaif!

I will spend some time investigating next week.

At first glance, the performance on `c7g Graviton 3` looks bad across the board. But, everything else has just regressed the GitHub case, which is a bunch of small files. Which maybe suggests that we need to either improve the Fast-C & ASM loops for small literals sections, or automatically use the old code versions for small literals sections.

**Comment by iksaif** [comment]
👋 any finding ? thanks!

**Comment by terrelln** [comment]
Hi @iksaif sorry for the delay, but I have several updates:

1. PR #3827 drastically speeds up the fast C & assembly Huffman decoders on very small data like in the `github` corpus.
2. PR #3826 may improve `c7g Graviton 3` performance. It manually unrolls the inner loops, because I've found that in certain scenarios the compiler wasn't unrolling the inner loops. If that was the case for `c7g`, then I would expect significant performance improvements.
3. PR #3826 also provides the ability to disable the fast C decoding loops at compile time by defining the C macro `HUF_DISABLE_FAST_DECODE`, in case you still see subpar performance after these PRs.

Please let me know if you see any more issues with performance after these PRs, and we will look into them. I can't guarantee a super fast turnaround time, but we always try to handle outstanding issues before we make releases.

**Comment by iksaif** [comment]
Thanks for the update, I'll try this out in the next few weeks!

**Comment by iksaif** [comment]
I can confirm that the latest version from git is back to `v1.5.2` level of performances  on c7g !


```
 1# 9114 files       :   7484607 ->   2603666 (x2.875),  183.3 MB/s,  435.3 MB/s
 1#silesia.tar       : 211957760 -> 132055991 (x1.605),  700.0 MB/s, 1143.6 MB/s
```

**Comment by terrelln** [comment]
Great, I'm glad to hear it! Looks like it was running into the loop unrolling problem.
