### ISSUE TITLE
aarch64/x86 causing different compression outputs with row match finder

### ISSUE THREAD

**Issue by cgbur** [facebook/zstd#3796]
My current setup is that I have an x86 machine and a Graviton arm machine on EC2. I have a 500 megabyte log file that I'm compressing in both instances. I'm using level 7 because I know that that uses the row-based match finder.

Some notes and questions:

- As expected, x86 defaults to row based
- surprisingly, aarch64 defaults to the hash chain match finder (I thought since graviton2 has Neon this would use the row finder)
- surprisingly, `--row-match-finder` on aarch64 produces the same output as `--no-row-match-finder` on x86.
- The sizes do not match up otherwise. I would expect these to be the same across different cpu types, and only the time would change.

I confirmed size being equal means the md5sum is equal.

| CPU | default  | --row-match-finder | --no-row-match-finder |
| --- | -------- | ------------------ | --------------------- |
| x86 | 35528444 | 35528444           | 36069905              |
| arm | 35424705 | 36069905           | 35424705              |

## x86

lscpu

```
Architecture:        x86_64
Byte Order:          Little Endian
Vendor ID:           AuthenticAMD
CPU family:          25
Model:               1
Model name:          AMD EPYC 7R13 Processor
```

```
md5sum log
f7f880c8d58cdd4ef4f8ab74079ce865 log
time zstd -7 -c log | wc -c
35528444


Executed in 2.88 secs fish external
usr time 2.97 secs 0.00 millis 2.97 secs
sys time 0.21 secs 1.02 millis 0.21 secs

md5: afa0b8c2cf8f8f672df232121b4c09fc
```

```
time zstd -7 -c log --row-match-finder | wc -c
35528444

Executed in 2.99 secs fish external
usr time 3.13 secs 0.00 micros 3.13 secs
sys time 0.13 secs 991.00 micros 0.13 secs

md5: afa0b8c2cf8f8f672df232121b4c09fc
```

```
time zstd -7 -c log --no-row-match-finder | wc -c
36069905

Executed in 3.25 secs fish external
usr time 3.37 secs 0.00 millis 3.37 secs
sys time 0.19 secs 1.72 millis 0.19 secs

md5: bc8b5dd23a75cb9a9b4245a51accbbd4
```

## Arm

This is a c6g instance on EC2, which is a Graviton2 processor.

lscpu

```
Architecture:           aarch64
  CPU op-mode(s):       32-bit, 64-bit
  Byte Order:           Little Endian
CPU(s):                 4
  On-line CPU(s) list:  0-3
Vendor ID:              ARM
  Model name:           Neoverse-N1
    Model:              1
    Thread(s) per core: 1
    Core(s) per socket: 4
    Socket(s):          1
    Stepping:           r3p1
    BogoMIPS:           243.75
    Flags:              fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
```

```
md5sum log
f7f880c8d58cdd4ef4f8ab74079ce865  log
```

```
time zstd -7 -c log | wc -c
35424705

real    0m5.056s
user    0m5.078s
sys     0m0.077s

md5: 7a1de356226811093cfcf28299559bf2
```

```
time zstd -7 -c log --row-match-finder | wc -c
36069905

real 0m6.396s
user 0m6.430s
sys 0m0.067s

md5: bc8b5dd23a75cb9a9b4245a51accbbd4
```

```
time zstd -7 -c log --no-row-match-finder | wc -c
35424705

real 0m5.060s
user 0m5.072s
sys 0m0.086s

md5: 7a1de356226811093cfcf28299559bf2
```

**Comment by danlark1** [comment]
Hi, I've changed a bit of NEON code in row match finder in 1.5.1 and above, can you share `zstd --version`? I was unable to reproduce with any handy file

**Comment by cgbur** [comment]
The zstd version tested on graviton was v1.5.2. I just grabbed the lastest dev release and compiled it and the results now match x86 and the performance is much better. Totally forgot to check the version, my bad! Here is the updated table. Closing this now, thank you for the ARM work!

| CPU              | default  | --row-match-finder | --no-row-match-finder |
| ---------------- | -------- | ------------------ | --------------------- |
| x86 v1.5.5       | 35528444 | 35528444           | 36069905              |
| arm v1.5.2       | 35424705 | 36069905           | 35424705              |
| arm v1.5.5 (dev) | 35528444 | 35528444           | 36069905              |
