### ISSUE TITLE
ZStd 64 bit library compiles with VS 2022 crashes on old CPUs

### ISSUE THREAD

**Issue by anatolpiotrowski** [facebook/zstd#3797]
We are trying to compile x64 ZStd compression library with VS2022 C++ 
But we have a set of old computers where the ZStd library crashes because it contains AVX instructions.
On these old computers AVX instructions do not exist. ( Intel Xeon E5620 )
Looks like VS 2022 does not allow removing AVX instructions for x64 code.
Seems like I can disable them only for 32 bit code. 
(I tried "Not Set" and "No Enchanced Instructions" in VS 2022 without success)

I was able to compile with VS2017 without AVX instructions by setting instructions to SSE2.

Anyone else had this problem?

![image](https://github.com/facebook/zstd/assets/41700809/fea803a9-3339-4f96-ba63-513561ab61d9)

![image](https://github.com/facebook/zstd/assets/41700809/bf651091-cf47-4d9e-8525-b432de8c77ec)

**Comment by Cyan4973** [comment]
The expectation is that this should be controllable either by command line (`/arch:SSE2`) or via the "code generation" property page (https://learn.microsoft.com/en-us/cpp/build/reference/arch-x86?view=msvc-170).

But this sounds more like a Visual Studio issue, and therefore these questions would probably receive a more appropriate peer attention on a Visual Studio support forum (we do all developments on `gcc` + `clang`, and almost never employ Visual Studio).
