### ISSUE TITLE
A question about the streaming compression interface

### ISSUE THREAD

**Issue by wqshr12345** [facebook/zstd#3805]
Hello, I have a question about the streaming compression interface of zstd, and I'd like to ask for some guidance.

I have a data stream that continuously produces data of unknown length. Now, I have two ways to compress it:
1. Use the streaming compression interface provided by zstd, with a block size set to 5MB, to compress the incoming data from the data stream.
2. Set up a 5MB-sized buffer.Whenever I receive 5MB of data from the data stream, I use the regular compression interface to compress it.

Are the compression results the same for these two methods?

**Comment by Cyan4973** [comment]
Both methods will work,
but they do not produce the same artifact.

The first method (streaming) will produce a single continuous frame, of unspecified content length (discovered at the end).

The second method will produce many compressed frames of decompressed size 5 MB each, and simply concatenate them back to back.

Both artifacts will be decompressible, and will regenerate the same source.
But the first method (streaming) is likely going to compress better, more or less substantially depending on compression parameters (difference is probably going to be larger at level 19 than at level 1). On the other hand, streaming requires maintaining a state throughout the complete process.

Streaming tends to be preferred when there is a continuous flow of input to compress,
while concatenation of independent frames tends to be preferred when there is an irregular production of input, with some delay between consecutive batches.
