### ISSUE TITLE
Take fixes of zstd tool before it  included in latest

### ISSUE THREAD

**Issue by shulib** [facebook/zstd#3809]
Hi, 
If I want to take a fix or updated of tool before it released to latest,
how should I take the updates?
Thanks,

**Comment by Cyan4973** [comment]
Just use the `dev` branch ?

**Comment by shulib** [comment]
yes,

**Comment by shulib** [comment]
when will you release next version of tool that include fix "fixed decoder behavior when nbSeqs==0 is encoded using 2 bytes
"?

**Comment by Cyan4973** [comment]
There is no date set for the next release yet.
If you urgently need now a version of "tool" which contains a specific fix already applied to the `dev` branch, your best course of action is to compile it from the `dev` branch.
