### ISSUE TITLE
question: does `zstd_decompress` function has tolerance of data race

### ISSUE THREAD

**Issue by Absoler** [facebook/zstd#3815]
I found that in function `HUF_readStats_body` defined in `lib/zstd/common/entropy_common.c`, if src's data is modified by other threads, some unexpected error will happen. I wonder whether this situation is permitted in our project

**Comment by Cyan4973** [comment]
No, it's not.
And I don't see in which situation this could be a valid scenario.
When reading data from a buffer segment, the buffer segment should remain immutable, whatever the actual processing is.
