### ISSUE TITLE
[question] Seek for insights on the suitable case for zstd dictionary compression

### ISSUE THREAD

**Issue by Nor7th** [facebook/zstd#3832]
The zstd dictionary compression is known to be effective for small files with size around 100KB：

```
 * When is a dictionary useful?
 * ----------------------------
 *
 * Dictionaries are useful when compressing many small files that are similar.
 * The larger a file is, the less benefit a dictionary will have. Generally,
 * we don't expect dictionary compression to be effective past 100KB. And the
 * smaller a file is, the more we would expect the dictionary to help.
```

I have a question that, could the advantage of dictionary compression still exists if those "small files" come from the cut pieces of a very large file?

In other words, is it possible to get a better **total compression speed/ratio** by cutting a larger file into small pieces (~100kb) and compress each piece via dictionary compression, than just compressing the original large file? (**_No need to consider to rebuild the original file, just focusing on total compression effectiveness_**)

Is the answer just an absolute "**Impossible!**", or it actually depends on different file/data types (plain text file, binary file, database file, picture file, etc)? Anyone has some insights on this?

**Comment by Cyan4973** [comment]
This is highly unlikely.

There _might_ be ways to manufacture a case to explicitly advantage the dictionary compression method, but even in this case, such a difference would end up being unimpressive. 

Sort of such cheating technique, I would expect the more natural "stream the whole file" method to win every time, and sometimes by very significant margins.

**Comment by Nor7th** [comment]
@Cyan4973  Thanks for the very clear conclusion.

Given many files to compress, it's usually understandable that to compress the concatenating file of all can get a better compression effectiveness than compress each file one by one. 

> https://stackoverflow.com/questions/48145313/how-is-concatenating-files-before-compressing-more-effective-than-just-compressi

Then what's exactly kind of case where zstd dictionary compression can actually stand out? Can I say, it's the case of many small files but don't allow to be concatenated?

**Comment by Cyan4973** [comment]
> Then what's exactly kind of case where zstd dictionary compression can actually stand out? Can I say, it's the case of many small files but don't allow to be concatenated?

Yes. It's a case where random access is required, or there is no time or memory to allow concatenation.

These cases are more common in data centers than on personal computers.

**Comment by Nor7th** [comment]
@Cyan4973  BTW, from your view, how difficult it is to expand the dictionary mechanism into other compression algorithms like snappy, lz4, gzip, zlib?

**Comment by Cyan4973** [comment]
`lz4` already supports it.

`zlib` should also support it, the interface may be less obvious though.

No idea about `snappy`.
