### ISSUE TITLE
Adding a library to https://facebook.github.io/zstd/#other-languages

### ISSUE THREAD

**Issue by johnwedgbury** [facebook/zstd#3844]
We've created a [PHP library](https://github.com/appoly/zstd-php) that doesn't depend on modifying the PHP installation to function. This is a wrapper for the system zstd binary, supporting simple compression/decompression on the local filesystem, and streams (very similar to the [Node.js version](https://www.npmjs.com/package/simple-zstd) listed).

Could this be added to https://facebook.github.io/zstd/#other-languages please?

**Comment by Cyan4973** [comment]
Sure !
