### ISSUE TITLE
[Question] How to force single literal streams during compression

### ISSUE THREAD

**Issue by roynalnaruto** [facebook/zstd#3857]
I have a question related to configuring the encoder. I couldn't locate in the specifications how to configure this part, so decided to ask here.

During compression, is there an encoder config/parameter that ensures:
- A single literal stream `LSTREAM1` is used in the zstd compressed blocks
- consequently, the jump table is skipped

Thank you :)

**Comment by Cyan4973** [comment]
1) There is no such parameter (at least not yet).
    Currently, the encoder selects automatically which one (1-stream, 4-streams) to employ,
    mostly based on the size of literals buffers.
2) The single literal stream is limited to 1 KB max. This is a hard format limitation. 
    As a consequence, single stream cannot be unconditionally selected.
