### ISSUE TITLE
How to compute memory usage?

### ISSUE THREAD

**Issue by Bulat-Ziganshin** [facebook/zstd#388]
I see 4 scenarios of compression & decompression:
1. ZSTD_compressCCtx / ZSTD_decompressDCtx
2. ZSTD_compressStream / ZSTD_decompressStream
3. ZSTD_compressContinue / ZSTD_decompressContinue
4. ZSTD_compressBlock / ZSTD_decompressBlock

and 3 pair of functions measuring memory usage:
1. ZSTD_estimateCCtxSize / ZSTD_estimateDCtxSize
2. ZSTD_sizeof_CCtx / ZSTD_sizeof_DCtx
3. ZSTD_sizeof_CStream / ZSTD_sizeof_DStream

It will be great to document how to compute memory usage in all 4 scenarios for both cases - prior to (de)compression (using only compression params) and during the (de)compression.

**Comment by Cyan4973** [comment]
`CCtx` are used for cases 1, 3 and 4.
So `ZSTD_sizeof_CCtx` / `ZSTD_sizeof_DCtx` is good for all 3 of them.

Case 2 is the only one in need of `ZSTD_sizeof_CStream` / `ZSTD_sizeof_DStream`.

`ZSTD_estimateCCtxSize` / `ZSTD_estimateDCtxSize` is applicable to cases 1, 3 and 4.
It tries to estimate the size of a future `CCtx` not yet allocated , depending on a set of parameters.
It's just an estimation, it may get it wrong in some corner cases.
So I recommend `ZSTD_sizeof_*` for precise/guaranteed measurements.

You could have added `ZSTD_sizeof_CDict` / `ZSTD_sizeof_DDict` which are also relevant when these objects are in use (dictionary compression).

**Comment by Cyan4973** [comment]
Does that answer your question ?

**Comment by Bulat-Ziganshin** [comment]
I think that I personally got it. But it will be great to add this info to the docs. Reformulating your answer:
1. If you already run (de)compression using ?Ctx, use ZSTD_sizeof_?Ctx to measure actual memory usage
1a. If you plan to run (de)compression using ?Ctx, use ZSTD_sizeof_?Ctx to estimate future memory usage
2. If you already run (de)compression using ?Stream, use ZSTD_sizeof_?Stream  to measure actual memory usage
2a. If you plan to run (de)compression using ?Stream, use ZSTD_sizeof_?Ctx to estimate future memory usage and then add 1<<windowLog
3. In any case above, add sizes of all buffers you have allocated yourself, even if zstd suggested you their sizes (such as ZSTD_CStreamInSize) - they aren't accounted by functions above due to obvious reason that you can actually allocate any other amount of space.

I also propose to add ZSTD_estimate?StreamSize function to deal with the case 2a.

**Comment by Cyan4973** [comment]
In current `dev` branch, memory functions have been revamped,
and now encompass all objects handled by this library.
Each object has a `ZSTD_sizeof_*()` and a `ZSTD_estimate*Size()` function.

All definitions are regrouped into a single paragraph :
https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L463

to help for clarity
