### ISSUE TITLE
How to throttle disk IO?

### ISSUE THREAD

**Issue by beef9999** [facebook/zstd#389]
I'm trying to compress some very large binary files, and find my server's IO util percentage always rise to 100.

Is there any method to slow down the compression? The compression itself can accept slowness, but the other services cannot be affected.

**Comment by gyscos** [comment]
You can try [ionice](https://linux.die.net/man/1/ionice) to change the compression process priority.

**Comment by beef9999** [comment]
That was Brilliant!
