### ISSUE TITLE
How can I change the window size?

### ISSUE THREAD

**Issue by RoronoaDZor** [facebook/zstd#3898]
Hello, 

I want to compress some files with the zstd for different window sizes.
If I have understood correctely, I can change the window sizes through the --windowLog in command line.
But after installing the zstd I typed $zstd -H to see what options I have, but I do not have such choice.
How can I change the window size then?

Thank you in advance.

**Comment by Cyan4973** [comment]
After installing `zstd`, type [`man zstd`](https://man.freebsd.org/cgi/man.cgi?query=zstd&sektion=1&format=html#end)
