### ISSUE TITLE
zstd library for ios example

### ISSUE THREAD

**Issue by qylibohao** [facebook/zstd#391]
does zstd libaray has an example for ios ?

**Comment by Cyan4973** [comment]
libzstd is known to work on iOS, with several implementations already running.
The code is compatible without modification with C, C++ and objective-C compilers.

Beyond that, if your question is about setting up a build system for iOS,
I'm afraid this is out of this repository scope.

If you have a project already working for iOS, you should be able to add zstd source into it with minimal pain. If not, this repository is not the better place to learn how to build one.

Example of external iOS tutorial : http://codewithchris.com/first-xcode-project/

**Comment by Cyan4973** [comment]
I see you made your own example : https://github.com/qylibohao/ZSTDCompressLib 
👍
