### ISSUE TITLE
Reducing DCtx Size for Embedded Systems (like esp32)

### ISSUE THREAD

**Issue by olokelo** [facebook/zstd#3919]
Hi,

Firstly I must say I really appreciate your work on lz4 and zstd.

I've recently had an idea that would require running zstd decompression on an esp32 board with very limited RAM.
My main motivation was that zstd can use dictionaries which gave me very nice compression ratios (much higher than brotli or lzma on short messages). 

I tested both compression and decompression on my esp32. Context size for compression is not a big problem - got it down to 36kB with custom parameters.

However decompressor Context seems to always require around 96kB regardless of compression preset even without setting up dictionary. Decompression is certainly possible but the esp32 board has only 300kB available RAM so it would probably take around half of available memory.

```c
ZSTD_CCtx* const cctx = ZSTD_createCCtx();
  
ZSTD_CCtx_params* params = ZSTD_createCCtxParams();

ZSTD_CCtxParams_setParameter(params, ZSTD_c_windowLog, 10);
ZSTD_CCtxParams_setParameter(params, ZSTD_c_hashLog, 10);
ZSTD_CCtxParams_setParameter(params, ZSTD_c_chainLog, 10);
ZSTD_CCtxParams_setParameter(params, ZSTD_c_searchLog, 10);
ZSTD_CCtxParams_setParameter(params, ZSTD_c_minMatch, 3);
ZSTD_CCtxParams_setParameter(params, ZSTD_c_targetLength, 0);
ZSTD_CCtxParams_setParameter(params, ZSTD_c_strategy, ZSTD_fast);

printf("Compressor CCtx size: %zu\n", ZSTD_estimateCCtxSize_usingCCtxParams(params));
printf("Decompressor DCtx size: %zu\n", ZSTD_estimateDCtxSize());
```

gives:

```
Compressor CCtx size: 35055
Decompressor DCtx size: 95808
```

I understand that zstd is not intended for that use-case however maybe someone knows if it's possible to reduce DCtx size somehow. I also tried `ZSTD_DCtx_setParameter(dctx, ZSTD_d_windowLogMax, 10)` but it doesn't seem to affect the memory usage.

If it's not possible then I would probably use lz4 since it also has dictionary support but somewhat worse compression ratio since AFAIK it doesn't use ANS entropy coder.

**Comment by Cyan4973** [comment]
The bulk of the decompression state memory budget is taken by the literals buffer.
For such special case, it's possible to reduce it considerably by modifying the build variable `ZSTD_DECODER_INTERNAL_BUFFER` at compilation time.
This is documented in https://github.com/facebook/zstd/tree/dev/lib#modular-build.
Be aware that reducing the size of the literals buffer tends to impact decompression speed negatively, but the cost is reasonable, and that's probably the better choice for your memory-constrained scenario.

**Comment by olokelo** [comment]
Thanks for quick response. Setting `ZSTD_DECODER_INTERNAL_BUFFER` to 4096 reduced DCtx size to 34368 bytes which is perfectly acceptable. I've looked at modular build yet somehow I missed this setting, thanks again.
