### ISSUE TITLE
No `uncompressed` and `ratio` information in `zstd --list` output if the zstd file is created via pipe

### ISSUE THREAD

**Issue by moontide** [facebook/zstd#3921]
**Describe the bug**
If zstd file is created via pipe, then there's no `uncompressed` and `ratio` information in `zstd --list` output.

**To Reproduce**
1. `hexdump -C $(which zstd) | zstd -3 > /tmp/zstd.hexdump.txt.zstd`
2. `zstd -l /tmp/zstd.hexdump.txt.zstd`
3. See the output, there's no `uncompressed` and `ratio` information
    ````
    # zstd -l zstd.hexdump.txt.zstd 
    Frames  Skips  Compressed  Uncompressed  Ratio  Check  Filename
         1      0    1.12 MiB                       XXH64  zstd.hexdump.txt.zstd
    ````
**Expected behavior**
Update uncompressed and ratio information somehow when pipe reached EOF, or calculate them when issuing `zstd --list`, so that we can get `uncompressed` and `ratio` information.

**Screenshots and charts**

**Desktop (please complete the following information):**
 - OS: Fedora 39 x86_64
 - Version 1.5.5

**Additional context**
* `xz -l` can report `uncompressed` and `ratio` information if xz file is created via pipe.
* I use pipe because I don't want to create intermedium files (file size could be huge) on the server.

**Comment by Cyan4973** [comment]
This behavior is expected.

By the time the stream reaches its end, the header has already been written and sent. 

You can manually specify this information with command `--stream-size=#`,
in which case it will be forcefully written into the header,
but also controlled at the end: 
the compression function will issue an error if the pledged amount of data has not been met exactly.

**Comment by moontide** [comment]
> You can manually specify this information with command `--stream-size=#`

Unfortunately, the steam size is unpredictable (`mysqldump HUGE_DATABASE | zstd > data.sql.zstd`).

`xz -l` can report `uncompressed` and `ratio` information if xz file is created via pipe.
````
# hexdump -C $(which zstd) | xz -3 > zstd.hexdump.txt.xz

# xz -l zstd.hexdump.txt.xz 
Strms  Blocks   Compressed Uncompressed  Ratio  Check   Filename
    1       1    968.3 KiB  4,272.3 KiB  0.227  CRC64   zstd.hexdump.txt.xz
````
I don't know how `xz -l` can do that, hope zstd can do that too.

**Comment by Cyan4973** [comment]
They are likely adding metadata at the end.
