### ISSUE TITLE
lz4 "legacy" format support

### ISSUE THREAD

**Issue by slowpeek** [facebook/zstd#3922]
My zstd build (ubuntu 22.04.4) does support lz4 format:

    > zstd --help | grep lz4
    --format=lz4 : compress files to the .lz4 format

But it cant uncompress the "legacy" lz4 format, only the "new" one:

    > echo abc | lz4 -c | zstd -dc
    abc
    > echo abc | lz4 -l -c | zstd -dc
    zstd: /*stdin*\: unsupported format

I've discovered this problem while unpacking the compressed cpio in the initrd of `ubuntu-20.04.6-desktop-amd64.iso` (it starts at offset `6938624`).

So, is it so by design, or is it a bug? In the sources I see it only checks for one magic number, namely

    #define LZ4_MAGICNUMBER 0x184D2204

It is the one for the "new" format:

    > echo abc | lz4 -c | od -An -tx4 -N4 --endian=little
     184d2204

For the "legacy" format it is `0x184C2102`:

    > echo abc | lz4 -l -c | od -An -tx4 -N4 --endian=little
     184c2102

I tried recompiling with the magic number for the "legacy" format, but it didn't work:

    > echo abc | lz4 -l -c | zstd -dc
    zstd: /*stdin*\: lz4 decompression error : ERROR_frameType_unknown

**Comment by Cyan4973** [comment]
Unfortunately, it's not within the scope of `zstd` to support the older (pre v1.0) legacy `lz4` format.
