### ISSUE TITLE
Add common file types that are compressed to ' --exclude-compressed'

### ISSUE THREAD

**Issue by dcog989** [facebook/zstd#3923]
https://github.com/facebook/zstd/issues/1579 produced the switch '--exclude-compressed' but that only excludes some archive file types (https://github.com/facebook/zstd/blob/a58b48ef0e543980888a4d9d16c9072ff22135ca/programs/fileio.c#L1897).

Request that common file types that are already compressed are added to the above list. 

A starter list (note: also includes archive formats so some duplication with current code): https://github.com/dcog989/Common-file-types-that-are-compressed/blob/main/compressed-already.yaml

**Comment by Cyan4973** [comment]
feature completed by @daniellerozenblit at #3951

**Comment by dcog989** [comment]
Excellent! That should bring a nice bump in compression times for mixed data sets. Thanks @daniellerozenblit and @Cyan4973.

Yann - any ETA for next release?

**Comment by Cyan4973** [comment]
"soon"
