### ISSUE TITLE
compressing files containing multiple similar portions

### ISSUE THREAD

**Issue by yxsamliu** [facebook/zstd#3932]
Clang uses a tool clang-offload-bundler to compress a fat binary file containing multiple similar portions (so called code objects). clang-offload-bundler in turn uses ZSTD_compress of libzstd to do the compression (https://github.com/llvm/llvm-project/blob/main/llvm/lib/Support/Compression.cpp#L171 ). 

A compression level is specified when calling ZSTD_compress. Recently, it was found that the compression level 6 which is used by LLVM by default is not good at compressing large files where each similar portion is 11MB, but compression level 20 can get a much higher compression rate (the compressed file is smaller than half of one portion). Therefore a PR was opened to change the compression level used by clang-offload-bundler (https://github.com/llvm/llvm-project/pull/83605)

However, there are concerns that the optimal compression level may depend on the size of the similar portions. As shown in https://github.com/facebook/zstd/blob/a58b48ef0e543980888a4d9d16c9072ff22135ca/lib/compress/clevels.h#L48, different compression level is associated with different window size and chain size, which may be more relevant to achieve a good compression rate. Therefore there is suggestion to use these parameters directly.

So we seek your advice on a solution that works for different sizes of similar portions. We do not need the highest compression rate. As long as the compressed size is below the size of one portion that is fine. The size of most of the similar portions are below 32MB.

Thanks.

**Comment by felixhandte** [comment]
Hi @yxsamliu,

As you noted, the limiting factor here is likely the window size, which controls the maximum distance over which objects can be deduplicated. For level 6 it's 2 MB. For level 20 it's 32 MB. You can control this independently of the compression level, by setting the [`ZSTD_c_windowLog`](https://github.com/facebook/zstd/blob/v1.5.5/lib/zstd.h#L347-L354) compression parameter, although lower compression levels have increasingly limited abilities to take advantage of very long windows.

Zstd also has a search engine specifically targeting large matches at long distances: the [long-distance matcher](https://github.com/facebook/zstd/blob/v1.5.5/lib/zstd.h#L394-L401).

For your use case, I'd expect a moderate compression level with the long-distance matcher enabled on a large window size to perform well at significantly better speed than setting a very high compression level.

**Comment by Cyan4973** [comment]
If we assume that some relatively large portions (dozens of bytes at least) are very similar at byte level, but separated by significant distances, then indeed the long distance matcher would be my recommendation too. It's great at finding long matches at large distances, and the overall speed cost is reasonable. You wouldn't have to change the compression level.

Using the long distance matcher will also impact the window size automatically.
Be aware though that this mode automatically sets the window size to 128 MB by default, which might be too high. You can change that by being explicit about the window size you want.

**Comment by yxsamliu** [comment]
Thanks for your advice. I tried the following code to specify both compression level and enable LDM:

```
void zstd::compress(ArrayRef<uint8_t> Input,
                    SmallVectorImpl<uint8_t> &CompressedBuffer, int Level, bool EnableLdm) {
  ZSTD_CCtx* Cctx = ZSTD_createCCtx();
  if (!Cctx) report_bad_alloc_error("Failed to create ZSTD_CCtx");

  size_t const LevelStatus = ZSTD_CCtx_setParameter(Cctx, ZSTD_c_compressionLevel, Level);
  if (ZSTD_isError(LevelStatus)) {
    ZSTD_freeCCtx(Cctx);
    report_bad_alloc_error("Failed to set ZSTD_c_compressionLevel");
  }

  size_t const LdmStatus = ZSTD_CCtx_setParameter(Cctx, ZSTD_c_enableLongDistanceMatching, EnableLdm ? 1 : 0);
  printf("LDM=%d\n", (int)EnableLdm);
  if (ZSTD_isError(LdmStatus)) {
    ZSTD_freeCCtx(Cctx);
    report_bad_alloc_error("Failed to set ZSTD_c_enableLongDistanceMatching");
  }

  unsigned long CompressedBufferSize = ZSTD_compressBound(Input.size());
  CompressedBuffer.resize_for_overwrite(CompressedBufferSize);

  size_t const CompressedSize = ZSTD_compressCCtx(
      Cctx,
      CompressedBuffer.data(), CompressedBufferSize,
      Input.data(), Input.size(),
      Level
  );

  ZSTD_freeCCtx(Cctx);

  if (ZSTD_isError(CompressedSize))
    report_bad_alloc_error("Compression failed");

  __msan_unpoison(CompressedBuffer.data(), CompressedSize);
  if (CompressedSize < CompressedBuffer.size())
    CompressedBuffer.truncate(CompressedSize);
}

```
The compression level seems to take effect but LDM seems not. Strangely, using the zstd program with the same compression level and `--long`, I can see `--long` takes effect. Does my code missing some other parameters which makes LDM not taking effect? Thanks.

**Comment by Cyan4973** [comment]
`ZSTD_compressCCtx()` is [ignoring advanced parameters](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L265) : 
```
 *  Important : in order to behave similarly to `ZSTD_compress()`,
 *  this function compresses at requested compression level,
 *  __ignoring any other parameter__ .
```

Use [`ZSTD_compress2()` instead](https://github.com/facebook/zstd/blob/v1.5.5/lib/zstd.h#L304) : 
```
 *   "sticky" parameters are applicable to `ZSTD_compress2()` and `ZSTD_compressStream*()` !
 *   __They do not apply to "simple" one-shot variants such as ZSTD_compressCCtx()__ .
```

**Comment by yxsamliu** [comment]
> `ZSTD_compressCCtx()` is [ignoring advanced parameters](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L265) :
> 
> ```
>  *  Important : in order to behave similarly to `ZSTD_compress()`,
>  *  this function compresses at requested compression level,
>  *  __ignoring any other parameter__ .
> ```
> 
> Use [`ZSTD_compress2()` instead](https://github.com/facebook/zstd/blob/v1.5.5/lib/zstd.h#L304) :
> 
> ```
>  *   "sticky" parameters are applicable to `ZSTD_compress2()` and `ZSTD_compressStream*()` !
>  *   __They do not apply to "simple" one-shot variants such as ZSTD_compressCCtx()__ .
> ```

Thanks. It works.
