### ISSUE TITLE
Using ZSTD_compressBound for Streaming Input

### ISSUE THREAD

**Issue by Arjav-Patel** [facebook/zstd#3935]
Is it guaranteed that streaming compression will yield output that is smaller than `ZSTD_compressBound(size)` where `size` is the total size of the streaming input (assuming it is known apriori)?

I need to compress input in chunks, but I know what the size of my input will be beforehand. I would like to reduce the number of times I allocate a buffer, as well as the number of times I have to flush my `ZSTD_outBuffer` to a larger buffer which holds the total streaming output.

**Comment by Cyan4973** [comment]
It's guaranteed if you merely `compressStream`, but not if you also employ `flush`.

`flush` can be abused in creating a lot of tiny blocks which, in extreme cases, might cumulatively reach beyond `ZSTD_compressBound()`.
This is really for extreme cases, a few parsimonious flushes here and there shouldn't change the picture here and there,
but the simple fact that it's possible to abuse `flush()` to create the above scenario makes it not possible to guarantee `ZSTD_compressBound()` when `flush()` is employed.

**Comment by Arjav-Patel** [comment]
@Cyan4973 

If I use if in the following manner:

1. `compressStream2` with continue
2. `compressStream2` with continue
...
N. `compressStream2` with continue
N + 1. `compressStream2` with end
N + 2. `compressStream2` with flush

That is, call flush at most 1 time after N calls to `compressStream2`, does the guarantee still hold?

**Comment by Cyan4973** [comment]
Yes, the guarantee would hold.

Such final flushes do not create intermediate small blocks. They just ensure that all buffers are completely emptied hence the operation is truly complete.

**Comment by Arjav-Patel** [comment]
Nice, thanks!
