### ISSUE TITLE
head file not found

### ISSUE THREAD

**Issue by 567MEI13** [facebook/zstd#3938]
why the fileio_asyncio.c report the error file not found
![Snipaste_2024-03-11_14-20-17](https://github.com/facebook/zstd/assets/88084071/be1fb966-0602-4849-823b-1c8498b42c8b)

and zstd_deps.h does not report the error
![Snipaste_2024-03-11_14-24-19](https://github.com/facebook/zstd/assets/88084071/ca24a663-6690-4b41-934a-07e18a175825)

**Comment by Cyan4973** [comment]
This looks like an IDE configuration issue.
In which case, it is outside of the scope of this repository.
