### ISSUE TITLE
manpage outdated

### ISSUE THREAD

**Issue by anotherwon** [facebook/zstd#396]
The manpage for `zstd` is outdated.
For example it says compression levels work from 1-22 whereas the `zstd --help` command mentions only 1-19 with the optional `--ultra` option.
So far I found:
- `-#`: false levels
- `--ultra`: missing
- `--no-dictID`: missing
- `--no-check`: missing
- `--[no-]sparse`: missing
- `-e#`: missing

**Comment by Cyan4973** [comment]
Fair enough, can be fixed with a PR.

**Comment by anotherwon** [comment]
Unfortunately someone else has to do this, as I'm not comfortable signing Facebook's CLA atm.

**Comment by Cyan4973** [comment]
Fixed in latest `dev` branch updated

**Comment by Cyan4973** [comment]
man page updated in v1.1.1
