### ISSUE TITLE
Support history buffers in zstd hardware acceleration

### ISSUE THREAD

**Issue by skyskyhu** [facebook/zstd#3970]
Rectently I integrated zstd with intel QAT hardware acceleration. The hardware acceleration speed is siginificantly faster than that of software compression. However, my primary objective is to reducue total storage size and cost using zstd compression. For all testing files, I observed that the compression ratio of hardware acceleration is lower than software compression as shown below. I suspect this is caused by the limitation of zstd hardware acceleration doucmented at the [link](https://github.com/facebook/zstd/blob/7806d803383b75b00868a5367154a18caf535a92/lib/zstd.h#L2768). History buffers are not currently supported, resulting in a lower hardware compression ratio compared to software compression. I am wondering if there is any plan to support history buffers in zstd hardware acceleration in the near future. Thanks!

## hardware compression with level 12
./benchmark -m1 -l10 -c64K -t5 -E2 -L12 1.txt
Thread 1: Compression: 446020002 -> **130257784**, Throughput: Comp:   508 MB/s, Decomp:  1273 MB/s, Compression Ratio: 29.20%, PASS

## software compression with level 12
./benchmark -m0 -l10 -c64K -t5 -E2 -L12 1.txt
Thread 1: Compression: 446020002 -> **120037796**, Throughput: Comp:    39 MB/s, Decomp:  1350 MB/s, Compression Ratio: 26.91%, PASS

## software compression with level 9
./benchmark -m0 -l10 -c64K -t5 -E2 -L9 1.txt
Thread 1: Compression: 446020002 -> **120318010**, Throughput: Comp:    99 MB/s, Decomp:  1341 MB/s, Compression Ratio: 26.98%, PASS

**Comment by embg** [comment]
Hey @skyskyhu! It's really exciting to hear that the community is starting to play around with QAT-acceleration for zstd.

One important thing to understand is that current-gen QAT uses a 32KB history buffer at the hardware level. No matter how much history we pass in from software, we can't change that fundamental limitation.

zstd currently passes data to QAT in 128KB blocks (without previous history). Therefore, 75% of bytes in each block are already hitting the 32KB hardware history limit. Only the first 25% would benefit from using the previous block as history.

The key point is: even if we passed in 32KB history from the previous block, we would still be a far cry from the multi-megabyte history used in software compression. This is a fundamental problem when using QAT for large files. Thus, we have focused more on using QAT in small-data applications, where the 32KB history limitation is not an issue.

We do have some ideas around a hybrid sequence producer which would search for long-distance matches in software and short-distance matches in hardware. This would require significant engineering effort, so unfortunately it hasn't been prioritized yet.

**Comment by embg** [comment]
One additional note: if future hardware accelerators support a larger history size relative to the 128KB zstd block size, it would be more interesting to look at passing in history from the previous block. We should keep an eye on this going forward as new hardware is introduced.

**Comment by skyskyhu** [comment]
OK, I got it. Many thanks, @embg, for your detailed information. Your insights are helpful. I'm looking forward to a more advanced QAT zstd plugin.
