### ISSUE TITLE
Why doesn't ZSTD_createCStream() work with ZSTD_getErrorName()?

### ISSUE THREAD

**Issue by keithbostic** [facebook/zstd#398]
Is there a reason ZSTD_createCStream() doesn't have the same error handling the other ZSTD functions?

Not being able to call ZSTD_getErrorName() complicates any code that's wrapping ZSTD errors.

Maybe:
```
size_t zstd_ret = ZSTD_createCStream(ZSTD_CStream **);
```
would simplify things.

**Comment by Cyan4973** [comment]
All ZSTD_create*() functions follow the same logic as malloc(),
 that is it provides a pointer to requested type, or NULL in case of failure .

**Comment by keithbostic** [comment]
IMHO, I'd rather have simpler/consistent error handling instead, not to mention giving Zstd more flexibility to return specific errors from the functions in the future.

**Comment by Cyan4973** [comment]
Unfortunately, it's a bit late for that discussion now.
This design is in place for all `ZSTD_create*()` functions, most of which are now in "stable" section, meaning it shall not be changed for the sake of API and ABI stability.

I'm also not sure it's a big issue. The only error that can happen is a `ZSTD_error_memory_allocation` one. This is, btw, the error number returned by functions using (and checking) `ZSTD_create*()`.
