### ISSUE TITLE
Cost of ZSTD_createCStream/ZSTD_freeCStream

### ISSUE THREAD

**Issue by keithbostic** [facebook/zstd#399]
It would be useful to know/document the cost of the ZSTD_createCStream/ZSTD_freeCStream functions.

Is it Zstd's expectation that programs will do the work to allocate them once and reuse them, or will they always be cheap enough that threads can create/free them on demand?

**Comment by Cyan4973** [comment]
What do you mean by "cost" ?

**Comment by keithbostic** [comment]
It's not trivial for MongoDB compression to re-use ZSTD_CStream structures: if it's cheap in terms of CPU/memory usage to create/free those structures, I won't bother doing that work.

**Comment by Cyan4973** [comment]
It's always better, from a performance perspective, to re-use `ZSTD_CStream` structures. That being said, some designs might be ill-prepared for such requirement. In which case, it may be unavoidable to alloc and free a CStream structure for each item.

Cost of creating a CStream structure is 2 sided : 
- allocation
- init

It primarily depends on the compression level, which means the majority of the cost will be effectively triggered on reaching `ZSTD_initStream()`.
Low level (1, 2) have a relatively low init cost (although, in relative terms, it depends on the size of data to compress). But then, as compression level increases, the amount of memory to allocate and init becomes bigger. At some point, it can even become the dominant cost when compressing a single item.

Re-using a `ZSTD_CStream` structure will avoid allocation. Re-using it with the same compression parameters will also avoid init. It can make a significant difference when compressing a lot of small blocks.

**Comment by keithbostic** [comment]
To be clear, I read `Start by initializing ZSTD_CStream. Use ZSTD_initCStream() to start a new compression operation.` to mean ZSTD_initCStream() must be called each time a ZSTD_CStream structure is reused, that is, when starting to compress a new chunk of data.

Is that reading correct?

Or, is that reading wrong, and ZSTD_initCStream() can be skipped when reusing ZSTD_CStream objects where the compression level isn't changing?

**Comment by Cyan4973** [comment]
Your reading is correct.
`ZSTD_createCStream()` can be shared for multiple compression operations,
but each compression operation must start by a call to `ZSTD_initCStream()`.
(or `ZSTD_initCStream_advanced()`, or `ZSTD_resetCStream()`, although these ones are advanced functions, in experimental section)

**Comment by Cyan4973** [comment]
`zstd.h` has been updated with a few code comments explaining the benefits of re-using compression context (notably, improved startup delays, and reduced memory management overhead)
