### ISSUE TITLE
[More convenient build options] Cmake or meson/ninja?

### ISSUE THREAD

**Issue by rubyFeedback** [facebook/zstd#3990]
Hey guys,

Could cmake and/or meson/ninja be added as an additional build tool?

Meson is probably the most convenient at this point. Nobody wants to do GNU configure
anymore it seems; and raw Makefiles, while they work, are not very elegant to use.

zstd right now appears to come with a simple Makefile (only). That works, so no problem here,
it can be retained. And strictly speaking cmake or meson is not necessary in such a case,
of course. But it would be a convenient additional entry, in particular when a user wants to
use custom prefixes or similar. Yes, all possibly through a Makefile too, but it is not
super-convenient to use it IMO.

Perhaps if the support for e. g. meson/ninja is not too much, or cmake, that could be
added. Anyway, just suggesting it - thanks for reading this issue request either way.

**Comment by Cyan4973** [comment]
Have you checked [`build/`](https://github.com/facebook/zstd/tree/dev/build) ?
