### ISSUE TITLE
--exclude-compressed in environement variable

### ISSUE THREAD

**Issue by Pascal76** [facebook/zstd#3992]
--exclude-compressed is not usable when using tar command for backups for ex.

tar cf $FILE.zst --use-compress-program zstd

Would be great to be able to ignore already compressed files in this case and probably other ones.

**Comment by Cyan4973** [comment]
Did you mean: 
```
tar -cf $FILE.tar.zst -I 'zstd' .
```

**Comment by Pascal76** [comment]
sorry I don't understand your question.

-I = --use-compress-program
also I did not added the directory to backup ... but that is not interesting 

For zstd, --exclude-compressed should be the default value, from my point of view, for a compressor reputed for its velocity

**Comment by gcflymoto** [comment]
I disagree. Sometimes there is a benefit to double compressing so zstd should not be forcing --exclude-compressed on everyone. You can include it yourself 

`tar cf $FILE.zst --use-compress-program 'zstd --exclude-compressed'`

**Comment by Pascal76** [comment]
ok some people may want double compressing, and for some cases too sometimes the compression is better.

Do you double compress zstd files too ?

Thank you for the command line.

**Comment by gcflymoto** [comment]
Not double .zst, but gzip+bzip2 or gzip+zstd can be a worthwhile combination

**Comment by lelik107** [comment]
> I disagree. Sometimes there is a benefit to double compressing so zstd should not be forcing --exclude-compressed on everyone. You can include it yourself
> 
> `tar cf $FILE.zst --use-compress-program 'zstd --exclude-compressed'`

I totally agree - this option should not be enabled by default.

**Comment by Cyan4973** [comment]
The current consensus is that `--exclude-compressed` can be requested as part of the `tar` command line,
and that it's not at this point a desirable default setting.
