### ISSUE TITLE
Windows binaries are missing on v1.5.6 release

### ISSUE THREAD

**Issue by viceice** [facebook/zstd#3993]
**Describe the bug**
The windows binaries are missing on the [`v1.5.6`](https://github.com/facebook/zstd/releases/tag/v1.5.6) release

**To Reproduce**
1. check the release
2. see missing windows binaries

**Expected behavior**
To have windows binaries released as before

**Screenshots and charts**
none

**Desktop (please complete the following information):**
 - OS: [e.g. Mac] Windows
 - Version [e.g. 22] 11
 - Compiler [e.g. gcc]
 - Flags [e.g. O2]
 - Other relevant hardware specs [e.g. Dual-core]
 - Build system [e.g. Makefile]

**Additional context**
none

**Comment by sergeevabc** [comment]
Aggrrhh!

[MICHAEL JACKSON — THEY DON'T CARE ABOUT US][1]

[1]: https://www.youtube.com/watch?v=t1pqi8vjTLY

**Comment by Cyan4973** [comment]
`v1.5.6` Windows binaries are now available in the assets section of the release page

**Comment by viceice** [comment]
@Cyan4973 Those are broken, double ziped 🙈, so Chrome is blocking the download because of that
