### ISSUE TITLE
v1.5.6 Windows binary downloads are double zipped

### ISSUE THREAD

**Issue by pratikpc** [facebook/zstd#4000]
**Describe the bug**
v1.5.6 windows binaries are double zipped 

**To Reproduce**
1. Download https://github.com/facebook/zstd/releases/download/v1.5.6/zstd-v1.5.6-win64.zip

**Expected behavior**
No need for double unzip

**Screenshots and charts**
NA

**Desktop (please complete the following information):**
NA

**Additional context**
NA

**Comment by pratikpc** [comment]
It has been reported that [Chrome is also blocking their downloads](https://github.com/facebook/zstd/issues/3993#issuecomment-2024610520)

**Comment by lelik107** [comment]
Yes, Yann - are you going to be a pirate :) ? And the next step will be a password - ZSTD or zstd, obviously.

**Comment by lelik107** [comment]
Yann's gonna be a pirate :) And the next step will be a password - ZSTD or zstd, obviously. Or he was just too busy with the release. Yes, nowadays, some browsers don't allow this to download.

**Comment by Cyan4973** [comment]
This should be fixed now.

Not sure how it happened. 
Strangely, there was no problem downloading the `zip` file myself using Chrome (tested again today, still successful).
Also, testing the archive, the archiver (default `macos`) directly delivers the final directory of files without any intermediate step, transparently decompressing the 2 layers of zip. That makes is harder to spot (could nonetheless confirm it by using the `unzip` cli).

**Comment by lelik107** [comment]
It's OK now. It might be @ pratikpc mentioned one of the Chromium based browsers we have a lot.  I suggest that issue should be closed.
