### ISSUE TITLE
Why was the new release 1.5.6 removed?

### ISSUE THREAD

**Issue by firasuke** [facebook/zstd#4004]
Why was the new release 1.5.6 removed from the releases page?

**Comment by doublex** [comment]
Huh...

**Comment by vimsux** [comment]
it was the CIA glowies

**Comment by lelik107** [comment]
It's might be because of this?
https://www.openwall.com/lists/oss-security/2024/03/29/4

**Comment by selfisekai** [comment]
@lelik107 that's xz, a different project

**Comment by starg2** [comment]
The message of the tag v1.5.6 says `Zstandard v1.5.6 (Re-Tagged with Signing Key)`.

Does re-tagging remove the corresponding release? I don't know.

**Comment by lelik107** [comment]
> @lelik107 that's xz, a different project

Yes, but where did LZMA & XZ codes come from?
"--format=FORMAT: compress and decompress in other formats. If compiled with support, zstd can compress to or decompress from other compression algorithm formats. Possibly available options are zstd, gzip, **xz, lzma,** and lz4. If no such format is provided, zstd is the default."

I'm not a C/C++ coder myself and can't tell apart the code from 7-Zip SDK, libarchive or XZ.

**Comment by doublex** [comment]
Does 1.5.6 generate invalid compression??

**Comment by m-vz** [comment]
For reference, here is the removed 1.5.6 release (archived): https://web.archive.org/web/20240327173034/https://github.com/facebook/zstd/releases/tag/v1.5.6

**Comment by lelik107** [comment]
> Does 1.5.6 generate invalid compression??
I packed yesterday some archives with  v1.5.6 Windows x64 and it did just fine but I'm not sure about the other OSs.

**Comment by terrelln** [comment]
It looks like it was accidentally removed. We forgot to sign the `v1.5.6` tag, and replaced the tag with a signed tag pointing to the same commit. It looks like it may have removed the release. I believe we've done this in the past, and it worked. I'm looking into it.

**Comment by terrelln** [comment]
It looks like the release was accidentally converted back into a draft. I've republished the release.

**Comment by SMillerDev** [comment]
Might want to tag 1.5.6.1 in the future since the [git manual](https://git-scm.com/docs/git-tag#_on_re_tagging) says re-tagging is "the insane thing" to do.

**Comment by selfisekai** [comment]
same sha512sum for the current tarball as around `2024-03-27 02:35:41 +0100`

**Comment by terrelln** [comment]
> Does 1.5.6 generate invalid compression??

No, there are no known flaws with v1.5.6.

> It's might be because of this?
> https://www.openwall.com/lists/oss-security/2024/03/29/4

It is completely unrelated.

**Comment by terrelln** [comment]
> Might want to tag 1.5.6.1 in the future since the [git manual](https://git-scm.com/docs/git-tag#_on_re_tagging) says re-tagging is "the insane thing" to do.

It is less crazy, given that the tags point to the same commit, the only difference is the presence of a signature. But, we'll discuss changing our workflow, and will likely avoid overwriting tags for future releases, to avoid this confusion.

**Comment by lelik107** [comment]
> > Does 1.5.6 generate invalid compression??
> 
> No, there are no known flaws with v1.5.6.
> 
> > It's might be because of this?
> > https://www.openwall.com/lists/oss-security/2024/03/29/4
> 
> It is completely unrelated.

It's OK. So It's solved.
