### ISSUE TITLE
long file names are cut off in output

### ISSUE THREAD

**Issue by Mitmischer** [facebook/zstd#4005]
**Describe the bug**
When dealing with large archive names, zstd will just print the last chars of the name.
This is troublesome in the presense of non-attributable error messages.
As a real use case, I ran into this when analyzing incomplete archives on a disk that went full during the compression procedure.
(As an aside, shouldn't zstd just remove incomplete archives as those are useless and harmful anyway?).
This issue arises both in `bash` and `fish`.

**To Reproduce**
```
/tmp $ cd /tmp
/tmp $ echo "hello" > somereallylongfilename
/tmp $ zstd somereallylongfilename
somereallylongfilename :316.67%   (     6 B =>     19 B, somereallylongfilename.zst) 
/tmp $ truncate somereallylongfilename.zst --size 10
/tmp $ zstd -t somereallylongfilename.zst
allylongfilename.zst : 0 B...     allylongfilename.zst : Read error (39) : premature end 
/tmp $ 
```

**Expected behavior**
At last in error messages, I expect the file name to be complete (also consider using the full path for full unambiguity).
For the case, above, this would mean on of the following two alternatives:
```
allylongfilename.zst : 0 B...     somereallylongfilename.zst : Read error (39) : premature end 
allylongfilename.zst : 0 B...     /tmp/somereallylongfilename.zst : Read error (39) : premature end 
```

**Screenshots and charts**
None.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: Arch Linux rolling, zstd 1.5.5-1
 - Compiler: / (no self-compiled binary, source distributed binary is used)
 - Flags: /
 - Other relevant hardware specs: not relevant
 - Build system: / (for details on how Arch Linux builds zstd, see https://gitlab.archlinux.org/archlinux/packaging/packages/zstd/-/blob/main/PKGBUILD)

**Additional context**
None.

**Comment by terrelln** [comment]
I believe that @Cyan4973 made passing `-v` output the entire filename.

**Comment by Cyan4973** [comment]
I think this request is more general,
essentially it states that filenames ought to remain complete in case of errors.

**Comment by Mitmischer** [comment]
Just stopping by to say it's *awesome* how quickly this has been handled @Cyan4973 !
Thank you :)
