### ISSUE TITLE
Decompress multiple zstaa backups on FAT32 drives

### ISSUE THREAD

**Issue by oDinZu** [facebook/zstd#4014]
**Is your feature request related to a problem? Please describe.**
I tar/compressed my entire `/home` directory and `split` each zst into multiple 4.3GB chunks for FAT32 formatted drives.

**Describe the solution you'd like**
I haven't been able to figure out a simple solution for decompressing each .zstaa, zstab, etc... automatically. 

At the moment, I must rename each zstaa to .zst and then decompress each .zst and extract that file into the correct location.

**Describe alternatives you've considered**
Maybe remove the .zst check when decompressing multiple files?

**Additional context**
I tried doing something like this: `for i in *zst*; do zstd -d "$i" & done`, but still bumped into having the .zst extenstion check requirement.

I also tried putting all the .zst* files into a directory/folder and then doing: `zstd -dr Desktop/`, but again, had the same issue as stated before.

**Comment by Cyan4973** [comment]
The `*.zst` suffix requirement is because the CLI must determine a destination filename.
If it doesn't need to generate such a name, the `*.zst` requirement is dropped.

So one way to achieve your objective could be : 
```
zstd -d *.zst* -c > dest.tar
```
This however implies that `*zst*` shell expansion is properly ordered, which I'm not sure of.
There are probably more elaborated way to generate this list of files that would guarantee proper alphabetical order.
But you get the idea for the `zstd` part.

**Comment by oDinZu** [comment]
I tried that and received and error, but the file size seems to have added another file; each zst is 4.3GB and the dest.tar is now 8.2GB..or maybe that is the actual size `uncompressed`: 

`zstd -d *.zst* -c > /home/username/dest.tar`

```
top.backup.tar.zstaa : Read error (39) : premature end 
zstd: Desktop.backup.tar.zstab: unsupported format 
zstd: Desktop.backup.tar.zstac: unsupported format 
zstd: Desktop.backup.tar.zstad: unsupported format 
zstd: Desktop.backup.tar.zstae: unsupported format 
zstd: Desktop.backup.tar.zstaf: unsupported format 
zstd: Desktop.backup.tar.zstag: unsupported format
```

Also, 
`*** Zstandard CLI (64-bit) v1.5.5, by Yann Collet ***`

**Comment by Cyan4973** [comment]
Ah, you cut _after_ compression, not before.

In this case, this is more like : 
```
cat *.zst* | zstd -d > dest.tar
```

Same idea here, this only works if expansion of `*.zst*` is properly ordered.

**Comment by oDinZu** [comment]
That worked! You rock and thank you! Now, to simplify the command and also untar :smile: 

For others on the internet, the one liner I made use of to tar and compress with zstd. 

I backed up ~120GB SSD onto a FAT32 1.5TB disk drive in less than 15 minutes with default compression algorithms :tada: 

Thank you zstd! :raised_hands: 

## Compress / Decompress Huge Files via zstd with PROGRESS indication via PV

The required packages are: 

* tar
* pv
* zstd
* dosfsck

### Check the filesize in chunks for the FAT32 drive
```
sudo dosfsck -v -n /dev/sda1
```
**File size is 4294967295 bytes, cluster chain length is 0 bytes.**

### Split the tar into files to transport between drives e.g. FAT32 formatted drive and filter/compress with zstd with -I option into another drive, while visualizing a progress counter with pv.
```
tar -I zstd -cf - Desktop/ | (pv -p --timer --rate --bytes | split --bytes=4294967295 - /run/media/username/Backups/System/Linux/Desktop/Desktop.backup.tar.zst)
```

### Decompress multiple *zst* files between drives
`cat *.zst* | zstd -d > /home/username/dest.tar`

### Then extract the archive
`tar -xvf dest.tar`

or extract the archive into specific directory

`tar -xvf dest.tar -C /opt/files`
