### ISSUE TITLE
Decompression speed regression in zstd 1.5.6 (win)

### ISSUE THREAD

**Issue by oleg-st** [facebook/zstd#4018]
Comparison between [zstd-v1.5.6-win64.zip](https://github.com/facebook/zstd/releases/download/v1.5.6/zstd-v1.5.6-win64.zip) and [zstd-v1.5.5-win64.zip](https://github.com/facebook/zstd/releases/download/v1.5.5/zstd-v1.5.5-win64.zip):

C:\Downloads\zstd-v1.5.6-win64>zstd.exe -b5 C:\\.data\dickens
5#dickens           :  10192446 ->   3529639 (x2.888),  145.2 MB/s, **1608.3** MB/s
C:\Downloads\zstd-v1.5.5-win64>zstd.exe -b5 C:\\.data\dickens
5#dickens           :  10192446 ->   3529639 (x2.888),  146.3 MB/s, **1662.8** MB/s

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.5.6
- CPU: 12th Gen Intel Core i7-12700, 1 CPU, 20 logical and 12 physical cores

**Comment by Cyan4973** [comment]
This is most likely a side effect of random instruction alignment.
Modern cpus are pretty sensitive to instruction alignment when the code is approaching the limit of their performance, i.e. when the code is not slowed down by other issues such as waiting for RAM data.

This is uncontrollable from `C` unfortunately: these decisions are taken by compilers, and these days, compilers are incredibly complex heuristics machine, and on this topic specifically, they get it better or worse essentially randomly. The way to observe that is to compile the code with multiple compilers and compiler versions, and see the performance difference change in either direction randomly. One may also modify the code, in a typically unrelated part (such as the compression part) and see nonetheless the decompression performance change after this modification.

In this context, 3% is not that much. We have witnessed differences of up to 20% due solely to random instruction alignment side effect. So, assuming the 1.5.5 windows binary was on the luckier side of the distribution, a 3% difference is about fine.

**Comment by gcflymoto** [comment]
Could Meta's clang BOLT help with compiler version randomness effects like this?

**Comment by Cyan4973** [comment]
It probably does help,
though my understanding is that BOLT deal with positions of fragments,
so it doesn't go down to single instruction.
Yet, I suspect this mechanism is enough to take care of half the problems.

**Comment by gcflymoto** [comment]
Hi @Cyan4973 I have a GH zstd fork with an integration of BOLT into the Makefile that "does the job.".. It adds a new "zstd-bolt" target. I can create PR to start a discussion. I could see the "zstd-bolt" target as an experimental addition on the dev branch for the zstd community to test. How does that sound?

**Comment by Cyan4973** [comment]
sounds good
