### ISSUE TITLE
Make a branch for every version

### ISSUE THREAD

**Issue by Bulat-Ziganshin** [facebook/zstd#402]
I think it's usual practice to create a branch for every release - 1.0, 1.1 and so

**Comment by Cyan4973** [comment]
It's necessary when maintaining several versions in parallel.
We haven't yet adopted this model, we are supporting a single version, the latest one.

**Comment by Bulat-Ziganshin** [comment]
Sorry for the noise!! It's just my ignorance and now i figured out that the Releases section has the link to 1.1 sources that I need: https://github.com/facebook/zstd/blob/v1.1.0/lib/compress/zstd_compress.c#L3044
