### ISSUE TITLE
Decompression crash after upgrading from zstd 1.4.5 to 1.5.6

### ISSUE THREAD

**Issue by marcinlawicki-hg** [facebook/zstd#4024]
**Describe the bug**
This request is more for advice than for help with an actual bug. I am working on a codebase that integrates with `zstd 1.4.5` and uses the `ZSTD_f_zstd1_magicless` compression format. After upgrading from `zstd 1.4.5` to `1.5.6`, decompression started crashing. I've noticed this is due to changes in internal structures and implementation, with `ZSTD_f_zstd1_magicless` being replaced by `ZSTD_f_zstd1`. I attempted to tweak `1.5.6` to force `ZSTD_f_zstd1_magicless`, and while this stopped the decompression from crashing, it now produces invalid output (it does, however, correctly decompress archives compressed with `1.4.5` using `ZSTD_f_zstd1_magicless`).
Since there are numerous differences between the two `zstd` versions, it doesn't make sense for me to try further modifications.

So, my question is, can I somehow force `zstd 1.5.6` to use `ZSTD_f_zstd1_magicless`?

**Expected behavior**
I expect to be able to compress and decompress with `1.5.6` using `ZSTD_f_zstd1_magicless` as compression format.

**Desktop (please complete the following information):**
 - OS: Windows/WSL
 - Version 1.5.6

**Comment by Cyan4973** [comment]
cc @embg

**Comment by embg** [comment]
@marcinlawicki-hg Can you share the code you are using for compression and decompression?

If you want to decompress magicless format, you should use
```
ZSTD_DCtx_setParameter(dctx, ZSTD_d_format, ZSTD_f_zstd1_magicless)
```

If you want to compress magicless format, you should use
```
ZSTD_CCtx_setParameter(cctx, ZSTD_c_format, ZSTD_f_zstd1_magicless)
```

Is it possible that you have a mismatch between the compression-side format and the decompression-side format? There is no change in default behavior between `1.4.5` and `1.5.6`.

> I've noticed this is due to changes in internal structures and implementation

Which changes are you referring to? What error are you seeing?

**Comment by marcinlawicki-hg** [comment]
> @marcinlawicki-hg Can you share the code you are using for compression and decompression?
> 
> If you want to decompress magicless format, you should use
> 
> ```
> ZSTD_DCtx_setParameter(dctx, ZSTD_d_format, ZSTD_f_zstd1_magicless)
> ```
> 
> If you want to compress magicless format, you should use
> 
> ```
> ZSTD_CCtx_setParameter(cctx, ZSTD_c_format, ZSTD_f_zstd1_magicless)
> ```
> 
> Is it possible that you have a mismatch between the compression-side format and the decompression-side format? There is no change in default behavior between `1.4.5` and `1.5.6`.

@embg Thank you for your response. The formats have been properly matched. Here's the sequence for setting the format for decompression.
First, we set the format:
```
ZSTD_DCtx_setFormat( m_ctx, ZSTD_f_zstd1_magicless );
```
Then, retrieve the frame header data this way:
```
ZSTD_getFrameHeader_advanced( &fhdr, hdrPacked, hdrSizePacked, ZSTD_f_zstd1_magicless );
```
Followed by the decompression:
```
ZSTD_inBuffer in = { hdrPacked, hdrSizePacked, 0 };
ZSTD_outBuffer out = { hdr, hdrSize, 0 };
ZSTD_decompressStream( m_ctx, &out, &in );
```

Compression is done by setting the format:
```
ZSTD_CCtx_setParameter( ctx, ZSTD_c_format, ZSTD_f_zstd1_magicless );
```
This is then followed by:
```
ZSTD_compressCCtx( .... )
```

> > I've noticed this is due to changes in internal structures and implementation
> 
> Which changes are you referring to? What error are you seeing?

I was referring to differences in the implementation, not any particular errors. For example, in version `1.5.6` there is a new member called `simpleApiParams` in the `ZSTD_CCtx` structure. It is being cleared in `ZSTD_CCtxParams_init_internal`, effectively setting compression format to `ZSTD_f_zstd1`, and it's later assigned to `appliedParams` in a call to `ZSTD_resetCCtx_internal`. Before I added a flag to override the clearing of the compression format in `simpleApiParams`, the decompression was crashing. After I added it, it no longer crashes but produces invalid output.
However, decompression with `1.5.6`, does work for files compressed with `1.4.5` (with and without the override flag I mentioned).

**Comment by felixhandte** [comment]
https://github.com/facebook/zstd/blob/794ea1b0afca0f020f4e57b6732332231fb23c70/lib/zstd.h#L263-L274

`ZSTD_compressCCtx()` ignores parameters set on the CCtx. It aims to be exactly like invoking `ZSTD_compress()` other than that you get to reuse a context to avoid reallocating/reinitializing the internal data structures.

For the parameters on the CCtx to apply, you want to use `ZSTD_compress2()`:

https://github.com/facebook/zstd/blob/794ea1b0afca0f020f4e57b6732332231fb23c70/lib/zstd.h#L588-L602

**Comment by marcinlawicki-hg** [comment]
Hi @felixhandte, thank you for quick response and sorry for the delay from my side. I have replaced `ZSTD_compressCCtx` with `ZSTD_compress2` and it had the same effect as me forcing compression format, meaning - no more crashes.
However, because I have used some specific asset, it was causing execution of only one of the two compression steps. With a different asset, the image data is first compressed with `ZSTD_compress_usingDict` and after that it is combined with metadata and sent to `ZSTD_compress2`. Decompression of archives created that way produces invalid images in the output.

**Comment by Cyan4973** [comment]
I presume you mean that now you have a mixture of frames, some with a `zstd` magic number, and some magic-less.
And now that the decoder is no longer permissive in `v1.5.6`, passing a frame with a magic number to the magic-less decoder will fail. So it makes the decompression setup more complex, as you need first to identify in which case you are (magic number, or magic-less) and then select the right decompression variant or right parameter.

I presume you would prefer a decoder that is more permissive, and would accept both magic and magic-less frames, and decompress them correctly in both cases.

**Comment by marcinlawicki-hg** [comment]
Unless our current implementation is invalidated by changes between `v1.4.5` and `v1.5.6`, I think that is not the case. Before calling `ZSTD_compress_usingDict`, compression format is set to magic-less with `ZSTD_CCtx_setParameter( ctx, ZSTD_c_format, ZSTD_f_zstd1_magicless )`.
At the later stage, before calling `ZSTD_compress2`, magic-less is set with `ZSTD_CCtx_setParameter( ctx, ZSTD_c_format, ZSTD_f_zstd1_magicless )` (there are two separate instances of `ZSTD_CCtx` btw.).

So, my understanding is that magic-less compression format should be used in both steps, and, since decompression is using the same format, it should be fine.
When looking at the memory view of dictionary and the memory view of the output of `ZSTD_compress_usingDict`, I see they differ between `v1.4.5` and `v1.5.6`. Is it maybe now that `ZSTD_compress_usingDict` is ignoring compression format set in the context, like `ZSTD_compressCCtx` did?

**Comment by terrelln** [comment]
`ZSTD_compress_usingDict()` does not use the advanced parameters.

You're right that in `v1.4.5` both `ZSTD_compressCCtx()` and `ZSTD_compress_usingDict()` used some of the advanced parameters. But, now the only functions that uses advanced parameters are `ZSTD_compress2()`, and the streaming API.

When you say that decompression crashes, do you mean that zstd decompression fails and returns an error code, and then your code crashes / assert fails or something? Or that decompression crashes inside of zstd? I assume it is the former, but if it is the latter, then we have something to fix.

**Comment by marcinlawicki-hg** [comment]
It crashes in our code since the header data is being incorrectly interpreted, due to mismatch in compression format. That is, however, solved by replacing `ZSTD_compressCCtx` with `ZSTD_compress2`.

It looks like we need to stop using `ZSTD_compress_usingDict` if we wish to keep magic-less format.
Could you please advise if creating dictionary explicitly with `ZSTD_createCDict` and compressing with `ZSTD_compress_usingCDict` (as presented in this [example](https://github.com/facebook/zstd/blob/dev/examples/dictionary_compression.c)) will yield the same results as using `ZSTD_compress_usingDict` with magic-less in `v1.4.5`?

**Comment by terrelln** [comment]
`ZSTD_compress2()` also supports dictionary compression. You can load a dictionary using one of the following methods:

```c
ZSTD_CCtx_loadDictionary()
ZSTD_CCtx_refCDict()
```

The dictionary will be used until another dictionary is set via any means, or the context parameters are reset using `ZSTD_CCtx_reset()` with any value other than `session_only`.

See the docs here:

https://github.com/facebook/zstd/blob/ff7a151f2e6c009b657d9f798c2d9962b0e3feb5/lib/zstd.h#L1045-L1170

Sorry for this breakage! This combo of using advanced parameters with the normal compression function was never an intended usage. When we removed it, we hoped that no one was using it in practice.

A full example (without error checking) would be:

```c
size_t compressUsingDictionary(void* dst, size_t dstCapacity, void const* src, size_t srcSize, void const* dict, size_t dictSize, int level) {
  ZSTD_CCtx* cctx = ZSTD_createCCtx();
  ZSTD_CCtx_setParameter(cctx, ZSTD_c_format, ZSTD_f_magicless);
  ZSTD_CCtx_setParameter(cctx, ZSTD_c_compressionLevel, level);
  ZSTD_CCtx_loadDictionary(cctx, dict, dictSize);
  size_t const ret = ZSTD_compress2(cctx, dst, dstCapacity, src, srcSize);
  ZSTD_freeCCtx(cctx);
  return ret;
}

size_t compressUsingCDict(void* dst, size_t dstCapacity, void const* src, size_t srcSize, ZSTD_CDict const* cdict) {
  ZSTD_CCtx* cctx = ZSTD_createCCtx();
  ZSTD_CCtx_setParameter(cctx, ZSTD_c_format, ZSTD_f_magicless);
  ZSTD_CCtx_refCDict(cctx, cdict);
  size_t const ret = ZSTD_compress2(cctx, dst, dstCapacity, src, srcSize);
  ZSTD_freeCCtx(cctx);
  return ret;
}
```

**Comment by marcinlawicki-hg** [comment]
Thanks a lot! Got it working with your help!
