### ISSUE TITLE
Improve misleading wording in the streaming decompression howto

### ISSUE THREAD

**Issue by dbuenzli** [facebook/zstd#4030]
**Describe the bug**

The wording [here](https://github.com/facebook/zstd/blob/ff7a151f2e6c009b657d9f798c2d9962b0e3feb5/lib/zstd.h#L870-L871) is slightly misleading. You should not call again `ZSTD_decompressStream()` if  `output.pos == output.size` **and** the function returned `0`.

**Expected behavior**

Perhaps this could be changed to:

```
*  But if `output.pos == output.size` and the function returns greater than 0 there might be some data left within internal buffers.,
```

(I would have gladly PR'd but on a matter of principle I don't sign CLAs).

**Comment by dbuenzli** [comment]
Thank you!

**Comment by archshift** [comment]
I think the wording could be stronger, and explicitly say that it is an error to call the function in that condition if that's the case.
