### ISSUE TITLE
Building on MacOS 13 and targeting MacOS 11 and SDK 11.3 (or any other MacOS version) does not work

### ISSUE THREAD

**Issue by lukaso** [facebook/zstd#4038]
**Describe the bug**
As of v1.5.6, the minos and sdk settings are no longer respected. This works on version 1.5.5.

(It is possible this is an interaction with MacPorts where I am building the library.

**To Reproduce**
1. Install macports
2. `echo 'macosx_deployment_target 11.0' | tee -a ${PREFIX}/etc/macports/macports.conf`
  `echo 'macosx_sdk_version 11.3' | tee -a ${PREFIX}/etc/macports/macports.conf`
4. `sudo port install -sv zstd`
5. look in macports `lib` directory and run `otool -l libzstd.1.dylib`
6. see output includes `minos` and `sdk` of the current OS, rather than `minos 11.0` and `sdk 11.3` 

**Expected behavior**
Should correctly set the OS and SDK versions in the dylib.

**Screenshots and charts**
If applicable, add screenshots and charts to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Mac
 - Version 14.4.1
 - Compiler clang
 - Flags not sure
 - Other relevant hardware specs not relevant
 - Build system CMAKE

**Additional context**
Downstream bug reports:
https://trac.macports.org/ticket/69944#comment:1
https://gitlab.gnome.org/GNOME/gimp/-/issues/11483

**Comment by Cyan4973** [comment]
Isn't that a `MacPorts` issue ?

**Comment by lukaso** [comment]
> Isn't that a MacPorts issue ?

I doubt it because other than trivial changes to the MacPorts build file (`Portfile`), the build is unchanged between 1.5.5 and 1.5.6. And 1.5.5 doesn't have this problem. It could potentially be MacPorts if they are using a non-standard way of indicating the OS and SDK, however the hundreds of other packages on MacPorts that GIMP uses, don't have this problem.
