### ISSUE TITLE
Dynamic decompression

### ISSUE THREAD

**Issue by oscarbaselga** [facebook/zstd#4062]
I am trying to compress the traffic sent over Linux sockets. To this end, I implemented a TCP client which transmits dummy messages (compressed with ZSTD into 20 bytes) to a TCP server (which does not generate any response). If the client sends just one message, the server receives and decompresses it successfully. However, if the client sends for example two consecutive messages, the servers reads 40 bytes at once from the socket buffer and fails during the decompression. I am convinced that this happens because the server does not distinguish them, so it tries to decompress both messages as they were only one. I imagine that the problem is related to the memory allocation and the read of the ZSTD headers.

I would like a solution which provides an interface for real-time processing, allowing to decompress blocks of messages at a time.

I considered to add a separator between messages in the socket buffer and decompress them individually, but it is not an optimal solution.

**Comment by Cyan4973** [comment]
Presuming you are using the reference version of `zstd` hosted in this repository,
the decompression function is able to decompress multiple compressed frames sent together back to back concatenated.

> if the client sends for example two consecutive messages, the servers reads 40 bytes at once from the socket buffer and fails during the decompression. I am convinced that this happens because the server does not distinguish them, so it tries to decompress both messages as they were only one.

Indeed, if you send both messages together, and ask `zstd` to decompress them together, as a single block, in a one-shot decompression function, then `zstd` will decompress them both, and produce a result which is a concatenation of both.

If your application relies on receiving each message individually, and expects `zstd` to stop at the end of each compressed frame (corresponding to a single message), there are a few options : 
1) Ask for the compressed size of the first frame (using `ZSTD_findFrameCompressedSize()`), submit each compressed frame one by one
2) Use the Streaming API `ZSTD_decompressStream()`, it will stop at each frame boundary, with a return code of `0`. Check this return code, stop consuming the input at this moment and process your message. Resume decompression for next messages.

**Comment by oscarbaselga** [comment]
Understood! Is there any example in which the Streaming API is applied to Linux sockets? I see that current examples only use files.

**Comment by Cyan4973** [comment]
All examples are in the `examples/` directory.
They are just very simple scenarios, to illustrate how the API can be used.
Your specific project is unlikely to be directly represented there.
