### ISSUE TITLE
Poor compressor behavior on interleaved data

### ISSUE THREAD

**Issue by elasota** [facebook/zstd#4072]
I've been doing some comparative analysis on why libdeflate seems to be outperforming zstd on small (~64kb) blocks despite having a less-sophisticated compression algorithm and it seems to be just due to the encoder making better decisions.  I've been investigating some of the outliers and it seems like repetitive data interleaved with non-repetitive data seems to be especially bad, since Zstd seems to sometimes prefer emitting large blocks of literals instead of repeated-offset-1 matches.

Attached a sample bad case where a Zstandard block converted from a deflate block was 30% smaller.
- `fail_block_2118.bin`: Sample data (from OpenArena)
- `zstdcompressed_nosplit.zst`: Data compressed with Zstd level 22
- `zstdcompressed_nosplit.txt`: Decompiled version of previous file
- `converted.zst`: Data compressed with libdeflate 12 and converted to a Zstandard block
- `converted.txt`: Decompiled version of previous file

[zstd_striped.zip](https://github.com/user-attachments/files/15792580/zstd_striped.zip)

**Comment by Cyan4973** [comment]
Which version of `zstd` are you using ?

On a local system, I'm seeing 9062 bytes at levels 19-22 for this sample.

**Comment by elasota** [comment]
Retested with latest, seems to have been fixed by PR #3895
