### ISSUE TITLE
[Not a bug] Dictionary building strategy

### ISSUE THREAD

**Issue by sreendra** [facebook/zstd#4077]
**Describe the bug**
Hi @Cyan4973 ,
Sorry for reporting this as a bug as i don't have a way to reach out to you/team to get this info

I would like to digest a dictionary which i want to use it for all the users. My Blob which i want to compress varies for documents, folders, within documents - pdfs/docx/ppt/jpeg/video etc there are multiple types ...
2. It is a key, value pair object but not a json object
3. Within a given type, content of blob varies from document to document i..e., if i have 2 photos (photo1 and photo2), content for photo1 varies from content for photo2...there is a high chance that the keys may be same ...at times, keys also might slightly differ

With this set up,
1. if i want to train a dictionary(using the API - ZDICT_trainFromBuffer ), is it enough to choose 1 doc from each type or do i have to run it on multiple files of the same type.

2. I tried to train using some 700 samples data whose size came around to be ~12MB(sum of samples size)...should i pass dictBufferCapacity to be 12MB or send default value of 110 KB.?

Thank you

**To Reproduce**
1. Downloads data '...'
2. Run '...' with flags '...'
4. Scroll up on the log to '....'
5. See error

**Expected behavior**

**Screenshots and charts**
If applicable, add screenshots and charts to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Mac]
 - Compiler [e.g. gcc]
 - Flags [e.g. O2]
 - Other relevant hardware specs [e.g. Dual-core]
 - Build system [e.g. Makefile]

**Additional context**

**Comment by Cyan4973** [comment]
> if i want to train a dictionary(using the API - ZDICT_trainFromBuffer ), is it enough to choose 1 doc from each type or do i have to run it on multiple files of the same type.

The point of a Dictionary is to capture commonalities _across_ samples. So yes, you'll need multiple samples to train a dictionary. I believe the trainer even refuses to start if it doesn't receive a minimum amount of samples.

> I tried to train using some 700 samples data whose size came around to be ~12MB(sum of samples size)...should i pass dictBufferCapacity to be 12MB or send default value of 110 KB.?

110 KB looks appropriate to me. In your example, there is a ~100:1 ratio between samples and dictionary size, which feels about right.

**Comment by sreendra** [comment]
I tried to train using some 700 samples data whose size came around to be ~12MB(sum of samples size)...should i pass dictBufferCapacity to be 12MB or send default value of 110 KB.?

110 KB looks appropriate to me. In your example, there is a ~100:1 ratio between samples and dictionary size, which feels about right.

Thank you @Cyan4973 for the response.

Just one 2 more follow up questions on the same. 
1. I tried building dictionary passing in 110KB as **dictBufferCapacity** (with 700 samples), after training, i saw the dictBuffer size as 110KB but when i chose some 20MB for **dictBufferCapacity** , i saw the dictBuffer size to be 700KB. In this scenario what number should i choose (sorry for asking naive question) ?
2. Just in case if i am required to build another dictionary(ies) because of decay, how would i handle such scenario ...say if i maintain D1, D2 and D3 dicts, and there is a record r1 compressed using D1, then how would i know i compressed r1 using D1 and the rest with other dicts ? I am afraid i have to traverse all the dicts to see which is the dict used for compression and use the same dict D1 for decompression and the latest dict for compression again ...Here i might be required to maintain all the dicts created. How would i solve this problem ? Is there an elegant way of handling this conundrum ?

**Comment by Cyan4973** [comment]
I guess it means the dictionary trainer considers there is no more than 700KB worth of data for a dictionary in these samples.

You could try any value you want, from very small (~4KB) up to very large, with everything above 700 KB being essentially the same as 700 KB.

Which value works best depends on your use case, and your cost trade off.
This is a local decision, there is no one side fits all.
If unsure, try, test and benchmark multiple dictionary sizes, and pick whichever one works best for you.

**Comment by sreendra** [comment]
Sure @Cyan4973 ...thank you

**Comment by sreendra** [comment]
Hi @Cyan4973 ,

One small information, i would like to know as part of dictionaries... 

How often(i know its a very abstract question), would i be required to change the dictionary ? Can you please the parameters that would lead to change of dictionary ?

**Comment by Cyan4973** [comment]
This depends on how fast your data is changing.

Eventually, train a new dictionary from time to time, check if it compresses better than the existing one, and if it does, switch to the new dictionary (and keep the old one around as long as data compressed with it exist).

Some data sources may remain stable for years, while other may change abruptly one month to another. There's no rule.

**Comment by sreendra** [comment]
Thank you
