### ISSUE TITLE
ZSTD_initCStream is slow

### ISSUE THREAD

**Issue by liewegas** [facebook/zstd#408]
In my use case I am compressing relatively small bits of data (10's to 100's of KB at a time), each with a fresh dictionary.  My simple test benchmarks are dominated by ZSTD_initCStream, with 95% CPU time consumed by the memset() call.

Is this something that can easily optimized?  I can reuse CStreams, but I can't share dictionaries across compressed blobs.

Thanks!

**Comment by terrelln** [comment]
If you are using the same dictionary there is `ZSTD_resetCStream()`, but it sounds like that isn't the case.

`ZSTD_initCStream_usingCDict()` and `ZSTD_initDStream_usingDDict()` functions are planned for this use case.

**Comment by inikep** [comment]
Are you using `ZSTD_compress_usingDict` or `ZSTD_compress_usingCDict`? 

You may also try the funcions `ZSTD_initCStream_usingDict` and `ZSTD_initDStream_usingDict`. They are available only in experimental/advanced API. 

Moreover you should remember that the memory size and `memset()` highly depends on `compressionLevel`.

**Comment by liewegas** [comment]
I'm using neither, since I want each compressed blob to have an 
independent dictionary.  Currently, for each blob, I'm doing

    ZSTD_CStream *s = ZSTD_createCStream();
    ZSTD_initCStream(s, COMPRESSION_LEVEL);
    ...
    while (...) {
      ...
      ZSTD_compressStream(s, &outbuf, &inbuf);
      ...
    }
    ZSTD_flushStream(s, &outbuf);
    ZSTD_endStream(s, &outbuf);
    ZSTD_freeCStream(s);

I can easily reuse the CStream to avoid the allocation/deallocation, but 
the real pain is initCStream.  Is there a way to get a fresh dictionary 
without the memset?

**Comment by inikep** [comment]
After:
```
ZSTD_createCStream
ZSTD_initCStream
while (...) ZSTD_compressStream
ZSTD_flushStream
ZSTD_endStream
```
You can use many times:
```
ZSTD_resetCStream
while (...) ZSTD_compressStream
ZSTD_flushStream
ZSTD_endStream
```

**Comment by liewegas** [comment]
Ah, that's much better. Thank you!
