### ISSUE TITLE
We need an nginx binding

### ISSUE THREAD

**Issue by rugk** [facebook/zstd#409]
We need an nginx module for this, so the web can speed up! 😃 :rocket:

**Comment by ariq01** [comment]
yup, nginx module, so the name would be ngx-zstd or ngx-zstandard 👍

**Comment by centminmod** [comment]
yes please 👍

**Comment by txtsd** [comment]
While this is a great idea, it will only be implemented if the major browsers decide to implement the decompression.

**Comment by Cyan4973** [comment]
Request for HTTP content encoding has been formally started :
https://tools.ietf.org/id/draft-kucherawy-dispatch-zstd-00.html

**Comment by tokers** [comment]
Any plan for the nginx filter module for zstd? ☺

**Comment by Cyan4973** [comment]
I guess it's tied to MIME / Media Type registration, which is currently being requested here :
https://tools.ietf.org/id/draft-kucherawy-dispatch-zstd-01.html

**Comment by lbadger** [comment]
Any progress on this?

**Comment by Cyan4973** [comment]
Yes,
final revision should be online in the next few days,
then final vote is planned May 24th.

**Comment by centminmod** [comment]
@Cyan4973 thanks for the update 👍

**Comment by felixhandte** [comment]
Update:

Zstd has been standardized as [RFC 8478](https://tools.ietf.org/html/rfc8478), which included registering a "`zstd`" content coding for HTTP.

We would love to see community adoption of Zstd for HTTP. I plan to spend some of my time pushing to make that happen, and Nginx is definitely on my list of target projects. However, I don't expect to get to it in the near future. So if any of you want to write up a binding, that would certainly be welcome from our end!

**Comment by tokers** [comment]
The zstd-nginx-module is complete (basically), I'd like to add some test cases when I have a vacation.

I don't test the compatibility with various Nginx version, I just test it with `Nginx/1.15.5`. Please report the compatibility broken problems to me if you ever encountered.

This Nginx module contains the basic functions to configure zstd (just like gzip and br).

PRs and issues are welcome if you think some features are good or some performances are bad.

See https://github.com/tokers/zstd-nginx-module for more details.

**Comment by tokers** [comment]
I have created another nginx module which named as `ngx_http_zstd_static_module`, to serve the pre-compressed zstd files on disk. This module is similar with `ngx_http_gzip_static_module`.

See https://github.com/tokers/zstd-nginx-module for more details.

**Comment by Cyan4973** [comment]
I guess @tokers ' module closes this topic

**Comment by stapelberg** [comment]
> I guess @tokers ' module closes this topic

Having to build your own version of nginx is quite the hurdle to jump through depending on the environment.

Has there been any effort to get the zstd module merged into upstream nginx?

I think having zstd available by default would significantly boost adoption.

Thanks,

**Comment by muuvmuuv** [comment]
Soo, sorry in the first place to comment on this old issue but is there now any NGINX implementation? Just found @tokers version, but it is 2 years old, so I have no idea if it is still the way to go.

**Comment by rthamrin** [comment]
I tried this but confuse to implement it inside of my nginx.conf kubernetes. no so much information

**Comment by CoderJoeW** [comment]
2022 still need an nginx module we adopted Zstandard for all our compression/decompression needs replacing GZIP a while back and it has been the best move we ever made. Now we need to do the same for the web
