### ISSUE TITLE
Add back `error_public.h` to `zstd.h`?

### ISSUE THREAD

**Issue by david-y-lam** [facebook/zstd#410]
I see it was removed in commit https://github.com/facebook/zstd/commit/e72efeb0a13e919979b67acc7229f987f99cbcbd, what's the reasoning? Is there some another way to translate an error code? I currently have some hacky code that does this checking by hardcoding specific values instead of making use of `ZSTD_getErrorCode`:

```
size_t ZSTD_error_dstSize_tooSmall = (size_t)-11;
size_t res = ZSTD_decompress(...);
if (res == ZSTD_error_dstSize_tooSmall) {...}
```

**Comment by advancedxy** [comment]
ping @Cyan4973 .

I also met this problem. App has no access to zstd error codes list

**Comment by Cyan4973** [comment]
The main reason is that `error_public.h` is not distributed as part of `include` installation,
so requiring its presence within `zstd.h` would produce some `#include` error for programs using library linking only (as opposed to integrating the source code directly).

We will have to change that.
`error_public.h` is way to generic to pollute `include` namespace.
So we'll have to change the name of this file too.

**Comment by Cyan4973** [comment]
latest update in `dev` branch brings the following changes : 
- `error_public.h` is renamed `zstd_errors.h`.
- `zstd_errors.h` is part of installation process, hence present in `include` after installation.

Note that `zstd_errors.h` is not part of `zstd.h`, and requires to be explicitly included to access its capabilities.

Let me know if it helps your issue.

**Comment by advancedxy** [comment]
Yes, it sounds good. Thanks.

**Comment by david-y-lam** [comment]
@Cyan4973, thanks!
