### ISSUE TITLE
zstdgrep & zstdless tools

### ISSUE THREAD

**Issue by kshcherbatov** [facebook/zstd#411]
Hi! As you possibly know gzip provides zless and zgrep scripts. They could be easily adapted to zstd usage just by switching "gzip" calls to "zstd"(argv flags in this use case looks similar). 
I know that you have implemented inherent zstdcat & unzstd presented as symlinks to the end-user, but why not to support zstdgrep and zstdless the other way, using scripts, like gzip does?

Hope to see this feature in next release :) thx.

P.S. Concept-idea patch to git://git.savannah.gnu.org/gzip.git here https://github.com/kshcherbatov/playground/blob/master/other/0001-zstd-zless-and-zgrep-scripts.patch

---

Kirill Shcherbatov, DATI MIPT student

**Comment by Cyan4973** [comment]
That's a good point @kshcherbatov !
We'll see how we can add such functionality in a future release.

**Comment by Cyan4973** [comment]
regarding `zstdless` :
there is already `zstdcat` available.
Would a simple script performing `zstdcat $@ | less` do the trick ?
In that case, there is a test version available in `dev` branch

**Comment by Cyan4973** [comment]
Also added a `zstdgrep` tool, based on NetBSD version by Thomas Klausner

**Comment by Cyan4973** [comment]
Included in latest zstd release

**Comment by apjanke** [comment]
Quick question on the `zstdgrep` command: It [has support for being aliased as `zegrep` or `zfgrep`](https://github.com/facebook/zstd/blob/d76d1a9ef08e9baaec9beec40bd354b2b2e1e893/programs/zstdgrep#L36-L42).

```
# handle being called 'zegrep' or 'zfgrep'
case ${prg} in
    *zegrep)
	grep_args="-E";;
    *zfgrep)
	grep_args="-F";;
esac
```

Since this is using `zstdcat` instead of `zcat`, should these aliases be `zstdegrep` and `zstdfgrep` instead of, or in addition to, `zegrep` and `zfgrep`?

**Comment by Cyan4973** [comment]
Yes, you are completely right.
To be fair, I didn't paid attention to these aliases, as I didn't planned to introduce them.
So we could as well remove them, except if someone believe that they can be useful.
