### ISSUE TITLE
There is a memory leak defect at line 3466 in the file /zstd/lib/compress/zstd_compress.c.

### ISSUE THREAD

**Issue by LuMingYinDetect** [facebook/zstd#4112]
A pointer variable named dst is defined at line 3461 in the file /zstd/lib/compress/zstd_compress.c and a new dynamic memory area is allocated to it using the function ZSTD_customMalloc. If the RETURN_ERROR_IF macro condition at line 3466 is met, the function will return at this line, and the release operation of the dynamic memory area pointed to by dst at line 3484 will not be executed, resulting in a memory leak, as shown in the figure below:
https://github.com/LuMingYinDetect/zstd_defects/blob/main/zstd_1.png

**Comment by Adenilson** [comment]
Perhaps something like this could help:
https://gist.github.com/Adenilson/7d822b4223ca11753a1c632cd7dee9bc

**Comment by terrelln** [comment]
Fixed by https://github.com/facebook/zstd/pull/4115
