### ISSUE TITLE
Newer releases of the zstd-dev package for Alpine Linux do not have Cmake files, while older versions do. This causes build problems for Alpine projects depending on zstd.

### ISSUE THREAD

**Issue by johnny-pongetti** [facebook/zstd#4120]
**Describe the bug**
You can compare the included files in the releases here: 
https://pkgs.alpinelinux.org/contents?branch=v3.20&name=zstd-dev&arch=x86&repo=main
and here:
https://pkgs.alpinelinux.org/contents?branch=v3.17&name=zstd-dev&arch=x86&repo=main

3.17 has all of the cmake files while newer versions do not, and older releases are not provided so this causes pretty major problems.
Also, the Ubuntu release of libzstd-dev does include the cmake files. 

If this was intentional to only exclude Cmake files in newer Alpine zstd releases then I can't find any documentation for it.

**Comment by felixhandte** [comment]
This sounds like a packaging issue that you should take up with the folks at Alpine. We don't have any control over how our project is packaged by distributions other than what's in our upstream release tarball, which as best I recall has always included the cmake files.

**Comment by felixhandte** [comment]
Closing, but feel free to reopen if there are any actions Alpine would like us to take to help fix this.
