### ISSUE TITLE
Could you please share the policy or algorithm to generate the dictionary?

### ISSUE THREAD

**Issue by a406749043** [facebook/zstd#4121]
Understanding the way to generate compress dic by source code is quite difficult for me, so I wonder if it is possible to tell me the originnal algorithm about dic generating, I will be very grateful for that!

**Comment by Adenilson** [comment]
@OP: there is a comment on the top of the cover.c file with the following
 "
 * Constructs a dictionary using a heuristic based on the following paper:
 *
 * Liao, Petri, Moffat, Wirth
 * Effective Construction of Relative Lempel-Ziv Dictionaries
 * Published in WWW 2016.
"

Please check:
https://github.com/facebook/zstd/blob/dev/lib/dictBuilder/cover.c#L15

**Comment by a406749043** [comment]
> @op: there is a comment on the top of the cover.c file with the following "
> 
> * Constructs a dictionary using a heuristic based on the following paper:
> * Liao, Petri, Moffat, Wirth
> * Effective Construction of Relative Lempel-Ziv Dictionaries
> * Published in WWW 2016.
>   "
> 
> Please check: https://github.com/facebook/zstd/blob/dev/lib/dictBuilder/cover.c#L15

ty,I'll check this out later.
