### ISSUE TITLE
Dictionary format

### ISSUE THREAD

**Issue by rwultsch** [facebook/zstd#413]
Howdy,
We have done a bunch of work to build automation to create very good predefined compression dictionaries for lookback to be used by zlib. I would like to well test zstd. It appears that the dictionary training ads in more data than just lookback. Is this format documented somewhere?

**Comment by terrelln** [comment]
Yup, its documented in https://github.com/facebook/zstd/blob/dev/zstd_compression_format.md#dictionary-format.

**Comment by Cyan4973** [comment]
You may also consider the advanced prototype `ZDICT_addEntropyTablesFromBuffer()` from `zdict.h` (experimental section).

Its purpose is to create the header part of a Zstandard dictionary,
from any dictionary content.
To do that, it also needs a set of samples to properly calculate statistics.

For more details, see its definition at : 
https://github.com/facebook/zstd/blob/dev/lib/dictBuilder/zdict.h#L100

**Comment by Cyan4973** [comment]
Does it answer your question @rwultsch ?

**Comment by Cyan4973** [comment]
Closing, as it hopefully answered your question

**Comment by AvdN** [comment]
Either something changed on in the project layout, or there are two typos in @terrelln's answer: it's now documented [here](https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md#dictionary-format)
