### ISSUE TITLE
Allow using dictionaries in benchmark

### ISSUE THREAD

**Issue by corneliusroemer** [facebook/zstd#4139]
**Is your feature request related to a problem? Please describe.**
I would like to run the CLI benchmark a constant dictionary file

**Describe the solution you'd like**
Allow passing a dictionary in benchmark mode

Maybe this is already possible, but in that case it's not visible in the documentation.

**Comment by Cyan4973** [comment]
It's already possible,
just combine `-b FILE(s)` with `-D dictionary`.

```
zstd -b dirGithub/*                          
 3# 9114 files       :   7484607 ->   2493833 (x3.001),  203.9 MB/s,  474.8 MB/s

zstd -b dirGithub/* -D dictGithub
 3# 9114 files       :   7484607 ->    703316 (x10.64),  711.5 MB/s, 2119.2 MB/s
```
