### ISSUE TITLE
ZSTD_DICTSIZE_MIN is referenced in documentation but not defined

### ISSUE THREAD

**Issue by mvhooren** [facebook/zstd#4142]
The documentation of ZDICT_finalizeDictionary says:

` * `maxDictSize` must be >= max(dictContentSize, ZSTD_DICTSIZE_MIN).`
 
But ZSTD_DICTSIZE_MIN is not defined anywhere.
What is the actual minimum dictionary size?

**Comment by Cyan4973** [comment]
It's a typo: it's actually `ZDICT_DICTSIZE_MIN`, which is defined in the same file
