### ISSUE TITLE
The file is open but not closed

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [facebook/zstd#4148]
Hi all,
This is Qianxin CodeSafe Team, we found a suspicious question, at
https://github.com/facebook/zstd/blob/9215de52c7029bdad06d5fa59a4777edf0c92df9/contrib/pzstd/Pzstd.cpp#L127
the file is open but not closed

**Comment by Cyan4973** [comment]
reaching this line actually means that the file is ***not*** opened.
