### ISSUE TITLE
Cross-border access？

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [facebook/zstd#4149]
Hi all,
This is Qianxin CodeSafe Team, we found a suspicious issue, at

https://github.com/facebook/zstd/blob/9215de52c7029bdad06d5fa59a4777edf0c92df9/lib/compress/zstd_compress_internal.h#L720
where 'repCode' is initialized to 4294967295，and
https://github.com/facebook/zstd/blob/9215de52c7029bdad06d5fa59a4777edf0c92df9/lib/compress/zstd_compress_internal.h#L722
In the statement "rep[repCode]", the access to memory exceeded the upper limit of the memory block, causing an out-of-bounds access

**Comment by Cyan4973** [comment]
> where 'repCode' is initialized to 4294967295，and

For that outcome to happen, it would require `offbase == 0`.
This is not possible. `offbase` is always `>= 1`. 
This condition is even asserted _within_ the macro.
