### ISSUE TITLE
"make install" creates libraries

### ISSUE THREAD

**Issue by Patterner** [facebook/zstd#415]
```
make ; make -n install
```

```
clang ... -c common/fse_decompress.c ... legacy/zstd_v02.c
ar rcs libzstd.a *.o
clang ... -shared common/fse_decompress.c ... legacy/zstd_v02.c -fPIC -Wl,-soname=libzstd.so.1 -o libzstd.so.1.1.1
ln -sf libzstd.so.1.1.1 libzstd.so.1
ln -sf libzstd.so.1.1.1 libzstd.so
```

Those commands should've executed by the `make` phase, not `make install`
To install into `/usr/local` you need `root` access and this way you have `root`-owned files in the repo.

**Comment by Cyan4973** [comment]
Good point.
Currently, `make` only creates the `zstd` command line binary.
This could be changed so that `make` also creates library binaries.

**Comment by Cyan4973** [comment]
Implemented in latest `dev` branch update

**Comment by Patterner** [comment]
`lib/Makefile` has the following targets:

```
default: clean libzstd
all: clean libzstd
```

Should `clean` be there?

I expect that `make ; make` doesn't do anything during the 2nd invocation.

**Comment by Cyan4973** [comment]
There used to be a problem with mixing x86 and x64 binary generation. This issue can also be extended to specific test flags, such as `-fsanitize=address`,`g++` / `clang` generations, etc.

In short, calling a test, or some specific generation, will create binaries with appropriate compiler and test flags. 
Then, calling `make`, it would detect the presence of these recently built binaries, and consequently not generate them. It obviously results in linking errors afterwards

`clean` was a quick and simple solution to this problem.

**Comment by Cyan4973** [comment]
Latest update in `dev` now ensures that in the case of `make ; make` scenario, there is no compilation during the 2nd invocation.

We will have to test it a bit to ensure it doesn't introduce the side-effects previously observed, due to the numerous test targets we have to handle during validation.

**Comment by Cyan4973** [comment]
Seems to work fine so far, so we'll keep this setting.
