### ISSUE TITLE
ZDICT_trainFromBuffer_advanced notifications cause access violation

### ISSUE THREAD

**Issue by klaro115** [facebook/zstd#418]
Hi,
When trying to set a higher notification level using ZDICT_params_t and trainFromBuffer_advanced(), writing the notifications tends to throw an access violation exception when calling ZDICT_printHex() function.

The example below can reproduce this situation:

```
#define ZDICT_STATIC_LINKING_ONLY

#include "zstd.h"
#include "zdict.h"

#include <algorithm>
#include <stdio.h>

int main( int argc, char* argv[] )
{
    const size_t sourceDataSize     = 10000u;
    const size_t maxDictionarySize  = 100000u;
    const int compressionLevel      = 6;

    const size_t blockSize  = 65536u;
    const size_t blockCount = ( sourceDataSize + blockSize - 1u ) / blockSize;

    char* pSourceData       = ( char* )calloc( sourceDataSize, sizeof( char ) );
    char* pDictionary       = ( char* )calloc( maxDictionarySize, sizeof( char ) );
    size_t* pBlockSizes     = ( size_t* )calloc( blockCount * sizeof( size_t ), sizeof( size_t ) );

    for( size_t i = 0u; i < sourceDataSize; ++i )
    {
        pSourceData[ i ] = ( char )( i % 255 );
    }

    for( size_t i = 0u; i < blockCount; ++i )
    {
        pBlockSizes[ i ] = std::min( sourceDataSize - i * blockSize, blockSize );
    }

    ZDICT_params_t parameters;
    memset( &parameters, 0u, sizeof( parameters ) );

    parameters.compressionLevel     = compressionLevel;
    parameters.notificationLevel    = 3;

    const size_t dictionarySize = ZDICT_trainFromBuffer_advanced( pDictionary, maxDictionarySize, pSourceData, pBlockSizes, ( unsigned int )blockCount, parameters );
    if( ZDICT_isError( dictionarySize ) )
    {
        printf( "Error: '%s'\n", ZDICT_getErrorName( dictionarySize ) );
        return 2;
    }

    free( pBlockSizes );
    free( pDictionary );
    free( pSourceData );

    return 0;
}
```

**Comment by Cyan4973** [comment]
Thanks @klaro115 .
I tried to reproduce the issue by using your program, but failed so far.
The programs exits, but without segfault nor access violation.
Could you provide information on your configuration ?

**Comment by Cyan4973** [comment]
feedback ping

**Comment by cornfed** [comment]
Hi @Cyan4973,
I compiled the code with msvc-180031101 without optimizations and got the same access violation (x86 and x64):
ZDICT_printHex((const char*)samplesBuffer+pos, printedLength);
pos=3452816845

**Comment by Cyan4973** [comment]
`pos` is obviously way too large in this sample. So it leads to a segfault.

There is no reason why such an error would only show up on Visual.
It should behave the same on gcc/clang.

Yet, for some reason, I was unable to produce it ...

To be complete, I had to modify slightly the provided source code to get it compile in C mode using XCode. Maybe the modifications altered the program behavior ?
Here is the modified example : 

```
#define ZDICT_STATIC_LINKING_ONLY

#include "zstd.h"
#include "zdict.h"

#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#define MIN(a,b)   ( (a) < (b) ? (a) : (b) )

int main( int argc, char* argv[] )
{
    const size_t sourceDataSize     = 10000u;
    const size_t maxDictionarySize  = 100000u;
    const int compressionLevel      = 6;
    
    const size_t blockSize  = 65536u;
    const size_t blockCount = ( sourceDataSize + blockSize - 1u ) / blockSize;
    
    char* pSourceData       = ( char* )calloc( sourceDataSize, sizeof( char ) );
    char* pDictionary       = ( char* )calloc( maxDictionarySize, sizeof( char ) );
    size_t* pBlockSizes     = ( size_t* )calloc( blockCount * sizeof( size_t ), sizeof( size_t ) );
    
    for( size_t i = 0u; i < sourceDataSize; ++i )
    {
        pSourceData[ i ] = ( char )( i % 255 );
    }
    
    for( size_t i = 0u; i < blockCount; ++i )
    {
        pBlockSizes[ i ] = MIN( sourceDataSize - i * blockSize, blockSize );
    }
    
    ZDICT_params_t parameters;
    memset( &parameters, 0u, sizeof( parameters ) );
    
    parameters.compressionLevel     = compressionLevel;
    parameters.notificationLevel    = 3;
    
    const size_t dictionarySize = ZDICT_trainFromBuffer_advanced( pDictionary, maxDictionarySize, pSourceData, pBlockSizes, ( unsigned int )blockCount, parameters );
    if( ZDICT_isError( dictionarySize ) )
    {
        printf( "Error: '%s'\n", ZDICT_getErrorName( dictionarySize ) );
        return 2;
    }
    
    free( pBlockSizes );
    free( pDictionary );
    free( pSourceData );
    
    return 0;
}
```

Among the most visible changes, the modified version doesn't use `<algorithm>`. That's because it's pure C.

But I fail to see how it would impact the test result.
Behaviour should remain similar.

**Comment by cornfed** [comment]
Same. Content of the "dictList" in "ZDICT_trainFromBuffer_unsafe":

[0] {pos=6 length=0 savings=4294967295 }
[1] {pos=765 length=63 savings=2332 }
[2] {pos=828 length=63 savings=2280 }
[3] {pos=891 length=63 savings=2280 }
[4] {pos=954 length=63 savings=2280 }
[5] {pos=1017 length=63 savings=2275 }
[6] {pos=3452816845 length=3452816845 savings=3452816845 }

**Comment by Cyan4973** [comment]
Thanks for traces @cornfed !

`[0]`  is obviously wrong, `length=0`, and `savings` underflow below `0`.
`[6]` is likely the one triggering segfault issue.

My results are quite different :
```
 2 segments found, of total size 315 
list 2 best segments 
  1:315 bytes at pos      765, savings   11475 bytes |................................ !"#$%&'| 
  2:  0 bytes at pos        0, savings       0 bytes || 
```

though I'm using v1.1.1, which could explain it.

So, if I link to libzstd v1.0.0 instead : 

```
 6 segments found, of total size 315
list 6 best segments
  1: 63 bytes at pos      765, savings    2332 bytes |................................ !"#$%&'|
  2: 63 bytes at pos      828, savings    2280 bytes |?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdef|
  3: 63 bytes at pos      891, savings    2280 bytes |~.......................................|
  4: 63 bytes at pos      954, savings    2280 bytes |........................................|
  5: 63 bytes at pos     1017, savings    2275 bytes |................................... !"#$|
  6:  0 bytes at pos        0, savings       0 bytes ||
```

still no crash, and no strange entry.

So, what could be the difference ?

It looks like `[6]` in your test is filled with garbage values, i.e. not initialised.
Maybe that's the problem.
And that behavior could be compiler-dependent (and even compiler-option dependent).

**Comment by cornfed** [comment]
When I set the dictList buffer to zero I get your result. So maybe you should check all the other mallocs if they can deal with uninitialized data ;)

**Comment by Cyan4973** [comment]
Ah, that's it, could finally reproduce it.
I guess the pb is that `[6]` shouldn't be displayed, because it's not part of the valid segment list.
`[0]` shouldn't be displayed either. For some reason, it is displayed in your traces, but not in mine. Not sure why ...

**Comment by Cyan4973** [comment]
Hopefully fixed in latest `dev` branch update.

New result using above test program : 
```
 1 segments found, of total size 315
list 1 best segments
  1:315 bytes at pos      765, savings   11475 bytes |................................ !"#$%&'|
```
