### ISSUE TITLE
Submission of security bugs

### ISSUE THREAD

**Issue by the-st0rm** [facebook/zstd#420]
Hi guys, 
I think I have soke secuirty bugs which I would like to submit. I just would like to know if zstd is part of fb white hat secuirty or not and if I should submit the security bug through fb or not. 

Best
Ibrahim

**Comment by Cyan4973** [comment]
Yes, you are welcomed to do it through fb white hat security program.

**Comment by the-st0rm** [comment]
Wohooo 😁😁 I am glad it is part of fb white hat program. I will triage the
crashes and send u reports very soon.

Thanks for the quick reply.
