### ISSUE TITLE
Rust port now supports compression, should maybe be listed as a full port not just as decoder

### ISSUE THREAD

**Issue by KillingSpark** [facebook/zstd#4224]
**Describe the bug**
facebook.github.io/zstd/  lists the rust port as a decoder. This is outdated as of recently, there is now a published, working, encoder implementation. 

**To Reproduce**
1. Go to website
2. look at  table
3. See "Rust (decoder, Port)" listed for https://github.com/KillingSpark/zstd-rs

**Expected behavior**
1. Go to website
2. look at  table
3. See "Rust (Port)" listed for https://github.com/KillingSpark/zstd-rs

**Additional context**
I'm not sure what the exact criteria are to be listed as a full port. The current encoder implementation offers no real flexibility over the compression level yet. It is able to process any data thrown at it and output valid zstd frames, compressing enwik9 to ~48% of the original size.

**Comment by Cyan4973** [comment]
Rust port listing updated

**Comment by KillingSpark** [comment]
Thanks!
