### ISSUE TITLE
Found a slight improvement

### ISSUE THREAD

**Issue by beef9999** [facebook/zstd#440]
fileio.c:301
size_t const inSize = fread(ress.srcBuffer, (size_t)1, ress.srcBufferSize, srcFile);

Should it be 

size_t const inSize = fread(ress.srcBuffer, ress.srcBufferSize, (size_t)1, srcFile);

?

**Comment by terrelln** [comment]
The signature is:

    size_t fread( void* buffer, size_t size, size_t count, FILE* stream )

`size` is the size of each object, and `count` is the number of objects to read.  We are reading in raw bytes, so `size == 1`.

**Comment by beef9999** [comment]
Why not read all of them for once?

**Comment by Cyan4973** [comment]
There's technically no difference between the 2 versions.
All bytes are "loaded at one",

or rather, in successive blocks, depending on source IO, OS cache, runtime buffering, etc.
All sorts of things which are hidden through the standard lib.
At the end, we just get the total number of bytes required into our own userland buffer.
