### ISSUE TITLE
v1.1.1 for windows

### ISSUE THREAD

**Issue by jungle-boogie** [facebook/zstd#445]
Hi All,

I'm happy to see 1.1.1 was recently released:
https://github.com/facebook/zstd/releases/tag/v1.1.1

However, there's not a precompiled binary for Windows. Is this expected for this release and going forward you will have windows binaries?

thanks!

**Comment by Cyan4973** [comment]
We have problems building automatically Windows binaries for each release, due to complex right managements.
So the process is largely manual.

We'll try to improve this situation in the future.

**Comment by Cyan4973** [comment]
v1.1.1 Windows Binaries are now available in the "Release" section, thanks to @inikep
