### ISSUE TITLE
Streaming API and objects question

### ISSUE THREAD

**Issue by roussec** [facebook/zstd#446]
I am currently working with the streaming API to replace our current compression solution. We compress objects of different sizes. Writing all objects into one stream (just one ZSTD_endStream() at the end) gives very good results.  But we need to identify and be able to individually decompress objects so I added a ZSTD_endStream()/ZSTD_resetStream() after each object. This results in files 20%-30% larger than before which is not acceptable.

Is there a better way to identify objects and be able to individually decompress them then using ZSTD_endStream()/ZSTD_resetStream()?

Thank you.

**Comment by Cyan4973** [comment]
The most straightforward solution would be to create your own metadata format.
Essentially, each object would have its own parsable "header", telling what it is and its length.
The decoder will parse the stream after decompression to find back objects.

**Comment by roussec** [comment]
Yes this is how it works. The problem is not so much the format but why the compression is so much worse when I compress each object one by one instead of all objects at the same time.

**Comment by gyscos** [comment]
You could:
* Use a dictionary to improve compression performance for smallish individual objects
* As a compromise, compress objects "in batch": each individual stream contains a handful of objects - enough to get a correct compression ration, but few enough so that there's not to much to decode when you want to decompress an individual item.

**Comment by Cyan4973** [comment]
The goal of metadata header in front each object
is to be able to append them blindly,
and then compress them as a single frame.

Multiple frames will necessarily compress worse.
The only reason one would like to do so is to for "random access" ability.
But if you can access (decode) your objects sequentially, there is no reason to do so.

**Comment by roussec** [comment]
Thank you. I went for the second method gyscos suggested. This works fine. Thanks a lot.

**Comment by Zhibolive** [comment]
"公鸡年2017年农历新年快乐 - Happy New Year 2017, Year of the Rooster
https://goo.gl/0joVvd"
