### ISSUE TITLE
libzstd.so.1.1.2 are the same file

### ISSUE THREAD

**Issue by jungle-boogie** [facebook/zstd#447]
Hi All,

Running dragonflyBSD almost at the tip of master and I am compile zstd fine with gmake, but the problem is with make install:

```
zstd> sudo gmake install
gmake[1]: Entering directory '/home/user/bin/zstd/lib'
install: libzstd.so.1.1.2 and /usr/local/lib/libzstd.so.1.1.2 are the same file
gmake[1]: *** [Makefile:106: install] Error 64
gmake[1]: Leaving directory '/home/user/bin/zstd/lib'
gmake: *** [Makefile:68: install] Error 2
```

```
> gmake -v
GNU Make 4.2.1
```

```
> sha256 lib/libzstd.so.1.1.2
SHA256 (lib/libzstd.so.1.1.2) = 0d102a99cb74a8c838683c8db352cd31dbe586ef435d6b1582739bae41fa3f7b
                                                                                                                                                                                               > sha256 /usr/local/lib/libzstd.so.1.1.2
SHA256 (/usr/local/lib/libzstd.so.1.1.2) = 0d102a99cb74a8c838683c8db352cd31dbe586ef435d6b1582739bae41fa3f7b
```

is it related to this commit?
https://github.com/facebook/zstd/commit/e19111c42f19f4d98b230faad79bd7763f5e1e49

see also:
https://github.com/facebook/zstd/issues/415

**Comment by Cyan4973** [comment]
I'm afraid it seems to be a system-specific issue.

First, it looks like `usr/local/lib/libzstd.so.1.1.2` already exists, which means it was previously installed.
That must be recently, since 1.1.2 is not even a release, and this number was only added [very recently](https://github.com/facebook/zstd/commit/fd3be6bc97e33d0db6cbe93984ac71dd3de3327c) in `dev` branch.

Nevertheless, I see no issue doing `sudo make install` on any test system I can reach, even when `libzstd` is already installed. So there must be some specific protection to the version of `install` shipped with dragonflyBSD, which forbids this operation.

If that's all there is, a quick work-around could be to uninstall zstd before installing again.

**Comment by jungle-boogie** [comment]
> I'm afraid it seems to be a system-specific issue.

I think this might be a regression, though.

Yes, 1.1.2 is your master because I'm building from master. 

I'll rollback and see if it still happens.

**Comment by Cyan4973** [comment]
master is still 1.1.1 : https://github.com/facebook/zstd/blob/master/lib/zstd.h#L56

**Comment by jungle-boogie** [comment]
What's https://github.com/facebook/zstd ? That's what I'm cloning.

**Comment by Cyan4973** [comment]
Not sure exactly how you clone, but this repository is supposed to contain 3 branches : `dev`, `master` and `gh-pages`.
You could `git status` to know on which branch you are.

**Comment by gyscos** [comment]
The error message reported by `install` doesn't indicate that the files have the same content, but that the two paths refer to the same file.
Did you use symbolic link between `/home/user/bin/zstd/lib` and `/usr/local/lib`?

**Comment by jungle-boogie** [comment]
```
> git status
On branch dev
Your branch is up-to-date with 'origin/dev'.
nothing to commit, working tree clean
```

There was a link, but I didn't manually create it.

I see this after the failed gmake install:

```
lrwxr-xr-x  1 sean  sean         25 03-Nov-2016 12:23 libzstd.so.1 -> libzstd.so.1.1.1.so.1.1.1
lrwxr-xr-x  1 sean  sean         25 03-Nov-2016 12:23 libzstd.so -> libzstd.so.1.1.1.so.1.1.1
-rw-r--r--  1 root  wheel    669530 03-Nov-2016 12:24 libzstd.a
drwxr-xr-x  1 root  wheel         0 07-Nov-2016 12:19 gawk
-rwxr-xr-x  1 root  wheel    538552 08-Nov-2016 15:36 libzstd.so.1.1.2 
```

**Comment by jungle-boogie** [comment]
this symlink exists in `zstd/lib`
```
lrwxr-xr-x  1 root  user      16 08-Nov-2016 15:39 libzstd.so -> libzstd.so.1.1.2
lrwxr-xr-x  1 root  user      16 08-Nov-2016 15:39 libzstd.so.1 -> libzstd.so.1.1.2
```

**Comment by gyscos** [comment]
Can you post the result from:

```bash
file /home
file /home/user
file /home/user/bin
file /home/user/bin/zstd
file /home/user/bin/lib
file /usr
file /usr/local
file /usr/local/lib
```

**Comment by jungle-boogie** [comment]
Here you are:
```
/home/: directory
/home/user/: directory
/home/user/bin: directory
/home/user/bin/zstd/: directory
/home/user/bin/zstd/lib/: directory
/usr/: directory
/usr/local/: directory
/usr/local/lib: directory
```

**Comment by gyscos** [comment]
If you do manually

```
cd /home/user/bin/zstd/lib
sudo install -m 755 libzstd.so.1.1.2 /usr/local/lib/libzstd.so.1.1.2
```
Do you also get an error?

**Comment by jungle-boogie** [comment]
No error.

```
> sudo install -m 755 libzstd.so.1.1.2 /usr/local/bin/libzstd.so.1.1.2                                                                                                                                                                                        user@fly:~/bin/zstd/lib> 
```

**Comment by gyscos** [comment]
Well I would assume the `gmake install` works as well now. Looks like something you did fixed the problem?

**Comment by jungle-boogie** [comment]
Hi @gyscos,

No, `sudo gmake install` still generates the same error. I will install with install -m as that works.

Thanks,
sean

**Comment by Cyan4973** [comment]
I installed a fresh copy of DragonFlyBSD 4.6.1,
and proceeded with compiling and installing `zstd` (`dev` branch) with `gmake` v4.2.1

`gmake  && sudo gmake install` worked fine.
So did `gmake clean && sudo gmake install`.

I also tried to generate some race conditions, playing with different values of `-jX`, but without triggering any error so far.

Can't tell what happened on your system...

**Comment by jungle-boogie** [comment]
Hi @Cyan4973,

Thanks for the efforts you put into tracking this down. 

I'll post this to the dragonfly mailing list to see if anyone else running master experiences the same issue.
