### ISSUE TITLE
03982b5d breaks building on Linux Mint 17.3

### ISSUE THREAD

**Issue by ole-tange** [facebook/zstd#448]
589f0117 builds fine, but the next commit (03982b5d) introduces -lgtest, for which I have not been able to find a package for in Linux Mint 17.3:

g++ main.o Options.o Pzstd.o SkippableFrame.o ../../lib/libzstd.a             -L googletest/build/googlemock/gtest -lpthread -o pzstd
g++ test/OptionsTest.o ../../programs/datagen.o Options.o Pzstd.o SkippableFrame.o ../../lib/libzstd.a          -Wno-deprecated-declarations   -L googletest/build/googlemock/gtest -lgtest -lgtest_main -lpthread -o test/OptionsTest
/usr/bin/ld: cannot find -lgtest
/usr/bin/ld: cannot find -lgtest_main
collect2: error: ld returned 1 exit status
make: *** [test/OptionsTest] Error 1
make: *** Waiting for unfinished jobs....

To build 589f0117 I needed these packages:
binutils binutils-multiarch coreutils cpp-4.8 dash g++ g++-4.8 gcc gcc-4.8 gcc-multilib grep hardening-wrapper lib32gcc-4.8-dev libacl1 libattr1 libc6 libc6-dev libc6-dev-i386 libc6-i386 libcloog-isl4 libgcc-4.8-dev libgmp10 libisl10 libmpc3 libmpfr4 libpcre3 libselinux1 libstdc++-4.8-dev libtinfo5 linux-libc-dev locales make pentium-builder sed zlib1g

I assume that gtest is only used for testing and not for the actual program. Consider making that optional to build by removing it from the build target 'all', so systems without libgtest can build (but not test) the package.

**Comment by terrelln** [comment]
Sorry for the regression.  I will remove the dependency, but in the meantime, running `make pzstd` should only build `pzstd` and not the tests.

**Comment by ole-tange** [comment]
I can confirm that `make pzstd` works.

This also works:

diff --git a/contrib/pzstd/Makefile b/contrib/pzstd/Makefile
index 2de5041..dff3601 100644
--- a/contrib/pzstd/Makefile
+++ b/contrib/pzstd/Makefile
@@ -109,7 +109,7 @@ uninstall:
 # Targets for many different builds
 .PHONY: all
 all: PZSTD_CPPFLAGS += -DNDEBUG
-all: pzstd$(EXT) tests roundtrip
+all: pzstd$(EXT) 
 
 .PHONY: debug
 debug: EXTRA_FLAGS += -g
