### ISSUE TITLE
HowTo: Dictionary on the fly?

### ISSUE THREAD

**Issue by kshcherbatov** [facebook/zstd#449]
Hi! I need to make a compression of several small typical files. How can I use an information collected during compression? Streaming compression seems to be ok for this: (StreamCreate ([StreamInit;Write;StreamEnd]...[StreamInit;Write;StreamEnd]) StreamFree), but I am not sure that it is works this way.
As I have understood, dictionary should be built in advance, so it does not fit to me.

**Comment by Cyan4973** [comment]
If streaming works for your use case, then streaming should be preferred.

Dictionary compression should be considered for use cases for which streaming is not applicable.

**Comment by kshcherbatov** [comment]
Thank you.
