### ISSUE TITLE
Library Installation

### ISSUE THREAD

**Issue by kklouzal** [facebook/zstd#457]
I'm coming from LZ4 and used to just drop lz4.c and lz4.h into my project directory and away I went. Uploading my project to GitHub was simple and appveyor had no troubles compiling my project and subsequently uploading to coverity.

Can things be that simple with ZStd? The projects file base is much larger compared to LZ4. Can I still drag and drop what I need into my project directory easily so future ZStd updates can be merged just as quickly?

My main concern is getting things to publish properly to appveyor and making it easy for users of my library to just pull from GitHub and embed into their project, no need to compile a 3rd party library.

How can this be done?

**Comment by Cyan4973** [comment]
Zstandard is indeed larger, featuring multiple source files, so it's more complex than lz4.

That being said, the following proposition works : 

> Can I still drag and drop what I need into my project directory easily so future ZStd updates can be merged just as quickly?

Yes. As long as you drag and drop (or copy) the correct files into your own directory structure, it will work.
To know which files you need, follow instructions in [`lib/README.md`](https://github.com/facebook/zstd/blob/dev/lib/README.md).
