### ISSUE TITLE
Switching endianess for faster decompression

### ISSUE THREAD

**Issue by GSt4r** [facebook/zstd#462]
Hello!
Is it somehow possible to "force" zstd to use a specific endianess?
I have a special use case where I'm compressing data on a host system. This data is then transferred to a target system and decompressed there. The compression time on the host is not important. However the decompression should be as fast as possible. The host system is Little-endian while the target system is Big-endian. When doing the decompression some bytes need to be swapped, due to the fact that it is Big-endian (in functions like `MEM_readLE16()`). What I would like to achieve is having the "overhead" of byte-swapping on the host and not on the target. 
I tried to compress in Big-endian format on the host (by returning a constant 0 in `MEM_isLittleEndian()`) and decompress in Little-endian format on the target (by returning a constant 1 in  `MEM_isLittleEndian()`). But unfortunately I'm getting an error saying `corrupted block detected`.
Is there a way to solve this?
Thanks!

**Comment by Cyan4973** [comment]
This looks difficult @GSt4r .
The entire algorithm has been created to be endian independent, which basically means it enforces one convention (little endian) everywhere it matters.
Changing this convention would be a very invasive change.

Besides, bitstream is really built for little endian, changing convention there would impact more than a shuffle.

Finally, in most "modern" big-endian CPU, you should be able to expect a fairly efficient `swap` operation. Even older systems such as Motorola 68030 were able to achieve this.

One can test such difference by using [xxHash](https://github.com/Cyan4973/xxHash), which has a [mode to force native endianness](https://github.com/Cyan4973/xxHash/blob/dev/xxhash.c#L68). It should give a good hint on the performance impact of `swap` (keeping in mind that xxHash is a pretty extreme case, where `swap` is going to have a high % usage).
