### ISSUE TITLE
Autotool/CMake build system

### ISSUE THREAD

**Issue by SoapGentoo** [facebook/zstd#485]
Dear maintainers,
the current Makefile-based build system violates a number of requirements for downstream distributions and requires hacking on our part. Would you consider a PR where we Autotool/CMake the build system, such that general handling becomes easier and more idiomatic that the current situation? All downstream users would thank you!

**Comment by inikep** [comment]
Can you describe what is the problem? Makefile works fine with Linuxes and MSYS. Today I compiled zstd on FreeBSD 11.0 with gmake without a single warning.

**Comment by Cyan4973** [comment]
Thanks for suggestion @SoapGentoo .

We are not aware of issues with downstream distributions, and would therefore welcome to know more about it. We indeed want to ease situation if there is any problem remaining.

Having no experience with autotool, I would therefore be worried by its maintenance.

We have a `cmake` build script, in `build` directory. If you feel this script can be improved to better fit downstream requirements, you are welcomed to propose a patch for it.

For the `Makefile` at root directory, I would prefer to keep it manual for now, though we can certainly evolve it to take into consideration more requirements.

**Comment by qunying** [comment]
I personally prefer a manual Makefile, it is more more easier to maintain for the current OS landscape. Although I dislike autotool either, I prefer it over cmake, as it makes a hard dependency on cmake to be present on the system. I encounter problem when trying to compile one package with CMake,  it refuse to run due to my system 's cmake version a littler older then it required.

**Comment by Cyan4973** [comment]
bump @SoapGentoo .
We need more feedback before proceeding on any plan.

**Comment by SoapGentoo** [comment]
@Cyan4973 have a look at our current build instructions: https://github.com/gentoo/gentoo/blob/master/app-arch/zstd/zstd-1.1.0.ebuild
Including our patch to the build system: https://github.com/gentoo/gentoo/blob/master/app-arch/zstd/files/zstd-1.1.0-fix_build_system.patch

For instance, static libraries are built either way. The correct way to do this is to tell the build system to either build shared or static libraries. Both Autotools and CMake have options for this, and these options are standardised. Please think of the downstream users! Providing an autotooled or CMake'd package is much easier for us, as all the mechanisms for handling these are in place already. Every hand-written Makefile is a pain for us, as hand-written Makefiles inadvertently always miss something that makes our workflow easier.

**Comment by Cyan4973** [comment]
> For instance, static libraries are built either way. The correct way to do this is to tell the build system to either build shared or static libraries.

This possibility exists :
in `lib` directory, `make libzstd` only builds dynamic library,
and `make libzstd.a` only builds static library.

We can probably support even more options, but try to be specific about what you ask for.
We can't guess all the requirements of each distribution, and we have a lot of downstream distributions and systems to support. Don't assume the process you are following is universal.
