### ISSUE TITLE
Bench marking recommendation

### ISSUE THREAD

**Issue by sudouser2010** [facebook/zstd#495]
I'm comparing Zstandard to Snappy (https://github.com/google/snappy). In order to create an apples-to-apples comparison, do you have any suggestions as far as setting up the environment inside of docker containers ?

So far, Snappy appears to decompress faster.

**Comment by Cyan4973** [comment]
Hi @sudouser2010 

We tend to recommend benchmark comparison with [lzbench](https://github.com/inikep/lzbench). It includes both snappy and zstd.

According to our measurements, snappy does decompress faster than Zstandard.
Snappy belongs to the "lightweight compression" category, which other members include QuickLZ, LZO and LZ4, and many more. They are fast, but pay this speed by delivering less compression ratios.

`zstd -1` is the closest setting you'll get from these compressors. Its speed is good, but lightweight alternatives are supposed to be even faster. The difference is that `zstd -1` is supposed to deliver better compression ratio.
