### ISSUE TITLE
Issues for Android about replacing zlib using zstd

### ISSUE THREAD

**Issue by 296777513** [facebook/zstd#501]
Hi
    I am attempting to port zstd to Android libziparchive module, by using zlibWrapper to replace zlib .
   As scenes in Androd concerns more about decompress speed, so I test decompressing  zip files(like bmp.zip(bmp file compressed by zstd/zlib firstly) and apk) using zlib/zstd.
   The data below shows gaining little benefit comparing zlib, do you have any advise for my occuration?
thanks

![image](https://cloud.githubusercontent.com/assets/8221740/21477843/bbe93d02-cb80-11e6-9522-6157e69cb4b2.png)

test steps:
1: firstly, compress bmp/txt files into test_zstd.zip using zstd, test_zlib.zip using zlib;
2: secondly, decompress zip files above into memory or file system;
3: calculating time consuming for step 2.

**Comment by dongjinguang-china** [comment]
Hi Cyan4973，

    Please help to analysis and give some suggestion  for the decompress benfit issue.

**Comment by terrelln** [comment]
It seems the decompressor is running at about 100 MB/s in your tests.

`zstd` so far is primarily optimized for x86, so it is expected to be slower on ARM, but that is too slow, so I ran some tests.  I ran the following program on my iPhone 6s and looked at the logging output.

```
#import "bench.h"

/* ... */

- (void)viewDidLoad {
    ZSTD_compressionParameters params;
    memset(&params, 0, sizeof(params));
    BMK_SetNbSeconds(5);
    BMK_setNotificationLevel(1);
    BMK_setDecodeOnly(0);
    BMK_benchFiles(NULL, 0, NULL, 1, 10, &params);
}
/* ... */
```

When running on an unoptimized build it decompressed at about 100 MB/s.  When running a build optimized with `-Os` it decompressed at about 800 MB/s.  For reference, [Apple's](https://developer.apple.com/reference/compression/1665429-data_compression?language=objc) zlib compression decompresses at about 270 MB/s.  I know it isn't Android, but I would expect similar relative results on the same architecture.

Is your binary compiled with optimizations?

**Comment by dongjinguang-china** [comment]
Hi Terrelln,
   Thanks for your propose and We will try it.

**Comment by powof2** [comment]
May be it is something about your android system? 64-bits is way faster.
here is another test : [https://github.com/facebook/zstd/issues/190](url)

**Comment by Cyan4973** [comment]
Both advises by @terrelln and @powof2 are relevant : 
- Check compiler optimisation settings
- Check if your test system is 32 or 64 bits. It makes a substantial difference.

**Comment by 296777513** [comment]
Hi Cyan4973 and terrelln,
Thanks for your reply,  we run a build optimized with -O2 default, and test in 64-bits case.
I see that the file tested may influence the decompress speed, use fullbench and turbobench, 800+M/s when decompressing default 10M sample, while only 450+M/s when decompressing bmp file.  Both tested in my linux server.
![image](https://cloud.githubusercontent.com/assets/8221740/21535037/af7a3176-cdaa-11e6-848d-917178c9aab4.png)
![image](https://cloud.githubusercontent.com/assets/8221740/21535038/b5a6a214-cdaa-11e6-8d10-5657b52445a3.png)

Also,  for the same test file(10M sample), linux server runs decompressing in 800+M, while my Android 7.0 mobile phone only runs in 450+M(data shows below).
![image](https://cloud.githubusercontent.com/assets/8221740/21535139/c800c0ce-cdab-11e6-860b-51243d80f5d5.png)

So, I think both the test files and my Android platform  cause the decomressing speed too slow.

Thanks
