### ISSUE TITLE
About the usage of memory  when compressing files with different size.

### ISSUE THREAD

**Issue by dracular1983** [facebook/zstd#508]
Hi Cyan，
 I test the zstd in our android product,and i am concerned with the usage of the memory(to be mallocd in HEAP).In our testing case,the usage of the memory is only related to the compress-level,and is not related to the size of the files. I want to make sure if my understanding is correct. 
![image](https://cloud.githubusercontent.com/assets/19596242/21757139/3e3424c2-d665-11e6-866c-9903c5a82574.png)

**Comment by terrelln** [comment]
The memory allocated by zstd for compression depends only on the compression level.

If you are using the `ZSTD_compress()` API, or related functions, the memory usage will only be the `ZSTD_CCtx`, which can be estimated with `ZSTD_estimateCCtxSize()`.  If you are using the streaming API, it will additionally allocate input and output buffers, which depend only on the window size.

If you are using the `ZSTD_decompress()` API, or related functions, the memory usage is constant and is calculated with `ZSTD_estimateDCtxSize()`.  If you are using the streaming API, it will additionally allocate input and output buffers which depend only on the window size.

**Comment by dracular1983** [comment]
@terrelln thank you very much
