### ISSUE TITLE
Has any plan to complete more functions for zlibWrapper?

### ISSUE THREAD

**Issue by 296777513** [facebook/zstd#512]
Hi Cyan4973 ,

Thanks for you project,  and do you have any plan to complete more functions for zlibWrapper?
get_crc_table is not supported right now, and there is problem to use zstd to replace zlib.

Thanks again.

**Comment by inikep** [comment]
1. You can still access `get_crc_table` as `z_get_crc_table`.
2. I assume that you're using zlib to create a gzip/zip/deflate stream. What is your use case for `get_crc_table`? Is it an ordinary CRC or header CRC? If you can provide a simple example we can try to translate it to zstd and update zlibWrapper.

**Comment by 296777513** [comment]
Hi inikep,
   Thanks for your reply, I am just trying to compile zip/unzip source code using zlibWrapper and zstd, and test the resule. It seems that zip is ok, while unzip not.
   I copy the following codes to zstd_zlibWrapper.c, it seems function ok now.

ZEXTERN const z_crc_t FAR * ZEXPORT z_get_crc_table OF((void))
{
    return get_crc_table();
}

Thanks again.

**Comment by inikep** [comment]
We have added get_crc_table, adler32_z, crc32_z to zlibWrapper in _dev branch_ at https://github.com/facebook/zstd/commits/dev

I successfully compiled zlib/contrib/minizip but I found a bug when switched to zstd compression. It should be fixed today.
