### ISSUE TITLE
Training a dictionary in streaming fashion

### ISSUE THREAD

**Issue by toddlipcon** [facebook/zstd#513]
Hi folks,

Apologies for using an "issue" to ask a question -- I couldn't find a mailing list.

I'm interested in using zstd as a compression codec for compression the WAL of a database system. Entries are appended to the WAL sequentially, and the entries could vary from very small (a few hundred bytes) to relatively large (multi-MB). I also need to support random access to the WAL entries (achieved by the use of a side file, currently).

In order to get a good compression ratio on the small entries, I'm interested in using the dictionary training mode. I was thinking that I could train the dictionary in a "streaming" fashion -- i.e as each entry is appended, I'll compress it with the most recent dictionary while incrementally training a new one. After a sufficient amount of data, I would append the "trained" dictionary and start training the next one in sequence.

It seems like the provided APIs require that all of the dictionary samples be provided uncompressed up front, rather than in a streaming fashion. Is this a fundamental limitation or is there a way in which I could achieve single-pass training? Even if it's not as good as a "provide all the samples at once" method, I'm guessing that it could be a bit better than using no dictionary at all.

Thanks!

**Comment by Cyan4973** [comment]
Indeed,
the current dictionary builder requires all data to be analyzed "upfront".
It's not able to "append" some new data later on.

The workaround would be to implement an intermediate "storage" where relevant samples are collected, and then push that to the dictionary builder when it's ready to create a new dictionary.

Note that the memory cost for analyzing data is pretty steep (about x11 the size of samples),
so it would not make sense to keep the analyzing structure around while collecting samples.
Better do it once at the end.

**Comment by toddlipcon** [comment]
Hm, it sounds like the available dictionary training methods are too heavy-weight for this "online" use case, where the CPU and memory cost on the write side is relatively important. I haven't delved into the structure of what a dictionary exactly contains, but is it possible to build an online algorithm that, despite being significantly less effective than the currently-provided ones, would have O(n) runtime and O(1) memory usage? (and of course must be better than using no dictionary at all!)

**Comment by terrelln** [comment]
Another approach might be to group entries into the WAL in blocks of X MB, and compress each block together. This would help the compression ratio of smaller entries, while still preserving random access.

I'll speak about the new `cover` dictionary algorithm. There isn't a fundamental limitation in the `cover` dictionary algorithm that would prevent streaming. However, it would require nontrivial changes to the implementation.

The only part of the implementation that requires access to the whole corpus is when it is computing the frequencies of each segment of length `d`. This step could be replaced with a streaming approximation, which would trade use less memory, support streaming, and likely be faster, in exchange for accuracy. I'm unsure how much the loss in accuracy would reduce the compression ratio.

Its not immediately planned to support streaming dictionary creation. If there is enough demand, and a compelling enough use case, I can add it in the medium term. In the meantime, a patch that adds support would be extremely welcome.

**Comment by Cyan4973** [comment]
context note : `cover` is a new dictionary-builder algorithm implemented by @terrelln, currently only available in `dev` branch.

**Comment by toddlipcon** [comment]
> Another approach might be to group entries into the WAL in blocks of X MB, and compress each block together. This would help the compression ratio of smaller entries, while still preserving random access.

Right, we already do that a certain amount using group-commit. But, we can't arbitrarily delay writers either, so if someone does a single write with 1KB data, we need to get it written to storage in such a way that it is still random-readable later.

I'll take a look at the cover algorithm.

**Comment by Cyan4973** [comment]
`cover` new dictionary builder by @terrelln is now available within [latest release v1.1.3](https://github.com/facebook/zstd/releases/tag/v1.1.3)

**Comment by Cyan4973** [comment]
While we don't provide a "streaming" more per say for dictionary training,
the new dictionary builder `fast-cover` has been designed with inline scenarios in mind,
meaning, it's able to generate new dictionaries very fast, even in a fraction of a second (configurable).

We believe this covers the need for fast dictionary generation.
