### ISSUE TITLE
Any java libs / usage examples

### ISSUE THREAD

**Issue by sumit784** [facebook/zstd#568]
Hi, 

I am trying to test this compression within a java project. Are there any jars and java exmpales available for compression and de-compression.

**Comment by tobijdc** [comment]
Thank you for your interrest in zstd.
As stated in the readme, you can find implemtnations and binding for other languages on zstd's homepage.
[http://facebook.github.io/zstd/#other-languages](http://facebook.github.io/zstd/#other-languages)
There you will find Luben's zstd-jni binding.
