### ISSUE TITLE
Warning if XXH_STATIC_LINKING_ONLY is defined for the preprocessor

### ISSUE THREAD

**Issue by Ono-Sendai** [facebook/zstd#570]
I want to use xxhash in static mode, so I define XXH_STATIC_LINKING_ONLY as a preprocessor definition.

But then I get this warning:

zstd-1.0.0\lib\compress\zstd_compress.c(33): warning C4005: 'XXH_STATIC_LINKING_ONLY': macro redefinition 

I would suggest that zstd_compress.c etc.. check if the symbol is already defined, and not redefine it if so.
Thanks!

**Comment by Cyan4973** [comment]
Could you please describe for which objective you define `XXH_STATIC_LINKING_ONLY` while compiling `zstd` ?

**Comment by Ono-Sendai** [comment]
Hi,
Because I want to be able to declare XXH64_state_t variables on the stack when using xxhash directly.

**Comment by Cyan4973** [comment]
Yes, that's a useful modifier when using `xxhash` directly.

That being said, the version of `xxhash` inside `zstd` wasn't planned to be used directly.
It's supposed to remain "internal stuff".
These symbols are supposed to remain "hidden" from users of `libzstd` library (https://github.com/facebook/zstd/blob/dev/lib/Makefile#L71).
`xxhash` symbols are also renamed within `zstd` to avoid symbol duplication should someone use another copy of `xxhash` in the same program.

So I suspect you include "xxhash.h" independently in your `*.c` client file, but you then define `XXH_STATIC_LINKING_ONLY` globally, from project setting ?

In which case, it wasn't designed to be used this way :
`#define XXH_STATIC_LINKING_ONLY` should be present just before the `#include`, to remain a local definition, avoid spilling effects on other files of the project.

Perhaps I could add a note about intended usage of this setting...

**Comment by Ono-Sendai** [comment]
Well let me describe the general situation.
We want to use zstd, as well as xxhash directly for hashing stuff.  We also want to declare XXH64_state_t variables on the stack for performance.
So i'm happy to do whatever to achieve this in an efficient way without warnings :)

**Comment by Ono-Sendai** [comment]
Also yes, I define XXH_STATIC_LINKING_ONLY globally as a preprocessor def.  I'd rather not have to put it before every occurance #include <xxhash.h>.

**Comment by Cyan4973** [comment]
> I'd rather not have to put it before every occurrence of #include <xxhash.h>

Does it happen _that_ often ?

Problem is, it was designed to be used exactly this way.
Alternative could be to create your own `xxhash_static.h` with just 2 lines, the `#define` and the `#include`.

**Comment by Ono-Sendai** [comment]
26 occurances of #include <xxhash.h> :)
I can try the approach of xxhash_static.h I guess.

**Comment by Ono-Sendai** [comment]
Well, the xxhash_static.h approach works fine, although I do consider it a bit stylistically awkward.  I'll close the bug.  Thanks for your help and the great library!
