### ISSUE TITLE
Compression on Windows help

### ISSUE THREAD

**Issue by jungle-boogie** [facebook/zstd#581]
Hi All,

I have an unfortunate need to use Windows and rely on non-Unix tools. This means I can't tar things up and pass to zstd for compression.

When attempting to compress a directory that was compressed with Windows built in Zip "compression", I get an error of, "directory.zip is not a regular file -- ignored".
When trying with just the directory, I get the same message.

zstd v1.1.3 Windows 32 bit.

**Comment by Cyan4973** [comment]
Could you try `-r` command on the target directory ?
Note though that the result will be one `*.zst` compressed file per original file in the target directory, which is not the same as a single archive like `*.tar.zst`.

`tar` on Windows exist.
For example : http://gnuwin32.sourceforge.net/packages/gtar.htm
(I have not tested directly, but feels legit)
 
Another solution could be to use @mcmilk 's [7zip-with-zstd-support](https://github.com/mcmilk/7-Zip-zstd), which is a great GUI for such task, and I believe it has been upgraded to support `*.tar.zst` scenario. It also has a command line tool, but I'm not sure if provides the same functionality level.

**Comment by jungle-boogie** [comment]
> Could you try -r command on the target directory ?

yes, this functions as you mentioned, but that means all the files are basically duplicated within the directories.  Is there support to compress and move the files to a new directory within zstd?

I'm happy to know tar exists for the windows platform, but that means another dependency to ship. :( I was trying to get away with zstd for all compression stuff. What's going to be compressed is just text files. We use 7zip now and it's a little too slow when we start to accumulate many files.

I've used the gui tool for zstd that you linked to. I'll check out the cli and see if it can operate as easily as zstd on the UNIX side.


Any other thoughts are welcome!

**Comment by Cyan4973** [comment]
Any progresses on this topic ?

**Comment by jungle-boogie** [comment]
No, not from me. I'll close this.
