### ISSUE TITLE
No such file or directory (Cygwin, --rm)

### ISSUE THREAD

**Issue by dorfsmay** [facebook/zstd#587]
When using the **windows version** of zstd in Cygwin, and trying to use `--rm` for a file in a different directory, I get the error message "`zstd: /tmp/filename.zst: No such file or directory`". The issue does not manifest itself on Linux.

```bash
$ cd
$ zstd --version
*** zstd command line interface 64-bits v1.1.3, by Yann Collet ***
$ cp /etc/services /tmp/.
$ zstd --rm -9 /tmp/services
zstd: /tmp/services.zst: No such file or directory
$
```

**Comment by Cyan4973** [comment]
could it be that the Windows version does not understand path in the form of `/tmp/filename` ?

**Comment by dorfsmay** [comment]
You're right. I assumed it was the delete part that was the issue, but even `zstd /tmp/services` gives me "no such file or directory. I checked with other apps such as Libreoffice and it is the same issue. Looks like a limitation of Windows/Cygwin.

I think we can close this one.
