### ISSUE TITLE
Could use updated benchmarks; identify OS

### ISSUE THREAD

**Issue by JoeArizona** [facebook/zstd#589]
A few notes on the benchmarks:

### They're out of date

- The benchmarks here on the main GitHub page have been stuck on Zstd 0.8.2 and brotli 0.4 for a while.

- The benchmarks on the separate Zstd website use Zstd 1.0.0, and still brotli 0.4. (The website I'm referring to is listed as zstd.net, but redirects to http://facebook.github.io/zstd/ – github.io is not the GitHub you are on right now, but is their custom web hosting.)

Given all the releases since those benchmarks, it would be helpful to have updated results for Zstd ≥ 1.1.4 and brotli ≥ 0.5.2.

### Different compilers

Note also that the benchmarks here on GitHub use two different compilers: gcc **5.4** for the table, and gcc **5.2.1** for the graphs. Unless there's a compelling reason, there's no point in introducing a confound like two different compilers.

### No operating system

There's no mention of an OS in any of the benchmarks, not even broad families like Linux vs. Windows.

### Summary

Ideally, what we want is: updated builds, same and updated compiler, identify the OS, report the amount of memory (and type) the system has and whether it's SSD or spinner (unless the benchmarks are in-memory only).

I've got some useful machines for benchmarking, but lzbench only works with gcc (on Windows). I think @inikep and others would be better for gcc benchmarks. I could do Visual Studio 2017 or 2015 benchmarks.

**Comment by Cyan4973** [comment]
We can certainly update the benchmark, and provide more precise build info.
We recently changed our reference config, so we will need to run all tests again for comparison.

**Comment by Cyan4973** [comment]
first step : updated table benchmark in `README.md`

**Comment by jimhester** [comment]
While we are talking about benchmarks could you reconsider the 3d bar charts. They are easily misinterpreted and have long been cautioned against in the statistical community, e.g. [Haemer (1951)](https://github.com/facebook/zstd/files/955967/haemer1951.pdf).

I am happy to assist in generating more informative and scriptable plots if you are interested.

**Comment by Cyan4973** [comment]
That's a good point @jimhester .
Charts will be updated to remove 3D effect.

**Comment by Cyan4973** [comment]
All charts updated, to display 2D bar graphs instead of 3D ones

**Comment by JoeArizona** [comment]
@Cyan4973, thanks for being so responsive on this. You guys nailed it – the updated benchmarks are excellent!

**Comment by jimhester** [comment]
Thanks, new charts are much easier to interpret!
