### ISSUE TITLE
pure javascript implementation

### ISSUE THREAD

**Issue by cordovapolymer** [facebook/zstd#606]
Any chance that a pure JS implementation will be developed?
There's a https://github.com/kig/zstd-emscripten port, but it looks like unmaintained.

**Comment by Cyan4973** [comment]
Indeed, this version appears unmaintained.
We are welcoming any new JS port or binding.

**Comment by cordovapolymer** [comment]
@Cyan4973 Two JS bingings already exist, it would be great to have a pure JS port.

**Comment by Cyan4973** [comment]
It's not the same as downloading a pure Javascript source code implementing zstd,
but for information, this blog entry explains how to create zstd for browser using emscripten : 
http://dev.classmethod.jp/client-side/javascript/emscripten-zstandard-on-browser/

**Comment by yoshihitoh** [comment]
Hello, I wrote above blog entry, and creating a new zstd binding powered by Emscripten (pure-js).
- [Github repository](https://github.com/yoshihitoh/zstd-codec)
- [NPM](https://www.npmjs.com/package/zstd-codec)

This binding work on both Node.js and Browser.
Browser example:
- https://github.com/yoshihitoh/zstd-codec/tree/develop/js/example

**Comment by Cyan4973** [comment]
Nice work @yoshihitoh !

**Comment by Cyan4973** [comment]
I guess @yoshihitoh port, now also referenced on [Zstandard homepage](https://facebook.github.io/zstd/#other-languages), is a nice answer to this request.

**Comment by jakirkham** [comment]
Some work along these lines was done recently for ITK.

xref: https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/pull/25

**Comment by photopea** [comment]
Hi guys. I made a decompressor of DEFLATE (RFC 1951), that is only  4.2 kB of JS (it took me a week) - and it is faster than pako.js (a popular JS port of ZLIB).

I am a bit shocked, that what you provided so far is almost 2 MB of Javascript :( Do you think you could implement just a decoder of ZStandard in JS, that would be smaller than e.g. 30 kB?  I would like to use it in www.Photopea.com .

**Comment by jakirkham** [comment]
These days one might consider using WebAssembly. Idk how well that will work though depending on what functionality ZStandard depends on. Would have to look at the WebAssembly spec to see what is implemented and what still remains an open issue.

**Comment by Cyan4973** [comment]
If you only care about the decoder, consider starting from the [single-file decoder](https://github.com/facebook/zstd/tree/dev/contrib/single_file_libs) by @cwoffenden.
It's not JS code, but if `wasm` is an acceptable answer to your use case, the directory also contains scripts for `wasm` compilation, and a demo.

**Comment by photopea** [comment]
Yes, wasm is fine for me. In the worst case, I can write my own tiny interpreter of wasm in JS :)

Do you know about any other implementation of the Zstandard algorithm, other than this one? Maybe there are some "light-weight" implementations. I do not need multi-core execution, SIMD, etc.

**Comment by cwoffenden** [comment]
The single-file Wasm decoder was 26kB last time I checked, even smaller if Gzipped for for serving.

**Comment by jakirkham** [comment]
Could look at using Zopfli to squeeze that down even further potentially

**Comment by photopea** [comment]
Hi, I managed to generate a 31kB WASM file (12 kB compressed with Deflate) which works perfectly, so thanks! :)

BTW. it seems like in my case, I do not know the final size of decompressed data. However, ZSTD_decompress() requires the pointer in the memory for the output (and returns the output length).

Is there a way to tell the library to allocate the output dynamically? At the moment, I give it a buffer, which is 8x larger than the compressed data. But I still feel uncomfortable about doing it this way.

**Comment by terrelln** [comment]
@photopea you can use `ZSTD_getFrameContentSize()` to find the uncompressed size of the data, and then dynamically allocate a correctly sized buffer yourself.

By default the zstd CLI & library will write the uncompressed size into the frame by default whenever the file size is known: Either when using a "single-pass" compression function like `ZSTD_compress()`, or when streaming and a `pledgedSrcSize` is set (the CLI will set it whenever compressing a regular file).

**Comment by photopea** [comment]
I am processing sequnces of bytes, which can be used inside Adobe Illustrator files.

I looked at the initial bytes of these sequences, but none of them looks like the size of the optut (in big or little endian). However, these sequences are the correct input for ZSTD_compress() , which returns an expected output.

I do not know what a CLI is, I never worked with your library. I asked a frend to prepare a WASM file for me and I am calling ZSTD_compress(), malloc() and free() which are inside it (from JS) :)

**Comment by photopea** [comment]
@terrelln What exactly does the ZSTD_getFrameContentSize() ? I thought it does the same thing as ZSTD_decompress(), except that it does not write any data anywhere. But it does go through the whole compressed data to determine the length.

In my case, ZSTD_getFrameContentSize() returns -1 (ZSTD_CONTENTSIZE_UNKNOWN). Is there any function to perform the decompression without writing an output data (to determine the output length)?

**Comment by getkey** [comment]
I haven't tried it yet but it looks like @donmccurdy's is maintaining a WebAssembly port here https://github.com/donmccurdy/zstddec

**Comment by photopea** [comment]
@getkey I would not call it a WebAssembly port, as there is no wasm file in it.

**Comment by donmccurdy** [comment]
It's using the single-file decoder from this repository, compiled to WASM, and embedded in the JavaScript file as a base64 Data URI: https://github.com/donmccurdy/zstddec/blob/c600de0ce7c3b2dca89d6234da75bf2e5df7c44c/zstddec.ts#L126. I packaged it that way because publishing `.wasm` files for npm (the JS package manager) is [tricky](https://twitter.com/donrmccurdy/status/1357560879718354945), and the file was small enough that decoding the Data URI doesn't add much overhead.

**Comment by fabiospampinato** [comment]
In case anybody here is interested I've made a ~27kb port of zstd v1.5 to wasm (decompressor-only): https://www.npmjs.com/package/zstandard-wasm, I plan for it to track every release of zstd, and potentially add a compressor for it too, although I don't really need a wasm compressor myself and adding that in a way that doesn't bloat up bundles might be tedious, so we'll see about that.

**Comment by photopea** [comment]
Here is my ZSTD in Wasm, 28 kB (12.6 kB ZIPped), which I am using since January. I am not a user of NPM.

[zstd.zip](https://github.com/facebook/zstd/files/6602821/zstd.zip)

**Comment by fabiospampinato** [comment]
> Here is my ZSTD in Wasm, 28 kB (12.6 kB ZIPped), which I am using since January. I am not a user of NPM.

Yeah basically for the record if one would like to try this out for themselves one can either optimize for size by using the `-Oz` flag [here](https://github.com/fabiospampinato/zstandard-wasm/blob/1f9b78ff0f82f52157e7ec4f58a1692a8436dc05/zstd/update.sh#L14), or optimize for performance by using the `-O3` flag.

**Comment by felixhandte** [comment]
@fabiospampinato, you may want to take a look at these [build flags](https://github.com/facebook/zstd/blob/dev/lib/Makefile#L38-L59). Some or all of them might help in further minimizing the size of the decompressor you build.

**Comment by cwoffenden** [comment]
@felixhandte Most of these flags are already in the single file build script that, AFAIK, the JS builds are using:

https://github.com/facebook/zstd/blob/8a3bdfaa7bb2944dbed1ce9dede39f512d6da3f9/build/single_file_libs/zstddeclib-in.c#L31

(At the time I did the tradeoff between size and performance and settled on these ones)

**Comment by photopea** [comment]
Guys, could some of you make a webapp for ZSTD compression? I would drag and drop one binary file into a website, and after a while, it would offer me to save another binary file to my computer. I would like to do some experiments.

As I said, I do not work with C or compilers, and I do not want to install some complex 50 MB EXE program into my computer.

**Comment by 101arrowz** [comment]
@photopea Maybe you could use the command line tool? If not it's trivial to create a webapp that compresses with WASM, there are many existing JS bindings to Zstandard (it seems you already have one, but [this one](https://github.com/evanwashere/wasm/tree/master/src/zstd) seems solid as well).

In case anyone is interested, I am currently working on a pure JS port of Zstandard (not made with Emscripten and not compiled to WASM, but an actual port) that should be much smaller and potentially faster than existing versions. You can follow [this discussion](https://github.com/101arrowz/fflate/discussions/69) if you'd like to know about any progress I make; currently, I'm working on the decompressor and will publish it when it's finished.

**Comment by photopea** [comment]
@101arrowz I looked at your link https://github.com/evanwashere/wasm/tree/master/src/zstd , but it seems their code is not Javascript (I wonder why they name it .js). When I run it, I see an error "Uncaught SyntaxError: Unexpected token 'export'". 

BTW. I see you already know my library UZIP.js :) I strongly support you in your goal of creating an independent ZStandard implementation!

**Comment by photopea** [comment]
@101arrowz What is your progress with the Javascript decompressor of ZStandard? I think I already need it :D

People open files in Photopea.com , which are e.g. only 20 MB, but they are over 3 GB after the ZSTD decompression. I can not use the WASM library, because current WASM implementations in browsers are limited to 2 GB of memory for a WASM module.

**Comment by 101arrowz** [comment]
If you want a contiguous ArrayBuffer, I don't think any engines support over 2GB either, though streaming would be possible.

So far the decompressor is almost done. It will be a few more days before I can publish it. It will support data streaming, so you can bypass the memory limitations of the browser.

**Comment by 101arrowz** [comment]
[I've completed the pure JS decompressor](https://github.com/101arrowz/fflate/discussions/69#discussioncomment-945803). It seems to perform OK compared to WASM, but WASM should be preferred if it's available. The main benefit of this JS version is streaming support and tiny bundle size (7kB minified, 3.4kB minzipped).

**Comment by photopea** [comment]
@101arrowz All your code is TypeScript. Could you provide a JS file somehwere, which I can use directly in a web browser? I have no experience with "compiling".

**Comment by 101arrowz** [comment]
@photopea Check out the updated README, there are instructions for how to use a CDN. Just download the file from the CDN and use the global `fzstd`. [This is the current CDN link](https://unpkg.com/fzstd@0.0.2/umd/index.js).

**Comment by photopea** [comment]
@101arrowz Thanks! Your decompressor seems to be about 2.2x slower than the WASM port. On the other hand, it is only 3.6 kB zipped, while WASM is 11.9 kB. I am really happy when I see such "tiny" software :)

**Comment by 101arrowz** [comment]
Good to hear! @Cyan4973 could you add this port to the list of implementations in other languages?

**Comment by Cyan4973** [comment]
done

**Comment by photopea** [comment]
@101arrowz  have you thought about making a "simple" ZSTD compressor in pure Javascript? I think You can create an amazing thing, which will beat Deflate compression (in terms of compression ratio and speed) in just 10 - 20 kB of code :) You ca probably even use some code from your "fflate" compressor :)

I would like to do the compression in a browser, and I don't want people to download a 3 MB Wasm port of "zstd" from Facebook.

**Comment by 101arrowz** [comment]
FSE compression seems much more complex than standard Huffman coding, so if I do end up creating a compressor it could take multiple weeks or months. For now the decompressor alone is available but I'll look into a compressor implementation.

**Comment by photopea** [comment]
Could someone create a compressor for ZSTD in WASM, that is smaller than e.g. 100 kB? Do you think it is possible? Would it be possible to generate it out of this library, or a new implementation would be required?

**Comment by cwoffenden** [comment]
It's possible to fit the entire compressor/decompressor into less than 100kB. A quick test compiling (with `emcc`) the `single_file_libs/examples/roundtrip.c` (with the inlined data replaced with a few bytes) results in 300k-ish Wasm file, which can be served Gzipped at 86kB. I think it's even been done by a few people who've posted links to this ticket.

**Comment by photopea** [comment]
@cwoffenden  could you maybe share the WASM file of your compressor? I havent worked with any compilers in ages and I am afraid of them :/

Do you think the compressor could be squeezed even more? If it can be made 3x smaller, but the compression would be 3% worse, I am ok with that :)

**Comment by cwoffenden** [comment]
@photopea sharing the Wasm file won't expose the calls the JS, since I only built the roundtrip test file. You need something that does the equivalent of this but for the compressor: https://github.com/fabiospampinato/zstandard-wasm

**Comment by photopea** [comment]
You can see the methods of a WASM file e.g. in the browser environment. I was usually able to figure out the input / output of methods using the documentation of the library. So a WASM file is usually enough for me (if the names of methods are preserved in it).

**Comment by ctrlcctrlv** [comment]
Hello friends,

I had never played with WebAssembly before, but am very familiar with CMake, C compilers etc, so fell down a bit of a rabbit hole this morning attempting to upgrade the original project here, just because I wanted to distribute an HTML file with some Zstd-compressed data rather than Zlib, the usual trick. I succeeded in updating @kig's https://github.com/kig/zstd-emscripten from 2016. I pulled facebook/zstd then worked on their CMake files until it built again and the test worked. (The test needed some upgrading to run due to the fact `ZStd.buffer` is now `undefined` due to us using WebAssembly heap memory, please kindly see https://github.com/ctrlcctrlv/zstd-emscripten/commit/568bc158950234ceba8e917b6d69285984389249#diff-b3d3218af14fb18fec622741904b4d597852babaac96e054b23258ea2509eeaa.)

Emscripten+WebAssembly build of Zstandard supporting both compression and decompression: https://github.com/ctrlcctrlv/zstd-emscripten

I believe this issue can be closed, and @fabiospampinato's zstandard-wasm should probably be considered deprecated.

```js
var rawSize = 500000;

var compressionLevel = 1;

var rawPtr = ZStd._malloc(rawSize);
var rawU8 = new Uint8Array(ZStd.HEAPU8.buffer, rawPtr, rawSize);
for (var i=0; i<rawU8.length; i++) {
        //rawU8[i] = (Date.now() & 0xff) + (Math.random()*2);
        rawU8[i] = i % 200;
}

console.time("Compression");
var compressedPtr = ZStd._malloc(rawSize);
var compressedSize = ZStd._ZStdCompress(compressedPtr, rawSize, rawPtr, rawSize, compressionLevel);
var compressedU8 = new Uint8Array(ZStd.HEAPU8.buffer, compressedPtr, compressedSize);
console.timeEnd("Compression");

console.log("Compressed " + rawSize + " bytes to " + compressedSize + " bytes. ");
console.log(compressedPtr);
console.log(compressedSize);
console.log(compressedU8);

console.time("Decompression");
var decompressedPtr = ZStd._malloc(rawSize);
var decompressedSize = ZStd._ZStdDecompress(decompressedPtr, rawSize, compressedPtr, compressedSize);
console.timeEnd("Decompression");

console.log("Decompressed " + compressedSize + " bytes to " + decompressedSize + " bytes.");

if (decompressedSize !== rawSize) {
        throw("ERROR: Decompressed size is different from raw size.");
}

var decompressedU8 = new Uint8Array(ZStd.HEAPU8.buffer, decompressedPtr, decompressedSize);
console.log(decompressedU8);

for (var i=0; i<decompressedU8.length; i++) {
        if (decompressedU8[i] !== rawU8[i]) {
                throw("ERROR: Decompressed value differs from raw at " + i + ", " + decompressedU8[i] + " !== " + rawU8[i]);
        }
}

console.log("Compression roundtrip completed successfully.")
```

**Comment by ctrlcctrlv** [comment]
By the way, if you just want `zstd.js` and `zstd.wasm` and don't want to go through the CMake build, I uploaded them here: https://github.com/ctrlcctrlv/zstd-emscripten/releases/tag/v20211120

**Comment by fabiospampinato** [comment]
> I believe this issue can be closed, and @fabiospampinato's zstandard-wasm should probably be considered deprecated.

I have no plan to stop maintaining it in the foreseeable future.

It's cool that you ported the compressor to the web too, but if one doesn't need that it's just overhead for them, my decompressor-only build is like ~25kb gzipped, yours is ~1000kb gzipped.

To summarize:

- For compressing on the web I think @ctrlcctrlv's [build](https://github.com/ctrlcctrlv/zstd-emscripten) is the only game in town, and it can decompress as well.
- For decompressing-only on the web my [build](https://github.com/fabiospampinato/zstandard-wasm) should be smaller than other WASM builds, and faster than other non-WASM builds.
- For decompressing-only with pure JS there's @101arrowz [implementation](https://github.com/101arrowz/fzstd), which is the smallest zstd decompressor I've seen by far, but it's a bit slower than WASM builds.

FWIW personally I'd go with @ctrlcctrlv's build for compressing as that seems the only option, and @101arrowz's implementation for decompressing unless the absolute maximum performance is necessary, as WASM modules tend to sort of leak memory (you can't free no longer needed heap without killing the whole thing and instantiating it again).

**Comment by ctrlcctrlv** [comment]
Thanks for your appraisal :) I needed to decompress a file which expands to 75MB, which is why I wanted WASM.

**Comment by photopea** [comment]
I am still looking for a tiny compressor, e.g. under 50 kB zipped. I will try to implement my own "light" compressor once I have more time.

**Comment by ctrlcctrlv** [comment]
```
-rwxr-xr-x 1 fred fred 89K Nov 20 13:23 zstd.wasm.gz
```

I don't see much difference between 50K and 89K personally.

**Comment by photopea** [comment]
Where exactly is the 89K file? I saw only your WASM file, that is 3 MB.

**Comment by ctrlcctrlv** [comment]
You said "under 50 kB zipped", so I just tried `gzip zstd.wasm` to see what the gzipped size would be (as delivered by e.g. a webserver). If your webserver supports the newer Brotli standard even 67K is possible:

```
-rwxr-xr-x 1 fred fred 67K Nov 20 13:23 zstd.wasm.br
```

The 3MB file is just the uncompressed raw WebAssembly.

**Comment by fabiospampinato** [comment]
@ctrlcctrlv I think you might be compressing the wrong file, gzipping the 3MB wasm file gives me a ~925kb file. WASM can usually be compressed pretty well, but not _that_ well.

**Comment by ctrlcctrlv** [comment]
Oh, you're right, I was in the wrong directory and compressed a file from a broken build while I was still figuring things out. :-) Sorry. Let me have a think on how to slim down the build, if such is even possible.

**Comment by ctrlcctrlv** [comment]
All rights friends, here we are, here's a pre-release of my results; first of all, I was compiling with `-O0`, so even the normal combined build is improved now that we're compiling with `-Os`.

https://github.com/ctrlcctrlv/zstd-emscripten/commit/c859cdb7df152f20840c02499fd9854f19587cc2

I would note that the decompressor is _under_ 50K with Brotli compression, and only just above it with Gzip, meeting @photopea's request!

Here are the new files: https://github.com/ctrlcctrlv/zstd-emscripten/releases/tag/v20211121

# Combined
```
-rw-r--r-- 1 fred fred  28K Nov 20 23:50 zstd.js
-rw-r--r-- 1 fred fred 6.9K Nov 20 23:50 zstd.js.br
-rw-r--r-- 1 fred fred 7.7K Nov 20 23:50 zstd.js.gz
-rwxr-xr-x 1 fred fred 1.2M Nov 20 23:50 zstd.wasm
-rwxr-xr-x 1 fred fred  94K Nov 20 23:50 zstd.wasm.br
-rwxr-xr-x 1 fred fred 204K Nov 20 23:50 zstd.wasm.gz
```

# Decompress only
```
-rw-r--r-- 1 fred fred  28K Nov 20 23:50 zstd_decompress.js
-rw-r--r-- 1 fred fred 6.9K Nov 20 23:50 zstd_decompress.js.br
-rw-r--r-- 1 fred fred 7.7K Nov 20 23:50 zstd_decompress.js.gz
-rwxr-xr-x 1 fred fred 124K Nov 20 23:50 zstd_decompress.wasm
-rwxr-xr-x 1 fred fred  30K Nov 20 23:50 zstd_decompress.wasm.br
-rwxr-xr-x 1 fred fred  42K Nov 20 23:50 zstd_decompress.wasm.gz
```

# Compress only
```
-rw-r--r-- 1 fred fred  28K Nov 20 23:50 zstd_compress.js
-rw-r--r-- 1 fred fred 6.9K Nov 20 23:50 zstd_compress.js.br
-rw-r--r-- 1 fred fred 7.7K Nov 20 23:50 zstd_compress.js.gz
-rwxr-xr-x 1 fred fred 1.1M Nov 20 23:50 zstd_compress.wasm
-rwxr-xr-x 1 fred fred  76K Nov 20 23:50 zstd_compress.wasm.br
-rwxr-xr-x 1 fred fred 176K Nov 20 23:50 zstd_compress.wasm.gz
```

**Comment by photopea** [comment]
Your compressor WASM is 176 kb zipped, which is great! :) I wanted something under 100 kb, but it is the smalles that I have seen so far.

But your decompressor is still quite huge. It is 124K (42K zipped), while [mine is 32K (12K zipped)](https://github.com/facebook/zstd/issues/606#issuecomment-855260340).

**Comment by fabiospampinato** [comment]
@ctrlcctrlv there might still be some room for size reduction, for whatever reason my size-optimized build is like half yours, no idea why.

**Comment by kig** [comment]
Hi all, thanks for reminding me of the emscripten port @ctrlcctrlv! 

I did a size-optimized emscripten [build script](https://github.com/kig/zstd-emscripten/commit/f3e1f96007797e1fc227208b12affdf6a7febc62) with legacy, dictBuilder and deprecated files removed, and set the ZSTD_LIB_MINIFY and ZSTD_NO_INLINE flags. The compressor + decompressor WASM is 222 kB, 75 kB gzipped, 62 kB with brotli.

You may be able to further reduce the total library size by going the llvm "[who needs libc](https://aransentin.github.io/cwasm/)"-route or stripping the emscripten-generated zstd.js file.

**Comment by kig** [comment]
I updated https://github.com/kig/zstd-emscripten/ with streaming compression and decompression, you can check the demo page for usage https://kig.github.io/zstd-emscripten/

The streaming API inflated the library size by 8 kB gzip, 5 kB brotli.

**Comment by ctrlcctrlv** [comment]
Thanks for your effort @kig! I planned to do the same at some point, but most of my coding energy goes into my fonts and font editor I'm afraid, so I'm happy just at having inspired further work :)

**Comment by kig** [comment]
Thanks for bringing the repo up-to-speed @ctrlcctrlv ! I wanted to use zstd + wasm in my drawing app last week, so it was great to re-discover this.

I ditched the API wrapper in zstd.js.c and changed the repo to track upstream in a submodule. The generated binding does a low-level binding to almost all functions in zstd.h (skipping the thread pool ones.) The old fork repo is [archived](https://github.com/kig/zstd-emscripten-archived/) and replaced by [the new one](https://github.com/kig/zstd-emscripten/).

If you want to write your JavaScript like C, you're in luck. https://kig.github.io/zstd-emscripten/ for a demo of the usage.

[edit] You can customize the exported API by deleting lines in the exported_functions.txt file (and corresponding directories in cmake/lib/CMakeLists.txt). E.g. A build with only the streaming decompression functions is 28k gzipped + 8k emscripten js.
