### ISSUE TITLE
Updated build 1.1.4 crashes.

### ISSUE THREAD

**Issue by sebbellob** [facebook/zstd#624]
Build 1.1.4 x64 crashes on Win7 x64 SP1.
Even the parameters cannot be seen,instant crash after running the.exe.
ATM i cant tell more details,because im from mobile.

**Comment by inikep** [comment]
It seems that the issue is dependency of 64-bit build on zlib1.dll
Is the 32-bit executable OK on Win7? It uses a static zlib library.

**Comment by sebbellob** [comment]
Checking ASAP.
