### ISSUE TITLE
Decompress a block inside a frame?

### ISSUE THREAD

**Issue by halayli** [facebook/zstd#651]
Hi there,

Is it possible to decompress a block inside a frame without decompressing all the previous blocks? I am aware that blocks are dependent but is the dependency here that they are accessible or that they've been decompressed?

I have a case where I compress a bunch of records into a stream and I need to extract couple records from it. I am trying to avoid decompressing from the beginning of the stream if that's even possible.

**Comment by terrelln** [comment]
You will need to decompress the entire frame up to the last record you need. If you want to be able to decompress only part of an input, you can compress the input as multiple concatenated frames, since each frame is independent. You can then use `ZSTD_findFrameCompressedSize()` to find the end of each frame, or can include metadata in a skippable frame. See Issue #395 for a discussion about jump tables.

**Comment by halayli** [comment]
@terrelln I was trying to avoid using multiple concatenated frames to avoid degrading compression ratio but I guess there's no way around it.

**Comment by Cyan4973** [comment]
Note that header sizes are not that large. Only specific use case (lots of small blocks) could measurably benefit from removing them.

Now, if you absolutely need to, you can indeed create your own format, by using raw block functions: 
https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L746

These functions do not generate any kind of header, which means you'll have to create them, any way you please. 
At a minimum, block decompression requires the size of compressed block, and an upper bound of decompressed size.

**Comment by halayli** [comment]
@Cyan4973 sorry I was referring to the frame compression ratio containing  4 blocks for example, vs 2 frames having 2 blocks each. My understanding was that blocks within a frame are dependent which gives better compression. So if I create 2 frames we'll have less data in each and hence lower compression ratio. 

Basically I am trying to find a good balance of compression ratio to record extraction granularity.

**Comment by Cyan4973** [comment]
Indeed, cutting data into smaller frame should result in lower compression ratio.
The impact is not necessarily "large", but such conclusion is highly dependent on data type.
So it's recommended to test and measure several schemes, and settle for the better "all-around" one.

**Comment by halayli** [comment]
Agreed. That's where I am now and ended up wondering about the possibility of decompressing starting from a random block inside a frame. 

Thanks you @terrelln and @Cyan4973 for your prompt responses!
