### ISSUE TITLE
How to use the blocks API with a dictionary?

### ISSUE THREAD

**Issue by ArtemGr** [facebook/zstd#664]
Documentation is a bit vague on this. How do I use the blocks API with a dictionary? Is it even possible?
Should I pass the dictionary contents to `ZSTD_insertBlock` in order to prime the stream?

Maybe add a note to the docs?

**Comment by Cyan4973** [comment]
From [zstd.h](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L746) : 
```
    - It is necessary to init context before starting
      + compression : ZSTD_compressBegin()
      + decompression : ZSTD_decompressBegin()
```
__`+ variants _usingDict() are also allowed`__

Maybe I should also add that variants `_using{C,D}Dict()` are allowed too.

**Comment by ArtemGr** [comment]
It's starting to make sense.
Thanks!
I'll try to post an example later.
