### ISSUE TITLE
node-zstd uses old version.  Also, just generally can't decompress on iOS with zstd

### ISSUE THREAD

**Issue by bhartsb** [facebook/zstd#667]
First, I simply want to compress some binary/text data being returned from redis to my nodejs server and then send the compressed data to my iOS Obj-C app and decompress it.  I'm really a user of compression and don't know much about it.

Installed node-zstd on Nodejs.   Then I installed https://github.com/RobinChao/iOS-zstd for my iOS Obj-C app.
I tested compressing then decompressing a Buffer on Nodejs server...so far so good.  Then I send same compressed data to iOS app and try to decompress.   Failure.  The indication is that node-zstd is not embedding the decompressed size into the compressed data frame (so it's retrievable with ZSTD_getDecompressedSize()).  I somewhat verify this by looking at node-zstd's index.js compress wrapper function:

```
    function compress(input, params, cb) {
      if (arguments.length === 2) {
        cb = params;
        params = {};
      }
      if (!Buffer.isBuffer(input)) {
        process.nextTick(cb, new Error('Input is not a buffer.'));
        return;
      }
      if (typeof cb !== 'function') {
        process.nextTick(cb, new Error('Second argument is not a function.'));
        return;
      }
      var stream = new TransformStreamCompressor(params);
      var chunks = [];
      var length = 0;
      stream.on('error', cb);
      stream.on('data', function(c) {
        chunks.push(c);
        length += c.length;
      });
      stream.on('end', function() {
        cb(null, Buffer.concat(chunks, length));
      });
      stream.end(input);
    }

```
and the function it calls:

```   
    function TransformStreamCompressor(params, sync) {
     Transform.call(this, params);

      this.compressor = new compressor.StreamCompressor(params || {});
      this.sync = sync || false;
      var blockSize = this.compressor.getBlockSize();
      this.status = {
        blockSize: blockSize,
        remaining: blockSize
      };
    }
```

It seems like instead of doing simple compression on a Buffer it is actually using stream compression internally. 

So I decided to try take the C function decompressFile_orDie(const char* fname) from the zstd example file streaming_decompression.c, modify it to use a memory file*.  Xcode's LLVM compiler is able to mix C and C++ into Obj-c code.  Failure again.  
I'm getting an error message "Unknown frame descriptor"  I thought at first that it might be that node-zstd was using an old version of zstd, and in fact it was using 1.0.0.  So I tried putting zstd in legacy mode by setting ZSTD_LEGACY_SUPPORT = 1.  NOTE: doing this doesn't seem to invoke legacy support, it seems one also needs to set zds->legacyVersion.  
Once I did this I got a new message saying the version wasn't supported (I don't recall the exact phrasing of the msg).  So next I tried updating the dependencies of node-zstd using NPM.  That didn't seem to update ./deps/zstd so I renamed the folder and git cloned a new zstd.  Tried decompressing again now with the zstd as the latest 1.1.5 on both sides.  Failure.  I'm getting a message: ZSTD_decompressStream() error : Unknown frame descriptor.

Here's what my hacked decompressFile_orDie(const char* fname) code looks like:

```
        char ch;
        FILE *fin;
        
        fin = fmemopen([argsData[0] bytes], [argsData[0] length], "r");
        while ((ch = fgetc (fin)) != EOF)
            printf ("Got %c\n", ch);
        
        
        size_t const buffInSize = ZSTD_DStreamInSize();
        void*  const buffIn  = malloc_orDie(buffInSize);
    //        FILE* const fout = stdout;
        size_t const buffOutSize = ZSTD_DStreamOutSize();  /* Guarantee to successfully flush at least one complete compressed block in all circumstances. */
        void*  const buffOut = malloc_orDie(buffOutSize);
        
        ZSTD_DStream* const dstream = ZSTD_createDStream();
        if (dstream==NULL) { fprintf(stderr, "ZSTD_createDStream() error \n"); exit(10); }
        
        /* In more complex scenarios, a file may consist of multiple appended frames (ex : pzstd).
         *  The following example decompresses only the first frame.
         *  It is compatible with other provided streaming examples */
        size_t const initResult = ZSTD_initDStream(dstream);
        if (ZSTD_isError(initResult)) { fprintf(stderr, "ZSTD_initDStream() error : %s \n", ZSTD_getErrorName(initResult)); exit(11); }
        size_t read, toRead = initResult;
        while ( (read = fread_orDie(buffIn, toRead, fin)) ) {
            ZSTD_inBuffer input = { buffIn, read, 0 };
            while (input.pos < input.size) {
                ZSTD_outBuffer output = { buffOut, buffOutSize, 0 };
                toRead = ZSTD_decompressStream(dstream, &output , &input);  /* toRead : size of next compressed block */
                if (ZSTD_isError(toRead)) { fprintf(stderr, "ZSTD_decompressStream() error : %s \n", ZSTD_getErrorName(toRead)); exit(12); }
    //                fwrite_orDie(buffOut, output.pos, fout);
            }
        }
        
        ZSTD_freeDStream(dstream);
        fclose_orDie(fin);
        //fclose_orDie(fout);
        free(buffIn);
        free(buffOut);
```

Since Xcode was choking on fmemopen I found this: https://github.com/NimbusKit/memorymapping

Anyway I'm somewhat over my head with this given the time I have to get this working. I'd like to use Zstd because it seems from my layman's point of view to be good, and the compress/decompress on Nodejs seemd remarkably fast and my compression was > 10:1 on my test data.  

I looked for a tutorial on zstd but it seems like there isn't much out there yet.  The wrappers for iOS and Nodejs seem to be out of date.  I did also look at SwiftZSTD.  Node-zstd and SwiftZSTD were both listed on the main page for ZSTD.

Referenced Nodejs wrapper:
https://github.com/zwb-ict/node-zstd

Referenced iOS wrappers:
https://github.com/RobinChao/iOS-zstd (Obj-C)
https://github.com/omniprog/SwiftZSTD (Swift)

Any help or suggestions are appreciated.

**Comment by Cyan4973** [comment]
That's a detailed investigation.
A few points come to mind : 
- The issue described looks clear : the compression is done with a version (node-js) which does not provide "decompressed size" in the header, because it's based on the streaming interface. The iOS decoders do not support this setup. This could be solved by : 
   + Using another version to compress
   + Sending the decompressed size alongside the compressed data (within your own protocol)
- In your code sample, without the function prototype, it's difficult to understand what you want to achieve
   + Assuming you're passing a `FILE* fout` argument, why comment the call to `fwrite()` ?
- All versions of Zstandard since >= v0.8.0 are compatible with each other. Legacy support is only useful to decode versions <= 0.7.5

**Comment by bhartsb** [comment]
I can pass the decompressed size and I hard coded it before but still had issues.  The function prototype would be:

void * decompressBuffer(void * inputBytes, long inputBytesSize, long outputBytesSizeDecompressed);
//returns * to decompressed bytes

In the above code sample I gave char ch; should actually be int ch;  That seems to make some difference.

**Comment by bhartsb** [comment]
This seems to work:
'''
NSData * decompressBuffer_streamMethod(void * inBuffer, size_t inBufferSize)
{
    /*
     * Adapted from nstd's example/streaming_decompression.c
     * To use in iOS include fclose_orDie(),fread_orDie(), fwrite_orDie() and malloc_orDie() in obj-c source file
     * Also for fmemopen() include sources from https://github.com/NimbusKit/memorymapping
     * 
     * returns decompressed bytes in an NSData object
     */
    
    NSMutableData *decompressedData = [[NSMutableData alloc] init];
    
    FILE * fin = fmemopen(inBuffer, inBufferSize, "r");
    
    size_t const buffInSize = ZSTD_DStreamInSize();
    void*  const buffIn  = malloc_orDie(buffInSize);
    FILE* const fout = stdout;
    size_t const buffOutSize = ZSTD_DStreamOutSize();/* Guarantee to successfully flush at least one complete compressed block in all circumstances. */
    void*  const buffOut = malloc_orDie(buffOutSize);
    
    ZSTD_DStream* const dstream = ZSTD_createDStream();
    if (dstream==NULL) {
        NSLog(@"ZSTD_createDStream() error");
    }
    
    /* In more complex scenarios, a file may consist of multiple appended frames (ex : pzstd).
     *  The following example decompresses only the first frame.
     *  It is compatible with other provided streaming examples */
    size_t const initResult = ZSTD_initDStream(dstream);
    if (ZSTD_isError(initResult)) {
        NSLog(@"%@", [NSString stringWithFormat:@"ZSTD_initDStream() error : %s",ZSTD_getErrorName(initResult)]);
    }
    size_t read, toRead = initResult;
    
    while ( (read = fread_orDie(buffIn,toRead , fin)) ) {
        ZSTD_inBuffer input = { buffIn, read, 0 };
        while (input.pos < input.size) {
            ZSTD_outBuffer output = { buffOut, buffOutSize, 0 };
            toRead = ZSTD_decompressStream(dstream, &output , &input);  /* toRead : size of next compressed block */
            if (ZSTD_isError(toRead)) {
                NSLog(@"%@", [NSString stringWithFormat:@"ZSTD_decompressStream() error : %s", ZSTD_getErrorName(toRead)]);
            }
            
            [decompressedData appendBytes:output.dst length:output.pos];
        }
    }
    
    ZSTD_freeDStream(dstream);
    fclose_orDie(fin);
    fclose_orDie(fout);
    free(buffIn);
    free(buffOut);
    
    return [decompressedData copy];
}
'''

**Comment by bhartsb** [comment]
This seems to work:
```
NSData * decompressBuffer_streamMethod(void * inBuffer, size_t inBufferSize)
{
    /*
     * Adapted from nstd's example/streaming_decompression.c
     * To use in iOS include fclose_orDie(),fread_orDie(), fwrite_orDie() and malloc_orDie() in obj-c source file
     * Also for fmemopen() include sources from https://github.com/NimbusKit/memorymapping
     * 
     * returns decompressed bytes in an NSData object
     */
    
    NSMutableData *decompressedData = [[NSMutableData alloc] init];
    
    FILE * fin = fmemopen(inBuffer, inBufferSize, "r");
    
    size_t const buffInSize = ZSTD_DStreamInSize();
    void*  const buffIn  = malloc_orDie(buffInSize);
    FILE* const fout = stdout;
    size_t const buffOutSize = ZSTD_DStreamOutSize();/* Guarantee to successfully flush at least one complete compressed block in all circumstances. */
    void*  const buffOut = malloc_orDie(buffOutSize);
    
    ZSTD_DStream* const dstream = ZSTD_createDStream();
    if (dstream==NULL) {
        NSLog(@"ZSTD_createDStream() error");
    }
    
    /* In more complex scenarios, a file may consist of multiple appended frames (ex : pzstd).
     *  The following example decompresses only the first frame.
     *  It is compatible with other provided streaming examples */
    size_t const initResult = ZSTD_initDStream(dstream);
    if (ZSTD_isError(initResult)) {
        NSLog(@"%@", [NSString stringWithFormat:@"ZSTD_initDStream() error : %s",ZSTD_getErrorName(initResult)]);
    }
    size_t read, toRead = initResult;
    
    while ( (read = fread_orDie(buffIn,toRead , fin)) ) {
        ZSTD_inBuffer input = { buffIn, read, 0 };
        while (input.pos < input.size) {
            ZSTD_outBuffer output = { buffOut, buffOutSize, 0 };
            toRead = ZSTD_decompressStream(dstream, &output , &input);  /* toRead : size of next compressed block */
            if (ZSTD_isError(toRead)) {
                NSLog(@"%@", [NSString stringWithFormat:@"ZSTD_decompressStream() error : %s", ZSTD_getErrorName(toRead)]);
            }
            
            [decompressedData appendBytes:output.dst length:output.pos];
        }
    }
    
    ZSTD_freeDStream(dstream);
    fclose_orDie(fin);
    fclose_orDie(fout);
    free(buffIn);
    free(buffOut);
    
    return [decompressedData copy];
}
```

**Comment by Cyan4973** [comment]
> I have not tested passing in the decompressedSize and setting buffer sizes explicitly...maybe this would be faster???

Yes, it would be faster.
That being said, decompressing correctly is more important, and you do have one working solution now. You can always come back optimizing it later on when you have time to spend on this topic.

**Comment by bhartsb** [comment]
Thanks:)

**Comment by bhartsb** [comment]
regarding decompressBuffer_streamMethod() above:
in the context of an iOS app it seems best to comment out the call to fclose_orDie(fout)
This was causing a crash the second time the function was called.

See the related thread at http://stackoverflow.com/questions/4972994/how-to-close-stdout-and-stderr-in-c  where it says "...Since after the call to fclose() any use of stream results in undefined behavior, fclose() should not be used on stdin, stdout, or stderr except immediately before process termination..."

Also I don't thing the const is needed for:

'''
size_t const buffInSize = ZSTD_DStreamInSize();
    void*  const buffIn  = malloc_orDie(buffInSize);
    FILE* const fout = stdout;
    size_t const buffOutSize = ZSTD_DStreamOutSize();/* Guarantee to successfully flush at least one complete compressed block in all circumstances. */
    void*  const buffOut = malloc_orDie(buffOutSize);
'''
