### ISSUE TITLE
Pure Java decompressor sources

### ISSUE THREAD

**Issue by catbaxter** [facebook/zstd#676]
Are you planning to release pure java decompressor sources?

**Comment by Cyan4973** [comment]
There is currently one open-source pure java decompressor, available at :
https://github.com/prestodb/presto/tree/master/presto-orc/src/main/java/com/facebook/presto/orc/zstd

That's all there is currently. Situation will improve around the Summer.

**Comment by catbaxter** [comment]
Ok, I see, It's a pity that I can't compile it for Android.

**Comment by Cyan4973** [comment]
Maybe this is related to : 
https://github.com/luben/zstd-jni/issues/10
