### ISSUE TITLE
use the zstd compress interface to compress same data , the size of compressed result is different

### ISSUE THREAD

**Issue by zdsppl** [facebook/zstd#681]
we use zstd in our system to compress block(size = 16Kb) data.  Our system is a distributed system，and data is stored mutiple copies on different server. In one server, we use mutiple threads to compress different block data  by  ZSTD_compressCCtx interface, and each thread holds a  thread local ZSTD_CCtx created by ZSTD_createCCtx function.  Recently, we are surprised to find out that the copyies of same block data on different server is compressed to different size, and the compressed size is different in the same server too.Although both the compressed results can been decompressed correctly.However, we never find this problem when we use LZ4, the compressed size is same when compressed repeatedly。

**Comment by Cyan4973** [comment]
A first simple thing to ensure is that all threads use the same compression level.

If that's the case, then we have some more complex settings to look at.
When re-using contexts, the compressor can skip a lot of initialization work, which is good for speed, especially on small data. That being said, it might impact compression ratio in subtle ways which might be worth exploring.

To investigate that possibility, it would be best to work on a set of samples which trigger this behavior, if that's an opened option.

**Comment by Cyan4973** [comment]
Any news on this topic ?

**Comment by Cyan4973** [comment]
closing due to absence of feedback
