### ISSUE TITLE
--threads=#

### ISSUE THREAD

**Issue by sebbellob** [facebook/zstd#688]
Greetings !

It looks like --threads=# still doesnt work in arc.exe when chaining algorithms.
Tried all possibilities with no success : 
arc a -mzstd:--threads=3 myarc.arc mydata.dat
arc a -mzstd:-threads=3 myarc.arc mydata.dat
arc a -mzstd:threads=3 myarc.arc mydata.dat
It uses only 1 thread. Or am i lame ?
I think it would be better to assign to another ,simplier letter. for example :  -th2 ,-th3 ,-th4 ,etc.
Btw thank you very much !

**Comment by Cyan4973** [comment]
Could this topic be forwarded to `arc` maintainer ?
`--threads=3` should have worked, but it all depends on how `arc` parses its command line, and we have no control over that part from here.
The issue seems too generic to only impact `zstd`, I guess many other programs would benefit from clarity in how arguments are forwarded.

**Comment by Cyan4973** [comment]
any news on this topic ?

**Comment by sebbellob** [comment]
Sadly i have no time,but today i contacted the author... (Bulat Z.)

**Comment by Bulat-Ziganshin** [comment]
well, what is your arc.ini section for zstd?

**Comment by sebbellob** [comment]
ATM
packcmd    = zstd --ultra -22 -T3 $$arcdatafile$$.tmp -o $$arcpackedfile$$.tmp

My problem is that ,i cant use "-T3" with Freearc when chaining algos : -mdelta+zstd:T3 for example. It uses only one core, simply skips -T3.
But when defined in arc.ini ,its perfect.

**Comment by Bulat-Ziganshin** [comment]
packcmd = zstd --ultra -22 {options} $$arcdatafile$$.tmp -o $$arcpackedfile$$.tmp

and now use zstd:T3. sorry, the problem is lack of proper freearc documentation

**Comment by sebbellob** [comment]
Thanks Bulat !
