### ISSUE TITLE
DDict in block mode

### ISSUE THREAD

**Issue by Crazee** [facebook/zstd#700]
So you've got ZSTD_compress_usingCDict and ZSTD_compressBegin_usingCDict; and ZSTD_decompress_usingDDict but no **ZSTD_decompressBegin_usingDDict**.  

I suppose I could just use ZSTD_decompressBegin_usingDict, but wouldn't a DDict be better?

**Comment by Cyan4973** [comment]
Indeed, that's an overlook.

This is currently achieved by internal function [`ZSTD_refDDict()`](https://github.com/facebook/zstd/blob/dev/lib/decompress/zstd_decompress.c#L1865).

I guess all it takes would be to rename and expose it.

**Comment by Cyan4973** [comment]
`ZSTD_decompressBegin_usingDDict()` has been added in latest update of `dev` branch.

It will be part of next release.

**Comment by Crazee** [comment]
Thanks!
