### ISSUE TITLE
VS Compile Errors

### ISSUE THREAD

**Issue by Johnex** [facebook/zstd#707]
Hi!
I downloaded the latest 1.2.0 release and i am getting these errors when compiling in VS2015:

```
4>bench.obj : error LNK2019: unresolved external symbol _XXH64 referenced in function _BMK_benchMem
4>dibio.obj : error LNK2019: unresolved external symbol _ERR_getErrorString referenced in function _ERR_getErrorName
4>dibio.obj : error LNK2019: unresolved external symbol _ZDICT_trainFromBuffer_unsafe referenced in function _DiB_trainFromFiles
4>zstd.exe : fatal error LNK1120: 3 unresolved externals
```

I had no compile problems with zstd-1.1.4

**Comment by Cyan4973** [comment]
Hi @Johnex 

`zstd` project is regularly tested with Visual compilers.
The v1.2.0 release is no exception, and was successfully tested with VS2015 too :
https://ci.appveyor.com/project/YannCollet/zstd-p0yf0/build/1.0.990/job/h0noujhu3vlgp7kq#L994

Are you compiling the VS project provided within `/build` directory ?

**Comment by Johnex** [comment]
Oh sorry i forgot to explain that im using the Intel Compiler with Visual Studio.
The only thing i'm doing is going into the cmake folder, creating a new folder and there running:

```
cmake -G"Visual Studio 14 2015" -T"Intel C++ Compiler 17.0" ..
msbuild /p:Configuration=Release ALL_BUILD.vcxproj

```

I was able to do that without problems in zstd-1.1.4 but not in the latest release. I haven't changed anything on my end just basically changed the folder which i run the commands on, from zstd-1.1.4 to zstd-1.2.0

**Comment by terrelln** [comment]
It looks like there might be some configuration issues with the cmake build files. The symbol `_XXH64` should not ever be called, it should be `_ZSTD_XXH64`.

**Comment by Johnex** [comment]
Well i tested just doing the same thing but using the stock compiler, same problem.
I saw in the link that you sent me that you are only compiling Debug not Release for testing.
Release doesnt work for me.


```
cmake -G"Visual Studio 14 2015"
msbuild /p:Configuration=Release ALL_BUILD.vcxproj
```

**Comment by Cyan4973** [comment]
The test with release mode is here :
https://ci.appveyor.com/project/YannCollet/zstd-p0yf0/build/1.0.990/job/ji6u5y6kgqan0j0x#L994
But I don't think that's the problem.

You are not using the Visual project provided in `build/VS2010`,
but rather the `cmake` project in combination with VS2015.

We highly rely on external contributions to maintain the `cmake` script.
Furthermore, while the `cmake` script is regularly tested with `gcc`,
it's not yet tested in combination with VS2015.
So it's quite possible an issue slipped through.

**Comment by Johnex** [comment]
Oh ok i see. I didn't have issues with the previous release and just thought it would work :)

I saw this in the release notes now:

> build: improved cmake script, by @Majlen

@Majlen maybe missed something in the modifications?

**Comment by Majlen** [comment]
Well, with Visual Studio Compiler there seems to be a problem with /RTC1, which I guess should be enabled only in Debug build. A fix for that is quite easy.

The problem with Intel compiler is odd and in my opinion should not be CMake related. Can you somehow test that with different build system?

**Comment by Johnex** [comment]
Well like i wrote before the previous version compiled fine, so any changes in the last build broke it. It could be the /RTC1. If you have a fix i can test it :)

**Comment by Majlen** [comment]
You can try the solution in my fork in cmake-improvement branch (which should be the default one). It deletes /RTC1 flag in non-Debug builds when using MSVC.

**Comment by Johnex** [comment]
Just tried it now, im getting this:

```
"D:\_Johnex\Desktop\Libraries\zstd-1.2.0\build\cmake\out32\ALL_BUILD.vcxproj" (default target) (1) ->
"D:\_Johnex\Desktop\Libraries\zstd-1.2.0\build\cmake\out32\programs\unzstd.vcxproj" (default target) (4) ->
"D:\_Johnex\Desktop\Libraries\zstd-1.2.0\build\cmake\out32\programs\zstd.vcxproj" (default target) (5) ->
(Link target) ->
  bench.obj : error LNK2019: unresolved external symbol _XXH64 referenced in function _BMK_benchMem [D:\_Johnex\Desktop
\Libraries\zstd-1.2.0\build\cmake\out32\programs\zstd.vcxproj]
  dibio.obj : error LNK2019: unresolved external symbol _ERR_getErrorString referenced in function _DiB_getErrorName [D
:\_Johnex\Desktop\Libraries\zstd-1.2.0\build\cmake\out32\programs\zstd.vcxproj]
  dibio.obj : error LNK2019: unresolved external symbol _ZDICT_trainFromBuffer_unsafe referenced in function _DiB_train
FromFiles [D:\_Johnex\Desktop\Libraries\zstd-1.2.0\build\cmake\out32\programs\zstd.vcxproj]
  D:\_Johnex\Desktop\Libraries\zstd-1.2.0\build\cmake\out32\programs\Release\zstd.exe : fatal error LNK1120: 3 unresolv
ed externals [D:\_Johnex\Desktop\Libraries\zstd-1.2.0\build\cmake\out32\programs\zstd.vcxproj]

    0 Warning(s)
    4 Error(s)
```

**Comment by codicodi** [comment]
I've hit similar problems. I think the main issue is that in zstd CLI is linked to zstd.dll which does not export said symbols.
Additionally looks like since https://github.com/facebook/zstd/commit/76f04940898bf062ad4504d95fe741c0c784cb24 xxhash symbols are no longer hidden, not sure it this is intended.

**Comment by codicodi** [comment]
I've prepared a patch for this, see #709

**Comment by Johnex** [comment]
I can confirm @codicodi 's patch fixes intel and native compilers 🥇 😀
Thanks 👍
