### ISSUE TITLE
Zstd version for a Frame Magic Number =0xFD2FB526

### ISSUE THREAD

**Issue by gregkwaste** [facebook/zstd#713]
Hi guys, I'm trying to parse some files and I've stumbled upon this magic number on zstd compressed frames. I read the docs where probably the magic number has been updated to 0xFD2FB528, so I suppose that this was used in way older versions of zstd. Can you please help me identify the specific zstd version? because the newer builds I'm using, fail to decompress the stream :/

Thank you

**Comment by mcmilk** [comment]
It's zstd version 0.6
