### ISSUE TITLE
R bindings to the zstandard compression algorithm

### ISSUE THREAD

**Issue by thekvs** [facebook/zstd#714]
Hello!

I wrote R bindings (simple one at this moment) to the zstandard compression library. They are not yet on CRAN as some formal things need to be done in order to be accepted, but I'd like to let you know about them.

It is here: https://github.com/thekvs/zstdr

**Comment by Cyan4973** [comment]
Thanks @thekvs !

Your binding has been added to the list at https://facebook.github.io/zstd/#other-languages
