### ISSUE TITLE
Improve the buildsystem

### ISSUE THREAD

**Issue by asarubbo** [facebook/zstd#715]
At this point, we have multiple choice to what we want to install through zstd, for example: 
thread support, lz4 support, xz support, gzip support, pzstd support and so on.

I guess that the best way to handle those supports is via a build system which provides a script that accepts configure options (autotools-based, cmake, etc).

Yes, I saw there is a cmake support, but it can be improved using a CMakeLists.txt file and have a flag for each thing we want to build or not.

It would also help downstream packagers.
Thanks.

**Comment by asarubbo** [comment]
To explain a bit better:

I'd expect to have a configure, that launched ad ./configure --help prints all support I can enable, so, then I can do:

``` ./configure --enable-lz4 --disable-xz --disable-static ``` 

and not dig into the makefile and analyze dozens of targets

**Comment by Cyan4973** [comment]
That's a good point @asarubbo .
We happily accept PR to improve the `cmake` build script.

**Comment by terrelln** [comment]
I agree that we need a `configure` script. I'll put it on my queue.

**Comment by lzutao** [comment]
@asarubbo Now we have meson build which support configure. Follow instructions in `contrib/meson`.

**Comment by LeeYoung624** [comment]
Hey @asarubbo  @Cyan4973 . 
As @lzutao said, zstd have meson support with these options:
_  Option         Default Value Possible Values           Description                                                           
  ------         ------------- ---------------           -----------                                                           
  backtrace      false         [true, false]             Display a stack backtrace when execution generates a runtime exception
  build_contrib  false         [true, false]             Enable contrib build                                                  
  build_programs true          [true, false]             Enable programs build                                                 
  build_tests    false         [true, false]             Enable tests build                                                    
  debug_level    1             >=0, <=9                  Enable run-time debug. See lib/common/debug.h                         
  legacy_level   5             >=0, <=7                  Support any legacy format: 7 to 1 for v0.7+ to v0.1+                  
  lz4            auto          [enabled, disabled, auto] Enable lz4 support                                                    
  lzma           auto          [enabled, disabled, auto] Enable lzma support                                                   
  multi_thread   enabled       [enabled, disabled, auto] Enable multi-threading when pthread is detected                       
  static_runtime false         [true, false]             Link to static run-time libraries on MSVC                             
  zlib           auto          [enabled, disabled, auto] Enable zlib support_

And I noticed that the build/cmake/CMakeLists.txt already has cmake option for multi thread and something else, and build/cmake/programs/CMakeLists.txt has cmake options for zlib and lzma:
`option(ZSTD_LEGACY_SUPPORT "LEGACY SUPPORT" OFF)
option(ZSTD_BUILD_PROGRAMS "BUILD PROGRAMS" ON)
option(ZSTD_BUILD_CONTRIB "BUILD CONTRIB" OFF)
option(ZSTD_BUILD_TESTS "BUILD TESTS" OFF)
option(ZSTD_MULTITHREAD_SUPPORT "MULTITHREADING SUPPORT" ON)
option(ZSTD_ZLIB_SUPPORT "ZLIB SUPPORT" OFF)
option(ZSTD_LZMA_SUPPORT "LZMA SUPPORT" OFF)`. These cmake options can be listed and configured like
`cmake -LH
cmake -DZSTD_BUILD_TESTS=ON `.

But it seems that the cmake scripts lack LZ4 support option and debug level option support. And the cmake instructions can be provided for guys not familiar with cmake. Maybe I can improve the cmake build scripts

**Comment by Cyan4973** [comment]
Do you want to update the `cmake` script with these additional options ?

**Comment by LeeYoung624** [comment]
Yes. And I want to improve the README.md in build/cmake to give some guides for users not familiar with cmake. Is it OK?

**Comment by Cyan4973** [comment]
Sure !

**Comment by Cyan4973** [comment]
`cmake` script was improved `LeeYoung624`,
but there is still no `./configure` script.
That being said, does the project need one ? for which purpose ?

@terrelln , is that still an opened direction ?
