### ISSUE TITLE
#include <mmintrin.h> breaks compilation on Windows ARM

### ISSUE THREAD

**Issue by GregSlazinski** [facebook/zstd#718]
Trying to compile on Windows ARM (UWP), I get the error:
zstd_decompress.c:
```
#if defined(_MSC_VER)
#  include <mmintrin.h>   /* https://msdn.microsoft.com/fr-fr/library/84szxsww(v=vs.90).aspx */
#  define ZSTD_PREFETCH(ptr)   _mm_prefetch((const char*)ptr, _MM_HINT_T0)

```
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\mmintrin.h(21): fatal error C1189: #error:  This header is specific to X86 and X64 targets

You can't use mmintrin.h on ARM

A quick workaround is to use:
```
#if defined(_MSC_VER) && !defined _M_ARM && !defined _M_ARM64
#  include <mmintrin.h>   /* https://msdn.microsoft.com/fr-fr/library/84szxsww(v=vs.90).aspx */
```

**Comment by Cyan4973** [comment]
Thanks for feedback @GregSlazinski .
Indeed, we haven't tested MS Visual on ARM so far.

Maybe we could make the test even stronger, by allowing `<mmintrin.h>` only on x86/x64 target.

**Comment by mcmilk** [comment]
It should be sth. defined like this:
```c
#if defined(_MSC_VER) && defined(_M_X64 || _M_I86)
#  include <mmintrin.h>
```

Not tested, but sth. like this ... As I currently know, these don't work:
- _M_ARM64
- _M_ARM
- _M_IA64

So it should easier to just add the two which will work...

**Comment by Cyan4973** [comment]
Totally agreed @mcmilk ,
suggested solution pushed to `dev` branch
