### ISSUE TITLE
Please provide Libs.private in the .pc for static link

### ISSUE THREAD

**Issue by yurivict** [facebook/zstd#719]
```pkg-config --static --libs libzstd``` should return the .a library, like this ``/usr/local/lib/libzstd.a```
For this .pc file should contain such line:
```
Libs.private: ${libdir}/libzstd.a
```

**Comment by nmathewson** [comment]
This issue is a blocker for Tor building statically with zstd support; see also https://trac.torproject.org/projects/tor/ticket/22550

**Comment by nmathewson** [comment]
I think the diagnosis above may be incorrect, however.  The Libs.private line is supposed to contain the list of libraries used by the static library, not the library itself.

**Comment by terrelln** [comment]
@nmathewson `libzstd` doesn't have any dependencies by default. There is an option to enable multithreaded compression support, but it isn't enabled by default yet.

**Comment by yurivict** [comment]
It seems from the web search that pkgconfig is broken on the conceptual level, because it doesn't allow static library detection. I didn't realize this when I wrote the OP.

**Comment by Cyan4973** [comment]
Here is what I could gather regarding `Links.private` : 
https://people.freedesktop.org/~dbn/pkg-config-guide.html

> Libs.private: The link flags for _private libraries required by this package but not exposed to applications_.

It seems unrelated to your issue (build statically with zstd).
Maybe we need another solution

**Comment by yurivict** [comment]
> Maybe we need another solution

It doesn't appear that .pc can be fixed for the static build. One option is to have two .pc files: zstd.pc and zstd-static.pc. 

Tor IMO should use autotools instead of pkgconfig in this instance.

**Comment by yurivict** [comment]
I think I misdiagnosed the problem. /usr/local/lib/libzstd.a is stripped when installed from the centrally built package for some reason. This is why tor failed, not because of pkg-config.
