### ISSUE TITLE
pzstd Deadlock on decompression failure

### ISSUE THREAD

**Issue by ghastmask** [facebook/zstd#720]
https://github.com/facebook/zstd/blob/dev/contrib/pzstd/Pzstd.cpp#L96

After line 96 closing block there needs to be a check of the state error holder, and if it is in error the outs WorkQueue needs to be marked finished. Otherwise it will hang on error. This can happen for example if you are writing to stdout and a pipe failure happens, the queue can fill up and deadlock.

**Comment by terrelln** [comment]
Thanks for the report @ghastmask! We'll get a fix in this week, before for the next release.
