### ISSUE TITLE
Does Zstandard compress/decompress has backward compatibility?

### ISSUE THREAD

**Issue by johnlanni** [facebook/zstd#731]
Does low version compressed content can be decompressed by high version ? 
Does high version compressed content can be decompressed by low version ?

**Comment by terrelln** [comment]
zstd's format is stable, starting at version 0.8.1. All zstd versions >= 0.8.1 are forwards and backwards compatible.

zstd has legacy support, enabled by default, that can decode the data produced by zstd versions down to 0.4.0. However very old zstd decompressors, with version < 0.8.1, cannot decode the stable zstd format.
