### ISSUE TITLE
Files with unknown file extensions shouldn't be ignored

### ISSUE THREAD

**Issue by dchest** [facebook/zstd#754]
I tried extracting an archive with `.zstd` extension and got this error:

```
$ zstd -d Mail.zstd
zstd: Mail.zstd: unknown suffix (.gz/.xz/.zst/.lzma/.lz4 expected) -- ignored
```

This is unexpected and unlike most other command-line tools — in my opinion, it's not the program's business to tell me how to name my files, especially since it can tell what kind of file it is by reading the magic string.

PS Thank you for the great file compressor.

**Comment by mcmilk** [comment]
This is the exact the exact `gzip` behavior... so this should be okay.

```bash
[mcmilk@latitude ~/tmp]$ echo 12345 > testing
[mcmilk@latitude ~/tmp]$ cat testing 
12345
[mcmilk@latitude ~/tmp]$ cat testing | gzip > testing.x
[mcmilk@latitude ~/tmp]$ gzip -d testing.x > testing2
gzip: testing.x: unknown suffix -- ignored
[mcmilk@latitude ~/tmp]$ 
```
Nearly the same for `bzip2` ... it's just using some filename it guesses:
```bash
[mcmilk@latitude ~/tmp]$ cat testing|bzip2 > testing.x
[mcmilk@latitude ~/tmp]$ bzip2 -d testing.x > testing2
bzip2: Can't guess original name for testing.x -- using testing.x.out
[mcmilk@latitude ~/tmp]$ cat testing.x.out
12345
```

So this is okay for zstd also. If you want to use such filenames, then just use `zstdcat` - this will work as you want.

**Comment by dchest** [comment]
Ha, interesting, thanks for pointing that out. So for the sake of consistency, I'm closing this.

**Comment by terrelln** [comment]
You can also specify an output file `zstd -d Mail.zstd -o Mail` should work. When the extension isn't `.zst` we don't know how to derive the output file name.

**Comment by stokito** [comment]
Meanwhile tar just don't care about an extension because it don't need to determine output file name since it already knows it. What is interesting is that gzip also save an original file name so it should also work.
Anyway, could you improve the error message and add a note that output file name should be specified?

**Comment by chungy** [comment]
> What is interesting is that gzip also save an original file name so it should also work.

This kind of metadata has largely been considered a misfeature (reduced determinism in output) and isn't present in other compressors like bzip2 or xz.

**Comment by stokito** [comment]
FYI: I reported a bug to gzip https://debbugs.gnu.org/cgi/bugreport.cgi?bug=37336
