### ISSUE TITLE
Windows binary for v1.3.0 request

### ISSUE THREAD

**Issue by jungle-boogie** [facebook/zstd#757]
Hi All,

Would it be possible to have windows binaries built for Windows 1.3.0?

See previous request:
https://github.com/facebook/zstd/issues/445

Thanks!

**Comment by Cyan4973** [comment]
Sure @jungle-boogie !

Windows binaries for v1.3.0 have been added to the [release tab](https://github.com/facebook/zstd/releases/tag/v1.3.0)
