### ISSUE TITLE
can't create ZSTDMT_CCtx if number of cores > 128

### ISSUE THREAD

**Issue by rgdoliveira** [facebook/zstd#760]
I'm compiling zstd in a Powerpc machine (ppc64le) and it builds fine, but when I try to run the test suite it fails with the following error:
"zstd: error 30 : allocation error : can't create ZSTDMT_CCtx"

zstd defines the max number of cores as 128 (ZSTDMT_NBTHREADS_MAX 128) but the Power machine I'm using has 160 cores and the test break.

In this case I guess the execution should continue and use the max number of cores instead of breaking it.

**Comment by Cyan4973** [comment]
That's a good point @rgdoliveira !

**Comment by Cyan4973** [comment]
I modified the version in `dev` branch to accept up to 256 threads.
It will also automatically cap to this new limit when requested more than this value, instead of triggering an error as you experienced.

**Comment by rgdoliveira** [comment]
thanks @Cyan4973, As this issue is fixed in dev branch and I guess it will be part of a future zstd release, I'm closing this issue.
