### ISSUE TITLE
IANA Media Type Registration

### ISSUE THREAD

**Issue by ib** [facebook/zstd#767]
Are there plans to register a media type for zstd and zstd compressed tar archives?

**Comment by ib** [comment]
> Are there plans to register a media type for zstd and zstd compressed tar archives?

At least entries in shared-mime-info (application/x-zstd, application/x-zstd-compressed-tar?) would be desirable.

**Comment by Cyan4973** [comment]
Media type request is ongoing

**Comment by ib** [comment]
> Media type request is ongoing

IANA or shared-mime-info?

**Comment by ib** [comment]
Can you already tell which types are going to be requested?

**Comment by Cyan4973** [comment]
Correction : the media type request has been delayed, it is now planned to be resumed alongside another ongoing normalization effort.

**Comment by ib** [comment]
Please keep us informed.

**Comment by Cyan4973** [comment]
The media type being requested is "to be used when transporting zstd-compressed via Multipurpose Internet Mail Extensions (MIME) ".

I'm not sure to understand the difference between IANA and MIME for this request.

**Comment by ib** [comment]
I'm not sure to understand you.

A Media Type can either be officially requested at [IANA](https://www.iana.org/assignments/media-types/media-types.xhtml) (which shall be requested for addition to [shared-mime-info](https://bugs.freedesktop.org/buglist.cgi?product=shared-mime-info&order=bug_id%20DESC) then) or - unregistered - directly at shared-mime-info. At least application/x-zstd and application/x-zstd-compressed-tar would be desirable there. (See the commits for [lz4](https://cgit.freedesktop.org/xdg/shared-mime-info/commit/?id=62345c56c9e2e582dbe00cc1b19e86930fe00863) and [tar.lz4](https://cgit.freedesktop.org/xdg/shared-mime-info/commit/?id=66d30952d1f768d132375274865f7cc3aa548b01).)

**Comment by Cyan4973** [comment]
I believe it's an official request, so it should be IANA.

**Comment by ib** [comment]
Is there any news?

**Comment by Cyan4973** [comment]
Nothing special.
It's progressing.
The major task here is redacting the content of the RFC, to which the Media Type request will be attached.

**Comment by Cyan4973** [comment]
Process application for `application/zstd` Media Type is formally started : 
https://tools.ietf.org/id/draft-kucherawy-dispatch-zstd-00.html

**Comment by Cyan4973** [comment]
https://www.ietf.org/id/draft-kucherawy-dispatch-zstd-01.txt

**Comment by ib** [comment]
I have no idea how long such an application can take, but it seems there is still no registration, isn't it?

**Comment by Cyan4973** [comment]
cc @mskucherawy

**Comment by mskucherawy** [comment]
There is no registration yet, correct.  It's part of the document @Cyan4973 cited above.  When that document is approved for publication by the IETF, the registrations will be made automatically.

@Cyan4973: IANA is the administrative body that maintains the registries.  MIME is a protocol for encoding arbitrary content type in a content body.  IANA maintains the registry of known media types, to which the MIME specification refers, and the MIME specification defines the rules by which the registry is modified.  We're following the same path as other top-level application media types, which requires a standards action by the IETF.

Use of a media type with an "x-" prefix is discouraged by BCP178 (RFC6648), so we're not pursuing that here.

**Comment by yososs** [comment]
When reading README.md, the extension of Zstd can be read as ".zst", but when looking at draft it is ".zstd". Which will you adopt?

Also, please decide what to do with the extension when combined with tar.

long version   => .tar.zstd or .tar.zst ?
short version => .t?

**Comment by Cyan4973** [comment]
That's a good point @yososs .
I guess it's a typo, as we have been supporting `.zst` only so far.
The 3 letters extension has been preferred to remain compatible with potential filesystems limited to 3 characters filename extension.
It wouldn't be hard for `zstd` cli to support both extensions, 
but the IETF document is more a guidance for the larger ecosystem, and we fear that introducing 2 extensions for all programs to support would be confusing.

> please decide what to do with the extension when combined with tar.

Currently it's `.tar.zst` .
There is no short version defined.

**Comment by ib** [comment]
> I guess it's a typo, as we have been supporting .zst only so far.

I suppose the draft should probably be corrected then, because when it becomes effective (if ever) `zstd` is the official extension which will most certainly cause confusion.

**Comment by yososs** [comment]
Thank you for your quick reply.

In CLI, we can operate with only long version, but if there is no short version there will be problems with GUI application. I think someone needs to decide on a short version.

Specifically, when using the common file save dialog in the GUI application of macOS, when using the long version extension (*. Tar.zst), there is a problem that does not work properly.

Referring to the existing archive file naming rules, tar + zst looks good at **tzs**.

- .tar + .gz => .tgz
- .tar + .bz2 => .tbz
- .tar + .xz => .txz
- .tar + .lzo => .tzo
- .tar + .lz4 => .tlz
- .tar + .sz => .tsz (Tar + Snappy)

**Comment by Cyan4973** [comment]
I'm totally fine with your suggestion @yososs, but I wonder who has the authority to decide a short equivalent extension for `.tar.zst` ?
Maybe the `tar` project directly ?

**Comment by yososs** [comment]
I am a developer of archiver applications that support many codecs.
If this rule determines the extension rule, it will be adopted as my GUI application first.

In the case of UNIX CLI, there is a way to connect with a pipe,
Users can use Tar's implementation without waiting for ZStandard to be integrated.
Tar developers will not decide extensions unless they plan to integrate.

**Comment by Cyan4973** [comment]
https://datatracker.ietf.org/doc/draft-kucherawy-dispatch-zstd/ballot/

**Comment by Cyan4973** [comment]
https://www.iana.org/assignments/media-types/application/zstd

**Comment by Cyan4973** [comment]
Zstandard is now published as [__RFC8478__](https://tools.ietf.org/search/rfc8478 ) .

It is also a fully [registered IANA media type](https://www.iana.org/assignments/media-types/application/zstd).

**Comment by stokito** [comment]
FYI: the `file` utility returns incorrect MIME type `application/x-zstd`. I created a ticket https://bugs.astron.com/view.php?id=103 so hope it will be fixed soon.

`application/x-zstd-compressed-tar` is used internally in KDE Ark, MATE Engrampa, GNOME File Roller, XArchiver for `*.tar.zst` and `*.tzst` files.
