### ISSUE TITLE
Add information about supported formats to cli's output

### ISSUE THREAD

**Issue by ib** [facebook/zstd#771]
This allows parsing the information if necessary and is informative to the user as well.

**Comment by Cyan4973** [comment]
That's a good point @ib,
though, to be complete, we would probably have to mention
when cli supports `.gz` and `.xz` formats too

**Comment by ib** [comment]
> though, to be complete, we would probably have to mention
when cli supports .gz and .xz formats too

This can already easily be parsed and seen from the cli's help output (```--format=```), but a new and compact **Supports:** line would be okay as well.

**Comment by ib** [comment]
Something like this:
```
*** zstd command line interface 32-bits v1.3.0, by Yann Collet
    supporting zstd formats v0.4+, gzip, lzma, xz ***
```
or this:
```
*** zstd command line interface 32-bits v1.3.0, by Yann Collet
*** supporting zstd formats v0.4+, gzip, lzma, xz
```

**Comment by Cyan4973** [comment]
Yes, something like the 2nd example looks great

**Comment by ib** [comment]
Here you are.
[git.am.patch.zip](https://github.com/facebook/zstd/files/1157606/git.am.patch.zip)

**Comment by Cyan4973** [comment]
Thanks @ib, it's pretty good,
though note that `ZSTD_LEGACY_SUPPORT==0` means "no legacy support"

**Comment by ib** [comment]
Oops, missed the header (which btw had no range check so far).
[git.am.patches.zip](https://github.com/facebook/zstd/files/1157625/git.am.patches.zip)

**Comment by ib** [comment]
On top of that some beautification.
[git.am.patch.zip](https://github.com/facebook/zstd/files/1157680/git.am.patch.zip)

**Comment by ib** [comment]
@Cyan4973, are you going to apply this?

**Comment by Cyan4973** [comment]
yes, it's in the list

**Comment by Cyan4973** [comment]
The proposed patch makes `zstdcli.c` dependant on `zstd_legacy.h`.
However, it should be possible to compile `zstdcli.c` without legacy support, hence without availability of `zstd_legacy.h`.

Let's find another way...

**Comment by Cyan4973** [comment]
In your patch, you propose this information to be displayed under `usage_advanced()`, which is triggered by `-h` command. In which case, it also displays additional instructions.

I was considering to trigger it under "verbose Version", which would be triggered by `-vV`. It would basically limit the output to the 2 lines mentioned.
What do you think ?

**Comment by ib** [comment]
`-vV` sounds good to me.

**Comment by ib** [comment]
This should do the job.
[git.am.zip](https://github.com/facebook/zstd/files/1236388/git.am.zip)

**Comment by Cyan4973** [comment]
#806 implements the requested feature, based on your suggested patch.
Branch `displayVersion` can be used to test it.
