### ISSUE TITLE
List command (displayInfo)

### ISSUE THREAD

**Issue by ib** [facebook/zstd#772]
There are two issues with the list command:

1. It only accepts skippable frame magic 0x184D2A50 and reports "not compressed with zstd" for 0x184D2A51 to 0x184D2A5F.
2. Displaying the sizes in MB doesn't make much sense for small files (< 1 MB).

Both issues are easy to fix.

**Comment by Cyan4973** [comment]
Good points @ib !
cc @paulcruz74

**Comment by ib** [comment]
There are more issues:

- If I add two skippable frames (one before a Zstandard frames, one after it) I get:
```
Skippable  Non-Skippable  Compressed  Uncompressed  Ratio  Check  Filename
        1              0     0.00 MB       0.00 MB  0.000   None  test1.zst
```
Shouldn't it be: 2 Skippable, 1 Non-Skippable? Where is the ratio?

- If I add one skippable frame after a Zstandard frame I get:
```
There was an error reading skippable frame sizeAn error occurred with getting file info
Skippable  Non-Skippable  Compressed  Uncompressed  Ratio  Check  Filename
        0              1     0.00 MB       0.00 MB  0.120  XXH64  test2.zst
```

**Comment by ib** [comment]
The (plain) ratio is usually (i.e. by all other compressors I know) defined as `compressedSize/decompressedSize`, not the other way around.

The compressor itself displays `compressedSize/decompressedSize * 100%` as compression result, so the list command should print that as well.

**Comment by ib** [comment]
@paulcruz74, do you have time to look after it or are you busy with other things, in which case I could help out and fix a few things.

**Comment by ib** [comment]
Patches for all bugs mentioned here attached.
[git.am.patches.zip](https://github.com/facebook/zstd/files/1167724/git.am.patches.zip)

**Comment by ib** [comment]
... and on top of the previous four patches a fifth one for output beautification.

[patch.zip](https://github.com/facebook/zstd/files/1169551/patch.zip)

**Comment by ib** [comment]
@Cyan4973, are you going to apply these?

**Comment by Cyan4973** [comment]
Yes,
I'm a bit concentrated on LZ4 right now,
but when I come back to zstd, I'll take care of your patches

**Comment by Cyan4973** [comment]
In latest `dev` branch update, I've updated the `--list` command based on your recommendations and patches.

While doing it, I've spotted another potential error, which still needs to be fixed.
It probably has no impact currently, because it's related to a type of block (rle) which is not generated by existing encoder.
