### ISSUE TITLE
V1.3.0 x64 - Windows binary bug

### ISSUE THREAD

**Issue by sebbellob** [facebook/zstd#780]
Hi !

Today i faced the first bug in V1.3.0 x64 windows binary.
See attached picture : 

![bug](https://user-images.githubusercontent.com/26646406/28821753-010868a4-76b7-11e7-8c79-1359c989c75e.png)

The third try is only a cosmetic bug ?! This POSIX-text thing...

**Comment by terrelln** [comment]
Thanks for the report @sebbellob! Are you able to provide the data the caused the bug?

**Comment by sebbellob** [comment]
Yes ,i can ,but only in private !

**Comment by terrelln** [comment]
You can email me at my username at fb dot com.

**Comment by sebbellob** [comment]
Sent...

**Comment by terrelln** [comment]
I've reproduced the error, working on fixing it now.
