### ISSUE TITLE
Can't get the squashfs functionality working

### ISSUE THREAD

**Issue by escalade** [facebook/zstd#784]
I've tried patching both 4.12.5 and 4.13-rc4. The patches apply cleanly and I've set CONFIG_SQUASHFS_ZSTD=y, CONFIG_XXHASH=y and CONFIG_ZSTD_DECOMPRESS=y.

I've used the squashfs toold from [here](https://github.com/iburinoc/squashfs-tools/commit/acb4c91250218147a060b9b49381c150a2ede8ee), it compiles fine and I've successfully created the squashfs.

When I mount I just get mounting failed input/output error. In dmesg I've spotted this:

`[ 4377.243871] SQUASHFS error: Failed to initialize zstd decompressor
[ 4377.243872] SQUASHFS error: zstd decompression failed, data probably corrupt
[ 4377.243873] SQUASHFS error: squashfs_read_data failed to read block 0x28b3d
[ 4377.243874] SQUASHFS error: Unable to read metadata cache entry [28b3d]
[ 4377.243875] SQUASHFS error: Unable to read inode 0x106709e0
`

I did read that the kernel patches were meant for 4.10, am I wrong to expect them to work on 4.12+ or is it perhaps the squashfs tools that are creating corrupt filesystems?

Any comment is appreciated, and let me know if there's any more info needed.

**Comment by escalade** [comment]
That was fast :)

**Comment by terrelln** [comment]
I've confirmed the fix, thanks again for the report. I'll update the patches here and on the mailing lists. I'll also add the squashfs-tools patch to the zstd repo. The patches are now tested on the master branch, I'll remove that outdated comment about 4.10.
