### ISSUE TITLE
Building zstd-decompress etc.

### ISSUE THREAD

**Issue by svenha** [facebook/zstd#788]
Before release 1.3 (roughly), one could build additional programs (after a successful 'make' in ./) in the directory programs/ . Afterwards I see errors like the following:

> make zstd-decompress
Makefile:206: update target 'zstd-decompress' due to: ../lib/common/fse_decompress.c ../lib/common/entropy_common.c ../lib/common/pool.c ../lib/common/error_private.c ../lib/common/xxhash.c ../lib/common/threading.c ../lib/common/zstd_common.c ../lib/decompress/zstd_decompress.c ../lib/decompress/huf_decompress.c zstdcli.c fileio.c
cc -I../lib -I../lib/common -I../lib/compress -I../lib/dictBuilder -DZSTD_NEWAPI -DXXH_NAMESPACE=ZSTD_    -I../lib/legacy -O3 -Wall -Wextra -Wcast-qual -Wcast-align -Wshadow -Wstrict-aliasing=1 -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wundef -Wpointer-arith -Wformat-security -Wvla -Wformat=2 -Winit-self -Wfloat-equal -Wwrite-strings -Wredundant-decls   -DZSTD_NOBENCH -DZSTD_NODICT -DZSTD_NOCOMPRESS ../lib/common/fse_decompress.c ../lib/common/entropy_common.c ../lib/common/pool.c ../lib/common/error_private.c ../lib/common/xxhash.c ../lib/common/threading.c ../lib/common/zstd_common.c ../lib/decompress/zstd_decompress.c ../lib/decompress/huf_decompress.c zstdcli.c fileio.c -o zstd-decompress
zstdcli.c: In function ‘main’:
zstdcli.c:350:17: warning: variable ‘suffix’ set but not used [-Wunused-but-set-variable]
     const char* suffix = ZSTD_EXTENSION;
                 ^~~~~~
zstdcli.c:338:12: warning: variable ‘blockSize’ set but not used [-Wunused-but-set-variable]
     size_t blockSize = 0;
            ^~~~~~~~~
zstdcli.c:336:9: warning: variable ‘setRealTimePrio’ set but not used [-Wunused-but-set-variable]
         setRealTimePrio = 0;
         ^~~~~~~~~~~~~~~
/tmp/cc5dicfP.o: In function `main':
zstdcli.c:(.text.startup+0x1254): undefined reference to `FIO_listMultipleFiles'
collect2: error: ld returned 1 exit status
Makefile:206: recipe for target 'zstd-decompress' failed

**Comment by Cyan4973** [comment]
To be fixed. 
These warnings look minor and should not prevent binaries from building
(the warnings should also be fixed, of course).
We need improve our CLI to always ensure these versions can still be built without hiccups.

**Comment by Cyan4973** [comment]
In branch [`variants`](https://github.com/facebook/zstd/tree/variants),
the generation of binary variants has been fixed,
it's now also part of regular CI test suite.
