### ISSUE TITLE
possible typo in ZSTD_estimateDStreamSize

### ISSUE THREAD

**Issue by romange** [facebook/zstd#790]
function `ZSTD_estimateDStreamSize` has the following line:
`sizeof(ZSTD_DStream) + ZSTD_estimateDCtxSize() + inBuffSize + outBuffSize` 

`ZSTD_estimateDCtxSize()` return `sizeof(ZSTD_DCtx)` which is equivalent to ` sizeof(ZSTD_DStream)`.
Could it be that ZSTD_estimateDStreamSize counts  `sizeof(ZSTD_DStream)` twice by mistake ?

**Comment by Cyan4973** [comment]
You are right.
In previous versions, a `DStream` was an object which contained a `DCtx`.
But now, `DStream` and `DCtx` are one and the same.
`ZSTD_estimateDCtxSize()` must be updated to reflect this change.

**Comment by romange** [comment]
Should I send the PR ?

**Comment by terrelln** [comment]
@romange That would be very appreciated!

**Comment by Cyan4973** [comment]
Patch merged in `dev` branch
