### ISSUE TITLE
Question about Huffman encoding example in Zstd compression format documentation

### ISSUE THREAD

**Issue by ulikunitz** [facebook/zstd#803]
The excellent compression format documentation contains following example in the section 'Huffman-coded Streams':

> For example, if the literal sequence "0145" was encoded using the prefix codes above,
> it would be encoded as:
> ```
> 00000001 01110000
> ```
> 
> |Symbol  |   5  |   4  |  1 | 0 | Padding |
> |--------|------|------|----|---|---------|
> |Encoding|`0000`|`0001`|`01`|`1`| `10000` |

It appears that the example intends to represent a byte from lowest to highest bit. My understanding is however that the encodings or codes are represented from highest bit to lowest bit and would need to be reversed in the example, which they aren't. In the example it is unclear how the decoder after reading `1` should decode `01` instead of another `1`.

Does it make sense to represent the bytes from highest to lowest bit as the codes? In that case the example encoding will be:
```
00010000 00001101
```
A byte is represented with the highest bit first and it is also obvious that the decoder must read `01` after having read `1`.

**Comment by Cyan4973** [comment]
Yes, you are totally right @ulikunitz .
The documentation should be amended to fix this error.

**Comment by Cyan4973** [comment]
You're suggested documentation fix is in PR #805.
You can review and comment if you wish.

**Comment by ulikunitz** [comment]
I provided a comment on PR #805.
