### ISSUE TITLE
Please rebuild zstd.dll without external dependency 

### ISSUE THREAD

**Issue by dimzon** [facebook/zstd#815]
Запуск программы невозможен, так как на компьютере отсутствует libgcc_s_dw2-1.dll. Попробуйте переустановить программу.

**Comment by Cyan4973** [comment]
I guess it's for the Windows version.
I also guess a `-static` link flag should probably do it.

**Comment by Cyan4973** [comment]
No `zstd.dll` have been produced for latest release of Zstandard. Only the command line utility `zstd.exe` is pre-compiled for Windows.

So, which `zstd.dll` are you talking about ? Do you compile it locally with one of the provided building scripts ?

**Comment by dimzon** [comment]
No, I'm talking about 1.3.0 release

**Comment by Cyan4973** [comment]
Actually, I was considering no longer shipping `zstd.dll` in releases (starting with `v1.3.1`), because it was unclear which kind of use case could benefit from it.

So, that's a good point to check : is there any usage which would benefit from having this Windows dll pre-compiled ? As opposed to, building it from source ?

**Comment by dimzon** [comment]
> is there any usage which would benefit from having this Windows dll pre-compiled ? As opposed to, building it from source ?

Yes, since this library used by not C++ programmers too, someone are too lame to install C++ and deal with it.

**Comment by Cyan4973** [comment]
Could you please test https://ci.appveyor.com/api/buildjobs/tusxiums5vjbyxk6/artifacts/zstd-win-release-x64.zip ?

It's an attempt at building Windows binaries without any runtime dependency.
Since I don't have a Windows machine around shortly, this is a blind fix. I hope it works.

**Comment by Cyan4973** [comment]
Closed, due to lack of feedback

**Comment by dolkensp** [comment]
Hi @Cyan4973 - I just distributed a copy of my app using your DLL to test, and it worked.

I'd previously been having no luck distributing it with a version I'd built myself - it worked on my machine, but no-where else.

Thanks

**Comment by Cyan4973** [comment]
Thanks for feedback @dolkensp !
