### ISSUE TITLE
C# Streaming-only wrapper

### ISSUE THREAD

**Issue by dimzon** [facebook/zstd#824]
this is my contribution
https://gist.github.com/dimzon/4e7f076dd59fa6df2a3207e1fa6ac406

doesn't need other modes except streaming so I doesnt implement them

**Comment by Cyan4973** [comment]
How would you compare it to @skbkontur 's https://github.com/skbkontur/ZstdNet ?

**Comment by dimzon** [comment]
@skbkontur doesn't implement streaming, they just support byte array ti bytearray (de)compression so you need to buffer whole input into memory.
Also my streams are compatible with Zstd.exe

**Comment by Cyan4973** [comment]
Clear ! Do you intend to make your binding a full project, or will it remain a gist ?

**Comment by dimzon** [comment]
I doesn't plan to make separate project containing only Zstd wrapper. Maybe this code will be a part of some LZ4|XZ|ZSTD wrapper collection.
So if you need Zstd-only just take this gist and drop it into you solution. Feel free to change it as you wish, no copyright restrictions.
