### ISSUE TITLE
Docker image for zstd

### ISSUE THREAD

**Issue by vaibhavsood** [facebook/zstd#880]
Hi,

Want to check if there is a docker image/Dockerfile for zstd which is officially supported? I could not find one under dockerhub official images https://hub.docker.com/explore/

If not, want to check if there is any plan to add an official zstd image to dockerhub? https://docs.docker.com/docker-hub/official_repos/#how-do-i-create-a-new-official-repository

**Comment by Cyan4973** [comment]
We haven't planned any docker image.
It seems like a reasonable idea, though the support of someone experienced in this process would be gladly welcomed.

**Comment by gyscos** [comment]
To be clear, you're looking for a docker image that contains a pre-built zstd binary?
If so, here is a dockerfile that generates such an image:

```Dockerfile
# Dockerfile
FROM alpine

RUN apk --no-cache add make gcc libc-dev
COPY . /src
RUN cd /src && make && make install

FROM alpine

RUN mkdir -p /usr/local/share/licenses
COPY --from=0 /usr/local/bin/*zstd* /usr/local/bin/
COPY --from=0 /usr/local/share/man/man1/*zstd* /usr/local/share/man/man1/
COPY --from=0 /src/LICENSE /usr/local/share/licenses/zstd

CMD ["/usr/local/bin/zstd"]
```

**Comment by Cyan4973** [comment]
Would it be useful to host such a script is `/contrib/docker` ?

**Comment by gyscos** [comment]
I suppose. I think the main idea is to use this script to build an image, and then push this image to the official docker hub - ideally people would use this official image rather than create one themselves.

**Comment by Cyan4973** [comment]
maybe calling it `zstd_image` or anything else
would avoid the confusion with the executable name ?

**Comment by gyscos** [comment]
That's true; though the current standard is for images to have directly the name of the binary/service they provide: [mysql](https://hub.docker.com/_/mysql/), [openjdk](https://hub.docker.com/_/openjdk/), ...

As a note, there's an [unofficial lz4 image](https://hub.docker.com/r/sguthrie/lz4/). This one just sets a `CMD` to `bash`, so it needs to be called this way:
```
docker run sguthrie/lz4 lz4 -9
```

**Comment by Cyan4973** [comment]
I've been trying to use the proposed `Dockerfile` by @gyscos to create a docker image.

As a warning, my docker skills are pretty limited, so I'm merely copy/pasting suggested script in a local file called `Dockerfile`. I'm using Ubuntu LTS 16.04 as baseline for this test.

Attempt 1 : 
```
$ docker build -t zstd .
Got permission denied while trying to connect to the Docker daemon socket
```

Attempt 2 : 
```
$ sudo docker build -t zstd .
Sending build context to Docker daemon  2.56 kB
Step 1/9 : FROM alpine as builder
Error parsing reference: "alpine as builder" is not a valid repository/tag: invalid reference format
```

Also : 
> requires docker >= 17.05 

```
$ docker -v
Docker version 1.13.1, build 092cba3
```

Versions do not match, I'm wondering if these numbers are unrelated.

**Comment by mkjaer** [comment]
1.13.1 is the old versioning scheme and is therefore older than 17.05.
Upgrading will allow you to build it.
