### ISSUE TITLE
New .Net wrapper library

### ISSUE THREAD

**Issue by bp74** [facebook/zstd#913]
Hi,

Sorry for opening an issue. This is not an issue but i would like to let you know that there is a new .Net wrapper for ZSTD.  This also refers to an older issue here: https://github.com/facebook/zstd/issues/824

There is already another .Net wrapper (https://github.com/skbkontur/ZstdNet) but this one does not support streaming, which is the default way to do compression in .Net (all other popular compression libraries are using streaming). And there is also a gist that shows how to do a wrapper for the streaming features of ZSTD (https://gist.github.com/dimzon/4e7f076dd59fa6df2a3207e1fa6ac406). I looked at all those implementations and built a new library which supports streaming and dictionaries. This new library is also available on NuGet which is the most popular package manager for .Net developers. 

Since i will use this new library in a big project, it is guaranteed that the new library will be well maintained in the future. To make a long story short, this is the new library:
https://github.com/bp74/Zstandard.Net

Thanks for working so hard on Zstd to make it an awesome compression algorithm!

**Comment by Cyan4973** [comment]
Thanks for the notification,
it's a great new project @bp74 !
