### ISSUE TITLE
Prebuilt binaries for Linux x64

### ISSUE THREAD

**Issue by develar** [facebook/zstd#915]
Could you please provide prebuilt binaries for Linux? Packages are outdated (both 16 and 17 Ubuntu).

Currently, for node or yarn, I use simple scripts like `sudo curl -L https://yarnpkg.com/latest.tar.gz | sudo tar xz -C /usr/local --strip-components=1` in my docker/packer configs.

But for zstd I need to install additional deps and waste time to build it.

**Comment by Cyan4973** [comment]
I'm actually trying to get Ubuntu LTS 16.04 (Xenial) update its zstd package, as it's too old, and uses an incompatible development version : 
https://bugs.launchpad.net/xenial-backports/+bug/1717040

Progresses are slow, unfortunately.
A bit of support for this action might help.

**Comment by Cyan4973** [comment]
packages for Ubuntu have been updated : 
https://bugs.launchpad.net/ubuntu/+source/libzstd/+bug/1717040

Now, Ubuntu LTS 16.04 repository delivers `zstd v1.3.1`.
