### ISSUE TITLE
Build: libraries install to /usr/lib on x86_64

### ISSUE THREAD

**Issue by rworkman** [facebook/zstd#926]
Please consider adding a cmake flag for e.g. -DLIBDIR:STRING="/usr/lib64"

**Comment by Cyan4973** [comment]
patch welcomed !

**Comment by krab** [comment]
Was fixed here https://github.com/facebook/zstd/pull/990 now installs to correct lib64 on x86_64, and directory always can be changed with `-DCMAKE_INSTALL_LIBDIR=my_awesome_64bit_dir` relative to `-DCMAKE_INSTALL_PREFIX=/usr`
