### ISSUE TITLE
InitializeConditionVariable could not located in the dynamic library Kernel32.dll

### ISSUE THREAD

**Issue by s866854** [facebook/zstd#932]
zstd-v1.3.2-win32 with Windows XP

* https://stackoverflow.com/questions/2847960/procedure-entry-point-initializeconditionvariable-could-not-be-located-in-kernel
* https://www.justsoftwaresolutions.co.uk/threading/implementing-a-thread-safe-queue-using-condition-variables.html

**Comment by Cyan4973** [comment]
Sorry, win32 on Windows xp is [no longer supported](https://www.microsoft.com/en-us/windowsforbusiness/end-of-xp-support). 

Moreover I don't have anything around that looks like it and could be used for tests. Plus, it seems making the code work for this environment requires more than tiny adaptations, so this is a pretty bad mix : low outcome, non-negligible complexity, and no way to test it.

Note that I'm not against supporting this target, it's just that the work necessary to make it work will have to come from another source. Either a dedicated fork, or someone willing to push the associated patch upstream.

**Comment by s866854** [comment]
I can test compression/decompression manually when patch comes.

XP is the latest Windows system with lowest (under 100-300mb) memory usage, but it can't be used as primary system

**Comment by jimmyleocn** [comment]
If you still need it, you can check out my forked version. @s866854 
[Zstandard (zstd) - Windows XP Compatibility Fork](https://github.com/jimmyleocn/zstd-winxp)

**Comment by tansy** [comment]
> and no way to test it.

I have slax module with wine that doesn't have it. That could be your environment for testing, if that's of any help.

**Comment by stati64** [comment]
Why not use std::condition_variable?

**Comment by tansy** [comment]
> Why not use std::condition_variable?

Why is zstd written in C, not C++, I wonder...
