### ISSUE TITLE
[Question]Is it ok to use same pointer for context and pre-allocated workspace?

### ISSUE THREAD

**Issue by yinsimei** [facebook/zstd#933]
Hello,
I have a question concerning these APIs for explicit memory management with externally allocated workspace:
`ZSTDLIB_API ZSTD_CCtx* ZSTD_initStaticCCtx(void* workspace, size_t workspaceSize);`
`ZSTDLIB_API ZSTD_DCtx* ZSTD_initStaticDCtx(void* workspace, size_t workspaceSize);`

After a glance at the definition, I think that I can use one void pointer for both context and workspace, since they share the same address. I cast this pointer to ZSTD_compressC(D)Ctx when feeding it to ZSTD_compressC(D)Ctx and free the same pointer at the end of program.

It works for me but I wonder if it is still a safe practice with zstd updates in the future?

Thank you for your time.

**Comment by Cyan4973** [comment]
Yes @yinsimei , it is.

`workspace` is a concept which is not exposed. A normal user should not be aware of it.
From an interface perspective, there is only a `ZSTD_{C,D}Ctx`, which encapsulates whatever is needed for the operation.

**Comment by yinsimei** [comment]
Thanks a lot for your response. That's very clear.

To be more precise about our case is that in our C++ project, we can switch between different algorithms and at present we only preserve one variable for workspace for each algorithm. But for ZSTD, we have two concepts, `ZSTD_{C,D}Ctx` for compression/decompression and `allocatedWorkspaceMemory` for memory allocation/liberation.

So I would like to confirm if it's safe to only keep one single pointer for both of them. As there is no address offset between the two. Or it's better to keep different pointers for them as there may be changes in the future?

Thanks again for your help!

**Comment by Cyan4973** [comment]
I'm not completely sure to understand the question so let's rephrase it.

It seems that `workspace` in your description is a concept at your application level, which would make it completely different from `workspace` as defined inside `ZSTD_{C,D}Ctx`, hence the potential confusion.

If you mean that `app_workspace` is a buffer that your application pre-allocate, and then attribute to `zstd` through `ZSTD_initStatic{C,D}Ctx()`, then indeed, the resulting `ZSTD_{C,D}Ctx*` pointer will have the same address as the buffer.
The main difference is that it will not have the same type.

**Comment by yinsimei** [comment]
Yes, it’s only a buffer we pre-allocate. Thanks a lot for your explanation. This is indeed the answer that I’m looking for. :)
