### ISSUE TITLE
Windows build for version 1.3.3 contains wrong build.

### ISSUE THREAD

**Issue by bp74** [facebook/zstd#962]
Thanks for the new release. I noticed a minor issue ...
The file zstd-v1.3.3-win32.zip contains the 64 bit Windows Dll.
The file zstd-v1.3.3-win64.zip contains the 32 bit Windows Dll.

**Comment by Cyan4973** [comment]
Thanks for notification @bp74 !
Indeed, archive names were mixed up !
This should be fixed now
