### ISSUE TITLE
No documentation on ZSTD_LEGACY_SUPPORT levels

### ISSUE THREAD

**Issue by shawnl** [facebook/zstd#967]
It is not documented anywhere what ZSTD_LEGACY_SUPPORT levels match what released versions.

I assume that 7 matches 0.7, 6 0.6, 5 0.5 et cetera. Any ZSTD_LEGACY_SUPPORT=3 is the default because zstd 0.4 got into Debian/Ubuntu trusty. But I am not sure.

**Comment by Cyan4973** [comment]
It's supposed to be documented here : 
https://github.com/facebook/zstd/tree/dev/programs#compilation-variables
or alternatively : 
https://github.com/facebook/zstd/blob/dev/programs/README.md#compilation-variables
