### ISSUE TITLE
zstd_compress.c Access violation writing location

### ISSUE THREAD

**Issue by kklouzal** [facebook/zstd#971]
I'm getting an intermittent exception while debugging with visual studio pointing me to `zstd_compress.c` line 1790 `pos = 4;` Access violation writing location.

I've rewritten a large portion of my code-base and it's probably an error on my part however any insight into why this would be happening would be greatly appreciated.

You can replicate the error by checking out the [`broken_beyond_repair` branch of my `PeerNet` repository](https://github.com/kklouzal/PeerNet/tree/broken_beyond_repair)

**Comment by Cyan4973** [comment]
Considering the error name "Access violation writing location",
I would suspect the error rather happen on line 1789,
where 4 bytes are written at `dst` location, and the pointer might be invalid.

**Comment by kklouzal** [comment]
That makes more sense. Gives me somewhere to start figuring out what I've broken. Hopefully it's not broken beyond repair.

**Comment by kklouzal** [comment]
After painstakingly sifting through my code, commenting out large blocks until the error disappeared then slowly uncommenting small pieces until the error reappeared, I finally found solace.
**I was corrupting my heap.**
_Whoops!_
