### ISSUE TITLE
zstd.h uses undefined MIN() macro

### ISSUE THREAD

**Issue by indygreg** [facebook/zstd#976]
Starting with version 1.3.2, zstd.h uses `MIN()`, but only if `ZSTD_STATIC_LINKING_ONLY` is defined. `MIN()` may not be defined since it isn't a standard macro in C (there is a definition in `zstd_internal.h`). This can lead to compiler errors.

**Comment by Cyan4973** [comment]
Thanks for notification @indygreg !
This is indeed a mistake, `MIN()` should not be needed in `zstd.h`.
This will be fixed.

**Comment by Cyan4973** [comment]
fix merged into `dev`
